import { STATE_CASE_MODEL, type StateCaseSpec } from "../../_framework/types";
import type { ALoginCaseData } from "./_support/alogin.context";

export const aloginSuccessCase = {
  id: "auth.admin.login",
  title: "管理员可以使用正确邮箱和密码登录 ORF",
  model: STATE_CASE_MODEL,
  tags: ["auth", "login", "admin", "happy-path"],

  data: {
    email: "orf-admin-login-e2e@orf.local",
    password: "OrfAdminLoginE2E!2026",
    name: "ORF Admin Login E2E",
    role: "admin",
  },

  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      {
        source: { caseStepId: "B-1", method: "api" },
        id: "frontend.ready",
        title: "前端服务 应可用",
        object: "frontend.service",
        operator: "available",
      },
      {
        source: { caseStepId: "B-2", method: "api" },
        id: "backend.ready",
        title: "后端服务 应可用",
        object: "api.health",
        operator: "ok",
      },
      {
        source: { caseStepId: "B-3", method: "api" },
        id: "frontend.login_entry.accessible",
        title: "前端登录页入口 应可访问",
        object: "frontend.login_entry",
        operator: "accessible",
      },
      {
        source: { caseStepId: "B-4", method: "api" },
        id: "session.endpoint.accessible",
        title: "当前会话查询能力 应可用",
        object: "auth.session",
        operator: "accessible",
      },
      {
        source: { caseStepId: "B-5", method: "prisma" },
        id: "db.ready",
        title: "ORF 数据库 应可连接",
        object: "db",
        operator: "ready",
      },
      {
        source: { caseStepId: "B-6", method: "prisma" },
        id: "db.schema.current",
        title: "ORF 数据库 schema 应为 当前测试版本",
        object: "db.schema",
        operator: "current",
      },
      {
        source: { caseStepId: "B-7", method: "api" },
        id: "ory.admin_public.ready",
        title: "Ory/Kratos 认证服务的管理和公共访问能力 应可用",
        object: "ory.admin_public",
        operator: "ready",
      },
      {
        source: { caseStepId: "B-8", method: "api" },
        id: "session.unauthenticated",
        title: "当前会话 应为 未登录",
        object: "auth.session",
        operator: "unauthenticated",
      },
      {
        source: { caseStepId: "B-9", method: "playwright" },
        id: "cookie.absent",
        title: "当前浏览器 应不存在 Ory 登录会话 cookie",
        object: "browser.cookie",
        operator: "absent",
      },
      {
        source: { caseStepId: "B-10", method: "playwright" },
        id: "storage.empty",
        title: "当前浏览器 应不保留本地登录态",
        object: "browser.auth_storage",
        operator: "empty",
      },
    ],
  },

  Setup: {
    description: "准备管理员测试账号、清理会话并进入登录页",
    steps: [
      {
        source: { caseStepId: "Setup-1", method: "api" },
        id: "ory.admin_identity.upsert",
        title: "准备邮箱为 `orf-admin-login-e2e@orf.local`、使用固定测试密码的管理员登录身份",
        object: "ory.identity",
        operator: "upsert_password",
        params: {
          emailFrom: "data.email",
          nameFrom: "data.name",
          passwordFrom: "data.password",
          saveAs: "adminIdentity",
        },
      },
      {
        source: { caseStepId: "Setup-2", method: "prisma" },
        id: "db.admin.upsert",
        title: "准备邮箱为 `orf-admin-login-e2e@orf.local`、角色为 `admin`、状态为 `active` 的管理员用户和默认团队成员关系",
        object: "db.user",
        operator: "upsert",
        params: {
          emailFrom: "data.email",
          nameFrom: "data.name",
          roleFrom: "data.role",
          status: "active",
          identityIdFrom: "runtime.adminIdentity.id",
          saveAs: "adminUser",
        },
      },
      {
        source: { caseStepId: "Setup-3", method: "api" },
        id: "ory.sessions.revoke",
        title: "撤销邮箱为 `orf-admin-login-e2e@orf.local` 的管理员登录身份可能残留的登录会话",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Setup-4", method: "playwright" },
        id: "browser.clear",
        title: "移除当前浏览器中的残留登录态",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "Setup-5", method: "playwright" },
        id: "page.goto.auth",
        title: "打开 ORF 登录页",
        object: "page",
        operator: "goto",
        params: { path: "/auth" },
      },
    ],
  },

  S0: {
    description: "登录页可用，管理员账号存在，当前浏览器仍未登录",
    assertions: [
      {
        source: { caseStepId: "S0-1", method: "playwright" },
        id: "url.auth",
        title: "当前页面 应为 登录页",
        object: "page.url",
        operator: "match",
        params: { pattern: "/auth$" },
      },
      {
        source: { caseStepId: "S0-2", method: "playwright" },
        id: "heading.sign_in.visible",
        title: "登录页中 \"Sign in\" 标题 应可见",
        object: "page",
        operator: "visible",
        params: { role: "heading", name: "Sign in" },
      },
      {
        source: { caseStepId: "S0-3", method: "playwright" },
        id: "input.email.visible",
        title: "邮箱输入框 应可见",
        object: "page",
        operator: "visible",
        params: { label: "Email" },
      },
      {
        source: { caseStepId: "S0-4", method: "playwright" },
        id: "input.email.empty",
        title: "邮箱输入框的值 应为空",
        object: "input",
        operator: "value",
        params: { label: "Email", value: "" },
      },
      {
        source: { caseStepId: "S0-5", method: "playwright" },
        id: "input.password.visible",
        title: "密码输入框 应可见",
        object: "page",
        operator: "visible",
        params: { label: "Password", exact: true },
      },
      {
        source: { caseStepId: "S0-6", method: "playwright" },
        id: "input.password.empty",
        title: "密码输入框的值 应为空",
        object: "input",
        operator: "value",
        params: { label: "Password", exact: true, value: "" },
      },
      {
        source: { caseStepId: "S0-7", method: "playwright" },
        id: "button.sign_in.visible",
        title: "登录页的 \"Sign In\" 登录操作 应可见",
        object: "page",
        operator: "visible",
        params: { role: "button", name: "Sign In" },
      },
      {
        source: { caseStepId: "S0-8", method: "playwright" },
        id: "button.sign_in.enabled",
        title: "登录页的 \"Sign In\" 登录操作 应可点击",
        object: "page",
        operator: "enabled",
        params: { role: "button", name: "Sign In" },
      },
      {
        source: { caseStepId: "S0-9", method: "api" },
        id: "session.unauthenticated",
        title: "当前会话 应为 未登录",
        object: "auth.session",
        operator: "unauthenticated",
      },
      {
        source: { caseStepId: "S0-10", method: "playwright" },
        id: "cookie.absent",
        title: "当前浏览器 应不存在 Ory 登录会话 cookie",
        object: "browser.cookie",
        operator: "absent",
      },
      {
        source: { caseStepId: "S0-11", method: "api" },
        id: "ory.admin_identity.exists",
        title: "认证系统中 应存在 邮箱为 `orf-admin-login-e2e@orf.local` 的管理员登录身份",
        object: "ory.identity",
        operator: "exists",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "S0-12", method: "api" },
        id: "ory.admin_identity.password_available",
        title: "邮箱为 `orf-admin-login-e2e@orf.local` 的管理员登录身份的密码凭据 应可用",
        object: "ory.identity",
        operator: "password_available",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "S0-13", method: "prisma" },
        id: "db.admin.matches",
        title: "ORF 业务系统中 应存在 邮箱为 `orf-admin-login-e2e@orf.local`、角色为 `admin`、状态为 `active` 的管理员用户",
        object: "db.user",
        operator: "matches",
        params: {
          emailFrom: "data.email",
          roleFrom: "data.role",
          status: "active",
        },
      },
    ],
  },

  Action: {
    description: "输入管理员测试邮箱和密码并提交登录表单",
    steps: [
      {
        source: { caseStepId: "Action-1", method: "playwright" },
        id: "fill.email",
        title: "在邮箱输入框输入 `orf-admin-login-e2e@orf.local`",
        object: "page",
        operator: "fill",
        params: {
          label: "Email",
          valueFrom: "data.email",
        },
      },
      {
        source: { caseStepId: "Action-2", method: "playwright" },
        id: "fill.password",
        title: "在密码输入框输入管理员固定测试密码",
        object: "page",
        operator: "fill",
        params: {
          label: "Password",
          exact: true,
          valueFrom: "data.password",
        },
      },
      {
        source: { caseStepId: "Action-3", method: "playwright" },
        id: "click.sign_in",
        title: "点击 \"Sign In\" 登录操作",
        object: "page.login_form",
        operator: "submit",
        params: {
          saveAs: "loginResponse",
        },
      },
    ],
  },

  S1: {
    description: "页面进入管理员登录后状态，后端 session 有效",
    assertions: [
      {
        source: { caseStepId: "S1-1", method: "api" },
        id: "login_response.ok",
        title: "登录结果 应成功",
        object: "api.response",
        operator: "ok",
        params: {
          responseFrom: "runtime.loginResponse",
          status: 200,
        },
      },
      {
        source: { caseStepId: "S1-2", method: "playwright" },
        id: "url.bounties",
        title: "当前页面 应为 悬赏大厅",
        object: "page.url",
        operator: "match",
        params: { pattern: "/bounties$" },
      },
      {
        source: { caseStepId: "S1-3", method: "playwright" },
        id: "cookie.present",
        title: "当前浏览器 应存在 Ory 登录会话 cookie",
        object: "browser.cookie",
        operator: "present",
      },
      {
        source: { caseStepId: "S1-4", method: "api" },
        id: "session.authenticated",
        title: "当前会话 应为 邮箱为 `orf-admin-login-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话",
        object: "auth.session",
        operator: "authenticated",
        params: {
          emailFrom: "data.email",
          roleFrom: "data.role",
          status: "active",
        },
      },
      {
        source: { caseStepId: "S1-5", method: "playwright" },
        id: "nav.visible",
        title: "登录后主导航 应可见",
        object: "page",
        operator: "visible",
        params: { label: "主导航" },
      },
      {
        source: { caseStepId: "S1-6", method: "playwright" },
        id: "user_menu.visible",
        title: "登录后用户菜单 应可见",
        object: "page",
        operator: "visible",
        params: { label: "用户菜单" },
      },
      {
        source: { caseStepId: "S1-7", method: "playwright" },
        id: "logout.visible",
        title: "登录后的 \"退出登录\" 操作 应可见",
        object: "page",
        operator: "visible",
        params: {
          role: "button",
          name: "退出登录",
        },
      },
      {
        source: { caseStepId: "S1-8", method: "playwright" },
        id: "members.nav.visible",
        title: "登录后的管理员入口 \"成员管理\" 应可见",
        object: "page",
        operator: "visible",
        params: { label: "系统管理" },
      },
      {
        source: { caseStepId: "S1-9", method: "playwright" },
        id: "permissions.nav.visible",
        title: "登录后的管理员入口 \"权限管理\" 应可见",
        object: "page",
        operator: "count",
        params: { text: "权限管理", count: 0 },
      },
      {
        source: { caseStepId: "S1-10", method: "playwright" },
        id: "sign_in.absent",
        title: "当前页面中的 \"Sign In\" 登录操作 应不存在",
        object: "page",
        operator: "count",
        params: {
          role: "button",
          name: "Sign In",
          count: 0,
        },
      },
      {
        source: { caseStepId: "S1-11", method: "prisma" },
        id: "db.admin.matches",
        title: "ORF 业务系统中 应仍存在 邮箱为 `orf-admin-login-e2e@orf.local` 的管理员用户和 `admin` 成员关系",
        object: "db.user",
        operator: "matches",
        params: {
          emailFrom: "data.email",
          roleFrom: "data.role",
          status: "active",
        },
      },
    ],
  },

  Clean: {
    description: "登出并删除管理员登录测试独占 fixture",
    steps: [
      {
        source: { caseStepId: "Clean-1", method: "api" },
        id: "auth.logout",
        title: "注销当前登录会话",
        object: "auth",
        operator: "logout",
      },
      {
        source: { caseStepId: "Clean-2", method: "playwright" },
        id: "page.runtime.stop",
        title: "离开当前 ORF 前端页面",
        object: "page.runtime",
        operator: "stop",
      },
      {
        source: { caseStepId: "Clean-3", method: "playwright" },
        id: "browser.clear",
        title: "移除当前浏览器中的残留登录态",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "Clean-4", method: "api" },
        id: "ory.sessions.revoke",
        title: "撤销邮箱为 `orf-admin-login-e2e@orf.local` 的管理员登录身份的残留登录会话",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-5", method: "api" },
        id: "ory.admin_identity.delete",
        title: "删除邮箱为 `orf-admin-login-e2e@orf.local` 的管理员登录身份",
        object: "ory.identity",
        operator: "delete_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-6", method: "prisma" },
        id: "db.admin.memberships.delete",
        title: "删除邮箱为 `orf-admin-login-e2e@orf.local` 的管理员用户的默认团队成员关系",
        object: "db.user",
        operator: "delete_memberships",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-7", method: "prisma" },
        id: "db.admin.delete",
        title: "删除邮箱为 `orf-admin-login-e2e@orf.local` 的管理员用户",
        object: "db.user",
        operator: "delete",
        params: { emailFrom: "data.email" },
      },
    ],
  },
} satisfies StateCaseSpec<ALoginCaseData>;
