import { STATE_CASE_MODEL, type StateCaseSpec } from "../../_framework/types";
import type { RecruitMemberCaseData } from "./_support/recruit-member.context";

export const recruitMemberCase = {
  id: "bounties.recruit-member",
  title: "管理员征召成员执行目标",
  model: STATE_CASE_MODEL,
  tags: ["bounties", "recruitment", "admin", "member", "happy-path"],

  data: {
    email: "orf-admin-recruit-member-e2e@orf.local",
    password: "OrfAdminRecruitMemberE2E!2026",
    name: "ORF Admin Recruit Member E2E",
    role: "admin",
    memberEmail: "orf-member-recruit-member-e2e@orf.local",
    memberPassword: "OrfMemberRecruitMemberE2E!2026",
    memberName: "ORF Member Recruit Member E2E",
    memberRole: "member",
    objectiveId: "obj-testd-recruit-member",
    objectiveTitle: "E2E-RECRUIT-MEMBER: 管理员征召成员执行目标",
  },

  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      {
        source: { caseStepId: "B-1", method: "api" },
        id: "frontend.ready",
        title: "前端服务 应可用",
        object: "frontend.service",
        operator: "available",
      },
      {
        source: { caseStepId: "B-2", method: "api" },
        id: "backend.ready",
        title: "后端服务 应可用",
        object: "api.health",
        operator: "ok",
      },
      {
        source: { caseStepId: "B-3", method: "api" },
        id: "frontend.login_entry.accessible",
        title: "前端登录页入口 应可访问",
        object: "frontend.login_entry",
        operator: "accessible",
      },
      {
        source: { caseStepId: "B-4", method: "api" },
        id: "session.endpoint.accessible",
        title: "当前会话查询能力 应可用",
        object: "auth.session",
        operator: "accessible",
      },
      {
        source: { caseStepId: "B-5", method: "prisma" },
        id: "db.ready",
        title: "ORF 数据库 应可连接",
        object: "db",
        operator: "ready",
      },
      {
        source: { caseStepId: "B-6", method: "prisma" },
        id: "db.schema.current",
        title: "ORF 数据库 schema 应为 当前测试版本",
        object: "db.schema",
        operator: "current",
      },
      {
        source: { caseStepId: "B-7", method: "api" },
        id: "ory.admin_public.ready",
        title: "Ory/Kratos 认证服务的管理和公共访问能力 应可用",
        object: "ory.admin_public",
        operator: "ready",
      },
      {
        source: { caseStepId: "B-8", method: "api" },
        id: "session.unauthenticated",
        title: "当前会话 应为 未登录",
        object: "auth.session",
        operator: "unauthenticated",
      },
      {
        source: { caseStepId: "B-9", method: "playwright" },
        id: "cookie.absent",
        title: "当前浏览器 应不存在 Ory 登录会话 cookie",
        object: "browser.cookie",
        operator: "absent",
      },
      {
        source: { caseStepId: "B-10", method: "playwright" },
        id: "storage.empty",
        title: "当前浏览器 应不保留本地登录态",
        object: "browser.auth_storage",
        operator: "empty",
      },
    ],
  },

  Setup: {
    description: "准备管理员、普通成员和本用例独占可征召目标，登录管理员并进入挑战工作台",
    steps: [
      {
        source: { caseStepId: "Setup-1", method: "prisma" },
        id: "db.objective.delete_residue",
        title: "删除可能残留的本用例可征召目标及其派生数据",
        object: "db.objective",
        operator: "delete_by_title",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Setup-2", method: "api" },
        id: "ory.admin_identity.upsert",
        title: "准备邮箱为 `orf-admin-recruit-member-e2e@orf.local`、使用固定测试密码的管理员登录身份",
        object: "ory.identity",
        operator: "upsert_password",
        params: {
          emailFrom: "data.email",
          nameFrom: "data.name",
          passwordFrom: "data.password",
          saveAs: "adminIdentity",
        },
      },
      {
        source: { caseStepId: "Setup-3", method: "prisma" },
        id: "db.admin_user_record.upsert",
        title: "准备邮箱为 `orf-admin-recruit-member-e2e@orf.local`、状态为 `active` 的管理员用户记录",
        object: "db.user_record",
        operator: "upsert",
        params: {
          emailFrom: "data.email",
          nameFrom: "data.name",
          status: "active",
          identityIdFrom: "runtime.adminIdentity.id",
          saveAs: "adminUserRecord",
        },
      },
      {
        source: { caseStepId: "Setup-4", method: "prisma" },
        id: "db.admin_membership.upsert",
        title: "准备邮箱为 `orf-admin-recruit-member-e2e@orf.local` 的管理员用户默认团队成员关系，角色为 `admin`",
        object: "db.default_team_membership",
        operator: "upsert",
        params: {
          emailFrom: "data.email",
          roleFrom: "data.role",
          saveAs: "adminUser",
        },
      },
      {
        source: { caseStepId: "Setup-5", method: "api" },
        id: "ory.member_identity.upsert",
        title: "准备邮箱为 `orf-member-recruit-member-e2e@orf.local`、使用固定测试密码的普通成员登录身份",
        object: "ory.identity",
        operator: "upsert_password",
        params: {
          emailFrom: "data.memberEmail",
          nameFrom: "data.memberName",
          passwordFrom: "data.memberPassword",
          saveAs: "memberIdentity",
        },
      },
      {
        source: { caseStepId: "Setup-6", method: "prisma" },
        id: "db.member_user_record.upsert",
        title: "准备邮箱为 `orf-member-recruit-member-e2e@orf.local`、状态为 `active` 的普通成员用户记录",
        object: "db.user_record",
        operator: "upsert",
        params: {
          emailFrom: "data.memberEmail",
          nameFrom: "data.memberName",
          status: "active",
          identityIdFrom: "runtime.memberIdentity.id",
          saveAs: "memberUserRecord",
        },
      },
      {
        source: { caseStepId: "Setup-7", method: "prisma" },
        id: "db.member_membership.upsert",
        title: "准备邮箱为 `orf-member-recruit-member-e2e@orf.local` 的普通成员用户默认团队成员关系，角色为 `member`",
        object: "db.default_team_membership",
        operator: "upsert",
        params: {
          emailFrom: "data.memberEmail",
          roleFrom: "data.memberRole",
          saveAs: "memberUser",
        },
      },
      {
        source: { caseStepId: "Setup-8", method: "prisma" },
        id: "db.objective.upsert_recruitable",
        title: "创建标题为 `E2E-RECRUIT-MEMBER: 管理员征召成员执行目标`、流转状态为 `open`、阶段为 `resultClaiming`、最终截止日期晚于当前测试日期的本用例可征召目标",
        object: "db.objective",
        operator: "upsert",
        params: {
          idFrom: "data.objectiveId",
          titleFrom: "data.objectiveTitle",
          teamIdFrom: "runtime.adminUser.teamId",
          stage: "resultClaiming",
          flowStatus: "open",
          status: "Draft",
          finalDueAt: "2026-12-31",
          createdByFrom: "runtime.adminUser.userId",
          updatedByFrom: "runtime.adminUser.userId",
          saveAs: "fixtureObjective",
        },
      },
      {
        source: { caseStepId: "Setup-9", method: "prisma" },
        id: "db.recruit_target.challengers_empty",
        title: "本用例可征召目标的挑战者集合 应为空",
        object: "db.recruit_target",
        operator: "challengers_empty",
        params: { targetFrom: "runtime.fixtureObjective" },
      },
      {
        source: { caseStepId: "Setup-10", method: "prisma" },
        id: "db.recruit_target.assigned_empty",
        title: "本用例可征召目标的待响应征召集合 应为空",
        object: "db.recruit_target",
        operator: "assigned_empty",
        params: { targetFrom: "runtime.fixtureObjective" },
      },
      {
        source: { caseStepId: "Setup-11", method: "prisma" },
        id: "db.recruit_target.applications_empty",
        title: "本用例可征召目标的挑战申请集合 应为空",
        object: "db.recruit_target",
        operator: "applications_empty",
        params: { targetFrom: "runtime.fixtureObjective" },
      },
      {
        source: { caseStepId: "Setup-12", method: "api" },
        id: "ory.admin_sessions.revoke",
        title: "撤销管理员登录身份可能残留的登录会话",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Setup-13", method: "api" },
        id: "ory.member_sessions.revoke",
        title: "撤销普通成员登录身份可能残留的登录会话",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.memberEmail" },
      },
      {
        source: { caseStepId: "Setup-14", method: "playwright" },
        id: "browser.clear",
        title: "移除当前浏览器中的残留登录态",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "Setup-15", method: "playwright" },
        id: "page.goto.auth",
        title: "打开 ORF 登录页",
        object: "page",
        operator: "goto",
        params: { path: "/auth" },
      },
      {
        source: { caseStepId: "Setup-16", method: "playwright" },
        id: "fill.admin_email",
        title: "在邮箱输入框输入管理员固定测试邮箱",
        object: "page",
        operator: "fill",
        params: { label: "Email", valueFrom: "data.email" },
      },
      {
        source: { caseStepId: "Setup-17", method: "playwright" },
        id: "fill.admin_password",
        title: "在密码输入框输入管理员固定测试密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.password" },
      },
      {
        source: { caseStepId: "Setup-18", method: "playwright" },
        id: "click.sign_in",
        title: "点击 \"Sign In\" 登录操作",
        object: "page",
        operator: "click",
        params: { role: "button", name: "Sign In" },
      },
      {
        source: { caseStepId: "Setup-19", method: "api" },
        id: "session.admin.authenticated",
        title: "当前会话 应为 已登录",
        object: "auth.session",
        operator: "authenticated",
      },
      {
        source: { caseStepId: "Setup-20", method: "api" },
        id: "session.admin.email",
        title: "当前会话用户邮箱 应为 `orf-admin-recruit-member-e2e@orf.local`",
        object: "auth.session.user_email",
        operator: "equals",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Setup-21", method: "api" },
        id: "session.admin.role",
        title: "当前会话用户角色 应为 `admin`",
        object: "auth.session.user_role",
        operator: "equals",
        params: { roleFrom: "data.role" },
      },
      {
        source: { caseStepId: "Setup-22", method: "api" },
        id: "session.admin.status",
        title: "当前会话用户状态 应为 `active`",
        object: "auth.session.user_status",
        operator: "equals",
        params: { status: "active" },
      },
      {
        source: { caseStepId: "Setup-23", method: "playwright" },
        id: "page.goto.tasks",
        title: "打开 挑战工作台",
        object: "page",
        operator: "goto",
        params: { path: "/tasks" },
      },
      {
        source: { caseStepId: "Setup-24", method: "playwright" },
        id: "scope.all",
        title: "切换到 \"所有挑战\" 视图",
        object: "page",
        operator: "click",
        params: { role: "button", name: "所有挑战" },
      },
      {
        source: { caseStepId: "Setup-25", method: "api" },
        id: "api.workbench.read_all",
        title: "读取 管理员挑战工作台数据",
        object: "api.my_challenges",
        operator: "read_all",
        params: { saveAs: "adminWorkbenchBefore" },
      },
    ],
  },

  S0: {
    description: "管理员已登录并位于挑战工作台，本用例目标可征召且目标尚无挑战者、征召和申请",
    assertions: [
      {
        source: { caseStepId: "S0-1", method: "api" },
        id: "session.admin.authenticated",
        title: "当前会话 应为 已登录",
        object: "auth.session",
        operator: "authenticated",
      },
      {
        source: { caseStepId: "S0-2", method: "api" },
        id: "session.admin.email",
        title: "当前会话用户邮箱 应为 `orf-admin-recruit-member-e2e@orf.local`",
        object: "auth.session.user_email",
        operator: "equals",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "S0-3", method: "api" },
        id: "session.admin.role",
        title: "当前会话用户角色 应为 `admin`",
        object: "auth.session.user_role",
        operator: "equals",
        params: { roleFrom: "data.role" },
      },
      {
        source: { caseStepId: "S0-4", method: "api" },
        id: "session.admin.status",
        title: "当前会话用户状态 应为 `active`",
        object: "auth.session.user_status",
        operator: "equals",
        params: { status: "active" },
      },
      {
        source: { caseStepId: "S0-5", method: "playwright" },
        id: "url.tasks",
        title: "当前页面 应为 挑战工作台",
        object: "page.url",
        operator: "match",
        params: { pattern: "/tasks$" },
      },
      {
        source: { caseStepId: "S0-6", method: "playwright" },
        id: "scope.all.enabled",
        title: "\"所有挑战\" 视图 应可用",
        object: "page",
        operator: "enabled",
        params: { role: "button", name: "所有挑战" },
      },
      {
        source: { caseStepId: "S0-7", method: "api" },
        id: "api.workbench.objective_present",
        title: "管理员挑战工作台数据 应包含 本用例可征召目标",
        object: "api.my_challenges",
        operator: "objective_present_all",
        params: { targetFrom: "runtime.fixtureObjective" },
      },
      {
        source: { caseStepId: "S0-8", method: "playwright" },
        id: "recruit_target.visible",
        title: "本用例可征召目标面板 应可见",
        object: "page.recruit_target",
        operator: "visible",
        params: { targetFrom: "runtime.fixtureObjective" },
      },
      {
        source: { caseStepId: "S0-9", method: "playwright" },
        id: "recruit_target.recruit_visible",
        title: "本用例可征召目标的 \"征召\" 操作 应可见",
        object: "page.recruit_target",
        operator: "recruit_visible",
        params: { targetFrom: "runtime.fixtureObjective" },
      },
      {
        source: { caseStepId: "S0-10", method: "playwright" },
        id: "recruit_target.recruit_enabled",
        title: "本用例可征召目标的 \"征召\" 操作 应可点击",
        object: "page.recruit_target",
        operator: "recruit_enabled",
        params: { targetFrom: "runtime.fixtureObjective" },
      },
      {
        source: { caseStepId: "S0-11", method: "prisma" },
        id: "db.recruit_target.open",
        title: "本用例可征召目标的流转状态 应为 `open`",
        object: "db.recruit_target",
        operator: "flow_status",
        params: { targetFrom: "runtime.fixtureObjective", status: "open" },
      },
      {
        source: { caseStepId: "S0-12", method: "prisma" },
        id: "db.recruit_target.result_claiming",
        title: "本用例可征召目标的阶段 应为 `resultClaiming`",
        object: "db.recruit_target",
        operator: "stage",
        params: { targetFrom: "runtime.fixtureObjective", stage: "resultClaiming" },
      },
      {
        source: { caseStepId: "S0-13", method: "prisma" },
        id: "db.recruit_target.challengers_empty",
        title: "本用例可征召目标的挑战者集合 应为空",
        object: "db.recruit_target",
        operator: "challengers_empty",
        params: { targetFrom: "runtime.fixtureObjective" },
      },
      {
        source: { caseStepId: "S0-14", method: "prisma" },
        id: "db.recruit_target.assigned_empty",
        title: "本用例可征召目标的待响应征召集合 应为空",
        object: "db.recruit_target",
        operator: "assigned_empty",
        params: { targetFrom: "runtime.fixtureObjective" },
      },
      {
        source: { caseStepId: "S0-15", method: "prisma" },
        id: "db.recruit_target.applications_empty",
        title: "本用例可征召目标的挑战申请集合 应为空",
        object: "db.recruit_target",
        operator: "applications_empty",
        params: { targetFrom: "runtime.fixtureObjective" },
      },
      {
        source: { caseStepId: "S0-16", method: "prisma" },
        id: "db.member.active",
        title: "邮箱为 `orf-member-recruit-member-e2e@orf.local` 的普通成员用户 应为 `active`",
        object: "db.member_user",
        operator: "active",
        params: { emailFrom: "data.memberEmail" },
      },
    ],
  },

  Action: {
    description: "管理员征召普通成员，普通成员随后登录悬赏大厅并接受挑战",
    steps: [
      {
        source: { caseStepId: "Action-1", method: "api" },
        id: "capture.recruitment_response",
        title: "监听征召成员请求响应",
        object: "api.recruitment",
        operator: "capture_response",
        params: { targetFrom: "runtime.fixtureObjective", saveAs: "recruitmentResponse" },
      },
      {
        source: { caseStepId: "Action-2", method: "playwright" },
        id: "recruit_target.recruit",
        title: "点击 本用例可征召目标的 \"征召\" 操作",
        object: "page.recruit_target",
        operator: "recruit",
        params: { targetFrom: "runtime.fixtureObjective" },
      },
      {
        source: { caseStepId: "Action-3", method: "playwright" },
        id: "recruit_dialog.visible",
        title: "\"征召挑战者\" 弹窗 应可见",
        object: "page.recruit_dialog",
        operator: "visible",
      },
      {
        source: { caseStepId: "Action-4", method: "playwright" },
        id: "recruit_dialog.target_visible",
        title: "\"征召挑战者\" 弹窗 应显示 本用例可征召目标",
        object: "page.recruit_dialog",
        operator: "target_visible",
        params: { targetFrom: "runtime.fixtureObjective" },
      },
      {
        source: { caseStepId: "Action-5", method: "playwright" },
        id: "recruit_dialog.member_visible",
        title: "\"征召挑战者\" 弹窗 应显示 \"ORF Member Recruit Member E2E\" 可征召成员",
        object: "page.recruit_dialog",
        operator: "member_visible",
        params: { memberNameFrom: "data.memberName" },
      },
      {
        source: { caseStepId: "Action-6", method: "playwright" },
        id: "recruit_dialog.select_member",
        title: "选择 \"ORF Member Recruit Member E2E\" 可征召成员",
        object: "page.recruit_dialog",
        operator: "select_member",
        params: { memberNameFrom: "data.memberName" },
      },
      {
        source: { caseStepId: "Action-7", method: "playwright" },
        id: "recruit_dialog.submit",
        title: "点击 \"发送征召\" 操作",
        object: "page.recruit_dialog",
        operator: "submit",
      },
      {
        source: { caseStepId: "Action-8", method: "api" },
        id: "recruitment_response.record",
        title: "征召成员结果 应成功，并记录响应中的目标作为 征召后的目标",
        object: "api.recruitment",
        operator: "record_objective",
        params: { responseFrom: "runtime.recruitmentResponse", saveAs: "recruitedObjective" },
      },
      {
        source: { caseStepId: "Action-9", method: "api" },
        id: "auth.logout_admin",
        title: "注销当前管理员登录会话",
        object: "auth",
        operator: "logout",
      },
      {
        source: { caseStepId: "Action-10", method: "playwright" },
        id: "browser.clear",
        title: "移除当前浏览器中的残留登录态",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "Action-11", method: "playwright" },
        id: "page.goto.auth",
        title: "打开 ORF 登录页",
        object: "page",
        operator: "goto",
        params: { path: "/auth" },
      },
      {
        source: { caseStepId: "Action-12", method: "playwright" },
        id: "fill.member_email",
        title: "在邮箱输入框输入普通成员固定测试邮箱",
        object: "page",
        operator: "fill",
        params: { label: "Email", valueFrom: "data.memberEmail" },
      },
      {
        source: { caseStepId: "Action-13", method: "playwright" },
        id: "fill.member_password",
        title: "在密码输入框输入普通成员固定测试密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.memberPassword" },
      },
      {
        source: { caseStepId: "Action-14", method: "playwright" },
        id: "click.sign_in_member",
        title: "点击 \"Sign In\" 登录操作",
        object: "page",
        operator: "click",
        params: { role: "button", name: "Sign In" },
      },
      {
        source: { caseStepId: "Action-15", method: "api" },
        id: "session.member.authenticated",
        title: "当前会话 应为 已登录",
        object: "auth.session",
        operator: "authenticated",
      },
      {
        source: { caseStepId: "Action-16", method: "api" },
        id: "session.member.email",
        title: "当前会话用户邮箱 应为 `orf-member-recruit-member-e2e@orf.local`",
        object: "auth.session.user_email",
        operator: "equals",
        params: { emailFrom: "data.memberEmail" },
      },
      {
        source: { caseStepId: "Action-17", method: "api" },
        id: "session.member.role",
        title: "当前会话用户角色 应为 `member`",
        object: "auth.session.user_role",
        operator: "equals",
        params: { roleFrom: "data.memberRole" },
      },
      {
        source: { caseStepId: "Action-18", method: "api" },
        id: "session.member.status",
        title: "当前会话用户状态 应为 `active`",
        object: "auth.session.user_status",
        operator: "equals",
        params: { status: "active" },
      },
      {
        source: { caseStepId: "Action-19", method: "playwright" },
        id: "page.goto.bounties",
        title: "打开 悬赏大厅",
        object: "page",
        operator: "goto",
        params: { path: "/bounties" },
      },
      {
        source: { caseStepId: "Action-20", method: "api" },
        id: "api.bounties.read",
        title: "读取 普通成员视角的悬赏大厅数据",
        object: "api.bounties",
        operator: "read",
        params: { saveAs: "memberBountiesBeforeAccept" },
      },
      {
        source: { caseStepId: "Action-21", method: "api" },
        id: "api.bounties.recruitment_present",
        title: "普通成员视角的悬赏大厅数据 应包含 本用例可征召目标作为 待接受征召",
        object: "api.bounties",
        operator: "recruitment_present",
        params: { targetFrom: "runtime.recruitedObjective" },
      },
      {
        source: { caseStepId: "Action-22", method: "api" },
        id: "capture.challenge_acceptance_response",
        title: "监听接受挑战请求响应",
        object: "api.challenge_acceptance",
        operator: "capture_response",
        params: { targetFrom: "runtime.recruitedObjective", saveAs: "acceptanceResponse" },
      },
      {
        source: { caseStepId: "Action-23", method: "playwright" },
        id: "bounty_recruitment_row.accept",
        title: "点击 本用例可征召目标的 \"接受挑战\" 操作",
        object: "page.bounty_recruitment_row",
        operator: "accept",
        params: { targetFrom: "runtime.recruitedObjective" },
      },
      {
        source: { caseStepId: "Action-24", method: "playwright" },
        id: "challenge_accept_dialog.visible",
        title: "接受挑战确认弹窗 应显示 \"接受后会进入你的挑战页\"",
        object: "page.challenge_accept_dialog",
        operator: "visible",
      },
      {
        source: { caseStepId: "Action-25", method: "playwright" },
        id: "challenge_accept_dialog.confirm",
        title: "点击 接受挑战确认弹窗中的 \"接受挑战\" 操作",
        object: "page.challenge_accept_dialog",
        operator: "confirm",
      },
      {
        source: { caseStepId: "Action-26", method: "api" },
        id: "acceptance_response.record",
        title: "接受挑战结果 应成功，并记录响应中的目标作为 接受后的目标",
        object: "api.challenge_acceptance",
        operator: "record_objective",
        params: { responseFrom: "runtime.acceptanceResponse", saveAs: "acceptedObjective" },
      },
    ],
  },

  S1: {
    description: "成员已接受征召，目标进入重估阶段并出现在普通成员挑战工作台",
    assertions: [
      {
        source: { caseStepId: "S1-1", method: "api" },
        id: "recruited_objective.same_id",
        title: "征召后的目标 应与 本用例可征召目标 ID 相同",
        object: "api.recruit_target",
        operator: "same_id",
        params: { actualFrom: "runtime.recruitedObjective", expectedFrom: "runtime.fixtureObjective" },
      },
      {
        source: { caseStepId: "S1-2", method: "api" },
        id: "recruited_objective.recruiting",
        title: "征召后的目标的流转状态 应为 `recruiting`",
        object: "api.recruit_target",
        operator: "flow_status",
        params: { targetFrom: "runtime.recruitedObjective", status: "recruiting" },
      },
      {
        source: { caseStepId: "S1-3", method: "api" },
        id: "recruited_objective.assigned_contains",
        title: "征召后的目标的待响应征召集合 应包含 \"ORF Member Recruit Member E2E\"",
        object: "api.recruit_target",
        operator: "assigned_contains",
        params: { targetFrom: "runtime.recruitedObjective", memberNameFrom: "data.memberName" },
      },
      {
        source: { caseStepId: "S1-4", method: "api" },
        id: "recruited_objective.challenger_absent",
        title: "征召后的目标的挑战者集合 应不包含 \"ORF Member Recruit Member E2E\"",
        object: "api.recruit_target",
        operator: "challenger_absent",
        params: { targetFrom: "runtime.recruitedObjective", memberNameFrom: "data.memberName" },
      },
      {
        source: { caseStepId: "S1-5", method: "api" },
        id: "accepted_objective.same_id",
        title: "接受后的目标 应与 本用例可征召目标 ID 相同",
        object: "api.recruit_target",
        operator: "same_id",
        params: { actualFrom: "runtime.acceptedObjective", expectedFrom: "runtime.fixtureObjective" },
      },
      {
        source: { caseStepId: "S1-6", method: "prisma" },
        id: "db.recruit_target.assigned_absent",
        title: "本用例可征召目标的待响应征召集合 应不包含 \"ORF Member Recruit Member E2E\"",
        object: "db.recruit_target",
        operator: "assigned_absent",
        params: { targetFrom: "runtime.fixtureObjective", memberNameFrom: "data.memberName" },
      },
      {
        source: { caseStepId: "S1-7", method: "prisma" },
        id: "db.recruit_target.challenger_contains",
        title: "本用例可征召目标的挑战者集合 应包含 \"ORF Member Recruit Member E2E\"",
        object: "db.recruit_target",
        operator: "challenger_contains",
        params: { targetFrom: "runtime.fixtureObjective", memberNameFrom: "data.memberName" },
      },
      {
        source: { caseStepId: "S1-8", method: "prisma" },
        id: "db.recruit_target.reestimating",
        title: "本用例可征召目标的流转状态 应变为 `reestimating`",
        object: "db.recruit_target",
        operator: "flow_status",
        params: { targetFrom: "runtime.fixtureObjective", status: "reestimating" },
      },
      {
        source: { caseStepId: "S1-9", method: "prisma" },
        id: "db.recruit_target.orf_reestimate",
        title: "本用例可征召目标的阶段 应变为 `orfReestimate`",
        object: "db.recruit_target",
        operator: "stage",
        params: { targetFrom: "runtime.fixtureObjective", stage: "orfReestimate" },
      },
      {
        source: { caseStepId: "S1-10", method: "prisma" },
        id: "db.recruit_target.accepted_at_present",
        title: "本用例可征召目标的接受时间 应存在",
        object: "db.recruit_target",
        operator: "accepted_at_present",
        params: { targetFrom: "runtime.fixtureObjective" },
      },
      {
        source: { caseStepId: "S1-11", method: "prisma" },
        id: "db.recruit_target.confirmation_due_at_present",
        title: "本用例可征召目标的确认截止时间 应存在",
        object: "db.recruit_target",
        operator: "confirmation_due_at_present",
        params: { targetFrom: "runtime.fixtureObjective" },
      },
      {
        source: { caseStepId: "S1-12", method: "api" },
        id: "api.bounties.recruitment_absent",
        title: "普通成员视角的悬赏大厅数据 应不再包含 本用例可征召目标作为 待接受征召",
        object: "api.bounties",
        operator: "recruitment_absent",
        params: { targetFrom: "runtime.acceptedObjective" },
      },
      {
        source: { caseStepId: "S1-13", method: "api" },
        id: "api.workbench.member_objective_present",
        title: "普通成员挑战工作台数据 应包含 本用例可征召目标",
        object: "api.my_challenges",
        operator: "objective_present_mine",
        params: { targetFrom: "runtime.acceptedObjective" },
      },
      {
        source: { caseStepId: "S1-14", method: "playwright" },
        id: "url.tasks",
        title: "当前页面 应为 挑战工作台",
        object: "page.url",
        operator: "match",
        params: { pattern: "/tasks$" },
      },
      {
        source: { caseStepId: "S1-15", method: "playwright" },
        id: "accepted_objective.visible",
        title: "挑战工作台列表 应显示 本用例可征召目标",
        object: "page.recruit_target",
        operator: "visible",
        params: { targetFrom: "runtime.acceptedObjective" },
      },
      {
        source: { caseStepId: "S1-16", method: "api" },
        id: "session.member.authenticated",
        title: "当前会话 应为 已登录",
        object: "auth.session",
        operator: "authenticated",
      },
      {
        source: { caseStepId: "S1-17", method: "api" },
        id: "session.member.email",
        title: "当前会话用户邮箱 应为 `orf-member-recruit-member-e2e@orf.local`",
        object: "auth.session.user_email",
        operator: "equals",
        params: { emailFrom: "data.memberEmail" },
      },
      {
        source: { caseStepId: "S1-18", method: "api" },
        id: "session.member.role",
        title: "当前会话用户角色 应为 `member`",
        object: "auth.session.user_role",
        operator: "equals",
        params: { roleFrom: "data.memberRole" },
      },
      {
        source: { caseStepId: "S1-19", method: "api" },
        id: "session.member.status",
        title: "当前会话用户状态 应为 `active`",
        object: "auth.session.user_status",
        operator: "equals",
        params: { status: "active" },
      },
    ],
  },

  Clean: {
    description: "删除本用例目标、账号和登录态并恢复未登录基准状态",
    steps: [
      {
        source: { caseStepId: "Clean-1", method: "prisma" },
        id: "db.objective.delete_by_title",
        title: "删除 本用例可征召目标及其派生数据",
        object: "db.objective",
        operator: "delete_by_title",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Clean-2", method: "api" },
        id: "auth.logout",
        title: "注销当前登录会话",
        object: "auth",
        operator: "logout",
      },
      {
        source: { caseStepId: "Clean-3", method: "playwright" },
        id: "page.runtime.stop",
        title: "离开当前 ORF 前端页面",
        object: "page.runtime",
        operator: "stop",
      },
      {
        source: { caseStepId: "Clean-4", method: "playwright" },
        id: "browser.clear",
        title: "移除当前浏览器中的残留登录态",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "Clean-5", method: "api" },
        id: "ory.admin_sessions.revoke",
        title: "撤销管理员登录身份的残留登录会话",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-6", method: "api" },
        id: "ory.member_sessions.revoke",
        title: "撤销普通成员登录身份的残留登录会话",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.memberEmail" },
      },
      {
        source: { caseStepId: "Clean-7", method: "api" },
        id: "ory.admin_identity.delete",
        title: "删除邮箱为 `orf-admin-recruit-member-e2e@orf.local` 的管理员登录身份",
        object: "ory.identity",
        operator: "delete_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-8", method: "api" },
        id: "ory.member_identity.delete",
        title: "删除邮箱为 `orf-member-recruit-member-e2e@orf.local` 的普通成员登录身份",
        object: "ory.identity",
        operator: "delete_by_email",
        params: { emailFrom: "data.memberEmail" },
      },
      {
        source: { caseStepId: "Clean-9", method: "prisma" },
        id: "db.admin.memberships.delete",
        title: "删除邮箱为 `orf-admin-recruit-member-e2e@orf.local` 的管理员用户默认团队成员关系",
        object: "db.user",
        operator: "delete_memberships",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-10", method: "prisma" },
        id: "db.member.memberships.delete",
        title: "删除邮箱为 `orf-member-recruit-member-e2e@orf.local` 的普通成员用户默认团队成员关系",
        object: "db.user",
        operator: "delete_memberships",
        params: { emailFrom: "data.memberEmail" },
      },
      {
        source: { caseStepId: "Clean-11", method: "prisma" },
        id: "db.admin.delete",
        title: "删除邮箱为 `orf-admin-recruit-member-e2e@orf.local` 的管理员用户",
        object: "db.user",
        operator: "delete",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-12", method: "prisma" },
        id: "db.member.delete",
        title: "删除邮箱为 `orf-member-recruit-member-e2e@orf.local` 的普通成员用户",
        object: "db.user",
        operator: "delete",
        params: { emailFrom: "data.memberEmail" },
      },
      {
        source: { caseStepId: "Clean-13", method: "prisma" },
        id: "db.objective.absent",
        title: "应不存在 标题为 `E2E-RECRUIT-MEMBER: 管理员征召成员执行目标` 的测试目标",
        object: "db.objective",
        operator: "absent",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Clean-14", method: "api" },
        id: "ory.admin_identity.absent",
        title: "邮箱为 `orf-admin-recruit-member-e2e@orf.local` 的管理员登录身份 应不存在",
        object: "ory.identity",
        operator: "absent",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-15", method: "api" },
        id: "ory.member_identity.absent",
        title: "邮箱为 `orf-member-recruit-member-e2e@orf.local` 的普通成员登录身份 应不存在",
        object: "ory.identity",
        operator: "absent",
        params: { emailFrom: "data.memberEmail" },
      },
      {
        source: { caseStepId: "Clean-16", method: "prisma" },
        id: "db.admin.absent",
        title: "邮箱为 `orf-admin-recruit-member-e2e@orf.local` 的管理员用户 应不存在",
        object: "db.user",
        operator: "absent",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-17", method: "prisma" },
        id: "db.member.absent",
        title: "邮箱为 `orf-member-recruit-member-e2e@orf.local` 的普通成员用户 应不存在",
        object: "db.user",
        operator: "absent",
        params: { emailFrom: "data.memberEmail" },
      },
    ],
  },
} satisfies StateCaseSpec<RecruitMemberCaseData>;
