import { STATE_CASE_MODEL, type StateCaseSpec, type StepExecutionMethod, type StepSpec } from "../../_framework/types";
import type { SystemMembersAddCaseData } from "./_support/members-add.context";

function step(
  caseStepId: string,
  method: StepExecutionMethod,
  id: string,
  title: string,
  object: string,
  operator: string,
  params?: Record<string, unknown>,
): StepSpec {
  return {
    source: { caseStepId, method },
    id,
    title,
    object,
    operator,
    ...(params ? { params } : {}),
  };
}

export const systemMembersAddCase = {
  id: "system.members-add.validation",
  title: "05-成员管理新增用户校验",
  model: STATE_CASE_MODEL,
  tags: ["system", "members", "add-user", "validation"],
  data: {
    admin: {
      email: "orf-system-members-add-admin-e2e@orf.local",
      password: "OrfSystemMembersAddAdminE2E!2026",
      name: "ORF Members Add Admin E2E",
      role: "admin",
    },
    existingUser: {
      email: "orf-system-members-add-existing-e2e@orf.local",
      name: "ORF Members Add Existing E2E",
      role: "member",
    },
    createdUser: {
      email: "orf-system-members-add-created-e2e@orf.local",
      name: "ORF Members Add Created E2E",
      role: "member",
    },
    emptyNameUser: {
      email: "orf-system-members-add-empty-name-e2e@orf.local",
      name: "",
      role: "member",
    },
    emptyEmailUser: {
      name: "ORF Members Add Empty Email E2E",
      role: "member",
    },
    invalidEmailUser: {
      email: "invalid-email",
      name: "ORF Members Add Invalid Email E2E",
      role: "member",
    },
    duplicateUser: {
      email: "orf-system-members-add-existing-e2e@orf.local",
      name: "ORF Members Add Duplicate E2E",
      role: "member",
    },
    cancelUser: {
      email: "orf-system-members-add-cancel-e2e@orf.local",
      name: "ORF Members Add Cancel E2E",
      role: "member",
    },
    closeUser: {
      email: "orf-system-members-add-close-e2e@orf.local",
      name: "ORF Members Add Close E2E",
      role: "admin",
    },
    defaultLandingPath: "/bounties",
    membersPath: "/system/members",
  },
  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      step("B-1", "api", "frontend.ready", "前端服务 应可用", "frontend.service", "available"),
      step("B-2", "api", "backend.ready", "后端服务 应可用", "api.health", "ok"),
      step("B-3", "api", "frontend.login_entry.accessible", "前端登录页入口 应可访问", "frontend.login_entry", "accessible"),
      step("B-4", "api", "session.endpoint.accessible", "当前会话查询能力 应可用", "auth.session", "accessible"),
      step("B-5", "prisma", "db.ready", "ORF 数据库 应可连接", "db", "ready"),
      step("B-6", "prisma", "db.schema.current", "ORF 数据库 schema 应为 当前测试版本", "db.schema", "current"),
      step("B-7", "api", "ory.admin_public.ready", "Ory/Kratos 认证服务的管理和公共访问能力 应可用", "ory.admin_public", "ready"),
      step("B-8", "api", "session.unauthenticated", "当前会话 应为 未登录", "auth.session", "unauthenticated"),
      step("B-9", "playwright", "cookie.absent", "当前浏览器 应不存在 Ory 登录会话 cookie", "browser.cookie", "absent"),
      step("B-10", "playwright", "storage.empty", "当前浏览器 应不保留本地登录态", "browser.auth_storage", "empty"),
    ],
  },
  Setup: {
    description: "准备管理员、已存在成员和待新增目标数据，并以管理员身份进入成员管理页面",
    steps: [
      step("Setup-1", "api", "ory.admin_identity.upsert", "准备邮箱为 `orf-system-members-add-admin-e2e@orf.local`、使用固定测试密码的成员管理新增用户管理员测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.admin.email", passwordFrom: "data.admin.password", nameFrom: "data.admin.name", saveAs: "adminIdentity" }),
      step("Setup-2", "prisma", "db.admin_user.upsert", "准备姓名为 \"ORF Members Add Admin E2E\"、邮箱为 `orf-system-members-add-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的成员管理新增用户管理员测试用户", "db.user", "upsert", { emailFrom: "data.admin.email", passwordFrom: "data.admin.password", nameFrom: "data.admin.name", roleFrom: "data.admin.role", status: "active", identityIdFrom: "runtime.adminIdentity.id", saveAs: "adminUser" }),
      step("Setup-3", "api", "admin.preferences.default_landing_path.set", "设置成员管理新增用户管理员测试用户默认进入页面为 首页（默认系统页）", "user.preferences", "set_default_landing_path_by_email", { emailFrom: "data.admin.email", pathFrom: "data.defaultLandingPath" }),
      step("Setup-4", "prisma", "db.existing_user.upsert", "准备姓名为 \"ORF Members Add Existing E2E\"、邮箱为 `orf-system-members-add-existing-e2e@orf.local`、角色为 `member`、状态为 `active` 的成员管理新增用户已存在测试用户", "db.user", "upsert", { emailFrom: "data.existingUser.email", nameFrom: "data.existingUser.name", roleFrom: "data.existingUser.role", status: "active", saveAs: "existingUser" }),
      step("Setup-5", "prisma", "db.created_user.delete", "删除邮箱为 `orf-system-members-add-created-e2e@orf.local` 的成员管理新增成功目标测试用户", "db.user", "delete", { emailFrom: "data.createdUser.email" }),
      step("Setup-6", "prisma", "db.cancel_user.delete", "删除邮箱为 `orf-system-members-add-cancel-e2e@orf.local` 的成员管理取消新增目标测试用户", "db.user", "delete", { emailFrom: "data.cancelUser.email" }),
      step("Setup-7", "prisma", "db.close_user.delete", "删除邮箱为 `orf-system-members-add-close-e2e@orf.local` 的成员管理关闭新增目标测试用户", "db.user", "delete", { emailFrom: "data.closeUser.email" }),
      step("Setup-8", "api", "ory.admin_sessions.revoke", "撤销邮箱为 `orf-system-members-add-admin-e2e@orf.local` 的成员管理新增用户管理员测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.admin.email" }),
      step("Setup-9", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Setup-10", "playwright", "page.goto.auth", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Setup-11", "playwright", "fill.admin_email", "在邮箱输入框输入 `orf-system-members-add-admin-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.admin.email" }),
      step("Setup-12", "playwright", "fill.admin_password", "在密码输入框输入成员管理新增用户管理员测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.admin.password" }),
      step("Setup-13", "playwright", "click.sign_in", "点击 \"Sign In\" 登录操作", "page.login_form", "submit", { saveAs: "adminLoginResponse" }),
      step("Setup-14", "api", "session.admin_authenticated", "当前会话 应为 邮箱为 `orf-system-members-add-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
      step("Setup-15", "playwright", "page.goto.members", "打开 成员管理页面", "page", "goto", { pathFrom: "data.membersPath" }),
    ],
  },
  S0: {
    description: "管理员已登录并位于成员管理页面，新增目标用户不存在",
    assertions: [
      step("S0-1", "api", "session.admin_authenticated", "当前会话 应为 邮箱为 `orf-system-members-add-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
      step("S0-2", "playwright", "url.members", "当前页面 应为 成员管理页面", "page.url", "match", { pattern: "/system/members$" }),
      step("S0-3", "playwright", "members.add_button.visible", "成员管理页面的新增用户按钮 应可见", "page.members_add_button", "visible"),
      step("S0-4", "playwright", "members.add_button.enabled", "成员管理页面的新增用户按钮 应可点击", "page.members_add_button", "enabled"),
      step("S0-5", "playwright", "members.list.created.hidden", "成员管理页面的用户列表 应不显示 新增成功目标测试用户", "page.members_list", "lacks_user", { emailFrom: "data.createdUser.email" }),
      step("S0-6", "playwright", "members.list.cancel.hidden", "成员管理页面的用户列表 应不显示 取消新增目标测试用户", "page.members_list", "lacks_user", { emailFrom: "data.cancelUser.email" }),
      step("S0-7", "playwright", "members.list.close.hidden", "成员管理页面的用户列表 应不显示 关闭新增目标测试用户", "page.members_list", "lacks_user", { emailFrom: "data.closeUser.email" }),
      step("S0-8", "prisma", "db.existing_user.exists", "邮箱为 `orf-system-members-add-existing-e2e@orf.local` 的成员管理新增用户已存在测试用户 应存在", "db.user", "matches", { emailFrom: "data.existingUser.email", roleFrom: "data.existingUser.role", status: "active" }),
      step("S0-9", "prisma", "db.created_user.absent", "邮箱为 `orf-system-members-add-created-e2e@orf.local` 的成员管理新增成功目标测试用户 应不存在", "db.user", "absent", { emailFrom: "data.createdUser.email" }),
      step("S0-10", "prisma", "db.cancel_user.absent", "邮箱为 `orf-system-members-add-cancel-e2e@orf.local` 的成员管理取消新增目标测试用户 应不存在", "db.user", "absent", { emailFrom: "data.cancelUser.email" }),
      step("S0-11", "prisma", "db.close_user.absent", "邮箱为 `orf-system-members-add-close-e2e@orf.local` 的成员管理关闭新增目标测试用户 应不存在", "db.user", "absent", { emailFrom: "data.closeUser.email" }),
    ],
  },
  Action: {
    description: "依次验证新增用户成功、输入校验、重复邮箱、取消和关闭弹窗",
    steps: [
      step("Action-1", "playwright", "members.add.open.success", "点击 成员管理页面的新增用户按钮", "page.members_add_button", "click"),
      step("Action-2", "playwright", "members.add.dialog.observe", "查看 新增用户弹窗", "page.add_user_dialog", "observe", { saveAs: "initialDialogSnapshot" }),
      step("Action-3", "playwright", "members.add.created.name.fill", "在新增用户弹窗的姓名输入框输入 \"ORF Members Add Created E2E\"", "page.add_user_dialog.name", "fill", { valueFrom: "data.createdUser.name" }),
      step("Action-4", "playwright", "members.add.created.email.fill", "在新增用户弹窗的邮箱输入框输入 `orf-system-members-add-created-e2e@orf.local`", "page.add_user_dialog.email", "fill", { valueFrom: "data.createdUser.email" }),
      step("Action-5", "playwright", "members.add.created.role.select", "在新增用户弹窗的角色选择框选择 \"成员\"", "page.add_user_dialog.role", "select", { label: "成员" }),
      step("Action-6", "playwright", "members.add.created.submit", "点击 新增用户弹窗的新增用户提交操作", "page.add_user_dialog.submit", "click_and_wait_created", { emailFrom: "data.createdUser.email" }),
      step("Action-7", "playwright", "members.add.open.empty_name", "点击 成员管理页面的新增用户按钮", "page.members_add_button", "click"),
      step("Action-8", "playwright", "members.add.empty_name.keep_empty", "保持新增用户弹窗的姓名输入框为空", "page.add_user_dialog.name", "keep_empty"),
      step("Action-9", "playwright", "members.add.empty_name.email.fill", "在新增用户弹窗的邮箱输入框输入 `orf-system-members-add-empty-name-e2e@orf.local`", "page.add_user_dialog.email", "fill", { valueFrom: "data.emptyNameUser.email" }),
      step("Action-10", "playwright", "members.add.empty_name.submit", "点击 新增用户弹窗的新增用户提交操作", "page.add_user_dialog.submit", "click_invalid_and_snapshot", { field: "name", saveAs: "emptyNameSnapshot" }),
      step("Action-11", "playwright", "members.add.empty_name.close", "关闭 新增用户弹窗", "page.add_user_dialog", "close"),
      step("Action-12", "playwright", "members.add.open.empty_email", "点击 成员管理页面的新增用户按钮", "page.members_add_button", "click"),
      step("Action-13", "playwright", "members.add.empty_email.name.fill", "在新增用户弹窗的姓名输入框输入 \"ORF Members Add Empty Email E2E\"", "page.add_user_dialog.name", "fill", { valueFrom: "data.emptyEmailUser.name" }),
      step("Action-14", "playwright", "members.add.empty_email.keep_empty", "保持新增用户弹窗的邮箱输入框为空", "page.add_user_dialog.email", "keep_empty"),
      step("Action-15", "playwright", "members.add.empty_email.submit", "点击 新增用户弹窗的新增用户提交操作", "page.add_user_dialog.submit", "click_invalid_and_snapshot", { field: "email", saveAs: "emptyEmailSnapshot" }),
      step("Action-16", "playwright", "members.add.empty_email.close", "关闭 新增用户弹窗", "page.add_user_dialog", "close"),
      step("Action-17", "playwright", "members.add.open.invalid_email", "点击 成员管理页面的新增用户按钮", "page.members_add_button", "click"),
      step("Action-18", "playwright", "members.add.invalid_email.name.fill", "在新增用户弹窗的姓名输入框输入 \"ORF Members Add Invalid Email E2E\"", "page.add_user_dialog.name", "fill", { valueFrom: "data.invalidEmailUser.name" }),
      step("Action-19", "playwright", "members.add.invalid_email.email.fill", "在新增用户弹窗的邮箱输入框输入 \"invalid-email\"", "page.add_user_dialog.email", "fill", { valueFrom: "data.invalidEmailUser.email" }),
      step("Action-20", "playwright", "members.add.invalid_email.submit", "点击 新增用户弹窗的新增用户提交操作", "page.add_user_dialog.submit", "click_invalid_and_snapshot", { field: "email", saveAs: "invalidEmailSnapshot" }),
      step("Action-21", "playwright", "members.add.invalid_email.close", "关闭 新增用户弹窗", "page.add_user_dialog", "close"),
      step("Action-22", "playwright", "members.add.open.duplicate", "点击 成员管理页面的新增用户按钮", "page.members_add_button", "click"),
      step("Action-23", "playwright", "members.add.duplicate.name.fill", "在新增用户弹窗的姓名输入框输入 \"ORF Members Add Duplicate E2E\"", "page.add_user_dialog.name", "fill", { valueFrom: "data.duplicateUser.name" }),
      step("Action-24", "playwright", "members.add.duplicate.email.fill", "在新增用户弹窗的邮箱输入框输入 `orf-system-members-add-existing-e2e@orf.local`", "page.add_user_dialog.email", "fill", { valueFrom: "data.duplicateUser.email" }),
      step("Action-25", "playwright", "members.add.duplicate.role.select", "在新增用户弹窗的角色选择框选择 \"成员\"", "page.add_user_dialog.role", "select", { label: "成员" }),
      step("Action-26", "playwright", "members.add.duplicate.submit", "点击 新增用户弹窗的新增用户提交操作", "page.add_user_dialog.submit", "click_duplicate_and_snapshot", { saveAs: "duplicateEmailSnapshot" }),
      step("Action-27", "playwright", "members.add.duplicate.close", "关闭 新增用户弹窗", "page.add_user_dialog", "close"),
      step("Action-28", "playwright", "members.add.open.cancel", "点击 成员管理页面的新增用户按钮", "page.members_add_button", "click"),
      step("Action-29", "playwright", "members.add.cancel.name.fill", "在新增用户弹窗的姓名输入框输入 \"ORF Members Add Cancel E2E\"", "page.add_user_dialog.name", "fill", { valueFrom: "data.cancelUser.name" }),
      step("Action-30", "playwright", "members.add.cancel.email.fill", "在新增用户弹窗的邮箱输入框输入 `orf-system-members-add-cancel-e2e@orf.local`", "page.add_user_dialog.email", "fill", { valueFrom: "data.cancelUser.email" }),
      step("Action-31", "playwright", "members.add.cancel.role.select", "在新增用户弹窗的角色选择框选择 \"成员\"", "page.add_user_dialog.role", "select", { label: "成员" }),
      step("Action-32", "playwright", "members.add.cancel.click", "点击 新增用户弹窗的取消操作", "page.add_user_dialog.cancel", "click"),
      step("Action-33", "playwright", "members.add.open.close", "点击 成员管理页面的新增用户按钮", "page.members_add_button", "click"),
      step("Action-34", "playwright", "members.add.close.name.fill", "在新增用户弹窗的姓名输入框输入 \"ORF Members Add Close E2E\"", "page.add_user_dialog.name", "fill", { valueFrom: "data.closeUser.name" }),
      step("Action-35", "playwright", "members.add.close.email.fill", "在新增用户弹窗的邮箱输入框输入 `orf-system-members-add-close-e2e@orf.local`", "page.add_user_dialog.email", "fill", { valueFrom: "data.closeUser.email" }),
      step("Action-36", "playwright", "members.add.close.role.select", "在新增用户弹窗的角色选择框选择 \"管理员\"", "page.add_user_dialog.role", "select", { label: "管理员" }),
      step("Action-37", "playwright", "members.add.close.click", "点击 新增用户弹窗的关闭操作", "page.add_user_dialog.close", "click"),
    ],
  },
  S1: {
    description: "新增用户成功，校验失败和取消关闭均不新增用户",
    assertions: [
      step("S1-1", "playwright", "dialog.title.visible", "新增用户弹窗标题 应显示 \"新增用户\"", "page.add_user_dialog_snapshot", "title_visible", { snapshotFrom: "runtime.initialDialogSnapshot" }),
      step("S1-2", "playwright", "dialog.name.visible", "新增用户弹窗的姓名输入框 应可见", "page.add_user_dialog_snapshot", "name_visible", { snapshotFrom: "runtime.initialDialogSnapshot" }),
      step("S1-3", "playwright", "dialog.email.visible", "新增用户弹窗的邮箱输入框 应可见", "page.add_user_dialog_snapshot", "email_visible", { snapshotFrom: "runtime.initialDialogSnapshot" }),
      step("S1-4", "playwright", "dialog.role.visible", "新增用户弹窗的角色选择框 应可见", "page.add_user_dialog_snapshot", "role_visible", { snapshotFrom: "runtime.initialDialogSnapshot" }),
      step("S1-5", "playwright", "dialog.cancel.visible", "新增用户弹窗的取消操作 应可见", "page.add_user_dialog_snapshot", "cancel_visible", { snapshotFrom: "runtime.initialDialogSnapshot" }),
      step("S1-6", "playwright", "dialog.close.visible", "新增用户弹窗的关闭操作 应可见", "page.add_user_dialog_snapshot", "close_visible", { snapshotFrom: "runtime.initialDialogSnapshot" }),
      step("S1-7", "playwright", "dialog.submit.visible", "新增用户弹窗的新增用户提交操作 应可见", "page.add_user_dialog_snapshot", "submit_visible", { snapshotFrom: "runtime.initialDialogSnapshot" }),
      step("S1-8", "playwright", "members.list.created.visible", "提交有效新增用户信息后，成员管理页面的用户列表 应显示 新增成功目标测试用户", "page.members_list", "contains_user", { emailFrom: "data.createdUser.email", nameFrom: "data.createdUser.name" }),
      step("S1-9", "prisma", "db.created_user.exists", "邮箱为 `orf-system-members-add-created-e2e@orf.local` 的成员管理新增成功目标测试用户 应存在", "db.user", "matches", { emailFrom: "data.createdUser.email", roleFrom: "data.createdUser.role", status: "active" }),
      step("S1-10", "prisma", "db.created_user.role", "邮箱为 `orf-system-members-add-created-e2e@orf.local` 的成员管理新增成功目标测试用户角色 应为 `member`", "db.user", "matches", { emailFrom: "data.createdUser.email", roleFrom: "data.createdUser.role" }),
      step("S1-11", "playwright", "empty_name.dialog.visible", "姓名为空提交后，新增用户弹窗 应保持可见", "page.add_user_dialog_snapshot", "dialog_visible", { snapshotFrom: "runtime.emptyNameSnapshot" }),
      step("S1-12", "playwright", "empty_name.required", "姓名为空提交后，系统 应提示 姓名必填规则错误", "page.add_user_dialog_snapshot", "field_invalid", { snapshotFrom: "runtime.emptyNameSnapshot", field: "name" }),
      step("S1-13", "prisma", "db.empty_name_user.absent", "邮箱为 `orf-system-members-add-empty-name-e2e@orf.local` 的成员管理姓名为空目标测试用户 应不存在", "db.user", "absent", { emailFrom: "data.emptyNameUser.email" }),
      step("S1-14", "playwright", "empty_email.dialog.visible", "邮箱为空提交后，新增用户弹窗 应保持可见", "page.add_user_dialog_snapshot", "dialog_visible", { snapshotFrom: "runtime.emptyEmailSnapshot" }),
      step("S1-15", "playwright", "empty_email.required", "邮箱为空提交后，系统 应提示 邮箱必填规则错误", "page.add_user_dialog_snapshot", "field_invalid", { snapshotFrom: "runtime.emptyEmailSnapshot", field: "email" }),
      step("S1-16", "prisma", "db.empty_email_name.absent", "姓名为 \"ORF Members Add Empty Email E2E\" 的成员管理邮箱为空目标测试用户 应不存在", "db.user_name", "absent", { nameFrom: "data.emptyEmailUser.name" }),
      step("S1-17", "playwright", "invalid_email.dialog.visible", "邮箱格式错误提交后，新增用户弹窗 应保持可见", "page.add_user_dialog_snapshot", "dialog_visible", { snapshotFrom: "runtime.invalidEmailSnapshot" }),
      step("S1-18", "playwright", "invalid_email.format", "邮箱格式错误提交后，系统 应提示 邮箱格式规则错误", "page.add_user_dialog_snapshot", "field_invalid", { snapshotFrom: "runtime.invalidEmailSnapshot", field: "email" }),
      step("S1-19", "prisma", "db.invalid_email_name.absent", "姓名为 \"ORF Members Add Invalid Email E2E\" 的成员管理邮箱格式错误目标测试用户 应不存在", "db.user_name", "absent", { nameFrom: "data.invalidEmailUser.name" }),
      step("S1-20", "playwright", "duplicate.dialog.visible", "邮箱已存在提交后，新增用户弹窗 应保持可见", "page.add_user_dialog_snapshot", "dialog_visible", { snapshotFrom: "runtime.duplicateEmailSnapshot" }),
      step("S1-21", "playwright", "duplicate.email.error", "邮箱已存在提交后，系统 应提示 邮箱已存在规则错误", "page.add_user_dialog_snapshot", "duplicate_email_error", { snapshotFrom: "runtime.duplicateEmailSnapshot" }),
      step("S1-22", "prisma", "db.existing_user.count", "邮箱为 `orf-system-members-add-existing-e2e@orf.local` 的成员管理新增用户已存在测试用户数量 应为 1", "db.user_email", "count", { emailFrom: "data.existingUser.email", expected: 1 }),
      step("S1-23", "playwright", "cancel.dialog.hidden", "点击取消后，新增用户弹窗 应不可见", "page.add_user_dialog", "hidden"),
      step("S1-24", "playwright", "members.list.cancel.hidden", "点击取消后，成员管理页面的用户列表 应不显示 取消新增目标测试用户", "page.members_list", "lacks_user", { emailFrom: "data.cancelUser.email" }),
      step("S1-25", "prisma", "db.cancel_user.absent", "邮箱为 `orf-system-members-add-cancel-e2e@orf.local` 的成员管理取消新增目标测试用户 应不存在", "db.user", "absent", { emailFrom: "data.cancelUser.email" }),
      step("S1-26", "playwright", "close.dialog.hidden", "点击关闭后，新增用户弹窗 应不可见", "page.add_user_dialog", "hidden"),
      step("S1-27", "playwright", "members.list.close.hidden", "点击关闭后，成员管理页面的用户列表 应不显示 关闭新增目标测试用户", "page.members_list", "lacks_user", { emailFrom: "data.closeUser.email" }),
      step("S1-28", "prisma", "db.close_user.absent", "邮箱为 `orf-system-members-add-close-e2e@orf.local` 的成员管理关闭新增目标测试用户 应不存在", "db.user", "absent", { emailFrom: "data.closeUser.email" }),
      step("S1-29", "api", "session.admin_authenticated.after_add", "当前会话 应仍为 邮箱为 `orf-system-members-add-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
    ],
  },
  Clean: {
    description: "删除新增用户相关测试数据并恢复未登录基准状态",
    steps: [
      step("Clean-1", "api", "auth.logout", "注销当前登录会话", "auth", "logout"),
      step("Clean-2", "playwright", "page.runtime.stop", "离开当前 ORF 前端页面", "page.runtime", "stop"),
      step("Clean-3", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Clean-4", "api", "ory.admin_sessions.revoke", "撤销邮箱为 `orf-system-members-add-admin-e2e@orf.local` 的成员管理新增用户管理员测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-5", "api", "ory.admin_identity.delete", "删除邮箱为 `orf-system-members-add-admin-e2e@orf.local` 的成员管理新增用户管理员测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-6", "api", "admin.preferences.default_landing_path.reset", "恢复邮箱为 `orf-system-members-add-admin-e2e@orf.local` 的默认进入页面为 系统默认", "user.preferences", "reset_default_landing_path_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-7", "prisma", "db.admin_user.memberships.delete", "删除邮箱为 `orf-system-members-add-admin-e2e@orf.local` 的成员管理新增用户管理员测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.admin.email" }),
      step("Clean-8", "prisma", "db.existing_user.memberships.delete", "删除邮箱为 `orf-system-members-add-existing-e2e@orf.local` 的成员管理新增用户已存在测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.existingUser.email" }),
      step("Clean-9", "prisma", "db.created_user.memberships.delete", "删除邮箱为 `orf-system-members-add-created-e2e@orf.local` 的成员管理新增成功目标测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.createdUser.email" }),
      step("Clean-10", "prisma", "db.cancel_user.memberships.delete", "删除邮箱为 `orf-system-members-add-cancel-e2e@orf.local` 的成员管理取消新增目标测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.cancelUser.email" }),
      step("Clean-11", "prisma", "db.close_user.memberships.delete", "删除邮箱为 `orf-system-members-add-close-e2e@orf.local` 的成员管理关闭新增目标测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.closeUser.email" }),
      step("Clean-12", "prisma", "db.admin_user.delete", "删除邮箱为 `orf-system-members-add-admin-e2e@orf.local` 的成员管理新增用户管理员测试用户", "db.user", "delete", { emailFrom: "data.admin.email" }),
      step("Clean-13", "prisma", "db.existing_user.delete", "删除邮箱为 `orf-system-members-add-existing-e2e@orf.local` 的成员管理新增用户已存在测试用户", "db.user", "delete", { emailFrom: "data.existingUser.email" }),
      step("Clean-14", "prisma", "db.created_user.delete", "删除邮箱为 `orf-system-members-add-created-e2e@orf.local` 的成员管理新增成功目标测试用户", "db.user", "delete", { emailFrom: "data.createdUser.email" }),
      step("Clean-15", "prisma", "db.cancel_user.delete", "删除邮箱为 `orf-system-members-add-cancel-e2e@orf.local` 的成员管理取消新增目标测试用户", "db.user", "delete", { emailFrom: "data.cancelUser.email" }),
      step("Clean-16", "prisma", "db.close_user.delete", "删除邮箱为 `orf-system-members-add-close-e2e@orf.local` 的成员管理关闭新增目标测试用户", "db.user", "delete", { emailFrom: "data.closeUser.email" }),
      step("Clean-17", "api", "ory.admin_identity.absent", "邮箱为 `orf-system-members-add-admin-e2e@orf.local` 的成员管理新增用户管理员测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.admin.email" }),
      step("Clean-18", "prisma", "db.admin_user.absent", "邮箱为 `orf-system-members-add-admin-e2e@orf.local` 的成员管理新增用户管理员测试用户 应不存在", "db.user", "absent", { emailFrom: "data.admin.email" }),
      step("Clean-19", "prisma", "db.existing_user.absent", "邮箱为 `orf-system-members-add-existing-e2e@orf.local` 的成员管理新增用户已存在测试用户 应不存在", "db.user", "absent", { emailFrom: "data.existingUser.email" }),
      step("Clean-20", "prisma", "db.created_user.absent", "邮箱为 `orf-system-members-add-created-e2e@orf.local` 的成员管理新增成功目标测试用户 应不存在", "db.user", "absent", { emailFrom: "data.createdUser.email" }),
      step("Clean-21", "prisma", "db.cancel_user.absent", "邮箱为 `orf-system-members-add-cancel-e2e@orf.local` 的成员管理取消新增目标测试用户 应不存在", "db.user", "absent", { emailFrom: "data.cancelUser.email" }),
      step("Clean-22", "prisma", "db.close_user.absent", "邮箱为 `orf-system-members-add-close-e2e@orf.local` 的成员管理关闭新增目标测试用户 应不存在", "db.user", "absent", { emailFrom: "data.closeUser.email" }),
    ],
  },
} satisfies StateCaseSpec<SystemMembersAddCaseData>;
