import { STATE_CASE_MODEL, type StateCaseSpec, type StepExecutionMethod, type StepSpec } from "../../_framework/types";
import type { FeedbackCreateSubmitCaseData } from "./_support/feedback-create-submit.context";

function step(
  caseStepId: string,
  method: StepExecutionMethod,
  id: string,
  title: string,
  object: string,
  operator: string,
  params?: Record<string, unknown>,
): StepSpec {
  return {
    source: { caseStepId, method },
    id,
    title,
    object,
    operator,
    ...(params ? { params } : {}),
  };
}

export const feedbackCreateSubmitCase = {
  id: "defaults.feedback-create.submit-validation",
  title: "12-新建反馈创建成功与必填校验",
  model: STATE_CASE_MODEL,
  tags: ["defaults", "feedback", "create-feedback", "submit", "validation"],
  data: {
    email: "orf-default-page-feedback-create-e2e@orf.local",
    password: "OrfDefaultPageFeedbackCreateE2E!2026",
    name: "ORF Default Page Feedback Create E2E",
    role: "admin",
    defaultLandingPath: "/bounties",
    homePath: "/dashboard",
    createFeedbackPathPattern: "/feedback/new$",
    feedbackDetailPathPattern: "/feedback/[^/]+$",
    title: "ORF默认页反馈创建E2E-标题",
    description: "ORF默认页反馈创建E2E-描述内容",
    owner: "ORF Default Page Feedback Create E2E",
    category: "技术问题",
    initialImpactLabel: "中",
    impactLabel: "高",
    impactValue: "High",
    requiredMessage: "请填写标题、正文、分类和处理人",
  },
  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      step("B-1", "api", "frontend.ready", "前端服务 应可用", "frontend.service", "available"),
      step("B-2", "api", "backend.ready", "后端服务 应可用", "api.health", "ok"),
      step("B-3", "api", "frontend.login_entry.accessible", "前端登录页入口 应可访问", "frontend.login_entry", "accessible"),
      step("B-4", "api", "session.endpoint.accessible", "当前会话查询能力 应可用", "auth.session", "accessible"),
      step("B-5", "prisma", "db.ready", "ORF 数据库 应可连接", "db", "ready"),
      step("B-6", "prisma", "db.schema.current", "ORF 数据库 schema 应为 当前测试版本", "db.schema", "current"),
      step("B-7", "api", "ory.admin_public.ready", "Ory/Kratos 认证服务的管理和公共访问能力 应可用", "ory.admin_public", "ready"),
      step("B-8", "api", "session.unauthenticated", "当前会话 应为 未登录", "auth.session", "unauthenticated"),
      step("B-9", "playwright", "cookie.absent", "当前浏览器 应不存在 Ory 登录会话 cookie", "browser.cookie", "absent"),
      step("B-10", "playwright", "storage.empty", "当前浏览器 应不保留本地登录态", "browser.auth_storage", "empty"),
    ],
  },
  Setup: {
    description: "准备新建反馈创建测试用户，清理残留反馈，登录并进入新建反馈页面",
    steps: [
      step("Setup-1", "api", "ory.identity.upsert", "准备邮箱为 `orf-default-page-feedback-create-e2e@orf.local`、使用固定测试密码的新建反馈创建测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.email", passwordFrom: "data.password", nameFrom: "data.name", saveAs: "identity" }),
      step("Setup-2", "prisma", "db.user.upsert", "准备邮箱为 `orf-default-page-feedback-create-e2e@orf.local`、姓名为 `ORF Default Page Feedback Create E2E`、角色为 `admin`、状态为 `active` 的新建反馈创建测试用户", "db.user", "upsert", { emailFrom: "data.email", passwordFrom: "data.password", nameFrom: "data.name", roleFrom: "data.role", status: "active", identityIdFrom: "runtime.identity.id", saveAs: "user" }),
      step("Setup-3", "api", "preferences.default_landing_path.set", "设置新建反馈创建测试用户默认进入页面为 首页（默认系统页）", "user.preferences", "set_default_landing_path_by_email", { emailFrom: "data.email", pathFrom: "data.defaultLandingPath" }),
      step("Setup-4", "prisma", "db.feedback.delete_residual", "删除现象为 `ORF默认页反馈创建E2E-标题` 的残留反馈 issue", "db.feedback", "delete_by_phenomenon", { phenomenonFrom: "data.title" }),
      step("Setup-5", "api", "ory.sessions.revoke", "撤销邮箱为 `orf-default-page-feedback-create-e2e@orf.local` 的新建反馈创建测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.email" }),
      step("Setup-6", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Setup-7", "playwright", "page.goto.auth", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Setup-8", "playwright", "fill.email", "在邮箱输入框输入 `orf-default-page-feedback-create-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.email" }),
      step("Setup-9", "playwright", "fill.password", "在密码输入框输入新建反馈创建测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.password" }),
      step("Setup-10", "playwright", "click.sign_in", "点击 \"Sign In\" 登录操作", "page.login_form", "submit", { saveAs: "loginResponse" }),
      step("Setup-11", "api", "session.authenticated", "当前会话 应为 邮箱为 `orf-default-page-feedback-create-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.email", roleFrom: "data.role", status: "active" }),
      step("Setup-12", "playwright", "page.goto.home", "打开 首页（默认系统页）", "page", "goto", { pathFrom: "data.homePath" }),
      step("Setup-13", "playwright", "topbar.feedback.click", "点击 顶部导航栏的新建反馈入口", "topbar.feedback", "click"),
    ],
  },
  S0: {
    description: "新建反馈页面表单可见，提交前未存在同名测试反馈",
    assertions: [
      step("S0-1", "api", "session.authenticated", "当前会话 应为 邮箱为 `orf-default-page-feedback-create-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.email", roleFrom: "data.role", status: "active" }),
      step("S0-2", "playwright", "feedback_create.page.visible", "当前页面 应为 新建反馈页面", "feedback_create.page", "visible", { patternFrom: "data.createFeedbackPathPattern" }),
      step("S0-3", "playwright", "feedback_create.form.visible", "新建反馈表单 应可见", "feedback_create.form", "visible"),
      step("S0-4", "playwright", "feedback_create.title_input.empty", "新建反馈表单的标题输入框 应为空", "feedback_create.title_input", "empty"),
      step("S0-5", "playwright", "feedback_create.description_input.empty", "新建反馈表单的反馈描述输入区域 应为空", "feedback_create.description_input", "empty"),
      step("S0-6", "playwright", "feedback_create.owner_select.selected", "新建反馈表单的处理人选择框 应已选择 `ORF Default Page Feedback Create E2E`", "feedback_create.owner_select", "selected_label", { labelFrom: "data.owner" }),
      step("S0-7", "playwright", "feedback_create.category_select.selected", "新建反馈表单的分类选择框 应已选择 `技术问题`", "feedback_create.category_select", "selected_label", { labelFrom: "data.category" }),
      step("S0-8", "playwright", "feedback_create.impact_select.selected", "新建反馈表单的影响等级选择框 应已选择 `中`", "feedback_create.impact_select", "selected_label", { labelFrom: "data.initialImpactLabel" }),
      step("S0-9", "playwright", "feedback_create.submit.enabled", "新建反馈表单的提交操作 应可点击", "feedback_create.submit", "enabled"),
      step("S0-10", "prisma", "db.feedback.absent", "现象为 `ORF默认页反馈创建E2E-标题` 的反馈 issue 应不存在", "db.feedback", "absent", { phenomenonFrom: "data.title" }),
    ],
  },
  Action: {
    description: "先提交正文为空的反馈表单，再补齐有效反馈信息并创建 issue",
    steps: [
      step("Action-1", "playwright", "feedback_create.title_input.fill", "在新建反馈表单的标题输入框输入 `ORF默认页反馈创建E2E-标题`", "feedback_create.title_input", "fill", { valueFrom: "data.title" }),
      step("Action-2", "playwright", "feedback_create.submit.empty_required", "点击 新建反馈表单的提交操作", "feedback_create.submit", "click", { expectedToastFrom: "data.requiredMessage", saveAs: "requiredToastSnapshot" }),
      step("Action-3", "playwright", "feedback_create.description_input.fill", "在新建反馈表单的反馈描述输入区域输入 `ORF默认页反馈创建E2E-描述内容`", "feedback_create.description_input", "fill", { valueFrom: "data.description" }),
      step("Action-4", "playwright", "feedback_create.owner_select.select", "在新建反馈表单的处理人选择框选择 `ORF Default Page Feedback Create E2E`", "feedback_create.owner_select", "select", { labelFrom: "data.owner" }),
      step("Action-5", "playwright", "feedback_create.category_select.select", "在新建反馈表单的分类选择框选择 `技术问题`", "feedback_create.category_select", "select", { labelFrom: "data.category" }),
      step("Action-6", "playwright", "feedback_create.impact_select.select", "在新建反馈表单的影响等级选择框选择 `高`", "feedback_create.impact_select", "select", { labelFrom: "data.impactLabel", valueFrom: "data.impactValue" }),
      step("Action-7", "playwright", "feedback_create.submit.valid", "点击 新建反馈表单的提交操作", "feedback_create.submit", "click", { expectNavigateToFrom: "data.feedbackDetailPathPattern" }),
    ],
  },
  S1: {
    description: "必填校验提示可见，补齐有效信息后创建反馈 issue 成功",
    assertions: [
      step("S1-1", "playwright", "toast.required.visible", "反馈正文为空提交后，系统 应提示 `请填写标题、正文、分类和处理人`", "toast_snapshot", "visible", { snapshotFrom: "runtime.requiredToastSnapshot", textFrom: "data.requiredMessage" }),
      step("S1-2", "playwright", "feedback_create.page.stayed", "当前页面 应为 新建反馈页面", "page_snapshot", "url_matches", { snapshotFrom: "runtime.requiredToastSnapshot", patternFrom: "data.createFeedbackPathPattern" }),
      step("S1-3", "playwright", "feedback_issue_detail.page.visible", "有效反馈信息提交后，当前页面 应为 新创建反馈 issue 的详情页", "feedback_issue_detail.page", "visible", { patternFrom: "data.feedbackDetailPathPattern" }),
      step("S1-4", "playwright", "feedback_issue_detail.title.visible", "新创建反馈 issue 详情页 应显示 `ORF默认页反馈创建E2E-标题`", "feedback_issue_detail.title", "visible", { valueFrom: "data.title" }),
      step("S1-5", "playwright", "feedback_issue_detail.description.visible", "新创建反馈 issue 详情页 应显示 `ORF默认页反馈创建E2E-描述内容`", "feedback_issue_detail.description", "visible", { valueFrom: "data.description" }),
      step("S1-6", "playwright", "feedback_issue_detail.category.visible", "新创建反馈 issue 详情页 应显示 分类为 `技术问题`", "feedback_issue_detail.category", "visible", { labelFrom: "data.category" }),
      step("S1-7", "playwright", "feedback_issue_detail.impact.visible", "新创建反馈 issue 详情页 应显示 影响等级为 `高`", "feedback_issue_detail.impact", "visible", { labelFrom: "data.impactLabel" }),
      step("S1-8", "prisma", "db.feedback.exists", "现象为 `ORF默认页反馈创建E2E-标题` 的反馈 issue 应存在", "db.feedback", "exists", { phenomenonFrom: "data.title" }),
      step("S1-9", "api", "session.authenticated.after_submit", "当前会话 应仍为 邮箱为 `orf-default-page-feedback-create-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.email", roleFrom: "data.role", status: "active" }),
    ],
  },
  Clean: {
    description: "删除新建反馈创建测试 issue 和测试用户并恢复未登录基准状态",
    steps: [
      step("Clean-1", "api", "auth.logout", "注销当前登录会话", "auth", "logout"),
      step("Clean-2", "playwright", "page.runtime.stop", "离开当前 ORF 前端页面", "page.runtime", "stop"),
      step("Clean-3", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Clean-4", "prisma", "db.feedback.delete_created", "删除现象为 `ORF默认页反馈创建E2E-标题` 的新建反馈创建测试 issue", "db.feedback", "delete_by_phenomenon", { phenomenonFrom: "data.title" }),
      step("Clean-5", "api", "ory.sessions.revoke", "撤销邮箱为 `orf-default-page-feedback-create-e2e@orf.local` 的新建反馈创建测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.email" }),
      step("Clean-6", "api", "ory.identity.delete", "删除邮箱为 `orf-default-page-feedback-create-e2e@orf.local` 的新建反馈创建测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.email" }),
      step("Clean-7", "api", "preferences.default_landing_path.reset", "恢复邮箱为 `orf-default-page-feedback-create-e2e@orf.local` 的默认进入页面为 系统默认", "user.preferences", "reset_default_landing_path_by_email", { emailFrom: "data.email" }),
      step("Clean-8", "prisma", "db.user.memberships.delete", "删除邮箱为 `orf-default-page-feedback-create-e2e@orf.local` 的新建反馈创建测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.email" }),
      step("Clean-9", "prisma", "db.user.delete", "删除邮箱为 `orf-default-page-feedback-create-e2e@orf.local` 的新建反馈创建测试用户", "db.user", "delete", { emailFrom: "data.email" }),
      step("Clean-10", "prisma", "db.feedback.absent.after_clean", "现象为 `ORF默认页反馈创建E2E-标题` 的反馈 issue 应不存在", "db.feedback", "absent", { phenomenonFrom: "data.title" }),
      step("Clean-11", "api", "ory.identity.absent", "邮箱为 `orf-default-page-feedback-create-e2e@orf.local` 的新建反馈创建测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.email" }),
      step("Clean-12", "prisma", "db.user.absent", "邮箱为 `orf-default-page-feedback-create-e2e@orf.local` 的新建反馈创建测试用户 应不存在", "db.user", "absent", { emailFrom: "data.email" }),
    ],
  },
} satisfies StateCaseSpec<FeedbackCreateSubmitCaseData>;
