import { STATE_CASE_MODEL, type StateCaseSpec } from "../../../../_framework/types";
import type { AdminSettleLootCaseData } from "./_support/admin-settle-loot.context";

export const adminSettleLootCase = {
  id: "target.admin-settle-loot",
  title: "管理员在已验收阶段可点击去结算成功结算后目标进入已结算阶段",
  model: STATE_CASE_MODEL,
  tags: ["target", "loot", "settlement", "admin"],

  data: {
    adminEmail: "orf-admin-settle-loot-e2e@orf.local",
    adminPassword: "OrfAdminSettleLootE2E!2026",
    adminName: "ORF Admin Settle Loot E2E",
    adminRole: "admin",
    adminStatus: "active",
    memberEmail: "orf-member-settle-loot-e2e@orf.local",
    memberPassword: "OrfMemberSettleLootE2E!2026",
    memberName: "ORF Member Settle Loot E2E",
    memberRole: "member",
    memberStatus: "active",
    targetPrefix: "E2E-TARGET-ADMIN-SETTLE-LOOT",
    target: {
      title: "E2E-TARGET-ADMIN-SETTLE-LOOT",
      stage: "goalFrozen",
      flowStatus: "accepted",
      finalDueOffsetDays: 8,
    },
    settledTarget: {
      title: "E2E-TARGET-ADMIN-SETTLE-LOOT",
      stage: "goalFrozen",
      flowStatus: "settled",
      finalDueOffsetDays: 8,
    },
    metric: {
      title: "E2E-METRIC-ADMIN-SETTLE-LOOT",
      difficulty: "进阶",
      score: 30,
      claim: "completed",
      finalEvidence: "E2E-ADMIN-SETTLE-LOOT-EVIDENCE：https://example.test/admin-settle-loot",
      acceptedResult: "completed",
    },
    finalLoot: {
      body: "E2E-ADMIN-SETTLE-LOOT-BODY：正式验收材料已通过，等待结算。",
      selfTestReportBody: "E2E-ADMIN-SETTLE-LOOT-SELF-TEST：结算前已完成自测。",
    },
    acceptanceResult: "completed",
    acceptanceReviewReason: "E2E-ADMIN-SETTLE-LOOT-ACCEPT：管理员已确认验收通过。",
    settlement: {
      basePoints: 30,
      completionMultiplier: 1,
      eventKind: "finalCompletion",
      reason: "指挥官确认最终结算比例",
      settlementPoints: 30,
    },
  },

  B: {
    description: "基准状态",
    assertions: [
      { source: { caseStepId: "B-1", method: "api" }, id: "frontend.ready", title: "前端服务 应可用", object: "frontend.service", operator: "available" },
      { source: { caseStepId: "B-2", method: "api" }, id: "backend.ready", title: "后端服务 应可用", object: "api.health", operator: "ok" },
      { source: { caseStepId: "B-3", method: "prisma" }, id: "db.ready", title: "ORF 数据库 应可连接", object: "db", operator: "ready" },
      { source: { caseStepId: "B-4", method: "api" }, id: "session.unauthenticated", title: "当前会话 应为 未登录", object: "auth.session", operator: "unauthenticated" },
      { source: { caseStepId: "B-5", method: "playwright" }, id: "storage.empty", title: "当前浏览器 应不保留本地登录态", object: "browser.auth_storage", operator: "empty" },
    ],
  },

  Setup: {
    description: "构造 S0",
    steps: [
      { source: { caseStepId: "Setup-1", method: "prisma" }, id: "db.objectives.delete_residue", title: "删除 本用例残留的目标标题前缀 `E2E-TARGET-ADMIN-SETTLE-LOOT` 对应的目标及其派生数据", object: "db.objectives_by_prefix", operator: "delete", params: { prefixFrom: "data.targetPrefix" } },
      { source: { caseStepId: "Setup-2", method: "api" }, id: "ory.admin_identity.upsert", title: "准备邮箱为 `orf-admin-settle-loot-e2e@orf.local`、使用固定测试密码的管理员登录身份", object: "ory.identity", operator: "upsert_password", params: { emailFrom: "data.adminEmail", nameFrom: "data.adminName", passwordFrom: "data.adminPassword", saveAs: "adminIdentity" } },
      { source: { caseStepId: "Setup-3", method: "prisma" }, id: "db.admin_user.upsert", title: "准备 角色为 `admin`、状态为 `active`、名称为 `ORF Admin Settle Loot E2E` 的本用例管理员用户", object: "db.user", operator: "upsert", params: { emailFrom: "data.adminEmail", nameFrom: "data.adminName", roleFrom: "data.adminRole", statusFrom: "data.adminStatus", identityIdFrom: "runtime.adminIdentity.id", saveAs: "adminUser" } },
      { source: { caseStepId: "Setup-4", method: "api" }, id: "ory.member_identity.upsert", title: "准备邮箱为 `orf-member-settle-loot-e2e@orf.local`、使用固定测试密码的普通成员登录身份", object: "ory.identity", operator: "upsert_password", params: { emailFrom: "data.memberEmail", nameFrom: "data.memberName", passwordFrom: "data.memberPassword", saveAs: "memberIdentity" } },
      { source: { caseStepId: "Setup-5", method: "prisma" }, id: "db.member_user.upsert", title: "准备 角色为 `member`、状态为 `active`、名称为 `ORF Member Settle Loot E2E` 的本用例普通成员用户", object: "db.user", operator: "upsert", params: { emailFrom: "data.memberEmail", nameFrom: "data.memberName", roleFrom: "data.memberRole", statusFrom: "data.memberStatus", identityIdFrom: "runtime.memberIdentity.id", saveAs: "memberUser" } },
      { source: { caseStepId: "Setup-6", method: "prisma" }, id: "db.accepted_objective.prepare", title: "准备 标题为 `E2E-TARGET-ADMIN-SETTLE-LOOT`、阶段为 `goalFrozen`、流转状态为 `accepted`、最终验收截止日为运行时当前日期后 `8` 天、冻结时间存在、战利品提交时间存在、验收通过时间存在、验收结果为 `completed`、目标基础积分为 `30`、当前挑战者仅包含本用例普通成员的目标", object: "db.accepted_objective_fixture", operator: "prepare", params: { adminUserFrom: "runtime.adminUser", memberUserFrom: "runtime.memberUser", settlementFrom: "data.settlement", targetFrom: "data.target", saveAs: "objective" } },
      { source: { caseStepId: "Setup-7", method: "prisma" }, id: "db.metric.prepare_accepted", title: "准备 归属于目标 `E2E-TARGET-ADMIN-SETTLE-LOOT`、口径为 `E2E-METRIC-ADMIN-SETTLE-LOOT`、等级积分等级为 `进阶`、等级积分为 `30`、验收结果为 `completed` 的指标", object: "db.metric", operator: "prepare_accepted", params: { targetFrom: "data.target", metricFrom: "data.metric", memberUserFrom: "runtime.memberUser", saveAs: "metric" } },
      { source: { caseStepId: "Setup-8", method: "prisma" }, id: "db.objective_loot.prepare_final", title: "准备 归属于目标 `E2E-TARGET-ADMIN-SETTLE-LOOT`、提交人为本用例普通成员、完成说明为 `E2E-ADMIN-SETTLE-LOOT-BODY：正式验收材料已通过，等待结算。`、自测报告为 `E2E-ADMIN-SETTLE-LOOT-SELF-TEST：结算前已完成自测。`、指标 `E2E-METRIC-ADMIN-SETTLE-LOOT` 的完成主张为 `completed`、证据为 `E2E-ADMIN-SETTLE-LOOT-EVIDENCE：https://example.test/admin-settle-loot` 的战利品正式提交记录", object: "db.objective_loot", operator: "prepare_final", params: { targetFrom: "data.target", metricFrom: "data.metric", finalLootFrom: "data.finalLoot", memberUserFrom: "runtime.memberUser", saveAs: "objectiveLoot" } },
      { source: { caseStepId: "Setup-9", method: "prisma" }, id: "db.acceptance_review.prepare_completed", title: "准备 归属于目标 `E2E-TARGET-ADMIN-SETTLE-LOOT`、审核人为本用例管理员、验收结果为 `completed`、验收说明为 `E2E-ADMIN-SETTLE-LOOT-ACCEPT：管理员已确认验收通过。` 的验收记录", object: "db.objective_acceptance_review", operator: "prepare_completed", params: { targetFrom: "data.target", metricFrom: "data.metric", acceptanceResultFrom: "data.acceptanceResult", reasonFrom: "data.acceptanceReviewReason", adminUserFrom: "runtime.adminUser" } },
      { source: { caseStepId: "Setup-10", method: "prisma" }, id: "db.settlement_events.delete_final", title: "确保 归属于目标 `E2E-TARGET-ADMIN-SETTLE-LOOT` 的最终结算事件不存在", object: "db.objective_settlement_events", operator: "delete_final_completion", params: { targetFrom: "data.target" } },
      { source: { caseStepId: "Setup-11", method: "prisma" }, id: "db.point_ledger.delete_by_target", title: "确保 归属于目标 `E2E-TARGET-ADMIN-SETTLE-LOOT` 的积分流水不存在", object: "db.point_ledger", operator: "delete_by_target", params: { targetFrom: "data.target" } },
      { source: { caseStepId: "Setup-12", method: "playwright" }, id: "auth.login.admin", title: "使用 本用例管理员账号 登录 ORF", object: "page.auth", operator: "login", params: { emailFrom: "data.adminEmail", passwordFrom: "data.adminPassword" } },
    ],
  },

  S0: {
    description: "Action 前状态",
    assertions: [
      { source: { caseStepId: "S0-1", method: "api" }, id: "session.authenticated", title: "当前会话 应为 已登录", object: "auth.session", operator: "authenticated" },
      { source: { caseStepId: "S0-2", method: "api" }, id: "session.email", title: "当前会话用户邮箱 应为 `orf-admin-settle-loot-e2e@orf.local`", object: "auth.session.user_email", operator: "equals", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "S0-3", method: "api" }, id: "session.role", title: "当前会话用户角色 应为 `admin`", object: "auth.session.user_role", operator: "equals", params: { roleFrom: "data.adminRole" } },
      { source: { caseStepId: "S0-4", method: "api" }, id: "session.name", title: "当前会话用户名称 应为 `ORF Admin Settle Loot E2E`", object: "auth.session.user_name", operator: "equals", params: { nameFrom: "data.adminName" } },
      { source: { caseStepId: "S0-5", method: "prisma" }, id: "db.accepted_objective.exists", title: "应存在 标题为 `E2E-TARGET-ADMIN-SETTLE-LOOT`、阶段为 `goalFrozen`、流转状态为 `accepted` 的目标", object: "db.accepted_objective_fixture", operator: "exists", params: { targetFrom: "data.target" } },
      { source: { caseStepId: "S0-6", method: "prisma" }, id: "db.accepted_objective.only_challenger", title: "目标 `E2E-TARGET-ADMIN-SETTLE-LOOT` 的当前挑战者 应仅包含本用例普通成员", object: "db.accepted_objective_fixture", operator: "only_challenger", params: { targetFrom: "data.target", memberUserFrom: "runtime.memberUser" } },
      { source: { caseStepId: "S0-7", method: "prisma" }, id: "db.accepted_objective.accepted_at", title: "目标 `E2E-TARGET-ADMIN-SETTLE-LOOT` 的验收通过时间 应存在", object: "db.accepted_objective_fixture", operator: "accepted_at_exists", params: { targetFrom: "data.target" } },
      { source: { caseStepId: "S0-8", method: "prisma" }, id: "db.accepted_objective.accepted_result", title: "目标 `E2E-TARGET-ADMIN-SETTLE-LOOT` 的验收结果 应为 `completed`", object: "db.accepted_objective_fixture", operator: "accepted_result", params: { targetFrom: "data.target", acceptanceResultFrom: "data.acceptanceResult" } },
      { source: { caseStepId: "S0-9", method: "prisma" }, id: "db.accepted_objective.base_points", title: "目标 `E2E-TARGET-ADMIN-SETTLE-LOOT` 的目标基础积分 应为 `30`", object: "db.accepted_objective_fixture", operator: "base_points", params: { targetFrom: "data.target", pointsFrom: "data.settlement.basePoints" } },
      { source: { caseStepId: "S0-10", method: "prisma" }, id: "db.accepted_objective.settlement_points_empty", title: "目标 `E2E-TARGET-ADMIN-SETTLE-LOOT` 的目标累计结算积分 应为空", object: "db.accepted_objective_fixture", operator: "settlement_points_empty", params: { targetFrom: "data.target" } },
      { source: { caseStepId: "S0-11", method: "prisma" }, id: "db.metric.exists_accepted", title: "应存在 归属于目标 `E2E-TARGET-ADMIN-SETTLE-LOOT`、口径为 `E2E-METRIC-ADMIN-SETTLE-LOOT`、验收结果为 `completed` 的指标", object: "db.metric", operator: "exists_accepted", params: { targetFrom: "data.target", titleFrom: "data.metric.title", difficultyFrom: "data.metric.difficulty", scoreFrom: "data.metric.score", acceptedResultFrom: "data.metric.acceptedResult" } },
      { source: { caseStepId: "S0-12", method: "prisma" }, id: "db.objective_loot.exists", title: "应存在 归属于目标 `E2E-TARGET-ADMIN-SETTLE-LOOT`、提交人为本用例普通成员、完成说明为 `E2E-ADMIN-SETTLE-LOOT-BODY：正式验收材料已通过，等待结算。` 的战利品正式提交记录", object: "db.objective_loot", operator: "exists", params: { targetFrom: "data.target", finalLootFrom: "data.finalLoot", memberUserFrom: "runtime.memberUser" } },
      { source: { caseStepId: "S0-13", method: "prisma" }, id: "db.acceptance_review.exists", title: "应存在 归属于目标 `E2E-TARGET-ADMIN-SETTLE-LOOT`、审核人为本用例管理员、验收结果为 `completed` 的验收记录", object: "db.objective_acceptance_review", operator: "exists", params: { targetFrom: "data.target", metricFrom: "data.metric", acceptanceResultFrom: "data.acceptanceResult", adminUserFrom: "runtime.adminUser" } },
      { source: { caseStepId: "S0-14", method: "prisma" }, id: "db.settlement_events.final_count_zero", title: "目标 `E2E-TARGET-ADMIN-SETTLE-LOOT` 的最终结算事件数量 应为 `0`", object: "db.objective_settlement_events", operator: "final_completion_count", params: { targetFrom: "data.target", count: 0 } },
      { source: { caseStepId: "S0-15", method: "prisma" }, id: "db.point_ledger.count_zero", title: "目标 `E2E-TARGET-ADMIN-SETTLE-LOOT` 的积分流水数量 应为 `0`", object: "db.point_ledger", operator: "count", params: { targetFrom: "data.target", count: 0 } },
    ],
  },

  Action: {
    description: "被测业务动作",
    steps: [
      { source: { caseStepId: "Action-1", method: "playwright" }, id: "admin.open_my_challenges", title: "管理员打开 我的挑战", object: "page.challenge", operator: "open_my_challenges" },
      { source: { caseStepId: "Action-2", method: "playwright" }, id: "objective.visible", title: "我的挑战列表 应显示目标 `E2E-TARGET-ADMIN-SETTLE-LOOT`", object: "page.challenge_objectives", operator: "visible_title", params: { titleFrom: "data.target.title" } },
      { source: { caseStepId: "Action-3", method: "playwright" }, id: "objective.status.accepted", title: "目标 `E2E-TARGET-ADMIN-SETTLE-LOOT` 的状态 应显示为 已验收", object: "page.challenge_objective", operator: "status_visible", params: { titleFrom: "data.target.title", statusLabel: "已验收" } },
      { source: { caseStepId: "Action-4", method: "playwright" }, id: "objective.settle_action.visible", title: "目标 `E2E-TARGET-ADMIN-SETTLE-LOOT` 的 \"去结算\" 操作 应可见", object: "page.challenge_objective", operator: "action_visible", params: { titleFrom: "data.target.title", actionLabel: "去结算" } },
      { source: { caseStepId: "Action-5", method: "playwright" }, id: "objective.settle_action.enabled", title: "目标 `E2E-TARGET-ADMIN-SETTLE-LOOT` 的 \"去结算\" 操作 应可点击", object: "page.challenge_objective", operator: "action_enabled", params: { titleFrom: "data.target.title", actionLabel: "去结算" } },
      { source: { caseStepId: "Action-6", method: "playwright" }, id: "settlement.open", title: "点击目标 `E2E-TARGET-ADMIN-SETTLE-LOOT` 的 \"去结算\" 操作", object: "page.settlement", operator: "open_from_objective", params: { targetTitleFrom: "data.target.title" } },
      { source: { caseStepId: "Action-7", method: "playwright" }, id: "settlement.page.loaded", title: "等待 确认结算页面加载完成", object: "page.settlement", operator: "loaded", params: { targetTitleFrom: "data.target.title" } },
      { source: { caseStepId: "Action-8", method: "playwright" }, id: "settlement.target.visible", title: "页面 应显示目标 `E2E-TARGET-ADMIN-SETTLE-LOOT`", object: "page.settlement", operator: "target_visible", params: { targetTitleFrom: "data.target.title" } },
      { source: { caseStepId: "Action-9", method: "playwright" }, id: "settlement.peer_result.visible", title: "页面 应显示 `匿名互评贡献结果`", object: "page.settlement", operator: "text_visible", params: { text: "匿名互评贡献结果" } },
      { source: { caseStepId: "Action-10", method: "playwright" }, id: "settlement.single_ratio.visible", title: "页面 应显示本用例普通成员的默认贡献比例 `100%`", object: "page.settlement", operator: "single_ratio_visible", params: { memberNameFrom: "data.memberName", percent: "100%" } },
      { source: { caseStepId: "Action-11", method: "playwright" }, id: "settlement.submit.enabled", title: "\"确认结算\" 操作 应可点击", object: "page.settlement", operator: "submit_enabled", params: { label: "确认结算" } },
      { source: { caseStepId: "Action-12", method: "playwright" }, id: "settlement.submit", title: "点击 \"确认结算\" 操作", object: "page.settlement", operator: "submit", params: { settledTargetFrom: "data.settledTarget", settlementFrom: "data.settlement" } },
      { source: { caseStepId: "Action-13", method: "api" }, id: "api.settlement.submit_result", title: "目标结算结果 应成功，并记录 本用例最终结算事件", object: "api.settlement", operator: "submit_result_success", params: { targetFrom: "data.settledTarget", settlementFrom: "data.settlement", adminUserFrom: "runtime.adminUser", saveAs: "settlementEvent" } },
    ],
  },

  S1: {
    description: "Action 后状态",
    assertions: [
      { source: { caseStepId: "S1-1", method: "playwright" }, id: "toast.settled", title: "页面 应提示 目标已结算", object: "page.challenge_toast", operator: "settled" },
      { source: { caseStepId: "S1-2", method: "playwright" }, id: "reports.page.url", title: "页面 应进入 数据统计页", object: "page.reports", operator: "url" },
      { source: { caseStepId: "S1-3", method: "api" }, id: "api.all_challenges.contains_objective", title: "所有挑战数据 应包含目标 `E2E-TARGET-ADMIN-SETTLE-LOOT`", object: "api.all_challenges", operator: "contains_objective", params: { titleFrom: "data.target.title" } },
      { source: { caseStepId: "S1-4", method: "api" }, id: "api.all_challenges.objective_stage_flow", title: "所有挑战数据中目标 `E2E-TARGET-ADMIN-SETTLE-LOOT` 的阶段 应为 `goalFrozen`，流转状态 应为 `settled`", object: "api.all_challenges", operator: "objective_stage_flow", params: { targetFrom: "data.settledTarget" } },
      { source: { caseStepId: "S1-5", method: "api" }, id: "api.all_challenges.accepted_result", title: "所有挑战数据中目标 `E2E-TARGET-ADMIN-SETTLE-LOOT` 的验收结果 应为 `completed`", object: "api.all_challenges", operator: "accepted_result", params: { titleFrom: "data.target.title", acceptanceResultFrom: "data.acceptanceResult" } },
      { source: { caseStepId: "S1-6", method: "api" }, id: "api.all_challenges.base_points", title: "所有挑战数据中目标 `E2E-TARGET-ADMIN-SETTLE-LOOT` 的目标基础积分 应为 `30`", object: "api.all_challenges", operator: "objective_base_points", params: { titleFrom: "data.target.title", pointsFrom: "data.settlement.basePoints" } },
      { source: { caseStepId: "S1-7", method: "api" }, id: "api.all_challenges.settlement_points", title: "所有挑战数据中目标 `E2E-TARGET-ADMIN-SETTLE-LOOT` 的目标累计结算积分 应为 `30`", object: "api.all_challenges", operator: "objective_settlement_points", params: { titleFrom: "data.target.title", pointsFrom: "data.settlement.settlementPoints" } },
      { source: { caseStepId: "S1-8", method: "api" }, id: "api.all_challenges.settlement_event", title: "所有挑战数据中目标 `E2E-TARGET-ADMIN-SETTLE-LOOT` 应包含类型为 `finalCompletion`、基础积分为 `30`、结算倍数为 `1`、结算积分为 `30`、创建人为本用例管理员的最终结算事件", object: "api.all_challenges", operator: "contains_final_settlement_event", params: { targetFrom: "data.settledTarget", settlementFrom: "data.settlement", adminUserFrom: "runtime.adminUser" } },
      { source: { caseStepId: "S1-9", method: "api" }, id: "api.all_challenges.point_ledger", title: "所有挑战数据中目标 `E2E-TARGET-ADMIN-SETTLE-LOOT` 应包含本用例普通成员获得 `30` 分、原因为 `指挥官确认最终结算比例` 的积分流水", object: "api.all_challenges", operator: "contains_point_ledger", params: { targetFrom: "data.settledTarget", settlementFrom: "data.settlement", memberUserFrom: "runtime.memberUser" } },
      { source: { caseStepId: "S1-10", method: "prisma" }, id: "db.settled_objective.exists", title: "标题为 `E2E-TARGET-ADMIN-SETTLE-LOOT` 的目标阶段 应为 `goalFrozen`，流转状态 应为 `settled`", object: "db.settled_objective_fixture", operator: "exists", params: { targetFrom: "data.settledTarget" } },
      { source: { caseStepId: "S1-11", method: "prisma" }, id: "db.settled_objective.accepted_result_still", title: "目标 `E2E-TARGET-ADMIN-SETTLE-LOOT` 的验收结果 应保持 `completed`", object: "db.settled_objective_fixture", operator: "accepted_result", params: { targetFrom: "data.settledTarget", acceptanceResultFrom: "data.acceptanceResult" } },
      { source: { caseStepId: "S1-12", method: "prisma" }, id: "db.settled_objective.base_points", title: "目标 `E2E-TARGET-ADMIN-SETTLE-LOOT` 的目标基础积分 应为 `30`", object: "db.settled_objective_fixture", operator: "base_points", params: { targetFrom: "data.settledTarget", pointsFrom: "data.settlement.basePoints" } },
      { source: { caseStepId: "S1-13", method: "prisma" }, id: "db.settled_objective.settlement_points", title: "目标 `E2E-TARGET-ADMIN-SETTLE-LOOT` 的目标累计结算积分 应为 `30`", object: "db.settled_objective_fixture", operator: "settlement_points", params: { targetFrom: "data.settledTarget", pointsFrom: "data.settlement.settlementPoints" } },
      { source: { caseStepId: "S1-14", method: "prisma" }, id: "db.settled_objective.completion_multiplier", title: "目标 `E2E-TARGET-ADMIN-SETTLE-LOOT` 的完成倍数 应为 `1`", object: "db.settled_objective_fixture", operator: "completion_multiplier", params: { targetFrom: "data.settledTarget", multiplierFrom: "data.settlement.completionMultiplier" } },
      { source: { caseStepId: "S1-15", method: "prisma" }, id: "db.settlement_event.exists", title: "应存在 归属于目标 `E2E-TARGET-ADMIN-SETTLE-LOOT`、类型为 `finalCompletion`、基础积分为 `30`、结算倍数为 `1`、结算积分为 `30`、创建人为本用例管理员的最终结算事件", object: "db.objective_settlement_events", operator: "exists_final_completion", params: { targetFrom: "data.settledTarget", settlementFrom: "data.settlement", adminUserFrom: "runtime.adminUser" } },
      { source: { caseStepId: "S1-16", method: "prisma" }, id: "db.point_ledger.exists", title: "应存在 归属于目标 `E2E-TARGET-ADMIN-SETTLE-LOOT`、成员为本用例普通成员、积分为 `30`、原因为 `指挥官确认最终结算比例`、关联本用例最终结算事件的积分流水", object: "db.point_ledger", operator: "exists_for_final_settlement", params: { targetFrom: "data.settledTarget", settlementFrom: "data.settlement", memberUserFrom: "runtime.memberUser" } },
      { source: { caseStepId: "S1-17", method: "prisma" }, id: "db.metric.accepted_result_still", title: "指标 `E2E-METRIC-ADMIN-SETTLE-LOOT` 的验收结果 应保持 `completed`", object: "db.metric", operator: "accepted_result", params: { titleFrom: "data.metric.title", acceptedResultFrom: "data.metric.acceptedResult" } },
      { source: { caseStepId: "S1-18", method: "prisma" }, id: "db.acceptance_review.exists_after_settlement", title: "应存在 归属于目标 `E2E-TARGET-ADMIN-SETTLE-LOOT`、审核人为本用例管理员、验收结果为 `completed` 的验收记录", object: "db.objective_acceptance_review", operator: "exists", params: { targetFrom: "data.settledTarget", metricFrom: "data.metric", acceptanceResultFrom: "data.acceptanceResult", adminUserFrom: "runtime.adminUser" } },
      { source: { caseStepId: "S1-19", method: "prisma" }, id: "db.settled_objective.challenger_still", title: "目标 `E2E-TARGET-ADMIN-SETTLE-LOOT` 的当前挑战者 应仍包含本用例普通成员", object: "db.settled_objective_fixture", operator: "challenger_contains", params: { targetFrom: "data.settledTarget", memberUserFrom: "runtime.memberUser" } },
    ],
  },

  Clean: {
    description: "恢复 B",
    steps: [
      { source: { caseStepId: "Clean-1", method: "prisma" }, id: "db.objectives.delete_created", title: "删除 本用例创建的目标标题前缀 `E2E-TARGET-ADMIN-SETTLE-LOOT` 对应的目标及其派生数据", object: "db.objectives_by_prefix", operator: "delete", params: { prefixFrom: "data.targetPrefix" } },
      { source: { caseStepId: "Clean-2", method: "api" }, id: "auth.logout", title: "注销当前管理员登录会话", object: "auth", operator: "logout" },
      { source: { caseStepId: "Clean-3", method: "playwright" }, id: "browser.clear", title: "移除当前浏览器中的残留登录态", object: "browser", operator: "clear_state" },
      { source: { caseStepId: "Clean-4", method: "api" }, id: "ory.admin_identity.delete", title: "删除 本用例管理员登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-5", method: "api" }, id: "ory.member_identity.delete", title: "删除 本用例普通成员登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-6", method: "prisma" }, id: "db.admin_user.delete", title: "删除 本用例管理员用户", object: "db.user", operator: "delete", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-7", method: "prisma" }, id: "db.member_user.delete", title: "删除 本用例普通成员用户", object: "db.user", operator: "delete", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-8", method: "prisma" }, id: "db.objectives.absent", title: "应不存在 标题前缀为 `E2E-TARGET-ADMIN-SETTLE-LOOT` 的目标", object: "db.objectives_by_prefix", operator: "absent", params: { prefixFrom: "data.targetPrefix" } },
      { source: { caseStepId: "Clean-9", method: "prisma" }, id: "db.metric.absent", title: "应不存在 口径为 `E2E-METRIC-ADMIN-SETTLE-LOOT` 的指标", object: "db.metric", operator: "absent", params: { titleFrom: "data.metric.title" } },
      { source: { caseStepId: "Clean-10", method: "api" }, id: "ory.admin_identity.absent", title: "邮箱为 `orf-admin-settle-loot-e2e@orf.local` 的管理员登录身份 应不存在", object: "ory.identity", operator: "absent", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-11", method: "api" }, id: "ory.member_identity.absent", title: "邮箱为 `orf-member-settle-loot-e2e@orf.local` 的普通成员登录身份 应不存在", object: "ory.identity", operator: "absent", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-12", method: "prisma" }, id: "db.admin_user.absent", title: "邮箱为 `orf-admin-settle-loot-e2e@orf.local` 的管理员用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-13", method: "prisma" }, id: "db.member_user.absent", title: "邮箱为 `orf-member-settle-loot-e2e@orf.local` 的普通成员用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-14", method: "api" }, id: "session.unauthenticated", title: "当前会话 应为 未登录", object: "auth.session", operator: "unauthenticated" },
    ],
  },
} satisfies StateCaseSpec<AdminSettleLootCaseData>;
