import { STATE_CASE_MODEL, type StateCaseSpec } from "../../_framework/types";
import type { MemberSubmitPeerReviewCaseData } from "./_support/member-submit-peer-review.context";

export const memberSubmitPeerReviewCase = {
  id: "acceptance.member-submit-peer-review",
  title: "成员提交匿名互评",
  model: STATE_CASE_MODEL,
  tags: ["acceptance", "peer-review", "member", "happy-path"],

  data: {
    email: "orf-member-submit-peer-review-e2e@orf.local",
    password: "OrfMemberSubmitPeerReviewE2E!2026",
    name: "ORF Member Submit Peer Review E2E",
    role: "member",
    objectiveId: "obj-testd-member-submit-peer-review",
    objectiveTitle: "E2E-MEMBER-SUBMIT-PEER-REVIEW: 目标前置",
    lootBody: "E2E-PEER-LOOT-BODY: 匿名互评前置战利品",
    ratio: "1",
  },

  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      {
        source: { caseStepId: "B-1", method: "api" },
        id: "frontend.ready",
        title: "前端服务 应可用",
        object: "frontend.service",
        operator: "available",
      },
      {
        source: { caseStepId: "B-2", method: "api" },
        id: "backend.ready",
        title: "后端服务 应可用",
        object: "api.health",
        operator: "ok",
      },
      {
        source: { caseStepId: "B-3", method: "api" },
        id: "frontend.login_entry.accessible",
        title: "前端登录页入口 应可访问",
        object: "frontend.login_entry",
        operator: "accessible",
      },
      {
        source: { caseStepId: "B-4", method: "api" },
        id: "session.endpoint.accessible",
        title: "当前会话查询能力 应可用",
        object: "auth.session",
        operator: "accessible",
      },
      {
        source: { caseStepId: "B-5", method: "prisma" },
        id: "db.ready",
        title: "ORF 数据库 应可连接",
        object: "db",
        operator: "ready",
      },
      {
        source: { caseStepId: "B-6", method: "prisma" },
        id: "db.schema.current",
        title: "ORF 数据库 schema 应为 当前测试版本",
        object: "db.schema",
        operator: "current",
      },
      {
        source: { caseStepId: "B-7", method: "api" },
        id: "ory.admin_public.ready",
        title: "Ory/Kratos 认证服务的管理和公共访问能力 应可用",
        object: "ory.admin_public",
        operator: "ready",
      },
      {
        source: { caseStepId: "B-8", method: "api" },
        id: "session.unauthenticated",
        title: "当前会话 应为 未登录",
        object: "auth.session",
        operator: "unauthenticated",
      },
      {
        source: { caseStepId: "B-9", method: "playwright" },
        id: "cookie.absent",
        title: "当前浏览器 应不存在 Ory 登录会话 cookie",
        object: "browser.cookie",
        operator: "absent",
      },
      {
        source: { caseStepId: "B-10", method: "playwright" },
        id: "storage.empty",
        title: "当前浏览器 应不保留本地登录态",
        object: "browser.auth_storage",
        operator: "empty",
      },
    ],
  },

  Setup: {
    description: "准备普通成员账号、本用例独占 submitted 目标和前置战利品，登录普通成员并进入战利品页面",
    steps: [
      {
        source: { caseStepId: "Setup-1", method: "prisma" },
        id: "db.peer_review.delete_residue",
        title: "删除可能残留的本用例普通成员匿名互评记录",
        object: "db.peer_review",
        operator: "delete",
        params: { reviewerFrom: "data.name" },
      },
      {
        source: { caseStepId: "Setup-2", method: "prisma" },
        id: "db.peer_review_loot.delete_residue",
        title: "删除可能残留的内容为 `E2E-PEER-LOOT-BODY: 匿名互评前置战利品` 的测试战利品",
        object: "db.peer_review_loot",
        operator: "delete",
        params: { bodyFrom: "data.lootBody" },
      },
      {
        source: { caseStepId: "Setup-3", method: "prisma" },
        id: "db.objective.delete_residue",
        title: "删除可能残留的标题为 `E2E-MEMBER-SUBMIT-PEER-REVIEW: 目标前置` 的本用例目标及其派生数据",
        object: "db.objective",
        operator: "delete_by_title",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Setup-4", method: "api" },
        id: "ory.member_identity.upsert",
        title: "准备邮箱为 `orf-member-submit-peer-review-e2e@orf.local`、使用固定测试密码的普通成员登录身份",
        object: "ory.identity",
        operator: "upsert_password",
        params: {
          emailFrom: "data.email",
          nameFrom: "data.name",
          passwordFrom: "data.password",
          saveAs: "memberIdentity",
        },
      },
      {
        source: { caseStepId: "Setup-5", method: "prisma" },
        id: "db.member.upsert",
        title: "准备邮箱为 `orf-member-submit-peer-review-e2e@orf.local`、角色为 `member`、状态为 `active` 的普通成员用户和默认团队成员关系",
        object: "db.user",
        operator: "upsert",
        params: {
          emailFrom: "data.email",
          nameFrom: "data.name",
          roleFrom: "data.role",
          status: "active",
          identityIdFrom: "runtime.memberIdentity.id",
          saveAs: "memberUser",
        },
      },
      {
        source: { caseStepId: "Setup-6", method: "prisma" },
        id: "db.objective.upsert_peer_review_target",
        title: "创建标题为 `E2E-MEMBER-SUBMIT-PEER-REVIEW: 目标前置` 的本用例独占目标",
        object: "db.objective",
        operator: "upsert",
        params: {
          idFrom: "data.objectiveId",
          titleFrom: "data.objectiveTitle",
          teamIdFrom: "runtime.memberUser.teamId",
          stage: "goalFrozen",
          flowStatus: "submitted",
          status: "Draft",
          saveAs: "fixtureObjective",
        },
      },
      {
        source: { caseStepId: "Setup-7", method: "prisma" },
        id: "db.peer_review_target.from_objective",
        title: "记录 本用例独占目标",
        object: "db.peer_review_target",
        operator: "from_objective",
        params: { objectiveIdFrom: "runtime.fixtureObjective.id", saveAs: "peerReviewTarget" },
      },
      {
        source: { caseStepId: "Setup-8", method: "prisma" },
        id: "db.peer_review_target.prepare",
        title: "设置本用例目标为 `submitted`，记录 lootSubmittedAt，并设置挑战者列表仅包含普通成员",
        object: "db.peer_review_target",
        operator: "prepare",
        params: { targetFrom: "runtime.peerReviewTarget", memberNameFrom: "data.name" },
      },
      {
        source: { caseStepId: "Setup-9", method: "prisma" },
        id: "db.peer_review_loot.create",
        title: "为本用例目标创建内容为 `E2E-PEER-LOOT-BODY: 匿名互评前置战利品` 的前置战利品",
        object: "db.peer_review_loot",
        operator: "create",
        params: {
          targetFrom: "runtime.peerReviewTarget",
          bodyFrom: "data.lootBody",
          memberNameFrom: "data.name",
          saveAs: "peerReviewLoot",
        },
      },
      {
        source: { caseStepId: "Setup-10", method: "api" },
        id: "ory.member_sessions.revoke",
        title: "撤销普通成员登录身份可能残留的登录会话",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Setup-11", method: "playwright" },
        id: "browser.clear",
        title: "移除当前浏览器中的残留登录态",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "Setup-12", method: "playwright" },
        id: "page.goto.auth",
        title: "打开 ORF 登录页",
        object: "page",
        operator: "goto",
        params: { path: "/auth" },
      },
      {
        source: { caseStepId: "Setup-13", method: "playwright" },
        id: "fill.email",
        title: "在邮箱输入框输入普通成员固定测试邮箱",
        object: "page",
        operator: "fill",
        params: { label: "Email", valueFrom: "data.email" },
      },
      {
        source: { caseStepId: "Setup-14", method: "playwright" },
        id: "fill.password",
        title: "在密码输入框输入普通成员固定测试密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.password" },
      },
      {
        source: { caseStepId: "Setup-15", method: "playwright" },
        id: "click.sign_in",
        title: "点击 `Sign In` 登录操作",
        object: "page",
        operator: "click",
        params: { role: "button", name: "Sign In" },
      },
      {
        source: { caseStepId: "Setup-16", method: "api" },
        id: "session.member.authenticated",
        title: "当前会话 应为 普通成员的已登录会话",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      {
        source: { caseStepId: "Setup-17", method: "playwright" },
        id: "page.goto.loot",
        title: "打开 本用例目标战利品页面",
        object: "page.peer_review",
        operator: "goto",
        params: { targetFrom: "runtime.peerReviewTarget" },
      },
    ],
  },

  S0: {
    description: "普通成员已登录并位于本用例目标战利品页面，目标可提交匿名互评",
    assertions: [
      {
        source: { caseStepId: "S0-1", method: "api" },
        id: "session.member.authenticated",
        title: "当前会话 应为 邮箱 `orf-member-submit-peer-review-e2e@orf.local`、角色为 `member`、状态为 `active` 的已登录会话",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      {
        source: { caseStepId: "S0-2", method: "playwright" },
        id: "url.loot",
        title: "当前页面 应为 本用例目标战利品页面",
        object: "page.url",
        operator: "match",
        params: { pattern: "/objectives/.+/loot$" },
      },
      {
        source: { caseStepId: "S0-3", method: "playwright" },
        id: "peer_review_form.visible",
        title: "匿名互评表单 应可见",
        object: "page.peer_review_form",
        operator: "visible",
      },
      {
        source: { caseStepId: "S0-4", method: "prisma" },
        id: "db.peer_review_target.submitted_for_member",
        title: "本用例目标流转状态 应为 `submitted`、战利品提交时间已存在，且挑战者列表包含普通成员",
        object: "db.peer_review_target",
        operator: "submitted_for_member",
        params: { targetFrom: "runtime.peerReviewTarget", memberNameFrom: "data.name" },
      },
      {
        source: { caseStepId: "S0-5", method: "prisma" },
        id: "db.peer_review_loot.present",
        title: "本用例目标 应存在 测试战利品",
        object: "db.peer_review_loot",
        operator: "present",
        params: { targetFrom: "runtime.peerReviewTarget", lootFrom: "runtime.peerReviewLoot" },
      },
      {
        source: { caseStepId: "S0-6", method: "prisma" },
        id: "db.peer_review.absent",
        title: "本用例目标 应不存在 普通成员提交的匿名互评",
        object: "db.peer_review",
        operator: "absent",
        params: { targetFrom: "runtime.peerReviewTarget", reviewerFrom: "data.name" },
      },
    ],
  },

  Action: {
    description: "普通成员通过页面提交测试匿名互评",
    steps: [
      {
        source: { caseStepId: "Action-1", method: "playwright" },
        id: "fill.member_ratio",
        title: "填写 普通成员贡献比例输入框 为 `1`",
        object: "page",
        operator: "fill",
        params: { labelFrom: "data.name", valueFrom: "data.ratio" },
      },
      {
        source: { caseStepId: "Action-2", method: "api" },
        id: "capture.submit_peer_review_response",
        title: "监听 提交匿名互评请求响应",
        object: "api.peer_review_submit",
        operator: "capture_response",
        params: { targetFrom: "runtime.peerReviewTarget", saveAs: "submitPeerReviewResponse" },
      },
      {
        source: { caseStepId: "Action-3", method: "playwright" },
        id: "click.submit_peer_review",
        title: "点击 `提交匿名互评` 操作",
        object: "page",
        operator: "click",
        params: { role: "button", name: "提交匿名互评" },
      },
      {
        source: { caseStepId: "Action-4", method: "api" },
        id: "submit_peer_review_response.record",
        title: "记录 提交匿名互评结果中的互评",
        object: "api.peer_review_submit_response",
        operator: "record_review",
        params: { responseFrom: "runtime.submitPeerReviewResponse", saveAs: "submittedPeerReview" },
      },
    ],
  },

  S1: {
    description: "测试匿名互评已经持久化，普通成员仍保持登录",
    assertions: [
      {
        source: { caseStepId: "S1-1", method: "api" },
        id: "submit_peer_review_response.ok",
        title: "提交匿名互评结果 应成功",
        object: "api.response",
        operator: "ok",
        params: { responseFrom: "runtime.submitPeerReviewResponse", status: 200 },
      },
      {
        source: { caseStepId: "S1-2", method: "api" },
        id: "submitted_peer_review.matches",
        title: "提交匿名互评结果中的互评 reviewer 应为 普通成员，allocations 应包含普通成员贡献比例 `1`",
        object: "api.peer_review_submit_response",
        operator: "matches",
        params: {
          reviewFrom: "runtime.submittedPeerReview",
          targetFrom: "runtime.peerReviewTarget",
          reviewerFrom: "data.name",
          ratioFrom: "data.ratio",
        },
      },
      {
        source: { caseStepId: "S1-3", method: "prisma" },
        id: "db.peer_review.present",
        title: "数据库中 应存在 普通成员对本用例目标提交的匿名互评",
        object: "db.peer_review",
        operator: "present",
        params: { targetFrom: "runtime.peerReviewTarget", reviewerFrom: "data.name", ratioFrom: "data.ratio" },
      },
      {
        source: { caseStepId: "S1-4", method: "api" },
        id: "session.member.still_authenticated",
        title: "当前会话 应仍为 普通成员的已登录会话",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
    ],
  },

  Clean: {
    description: "删除本用例创建的匿名互评、战利品、目标、普通成员账号和页面会话状态",
    steps: [
      {
        source: { caseStepId: "Clean-1", method: "prisma" },
        id: "db.peer_review.delete",
        title: "删除 本用例创建的测试匿名互评",
        object: "db.peer_review",
        operator: "delete",
        params: { targetFrom: "runtime.peerReviewTarget", reviewerFrom: "data.name", reviewFrom: "runtime.submittedPeerReview" },
      },
      {
        source: { caseStepId: "Clean-2", method: "prisma" },
        id: "db.peer_review_loot.delete",
        title: "删除 本用例创建的测试战利品",
        object: "db.peer_review_loot",
        operator: "delete",
        params: { bodyFrom: "data.lootBody", lootFrom: "runtime.peerReviewLoot" },
      },
      {
        source: { caseStepId: "Clean-3", method: "prisma" },
        id: "db.objective.delete",
        title: "删除 本用例独占目标及其派生数据",
        object: "db.objective",
        operator: "delete",
        params: { idFrom: "data.objectiveId", titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Clean-4", method: "api" },
        id: "auth.logout",
        title: "注销当前登录会话",
        object: "auth",
        operator: "logout",
      },
      {
        source: { caseStepId: "Clean-5", method: "playwright" },
        id: "page.runtime.stop",
        title: "离开当前 ORF 前端页面",
        object: "page.runtime",
        operator: "stop",
      },
      {
        source: { caseStepId: "Clean-6", method: "playwright" },
        id: "browser.clear",
        title: "移除当前浏览器中的残留登录态",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "Clean-7", method: "api" },
        id: "ory.member_sessions.revoke",
        title: "撤销普通成员登录身份的残留登录会话",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-8", method: "api" },
        id: "ory.member_identity.delete",
        title: "删除普通成员登录身份",
        object: "ory.identity",
        operator: "delete_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-9", method: "prisma" },
        id: "db.member.delete_memberships",
        title: "删除 普通成员默认团队成员关系",
        object: "db.user",
        operator: "delete_memberships",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-10", method: "prisma" },
        id: "db.member.delete",
        title: "删除 普通成员用户",
        object: "db.user",
        operator: "delete",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-11", method: "prisma" },
        id: "db.peer_review.absent",
        title: "本用例普通成员匿名互评记录 应不存在",
        object: "db.peer_review",
        operator: "absent",
        params: { targetFrom: "runtime.peerReviewTarget", reviewerFrom: "data.name" },
      },
      {
        source: { caseStepId: "Clean-12", method: "prisma" },
        id: "db.peer_review_loot.absent",
        title: "内容为 `E2E-PEER-LOOT-BODY: 匿名互评前置战利品` 的测试战利品 应不存在",
        object: "db.peer_review_loot",
        operator: "absent",
        params: { bodyFrom: "data.lootBody" },
      },
      {
        source: { caseStepId: "Clean-13", method: "prisma" },
        id: "db.objective.absent",
        title: "标题为 `E2E-MEMBER-SUBMIT-PEER-REVIEW: 目标前置` 的本用例目标 应不存在",
        object: "db.objective",
        operator: "absent",
        params: { idFrom: "data.objectiveId", titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Clean-14", method: "prisma" },
        id: "db.member.absent",
        title: "邮箱为 `orf-member-submit-peer-review-e2e@orf.local` 的普通成员用户 应不存在",
        object: "db.user",
        operator: "absent",
        params: { emailFrom: "data.email" },
      },
    ],
  },
} satisfies StateCaseSpec<MemberSubmitPeerReviewCaseData>;
