import { STATE_CASE_MODEL, type StateCaseSpec, type StepExecutionMethod, type StepSpec } from "../../_framework/types";
import type { SystemMembersDeleteCaseData } from "./_support/members-delete.context";

function step(
  caseStepId: string,
  method: StepExecutionMethod,
  id: string,
  title: string,
  object: string,
  operator: string,
  params?: Record<string, unknown>,
): StepSpec {
  return {
    source: { caseStepId, method },
    id,
    title,
    object,
    operator,
    ...(params ? { params } : {}),
  };
}

export const systemMembersDeleteCase = {
  id: "system.members-delete.confirmation",
  title: "09-成员管理删除用户校验",
  model: STATE_CASE_MODEL,
  tags: ["system", "members", "delete"],
  data: {
    admin: {
      email: "orf-system-members-delete-admin-e2e@orf.local",
      password: "OrfSystemMembersDeleteAdminE2E!2026",
      name: "ORF Members Delete Admin E2E",
      role: "admin",
    },
    targetUser: {
      email: "orf-system-members-delete-target-e2e@orf.local",
      password: "OrfSystemMembersDeleteTargetE2E!2026",
      name: "ORF Members Delete Target E2E",
      role: "member",
    },
    cancelUser: {
      email: "orf-system-members-delete-cancel-e2e@orf.local",
      password: "OrfSystemMembersDeleteCancelE2E!2026",
      name: "ORF Members Delete Cancel E2E",
      role: "member",
    },
    defaultLandingPath: "/bounties",
    membersPath: "/system/members",
  },
  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      step("B-1", "api", "frontend.ready", "前端服务 应可用", "frontend.service", "available"),
      step("B-2", "api", "backend.ready", "后端服务 应可用", "api.health", "ok"),
      step("B-3", "api", "frontend.login_entry.accessible", "前端登录页入口 应可访问", "frontend.login_entry", "accessible"),
      step("B-4", "api", "session.endpoint.accessible", "当前会话查询能力 应可用", "auth.session", "accessible"),
      step("B-5", "prisma", "db.ready", "ORF 数据库 应可连接", "db", "ready"),
      step("B-6", "prisma", "db.schema.current", "ORF 数据库 schema 应为 当前测试版本", "db.schema", "current"),
      step("B-7", "api", "ory.admin_public.ready", "Ory/Kratos 认证服务的管理和公共访问能力 应可用", "ory.admin_public", "ready"),
      step("B-8", "api", "session.unauthenticated", "当前会话 应为 未登录", "auth.session", "unauthenticated"),
      step("B-9", "playwright", "cookie.absent", "当前浏览器 应不存在 Ory 登录会话 cookie", "browser.cookie", "absent"),
      step("B-10", "playwright", "storage.empty", "当前浏览器 应不保留本地登录态", "browser.auth_storage", "empty"),
    ],
  },
  Setup: {
    description: "准备管理员、待删除用户和取消删除用户，并以管理员身份进入成员管理页面",
    steps: [
      step("Setup-1", "api", "ory.admin_identity.upsert", "准备邮箱为 `orf-system-members-delete-admin-e2e@orf.local`、使用固定测试密码的成员管理删除用户管理员测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.admin.email", passwordFrom: "data.admin.password", nameFrom: "data.admin.name", saveAs: "adminIdentity" }),
      step("Setup-2", "prisma", "db.admin_user.upsert", "准备姓名为 \"ORF Members Delete Admin E2E\"、邮箱为 `orf-system-members-delete-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的成员管理删除用户管理员测试用户", "db.user", "upsert", { emailFrom: "data.admin.email", passwordFrom: "data.admin.password", nameFrom: "data.admin.name", roleFrom: "data.admin.role", status: "active", identityIdFrom: "runtime.adminIdentity.id", saveAs: "adminUser" }),
      step("Setup-3", "api", "admin.preferences.default_landing_path.set", "设置成员管理删除用户管理员测试用户默认进入页面为 首页（默认系统页）", "user.preferences", "set_default_landing_path_by_email", { emailFrom: "data.admin.email", pathFrom: "data.defaultLandingPath" }),
      step("Setup-4", "api", "ory.target_identity.upsert", "准备邮箱为 `orf-system-members-delete-target-e2e@orf.local`、使用固定测试密码的成员管理待删除测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.targetUser.email", passwordFrom: "data.targetUser.password", nameFrom: "data.targetUser.name", saveAs: "targetIdentity" }),
      step("Setup-5", "prisma", "db.target_user.upsert", "准备姓名为 \"ORF Members Delete Target E2E\"、邮箱为 `orf-system-members-delete-target-e2e@orf.local`、角色为 `member`、状态为 `active` 的成员管理待删除测试用户", "db.user", "upsert", { emailFrom: "data.targetUser.email", passwordFrom: "data.targetUser.password", nameFrom: "data.targetUser.name", roleFrom: "data.targetUser.role", status: "active", identityIdFrom: "runtime.targetIdentity.id", saveAs: "targetUser" }),
      step("Setup-6", "api", "ory.cancel_identity.upsert", "准备邮箱为 `orf-system-members-delete-cancel-e2e@orf.local`、使用固定测试密码的成员管理取消删除测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.cancelUser.email", passwordFrom: "data.cancelUser.password", nameFrom: "data.cancelUser.name", saveAs: "cancelIdentity" }),
      step("Setup-7", "prisma", "db.cancel_user.upsert", "准备姓名为 \"ORF Members Delete Cancel E2E\"、邮箱为 `orf-system-members-delete-cancel-e2e@orf.local`、角色为 `member`、状态为 `active` 的成员管理取消删除测试用户", "db.user", "upsert", { emailFrom: "data.cancelUser.email", passwordFrom: "data.cancelUser.password", nameFrom: "data.cancelUser.name", roleFrom: "data.cancelUser.role", status: "active", identityIdFrom: "runtime.cancelIdentity.id", saveAs: "cancelUser" }),
      step("Setup-8", "prisma", "db.users_total.record", "记录成员管理页面用户总数为 删除前用户总数", "db.users_total", "record", { saveAs: "beforeDeleteUserTotal" }),
      step("Setup-9", "api", "ory.admin_sessions.revoke", "撤销邮箱为 `orf-system-members-delete-admin-e2e@orf.local` 的成员管理删除用户管理员测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.admin.email" }),
      step("Setup-10", "api", "ory.target_sessions.revoke", "撤销邮箱为 `orf-system-members-delete-target-e2e@orf.local` 的成员管理待删除测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.targetUser.email" }),
      step("Setup-11", "api", "ory.cancel_sessions.revoke", "撤销邮箱为 `orf-system-members-delete-cancel-e2e@orf.local` 的成员管理取消删除测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.cancelUser.email" }),
      step("Setup-12", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Setup-13", "playwright", "page.goto.auth", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Setup-14", "playwright", "fill.admin_email", "在邮箱输入框输入 `orf-system-members-delete-admin-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.admin.email" }),
      step("Setup-15", "playwright", "fill.admin_password", "在密码输入框输入成员管理删除用户管理员测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.admin.password" }),
      step("Setup-16", "playwright", "click.sign_in", "点击 \"Sign In\" 登录操作", "page.login_form", "submit", { saveAs: "adminLoginResponse" }),
      step("Setup-17", "api", "session.admin_authenticated", "当前会话 应为 邮箱为 `orf-system-members-delete-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
      step("Setup-18", "playwright", "page.goto.members", "打开 成员管理页面", "page", "goto", { pathFrom: "data.membersPath" }),
    ],
  },
  S0: {
    description: "管理员已登录并位于成员管理页面，待删除和取消删除用户均可执行删除操作",
    assertions: [
      step("S0-1", "api", "session.admin_authenticated", "当前会话 应为 邮箱为 `orf-system-members-delete-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
      step("S0-2", "playwright", "url.members", "当前页面 应为 成员管理页面", "page.url", "match", { pattern: "/system/members$" }),
      step("S0-3", "playwright", "members.list.target.visible", "成员管理页面的用户列表 应显示 待删除测试用户", "page.members_list", "contains_user", { emailFrom: "data.targetUser.email", nameFrom: "data.targetUser.name" }),
      step("S0-4", "playwright", "members.list.cancel.visible", "成员管理页面的用户列表 应显示 取消删除测试用户", "page.members_list", "contains_user", { emailFrom: "data.cancelUser.email", nameFrom: "data.cancelUser.name" }),
      step("S0-5", "playwright", "target.delete.visible", "待删除测试用户列表行的 \"删除用户\" 操作 应可见", "page.member_row_action", "visible", { emailFrom: "data.targetUser.email", action: "删除用户" }),
      step("S0-6", "playwright", "target.delete.enabled", "待删除测试用户列表行的 \"删除用户\" 操作 应可点击", "page.member_row_action", "enabled", { emailFrom: "data.targetUser.email", action: "删除用户" }),
      step("S0-7", "playwright", "cancel.delete.visible", "取消删除测试用户列表行的 \"删除用户\" 操作 应可见", "page.member_row_action", "visible", { emailFrom: "data.cancelUser.email", action: "删除用户" }),
      step("S0-8", "playwright", "cancel.delete.enabled", "取消删除测试用户列表行的 \"删除用户\" 操作 应可点击", "page.member_row_action", "enabled", { emailFrom: "data.cancelUser.email", action: "删除用户" }),
      step("S0-9", "playwright", "members.total.before", "成员管理页面的用户总数 应等于 删除前用户总数", "page.members_total", "equals", { expectedFrom: "runtime.beforeDeleteUserTotal" }),
      step("S0-10", "prisma", "db.target_user.exists", "邮箱为 `orf-system-members-delete-target-e2e@orf.local` 的成员管理待删除测试用户 应存在", "db.user", "matches", { emailFrom: "data.targetUser.email", roleFrom: "data.targetUser.role", status: "active" }),
      step("S0-11", "prisma", "db.cancel_user.exists", "邮箱为 `orf-system-members-delete-cancel-e2e@orf.local` 的成员管理取消删除测试用户 应存在", "db.user", "matches", { emailFrom: "data.cancelUser.email", roleFrom: "data.cancelUser.role", status: "active" }),
    ],
  },
  Action: {
    description: "先取消删除一个用户，再确认删除另一个用户",
    steps: [
      step("Action-1", "playwright", "cancel.delete.click", "点击 取消删除测试用户列表行的 \"删除用户\" 操作", "page.member_row_action", "click_confirm", { emailFrom: "data.cancelUser.email", action: "删除用户", decision: "dismiss", saveAs: "cancelDeleteConfirm" }),
      step("Action-2", "playwright", "cancel.delete.confirm.observe", "查看 删除用户确认弹窗", "page.confirm_snapshot", "observe", { snapshotFrom: "runtime.cancelDeleteConfirm" }),
      step("Action-3", "playwright", "cancel.delete.confirm.cancel", "点击 删除用户确认弹窗的取消操作", "page.confirm_snapshot", "dismissed", { snapshotFrom: "runtime.cancelDeleteConfirm", saveAs: "afterCancelUserTotal" }),
      step("Action-4", "playwright", "target.delete.click", "点击 待删除测试用户列表行的 \"删除用户\" 操作", "page.member_row_action", "click_confirm", { emailFrom: "data.targetUser.email", action: "删除用户", decision: "accept", saveAs: "targetDeleteConfirm" }),
      step("Action-5", "playwright", "target.delete.confirm.observe", "查看 删除用户确认弹窗", "page.confirm_snapshot", "observe", { snapshotFrom: "runtime.targetDeleteConfirm" }),
      step("Action-6", "playwright", "target.delete.confirm.accept", "点击 删除用户确认弹窗的确认操作", "page.confirm_snapshot", "accepted", { snapshotFrom: "runtime.targetDeleteConfirm", waitEmailFrom: "data.targetUser.email" }),
    ],
  },
  S1: {
    description: "取消删除不改变数据，确认删除后目标用户从列表和数据库移除且总数减少",
    assertions: [
      step("S1-1", "playwright", "cancel.delete.confirm.title", "删除用户确认弹窗标题 应显示 删除用户确认信息", "page.confirm_snapshot", "message_matches", { snapshotFrom: "runtime.cancelDeleteConfirm", pattern: "删除账号|删除用户" }),
      step("S1-2", "playwright", "cancel.delete.confirm.user", "删除用户确认弹窗 应显示 取消删除测试用户", "page.confirm_snapshot", "contains", { snapshotFrom: "runtime.cancelDeleteConfirm", textFrom: "data.cancelUser.name" }),
      step("S1-3", "playwright", "cancel.delete.confirm.hidden", "点击取消后，删除用户确认弹窗 应不可见", "page.confirm_snapshot", "dismissed", { snapshotFrom: "runtime.cancelDeleteConfirm" }),
      step("S1-4", "playwright", "members.list.cancel.visible.after_cancel", "点击取消后，成员管理页面的用户列表 应显示 取消删除测试用户", "page.members_list", "contains_user", { emailFrom: "data.cancelUser.email", nameFrom: "data.cancelUser.name" }),
      step("S1-5", "prisma", "db.cancel_user.still_exists", "点击取消后，邮箱为 `orf-system-members-delete-cancel-e2e@orf.local` 的成员管理取消删除测试用户 应仍存在", "db.user", "matches", { emailFrom: "data.cancelUser.email", roleFrom: "data.cancelUser.role", status: "active" }),
      step("S1-6", "playwright", "members.total.after_cancel", "点击取消后，成员管理页面的用户总数 应等于 删除前用户总数", "page.members_total", "equals", { actualFrom: "runtime.afterCancelUserTotal", expectedFrom: "runtime.beforeDeleteUserTotal" }),
      step("S1-7", "playwright", "target.delete.confirm.user", "删除用户确认弹窗 应显示 待删除测试用户", "page.confirm_snapshot", "contains", { snapshotFrom: "runtime.targetDeleteConfirm", textFrom: "data.targetUser.name" }),
      step("S1-8", "playwright", "target.delete.confirm.hidden", "确认删除后，删除用户确认弹窗 应不可见", "page.confirm_snapshot", "accepted", { snapshotFrom: "runtime.targetDeleteConfirm", waitEmailFrom: "data.targetUser.email" }),
      step("S1-9", "playwright", "members.list.target.hidden.after_delete", "确认删除后，成员管理页面的用户列表 应不显示 待删除测试用户", "page.members_list", "not_contains_user", { emailFrom: "data.targetUser.email" }),
      step("S1-10", "prisma", "db.target_user.absent", "确认删除后，邮箱为 `orf-system-members-delete-target-e2e@orf.local` 的成员管理待删除测试用户 应不存在", "db.user", "absent", { emailFrom: "data.targetUser.email" }),
      step("S1-11", "playwright", "members.total.after_delete", "确认删除后，成员管理页面的用户总数 应比 删除前用户总数 少 1", "page.members_total", "decreased_by", { baselineFrom: "runtime.beforeDeleteUserTotal", delta: 1 }),
      step("S1-12", "api", "session.admin_authenticated.after_delete", "当前会话 应仍为 邮箱为 `orf-system-members-delete-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
    ],
  },
  Clean: {
    description: "删除成员管理删除用户相关测试数据并恢复未登录基准状态",
    steps: [
      step("Clean-1", "api", "auth.logout", "注销当前登录会话", "auth", "logout"),
      step("Clean-2", "playwright", "page.runtime.stop", "离开当前 ORF 前端页面", "page.runtime", "stop"),
      step("Clean-3", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Clean-4", "api", "ory.admin_sessions.revoke", "撤销邮箱为 `orf-system-members-delete-admin-e2e@orf.local` 的成员管理删除用户管理员测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-5", "api", "ory.target_sessions.revoke", "撤销邮箱为 `orf-system-members-delete-target-e2e@orf.local` 的成员管理待删除测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.targetUser.email" }),
      step("Clean-6", "api", "ory.cancel_sessions.revoke", "撤销邮箱为 `orf-system-members-delete-cancel-e2e@orf.local` 的成员管理取消删除测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.cancelUser.email" }),
      step("Clean-7", "api", "ory.admin_identity.delete", "删除邮箱为 `orf-system-members-delete-admin-e2e@orf.local` 的成员管理删除用户管理员测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-8", "api", "ory.target_identity.delete", "删除邮箱为 `orf-system-members-delete-target-e2e@orf.local` 的成员管理待删除测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.targetUser.email" }),
      step("Clean-9", "api", "ory.cancel_identity.delete", "删除邮箱为 `orf-system-members-delete-cancel-e2e@orf.local` 的成员管理取消删除测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.cancelUser.email" }),
      step("Clean-10", "api", "admin.preferences.default_landing_path.reset", "恢复邮箱为 `orf-system-members-delete-admin-e2e@orf.local` 的默认进入页面为 系统默认", "user.preferences", "reset_default_landing_path_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-11", "prisma", "db.admin_user.memberships.delete", "删除邮箱为 `orf-system-members-delete-admin-e2e@orf.local` 的成员管理删除用户管理员测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.admin.email" }),
      step("Clean-12", "prisma", "db.target_user.memberships.delete", "删除邮箱为 `orf-system-members-delete-target-e2e@orf.local` 的成员管理待删除测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.targetUser.email" }),
      step("Clean-13", "prisma", "db.cancel_user.memberships.delete", "删除邮箱为 `orf-system-members-delete-cancel-e2e@orf.local` 的成员管理取消删除测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.cancelUser.email" }),
      step("Clean-14", "prisma", "db.admin_user.delete", "删除邮箱为 `orf-system-members-delete-admin-e2e@orf.local` 的成员管理删除用户管理员测试用户", "db.user", "delete", { emailFrom: "data.admin.email" }),
      step("Clean-15", "prisma", "db.target_user.delete", "删除邮箱为 `orf-system-members-delete-target-e2e@orf.local` 的成员管理待删除测试用户", "db.user", "delete", { emailFrom: "data.targetUser.email" }),
      step("Clean-16", "prisma", "db.cancel_user.delete", "删除邮箱为 `orf-system-members-delete-cancel-e2e@orf.local` 的成员管理取消删除测试用户", "db.user", "delete", { emailFrom: "data.cancelUser.email" }),
      step("Clean-17", "api", "ory.admin_identity.absent", "邮箱为 `orf-system-members-delete-admin-e2e@orf.local` 的成员管理删除用户管理员测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.admin.email" }),
      step("Clean-18", "api", "ory.target_identity.absent", "邮箱为 `orf-system-members-delete-target-e2e@orf.local` 的成员管理待删除测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.targetUser.email" }),
      step("Clean-19", "api", "ory.cancel_identity.absent", "邮箱为 `orf-system-members-delete-cancel-e2e@orf.local` 的成员管理取消删除测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.cancelUser.email" }),
      step("Clean-20", "prisma", "db.admin_user.absent", "邮箱为 `orf-system-members-delete-admin-e2e@orf.local` 的成员管理删除用户管理员测试用户 应不存在", "db.user", "absent", { emailFrom: "data.admin.email" }),
      step("Clean-21", "prisma", "db.target_user.absent", "邮箱为 `orf-system-members-delete-target-e2e@orf.local` 的成员管理待删除测试用户 应不存在", "db.user", "absent", { emailFrom: "data.targetUser.email" }),
      step("Clean-22", "prisma", "db.cancel_user.absent", "邮箱为 `orf-system-members-delete-cancel-e2e@orf.local` 的成员管理取消删除测试用户 应不存在", "db.user", "absent", { emailFrom: "data.cancelUser.email" }),
    ],
  },
} satisfies StateCaseSpec<SystemMembersDeleteCaseData>;
