import { STATE_CASE_MODEL, type StateCaseSpec } from "../../../../_framework/types";
import type { MemberEditTodayWorkLogCaseData } from "./_support/member-edit-today-work-log.context";

export const memberEditTodayWorkLogCase = {
  id: "work-log.member-edit-today-work-log",
  title: "成员可以编辑当天已写好的日志",
  model: STATE_CASE_MODEL,
  tags: ["work-log", "my-log", "member", "edit", "today", "happy-path"],

  data: {
    memberEmail: "orf-member-edit-today-work-log-e2e@orf.local",
    memberPassword: "OrfMemberEditTodayWorkLogE2E!2026",
    memberName: "ORF Member Edit Today Work Log E2E",
    memberRole: "member",
    memberStatus: "active",
    objectiveTitle: "E2E-TARGET-WORK-LOG-EDIT-TODAY",
    objectiveFlowStatus: "open",
    objectiveStage: "resultClaiming",
    objectiveStatus: "On Track",
    originalLogBodyMarker: "E2E-WORK-LOG-EDIT-TODAY-ORIGINAL",
    originalLogBody: "E2E-WORK-LOG-EDIT-TODAY-ORIGINAL：当天日志编辑前内容。",
    originalDurationMinutes: 60,
    originalProgressEstimatePercent: 40,
    originalRemainingEstimatePercent: 60,
    originalExpectedDurationLabel: "1h",
    originalExpectedProgressLabel: "进 40%",
    updatedLogBodyMarker: "E2E-WORK-LOG-EDIT-TODAY-UPDATED",
    updatedLogBody: "E2E-WORK-LOG-EDIT-TODAY-UPDATED：当天日志已完成编辑并同步最新风险。",
    updatedDurationMinutes: 120,
    updatedProgressEstimatePercent: 55,
    updatedRemainingEstimatePercent: 45,
    updatedExpectedDurationLabel: "2h",
    updatedExpectedProgressLabel: "进 55%",
  },

  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      { source: { caseStepId: "B-1", method: "api" }, id: "frontend.ready", title: "前端服务 应可用", object: "frontend.service", operator: "available" },
      { source: { caseStepId: "B-2", method: "api" }, id: "backend.ready", title: "后端服务 应可用", object: "api.health", operator: "ok" },
      { source: { caseStepId: "B-3", method: "prisma" }, id: "db.ready", title: "ORF 数据库 应可连接", object: "db", operator: "ready" },
      { source: { caseStepId: "B-4", method: "api" }, id: "session.unauthenticated", title: "当前会话 应为 未登录", object: "auth.session", operator: "unauthenticated" },
      { source: { caseStepId: "B-5", method: "playwright" }, id: "storage.empty", title: "当前浏览器 应不保留本地登录态", object: "browser.auth_storage", operator: "empty" },
    ],
  },

  Setup: {
    description: "准备已有当天日志的成员并打开工作日志当天视图",
    steps: [
      { source: { caseStepId: "Setup-1", method: "prisma" }, id: "db.work_log.delete_original_residue", title: "删除 本用例残留的工作日志正文标记 `E2E-WORK-LOG-EDIT-TODAY-ORIGINAL` 对应的工作日志", object: "db.work_log_entry", operator: "delete_by_body_marker", params: { bodyMarkerFrom: "data.originalLogBodyMarker" } },
      { source: { caseStepId: "Setup-2", method: "prisma" }, id: "db.work_log.delete_updated_residue", title: "删除 本用例残留的工作日志正文标记 `E2E-WORK-LOG-EDIT-TODAY-UPDATED` 对应的工作日志", object: "db.work_log_entry", operator: "delete_by_body_marker", params: { bodyMarkerFrom: "data.updatedLogBodyMarker" } },
      { source: { caseStepId: "Setup-3", method: "prisma" }, id: "db.objective.delete_residue", title: "删除 本用例残留的目标 `E2E-TARGET-WORK-LOG-EDIT-TODAY` 及其派生数据", object: "db.objective", operator: "delete_by_title", params: { titleFrom: "data.objectiveTitle" } },
      { source: { caseStepId: "Setup-4", method: "api" }, id: "ory.member_identity.upsert", title: "准备邮箱为 `orf-member-edit-today-work-log-e2e@orf.local`、使用固定测试密码的成员登录身份", object: "ory.identity", operator: "upsert_password", params: { emailFrom: "data.memberEmail", nameFrom: "data.memberName", passwordFrom: "data.memberPassword", saveAs: "memberIdentity" } },
      { source: { caseStepId: "Setup-5", method: "prisma" }, id: "db.member_user.upsert", title: "准备 角色为 `member`、状态为 `active`、名称为 `ORF Member Edit Today Work Log E2E` 的本用例成员用户", object: "db.user", operator: "upsert", params: { emailFrom: "data.memberEmail", nameFrom: "data.memberName", roleFrom: "data.memberRole", statusFrom: "data.memberStatus", identityIdFrom: "runtime.memberIdentity.id", saveAs: "memberUser" } },
      { source: { caseStepId: "Setup-6", method: "prisma" }, id: "db.objective.upsert_writable", title: "准备 标题为 `E2E-TARGET-WORK-LOG-EDIT-TODAY`、当前挑战者包含本用例成员、可填写工作日志的目标", object: "db.objective", operator: "upsert", params: { titleFrom: "data.objectiveTitle", teamIdFrom: "runtime.memberUser.teamId", challengersFrom: "data.memberName", challengerUserIdsFrom: "runtime.memberUser.userId", flowStatusFrom: "data.objectiveFlowStatus", stageFrom: "data.objectiveStage", statusFrom: "data.objectiveStatus", createdByFrom: "runtime.memberUser.userId", updatedByFrom: "runtime.memberUser.userId", saveAs: "workLogObjective" } },
      { source: { caseStepId: "Setup-7", method: "prisma" }, id: "db.work_log.prepare_original", title: "准备 本用例成员在测试执行当天已提交正文标记为 `E2E-WORK-LOG-EDIT-TODAY-ORIGINAL` 的工作日志", object: "db.work_log_entry", operator: "prepare_today", params: { memberUserFrom: "runtime.memberUser", objectiveFrom: "runtime.workLogObjective", bodyMarkerFrom: "data.originalLogBodyMarker", bodyFrom: "data.originalLogBody", durationMinutesFrom: "data.originalDurationMinutes", remainingEstimatePercentFrom: "data.originalRemainingEstimatePercent", saveAs: "originalWorkLogEntry" } },
      { source: { caseStepId: "Setup-8", method: "playwright" }, id: "auth.login.member", title: "使用 本用例成员账号 登录 ORF", object: "page.auth", operator: "login", params: { emailFrom: "data.memberEmail", passwordFrom: "data.memberPassword" } },
      { source: { caseStepId: "Setup-9", method: "playwright" }, id: "work_logs.open_today", title: "打开 工作日志页面的当天日志视图", object: "page.work_logs", operator: "open_today" },
    ],
  },

  S0: {
    description: "成员已登录且当天记录包含本用例原始日志",
    assertions: [
      { source: { caseStepId: "S0-1", method: "api" }, id: "session.authenticated", title: "当前会话 应为 已登录", object: "auth.session", operator: "authenticated" },
      { source: { caseStepId: "S0-2", method: "api" }, id: "session.email", title: "当前会话用户邮箱 应为 `orf-member-edit-today-work-log-e2e@orf.local`", object: "auth.session.user_email", operator: "equals", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "S0-3", method: "api" }, id: "session.role", title: "当前会话用户角色 应为 `member`", object: "auth.session.user_role", operator: "equals", params: { roleFrom: "data.memberRole" } },
      { source: { caseStepId: "S0-4", method: "api" }, id: "session.name", title: "当前会话用户名称 应为 `ORF Member Edit Today Work Log E2E`", object: "auth.session.user_name", operator: "equals", params: { nameFrom: "data.memberName" } },
      { source: { caseStepId: "S0-5", method: "api" }, id: "work_log.objectives.contains_target", title: "工作日志可选目标 应包含目标 `E2E-TARGET-WORK-LOG-EDIT-TODAY`", object: "api.work_log.objectives", operator: "contains_title", params: { titleFrom: "data.objectiveTitle" } },
      { source: { caseStepId: "S0-6", method: "api" }, id: "work_log.my_day.contains_original", title: "当天工作日志数据 应包含正文标记 `E2E-WORK-LOG-EDIT-TODAY-ORIGINAL`", object: "api.work_log.my_day", operator: "contains_body", params: { bodyMarkerFrom: "data.originalLogBodyMarker" } },
      { source: { caseStepId: "S0-7", method: "api" }, id: "work_log.my_day.not_contains_updated", title: "当天工作日志数据 应不包含正文标记 `E2E-WORK-LOG-EDIT-TODAY-UPDATED`", object: "api.work_log.my_day", operator: "not_contains_body_marker", params: { bodyMarkerFrom: "data.updatedLogBodyMarker" } },
      { source: { caseStepId: "S0-8", method: "prisma" }, id: "db.work_log.original_exists", title: "应存在 本用例成员在测试执行当天提交的正文标记为 `E2E-WORK-LOG-EDIT-TODAY-ORIGINAL` 的工作日志", object: "db.work_log_entry", operator: "exists_today_for_member", params: { bodyMarkerFrom: "data.originalLogBodyMarker", memberEmailFrom: "data.memberEmail", saveAs: "originalWorkLogEntryBeforeEdit" } },
      { source: { caseStepId: "S0-9", method: "prisma" }, id: "db.work_log.updated_absent", title: "应不存在 本用例成员在测试执行当天提交的正文标记为 `E2E-WORK-LOG-EDIT-TODAY-UPDATED` 的工作日志", object: "db.work_log_entry", operator: "absent_today_for_member", params: { bodyMarkerFrom: "data.updatedLogBodyMarker", memberEmailFrom: "data.memberEmail" } },
      { source: { caseStepId: "S0-10", method: "playwright" }, id: "work_logs.page.visible", title: "页面 应进入 工作日志", object: "page.work_logs", operator: "visible" },
      { source: { caseStepId: "S0-11", method: "playwright" }, id: "work_logs.today_tab.selected", title: "\"日志\" 视图 应处于选中状态", object: "page.work_logs.view_tab", operator: "selected", params: { label: "日志" } },
      { source: { caseStepId: "S0-12", method: "playwright" }, id: "work_logs.date.today", title: "日志日期 应为 测试执行当天", object: "page.work_logs.date", operator: "today" },
      { source: { caseStepId: "S0-13", method: "playwright" }, id: "work_logs.history.original_body", title: "\"当天记录\" 区域 应显示日志正文 `E2E-WORK-LOG-EDIT-TODAY-ORIGINAL：当天日志编辑前内容。`", object: "page.work_logs.history", operator: "contains_body", params: { bodyMarkerFrom: "data.originalLogBodyMarker", bodyFrom: "data.originalLogBody" } },
      { source: { caseStepId: "S0-14", method: "playwright" }, id: "work_logs.history.objective", title: "\"当天记录\" 区域 应显示目标 `E2E-TARGET-WORK-LOG-EDIT-TODAY`", object: "page.work_logs.history", operator: "contains_objective", params: { bodyMarkerFrom: "data.originalLogBodyMarker", objectiveTitleFrom: "data.objectiveTitle" } },
      { source: { caseStepId: "S0-15", method: "playwright" }, id: "work_logs.history.original_duration", title: "\"当天记录\" 区域 应显示记录时间 `1h`", object: "page.work_logs.history", operator: "contains_duration", params: { bodyMarkerFrom: "data.originalLogBodyMarker", durationLabelFrom: "data.originalExpectedDurationLabel" } },
      { source: { caseStepId: "S0-16", method: "playwright" }, id: "work_logs.history.original_progress", title: "\"当天记录\" 区域 应显示目标进度 `进 40%`", object: "page.work_logs.history", operator: "contains_progress", params: { bodyMarkerFrom: "data.originalLogBodyMarker", progressLabelFrom: "data.originalExpectedProgressLabel" } },
      { source: { caseStepId: "S0-17", method: "playwright" }, id: "work_logs.edit.visible", title: "本用例原始日志的 \"编辑\" 操作 应可见", object: "page.work_logs.edit_action", operator: "visible", params: { bodyMarkerFrom: "data.originalLogBodyMarker" } },
      { source: { caseStepId: "S0-18", method: "playwright" }, id: "work_logs.edit.enabled", title: "本用例原始日志的 \"编辑\" 操作 应可点击", object: "page.work_logs.edit_action", operator: "enabled", params: { bodyMarkerFrom: "data.originalLogBodyMarker" } },
    ],
  },

  Action: {
    description: "成员进入编辑状态并更新当天工作日志",
    steps: [
      { source: { caseStepId: "Action-1", method: "playwright" }, id: "work_logs.edit.click", title: "点击 本用例原始日志的 \"编辑\" 操作", object: "page.work_logs.edit_action", operator: "click", params: { bodyMarkerFrom: "data.originalLogBodyMarker" } },
      { source: { caseStepId: "Action-2", method: "playwright" }, id: "work_logs.fill_updated_progress", title: "填写 \"目标进度估计百分比\" 输入框 为 `55`", object: "page.work_logs.progress_estimate_input", operator: "fill", params: { valueFrom: "data.updatedProgressEstimatePercent" } },
      { source: { caseStepId: "Action-3", method: "playwright" }, id: "work_logs.fill_updated_duration", title: "填写 \"记录时间分钟数\" 输入框 为 `120`", object: "page.work_logs.duration_input", operator: "fill", params: { valueFrom: "data.updatedDurationMinutes" } },
      { source: { caseStepId: "Action-4", method: "playwright" }, id: "work_logs.fill_updated_body", title: "填写 工作日志正文编辑器 为 `E2E-WORK-LOG-EDIT-TODAY-UPDATED：当天日志已完成编辑并同步最新风险。`", object: "page.work_logs.body_editor", operator: "fill", params: { valueFrom: "data.updatedLogBody" } },
      { source: { caseStepId: "Action-5", method: "playwright" }, id: "work_logs.update", title: "点击 \"更新日志\" 操作", object: "page.work_logs.update_action", operator: "update" },
    ],
  },

  S1: {
    description: "页面、接口和数据库均显示更新后的当天工作日志且未新增重复日志",
    assertions: [
      { source: { caseStepId: "S1-1", method: "playwright" }, id: "work_logs.toast.updated", title: "页面 应提示 `工作日志已更新`", object: "page.work_logs.toast", operator: "visible", params: { text: "工作日志已更新" } },
      { source: { caseStepId: "S1-2", method: "playwright" }, id: "work_logs.history.updated_body", title: "\"当天记录\" 区域 应显示日志正文 `E2E-WORK-LOG-EDIT-TODAY-UPDATED：当天日志已完成编辑并同步最新风险。`", object: "page.work_logs.history", operator: "contains_body", params: { bodyMarkerFrom: "data.updatedLogBodyMarker", bodyFrom: "data.updatedLogBody" } },
      { source: { caseStepId: "S1-3", method: "playwright" }, id: "work_logs.history.objective", title: "\"当天记录\" 区域 应显示目标 `E2E-TARGET-WORK-LOG-EDIT-TODAY`", object: "page.work_logs.history", operator: "contains_objective", params: { bodyMarkerFrom: "data.updatedLogBodyMarker", objectiveTitleFrom: "data.objectiveTitle" } },
      { source: { caseStepId: "S1-4", method: "playwright" }, id: "work_logs.history.updated_duration", title: "\"当天记录\" 区域 应显示记录时间 `2h`", object: "page.work_logs.history", operator: "contains_duration", params: { bodyMarkerFrom: "data.updatedLogBodyMarker", durationLabelFrom: "data.updatedExpectedDurationLabel" } },
      { source: { caseStepId: "S1-5", method: "playwright" }, id: "work_logs.history.updated_progress", title: "\"当天记录\" 区域 应显示目标进度 `进 55%`", object: "page.work_logs.history", operator: "contains_progress", params: { bodyMarkerFrom: "data.updatedLogBodyMarker", progressLabelFrom: "data.updatedExpectedProgressLabel" } },
      { source: { caseStepId: "S1-6", method: "playwright" }, id: "work_logs.history.not_contains_original", title: "\"当天记录\" 区域 应不显示日志正文标记 `E2E-WORK-LOG-EDIT-TODAY-ORIGINAL`", object: "page.work_logs.history", operator: "not_contains_marker", params: { bodyMarkerFrom: "data.originalLogBodyMarker" } },
      { source: { caseStepId: "S1-7", method: "api" }, id: "work_log.my_day.contains_updated", title: "当天工作日志数据 应包含正文为 `E2E-WORK-LOG-EDIT-TODAY-UPDATED：当天日志已完成编辑并同步最新风险。` 的工作日志", object: "api.work_log.my_day", operator: "contains_body", params: { bodyMarkerFrom: "data.updatedLogBodyMarker" } },
      { source: { caseStepId: "S1-8", method: "api" }, id: "work_log.my_day.not_contains_original", title: "当天工作日志数据 应不包含正文标记 `E2E-WORK-LOG-EDIT-TODAY-ORIGINAL`", object: "api.work_log.my_day", operator: "not_contains_body_marker", params: { bodyMarkerFrom: "data.originalLogBodyMarker" } },
      { source: { caseStepId: "S1-9", method: "api" }, id: "work_log.my_day.objective_snapshot", title: "当天工作日志数据中的本用例工作日志目标标题快照 应为 `E2E-TARGET-WORK-LOG-EDIT-TODAY`", object: "api.work_log.my_day", operator: "objective_title_snapshot", params: { bodyMarkerFrom: "data.updatedLogBodyMarker", valueFrom: "data.objectiveTitle" } },
      { source: { caseStepId: "S1-10", method: "api" }, id: "work_log.my_day.updated_duration", title: "当天工作日志数据中的本用例工作日志记录时间分钟数 应为 `120`", object: "api.work_log.my_day", operator: "duration_minutes", params: { bodyMarkerFrom: "data.updatedLogBodyMarker", valueFrom: "data.updatedDurationMinutes" } },
      { source: { caseStepId: "S1-11", method: "api" }, id: "work_log.my_day.updated_remaining_estimate", title: "当天工作日志数据中的本用例工作日志剩余进度估计百分比 应为 `45`", object: "api.work_log.my_day", operator: "remaining_estimate_percent", params: { bodyMarkerFrom: "data.updatedLogBodyMarker", valueFrom: "data.updatedRemainingEstimatePercent" } },
      { source: { caseStepId: "S1-12", method: "prisma" }, id: "db.work_log.updated_exists", title: "应存在 本用例成员在测试执行当天提交的正文标记为 `E2E-WORK-LOG-EDIT-TODAY-UPDATED` 的工作日志", object: "db.work_log_entry", operator: "exists_today_for_member", params: { bodyMarkerFrom: "data.updatedLogBodyMarker", memberEmailFrom: "data.memberEmail", saveAs: "updatedWorkLogEntry" } },
      { source: { caseStepId: "S1-13", method: "prisma" }, id: "db.work_log.original_absent", title: "应不存在 本用例成员在测试执行当天提交的正文标记为 `E2E-WORK-LOG-EDIT-TODAY-ORIGINAL` 的工作日志", object: "db.work_log_entry", operator: "absent_today_for_member", params: { bodyMarkerFrom: "data.originalLogBodyMarker", memberEmailFrom: "data.memberEmail" } },
      { source: { caseStepId: "S1-14", method: "prisma" }, id: "db.work_log.objective_snapshot", title: "本用例工作日志的目标标题快照 应为 `E2E-TARGET-WORK-LOG-EDIT-TODAY`", object: "db.work_log_entry.objective_title_snapshot", operator: "equals", params: { entryFrom: "runtime.updatedWorkLogEntry", valueFrom: "data.objectiveTitle" } },
      { source: { caseStepId: "S1-15", method: "prisma" }, id: "db.work_log.updated_duration", title: "本用例工作日志的记录时间分钟数 应为 `120`", object: "db.work_log_entry.duration_minutes", operator: "equals", params: { entryFrom: "runtime.updatedWorkLogEntry", valueFrom: "data.updatedDurationMinutes" } },
      { source: { caseStepId: "S1-16", method: "prisma" }, id: "db.work_log.updated_remaining_estimate", title: "本用例工作日志的剩余进度估计百分比 应为 `45`", object: "db.work_log_entry.remaining_estimate_percent", operator: "equals", params: { entryFrom: "runtime.updatedWorkLogEntry", valueFrom: "data.updatedRemainingEstimatePercent" } },
      { source: { caseStepId: "S1-17", method: "prisma" }, id: "db.work_log.count_today_for_objective", title: "本用例成员在测试执行当天、目标为 `E2E-TARGET-WORK-LOG-EDIT-TODAY` 的工作日志数量 应为 `1`", object: "db.work_log_entry", operator: "count_today_for_member_and_objective", params: { memberEmailFrom: "data.memberEmail", objectiveTitleFrom: "data.objectiveTitle", value: 1 } },
    ],
  },

  Clean: {
    description: "删除本用例日志、目标、成员身份并清空登录态",
    steps: [
      { source: { caseStepId: "Clean-1", method: "prisma" }, id: "db.work_log.delete_original_created", title: "删除 本用例创建的工作日志正文标记 `E2E-WORK-LOG-EDIT-TODAY-ORIGINAL` 对应的工作日志", object: "db.work_log_entry", operator: "delete_by_body_marker", params: { bodyMarkerFrom: "data.originalLogBodyMarker" } },
      { source: { caseStepId: "Clean-2", method: "prisma" }, id: "db.work_log.delete_updated_created", title: "删除 本用例创建的工作日志正文标记 `E2E-WORK-LOG-EDIT-TODAY-UPDATED` 对应的工作日志", object: "db.work_log_entry", operator: "delete_by_body_marker", params: { bodyMarkerFrom: "data.updatedLogBodyMarker" } },
      { source: { caseStepId: "Clean-3", method: "prisma" }, id: "db.objective.delete_created", title: "删除 本用例创建的目标 `E2E-TARGET-WORK-LOG-EDIT-TODAY` 及其派生数据", object: "db.objective", operator: "delete", params: { titleFrom: "data.objectiveTitle" } },
      { source: { caseStepId: "Clean-4", method: "api" }, id: "auth.logout", title: "注销当前成员登录会话", object: "auth", operator: "logout" },
      { source: { caseStepId: "Clean-5", method: "playwright" }, id: "browser.clear", title: "移除当前浏览器中的残留登录态", object: "browser", operator: "clear_state" },
      { source: { caseStepId: "Clean-6", method: "api" }, id: "ory.member_identity.delete", title: "删除 本用例成员登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-7", method: "prisma" }, id: "db.member_user.delete", title: "删除 本用例成员用户", object: "db.user", operator: "delete", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-8", method: "prisma" }, id: "db.work_log.original_absent", title: "应不存在 正文标记为 `E2E-WORK-LOG-EDIT-TODAY-ORIGINAL` 的工作日志", object: "db.work_log_entry", operator: "absent_by_body_marker", params: { bodyMarkerFrom: "data.originalLogBodyMarker" } },
      { source: { caseStepId: "Clean-9", method: "prisma" }, id: "db.work_log.updated_absent", title: "应不存在 正文标记为 `E2E-WORK-LOG-EDIT-TODAY-UPDATED` 的工作日志", object: "db.work_log_entry", operator: "absent_by_body_marker", params: { bodyMarkerFrom: "data.updatedLogBodyMarker" } },
      { source: { caseStepId: "Clean-10", method: "prisma" }, id: "db.objective.absent", title: "应不存在 标题为 `E2E-TARGET-WORK-LOG-EDIT-TODAY` 的目标", object: "db.objective", operator: "absent", params: { titleFrom: "data.objectiveTitle" } },
      { source: { caseStepId: "Clean-11", method: "api" }, id: "ory.member_identity.absent", title: "邮箱为 `orf-member-edit-today-work-log-e2e@orf.local` 的成员登录身份 应不存在", object: "ory.identity", operator: "absent", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-12", method: "prisma" }, id: "db.member_user.absent", title: "邮箱为 `orf-member-edit-today-work-log-e2e@orf.local` 的成员用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-13", method: "api" }, id: "session.unauthenticated", title: "当前会话 应为 未登录", object: "auth.session", operator: "unauthenticated" },
    ],
  },
} satisfies StateCaseSpec<MemberEditTodayWorkLogCaseData>;
