import { STATE_CASE_MODEL, type StateCaseSpec } from "../../_framework/types";
import type { MemberSubmitLootCaseData } from "./_support/member-submit-loot.context";

export const memberSubmitLootCase = {
  id: "acceptance.loot.submit.member",
  title: "成员可以提交战利品",
  model: STATE_CASE_MODEL,
  tags: ["acceptance", "loot", "member", "happy-path"],

  data: {
    email: "orf-member-e2e@orf.local",
    password: "OrfMemberE2E!2026",
    name: "ORF Member E2E",
    role: "member",
    resultTitle: "E2E-LOOT-RESULT: 成员提交战利品指标",
    metricName: "E2E 成员提交战利品完成率",
    lootBody: "E2E-LOOT-BODY: 成员提交战利品完成说明",
    evidenceText: "E2E-LOOT-EVIDENCE: 指标证据 https://example.test/e2e-loot-evidence",
    reportUrl: "https://example.test/e2e-self-test-report",
    selfTestReportBody: "E2E-LOOT-REPORT: 自测报告 https://example.test/e2e-self-test-report",
  },

  B: {
    description: "系统服务、Ory、数据库和预置普通成员可用，当前浏览器未登录且测试指标和测试战利品不存在",
    assertions: [
      { id: "backend.ready", title: "后端服务可用", object: "api.health", operator: "ok" },
      { id: "db.ready", title: "数据库可连接", object: "db", operator: "ready" },
      { id: "ory.ready", title: "Ory Admin API 可用", object: "ory.admin", operator: "ready" },
      {
        id: "ory.member_identity.exists",
        title: "普通成员 Ory 身份存在",
        object: "ory.identity",
        operator: "exists",
        params: { emailFrom: "data.email" },
      },
      { id: "db.member.active", title: "预置普通成员账号可用", object: "db.member", operator: "active", params: { emailFrom: "data.email" } },
      { id: "db.loot_target.available", title: "存在可构造成员提交战利品起点的目标", object: "db.loot_target", operator: "available" },
      {
        id: "db.loot_result.absent",
        title: "测试指标不存在",
        object: "db.result",
        operator: "absent",
        params: { titleFrom: "data.resultTitle" },
      },
      {
        id: "db.loot.absent",
        title: "测试战利品不存在",
        object: "db.loot",
        operator: "absent",
        params: { bodyFrom: "data.lootBody" },
      },
      { id: "session.unauthenticated", title: "后端 session 未登录", object: "auth.session", operator: "unauthenticated" },
      { id: "cookie.absent", title: "浏览器不存在登录 cookie", object: "browser.cookie", operator: "absent" },
      { id: "storage.empty", title: "浏览器 storage 不含登录态", object: "browser.auth_storage", operator: "empty" },
    ],
  },

  Setup: {
    description: "准备可提交战利品的冻结目标，登录普通成员并进入战利品提交页",
    steps: [
      { id: "browser.clear", title: "清理浏览器状态", object: "browser", operator: "clear_state" },
      {
        id: "db.loot_target.select",
        title: "选择可构造成员提交战利品起点的目标",
        object: "db.loot_target",
        operator: "select",
        params: { saveAs: "lootTarget" },
      },
      {
        id: "db.loot_target.original_state_recorded",
        title: "记录目标原始状态",
        object: "db.loot_target",
        operator: "original_state_recorded",
        params: { targetFrom: "runtime.lootTarget" },
      },
      {
        id: "db.loot_target.prepare",
        title: "准备目标为可提交战利品状态",
        object: "db.loot_target",
        operator: "prepare",
        params: { targetFrom: "runtime.lootTarget", memberNameFrom: "data.name" },
      },
      {
        id: "db.loot_result.create",
        title: "准备战利品前置指标",
        object: "db.loot_result",
        operator: "create",
        params: {
          targetFrom: "runtime.lootTarget",
          titleFrom: "data.resultTitle",
          metricNameFrom: "data.metricName",
          saveAs: "lootResult",
        },
      },
      { id: "page.goto.auth", title: "打开登录页", object: "page", operator: "goto", params: { path: "/auth" } },
      { id: "fill.email", title: "输入普通成员邮箱", object: "page", operator: "fill", params: { label: "Email", valueFrom: "data.email" } },
      {
        id: "fill.password",
        title: "输入普通成员密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.password" },
      },
      { id: "click.sign_in", title: "点击登录按钮", object: "page", operator: "click", params: { role: "button", name: "Sign In" } },
      {
        id: "session.member.authenticated",
        title: "等待普通成员 session 已登录",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      {
        id: "page.goto.loot",
        title: "打开目标战利品提交页",
        object: "page.loot",
        operator: "goto",
        params: { targetFrom: "runtime.lootTarget" },
      },
    ],
  },

  S0: {
    description: "普通成员已登录并位于战利品提交页，目标可提交战利品",
    assertions: [
      {
        id: "session.member.authenticated",
        title: "后端 session 已登录",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      { id: "url.loot", title: "当前页面是目标战利品提交页", object: "page.url", operator: "match", params: { pattern: "/objectives/.+/loot$" } },
      { id: "loot_form.visible", title: "战利品提交表单可见", object: "page.loot_form", operator: "visible" },
      {
        id: "db.loot_target.frozen_for_member",
        title: "目标处于实施阶段且包含普通成员",
        object: "db.loot_target",
        operator: "frozen_for_member",
        params: { targetFrom: "runtime.lootTarget", memberNameFrom: "data.name" },
      },
      {
        id: "db.loot_result.present",
        title: "目标存在战利品前置指标",
        object: "db.loot_result",
        operator: "present",
        params: { targetFrom: "runtime.lootTarget", resultFrom: "runtime.lootResult" },
      },
      {
        id: "db.loot.absent",
        title: "目标不存在测试战利品",
        object: "db.loot",
        operator: "absent",
        params: { bodyFrom: "data.lootBody" },
      },
    ],
  },

  Action: {
    description: "普通成员通过页面提交测试战利品",
    steps: [
      { id: "fill.loot_body", title: "输入完成说明", object: "page", operator: "fill", params: { label: "完成说明", valueFrom: "data.lootBody" } },
      {
        id: "fill.loot_evidence",
        title: "输入指标证据",
        object: "page.loot_form",
        operator: "fill_evidence",
        params: { valueFrom: "data.evidenceText" },
      },
      {
        id: "fill.self_test_report",
        title: "输入自测报告",
        object: "page",
        operator: "fill",
        params: { label: "自测报告", valueFrom: "data.selfTestReportBody" },
      },
      {
        id: "capture.submit_loot_response",
        title: "监听提交战利品请求",
        object: "api.loot_submit",
        operator: "capture_response",
        params: { targetFrom: "runtime.lootTarget", saveAs: "submitLootResponse" },
      },
      { id: "click.submit_loot", title: "点击提交", object: "page", operator: "click", params: { role: "button", name: "提交" } },
      {
        id: "submit_loot_response.record",
        title: "记录提交的战利品",
        object: "api.loot_submit_response",
        operator: "record_loot",
        params: { responseFrom: "runtime.submitLootResponse", saveAs: "submittedLoot" },
      },
    ],
  },

  S1: {
    description: "测试战利品已经持久化，目标进入待验收状态，普通成员仍保持登录",
    assertions: [
      {
        id: "submit_loot_response.ok",
        title: "提交战利品接口响应成功",
        object: "api.response",
        operator: "ok",
        params: { responseFrom: "runtime.submitLootResponse", status: 200 },
      },
      {
        id: "submitted_loot.matches",
        title: "提交战利品接口返回内容正确",
        object: "api.loot_submit_response",
        operator: "matches",
        params: {
          lootFrom: "runtime.submittedLoot",
          targetFrom: "runtime.lootTarget",
          resultFrom: "runtime.lootResult",
          memberNameFrom: "data.name",
          bodyFrom: "data.lootBody",
          evidenceTextFrom: "data.evidenceText",
          selfTestReportBodyFrom: "data.selfTestReportBody",
          reportUrlFrom: "data.reportUrl",
        },
      },
      {
        id: "db.loot.present",
        title: "数据库存在测试战利品",
        object: "db.loot",
        operator: "present",
        params: { targetFrom: "runtime.lootTarget", bodyFrom: "data.lootBody", selfTestReportBodyFrom: "data.selfTestReportBody" },
      },
      {
        id: "db.loot_target.submitted",
        title: "目标进入待验收状态",
        object: "db.loot_target",
        operator: "submitted",
        params: { targetFrom: "runtime.lootTarget" },
      },
      {
        id: "session.member.still_authenticated",
        title: "普通成员仍保持登录",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
    ],
  },

  Clean: {
    description: "删除测试战利品和测试指标，恢复目标原始状态并退出登录",
    steps: [
      {
        id: "db.loot.delete",
        title: "删除测试战利品",
        object: "db.loot",
        operator: "delete",
        params: { bodyFrom: "data.lootBody", lootFrom: "runtime.submittedLoot" },
      },
      {
        id: "db.loot_result.delete",
        title: "删除战利品前置指标",
        object: "db.loot_result",
        operator: "delete",
        params: { titleFrom: "data.resultTitle", resultFrom: "runtime.lootResult" },
      },
      {
        id: "db.loot_target.restore",
        title: "恢复目标原始状态",
        object: "db.loot_target",
        operator: "restore",
        params: { targetFrom: "runtime.lootTarget" },
      },
      { id: "auth.logout", title: "退出当前登录态", object: "auth", operator: "logout" },
      { id: "browser.clear", title: "清理浏览器状态", object: "browser", operator: "clear_state" },
      {
        id: "ory.member_identity.exists",
        title: "普通成员 Ory 身份仍然存在",
        object: "ory.identity",
        operator: "exists",
        params: { emailFrom: "data.email" },
      },
      { id: "db.member.active", title: "预置普通成员账号仍然可用", object: "db.member", operator: "active", params: { emailFrom: "data.email" } },
    ],
  },
} satisfies StateCaseSpec<MemberSubmitLootCaseData>;
