import { STATE_CASE_MODEL, type StateCaseSpec } from "../../_framework/types";
import type { MemberSubmitLootCaseData } from "./_support/member-submit-loot.context";

export const memberSubmitLootCase = {
  id: "acceptance.member-submit-loot",
  title: "成员提交战利品",
  model: STATE_CASE_MODEL,
  tags: ["acceptance", "loot", "member", "happy-path"],

  data: {
    email: "orf-member-submit-loot-e2e@orf.local",
    password: "OrfMemberSubmitLootE2E!2026",
    name: "ORF Member Submit Loot E2E",
    role: "member",
    objectiveId: "obj-testd-member-submit-loot",
    objectiveTitle: "E2E-MEMBER-SUBMIT-LOOT: 目标前置",
    resultTitle: "E2E-LOOT-RESULT: 成员提交战利品指标",
    metricName: "E2E 成员提交战利品完成率",
    lootBody: "E2E-LOOT-BODY: 成员提交战利品完成说明",
    evidenceText: "E2E-LOOT-EVIDENCE: 指标证据 https://example.test/e2e-loot-evidence",
    reportUrl: "https://example.test/e2e-self-test-report",
    selfTestReportBody: "E2E-LOOT-REPORT: 自测报告 https://example.test/e2e-self-test-report",
  },

  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      {
        source: { caseStepId: "B-1", method: "api" },
        id: "frontend.ready",
        title: "前端服务 应可用",
        object: "frontend.service",
        operator: "available",
      },
      {
        source: { caseStepId: "B-2", method: "api" },
        id: "backend.ready",
        title: "后端服务 应可用",
        object: "api.health",
        operator: "ok",
      },
      {
        source: { caseStepId: "B-3", method: "api" },
        id: "frontend.login_entry.accessible",
        title: "前端登录页入口 应可访问",
        object: "frontend.login_entry",
        operator: "accessible",
      },
      {
        source: { caseStepId: "B-4", method: "api" },
        id: "session.endpoint.accessible",
        title: "当前会话查询接口 应可访问",
        object: "auth.session",
        operator: "accessible",
      },
      {
        source: { caseStepId: "B-5", method: "prisma" },
        id: "db.ready",
        title: "ORF 数据库 应可连接",
        object: "db",
        operator: "ready",
      },
      {
        source: { caseStepId: "B-6", method: "prisma" },
        id: "db.schema.current",
        title: "ORF 数据库 schema 应为 当前测试版本",
        object: "db.schema",
        operator: "current",
      },
      {
        source: { caseStepId: "B-7", method: "api" },
        id: "ory.admin_public.ready",
        title: "Ory/Kratos Admin/Public API 应可访问",
        object: "ory.admin_public",
        operator: "ready",
      },
      {
        source: { caseStepId: "B-8", method: "api" },
        id: "session.unauthenticated",
        title: "当前会话 应为 未登录",
        object: "auth.session",
        operator: "unauthenticated",
      },
      {
        source: { caseStepId: "B-9", method: "playwright" },
        id: "cookie.absent",
        title: "当前浏览器 应不存在 Ory session cookie",
        object: "browser.cookie",
        operator: "absent",
      },
      {
        source: { caseStepId: "B-10", method: "playwright" },
        id: "storage.empty",
        title: "当前浏览器 storage 应不包含 登录态",
        object: "browser.auth_storage",
        operator: "empty",
      },
    ],
  },

  Setup: {
    description: "准备普通成员账号、本用例独占冻结目标和前置指标，登录普通成员并进入战利品提交页",
    steps: [
      {
        source: { caseStepId: "Setup-1", method: "prisma" },
        id: "db.loot.delete_residue",
        title: "删除可能残留的测试战利品",
        object: "db.loot",
        operator: "delete",
        params: { bodyFrom: "data.lootBody" },
      },
      {
        source: { caseStepId: "Setup-2", method: "prisma" },
        id: "db.result.delete_residue",
        title: "删除可能残留的测试指标",
        object: "db.result",
        operator: "delete",
        params: { titleFrom: "data.resultTitle" },
      },
      {
        source: { caseStepId: "Setup-3", method: "prisma" },
        id: "db.objective.delete_residue",
        title: "删除可能残留的本用例目标及其派生数据",
        object: "db.objective",
        operator: "delete_by_title",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Setup-4", method: "api" },
        id: "ory.member_identity.upsert",
        title: '准备邮箱为 "orf-member-submit-loot-e2e@orf.local" 的普通成员登录身份，并设置固定测试密码',
        object: "ory.identity",
        operator: "upsert_password",
        params: {
          emailFrom: "data.email",
          nameFrom: "data.name",
          passwordFrom: "data.password",
          saveAs: "memberIdentity",
        },
      },
      {
        source: { caseStepId: "Setup-5", method: "prisma" },
        id: "db.member.upsert",
        title: '准备邮箱为 "orf-member-submit-loot-e2e@orf.local"、角色为 member、状态为 active 的普通成员用户和默认团队成员关系',
        object: "db.user",
        operator: "upsert",
        params: {
          emailFrom: "data.email",
          nameFrom: "data.name",
          roleFrom: "data.role",
          status: "active",
          identityIdFrom: "runtime.memberIdentity.id",
          saveAs: "memberUser",
        },
      },
      {
        source: { caseStepId: "Setup-6", method: "prisma" },
        id: "db.objective.upsert_loot_target",
        title: '创建标题为 "E2E-MEMBER-SUBMIT-LOOT: 目标前置"、流转状态为 frozen、阶段为 goalFrozen 的本用例独占目标',
        object: "db.objective",
        operator: "upsert",
        params: {
          idFrom: "data.objectiveId",
          titleFrom: "data.objectiveTitle",
          teamIdFrom: "runtime.memberUser.teamId",
          stage: "goalFrozen",
          flowStatus: "frozen",
          status: "Draft",
          saveAs: "fixtureObjective",
        },
      },
      {
        source: { caseStepId: "Setup-7", method: "prisma" },
        id: "db.loot_target.from_objective",
        title: "记录本用例独占目标为 runtime.lootTarget",
        object: "db.loot_target",
        operator: "from_objective",
        params: { objectiveIdFrom: "runtime.fixtureObjective.id", saveAs: "lootTarget" },
      },
      {
        source: { caseStepId: "Setup-8", method: "prisma" },
        id: "db.loot_target.prepare",
        title: "设置本用例目标的挑战者包含普通成员，并保持实施阶段待提交战利品状态",
        object: "db.loot_target",
        operator: "prepare",
        params: { targetFrom: "runtime.lootTarget", memberNameFrom: "data.name" },
      },
      {
        source: { caseStepId: "Setup-9", method: "prisma" },
        id: "db.loot_result.create",
        title: '为本用例目标创建标题为 "E2E-LOOT-RESULT: 成员提交战利品指标" 的前置指标',
        object: "db.loot_result",
        operator: "create",
        params: {
          targetFrom: "runtime.lootTarget",
          titleFrom: "data.resultTitle",
          metricNameFrom: "data.metricName",
          saveAs: "lootResult",
        },
      },
      {
        source: { caseStepId: "Setup-10", method: "api" },
        id: "ory.member_sessions.revoke",
        title: "撤销普通成员登录身份可能残留的 Ory session",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Setup-11", method: "playwright" },
        id: "browser.clear",
        title: "清空当前浏览器上下文的 cookies/localStorage/sessionStorage",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "Setup-12", method: "playwright" },
        id: "page.goto.auth",
        title: "打开 登录页",
        object: "page",
        operator: "goto",
        params: { path: "/auth" },
      },
      {
        source: { caseStepId: "Setup-13", method: "playwright" },
        id: "fill.email",
        title: "在邮箱输入框输入普通成员测试邮箱",
        object: "page",
        operator: "fill",
        params: { label: "Email", valueFrom: "data.email" },
      },
      {
        source: { caseStepId: "Setup-14", method: "playwright" },
        id: "fill.password",
        title: "在密码输入框输入普通成员测试密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.password" },
      },
      {
        source: { caseStepId: "Setup-15", method: "playwright" },
        id: "click.sign_in",
        title: '点击 "Sign In" 登录操作',
        object: "page",
        operator: "click",
        params: { role: "button", name: "Sign In" },
      },
      {
        source: { caseStepId: "Setup-16", method: "api" },
        id: "session.member.authenticated",
        title: "当前会话 应为 普通成员已登录",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      {
        source: { caseStepId: "Setup-17", method: "playwright" },
        id: "page.goto.loot",
        title: "打开 本用例目标战利品提交页",
        object: "page.loot",
        operator: "goto",
        params: { targetFrom: "runtime.lootTarget" },
      },
    ],
  },

  S0: {
    description: "普通成员已登录并位于本用例目标战利品提交页，目标可提交战利品",
    assertions: [
      {
        source: { caseStepId: "S0-1", method: "api" },
        id: "session.member.authenticated",
        title: '当前会话 应为 邮箱为 "orf-member-submit-loot-e2e@orf.local"、角色为 member、状态为 active 的已登录会话',
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      {
        source: { caseStepId: "S0-2", method: "playwright" },
        id: "url.loot",
        title: "当前页面 应为 本用例目标战利品提交页",
        object: "page.url",
        operator: "match",
        params: { pattern: "/objectives/.+/loot$" },
      },
      {
        source: { caseStepId: "S0-3", method: "playwright" },
        id: "loot_form.visible",
        title: "战利品提交表单 应可见",
        object: "page.loot_form",
        operator: "visible",
      },
      {
        source: { caseStepId: "S0-4", method: "prisma" },
        id: "db.loot_target.frozen_for_member",
        title: "本用例目标 应为 frozen / goalFrozen 且挑战者包含普通成员",
        object: "db.loot_target",
        operator: "frozen_for_member",
        params: { targetFrom: "runtime.lootTarget", memberNameFrom: "data.name" },
      },
      {
        source: { caseStepId: "S0-5", method: "prisma" },
        id: "db.loot_result.present",
        title: "本用例目标 应存在 前置测试指标",
        object: "db.loot_result",
        operator: "present",
        params: { targetFrom: "runtime.lootTarget", resultFrom: "runtime.lootResult" },
      },
      {
        source: { caseStepId: "S0-6", method: "prisma" },
        id: "db.loot.absent",
        title: "本用例目标 应不存在 测试战利品",
        object: "db.loot",
        operator: "absent",
        params: { bodyFrom: "data.lootBody" },
      },
    ],
  },

  Action: {
    description: "普通成员通过页面提交测试战利品",
    steps: [
      {
        source: { caseStepId: "Action-1", method: "playwright" },
        id: "fill.loot_body",
        title: "在完成说明输入框输入测试完成说明",
        object: "page",
        operator: "fill",
        params: { label: "完成说明", valueFrom: "data.lootBody" },
      },
      {
        source: { caseStepId: "Action-2", method: "playwright" },
        id: "fill.loot_evidence",
        title: "在测试指标证据输入框输入测试证据文本",
        object: "page.loot_form",
        operator: "fill_evidence",
        params: { valueFrom: "data.evidenceText" },
      },
      {
        source: { caseStepId: "Action-3", method: "playwright" },
        id: "fill.self_test_report",
        title: "在自测报告输入框输入包含链接的测试报告内容",
        object: "page",
        operator: "fill",
        params: { label: "自测报告", valueFrom: "data.selfTestReportBody" },
      },
      {
        source: { caseStepId: "Action-4", method: "playwright" },
        id: "capture.submit_loot_response",
        title: "在点击提交前注册提交战利品接口响应捕获",
        object: "api.loot_submit",
        operator: "capture_response",
        params: { targetFrom: "runtime.lootTarget", saveAs: "submitLootResponse" },
      },
      {
        source: { caseStepId: "Action-5", method: "playwright" },
        id: "click.submit_loot",
        title: "点击提交操作",
        object: "page",
        operator: "click",
        params: { role: "button", name: "提交" },
      },
      {
        source: { caseStepId: "Action-6", method: "api" },
        id: "submit_loot_response.record",
        title: "记录提交战利品接口返回的战利品",
        object: "api.loot_submit_response",
        operator: "record_loot",
        params: { responseFrom: "runtime.submitLootResponse", saveAs: "submittedLoot" },
      },
    ],
  },

  S1: {
    description: "测试战利品已经持久化，目标进入待验收状态，普通成员仍保持登录",
    assertions: [
      {
        source: { caseStepId: "S1-1", method: "api" },
        id: "submit_loot_response.ok",
        title: "提交战利品接口响应 应成功",
        object: "api.response",
        operator: "ok",
        params: { responseFrom: "runtime.submitLootResponse", status: 200 },
      },
      {
        source: { caseStepId: "S1-2", method: "api" },
        id: "submitted_loot.matches",
        title: "提交战利品接口返回内容 应属于本用例目标、由普通成员提交，并包含测试完成说明、测试证据文本和测试报告链接",
        object: "api.loot_submit_response",
        operator: "matches",
        params: {
          lootFrom: "runtime.submittedLoot",
          targetFrom: "runtime.lootTarget",
          resultFrom: "runtime.lootResult",
          memberNameFrom: "data.name",
          bodyFrom: "data.lootBody",
          evidenceTextFrom: "data.evidenceText",
          selfTestReportBodyFrom: "data.selfTestReportBody",
          reportUrlFrom: "data.reportUrl",
        },
      },
      {
        source: { caseStepId: "S1-3", method: "prisma" },
        id: "db.loot.present",
        title: "数据库中 应存在 该测试战利品",
        object: "db.loot",
        operator: "present",
        params: { targetFrom: "runtime.lootTarget", bodyFrom: "data.lootBody", selfTestReportBodyFrom: "data.selfTestReportBody" },
      },
      {
        source: { caseStepId: "S1-4", method: "prisma" },
        id: "db.loot_target.submitted",
        title: "本用例目标 flowStatus 应为 submitted 且记录 lootSubmittedAt",
        object: "db.loot_target",
        operator: "submitted",
        params: { targetFrom: "runtime.lootTarget" },
      },
      {
        source: { caseStepId: "S1-5", method: "api" },
        id: "session.member.still_authenticated",
        title: "当前会话 应仍为 普通成员已登录",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
    ],
  },

  Clean: {
    description: "删除本用例创建的战利品、指标、目标、普通成员账号和页面会话状态",
    steps: [
      {
        source: { caseStepId: "Clean-1", method: "prisma" },
        id: "db.loot.delete",
        title: "删除本用例创建的测试战利品",
        object: "db.loot",
        operator: "delete",
        params: { bodyFrom: "data.lootBody", lootFrom: "runtime.submittedLoot" },
      },
      {
        source: { caseStepId: "Clean-2", method: "prisma" },
        id: "db.loot_result.delete",
        title: "删除本用例创建的测试指标",
        object: "db.loot_result",
        operator: "delete",
        params: { titleFrom: "data.resultTitle", resultFrom: "runtime.lootResult" },
      },
      {
        source: { caseStepId: "Clean-3", method: "prisma" },
        id: "db.objective.delete",
        title: "删除本用例独占目标及其派生数据",
        object: "db.objective",
        operator: "delete",
        params: { idFrom: "data.objectiveId", titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Clean-4", method: "api" },
        id: "auth.logout",
        title: "退出当前登录态",
        object: "auth",
        operator: "logout",
      },
      {
        source: { caseStepId: "Clean-5", method: "playwright" },
        id: "page.runtime.stop",
        title: "停止当前页面运行态",
        object: "page.runtime",
        operator: "stop",
      },
      {
        source: { caseStepId: "Clean-6", method: "playwright" },
        id: "browser.clear",
        title: "清空当前浏览器上下文的 cookies/localStorage/sessionStorage",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "Clean-7", method: "api" },
        id: "ory.member_sessions.revoke",
        title: "撤销普通成员登录身份的 Ory session",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-8", method: "api" },
        id: "ory.member_identity.delete",
        title: "删除普通成员 Ory 身份",
        object: "ory.identity",
        operator: "delete_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-9", method: "prisma" },
        id: "db.member.delete_memberships",
        title: "删除普通成员默认团队成员关系",
        object: "db.user",
        operator: "delete_memberships",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-10", method: "prisma" },
        id: "db.member.delete",
        title: "删除普通成员用户",
        object: "db.user",
        operator: "delete",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-11", method: "prisma" },
        id: "db.loot.absent",
        title: "测试战利品 应不存在",
        object: "db.loot",
        operator: "absent",
        params: { bodyFrom: "data.lootBody" },
      },
      {
        source: { caseStepId: "Clean-12", method: "prisma" },
        id: "db.result.absent",
        title: "测试指标 应不存在",
        object: "db.result",
        operator: "absent",
        params: { titleFrom: "data.resultTitle" },
      },
      {
        source: { caseStepId: "Clean-13", method: "prisma" },
        id: "db.objective.absent",
        title: "本用例目标 应不存在",
        object: "db.objective",
        operator: "absent",
        params: { idFrom: "data.objectiveId", titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Clean-14", method: "prisma" },
        id: "db.member.absent",
        title: "普通成员用户 应不存在",
        object: "db.user",
        operator: "absent",
        params: { emailFrom: "data.email" },
      },
    ],
  },
} satisfies StateCaseSpec<MemberSubmitLootCaseData>;
