import { STATE_CASE_MODEL, type StateCaseSpec } from "../../_framework/types";
import type { MemberSubmitLootCaseData } from "./_support/member-submit-loot.context";

export const memberSubmitLootCase = {
  id: "acceptance.member-submit-loot",
  title: "成员提交战利品",
  model: STATE_CASE_MODEL,
  tags: ["acceptance", "loot", "member", "happy-path"],

  data: {
    email: "orf-member-submit-loot-e2e@orf.local",
    password: "OrfMemberSubmitLootE2E!2026",
    name: "ORF Member Submit Loot E2E",
    role: "member",
    objectiveId: "obj-testd-member-submit-loot",
    objectiveTitle: "E2E-MEMBER-SUBMIT-LOOT: 目标前置",
    resultTitle: "E2E-LOOT-RESULT: 成员提交战利品指标",
    metricName: "E2E 成员提交战利品完成率",
    lootBody: "E2E-LOOT-BODY: 成员提交战利品完成说明",
    evidenceText: "E2E-LOOT-EVIDENCE: 指标证据 https://example.test/e2e-loot-evidence",
    reportUrl: "https://example.test/e2e-self-test-report",
  },

  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      {
        source: { caseStepId: "B-1", method: "api" },
        id: "frontend.ready",
        title: "前端服务 应可用",
        object: "frontend.service",
        operator: "available",
      },
      {
        source: { caseStepId: "B-2", method: "api" },
        id: "backend.ready",
        title: "后端服务 应可用",
        object: "api.health",
        operator: "ok",
      },
      {
        source: { caseStepId: "B-3", method: "api" },
        id: "frontend.login_entry.accessible",
        title: "前端登录页入口 应可访问",
        object: "frontend.login_entry",
        operator: "accessible",
      },
      {
        source: { caseStepId: "B-4", method: "api" },
        id: "session.endpoint.accessible",
        title: "当前会话查询能力 应可用",
        object: "auth.session",
        operator: "accessible",
      },
      {
        source: { caseStepId: "B-5", method: "prisma" },
        id: "db.ready",
        title: "ORF 数据库 应可连接",
        object: "db",
        operator: "ready",
      },
      {
        source: { caseStepId: "B-6", method: "prisma" },
        id: "db.schema.current",
        title: "ORF 数据库 schema 应为 当前测试版本",
        object: "db.schema",
        operator: "current",
      },
      {
        source: { caseStepId: "B-7", method: "api" },
        id: "ory.admin_public.ready",
        title: "Ory/Kratos 认证服务的管理和公共访问能力 应可用",
        object: "ory.admin_public",
        operator: "ready",
      },
      {
        source: { caseStepId: "B-8", method: "api" },
        id: "session.unauthenticated",
        title: "当前会话 应为 未登录",
        object: "auth.session",
        operator: "unauthenticated",
      },
      {
        source: { caseStepId: "B-9", method: "playwright" },
        id: "cookie.absent",
        title: "当前浏览器 应不存在 Ory 登录会话 cookie",
        object: "browser.cookie",
        operator: "absent",
      },
      {
        source: { caseStepId: "B-10", method: "playwright" },
        id: "storage.empty",
        title: "当前浏览器 应不保留本地登录态",
        object: "browser.auth_storage",
        operator: "empty",
      },
    ],
  },

  Setup: {
    description: "准备普通成员账号、本用例独占冻结目标和前置指标，登录普通成员并进入战利品提交页",
    steps: [
      {
        source: { caseStepId: "Setup-1", method: "prisma" },
        id: "db.loot.delete_residue",
        title: "删除可能残留的内容为 `E2E-LOOT-BODY: 成员提交战利品完成说明` 的测试战利品",
        object: "db.loot",
        operator: "delete",
        params: { bodyFrom: "data.lootBody" },
      },
      {
        source: { caseStepId: "Setup-2", method: "prisma" },
        id: "db.result.delete_residue",
        title: "删除可能残留的标题为 `E2E-LOOT-RESULT: 成员提交战利品指标` 的测试指标",
        object: "db.result",
        operator: "delete",
        params: { titleFrom: "data.resultTitle" },
      },
      {
        source: { caseStepId: "Setup-3", method: "prisma" },
        id: "db.objective.delete_residue",
        title: "删除可能残留的标题为 `E2E-MEMBER-SUBMIT-LOOT: 目标前置` 的本用例目标及其派生数据",
        object: "db.objective",
        operator: "delete_by_title",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Setup-4", method: "api" },
        id: "ory.member_identity.upsert",
        title: "准备邮箱为 `orf-member-submit-loot-e2e@orf.local`、使用固定测试密码的普通成员登录身份",
        object: "ory.identity",
        operator: "upsert_password",
        params: {
          emailFrom: "data.email",
          nameFrom: "data.name",
          passwordFrom: "data.password",
          saveAs: "memberIdentity",
        },
      },
      {
        source: { caseStepId: "Setup-5", method: "prisma" },
        id: "db.member.upsert",
        title: "准备邮箱为 `orf-member-submit-loot-e2e@orf.local`、角色为 `member`、状态为 `active` 的普通成员用户和默认团队成员关系",
        object: "db.user",
        operator: "upsert",
        params: {
          emailFrom: "data.email",
          nameFrom: "data.name",
          roleFrom: "data.role",
          status: "active",
          identityIdFrom: "runtime.memberIdentity.id",
          saveAs: "memberUser",
        },
      },
      {
        source: { caseStepId: "Setup-6", method: "prisma" },
        id: "db.objective.upsert_loot_target",
        title: "创建 本用例目标，标题为 `E2E-MEMBER-SUBMIT-LOOT: 目标前置`、流转状态为 `frozen`、阶段为 `goalFrozen`",
        object: "db.objective",
        operator: "upsert",
        params: {
          idFrom: "data.objectiveId",
          titleFrom: "data.objectiveTitle",
          teamIdFrom: "runtime.memberUser.teamId",
          stage: "goalFrozen",
          flowStatus: "frozen",
          status: "Draft",
          saveAs: "fixtureObjective",
        },
      },
      {
        source: { caseStepId: "Setup-7", method: "prisma" },
        id: "db.loot_target.from_objective",
        title: "记录 本用例目标",
        object: "db.loot_target",
        operator: "from_objective",
        params: { objectiveIdFrom: "runtime.fixtureObjective.id", saveAs: "lootTarget" },
      },
      {
        source: { caseStepId: "Setup-8", method: "prisma" },
        id: "db.loot_target.add_challenger",
        title: "设置 本用例目标的挑战者包含普通成员",
        object: "db.loot_target",
        operator: "add_challenger",
        params: { targetFrom: "runtime.lootTarget", memberNameFrom: "data.name" },
      },
      {
        source: { caseStepId: "Setup-9", method: "prisma" },
        id: "db.loot_target.ready_for_submission",
        title: "设置 本用例目标为实施阶段待提交战利品状态",
        object: "db.loot_target",
        operator: "ready_for_submission",
        params: { targetFrom: "runtime.lootTarget" },
      },
      {
        source: { caseStepId: "Setup-10", method: "prisma" },
        id: "db.loot_result.create",
        title: "创建 本用例目标的前置测试指标，标题为 `E2E-LOOT-RESULT: 成员提交战利品指标`",
        object: "db.loot_result",
        operator: "create",
        params: {
          targetFrom: "runtime.lootTarget",
          titleFrom: "data.resultTitle",
          metricNameFrom: "data.metricName",
          saveAs: "lootResult",
        },
      },
      {
        source: { caseStepId: "Setup-11", method: "api" },
        id: "ory.member_sessions.revoke",
        title: "撤销普通成员登录身份可能残留的登录会话",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Setup-12", method: "playwright" },
        id: "browser.clear",
        title: "移除当前浏览器中的残留登录态",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "Setup-13", method: "playwright" },
        id: "page.goto.auth",
        title: "打开 ORF 登录页",
        object: "page",
        operator: "goto",
        params: { path: "/auth" },
      },
      {
        source: { caseStepId: "Setup-14", method: "playwright" },
        id: "fill.email",
        title: "在邮箱输入框输入普通成员固定测试邮箱",
        object: "page",
        operator: "fill",
        params: { label: "Email", valueFrom: "data.email" },
      },
      {
        source: { caseStepId: "Setup-15", method: "playwright" },
        id: "fill.password",
        title: "在密码输入框输入普通成员固定测试密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.password" },
      },
      {
        source: { caseStepId: "Setup-16", method: "playwright" },
        id: "click.sign_in",
        title: "点击 \"Sign In\" 登录操作",
        object: "page",
        operator: "click",
        params: { role: "button", name: "Sign In" },
      },
      {
        source: { caseStepId: "Setup-17", method: "api" },
        id: "session.member.authenticated",
        title: "当前会话 应为 普通成员的已登录会话",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      {
        source: { caseStepId: "Setup-18", method: "playwright" },
        id: "page.goto.loot",
        title: "打开 本用例目标战利品提交页",
        object: "page.loot",
        operator: "goto",
        params: { targetFrom: "runtime.lootTarget" },
      },
    ],
  },

  S0: {
    description: "普通成员已登录并位于本用例目标战利品提交页，目标可提交战利品",
    assertions: [
      {
        source: { caseStepId: "S0-1", method: "api" },
        id: "session.member.authenticated",
        title: "当前会话 应为 邮箱为 `orf-member-submit-loot-e2e@orf.local`、角色为 `member`、状态为 `active` 的已登录会话",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      {
        source: { caseStepId: "S0-2", method: "playwright" },
        id: "url.loot",
        title: "当前页面 应为 本用例目标战利品提交页",
        object: "page.url",
        operator: "match",
        params: { pattern: "/objectives/.+/loot$" },
      },
      {
        source: { caseStepId: "S0-3", method: "playwright" },
        id: "loot_form.visible",
        title: "战利品提交表单 应可见",
        object: "page.loot_form",
        operator: "visible",
      },
      {
        source: { caseStepId: "S0-4", method: "prisma" },
        id: "db.loot_target.frozen_for_member",
        title: "本用例目标 应为 流转状态 `frozen`、阶段 `goalFrozen` 且挑战者包含普通成员",
        object: "db.loot_target",
        operator: "frozen_for_member",
        params: { targetFrom: "runtime.lootTarget", memberNameFrom: "data.name" },
      },
      {
        source: { caseStepId: "S0-5", method: "prisma" },
        id: "db.loot_result.present",
        title: "本用例目标 应存在 标题为 `E2E-LOOT-RESULT: 成员提交战利品指标` 的前置测试指标",
        object: "db.loot_result",
        operator: "present",
        params: { targetFrom: "runtime.lootTarget", resultFrom: "runtime.lootResult" },
      },
      {
        source: { caseStepId: "S0-6", method: "prisma" },
        id: "db.loot.absent",
        title: "本用例目标 应不存在 内容为 `E2E-LOOT-BODY: 成员提交战利品完成说明` 的测试战利品",
        object: "db.loot",
        operator: "absent",
        params: { bodyFrom: "data.lootBody" },
      },
    ],
  },

  Action: {
    description: "普通成员通过页面提交测试战利品",
    steps: [
      {
        source: { caseStepId: "Action-1", method: "playwright" },
        id: "fill.loot_body",
        title: "在 \"完成说明\" 输入框 输入 测试完成说明",
        object: "page",
        operator: "fill",
        params: { label: "完成说明", valueFrom: "data.lootBody" },
      },
      {
        source: { caseStepId: "Action-2", method: "playwright" },
        id: "fill.loot_evidence",
        title: "在前置测试指标证据输入框 输入 测试证据文本",
        object: "page.loot_form",
        operator: "fill_evidence",
        params: { valueFrom: "data.evidenceText" },
      },
      {
        source: { caseStepId: "Action-3", method: "playwright" },
        id: "fill.self_test_report",
        title: "在 \"自测报告\" 输入框 输入 自测报告链接",
        object: "page",
        operator: "fill",
        params: { label: "自测报告", valueFrom: "data.reportUrl" },
      },
      {
        source: { caseStepId: "Action-4", method: "playwright" },
        id: "submit.loot_form",
        title: "点击 \"正式提交\" 提交战利品操作",
        object: "page.loot_form",
        operator: "submit",
        params: { targetFrom: "runtime.lootTarget", saveAs: "submitLootResponse" },
      },
      {
        source: { caseStepId: "Action-5", method: "api" },
        id: "submit_loot_response.record",
        title: "记录 提交后的测试战利品",
        object: "api.loot_submit_response",
        operator: "record_loot",
        params: { responseFrom: "runtime.submitLootResponse", saveAs: "submittedLoot" },
      },
    ],
  },

  S1: {
    description: "测试战利品已经持久化，目标进入待验收状态，普通成员仍保持登录",
    assertions: [
      {
        source: { caseStepId: "S1-1", method: "api" },
        id: "submitted_loot.belongs_to_target",
        title: "提交后的测试战利品 应属于 本用例目标",
        object: "api.loot_submit_response",
        operator: "belongs_to_target",
        params: { lootFrom: "runtime.submittedLoot", targetFrom: "runtime.lootTarget" },
      },
      {
        source: { caseStepId: "S1-2", method: "api" },
        id: "submitted_loot.submitted_by_member",
        title: "提交后的测试战利品 应由 普通成员提交",
        object: "api.loot_submit_response",
        operator: "submitted_by_member",
        params: { lootFrom: "runtime.submittedLoot", memberNameFrom: "data.name" },
      },
      {
        source: { caseStepId: "S1-3", method: "api" },
        id: "submitted_loot.contains_body",
        title: "提交后的测试战利品 应包含 测试完成说明",
        object: "api.loot_submit_response",
        operator: "contains_body",
        params: { lootFrom: "runtime.submittedLoot", bodyFrom: "data.lootBody" },
      },
      {
        source: { caseStepId: "S1-4", method: "api" },
        id: "submitted_loot.contains_evidence",
        title: "提交后的测试战利品 应包含 前置测试指标的测试证据文本",
        object: "api.loot_submit_response",
        operator: "contains_evidence",
        params: { lootFrom: "runtime.submittedLoot", resultFrom: "runtime.lootResult", evidenceTextFrom: "data.evidenceText" },
      },
      {
        source: { caseStepId: "S1-5", method: "api" },
        id: "submitted_loot.report_url_exact",
        title: "提交后的测试战利品的自测报告 应为 自测报告链接",
        object: "api.loot_submit_response",
        operator: "report_url_exact",
        params: {
          lootFrom: "runtime.submittedLoot",
          reportUrlFrom: "data.reportUrl",
        },
      },
      {
        source: { caseStepId: "S1-6", method: "prisma" },
        id: "db.loot.present",
        title: "本用例目标 应存在 内容为 `E2E-LOOT-BODY: 成员提交战利品完成说明` 的测试战利品",
        object: "db.loot",
        operator: "present",
        params: { targetFrom: "runtime.lootTarget", bodyFrom: "data.lootBody", selfTestReportBodyFrom: "data.reportUrl" },
      },
      {
        source: { caseStepId: "S1-7", method: "prisma" },
        id: "db.loot_target.submitted",
        title: "本用例目标 应为 流转状态 `submitted` 且战利品提交时间已存在",
        object: "db.loot_target",
        operator: "submitted",
        params: { targetFrom: "runtime.lootTarget" },
      },
      {
        source: { caseStepId: "S1-8", method: "api" },
        id: "session.member.still_authenticated",
        title: "当前会话 应仍为 普通成员的已登录会话",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
    ],
  },

  Clean: {
    description: "删除本用例创建的战利品、指标、目标、普通成员账号和页面会话状态",
    steps: [
      {
        source: { caseStepId: "Clean-1", method: "prisma" },
        id: "db.loot.delete",
        title: "删除 本用例创建的测试战利品",
        object: "db.loot",
        operator: "delete",
        params: { bodyFrom: "data.lootBody", lootFrom: "runtime.submittedLoot" },
      },
      {
        source: { caseStepId: "Clean-2", method: "prisma" },
        id: "db.loot_result.delete",
        title: "删除 本用例创建的测试指标",
        object: "db.loot_result",
        operator: "delete",
        params: { titleFrom: "data.resultTitle", resultFrom: "runtime.lootResult" },
      },
      {
        source: { caseStepId: "Clean-3", method: "prisma" },
        id: "db.objective.delete",
        title: "删除 本用例独占目标及其派生数据",
        object: "db.objective",
        operator: "delete",
        params: { idFrom: "data.objectiveId", titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Clean-4", method: "api" },
        id: "auth.logout",
        title: "注销当前登录会话",
        object: "auth",
        operator: "logout",
      },
      {
        source: { caseStepId: "Clean-5", method: "playwright" },
        id: "page.runtime.stop",
        title: "离开当前 ORF 前端页面",
        object: "page.runtime",
        operator: "stop",
      },
      {
        source: { caseStepId: "Clean-6", method: "playwright" },
        id: "browser.clear",
        title: "移除当前浏览器中的残留登录态",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "Clean-7", method: "api" },
        id: "ory.member_sessions.revoke",
        title: "撤销普通成员登录身份的残留登录会话",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-8", method: "api" },
        id: "ory.member_identity.delete",
        title: "删除邮箱为 `orf-member-submit-loot-e2e@orf.local` 的普通成员登录身份",
        object: "ory.identity",
        operator: "delete_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-9", method: "prisma" },
        id: "db.member.delete_memberships",
        title: "删除邮箱为 `orf-member-submit-loot-e2e@orf.local` 的普通成员默认团队成员关系",
        object: "db.user",
        operator: "delete_memberships",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-10", method: "prisma" },
        id: "db.member.delete",
        title: "删除邮箱为 `orf-member-submit-loot-e2e@orf.local` 的普通成员用户",
        object: "db.user",
        operator: "delete",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-11", method: "prisma" },
        id: "db.loot.absent",
        title: "应不存在 内容为 `E2E-LOOT-BODY: 成员提交战利品完成说明` 的测试战利品",
        object: "db.loot",
        operator: "absent",
        params: { bodyFrom: "data.lootBody" },
      },
      {
        source: { caseStepId: "Clean-12", method: "prisma" },
        id: "db.result.absent",
        title: "应不存在 标题为 `E2E-LOOT-RESULT: 成员提交战利品指标` 的测试指标",
        object: "db.result",
        operator: "absent",
        params: { titleFrom: "data.resultTitle" },
      },
      {
        source: { caseStepId: "Clean-13", method: "prisma" },
        id: "db.objective.absent",
        title: "应不存在 标题为 `E2E-MEMBER-SUBMIT-LOOT: 目标前置` 的本用例目标",
        object: "db.objective",
        operator: "absent",
        params: { idFrom: "data.objectiveId", titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Clean-14", method: "prisma" },
        id: "db.member.absent",
        title: "应不存在 邮箱为 `orf-member-submit-loot-e2e@orf.local` 的普通成员用户",
        object: "db.user",
        operator: "absent",
        params: { emailFrom: "data.email" },
      },
    ],
  },
} satisfies StateCaseSpec<MemberSubmitLootCaseData>;
