import { STATE_CASE_MODEL, type StateCaseSpec, type StepExecutionMethod, type StepSpec } from "../../_framework/types";
import type { SystemMembersReviewCaseData } from "./_support/members-review.context";

function step(
  caseStepId: string,
  method: StepExecutionMethod,
  id: string,
  title: string,
  object: string,
  operator: string,
  params?: Record<string, unknown>,
): StepSpec {
  return {
    source: { caseStepId, method },
    id,
    title,
    object,
    operator,
    ...(params ? { params } : {}),
  };
}

export const systemMembersReviewCase = {
  id: "system.members-review.registration",
  title: "08-成员管理注册申请审核校验",
  model: STATE_CASE_MODEL,
  tags: ["system", "members", "review", "registration"],
  data: {
    admin: {
      email: "orf-system-members-review-admin-e2e@orf.local",
      password: "OrfSystemMembersReviewAdminE2E!2026",
      name: "ORF Members Review Admin E2E",
      role: "admin",
    },
    approveUser: {
      email: "orf-system-members-review-approve-e2e@orf.local",
      password: "OrfSystemMembersReviewApproveE2E!2026",
      name: "ORF Members Review Approve E2E",
      role: "member",
    },
    rejectUser: {
      email: "orf-system-members-review-reject-e2e@orf.local",
      password: "OrfSystemMembersReviewRejectE2E!2026",
      name: "ORF Members Review Reject E2E",
      role: "member",
    },
    cancelUser: {
      email: "orf-system-members-review-cancel-e2e@orf.local",
      password: "OrfSystemMembersReviewCancelE2E!2026",
      name: "ORF Members Review Cancel E2E",
      role: "member",
    },
    defaultLandingPath: "/bounties",
    membersPath: "/system/members",
  },
  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      step("B-1", "api", "frontend.ready", "前端服务 应可用", "frontend.service", "available"),
      step("B-2", "api", "backend.ready", "后端服务 应可用", "api.health", "ok"),
      step("B-3", "api", "frontend.login_entry.accessible", "前端登录页入口 应可访问", "frontend.login_entry", "accessible"),
      step("B-4", "api", "session.endpoint.accessible", "当前会话查询能力 应可用", "auth.session", "accessible"),
      step("B-5", "prisma", "db.ready", "ORF 数据库 应可连接", "db", "ready"),
      step("B-6", "prisma", "db.schema.current", "ORF 数据库 schema 应为 当前测试版本", "db.schema", "current"),
      step("B-7", "api", "ory.admin_public.ready", "Ory/Kratos 认证服务的管理和公共访问能力 应可用", "ory.admin_public", "ready"),
      step("B-8", "api", "session.unauthenticated", "当前会话 应为 未登录", "auth.session", "unauthenticated"),
      step("B-9", "playwright", "cookie.absent", "当前浏览器 应不存在 Ory 登录会话 cookie", "browser.cookie", "absent"),
      step("B-10", "playwright", "storage.empty", "当前浏览器 应不保留本地登录态", "browser.auth_storage", "empty"),
    ],
  },
  Setup: {
    description: "准备管理员和三个待审核注册申请用户，并以管理员身份进入成员管理页面",
    steps: [
      step("Setup-1", "api", "ory.admin_identity.upsert", "准备邮箱为 `orf-system-members-review-admin-e2e@orf.local`、使用固定测试密码的成员管理注册申请审核管理员测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.admin.email", passwordFrom: "data.admin.password", nameFrom: "data.admin.name", saveAs: "adminIdentity" }),
      step("Setup-2", "prisma", "db.admin_user.upsert", "准备姓名为 \"ORF Members Review Admin E2E\"、邮箱为 `orf-system-members-review-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的成员管理注册申请审核管理员测试用户", "db.user", "upsert", { emailFrom: "data.admin.email", passwordFrom: "data.admin.password", nameFrom: "data.admin.name", roleFrom: "data.admin.role", status: "active", identityIdFrom: "runtime.adminIdentity.id", saveAs: "adminUser" }),
      step("Setup-3", "api", "admin.preferences.default_landing_path.set", "设置成员管理注册申请审核管理员测试用户默认进入页面为 首页（默认系统页）", "user.preferences", "set_default_landing_path_by_email", { emailFrom: "data.admin.email", pathFrom: "data.defaultLandingPath" }),
      step("Setup-4", "api", "ory.approve_identity.upsert", "准备邮箱为 `orf-system-members-review-approve-e2e@orf.local`、使用固定测试密码的成员管理待通过注册申请测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.approveUser.email", passwordFrom: "data.approveUser.password", nameFrom: "data.approveUser.name", saveAs: "approveIdentity" }),
      step("Setup-5", "prisma", "db.approve_user.upsert", "准备姓名为 \"ORF Members Review Approve E2E\"、邮箱为 `orf-system-members-review-approve-e2e@orf.local`、角色为 `member`、状态为 `pending` 的成员管理待通过注册申请测试用户", "db.user", "upsert", { emailFrom: "data.approveUser.email", passwordFrom: "data.approveUser.password", nameFrom: "data.approveUser.name", roleFrom: "data.approveUser.role", status: "pending", identityIdFrom: "runtime.approveIdentity.id", saveAs: "approveUser" }),
      step("Setup-6", "api", "ory.reject_identity.upsert", "准备邮箱为 `orf-system-members-review-reject-e2e@orf.local`、使用固定测试密码的成员管理待拒绝注册申请测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.rejectUser.email", passwordFrom: "data.rejectUser.password", nameFrom: "data.rejectUser.name", saveAs: "rejectIdentity" }),
      step("Setup-7", "prisma", "db.reject_user.upsert", "准备姓名为 \"ORF Members Review Reject E2E\"、邮箱为 `orf-system-members-review-reject-e2e@orf.local`、角色为 `member`、状态为 `pending` 的成员管理待拒绝注册申请测试用户", "db.user", "upsert", { emailFrom: "data.rejectUser.email", passwordFrom: "data.rejectUser.password", nameFrom: "data.rejectUser.name", roleFrom: "data.rejectUser.role", status: "pending", identityIdFrom: "runtime.rejectIdentity.id", saveAs: "rejectUser" }),
      step("Setup-8", "api", "ory.cancel_identity.upsert", "准备邮箱为 `orf-system-members-review-cancel-e2e@orf.local`、使用固定测试密码的成员管理取消拒绝注册申请测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.cancelUser.email", passwordFrom: "data.cancelUser.password", nameFrom: "data.cancelUser.name", saveAs: "cancelIdentity" }),
      step("Setup-9", "prisma", "db.cancel_user.upsert", "准备姓名为 \"ORF Members Review Cancel E2E\"、邮箱为 `orf-system-members-review-cancel-e2e@orf.local`、角色为 `member`、状态为 `pending` 的成员管理取消拒绝注册申请测试用户", "db.user", "upsert", { emailFrom: "data.cancelUser.email", passwordFrom: "data.cancelUser.password", nameFrom: "data.cancelUser.name", roleFrom: "data.cancelUser.role", status: "pending", identityIdFrom: "runtime.cancelIdentity.id", saveAs: "cancelUser" }),
      step("Setup-10", "api", "ory.admin_sessions.revoke", "撤销邮箱为 `orf-system-members-review-admin-e2e@orf.local` 的成员管理注册申请审核管理员测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.admin.email" }),
      step("Setup-11", "api", "ory.approve_sessions.revoke", "撤销邮箱为 `orf-system-members-review-approve-e2e@orf.local` 的成员管理待通过注册申请测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.approveUser.email" }),
      step("Setup-12", "api", "ory.reject_sessions.revoke", "撤销邮箱为 `orf-system-members-review-reject-e2e@orf.local` 的成员管理待拒绝注册申请测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.rejectUser.email" }),
      step("Setup-13", "api", "ory.cancel_sessions.revoke", "撤销邮箱为 `orf-system-members-review-cancel-e2e@orf.local` 的成员管理取消拒绝注册申请测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.cancelUser.email" }),
      step("Setup-14", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Setup-15", "playwright", "page.goto.auth", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Setup-16", "playwright", "fill.admin_email", "在邮箱输入框输入 `orf-system-members-review-admin-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.admin.email" }),
      step("Setup-17", "playwright", "fill.admin_password", "在密码输入框输入成员管理注册申请审核管理员测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.admin.password" }),
      step("Setup-18", "playwright", "click.sign_in", "点击 \"Sign In\" 登录操作", "page.login_form", "submit", { saveAs: "adminLoginResponse" }),
      step("Setup-19", "api", "session.admin_authenticated", "当前会话 应为 邮箱为 `orf-system-members-review-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
      step("Setup-20", "playwright", "page.goto.members", "打开 成员管理页面", "page", "goto", { pathFrom: "data.membersPath" }),
    ],
  },
  S0: {
    description: "管理员已登录并位于成员管理页面，三个注册申请均处于待审核状态",
    assertions: [
      step("S0-1", "api", "session.admin_authenticated", "当前会话 应为 邮箱为 `orf-system-members-review-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
      step("S0-2", "playwright", "url.members", "当前页面 应为 成员管理页面", "page.url", "match", { pattern: "/system/members$" }),
      step("S0-3", "playwright", "members.list.approve.visible", "成员管理页面的用户列表 应显示 待通过注册申请测试用户", "page.members_list", "contains_user", { emailFrom: "data.approveUser.email", nameFrom: "data.approveUser.name" }),
      step("S0-4", "playwright", "members.list.reject.visible", "成员管理页面的用户列表 应显示 待拒绝注册申请测试用户", "page.members_list", "contains_user", { emailFrom: "data.rejectUser.email", nameFrom: "data.rejectUser.name" }),
      step("S0-5", "playwright", "members.list.cancel.visible", "成员管理页面的用户列表 应显示 取消拒绝注册申请测试用户", "page.members_list", "contains_user", { emailFrom: "data.cancelUser.email", nameFrom: "data.cancelUser.name" }),
      step("S0-6", "playwright", "approve.status.pending", "待通过注册申请测试用户列表行的状态 应显示为 `待审核`", "page.member_row_status", "text", { emailFrom: "data.approveUser.email", text: "待审核" }),
      step("S0-7", "playwright", "reject.status.pending", "待拒绝注册申请测试用户列表行的状态 应显示为 `待审核`", "page.member_row_status", "text", { emailFrom: "data.rejectUser.email", text: "待审核" }),
      step("S0-8", "playwright", "cancel.status.pending", "取消拒绝注册申请测试用户列表行的状态 应显示为 `待审核`", "page.member_row_status", "text", { emailFrom: "data.cancelUser.email", text: "待审核" }),
      step("S0-9", "playwright", "approve.pass.visible", "待通过注册申请测试用户列表行的 \"通过\" 操作 应可见", "page.member_row_action", "visible", { emailFrom: "data.approveUser.email", action: "通过" }),
      step("S0-10", "playwright", "approve.pass.enabled", "待通过注册申请测试用户列表行的 \"通过\" 操作 应可点击", "page.member_row_action", "enabled", { emailFrom: "data.approveUser.email", action: "通过" }),
      step("S0-11", "playwright", "reject.reject.visible", "待拒绝注册申请测试用户列表行的 \"拒绝\" 操作 应可见", "page.member_row_action", "visible", { emailFrom: "data.rejectUser.email", action: "拒绝" }),
      step("S0-12", "playwright", "reject.reject.enabled", "待拒绝注册申请测试用户列表行的 \"拒绝\" 操作 应可点击", "page.member_row_action", "enabled", { emailFrom: "data.rejectUser.email", action: "拒绝" }),
      step("S0-13", "playwright", "cancel.reject.visible", "取消拒绝注册申请测试用户列表行的 \"拒绝\" 操作 应可见", "page.member_row_action", "visible", { emailFrom: "data.cancelUser.email", action: "拒绝" }),
      step("S0-14", "playwright", "cancel.reject.enabled", "取消拒绝注册申请测试用户列表行的 \"拒绝\" 操作 应可点击", "page.member_row_action", "enabled", { emailFrom: "data.cancelUser.email", action: "拒绝" }),
      step("S0-15", "prisma", "db.approve_user.pending", "邮箱为 `orf-system-members-review-approve-e2e@orf.local` 的成员管理待通过注册申请测试用户状态 应为 `pending`", "db.user", "matches", { emailFrom: "data.approveUser.email", roleFrom: "data.approveUser.role", status: "pending" }),
      step("S0-16", "prisma", "db.reject_user.pending", "邮箱为 `orf-system-members-review-reject-e2e@orf.local` 的成员管理待拒绝注册申请测试用户状态 应为 `pending`", "db.user", "matches", { emailFrom: "data.rejectUser.email", roleFrom: "data.rejectUser.role", status: "pending" }),
      step("S0-17", "prisma", "db.cancel_user.pending", "邮箱为 `orf-system-members-review-cancel-e2e@orf.local` 的成员管理取消拒绝注册申请测试用户状态 应为 `pending`", "db.user", "matches", { emailFrom: "data.cancelUser.email", roleFrom: "data.cancelUser.role", status: "pending" }),
    ],
  },
  Action: {
    description: "取消拒绝一个注册申请，确认拒绝一个注册申请，并通过一个注册申请",
    steps: [
      step("Action-1", "playwright", "cancel.reject.click", "点击 取消拒绝注册申请测试用户列表行的 \"拒绝\" 操作", "page.member_row_action", "click_confirm", { emailFrom: "data.cancelUser.email", action: "拒绝", decision: "dismiss", saveAs: "cancelRejectConfirm" }),
      step("Action-2", "playwright", "cancel.reject.confirm.observe", "查看 拒绝注册申请确认弹窗", "page.confirm_snapshot", "observe", { snapshotFrom: "runtime.cancelRejectConfirm" }),
      step("Action-3", "playwright", "cancel.reject.confirm.cancel", "点击 拒绝注册申请确认弹窗的取消操作", "page.confirm_snapshot", "dismissed", { snapshotFrom: "runtime.cancelRejectConfirm" }),
      step("Action-4", "playwright", "reject.reject.click", "点击 待拒绝注册申请测试用户列表行的 \"拒绝\" 操作", "page.member_row_action", "click_confirm", { emailFrom: "data.rejectUser.email", action: "拒绝", decision: "accept", saveAs: "rejectConfirm" }),
      step("Action-5", "playwright", "reject.reject.confirm.observe", "查看 拒绝注册申请确认弹窗", "page.confirm_snapshot", "observe", { snapshotFrom: "runtime.rejectConfirm" }),
      step("Action-6", "playwright", "reject.reject.confirm.accept", "点击 拒绝注册申请确认弹窗的确认操作", "page.confirm_snapshot", "accepted", { snapshotFrom: "runtime.rejectConfirm", waitEmailFrom: "data.rejectUser.email", waitStatus: "已拒绝" }),
      step("Action-7", "playwright", "approve.pass.click", "点击 待通过注册申请测试用户列表行的 \"通过\" 操作", "page.member_row_action", "click", { emailFrom: "data.approveUser.email", action: "通过", waitEmailFrom: "data.approveUser.email", waitStatus: "启用" }),
    ],
  },
  S1: {
    description: "取消拒绝保持待审核，确认拒绝更新为已拒绝，通过后更新为启用",
    assertions: [
      step("S1-1", "playwright", "cancel.reject.confirm.title", "拒绝注册申请确认弹窗标题 应显示 拒绝注册申请确认信息", "page.confirm_snapshot", "message_matches", { snapshotFrom: "runtime.cancelRejectConfirm", pattern: "拒绝" }),
      step("S1-2", "playwright", "cancel.reject.confirm.user", "拒绝注册申请确认弹窗 应显示 取消拒绝注册申请测试用户", "page.confirm_snapshot", "contains", { snapshotFrom: "runtime.cancelRejectConfirm", textFrom: "data.cancelUser.name" }),
      step("S1-3", "playwright", "cancel.reject.confirm.hidden", "点击取消后，拒绝注册申请确认弹窗 应不可见", "page.confirm_snapshot", "dismissed", { snapshotFrom: "runtime.cancelRejectConfirm" }),
      step("S1-4", "playwright", "members.list.cancel.visible.after_cancel", "点击取消后，成员管理页面的用户列表 应显示 取消拒绝注册申请测试用户", "page.members_list", "contains_user", { emailFrom: "data.cancelUser.email", nameFrom: "data.cancelUser.name" }),
      step("S1-5", "playwright", "cancel.status.pending.after_cancel", "点击取消后，取消拒绝注册申请测试用户列表行的状态 应显示为 `待审核`", "page.member_row_status", "text", { emailFrom: "data.cancelUser.email", text: "待审核" }),
      step("S1-6", "prisma", "db.cancel_user.still_pending", "点击取消后，邮箱为 `orf-system-members-review-cancel-e2e@orf.local` 的成员管理取消拒绝注册申请测试用户状态 应仍为 `pending`", "db.user", "matches", { emailFrom: "data.cancelUser.email", roleFrom: "data.cancelUser.role", status: "pending" }),
      step("S1-7", "playwright", "reject.confirm.user", "拒绝注册申请确认弹窗 应显示 待拒绝注册申请测试用户", "page.confirm_snapshot", "contains", { snapshotFrom: "runtime.rejectConfirm", textFrom: "data.rejectUser.name" }),
      step("S1-8", "playwright", "reject.confirm.hidden.after_accept", "确认拒绝后，拒绝注册申请确认弹窗 应不可见", "page.confirm_snapshot", "accepted", { snapshotFrom: "runtime.rejectConfirm", waitEmailFrom: "data.rejectUser.email", waitStatus: "已拒绝" }),
      step("S1-9", "playwright", "members.list.reject.visible.after_reject", "确认拒绝后，成员管理页面的用户列表 应显示 待拒绝注册申请测试用户", "page.members_list", "contains_user", { emailFrom: "data.rejectUser.email", nameFrom: "data.rejectUser.name" }),
      step("S1-10", "playwright", "reject.status.rejected", "确认拒绝后，待拒绝注册申请测试用户列表行的状态 应显示为 `已拒绝`", "page.member_row_status", "text", { emailFrom: "data.rejectUser.email", text: "已拒绝" }),
      step("S1-11", "playwright", "reject.pass.hidden", "确认拒绝后，待拒绝注册申请测试用户列表行的 \"通过\" 操作 应不可见", "page.member_row_action", "hidden", { emailFrom: "data.rejectUser.email", action: "通过" }),
      step("S1-12", "playwright", "reject.reject.hidden", "确认拒绝后，待拒绝注册申请测试用户列表行的 \"拒绝\" 操作 应不可见", "page.member_row_action", "hidden", { emailFrom: "data.rejectUser.email", action: "拒绝" }),
      step("S1-13", "prisma", "db.reject_user.rejected", "确认拒绝后，邮箱为 `orf-system-members-review-reject-e2e@orf.local` 的成员管理待拒绝注册申请测试用户状态 应为 `rejected`", "db.user", "matches", { emailFrom: "data.rejectUser.email", roleFrom: "data.rejectUser.role", status: "rejected" }),
      step("S1-14", "playwright", "members.list.approve.visible.after_approve", "点击通过后，成员管理页面的用户列表 应显示 待通过注册申请测试用户", "page.members_list", "contains_user", { emailFrom: "data.approveUser.email", nameFrom: "data.approveUser.name" }),
      step("S1-15", "playwright", "approve.status.active", "点击通过后，待通过注册申请测试用户列表行的状态 应显示为 `启用`", "page.member_row_status", "text", { emailFrom: "data.approveUser.email", text: "启用" }),
      step("S1-16", "playwright", "approve.pass.hidden", "点击通过后，待通过注册申请测试用户列表行的 \"通过\" 操作 应不可见", "page.member_row_action", "hidden", { emailFrom: "data.approveUser.email", action: "通过" }),
      step("S1-17", "playwright", "approve.reject.hidden", "点击通过后，待通过注册申请测试用户列表行的 \"拒绝\" 操作 应不可见", "page.member_row_action", "hidden", { emailFrom: "data.approveUser.email", action: "拒绝" }),
      step("S1-18", "playwright", "approve.disable.visible", "点击通过后，待通过注册申请测试用户列表行的 \"停用用户\" 操作 应可见", "page.member_row_action", "visible", { emailFrom: "data.approveUser.email", action: "停用用户" }),
      step("S1-19", "prisma", "db.approve_user.active", "点击通过后，邮箱为 `orf-system-members-review-approve-e2e@orf.local` 的成员管理待通过注册申请测试用户状态 应为 `active`", "db.user", "matches", { emailFrom: "data.approveUser.email", roleFrom: "data.approveUser.role", status: "active" }),
      step("S1-20", "api", "session.admin_authenticated.after_review", "当前会话 应仍为 邮箱为 `orf-system-members-review-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
    ],
  },
  Clean: {
    description: "删除注册申请审核相关测试数据并恢复未登录基准状态",
    steps: [
      step("Clean-1", "api", "auth.logout", "注销当前登录会话", "auth", "logout"),
      step("Clean-2", "playwright", "page.runtime.stop", "离开当前 ORF 前端页面", "page.runtime", "stop"),
      step("Clean-3", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Clean-4", "api", "ory.admin_sessions.revoke", "撤销邮箱为 `orf-system-members-review-admin-e2e@orf.local` 的成员管理注册申请审核管理员测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-5", "api", "ory.approve_sessions.revoke", "撤销邮箱为 `orf-system-members-review-approve-e2e@orf.local` 的成员管理待通过注册申请测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.approveUser.email" }),
      step("Clean-6", "api", "ory.reject_sessions.revoke", "撤销邮箱为 `orf-system-members-review-reject-e2e@orf.local` 的成员管理待拒绝注册申请测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.rejectUser.email" }),
      step("Clean-7", "api", "ory.cancel_sessions.revoke", "撤销邮箱为 `orf-system-members-review-cancel-e2e@orf.local` 的成员管理取消拒绝注册申请测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.cancelUser.email" }),
      step("Clean-8", "api", "ory.admin_identity.delete", "删除邮箱为 `orf-system-members-review-admin-e2e@orf.local` 的成员管理注册申请审核管理员测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-9", "api", "ory.approve_identity.delete", "删除邮箱为 `orf-system-members-review-approve-e2e@orf.local` 的成员管理待通过注册申请测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.approveUser.email" }),
      step("Clean-10", "api", "ory.reject_identity.delete", "删除邮箱为 `orf-system-members-review-reject-e2e@orf.local` 的成员管理待拒绝注册申请测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.rejectUser.email" }),
      step("Clean-11", "api", "ory.cancel_identity.delete", "删除邮箱为 `orf-system-members-review-cancel-e2e@orf.local` 的成员管理取消拒绝注册申请测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.cancelUser.email" }),
      step("Clean-12", "api", "admin.preferences.default_landing_path.reset", "恢复邮箱为 `orf-system-members-review-admin-e2e@orf.local` 的默认进入页面为 系统默认", "user.preferences", "reset_default_landing_path_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-13", "prisma", "db.admin_user.memberships.delete", "删除邮箱为 `orf-system-members-review-admin-e2e@orf.local` 的成员管理注册申请审核管理员测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.admin.email" }),
      step("Clean-14", "prisma", "db.approve_user.memberships.delete", "删除邮箱为 `orf-system-members-review-approve-e2e@orf.local` 的成员管理待通过注册申请测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.approveUser.email" }),
      step("Clean-15", "prisma", "db.reject_user.memberships.delete", "删除邮箱为 `orf-system-members-review-reject-e2e@orf.local` 的成员管理待拒绝注册申请测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.rejectUser.email" }),
      step("Clean-16", "prisma", "db.cancel_user.memberships.delete", "删除邮箱为 `orf-system-members-review-cancel-e2e@orf.local` 的成员管理取消拒绝注册申请测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.cancelUser.email" }),
      step("Clean-17", "prisma", "db.admin_user.delete", "删除邮箱为 `orf-system-members-review-admin-e2e@orf.local` 的成员管理注册申请审核管理员测试用户", "db.user", "delete", { emailFrom: "data.admin.email" }),
      step("Clean-18", "prisma", "db.approve_user.delete", "删除邮箱为 `orf-system-members-review-approve-e2e@orf.local` 的成员管理待通过注册申请测试用户", "db.user", "delete", { emailFrom: "data.approveUser.email" }),
      step("Clean-19", "prisma", "db.reject_user.delete", "删除邮箱为 `orf-system-members-review-reject-e2e@orf.local` 的成员管理待拒绝注册申请测试用户", "db.user", "delete", { emailFrom: "data.rejectUser.email" }),
      step("Clean-20", "prisma", "db.cancel_user.delete", "删除邮箱为 `orf-system-members-review-cancel-e2e@orf.local` 的成员管理取消拒绝注册申请测试用户", "db.user", "delete", { emailFrom: "data.cancelUser.email" }),
      step("Clean-21", "api", "ory.admin_identity.absent", "邮箱为 `orf-system-members-review-admin-e2e@orf.local` 的成员管理注册申请审核管理员测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.admin.email" }),
      step("Clean-22", "api", "ory.approve_identity.absent", "邮箱为 `orf-system-members-review-approve-e2e@orf.local` 的成员管理待通过注册申请测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.approveUser.email" }),
      step("Clean-23", "api", "ory.reject_identity.absent", "邮箱为 `orf-system-members-review-reject-e2e@orf.local` 的成员管理待拒绝注册申请测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.rejectUser.email" }),
      step("Clean-24", "api", "ory.cancel_identity.absent", "邮箱为 `orf-system-members-review-cancel-e2e@orf.local` 的成员管理取消拒绝注册申请测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.cancelUser.email" }),
      step("Clean-25", "prisma", "db.admin_user.absent", "邮箱为 `orf-system-members-review-admin-e2e@orf.local` 的成员管理注册申请审核管理员测试用户 应不存在", "db.user", "absent", { emailFrom: "data.admin.email" }),
      step("Clean-26", "prisma", "db.approve_user.absent", "邮箱为 `orf-system-members-review-approve-e2e@orf.local` 的成员管理待通过注册申请测试用户 应不存在", "db.user", "absent", { emailFrom: "data.approveUser.email" }),
      step("Clean-27", "prisma", "db.reject_user.absent", "邮箱为 `orf-system-members-review-reject-e2e@orf.local` 的成员管理待拒绝注册申请测试用户 应不存在", "db.user", "absent", { emailFrom: "data.rejectUser.email" }),
      step("Clean-28", "prisma", "db.cancel_user.absent", "邮箱为 `orf-system-members-review-cancel-e2e@orf.local` 的成员管理取消拒绝注册申请测试用户 应不存在", "db.user", "absent", { emailFrom: "data.cancelUser.email" }),
    ],
  },
} satisfies StateCaseSpec<SystemMembersReviewCaseData>;
