import { STATE_CASE_MODEL, type StateCaseSpec } from "../../_framework/types";
import type { ReviewApplicationCaseData } from "./_support/review-application.context";

export const reviewApplicationCase = {
  id: "bounties.review-application",
  title: "管理员可以审批成员挑战申请",
  model: STATE_CASE_MODEL,
  tags: ["bounties", "challenge-application", "review", "admin", "happy-path"],

  data: {
    email: "orf-admin-review-application-e2e@orf.local",
    password: "OrfAdminReviewApplicationE2E!2026",
    name: "ORF Admin Review Application E2E",
    role: "admin",
    approveApplicantEmail: "orf-member-review-approve-e2e@orf.local",
    approveApplicantPassword: "OrfMemberReviewApproveE2E!2026",
    approveApplicantName: "ORF Member Review Approve E2E",
    approveApplicantRole: "member",
    rejectApplicantEmail: "orf-member-review-reject-e2e@orf.local",
    rejectApplicantPassword: "OrfMemberReviewRejectE2E!2026",
    rejectApplicantName: "ORF Member Review Reject E2E",
    rejectApplicantRole: "member",
    objectiveId: "obj-testd-review-application",
    objectiveTitle: "E2E-REVIEW-APPLICATION: 成员申请审批",
    approveApplicationId: "challenge-application-testd-review-approve",
    rejectApplicationId: "challenge-application-testd-review-reject",
  },

  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      {
        source: { caseStepId: "B-1", method: "api" },
        id: "frontend.ready",
        title: "前端服务 应可用",
        object: "frontend.service",
        operator: "available",
      },
      {
        source: { caseStepId: "B-2", method: "api" },
        id: "backend.ready",
        title: "后端服务 应可用",
        object: "api.health",
        operator: "ok",
      },
      {
        source: { caseStepId: "B-3", method: "api" },
        id: "frontend.login_entry.accessible",
        title: "前端登录页入口 应可访问",
        object: "frontend.login_entry",
        operator: "accessible",
      },
      {
        source: { caseStepId: "B-4", method: "api" },
        id: "session.endpoint.accessible",
        title: "当前会话查询接口 应可访问",
        object: "auth.session",
        operator: "accessible",
      },
      {
        source: { caseStepId: "B-5", method: "prisma" },
        id: "db.ready",
        title: "ORF 数据库 应可连接",
        object: "db",
        operator: "ready",
      },
      {
        source: { caseStepId: "B-6", method: "prisma" },
        id: "db.schema.current",
        title: "ORF 数据库 schema 应为 当前测试版本",
        object: "db.schema",
        operator: "current",
      },
      {
        source: { caseStepId: "B-7", method: "api" },
        id: "ory.admin_public.ready",
        title: "Ory/Kratos Admin/Public API 应可访问",
        object: "ory.admin_public",
        operator: "ready",
      },
      {
        source: { caseStepId: "B-8", method: "api" },
        id: "session.unauthenticated",
        title: "当前会话 应为 未登录",
        object: "auth.session",
        operator: "unauthenticated",
      },
      {
        source: { caseStepId: "B-9", method: "playwright" },
        id: "cookie.absent",
        title: "当前浏览器 应不存在 Ory session cookie",
        object: "browser.cookie",
        operator: "absent",
      },
      {
        source: { caseStepId: "B-10", method: "playwright" },
        id: "storage.empty",
        title: "当前浏览器 storage 应不包含 登录态",
        object: "browser.auth_storage",
        operator: "empty",
      },
    ],
  },

  Setup: {
    description: "准备管理员、两个普通成员和本用例独占目标，创建两个待审批申请后登录管理员",
    steps: [
      {
        source: { caseStepId: "Setup-1", method: "prisma" },
        id: "db.objective.delete_residue",
        title: "删除可能残留的本用例审批目标及其派生数据",
        object: "db.objective",
        operator: "delete_by_title",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Setup-2", method: "api" },
        id: "ory.admin_identity.upsert",
        title: '准备邮箱为 "orf-admin-review-application-e2e@orf.local" 的管理员登录身份，并设置固定测试密码',
        object: "ory.identity",
        operator: "upsert_password",
        params: {
          emailFrom: "data.email",
          nameFrom: "data.name",
          passwordFrom: "data.password",
          saveAs: "adminIdentity",
        },
      },
      {
        source: { caseStepId: "Setup-3", method: "prisma" },
        id: "db.admin.upsert",
        title: '准备邮箱为 "orf-admin-review-application-e2e@orf.local"、角色为 admin、状态为 active 的管理员用户和默认团队成员关系',
        object: "db.user",
        operator: "upsert",
        params: {
          emailFrom: "data.email",
          nameFrom: "data.name",
          roleFrom: "data.role",
          status: "active",
          identityIdFrom: "runtime.adminIdentity.id",
          saveAs: "adminUser",
        },
      },
      {
        source: { caseStepId: "Setup-4", method: "api" },
        id: "ory.approve_identity.upsert",
        title: '准备邮箱为 "orf-member-review-approve-e2e@orf.local" 的审批通过申请人登录身份，并设置固定测试密码',
        object: "ory.identity",
        operator: "upsert_password",
        params: {
          emailFrom: "data.approveApplicantEmail",
          nameFrom: "data.approveApplicantName",
          passwordFrom: "data.approveApplicantPassword",
          saveAs: "approveApplicantIdentity",
        },
      },
      {
        source: { caseStepId: "Setup-5", method: "prisma" },
        id: "db.approve_member.upsert",
        title: '准备邮箱为 "orf-member-review-approve-e2e@orf.local"、角色为 member、状态为 active 的审批通过申请人用户和默认团队成员关系',
        object: "db.user",
        operator: "upsert",
        params: {
          emailFrom: "data.approveApplicantEmail",
          nameFrom: "data.approveApplicantName",
          roleFrom: "data.approveApplicantRole",
          status: "active",
          identityIdFrom: "runtime.approveApplicantIdentity.id",
          saveAs: "approveApplicantUser",
        },
      },
      {
        source: { caseStepId: "Setup-6", method: "api" },
        id: "ory.reject_identity.upsert",
        title: '准备邮箱为 "orf-member-review-reject-e2e@orf.local" 的审批拒绝申请人登录身份，并设置固定测试密码',
        object: "ory.identity",
        operator: "upsert_password",
        params: {
          emailFrom: "data.rejectApplicantEmail",
          nameFrom: "data.rejectApplicantName",
          passwordFrom: "data.rejectApplicantPassword",
          saveAs: "rejectApplicantIdentity",
        },
      },
      {
        source: { caseStepId: "Setup-7", method: "prisma" },
        id: "db.reject_member.upsert",
        title: '准备邮箱为 "orf-member-review-reject-e2e@orf.local"、角色为 member、状态为 active 的审批拒绝申请人用户和默认团队成员关系',
        object: "db.user",
        operator: "upsert",
        params: {
          emailFrom: "data.rejectApplicantEmail",
          nameFrom: "data.rejectApplicantName",
          roleFrom: "data.rejectApplicantRole",
          status: "active",
          identityIdFrom: "runtime.rejectApplicantIdentity.id",
          saveAs: "rejectApplicantUser",
        },
      },
      {
        source: { caseStepId: "Setup-8", method: "prisma" },
        id: "db.objective.upsert_reviewable",
        title: '创建标题为 "E2E-REVIEW-APPLICATION: 成员申请审批"、流转状态为 open、阶段为 resultClaiming 的本用例审批目标',
        object: "db.objective",
        operator: "upsert",
        params: {
          idFrom: "data.objectiveId",
          titleFrom: "data.objectiveTitle",
          teamIdFrom: "runtime.adminUser.teamId",
          stage: "resultClaiming",
          flowStatus: "open",
          status: "Draft",
          saveAs: "fixtureObjective",
        },
      },
      {
        source: { caseStepId: "Setup-9", method: "prisma" },
        id: "db.challenge_review.target_from_objective",
        title: "记录本用例审批目标的原始状态为 runtime.reviewTarget",
        object: "db.challenge_review",
        operator: "target_from_objective",
        params: {
          objectiveIdFrom: "runtime.fixtureObjective.id",
          objectiveTitleFrom: "runtime.fixtureObjective.title",
          saveAs: "reviewTarget",
        },
      },
      {
        source: { caseStepId: "Setup-10", method: "prisma" },
        id: "db.challenge_application.create_approve_pending",
        title: '创建 "ORF Member Review Approve E2E" 对本用例审批目标的 pending 挑战申请',
        object: "db.challenge_application",
        operator: "create_pending_application",
        params: {
          targetFrom: "runtime.reviewTarget",
          applicantFrom: "data.approveApplicantName",
          applicationIdFrom: "data.approveApplicationId",
        },
      },
      {
        source: { caseStepId: "Setup-11", method: "prisma" },
        id: "db.challenge_application.create_reject_pending",
        title: '创建 "ORF Member Review Reject E2E" 对本用例审批目标的 pending 挑战申请',
        object: "db.challenge_application",
        operator: "create_pending_application",
        params: {
          targetFrom: "runtime.reviewTarget",
          applicantFrom: "data.rejectApplicantName",
          applicationIdFrom: "data.rejectApplicationId",
        },
      },
      {
        source: { caseStepId: "Setup-12", method: "api" },
        id: "ory.admin_sessions.revoke",
        title: "撤销管理员登录身份可能残留的 Ory session",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Setup-13", method: "api" },
        id: "ory.approve_sessions.revoke",
        title: "撤销审批通过申请人登录身份可能残留的 Ory session",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.approveApplicantEmail" },
      },
      {
        source: { caseStepId: "Setup-14", method: "api" },
        id: "ory.reject_sessions.revoke",
        title: "撤销审批拒绝申请人登录身份可能残留的 Ory session",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.rejectApplicantEmail" },
      },
      {
        source: { caseStepId: "Setup-15", method: "playwright" },
        id: "browser.clear",
        title: "清空当前浏览器上下文的 cookies/localStorage/sessionStorage",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "Setup-16", method: "playwright" },
        id: "page.goto.auth",
        title: "打开 登录页",
        object: "page",
        operator: "goto",
        params: { path: "/auth" },
      },
      {
        source: { caseStepId: "Setup-17", method: "playwright" },
        id: "fill.email",
        title: "在邮箱输入框输入管理员测试邮箱",
        object: "page",
        operator: "fill",
        params: { label: "Email", valueFrom: "data.email" },
      },
      {
        source: { caseStepId: "Setup-18", method: "playwright" },
        id: "fill.password",
        title: "在密码输入框输入管理员测试密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.password" },
      },
      {
        source: { caseStepId: "Setup-19", method: "playwright" },
        id: "click.sign_in",
        title: '点击 "Sign In" 登录操作',
        object: "page",
        operator: "click",
        params: { role: "button", name: "Sign In" },
      },
      {
        source: { caseStepId: "Setup-20", method: "api" },
        id: "session.admin.authenticated",
        title: "当前会话 应为 管理员已登录",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      {
        source: { caseStepId: "Setup-21", method: "playwright" },
        id: "page.goto.tasks",
        title: "打开 挑战工作台",
        object: "page",
        operator: "goto",
        params: { path: "/tasks" },
      },
      {
        source: { caseStepId: "Setup-22", method: "playwright" },
        id: "scope.all",
        title: '切换到 "所有挑战" 视图',
        object: "page",
        operator: "click",
        params: { role: "button", name: "所有挑战" },
      },
    ],
  },

  S0: {
    description: "管理员位于挑战工作台，两个待审批申请可见且目标尚未包含两个申请人",
    assertions: [
      {
        source: { caseStepId: "S0-1", method: "api" },
        id: "session.admin.authenticated",
        title: '当前会话 应为 邮箱为 "orf-admin-review-application-e2e@orf.local"、角色为 admin、状态为 active 的已登录会话',
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      {
        source: { caseStepId: "S0-2", method: "playwright" },
        id: "url.tasks",
        title: "当前页面 应为 挑战工作台",
        object: "page.url",
        operator: "match",
        params: { pattern: "/tasks$" },
      },
      {
        source: { caseStepId: "S0-3", method: "playwright" },
        id: "review_target.visible",
        title: "本用例审批目标面板 应可见",
        object: "page.challenge_review_target",
        operator: "visible",
        params: { targetFrom: "runtime.reviewTarget" },
      },
      {
        source: { caseStepId: "S0-4", method: "playwright" },
        id: "approve_application.visible",
        title: '"ORF Member Review Approve E2E" 挑战申请的 "通过" 操作 应可见',
        object: "page.challenge_application",
        operator: "approve_visible",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.approveApplicantName" },
      },
      {
        source: { caseStepId: "S0-5", method: "playwright" },
        id: "reject_application.visible",
        title: '"ORF Member Review Reject E2E" 挑战申请的 "拒绝" 操作 应可见',
        object: "page.challenge_application",
        operator: "reject_visible",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.rejectApplicantName" },
      },
      {
        source: { caseStepId: "S0-6", method: "prisma" },
        id: "db.approve_application.pending",
        title: '"ORF Member Review Approve E2E" 对本用例审批目标的挑战申请状态 应为 pending',
        object: "db.challenge_application",
        operator: "status",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.approveApplicantName", status: "pending" },
      },
      {
        source: { caseStepId: "S0-7", method: "prisma" },
        id: "db.reject_application.pending",
        title: '"ORF Member Review Reject E2E" 对本用例审批目标的挑战申请状态 应为 pending',
        object: "db.challenge_application",
        operator: "status",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.rejectApplicantName", status: "pending" },
      },
      {
        source: { caseStepId: "S0-8", method: "prisma" },
        id: "db.approve_challenger.absent",
        title: '本用例审批目标的挑战者列表 应不包含 "ORF Member Review Approve E2E"',
        object: "db.objective_challengers",
        operator: "absent",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.approveApplicantName" },
      },
      {
        source: { caseStepId: "S0-9", method: "prisma" },
        id: "db.reject_challenger.absent",
        title: '本用例审批目标的挑战者列表 应不包含 "ORF Member Review Reject E2E"',
        object: "db.objective_challengers",
        operator: "absent",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.rejectApplicantName" },
      },
    ],
  },

  Action: {
    description: "管理员通过一个挑战申请，并拒绝另一个挑战申请",
    steps: [
      {
        source: { caseStepId: "Action-1", method: "api" },
        id: "capture.approve_response",
        title: "在点击通过前注册审批通过接口响应捕获",
        object: "api.challenge_review",
        operator: "capture_approve_response",
        params: { targetFrom: "runtime.reviewTarget", saveAs: "approveResponse" },
      },
      {
        source: { caseStepId: "Action-2", method: "playwright" },
        id: "click.approve_application",
        title: '点击 "ORF Member Review Approve E2E" 挑战申请的 "通过" 操作',
        object: "page.challenge_application",
        operator: "approve",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.approveApplicantName" },
      },
      {
        source: { caseStepId: "Action-3", method: "api" },
        id: "capture.reject_response",
        title: "在点击拒绝前注册审批拒绝接口响应捕获",
        object: "api.challenge_review",
        operator: "capture_reject_response",
        params: { targetFrom: "runtime.reviewTarget", saveAs: "rejectResponse" },
      },
      {
        source: { caseStepId: "Action-4", method: "playwright" },
        id: "click.reject_application",
        title: '点击 "ORF Member Review Reject E2E" 挑战申请的 "拒绝" 操作',
        object: "page.challenge_application",
        operator: "reject",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.rejectApplicantName" },
      },
    ],
  },

  S1: {
    description: "审批结果已经持久化，目标进入重估且管理员仍保持登录",
    assertions: [
      {
        source: { caseStepId: "S1-1", method: "api" },
        id: "approve_response.ok",
        title: "审批通过接口响应 应成功，且响应目标 ID 为本用例审批目标 ID",
        object: "api.challenge_review",
        operator: "response_ok",
        params: { responseFrom: "runtime.approveResponse", targetFrom: "runtime.reviewTarget" },
      },
      {
        source: { caseStepId: "S1-2", method: "api" },
        id: "reject_response.ok",
        title: "审批拒绝接口响应 应成功，且响应目标 ID 为本用例审批目标 ID",
        object: "api.challenge_review",
        operator: "response_ok",
        params: { responseFrom: "runtime.rejectResponse", targetFrom: "runtime.reviewTarget" },
      },
      {
        source: { caseStepId: "S1-3", method: "prisma" },
        id: "db.approve_application.approved",
        title: '"ORF Member Review Approve E2E" 对本用例审批目标的挑战申请状态 应变为 approved',
        object: "db.challenge_application",
        operator: "status",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.approveApplicantName", status: "approved" },
      },
      {
        source: { caseStepId: "S1-4", method: "prisma" },
        id: "db.approve_challenger.present",
        title: '本用例审批目标的挑战者列表 应包含 "ORF Member Review Approve E2E"',
        object: "db.objective_challengers",
        operator: "present",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.approveApplicantName" },
      },
      {
        source: { caseStepId: "S1-5", method: "prisma" },
        id: "db.reject_application.declined",
        title: '"ORF Member Review Reject E2E" 对本用例审批目标的挑战申请状态 应变为 declined',
        object: "db.challenge_application",
        operator: "status",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.rejectApplicantName", status: "declined" },
      },
      {
        source: { caseStepId: "S1-6", method: "prisma" },
        id: "db.reject_challenger.absent",
        title: '本用例审批目标的挑战者列表 应不包含 "ORF Member Review Reject E2E"',
        object: "db.objective_challengers",
        operator: "absent",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.rejectApplicantName" },
      },
      {
        source: { caseStepId: "S1-7", method: "prisma" },
        id: "db.objective.flow_reestimating",
        title: "本用例审批目标的 flowStatus 应变为 reestimating",
        object: "db.objective",
        operator: "flow_status",
        params: { targetFrom: "runtime.reviewTarget", status: "reestimating" },
      },
      {
        source: { caseStepId: "S1-8", method: "api" },
        id: "session.admin.still_authenticated",
        title: "当前会话 应保持 管理员已登录",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
    ],
  },

  Clean: {
    description: "删除本用例目标、三个独占账号并恢复未登录基准状态",
    steps: [
      {
        source: { caseStepId: "Clean-1", method: "prisma" },
        id: "db.objective.delete_by_title",
        title: "删除本用例审批目标及其派生数据",
        object: "db.objective",
        operator: "delete_by_title",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Clean-2", method: "api" },
        id: "auth.logout",
        title: "调用退出登录接口撤销当前登录会话",
        object: "auth",
        operator: "logout",
      },
      {
        source: { caseStepId: "Clean-3", method: "playwright" },
        id: "page.runtime.stop",
        title: "当前页面离开 ORF 前端应用",
        object: "page.runtime",
        operator: "stop",
      },
      {
        source: { caseStepId: "Clean-4", method: "playwright" },
        id: "browser.clear",
        title: "清空当前浏览器上下文的 cookies/localStorage/sessionStorage",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "Clean-5", method: "api" },
        id: "ory.admin_sessions.revoke",
        title: "撤销管理员登录身份的残留 Ory session",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-6", method: "api" },
        id: "ory.approve_sessions.revoke",
        title: "撤销审批通过申请人登录身份的残留 Ory session",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.approveApplicantEmail" },
      },
      {
        source: { caseStepId: "Clean-7", method: "api" },
        id: "ory.reject_sessions.revoke",
        title: "撤销审批拒绝申请人登录身份的残留 Ory session",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.rejectApplicantEmail" },
      },
      {
        source: { caseStepId: "Clean-8", method: "api" },
        id: "ory.admin_identity.delete",
        title: '删除邮箱为 "orf-admin-review-application-e2e@orf.local" 的管理员登录身份',
        object: "ory.identity",
        operator: "delete_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-9", method: "api" },
        id: "ory.approve_identity.delete",
        title: '删除邮箱为 "orf-member-review-approve-e2e@orf.local" 的审批通过申请人登录身份',
        object: "ory.identity",
        operator: "delete_by_email",
        params: { emailFrom: "data.approveApplicantEmail" },
      },
      {
        source: { caseStepId: "Clean-10", method: "api" },
        id: "ory.reject_identity.delete",
        title: '删除邮箱为 "orf-member-review-reject-e2e@orf.local" 的审批拒绝申请人登录身份',
        object: "ory.identity",
        operator: "delete_by_email",
        params: { emailFrom: "data.rejectApplicantEmail" },
      },
      {
        source: { caseStepId: "Clean-11", method: "prisma" },
        id: "db.admin.memberships.delete",
        title: "删除管理员用户的默认团队成员关系",
        object: "db.user",
        operator: "delete_memberships",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-12", method: "prisma" },
        id: "db.approve_member.memberships.delete",
        title: "删除审批通过申请人用户的默认团队成员关系",
        object: "db.user",
        operator: "delete_memberships",
        params: { emailFrom: "data.approveApplicantEmail" },
      },
      {
        source: { caseStepId: "Clean-13", method: "prisma" },
        id: "db.reject_member.memberships.delete",
        title: "删除审批拒绝申请人用户的默认团队成员关系",
        object: "db.user",
        operator: "delete_memberships",
        params: { emailFrom: "data.rejectApplicantEmail" },
      },
      {
        source: { caseStepId: "Clean-14", method: "prisma" },
        id: "db.admin.delete",
        title: '删除邮箱为 "orf-admin-review-application-e2e@orf.local" 的管理员用户',
        object: "db.user",
        operator: "delete",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-15", method: "prisma" },
        id: "db.approve_member.delete",
        title: '删除邮箱为 "orf-member-review-approve-e2e@orf.local" 的审批通过申请人用户',
        object: "db.user",
        operator: "delete",
        params: { emailFrom: "data.approveApplicantEmail" },
      },
      {
        source: { caseStepId: "Clean-16", method: "prisma" },
        id: "db.reject_member.delete",
        title: '删除邮箱为 "orf-member-review-reject-e2e@orf.local" 的审批拒绝申请人用户',
        object: "db.user",
        operator: "delete",
        params: { emailFrom: "data.rejectApplicantEmail" },
      },
      {
        source: { caseStepId: "Clean-17", method: "prisma" },
        id: "db.objective.absent",
        title: '应不存在 标题为 "E2E-REVIEW-APPLICATION: 成员申请审批" 的测试目标',
        object: "db.objective",
        operator: "absent",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Clean-18", method: "prisma" },
        id: "db.users.absent",
        title: "应不存在 本用例独占管理员、审批通过申请人和审批拒绝申请人用户",
        object: "db.user",
        operator: "absent",
        params: {
          emails: [
            "orf-admin-review-application-e2e@orf.local",
            "orf-member-review-approve-e2e@orf.local",
            "orf-member-review-reject-e2e@orf.local",
          ],
        },
      },
    ],
  },
} satisfies StateCaseSpec<ReviewApplicationCaseData>;
