import { STATE_CASE_MODEL, type StateCaseSpec } from "../../_framework/types";
import type { ReviewApplicationCaseData } from "./_support/review-application.context";

export const reviewApplicationCase = {
  id: "bounties.challenge-application.review.admin",
  title: "管理员可以审批成员挑战申请",
  model: STATE_CASE_MODEL,
  tags: ["bounties", "challenge-application", "review", "admin", "happy-path"],

  data: {
    email: "zrx831@gmail.com",
    password: "123123123",
    role: "admin",
    approveApplicantName: "ORF Member E2E",
    rejectApplicantName: "m2",
  },

  B: {
    description: "管理员、两个普通成员和可审批目标可用，浏览器未登录",
    assertions: [
      { id: "backend.ready", title: "后端服务可用", object: "api.health", operator: "ok" },
      { id: "db.ready", title: "数据库可连接", object: "db", operator: "ready" },
      { id: "ory.ready", title: "Ory Admin API 可用", object: "ory.admin", operator: "ready" },
      {
        id: "ory.admin_identity.exists",
        title: "管理员 Ory 身份存在",
        object: "ory.identity",
        operator: "exists",
        params: { emailFrom: "data.email" },
      },
      { id: "db.admin.active", title: "预置管理员账号可用", object: "db.admin", operator: "active", params: { emailFrom: "data.email" } },
      {
        id: "db.member.approve_applicant.active",
        title: "审批通过申请人账号可用",
        object: "db.member",
        operator: "active",
        params: { nameFrom: "data.approveApplicantName" },
      },
      {
        id: "db.member.reject_applicant.active",
        title: "审批拒绝申请人账号可用",
        object: "db.member",
        operator: "active",
        params: { nameFrom: "data.rejectApplicantName" },
      },
      { id: "db.challenge_review.target_available", title: "存在可准备待审批申请的目标", object: "db.challenge_review", operator: "target_available" },
      { id: "session.unauthenticated", title: "后端 session 未登录", object: "auth.session", operator: "unauthenticated" },
      { id: "cookie.absent", title: "浏览器不存在登录 cookie", object: "browser.cookie", operator: "absent" },
      { id: "storage.empty", title: "浏览器 storage 不含登录态", object: "browser.auth_storage", operator: "empty" },
    ],
  },

  Setup: {
    description: "登录管理员，准备两个待审批挑战申请并进入所有挑战视图",
    steps: [
      { id: "ory.sessions.revoke", title: "清理管理员已有 Ory session", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.email" } },
      { id: "browser.clear", title: "清理浏览器状态", object: "browser", operator: "clear_state" },
      { id: "page.goto.auth", title: "打开登录页", object: "page", operator: "goto", params: { path: "/auth" } },
      { id: "fill.email", title: "输入管理员邮箱", object: "page", operator: "fill", params: { label: "Email", valueFrom: "data.email" } },
      {
        id: "fill.password",
        title: "输入管理员密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.password" },
      },
      { id: "click.sign_in", title: "管理员登录", object: "page", operator: "click", params: { role: "button", name: "Sign In" } },
      {
        id: "session.admin.authenticated",
        title: "等待管理员 session 已登录",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      {
        id: "db.challenge_review.select_target",
        title: "选择可审批挑战申请的目标",
        object: "db.challenge_review",
        operator: "select_target",
        params: { saveAs: "reviewTarget" },
      },
      {
        id: "db.challenge_review.record_original_state",
        title: "记录目标原始状态",
        object: "db.challenge_review",
        operator: "original_state_recorded",
        params: { targetFrom: "runtime.reviewTarget" },
      },
      {
        id: "db.challenge_application.create_approve_pending",
        title: "准备审批通过申请人的待处理挑战申请",
        object: "db.challenge_application",
        operator: "create_pending_application",
        params: {
          targetFrom: "runtime.reviewTarget",
          applicantFrom: "data.approveApplicantName",
          applicationIdFrom: "runtime.reviewTarget.approveApplicationId",
        },
      },
      {
        id: "db.challenge_application.create_reject_pending",
        title: "准备审批拒绝申请人的待处理挑战申请",
        object: "db.challenge_application",
        operator: "create_pending_application",
        params: {
          targetFrom: "runtime.reviewTarget",
          applicantFrom: "data.rejectApplicantName",
          applicationIdFrom: "runtime.reviewTarget.rejectApplicationId",
        },
      },
      { id: "page.goto.tasks", title: "打开挑战工作台", object: "page", operator: "goto", params: { path: "/tasks" } },
      { id: "scope.all", title: "切换到所有挑战视图", object: "page", operator: "click", params: { role: "button", name: "所有挑战" } },
    ],
  },

  S0: {
    description: "管理员位于挑战工作台，两个待审批申请可见且目标尚未包含两个申请人",
    assertions: [
      {
        id: "session.admin.authenticated",
        title: "后端 session 已登录",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      { id: "url.tasks", title: "当前页面是挑战工作台", object: "page.url", operator: "match", params: { pattern: "/tasks$" } },
      {
        id: "review_target.visible",
        title: "目标面板可见",
        object: "page.challenge_review_target",
        operator: "visible",
        params: { targetFrom: "runtime.reviewTarget" },
      },
      {
        id: "approve_application.visible",
        title: "审批通过申请操作可见",
        object: "page.challenge_application",
        operator: "approve_visible",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.approveApplicantName" },
      },
      {
        id: "reject_application.visible",
        title: "审批拒绝申请操作可见",
        object: "page.challenge_application",
        operator: "reject_visible",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.rejectApplicantName" },
      },
      {
        id: "db.approve_application.pending",
        title: "审批通过申请处于待处理",
        object: "db.challenge_application",
        operator: "status",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.approveApplicantName", status: "pending" },
      },
      {
        id: "db.reject_application.pending",
        title: "审批拒绝申请处于待处理",
        object: "db.challenge_application",
        operator: "status",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.rejectApplicantName", status: "pending" },
      },
      {
        id: "db.approve_challenger.absent",
        title: "审批通过申请人尚未成为挑战者",
        object: "db.objective_challengers",
        operator: "absent",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.approveApplicantName" },
      },
      {
        id: "db.reject_challenger.absent",
        title: "审批拒绝申请人尚未成为挑战者",
        object: "db.objective_challengers",
        operator: "absent",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.rejectApplicantName" },
      },
    ],
  },

  Action: {
    description: "管理员通过一个挑战申请，并拒绝另一个挑战申请",
    steps: [
      {
        id: "capture.approve_response",
        title: "监听审批通过请求",
        object: "api.challenge_review",
        operator: "capture_approve_response",
        params: { targetFrom: "runtime.reviewTarget", saveAs: "approveResponse" },
      },
      {
        id: "click.approve_application",
        title: "点击通过挑战申请",
        object: "page.challenge_application",
        operator: "approve",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.approveApplicantName" },
      },
      {
        id: "await.approve_response",
        title: "等待审批通过请求完成",
        object: "api.challenge_review",
        operator: "await_response",
        params: { responseFrom: "runtime.approveResponse" },
      },
      {
        id: "capture.reject_response",
        title: "监听审批拒绝请求",
        object: "api.challenge_review",
        operator: "capture_reject_response",
        params: { targetFrom: "runtime.reviewTarget", saveAs: "rejectResponse" },
      },
      {
        id: "click.reject_application",
        title: "点击拒绝挑战申请",
        object: "page.challenge_application",
        operator: "reject",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.rejectApplicantName" },
      },
    ],
  },

  S1: {
    description: "审批结果已经持久化，目标进入重估且管理员仍保持登录",
    assertions: [
      {
        id: "approve_response.ok",
        title: "审批通过接口响应成功",
        object: "api.challenge_review",
        operator: "response_ok",
        params: { responseFrom: "runtime.approveResponse", targetFrom: "runtime.reviewTarget" },
      },
      {
        id: "reject_response.ok",
        title: "审批拒绝接口响应成功",
        object: "api.challenge_review",
        operator: "response_ok",
        params: { responseFrom: "runtime.rejectResponse", targetFrom: "runtime.reviewTarget" },
      },
      {
        id: "db.approve_application.approved",
        title: "通过申请状态已变为 approved",
        object: "db.challenge_application",
        operator: "status",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.approveApplicantName", status: "approved" },
      },
      {
        id: "db.approve_challenger.present",
        title: "通过申请人已成为挑战者",
        object: "db.objective_challengers",
        operator: "present",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.approveApplicantName" },
      },
      {
        id: "db.reject_application.declined",
        title: "拒绝申请状态已变为 declined",
        object: "db.challenge_application",
        operator: "status",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.rejectApplicantName", status: "declined" },
      },
      {
        id: "db.reject_challenger.absent",
        title: "拒绝申请人未成为挑战者",
        object: "db.objective_challengers",
        operator: "absent",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.rejectApplicantName" },
      },
      {
        id: "db.objective.flow_reestimating",
        title: "目标进入重估状态",
        object: "db.objective",
        operator: "flow_status",
        params: { targetFrom: "runtime.reviewTarget", status: "reestimating" },
      },
      {
        id: "session.admin.still_authenticated",
        title: "管理员仍保持登录",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
    ],
  },

  Clean: {
    description: "恢复目标原始状态并退出登录",
    steps: [
      {
        id: "db.challenge_review.restore",
        title: "恢复目标原始状态",
        object: "db.challenge_review",
        operator: "restore_target",
        params: { targetFrom: "runtime.reviewTarget" },
      },
      { id: "auth.logout", title: "退出当前登录态", object: "auth", operator: "logout" },
      { id: "browser.clear", title: "清理浏览器状态", object: "browser", operator: "clear_state" },
      {
        id: "ory.admin_identity.exists",
        title: "管理员 Ory 身份仍然存在",
        object: "ory.identity",
        operator: "exists",
        params: { emailFrom: "data.email" },
      },
      { id: "db.admin.active", title: "预置管理员账号仍然可用", object: "db.admin", operator: "active", params: { emailFrom: "data.email" } },
      {
        id: "db.member.approve_applicant.active",
        title: "审批通过申请人账号仍然可用",
        object: "db.member",
        operator: "active",
        params: { nameFrom: "data.approveApplicantName" },
      },
      {
        id: "db.member.reject_applicant.active",
        title: "审批拒绝申请人账号仍然可用",
        object: "db.member",
        operator: "active",
        params: { nameFrom: "data.rejectApplicantName" },
      },
    ],
  },
} satisfies StateCaseSpec<ReviewApplicationCaseData>;
