import { STATE_CASE_MODEL, type StateCaseSpec } from "../../_framework/types";
import type { ReviewApplicationCaseData } from "./_support/review-application.context";

export const reviewApplicationCase = {
  id: "bounties.review-application",
  title: "管理员可以审批成员挑战申请",
  model: STATE_CASE_MODEL,
  tags: ["bounties", "challenge-application", "review", "admin", "happy-path"],

  data: {
    email: "orf-admin-review-application-e2e@orf.local",
    password: "OrfAdminReviewApplicationE2E!2026",
    name: "ORF Admin Review Application E2E",
    role: "admin",
    approveApplicantEmail: "orf-member-review-approve-e2e@orf.local",
    approveApplicantPassword: "OrfMemberReviewApproveE2E!2026",
    approveApplicantName: "ORF Member Review Approve E2E",
    approveApplicantRole: "member",
    rejectApplicantEmail: "orf-member-review-reject-e2e@orf.local",
    rejectApplicantPassword: "OrfMemberReviewRejectE2E!2026",
    rejectApplicantName: "ORF Member Review Reject E2E",
    rejectApplicantRole: "member",
    objectiveId: "obj-testd-review-application",
    objectiveTitle: "E2E-REVIEW-APPLICATION: 成员申请审批",
  },

  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      { source: { caseStepId: "B-1", method: "api" }, id: "frontend.ready", title: "前端服务 应可用", object: "frontend.service", operator: "available" },
      { source: { caseStepId: "B-2", method: "api" }, id: "backend.ready", title: "后端服务 应可用", object: "api.health", operator: "ok" },
      { source: { caseStepId: "B-3", method: "api" }, id: "frontend.login_entry.accessible", title: "前端登录页入口 应可访问", object: "frontend.login_entry", operator: "accessible" },
      { source: { caseStepId: "B-4", method: "api" }, id: "session.endpoint.accessible", title: "当前会话查询能力 应可用", object: "auth.session", operator: "accessible" },
      { source: { caseStepId: "B-5", method: "prisma" }, id: "db.ready", title: "ORF 数据库 应可连接", object: "db", operator: "ready" },
      { source: { caseStepId: "B-6", method: "prisma" }, id: "db.schema.current", title: "ORF 数据库 schema 应为 当前测试版本", object: "db.schema", operator: "current" },
      { source: { caseStepId: "B-7", method: "api" }, id: "ory.admin_public.ready", title: "Ory/Kratos 认证服务的管理和公共访问能力 应可用", object: "ory.admin_public", operator: "ready" },
      { source: { caseStepId: "B-8", method: "api" }, id: "session.unauthenticated", title: "当前会话 应为 未登录", object: "auth.session", operator: "unauthenticated" },
      { source: { caseStepId: "B-9", method: "playwright" }, id: "cookie.absent", title: "当前浏览器 应不存在 Ory 登录会话 cookie", object: "browser.cookie", operator: "absent" },
      { source: { caseStepId: "B-10", method: "playwright" }, id: "storage.empty", title: "当前浏览器 应不保留本地登录态", object: "browser.auth_storage", operator: "empty" },
    ],
  },

  Setup: {
    description: "准备管理员、两个普通成员和本用例独占的可申请目标",
    steps: [
      {
        source: { caseStepId: "Setup-1", method: "prisma" },
        id: "db.objective.delete_residue",
        title: "删除可能残留的本用例审批目标及其派生数据",
        object: "db.objective",
        operator: "delete_by_title",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Setup-2", method: "api" },
        id: "ory.admin_identity.upsert",
        title: "准备邮箱为 `orf-admin-review-application-e2e@orf.local`、使用固定测试密码的管理员登录身份",
        object: "ory.identity",
        operator: "upsert_password",
        params: { emailFrom: "data.email", nameFrom: "data.name", passwordFrom: "data.password", saveAs: "adminIdentity" },
      },
      {
        source: { caseStepId: "Setup-3", method: "prisma" },
        id: "db.admin.upsert",
        title: "准备邮箱为 `orf-admin-review-application-e2e@orf.local`、角色为 `admin`、状态为 `active` 的管理员用户和默认团队成员关系",
        object: "db.user",
        operator: "upsert",
        params: { emailFrom: "data.email", nameFrom: "data.name", roleFrom: "data.role", status: "active", identityIdFrom: "runtime.adminIdentity.id", saveAs: "adminUser" },
      },
      {
        source: { caseStepId: "Setup-4", method: "api" },
        id: "ory.approve_identity.upsert",
        title: "准备邮箱为 `orf-member-review-approve-e2e@orf.local`、使用固定测试密码的审批通过申请人登录身份",
        object: "ory.identity",
        operator: "upsert_password",
        params: { emailFrom: "data.approveApplicantEmail", nameFrom: "data.approveApplicantName", passwordFrom: "data.approveApplicantPassword", saveAs: "approveApplicantIdentity" },
      },
      {
        source: { caseStepId: "Setup-5", method: "prisma" },
        id: "db.approve_member.upsert",
        title: "准备邮箱为 `orf-member-review-approve-e2e@orf.local`、角色为 `member`、状态为 `active` 的审批通过申请人用户和默认团队成员关系",
        object: "db.user",
        operator: "upsert",
        params: {
          emailFrom: "data.approveApplicantEmail",
          nameFrom: "data.approveApplicantName",
          roleFrom: "data.approveApplicantRole",
          status: "active",
          identityIdFrom: "runtime.approveApplicantIdentity.id",
          saveAs: "approveApplicantUser",
        },
      },
      {
        source: { caseStepId: "Setup-6", method: "api" },
        id: "ory.reject_identity.upsert",
        title: "准备邮箱为 `orf-member-review-reject-e2e@orf.local`、使用固定测试密码的审批拒绝申请人登录身份",
        object: "ory.identity",
        operator: "upsert_password",
        params: { emailFrom: "data.rejectApplicantEmail", nameFrom: "data.rejectApplicantName", passwordFrom: "data.rejectApplicantPassword", saveAs: "rejectApplicantIdentity" },
      },
      {
        source: { caseStepId: "Setup-7", method: "prisma" },
        id: "db.reject_member.upsert",
        title: "准备邮箱为 `orf-member-review-reject-e2e@orf.local`、角色为 `member`、状态为 `active` 的审批拒绝申请人用户和默认团队成员关系",
        object: "db.user",
        operator: "upsert",
        params: {
          emailFrom: "data.rejectApplicantEmail",
          nameFrom: "data.rejectApplicantName",
          roleFrom: "data.rejectApplicantRole",
          status: "active",
          identityIdFrom: "runtime.rejectApplicantIdentity.id",
          saveAs: "rejectApplicantUser",
        },
      },
      {
        source: { caseStepId: "Setup-8", method: "prisma" },
        id: "db.objective.upsert_reviewable",
        title: "创建标题为 `E2E-REVIEW-APPLICATION: 成员申请审批`、流转状态为 `open`、阶段为 `resultClaiming` 的本用例审批目标",
        object: "db.objective",
        operator: "upsert",
        params: {
          idFrom: "data.objectiveId",
          titleFrom: "data.objectiveTitle",
          teamIdFrom: "runtime.adminUser.teamId",
          stage: "resultClaiming",
          flowStatus: "open",
          status: "Draft",
          saveAs: "fixtureObjective",
        },
      },
      {
        source: { caseStepId: "Setup-9", method: "prisma" },
        id: "db.challenge_review.target_from_objective",
        title: "记录本用例审批目标的原始状态为 runtime.reviewTarget",
        object: "db.challenge_review",
        operator: "target_from_objective",
        params: { objectiveIdFrom: "runtime.fixtureObjective.id", objectiveTitleFrom: "runtime.fixtureObjective.title", saveAs: "reviewTarget" },
      },
      {
        source: { caseStepId: "Setup-10", method: "api" },
        id: "ory.admin_sessions.revoke",
        title: "撤销管理员登录身份可能残留的登录会话",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Setup-11", method: "api" },
        id: "ory.approve_sessions.revoke",
        title: "撤销审批通过申请人登录身份可能残留的登录会话",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.approveApplicantEmail" },
      },
      {
        source: { caseStepId: "Setup-12", method: "api" },
        id: "ory.reject_sessions.revoke",
        title: "撤销审批拒绝申请人登录身份可能残留的登录会话",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.rejectApplicantEmail" },
      },
      { source: { caseStepId: "Setup-13", method: "playwright" }, id: "auth.logout", title: "注销当前登录会话", object: "auth", operator: "logout" },
      { source: { caseStepId: "Setup-14", method: "playwright" }, id: "page.runtime.stop", title: "离开当前 ORF 前端页面", object: "page.runtime", operator: "stop" },
      { source: { caseStepId: "Setup-15", method: "playwright" }, id: "browser.clear", title: "移除当前浏览器中的残留登录态", object: "browser", operator: "clear_state" },
    ],
  },

  S0: {
    description: "三个账号和本用例审批目标已准备完成，两个成员尚未提交挑战申请",
    assertions: [
      { source: { caseStepId: "S0-1", method: "api" }, id: "session.unauthenticated", title: "当前会话 应为 未登录", object: "auth.session", operator: "unauthenticated" },
      {
        source: { caseStepId: "S0-2", method: "prisma" },
        id: "db.objective.flow_open",
        title: "本用例审批目标的 flowStatus 应为 `open`",
        object: "db.objective",
        operator: "flow_status",
        params: { targetFrom: "runtime.reviewTarget", status: "open" },
      },
      {
        source: { caseStepId: "S0-3", method: "prisma" },
        id: "db.objective.stage_result_claiming",
        title: "本用例审批目标的阶段 应为 `resultClaiming`",
        object: "db.objective",
        operator: "stage",
        params: { targetFrom: "runtime.reviewTarget", stage: "resultClaiming" },
      },
      {
        source: { caseStepId: "S0-4", method: "prisma" },
        id: "db.approve_application.absent",
        title: "\"ORF Member Review Approve E2E\" 对本用例审批目标的挑战申请 应不存在",
        object: "db.challenge_application",
        operator: "absent",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.approveApplicantName" },
      },
      {
        source: { caseStepId: "S0-5", method: "prisma" },
        id: "db.reject_application.absent",
        title: "\"ORF Member Review Reject E2E\" 对本用例审批目标的挑战申请 应不存在",
        object: "db.challenge_application",
        operator: "absent",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.rejectApplicantName" },
      },
      {
        source: { caseStepId: "S0-6", method: "prisma" },
        id: "db.approve_challenger.absent",
        title: "本用例审批目标的挑战者列表 应不包含 \"ORF Member Review Approve E2E\"",
        object: "db.objective_challengers",
        operator: "absent",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.approveApplicantName" },
      },
      {
        source: { caseStepId: "S0-7", method: "prisma" },
        id: "db.reject_challenger.absent",
        title: "本用例审批目标的挑战者列表 应不包含 \"ORF Member Review Reject E2E\"",
        object: "db.objective_challengers",
        operator: "absent",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.rejectApplicantName" },
      },
    ],
  },

  Action: {
    description: "两个普通成员分别提交挑战申请，管理员通过一个申请并拒绝另一个申请，两个成员分别查看结果",
    steps: [
      { source: { caseStepId: "Action-1", method: "playwright" }, id: "approve_member.goto_auth", title: "打开 ORF 登录页", object: "page", operator: "goto", params: { path: "/auth" } },
      {
        source: { caseStepId: "Action-2", method: "playwright" },
        id: "approve_member.fill_email",
        title: "在邮箱输入框输入审批通过申请人固定测试邮箱",
        object: "page",
        operator: "fill",
        params: { label: "Email", valueFrom: "data.approveApplicantEmail" },
      },
      {
        source: { caseStepId: "Action-3", method: "playwright" },
        id: "approve_member.fill_password",
        title: "在密码输入框输入审批通过申请人固定测试密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.approveApplicantPassword" },
      },
      { source: { caseStepId: "Action-4", method: "playwright" }, id: "approve_member.sign_in", title: "点击 \"Sign In\" 登录操作", object: "page", operator: "click", params: { role: "button", name: "Sign In" } },
      {
        source: { caseStepId: "Action-5", method: "api" },
        id: "approve_member.session",
        title: "当前会话 应为 审批通过申请人的已登录会话",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.approveApplicantEmail", roleFrom: "data.approveApplicantRole", status: "active" },
      },
      { source: { caseStepId: "Action-6", method: "playwright" }, id: "approve_member.goto_bounties", title: "打开 悬赏大厅", object: "page", operator: "goto", params: { path: "/bounties" } },
      {
        source: { caseStepId: "Action-7", method: "api" },
        id: "approve_member.bounty_available",
        title: "悬赏大厅数据中的本用例审批目标 对审批通过申请人 应可申请",
        object: "api.bounties",
        operator: "target_available",
        params: { targetFrom: "runtime.reviewTarget" },
      },
      {
        source: { caseStepId: "Action-8", method: "playwright" },
        id: "approve_member.apply_visible",
        title: "本用例审批目标的 \"申请挑战\" 操作 应可见",
        object: "page.bounty_row",
        operator: "apply_visible",
        params: { targetFrom: "runtime.reviewTarget" },
      },
      {
        source: { caseStepId: "Action-9", method: "playwright" },
        id: "approve_member.apply",
        title: "点击 本用例审批目标的 \"申请挑战\" 操作",
        object: "page.bounty_row",
        operator: "apply",
        params: { targetFrom: "runtime.reviewTarget" },
      },
      {
        source: { caseStepId: "Action-10", method: "playwright" },
        id: "approve_member.dialog_visible",
        title: "提交挑战申请确认弹窗 应可见",
        object: "page.challenge_application_dialog",
        operator: "visible",
      },
      {
        source: { caseStepId: "Action-11", method: "playwright" },
        id: "approve_member.confirm_application",
        title: "在确认弹窗中点击 \"申请挑战\"",
        object: "page.challenge_application_dialog",
        operator: "confirm",
        params: { targetFrom: "runtime.reviewTarget", saveAs: "approveApplicationResponse" },
      },
      {
        source: { caseStepId: "Action-12", method: "api" },
        id: "approve_application.record",
        title: "创建审批通过挑战申请结果 应成功，并记录 审批通过挑战申请",
        object: "api.challenge_application",
        operator: "record_approve_application",
        params: { responseFrom: "runtime.approveApplicationResponse", targetFrom: "runtime.reviewTarget", applicantFrom: "data.approveApplicantName", saveAs: "reviewTarget" },
      },
      {
        source: { caseStepId: "Action-13", method: "api" },
        id: "approve_member.current_application",
        title: "悬赏大厅数据中的本用例审批目标 对审批通过申请人 应为 已申请",
        object: "api.bounties",
        operator: "current_application",
        params: { targetFrom: "runtime.reviewTarget" },
      },
      { source: { caseStepId: "Action-14", method: "api" }, id: "approve_member.logout", title: "注销审批通过申请人登录会话", object: "auth", operator: "logout" },
      { source: { caseStepId: "Action-15", method: "playwright" }, id: "approve_member.clear", title: "移除当前浏览器中的残留登录态", object: "browser", operator: "clear_state" },

      { source: { caseStepId: "Action-16", method: "playwright" }, id: "reject_member.goto_auth", title: "打开 ORF 登录页", object: "page", operator: "goto", params: { path: "/auth" } },
      {
        source: { caseStepId: "Action-17", method: "playwright" },
        id: "reject_member.fill_email",
        title: "在邮箱输入框输入审批拒绝申请人固定测试邮箱",
        object: "page",
        operator: "fill",
        params: { label: "Email", valueFrom: "data.rejectApplicantEmail" },
      },
      {
        source: { caseStepId: "Action-18", method: "playwright" },
        id: "reject_member.fill_password",
        title: "在密码输入框输入审批拒绝申请人固定测试密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.rejectApplicantPassword" },
      },
      { source: { caseStepId: "Action-19", method: "playwright" }, id: "reject_member.sign_in", title: "点击 \"Sign In\" 登录操作", object: "page", operator: "click", params: { role: "button", name: "Sign In" } },
      {
        source: { caseStepId: "Action-20", method: "api" },
        id: "reject_member.session",
        title: "当前会话 应为 审批拒绝申请人的已登录会话",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.rejectApplicantEmail", roleFrom: "data.rejectApplicantRole", status: "active" },
      },
      { source: { caseStepId: "Action-21", method: "playwright" }, id: "reject_member.goto_bounties", title: "打开 悬赏大厅", object: "page", operator: "goto", params: { path: "/bounties" } },
      {
        source: { caseStepId: "Action-22", method: "api" },
        id: "reject_member.bounty_available",
        title: "悬赏大厅数据中的本用例审批目标 对审批拒绝申请人 应可申请",
        object: "api.bounties",
        operator: "target_available",
        params: { targetFrom: "runtime.reviewTarget" },
      },
      {
        source: { caseStepId: "Action-23", method: "playwright" },
        id: "reject_member.apply_visible",
        title: "本用例审批目标的 \"申请挑战\" 操作 应可见",
        object: "page.bounty_row",
        operator: "apply_visible",
        params: { targetFrom: "runtime.reviewTarget" },
      },
      {
        source: { caseStepId: "Action-24", method: "playwright" },
        id: "reject_member.apply",
        title: "点击 本用例审批目标的 \"申请挑战\" 操作",
        object: "page.bounty_row",
        operator: "apply",
        params: { targetFrom: "runtime.reviewTarget" },
      },
      {
        source: { caseStepId: "Action-25", method: "playwright" },
        id: "reject_member.dialog_visible",
        title: "提交挑战申请确认弹窗 应可见",
        object: "page.challenge_application_dialog",
        operator: "visible",
      },
      {
        source: { caseStepId: "Action-26", method: "playwright" },
        id: "reject_member.confirm_application",
        title: "在确认弹窗中点击 \"申请挑战\"",
        object: "page.challenge_application_dialog",
        operator: "confirm",
        params: { targetFrom: "runtime.reviewTarget", saveAs: "rejectApplicationResponse" },
      },
      {
        source: { caseStepId: "Action-27", method: "api" },
        id: "reject_application.record",
        title: "创建审批拒绝挑战申请结果 应成功，并记录 审批拒绝挑战申请",
        object: "api.challenge_application",
        operator: "record_reject_application",
        params: { responseFrom: "runtime.rejectApplicationResponse", targetFrom: "runtime.reviewTarget", applicantFrom: "data.rejectApplicantName", saveAs: "reviewTarget" },
      },
      {
        source: { caseStepId: "Action-28", method: "api" },
        id: "reject_member.current_application",
        title: "悬赏大厅数据中的本用例审批目标 对审批拒绝申请人 应为 已申请",
        object: "api.bounties",
        operator: "current_application",
        params: { targetFrom: "runtime.reviewTarget" },
      },
      { source: { caseStepId: "Action-29", method: "api" }, id: "reject_member.logout", title: "注销审批拒绝申请人登录会话", object: "auth", operator: "logout" },
      { source: { caseStepId: "Action-30", method: "playwright" }, id: "reject_member.clear", title: "移除当前浏览器中的残留登录态", object: "browser", operator: "clear_state" },

      { source: { caseStepId: "Action-31", method: "playwright" }, id: "admin.goto_auth", title: "打开 ORF 登录页", object: "page", operator: "goto", params: { path: "/auth" } },
      { source: { caseStepId: "Action-32", method: "playwright" }, id: "admin.fill_email", title: "在邮箱输入框输入管理员固定测试邮箱", object: "page", operator: "fill", params: { label: "Email", valueFrom: "data.email" } },
      {
        source: { caseStepId: "Action-33", method: "playwright" },
        id: "admin.fill_password",
        title: "在密码输入框输入管理员固定测试密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.password" },
      },
      { source: { caseStepId: "Action-34", method: "playwright" }, id: "admin.sign_in", title: "点击 \"Sign In\" 登录操作", object: "page", operator: "click", params: { role: "button", name: "Sign In" } },
      {
        source: { caseStepId: "Action-35", method: "api" },
        id: "admin.session",
        title: "当前会话 应为 管理员的已登录会话",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      { source: { caseStepId: "Action-36", method: "playwright" }, id: "admin.goto_tasks", title: "打开 挑战工作台", object: "page", operator: "goto", params: { path: "/tasks" } },
      { source: { caseStepId: "Action-37", method: "playwright" }, id: "admin.scope_all", title: "切换到 \"所有挑战\" 视图", object: "page", operator: "click", params: { role: "button", name: "所有挑战" } },
      {
        source: { caseStepId: "Action-38", method: "playwright" },
        id: "admin.review_target.visible",
        title: "本用例审批目标面板 应可见",
        object: "page.challenge_review_target",
        operator: "visible",
        params: { targetFrom: "runtime.reviewTarget" },
      },
      {
        source: { caseStepId: "Action-39", method: "playwright" },
        id: "admin.approve_application.visible",
        title: "\"ORF Member Review Approve E2E\" 挑战申请的 \"通过\" 操作 应可见",
        object: "page.challenge_application",
        operator: "approve_visible",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.approveApplicantName" },
      },
      {
        source: { caseStepId: "Action-40", method: "playwright" },
        id: "admin.approve_application",
        title: "点击 \"ORF Member Review Approve E2E\" 挑战申请的 \"通过\" 操作",
        object: "page.challenge_application",
        operator: "approve",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.approveApplicantName", saveAs: "approveResponse" },
      },
      {
        source: { caseStepId: "Action-41", method: "playwright" },
        id: "admin.reject_application.visible",
        title: "\"ORF Member Review Reject E2E\" 挑战申请的 \"拒绝\" 操作 应可见",
        object: "page.challenge_application",
        operator: "reject_visible",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.rejectApplicantName" },
      },
      {
        source: { caseStepId: "Action-42", method: "playwright" },
        id: "admin.reject_application",
        title: "点击 \"ORF Member Review Reject E2E\" 挑战申请的 \"拒绝\" 操作",
        object: "page.challenge_application",
        operator: "reject",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.rejectApplicantName", saveAs: "rejectResponse" },
      },
      { source: { caseStepId: "Action-43", method: "api" }, id: "admin.logout", title: "注销管理员登录会话", object: "auth", operator: "logout" },
      { source: { caseStepId: "Action-44", method: "playwright" }, id: "admin.clear", title: "移除当前浏览器中的残留登录态", object: "browser", operator: "clear_state" },

      { source: { caseStepId: "Action-45", method: "playwright" }, id: "approve_result.goto_auth", title: "打开 ORF 登录页", object: "page", operator: "goto", params: { path: "/auth" } },
      {
        source: { caseStepId: "Action-46", method: "playwright" },
        id: "approve_result.fill_email",
        title: "在邮箱输入框输入审批通过申请人固定测试邮箱",
        object: "page",
        operator: "fill",
        params: { label: "Email", valueFrom: "data.approveApplicantEmail" },
      },
      {
        source: { caseStepId: "Action-47", method: "playwright" },
        id: "approve_result.fill_password",
        title: "在密码输入框输入审批通过申请人固定测试密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.approveApplicantPassword" },
      },
      { source: { caseStepId: "Action-48", method: "playwright" }, id: "approve_result.sign_in", title: "点击 \"Sign In\" 登录操作", object: "page", operator: "click", params: { role: "button", name: "Sign In" } },
      {
        source: { caseStepId: "Action-49", method: "api" },
        id: "approve_result.session",
        title: "当前会话 应为 审批通过申请人的已登录会话",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.approveApplicantEmail", roleFrom: "data.approveApplicantRole", status: "active" },
      },
      { source: { caseStepId: "Action-50", method: "playwright" }, id: "approve_result.goto_tasks", title: "打开 挑战工作台", object: "page", operator: "goto", params: { path: "/tasks" } },
      {
        source: { caseStepId: "Action-51", method: "api" },
        id: "approve_result.workbench_present",
        title: "审批通过申请人的挑战工作台数据 应包含 本用例审批目标",
        object: "api.my_challenges",
        operator: "objective_present",
        params: { targetFrom: "runtime.reviewTarget" },
      },
      {
        source: { caseStepId: "Action-52", method: "playwright" },
        id: "approve_result.panel_visible",
        title: "本用例审批目标面板 应可见",
        object: "page.challenge_review_target",
        operator: "visible",
        params: { targetFrom: "runtime.reviewTarget" },
      },
      { source: { caseStepId: "Action-53", method: "api" }, id: "approve_result.logout", title: "注销审批通过申请人登录会话", object: "auth", operator: "logout" },
      { source: { caseStepId: "Action-54", method: "playwright" }, id: "approve_result.clear", title: "移除当前浏览器中的残留登录态", object: "browser", operator: "clear_state" },

      { source: { caseStepId: "Action-55", method: "playwright" }, id: "reject_result.goto_auth", title: "打开 ORF 登录页", object: "page", operator: "goto", params: { path: "/auth" } },
      {
        source: { caseStepId: "Action-56", method: "playwright" },
        id: "reject_result.fill_email",
        title: "在邮箱输入框输入审批拒绝申请人固定测试邮箱",
        object: "page",
        operator: "fill",
        params: { label: "Email", valueFrom: "data.rejectApplicantEmail" },
      },
      {
        source: { caseStepId: "Action-57", method: "playwright" },
        id: "reject_result.fill_password",
        title: "在密码输入框输入审批拒绝申请人固定测试密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.rejectApplicantPassword" },
      },
      { source: { caseStepId: "Action-58", method: "playwright" }, id: "reject_result.sign_in", title: "点击 \"Sign In\" 登录操作", object: "page", operator: "click", params: { role: "button", name: "Sign In" } },
      {
        source: { caseStepId: "Action-59", method: "api" },
        id: "reject_result.session",
        title: "当前会话 应为 审批拒绝申请人的已登录会话",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.rejectApplicantEmail", roleFrom: "data.rejectApplicantRole", status: "active" },
      },
      { source: { caseStepId: "Action-60", method: "playwright" }, id: "reject_result.goto_tasks", title: "打开 挑战工作台", object: "page", operator: "goto", params: { path: "/tasks" } },
      {
        source: { caseStepId: "Action-61", method: "api" },
        id: "reject_result.workbench_absent",
        title: "审批拒绝申请人的挑战工作台数据 应不包含 本用例审批目标",
        object: "api.my_challenges",
        operator: "objective_absent",
        params: { targetFrom: "runtime.reviewTarget" },
      },
      { source: { caseStepId: "Action-62", method: "api" }, id: "reject_result.logout", title: "注销审批拒绝申请人登录会话", object: "auth", operator: "logout" },
      { source: { caseStepId: "Action-63", method: "playwright" }, id: "reject_result.clear", title: "移除当前浏览器中的残留登录态", object: "browser", operator: "clear_state" },
    ],
  },

  S1: {
    description: "审批结果已经持久化，通过成员可进入挑战工作台，拒绝成员不会进入挑战者列表",
    assertions: [
      {
        source: { caseStepId: "S1-1", method: "api" },
        id: "approve_response.ok",
        title: "审批通过结果 应成功，且响应目标 ID 为本用例审批目标 ID",
        object: "api.challenge_review",
        operator: "response_ok",
        params: { responseFrom: "runtime.approveResponse", targetFrom: "runtime.reviewTarget" },
      },
      {
        source: { caseStepId: "S1-2", method: "api" },
        id: "reject_response.ok",
        title: "审批拒绝结果 应成功，且响应目标 ID 为本用例审批目标 ID",
        object: "api.challenge_review",
        operator: "response_ok",
        params: { responseFrom: "runtime.rejectResponse", targetFrom: "runtime.reviewTarget" },
      },
      {
        source: { caseStepId: "S1-3", method: "prisma" },
        id: "db.approve_application.approved",
        title: "\"ORF Member Review Approve E2E\" 对本用例审批目标的挑战申请状态 应变为 `approved`",
        object: "db.challenge_application",
        operator: "status",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.approveApplicantName", status: "approved" },
      },
      {
        source: { caseStepId: "S1-4", method: "prisma" },
        id: "db.approve_challenger.present",
        title: "本用例审批目标的挑战者列表 应包含 \"ORF Member Review Approve E2E\"",
        object: "db.objective_challengers",
        operator: "present",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.approveApplicantName" },
      },
      {
        source: { caseStepId: "S1-5", method: "prisma" },
        id: "db.reject_application.declined",
        title: "\"ORF Member Review Reject E2E\" 对本用例审批目标的挑战申请状态 应变为 `declined`",
        object: "db.challenge_application",
        operator: "status",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.rejectApplicantName", status: "declined" },
      },
      {
        source: { caseStepId: "S1-6", method: "prisma" },
        id: "db.reject_challenger.absent",
        title: "本用例审批目标的挑战者列表 应不包含 \"ORF Member Review Reject E2E\"",
        object: "db.objective_challengers",
        operator: "absent",
        params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.rejectApplicantName" },
      },
      {
        source: { caseStepId: "S1-7", method: "prisma" },
        id: "db.objective.flow_reestimating",
        title: "本用例审批目标的 flowStatus 应变为 `reestimating`",
        object: "db.objective",
        operator: "flow_status",
        params: { targetFrom: "runtime.reviewTarget", status: "reestimating" },
      },
      {
        source: { caseStepId: "S1-8", method: "prisma" },
        id: "db.objective.stage_orf_reestimate",
        title: "本用例审批目标的阶段 应变为 `orfReestimate`",
        object: "db.objective",
        operator: "stage",
        params: { targetFrom: "runtime.reviewTarget", stage: "orfReestimate" },
      },
      { source: { caseStepId: "S1-9", method: "api" }, id: "session.unauthenticated", title: "当前会话 应为 未登录", object: "auth.session", operator: "unauthenticated" },
    ],
  },

  Clean: {
    description: "删除本用例目标、三个独占账号并恢复未登录基准状态",
    steps: [
      {
        source: { caseStepId: "Clean-1", method: "prisma" },
        id: "db.objective.delete_by_title",
        title: "删除 本用例审批目标及其派生数据",
        object: "db.objective",
        operator: "delete_by_title",
        params: { titleFrom: "data.objectiveTitle" },
      },
      { source: { caseStepId: "Clean-2", method: "api" }, id: "auth.logout", title: "注销当前登录会话", object: "auth", operator: "logout" },
      { source: { caseStepId: "Clean-3", method: "playwright" }, id: "page.runtime.stop", title: "离开当前 ORF 前端页面", object: "page.runtime", operator: "stop" },
      { source: { caseStepId: "Clean-4", method: "playwright" }, id: "browser.clear", title: "移除当前浏览器中的残留登录态", object: "browser", operator: "clear_state" },
      { source: { caseStepId: "Clean-5", method: "api" }, id: "ory.admin_sessions.revoke", title: "撤销管理员登录身份的残留登录会话", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.email" } },
      {
        source: { caseStepId: "Clean-6", method: "api" },
        id: "ory.approve_sessions.revoke",
        title: "撤销审批通过申请人登录身份的残留登录会话",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.approveApplicantEmail" },
      },
      {
        source: { caseStepId: "Clean-7", method: "api" },
        id: "ory.reject_sessions.revoke",
        title: "撤销审批拒绝申请人登录身份的残留登录会话",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.rejectApplicantEmail" },
      },
      {
        source: { caseStepId: "Clean-8", method: "api" },
        id: "ory.admin_identity.delete",
        title: "删除邮箱为 `orf-admin-review-application-e2e@orf.local` 的管理员登录身份",
        object: "ory.identity",
        operator: "delete_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-9", method: "api" },
        id: "ory.approve_identity.delete",
        title: "删除邮箱为 `orf-member-review-approve-e2e@orf.local` 的审批通过申请人登录身份",
        object: "ory.identity",
        operator: "delete_by_email",
        params: { emailFrom: "data.approveApplicantEmail" },
      },
      {
        source: { caseStepId: "Clean-10", method: "api" },
        id: "ory.reject_identity.delete",
        title: "删除邮箱为 `orf-member-review-reject-e2e@orf.local` 的审批拒绝申请人登录身份",
        object: "ory.identity",
        operator: "delete_by_email",
        params: { emailFrom: "data.rejectApplicantEmail" },
      },
      { source: { caseStepId: "Clean-11", method: "prisma" }, id: "db.admin.memberships.delete", title: "删除管理员用户的默认团队成员关系", object: "db.user", operator: "delete_memberships", params: { emailFrom: "data.email" } },
      {
        source: { caseStepId: "Clean-12", method: "prisma" },
        id: "db.approve_member.memberships.delete",
        title: "删除审批通过申请人用户的默认团队成员关系",
        object: "db.user",
        operator: "delete_memberships",
        params: { emailFrom: "data.approveApplicantEmail" },
      },
      {
        source: { caseStepId: "Clean-13", method: "prisma" },
        id: "db.reject_member.memberships.delete",
        title: "删除审批拒绝申请人用户的默认团队成员关系",
        object: "db.user",
        operator: "delete_memberships",
        params: { emailFrom: "data.rejectApplicantEmail" },
      },
      { source: { caseStepId: "Clean-14", method: "prisma" }, id: "db.admin.delete", title: "删除邮箱为 `orf-admin-review-application-e2e@orf.local` 的管理员用户", object: "db.user", operator: "delete", params: { emailFrom: "data.email" } },
      {
        source: { caseStepId: "Clean-15", method: "prisma" },
        id: "db.approve_member.delete",
        title: "删除邮箱为 `orf-member-review-approve-e2e@orf.local` 的审批通过申请人用户",
        object: "db.user",
        operator: "delete",
        params: { emailFrom: "data.approveApplicantEmail" },
      },
      {
        source: { caseStepId: "Clean-16", method: "prisma" },
        id: "db.reject_member.delete",
        title: "删除邮箱为 `orf-member-review-reject-e2e@orf.local` 的审批拒绝申请人用户",
        object: "db.user",
        operator: "delete",
        params: { emailFrom: "data.rejectApplicantEmail" },
      },
      {
        source: { caseStepId: "Clean-17", method: "prisma" },
        id: "db.objective.absent",
        title: "应不存在 标题为 `E2E-REVIEW-APPLICATION: 成员申请审批` 的测试目标",
        object: "db.objective",
        operator: "absent",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Clean-18", method: "prisma" },
        id: "db.users.absent",
        title: "应不存在 本用例独占管理员、审批通过申请人和审批拒绝申请人用户",
        object: "db.user",
        operator: "absent",
        params: {
          emails: [
            "orf-admin-review-application-e2e@orf.local",
            "orf-member-review-approve-e2e@orf.local",
            "orf-member-review-reject-e2e@orf.local",
          ],
        },
      },
    ],
  },
} satisfies StateCaseSpec<ReviewApplicationCaseData>;
