import { STATE_CASE_MODEL, type StateCaseSpec } from "../../_framework/types";
import type { RegisterCaseData } from "./_support/register.context";

export const registerApprovalLoginCase = {
  id: "auth.register.approve-login",
  title: "用户注册通过后可以再次登录 ORF",
  model: STATE_CASE_MODEL,
  tags: ["auth", "registration", "approval", "member", "happy-path"],

  data: {
    email: "orf-register-e2e@orf.local",
    password: "OrfRegisterE2E!2026",
    name: "ORF Register E2E",
    role: "member",
    adminEmail: "zrx831@gmail.com",
    adminPassword: "123123123",
    adminRole: "admin",
  },

  B: {
    description: "系统服务可用，预置管理员存在，注册测试用户不存在，浏览器未登录",
    assertions: [
      { id: "backend.ready", title: "后端服务可用", object: "api.health", operator: "ok" },
      { id: "db.ready", title: "数据库可连接", object: "db", operator: "ready" },
      { id: "ory.ready", title: "Ory Admin API 可用", object: "ory.admin", operator: "ready" },
      {
        id: "ory.admin_identity.exists",
        title: "管理员 Ory 身份存在",
        object: "ory.identity",
        operator: "exists",
        params: { emailFrom: "data.adminEmail" },
      },
      {
        id: "db.admin.active",
        title: "预置管理员账号可用",
        object: "db.admin",
        operator: "active",
        params: { emailFrom: "data.adminEmail" },
      },
      {
        id: "ory.register_identity.absent",
        title: "注册测试 Ory 身份不存在",
        object: "ory.identity",
        operator: "absent",
        params: { emailFrom: "data.email" },
      },
      {
        id: "db.registered_user.absent",
        title: "注册测试用户不存在",
        object: "db.registered_user",
        operator: "absent",
        params: { emailFrom: "data.email" },
      },
      { id: "session.unauthenticated", title: "后端 session 未登录", object: "auth.session", operator: "unauthenticated" },
      { id: "cookie.absent", title: "浏览器不存在登录 cookie", object: "browser.cookie", operator: "absent" },
      { id: "storage.empty", title: "浏览器 storage 不含登录态", object: "browser.auth_storage", operator: "empty" },
    ],
  },

  Setup: {
    description: "清理浏览器并进入注册模式",
    steps: [
      { id: "browser.clear", title: "清理浏览器状态", object: "browser", operator: "clear_state" },
      { id: "page.goto.auth", title: "打开登录页", object: "page", operator: "goto", params: { path: "/auth" } },
      {
        id: "switch.register",
        title: "切换到注册模式",
        object: "page",
        operator: "click",
        params: { role: "button", name: "Register" },
      },
    ],
  },

  S0: {
    description: "注册表单可用，测试用户尚不存在，当前浏览器仍未登录",
    assertions: [
      { id: "url.auth", title: "当前页面是登录页", object: "page.url", operator: "match", params: { pattern: "/auth$" } },
      {
        id: "heading.register.visible",
        title: "注册页标题可见",
        object: "page",
        operator: "visible",
        params: { role: "heading", name: "Register" },
      },
      { id: "input.name.empty", title: "姓名输入框为空", object: "input", operator: "value", params: { label: "Name", value: "" } },
      { id: "input.email.empty", title: "邮箱输入框为空", object: "input", operator: "value", params: { label: "Email", value: "" } },
      {
        id: "input.password.empty",
        title: "密码输入框为空",
        object: "input",
        operator: "value",
        params: { label: "Password", exact: true, value: "" },
      },
      {
        id: "button.create_account.enabled",
        title: "创建账号按钮可点击",
        object: "page",
        operator: "enabled",
        params: { role: "button", name: "Create Account" },
      },
      { id: "session.unauthenticated", title: "后端 session 未登录", object: "auth.session", operator: "unauthenticated" },
      {
        id: "ory.register_identity.absent",
        title: "注册测试 Ory 身份不存在",
        object: "ory.identity",
        operator: "absent",
        params: { emailFrom: "data.email" },
      },
      {
        id: "db.registered_user.absent",
        title: "注册测试用户不存在",
        object: "db.registered_user",
        operator: "absent",
        params: { emailFrom: "data.email" },
      },
    ],
  },

  Action: {
    description: "提交注册申请、管理员通过后再用注册用户登录",
    steps: [
      { id: "fill.name", title: "输入姓名", object: "page", operator: "fill", params: { label: "Name", valueFrom: "data.name" } },
      { id: "fill.email", title: "输入邮箱", object: "page", operator: "fill", params: { label: "Email", valueFrom: "data.email" } },
      {
        id: "fill.password",
        title: "输入密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.password" },
      },
      {
        id: "capture.registration_response",
        title: "注册账号响应捕获",
        object: "api",
        operator: "capture_response",
        params: { urlEndsWith: "/api/auth/registration", method: "POST", saveAs: "registrationResponse" },
      },
      {
        id: "click.create_account",
        title: "提交注册申请",
        object: "page",
        operator: "click",
        params: { role: "button", name: "Create Account" },
      },
      {
        id: "approval_pending.visible",
        title: "记录等待审核状态可见",
        object: "page.approval_pending",
        operator: "visible",
        params: { saveAs: "approvalPendingSeen" },
      },
      {
        id: "registration_response.record_user",
        title: "记录注册响应用户",
        object: "api.registration_response",
        operator: "record_user",
        params: { responseFrom: "runtime.registrationResponse", saveAs: "registeredUser" },
      },
      {
        id: "db.registered_user.pending",
        title: "记录注册用户待审核状态",
        object: "db.registered_user",
        operator: "pending",
        params: { emailFrom: "data.email", saveAs: "pendingRegisteredUser" },
      },
      { id: "auth.logout.pending_user", title: "退出注册用户会话", object: "auth", operator: "logout" },
      { id: "browser.clear.pending_user", title: "清理注册用户浏览器状态", object: "browser", operator: "clear_state" },
      { id: "page.goto.auth.admin", title: "打开登录页", object: "page", operator: "goto", params: { path: "/auth" } },
      {
        id: "fill.admin.email",
        title: "输入管理员邮箱",
        object: "page",
        operator: "fill",
        params: { label: "Email", valueFrom: "data.adminEmail" },
      },
      {
        id: "fill.admin.password",
        title: "输入管理员密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.adminPassword" },
      },
      {
        id: "click.admin.sign_in",
        title: "管理员登录",
        object: "page",
        operator: "click",
        params: { role: "button", name: "Sign In" },
      },
      {
        id: "session.admin.authenticated",
        title: "等待管理员 session 已登录",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.adminEmail", roleFrom: "data.adminRole", status: "active" },
      },
      { id: "page.goto.members", title: "打开成员管理页", object: "page", operator: "goto", params: { path: "/members" } },
      {
        id: "member_row.visible",
        title: "注册用户行可见",
        object: "page.member_row",
        operator: "visible",
        params: { emailFrom: "data.email", nameFrom: "data.name" },
      },
      {
        id: "capture.approval_response",
        title: "注册通过响应捕获",
        object: "api.registration_approval",
        operator: "capture_response",
        params: { userIdFrom: "runtime.registeredUser.id", saveAs: "approvalResponse" },
      },
      {
        id: "member_row.approve",
        title: "通过注册申请",
        object: "page.member_row",
        operator: "approve",
        params: { emailFrom: "data.email", nameFrom: "data.name" },
      },
      { id: "auth.logout.admin", title: "管理员退出登录", object: "auth", operator: "logout" },
      { id: "browser.clear.admin", title: "清理管理员浏览器状态", object: "browser", operator: "clear_state" },
      { id: "page.goto.auth.member", title: "打开登录页", object: "page", operator: "goto", params: { path: "/auth" } },
      { id: "fill.member.email", title: "输入注册用户邮箱", object: "page", operator: "fill", params: { label: "Email", valueFrom: "data.email" } },
      {
        id: "fill.member.password",
        title: "输入注册用户密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.password" },
      },
      {
        id: "click.member.sign_in",
        title: "注册用户再次登录",
        object: "page",
        operator: "click",
        params: { role: "button", name: "Sign In" },
      },
    ],
  },

  S1: {
    description: "注册申请通过，注册用户可以作为普通成员登录",
    assertions: [
      {
        id: "registration_response.pending",
        title: "注册响应为待审核普通成员",
        object: "api.registration_response",
        operator: "pending",
        params: { responseFrom: "runtime.registrationResponse", emailFrom: "data.email" },
      },
      {
        id: "approval_pending.seen",
        title: "注册后曾显示等待审核",
        object: "runtime.boolean",
        operator: "true",
        params: { valueFrom: "runtime.approvalPendingSeen" },
      },
      {
        id: "pending_user.recorded",
        title: "注册用户曾处于待审核状态",
        object: "runtime.registered_user",
        operator: "pending",
        params: { userFrom: "runtime.pendingRegisteredUser", emailFrom: "data.email" },
      },
      {
        id: "approval_response.ok",
        title: "注册通过接口响应成功",
        object: "api.registration_approval",
        operator: "ok",
        params: { responseFrom: "runtime.approvalResponse" },
      },
      {
        id: "db.registered_user.active",
        title: "注册用户已启用",
        object: "db.registered_user",
        operator: "active",
        params: { emailFrom: "data.email" },
      },
      {
        id: "session.member.authenticated",
        title: "注册用户 session 已登录",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      { id: "url.tasks", title: "进入登录后页面", object: "page.url", operator: "match", params: { pattern: "/(tasks|bounties)$" } },
      { id: "nav.visible", title: "主导航可见", object: "page", operator: "visible", params: { label: "主导航" } },
      { id: "current_user.visible", title: "当前用户入口可见", object: "page", operator: "visible", params: { label: "当前用户" } },
      { id: "members.nav.absent", title: "成员管理入口不可见", object: "page", operator: "count", params: { text: "成员管理", count: 0 } },
    ],
  },

  Clean: {
    description: "删除注册测试用户和 Ory 身份，恢复未登录基准状态",
    steps: [
      { id: "auth.logout", title: "退出当前登录态", object: "auth", operator: "logout" },
      { id: "browser.clear", title: "清理浏览器状态", object: "browser", operator: "clear_state" },
      {
        id: "ory.sessions.revoke.registered_user",
        title: "撤销注册测试身份 Ory session",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        id: "db.registered_user.delete",
        title: "删除注册测试用户",
        object: "db.registered_user",
        operator: "delete",
        params: { emailFrom: "data.email" },
      },
      {
        id: "ory.register_identity.delete",
        title: "删除注册测试 Ory 身份",
        object: "ory.identity",
        operator: "delete_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        id: "ory.sessions.revoke.admin",
        title: "撤销管理员残留 Ory session",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.adminEmail" },
      },
      {
        id: "ory.admin_identity.exists",
        title: "管理员 Ory 身份仍然存在",
        object: "ory.identity",
        operator: "exists",
        params: { emailFrom: "data.adminEmail" },
      },
      {
        id: "db.admin.active",
        title: "预置管理员账号仍然可用",
        object: "db.admin",
        operator: "active",
        params: { emailFrom: "data.adminEmail" },
      },
    ],
  },
} satisfies StateCaseSpec<RegisterCaseData>;
