import { STATE_CASE_MODEL, type StateCaseSpec } from "../../_framework/types";
import type { RegisterCaseData } from "./_support/register.context";

export const registerApprovalLoginCase = {
  id: "auth.register.approve-login",
  title: "用户注册通过后可以再次登录 ORF",
  model: STATE_CASE_MODEL,
  tags: ["auth", "registration", "approval", "member", "happy-path"],

  data: {
    email: "orf-register-e2e@orf.local",
    password: "OrfRegisterE2E!2026",
    name: "ORF Register E2E",
    role: "member",
    adminEmail: "orf-register-admin-e2e@orf.local",
    adminPassword: "OrfRegisterAdminE2E!2026",
    adminName: "ORF Register Admin E2E",
    adminRole: "admin",
  },

  B: {
    description: "系统服务可用，浏览器未登录",
    assertions: [
      {
        id: "frontend.ready",
        title: "前端服务 应可用",
        object: "frontend.service",
        operator: "available",
      },
      {
        id: "backend.ready",
        title: "后端服务 应可用",
        object: "api.health",
        operator: "ok",
      },
      {
        id: "frontend.login_entry.accessible",
        title: "前端登录页入口 应可访问",
        object: "frontend.login_entry",
        operator: "accessible",
      },
      {
        id: "session.endpoint.accessible",
        title: "当前会话查询接口 应可访问",
        object: "auth.session",
        operator: "accessible",
      },
      {
        id: "db.ready",
        title: "ORF 数据库 应可连接",
        object: "db",
        operator: "ready",
      },
      {
        id: "db.schema.current",
        title: "ORF 数据库 schema 应为 当前测试版本",
        object: "db.schema",
        operator: "current",
      },
      {
        id: "ory.admin_public.ready",
        title: "Ory/Kratos Admin/Public API 应可访问",
        object: "ory.admin_public",
        operator: "ready",
      },
      {
        id: "session.unauthenticated",
        title: "当前会话 应为 未登录",
        object: "auth.session",
        operator: "unauthenticated",
      },
      {
        id: "cookie.absent",
        title: "当前浏览器 应不存在 Ory session cookie",
        object: "browser.cookie",
        operator: "absent",
      },
      {
        id: "storage.empty",
        title: "当前浏览器 storage 应不包含 登录态",
        object: "browser.auth_storage",
        operator: "empty",
      },
    ],
  },

  Setup: {
    description: "准备测试管理员和可注册邮箱，并进入注册模式",
    steps: [
      {
        id: "ory.sessions.revoke.registered_user.setup",
        title: "撤销注册测试登录身份可能残留的 Ory session",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        id: "ory.register_identity.delete.setup",
        title: "删除邮箱为 `orf-register-e2e@orf.local` 的注册测试登录身份",
        object: "ory.identity",
        operator: "delete_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        id: "db.registered_user.memberships.delete.setup",
        title: "删除注册测试用户的默认团队成员关系",
        object: "db.registered_user",
        operator: "delete_memberships",
        params: { emailFrom: "data.email" },
      },
      {
        id: "db.registered_user.delete.setup",
        title: "删除邮箱为 `orf-register-e2e@orf.local` 的注册测试用户",
        object: "db.registered_user",
        operator: "delete",
        params: { emailFrom: "data.email" },
      },
      {
        id: "ory.admin_identity.upsert",
        title:
          "准备邮箱为 `orf-register-admin-e2e@orf.local` 的测试管理员登录身份，并设置固定测试密码",
        object: "ory.identity",
        operator: "upsert_password",
        params: {
          emailFrom: "data.adminEmail",
          passwordFrom: "data.adminPassword",
          nameFrom: "data.adminName",
          saveAs: "adminIdentity",
        },
      },
      {
        id: "db.admin.upsert",
        title:
          "准备邮箱为 `orf-register-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的测试管理员用户",
        object: "db.admin",
        operator: "upsert",
        params: {
          emailFrom: "data.adminEmail",
          nameFrom: "data.adminName",
          identityIdFrom: "runtime.adminIdentity.id",
          saveAs: "adminUser",
        },
      },
      {
        id: "ory.sessions.revoke.admin",
        title: "撤销测试管理员登录身份可能残留的 Ory session",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.adminEmail" },
      },
      {
        id: "browser.clear",
        title: "清理浏览器状态",
        object: "browser",
        operator: "clear_state",
      },
      {
        id: "page.goto.auth",
        title: "打开 登录页",
        object: "page",
        operator: "goto",
        params: { path: "/auth" },
      },
      {
        id: "switch.register",
        title: "点击登录页的 `Register` 切换到注册模式",
        object: "page",
        operator: "click",
        params: { role: "button", name: "Register" },
      },
    ],
  },

  S0: {
    description: "注册表单可用，测试用户尚不存在，当前浏览器仍未登录",
    assertions: [
      {
        id: "url.auth",
        title: "当前页面 应为 注册页",
        object: "page.url",
        operator: "match",
        params: { pattern: "/auth$" },
      },
      {
        id: "heading.register.visible",
        title: '注册页标题 "Register" 应可见',
        object: "page",
        operator: "visible",
        params: { role: "heading", name: "Register" },
      },
      {
        id: "input.name.visible",
        title: "姓名输入框 应可见",
        object: "page",
        operator: "visible",
        params: { label: "Name" },
      },
      {
        id: "input.name.empty",
        title: "姓名输入框的值 应为空",
        object: "input",
        operator: "value",
        params: { label: "Name", value: "" },
      },
      {
        id: "input.email.visible",
        title: "邮箱输入框 应可见",
        object: "page",
        operator: "visible",
        params: { label: "Email" },
      },
      {
        id: "input.email.empty",
        title: "邮箱输入框的值 应为空",
        object: "input",
        operator: "value",
        params: { label: "Email", value: "" },
      },
      {
        id: "input.password.visible",
        title: "密码输入框 应可见",
        object: "page",
        operator: "visible",
        params: { label: "Password", exact: true },
      },
      {
        id: "input.password.empty",
        title: "密码输入框的值 应为空",
        object: "input",
        operator: "value",
        params: { label: "Password", exact: true, value: "" },
      },
      {
        id: "button.create_account.visible",
        title: '"Create Account" 注册操作 应可见',
        object: "page",
        operator: "visible",
        params: { role: "button", name: "Create Account" },
      },
      {
        id: "button.create_account.enabled",
        title: '"Create Account" 注册操作 应可点击',
        object: "page",
        operator: "enabled",
        params: { role: "button", name: "Create Account" },
      },
      {
        id: "session.unauthenticated",
        title: "当前会话 应为 未登录",
        object: "auth.session",
        operator: "unauthenticated",
      },
      {
        id: "ory.admin_identity.exists",
        title:
          "认证系统中 应存在 邮箱为 `orf-register-admin-e2e@orf.local` 的测试管理员登录身份",
        object: "ory.identity",
        operator: "exists",
        params: { emailFrom: "data.adminEmail" },
      },
      {
        id: "ory.admin_identity.password_available",
        title: "测试管理员登录身份 的密码凭据 应可用",
        object: "ory.identity",
        operator: "password_available",
        params: { emailFrom: "data.adminEmail" },
      },
      {
        id: "db.admin.active",
        title:
          "ORF 业务系统中 应存在 邮箱为 `orf-register-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的测试管理员用户",
        object: "db.admin",
        operator: "active",
        params: { emailFrom: "data.adminEmail" },
      },
      {
        id: "ory.register_identity.absent",
        title: "认证系统中 应不存在 注册测试登录身份",
        object: "ory.identity",
        operator: "absent",
        params: { emailFrom: "data.email" },
      },
      {
        id: "db.registered_user.absent",
        title: "ORF 业务系统中 应不存在 注册测试用户",
        object: "db.registered_user",
        operator: "absent",
        params: { emailFrom: "data.email" },
      },
    ],
  },

  Action: {
    description: "提交注册申请、管理员通过后再用注册用户登录",
    steps: [
      {
        id: "fill.name",
        title: "在姓名输入框输入 `ORF Register E2E`",
        object: "page",
        operator: "fill",
        params: { label: "Name", valueFrom: "data.name" },
      },
      {
        id: "fill.email",
        title: "在邮箱输入框输入 `orf-register-e2e@orf.local`",
        object: "page",
        operator: "fill",
        params: { label: "Email", valueFrom: "data.email" },
      },
      {
        id: "fill.password",
        title: "在密码输入框输入固定测试密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.password" },
      },
      {
        id: "capture.registration_response",
        title: '在点击 "Create Account" 注册操作前注册注册申请接口响应捕获',
        object: "api",
        operator: "capture_response",
        params: {
          urlEndsWith: "/api/auth/registration",
          method: "POST",
          saveAs: "registrationResponse",
        },
      },
      {
        id: "click.create_account",
        title: '点击 "Create Account" 注册操作',
        object: "page",
        operator: "click",
        params: { role: "button", name: "Create Account" },
      },
      {
        id: "approval_pending.visible",
        title: '"等待注册审核" 状态 应可见',
        object: "page.approval_pending",
        operator: "visible",
        params: { saveAs: "approvalPendingSeen" },
      },
      {
        id: "registration_response.record_user",
        title: "记录 注册响应用户",
        object: "api.registration_response",
        operator: "record_user",
        params: {
          responseFrom: "runtime.registrationResponse",
          saveAs: "registeredUser",
        },
      },
      {
        id: "db.registered_user.pending",
        title: "记录 注册测试用户的待审核状态",
        object: "db.registered_user",
        operator: "pending",
        params: { emailFrom: "data.email", saveAs: "pendingRegisteredUser" },
      },
      {
        id: "auth.logout.pending_user",
        title: "点击 `退出登录` 清理注册用户当前会话",
        object: "auth",
        operator: "logout",
      },
      {
        id: "browser.clear.pending_user",
        title: "清理注册用户浏览器状态",
        object: "browser",
        operator: "clear_state",
      },
      {
        id: "page.goto.auth.admin",
        title: "打开 登录页",
        object: "page",
        operator: "goto",
        params: { path: "/auth" },
      },
      {
        id: "fill.admin.email",
        title: "在邮箱输入框输入测试管理员邮箱",
        object: "page",
        operator: "fill",
        params: { label: "Email", valueFrom: "data.adminEmail" },
      },
      {
        id: "fill.admin.password",
        title: "在密码输入框输入测试管理员密码",
        object: "page",
        operator: "fill",
        params: {
          label: "Password",
          exact: true,
          valueFrom: "data.adminPassword",
        },
      },
      {
        id: "click.admin.sign_in",
        title: "点击 `Sign In` 登录操作",
        object: "page",
        operator: "click",
        params: { role: "button", name: "Sign In" },
      },
      {
        id: "session.admin.authenticated",
        title: "当前会话 应为 测试管理员已登录",
        object: "auth.session",
        operator: "authenticated",
        params: {
          emailFrom: "data.adminEmail",
          roleFrom: "data.adminRole",
          status: "active",
        },
      },
      {
        id: "page.goto.members",
        title: "打开 成员管理页面",
        object: "page",
        operator: "goto",
        params: { path: "/members" },
      },
      {
        id: "member_row.visible",
        title:
          "成员管理列表 应显示 `ORF Register E2E` 或 `orf-register-e2e@orf.local`",
        object: "page.member_row",
        operator: "visible",
        params: { emailFrom: "data.email", nameFrom: "data.name" },
      },
      {
        id: "capture.approval_response",
        title: "在点击 `通过` 操作前注册审批通过接口响应捕获",
        object: "api.registration_approval",
        operator: "capture_response",
        params: {
          userIdFrom: "runtime.registeredUser.id",
          saveAs: "approvalResponse",
        },
      },
      {
        id: "member_row.approve",
        title: "点击该用户行的 `通过` 操作",
        object: "page.member_row",
        operator: "approve",
        params: { emailFrom: "data.email", nameFrom: "data.name" },
      },
      {
        id: "approval_response.ok",
        title: "审批通过接口响应 应成功",
        object: "api.registration_approval",
        operator: "ok",
        params: { responseFrom: "runtime.approvalResponse" },
      },
      {
        id: "db.registered_user.active",
        title:
          "ORF 业务系统中 注册测试用户状态 应变为 `active`，且成员关系角色 应仍为 `member`",
        object: "db.registered_user",
        operator: "active",
        params: { emailFrom: "data.email" },
      },
      {
        id: "auth.logout.admin",
        title: "管理员退出登录",
        object: "auth",
        operator: "logout",
      },
      {
        id: "browser.clear.admin",
        title: "清理管理员浏览器状态",
        object: "browser",
        operator: "clear_state",
      },
      {
        id: "page.goto.auth.member",
        title: "打开 登录页",
        object: "page",
        operator: "goto",
        params: { path: "/auth" },
      },
      {
        id: "fill.member.email",
        title: "在邮箱输入框输入注册测试用户邮箱",
        object: "page",
        operator: "fill",
        params: { label: "Email", valueFrom: "data.email" },
      },
      {
        id: "fill.member.password",
        title: "在密码输入框输入注册测试用户密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.password" },
      },
      {
        id: "click.member.sign_in",
        title: "点击 `Sign In` 登录操作",
        object: "page",
        operator: "click",
        params: { role: "button", name: "Sign In" },
      },
    ],
  },

  S1: {
    description: "注册申请通过，注册用户可以作为普通成员登录",
    assertions: [
      {
        id: "registration_response.ok",
        title: "注册申请接口响应 应成功",
        object: "api.registration_response",
        operator: "ok",
        params: { responseFrom: "runtime.registrationResponse" },
      },
      {
        id: "registration_response.email_matches",
        title: "注册响应的用户邮箱 应匹配 测试邮箱",
        object: "api.registration_response",
        operator: "email_matches",
        params: {
          responseFrom: "runtime.registrationResponse",
          emailFrom: "data.email",
        },
      },
      {
        id: "registration_response.status_pending",
        title: "注册响应的用户状态 应为 `pending`",
        object: "api.registration_response",
        operator: "status",
        params: {
          responseFrom: "runtime.registrationResponse",
          status: "pending",
        },
      },
      {
        id: "registration_response.role_member",
        title: "注册响应的用户角色 应为 `member`",
        object: "api.registration_response",
        operator: "role",
        params: {
          responseFrom: "runtime.registrationResponse",
          roleFrom: "data.role",
        },
      },
      {
        id: "approval_pending.seen",
        title: '"等待注册审核" 提示 应曾可见',
        object: "runtime.boolean",
        operator: "true",
        params: { valueFrom: "runtime.approvalPendingSeen" },
      },
      {
        id: "db.registered_user.exists",
        title: "ORF 业务系统中 应存在 注册测试用户",
        object: "db.registered_user",
        operator: "exists",
        params: { emailFrom: "data.email" },
      },
      {
        id: "pending_user.status_recorded",
        title: "注册测试用户 的状态 应曾为 `pending`",
        object: "runtime.registered_user",
        operator: "status",
        params: {
          userFrom: "runtime.pendingRegisteredUser",
          emailFrom: "data.email",
          status: "pending",
        },
      },
      {
        id: "pending_user.role_recorded",
        title: "注册测试用户 的成员关系角色 应为 `member`",
        object: "runtime.registered_user",
        operator: "role",
        params: {
          userFrom: "runtime.pendingRegisteredUser",
          emailFrom: "data.email",
          roleFrom: "data.role",
        },
      },
      {
        id: "session.member.authenticated",
        title:
          "注册测试用户再次登录后的当前会话 应为 邮箱为 `orf-register-e2e@orf.local`、角色为 `member`、状态为 `active` 的已登录会话",
        object: "auth.session",
        operator: "authenticated",
        params: {
          emailFrom: "data.email",
          roleFrom: "data.role",
          status: "active",
        },
      },
      {
        id: "url.tasks",
        title: "再次登录后的当前页面 应为 ORF 已登录页面",
        object: "page.url",
        operator: "match",
        params: { pattern: "/(tasks|bounties)$" },
      },
      {
        id: "nav.visible",
        title: "主导航 应可见",
        object: "page",
        operator: "visible",
        params: { label: "主导航" },
      },
      {
        id: "current_user.visible",
        title: "当前用户入口 应可见",
        object: "page",
        operator: "visible",
        params: { label: "当前用户" },
      },
      {
        id: "members.nav.absent",
        title: "成员管理入口 应不对该普通成员可见",
        object: "page",
        operator: "count",
        params: { text: "成员管理", count: 0 },
      },
    ],
  },

  Clean: {
    description:
      "先切断页面请求源和认证身份源，再删除注册测试用户数据，恢复未登录基准状态",
    steps: [
      {
        id: "auth.logout",
        title: "撤销当前会话的 Ory session",
        object: "auth",
        operator: "logout",
      },
      {
        id: "page.runtime.stop",
        title: "当前页面离开 ORF 前端应用",
        object: "page.runtime",
        operator: "stop",
      },
      {
        id: "browser.clear",
        title: "清理浏览器状态",
        object: "browser",
        operator: "clear_state",
      },
      {
        id: "ory.sessions.revoke.registered_user",
        title: "撤销注册测试登录身份的残留 Ory session",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        id: "ory.register_identity.delete",
        title: "删除邮箱为 `orf-register-e2e@orf.local` 的注册测试登录身份",
        object: "ory.identity",
        operator: "delete_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        id: "db.registered_user.memberships.delete",
        title: "删除注册测试用户的默认团队成员关系",
        object: "db.registered_user",
        operator: "delete_memberships",
        params: { emailFrom: "data.email" },
      },
      {
        id: "db.registered_user.delete",
        title: "删除邮箱为 `orf-register-e2e@orf.local` 的注册测试用户",
        object: "db.registered_user",
        operator: "delete",
        params: { emailFrom: "data.email" },
      },
      {
        id: "ory.sessions.revoke.admin",
        title: "撤销测试管理员登录身份的残留 Ory session",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.adminEmail" },
      },
      {
        id: "ory.admin_identity.delete",
        title:
          "删除邮箱为 `orf-register-admin-e2e@orf.local` 的测试管理员登录身份",
        object: "ory.identity",
        operator: "delete_by_email",
        params: { emailFrom: "data.adminEmail" },
      },
      {
        id: "db.admin.memberships.delete",
        title: "删除测试管理员的默认团队成员关系",
        object: "db.admin",
        operator: "delete_memberships",
        params: { emailFrom: "data.adminEmail" },
      },
      {
        id: "db.admin.delete",
        title: "删除邮箱为 `orf-register-admin-e2e@orf.local` 的测试管理员用户",
        object: "db.admin",
        operator: "delete",
        params: { emailFrom: "data.adminEmail" },
      },
    ],
  },
} satisfies StateCaseSpec<RegisterCaseData>;
