import { STATE_CASE_MODEL, type StateCaseSpec } from "../../../../_framework/types";
import type { AdminAcceptLootCaseData } from "./_support/admin-accept-loot.context";

export const adminAcceptLootCase = {
  id: "target.admin-accept-loot",
  title: "管理员确认验收通过后目标进入已验收阶段",
  model: STATE_CASE_MODEL,
  tags: ["target", "loot", "acceptance", "admin"],

  data: {
    adminEmail: "orf-admin-accept-loot-e2e@orf.local",
    adminPassword: "OrfAdminAcceptLootE2E!2026",
    adminName: "ORF Admin Accept Loot E2E",
    adminRole: "admin",
    adminStatus: "active",
    memberEmail: "orf-member-accept-loot-e2e@orf.local",
    memberPassword: "OrfMemberAcceptLootE2E!2026",
    memberName: "ORF Member Accept Loot E2E",
    memberRole: "member",
    memberStatus: "active",
    targetPrefix: "E2E-TARGET-ADMIN-ACCEPT-LOOT",
    target: {
      title: "E2E-TARGET-ADMIN-ACCEPT-LOOT",
      stage: "goalFrozen",
      flowStatus: "submitted",
      finalDueOffsetDays: 8,
    },
    acceptedTarget: {
      title: "E2E-TARGET-ADMIN-ACCEPT-LOOT",
      stage: "goalFrozen",
      flowStatus: "accepted",
      finalDueOffsetDays: 8,
    },
    metric: {
      title: "E2E-METRIC-ADMIN-ACCEPT-LOOT",
      difficulty: "进阶",
      score: 30,
      claim: "completed",
      finalEvidence: "E2E-ADMIN-ACCEPT-LOOT-EVIDENCE：https://example.test/admin-accept-loot",
      acceptedResult: "completed",
    },
    finalLoot: {
      body: "E2E-ADMIN-ACCEPT-LOOT-BODY：普通成员已提交正式验收材料。",
      selfTestReportBody: "E2E-ADMIN-ACCEPT-LOOT-SELF-TEST：正式验收前已完成自测。",
    },
    alignmentKind: "acceptance",
    alignmentStatus: "requested",
    completedAlignmentStatus: "completed",
    alignmentNote: "E2E-ADMIN-ACCEPT-LOOT-ALIGNMENT-NOTE：等待管理员确认验收。",
    alignmentFeedback: "验收对齐完成，目标已验收。",
    acceptanceResult: "completed",
    reviewReason: "E2E-ADMIN-ACCEPT-LOOT-REASON：证据完整，同意验收通过。",
  },

  B: {
    description: "基准状态",
    assertions: [
      { source: { caseStepId: "B-1", method: "api" }, id: "frontend.ready", title: "前端服务 应可用", object: "frontend.service", operator: "available" },
      { source: { caseStepId: "B-2", method: "api" }, id: "backend.ready", title: "后端服务 应可用", object: "api.health", operator: "ok" },
      { source: { caseStepId: "B-3", method: "prisma" }, id: "db.ready", title: "ORF 数据库 应可连接", object: "db", operator: "ready" },
      { source: { caseStepId: "B-4", method: "api" }, id: "session.unauthenticated", title: "当前会话 应为 未登录", object: "auth.session", operator: "unauthenticated" },
      { source: { caseStepId: "B-5", method: "playwright" }, id: "storage.empty", title: "当前浏览器 应不保留本地登录态", object: "browser.auth_storage", operator: "empty" },
    ],
  },

  Setup: {
    description: "构造 S0",
    steps: [
      { source: { caseStepId: "Setup-1", method: "prisma" }, id: "db.objectives.delete_residue", title: "删除 本用例残留的目标标题前缀 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 对应的目标及其派生数据", object: "db.objectives_by_prefix", operator: "delete", params: { prefixFrom: "data.targetPrefix" } },
      { source: { caseStepId: "Setup-2", method: "api" }, id: "ory.admin_identity.upsert", title: "准备邮箱为 `orf-admin-accept-loot-e2e@orf.local`、使用固定测试密码的管理员登录身份", object: "ory.identity", operator: "upsert_password", params: { emailFrom: "data.adminEmail", nameFrom: "data.adminName", passwordFrom: "data.adminPassword", saveAs: "adminIdentity" } },
      { source: { caseStepId: "Setup-3", method: "prisma" }, id: "db.admin_user.upsert", title: "准备 角色为 `admin`、状态为 `active`、名称为 `ORF Admin Accept Loot E2E` 的本用例管理员用户", object: "db.user", operator: "upsert", params: { emailFrom: "data.adminEmail", nameFrom: "data.adminName", roleFrom: "data.adminRole", statusFrom: "data.adminStatus", identityIdFrom: "runtime.adminIdentity.id", saveAs: "adminUser" } },
      { source: { caseStepId: "Setup-4", method: "api" }, id: "ory.member_identity.upsert", title: "准备邮箱为 `orf-member-accept-loot-e2e@orf.local`、使用固定测试密码的普通成员登录身份", object: "ory.identity", operator: "upsert_password", params: { emailFrom: "data.memberEmail", nameFrom: "data.memberName", passwordFrom: "data.memberPassword", saveAs: "memberIdentity" } },
      { source: { caseStepId: "Setup-5", method: "prisma" }, id: "db.member_user.upsert", title: "准备 角色为 `member`、状态为 `active`、名称为 `ORF Member Accept Loot E2E` 的本用例普通成员用户", object: "db.user", operator: "upsert", params: { emailFrom: "data.memberEmail", nameFrom: "data.memberName", roleFrom: "data.memberRole", statusFrom: "data.memberStatus", identityIdFrom: "runtime.memberIdentity.id", saveAs: "memberUser" } },
      { source: { caseStepId: "Setup-6", method: "prisma" }, id: "db.submitted_objective.prepare", title: "准备 标题为 `E2E-TARGET-ADMIN-ACCEPT-LOOT`、阶段为 `goalFrozen`、流转状态为 `submitted`、最终验收截止日为运行时当前日期后 `8` 天、冻结时间存在、战利品提交时间存在、当前挑战者包含本用例普通成员的目标", object: "db.submitted_objective_fixture", operator: "prepare", params: { adminUserFrom: "runtime.adminUser", memberUserFrom: "runtime.memberUser", targetFrom: "data.target", saveAs: "objective" } },
      { source: { caseStepId: "Setup-7", method: "prisma" }, id: "db.metric.prepare_calibrated", title: "准备 归属于目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT`、口径为 `E2E-METRIC-ADMIN-ACCEPT-LOOT`、等级积分等级为 `进阶`、等级积分为 `30` 的指标", object: "db.metric", operator: "prepare_calibrated", params: { targetFrom: "data.target", metricFrom: "data.metric", memberUserFrom: "runtime.memberUser", saveAs: "metric" } },
      { source: { caseStepId: "Setup-8", method: "prisma" }, id: "db.objective_loot.prepare_final", title: "准备 归属于目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT`、提交人为本用例普通成员、完成说明为 `E2E-ADMIN-ACCEPT-LOOT-BODY：普通成员已提交正式验收材料。`、自测报告为 `E2E-ADMIN-ACCEPT-LOOT-SELF-TEST：正式验收前已完成自测。`、指标 `E2E-METRIC-ADMIN-ACCEPT-LOOT` 的完成主张为 `completed`、证据为 `E2E-ADMIN-ACCEPT-LOOT-EVIDENCE：https://example.test/admin-accept-loot` 的战利品正式提交记录", object: "db.objective_loot", operator: "prepare_final", params: { targetFrom: "data.target", metricFrom: "data.metric", finalLootFrom: "data.finalLoot", memberUserFrom: "runtime.memberUser", saveAs: "objectiveLoot" } },
      { source: { caseStepId: "Setup-9", method: "prisma" }, id: "db.alignment_request.prepare_acceptance", title: "准备 归属于目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT`、类型为 `acceptance`、状态为 `requested`、申请人为本用例普通成员、申请说明为 `E2E-ADMIN-ACCEPT-LOOT-ALIGNMENT-NOTE：等待管理员确认验收。` 的阶段对齐申请", object: "db.objective_alignment_request", operator: "prepare_acceptance", params: { targetFrom: "data.target", kindFrom: "data.alignmentKind", statusFrom: "data.alignmentStatus", noteFrom: "data.alignmentNote", memberUserFrom: "runtime.memberUser", saveAs: "alignmentRequest" } },
      { source: { caseStepId: "Setup-10", method: "prisma" }, id: "db.acceptance_review.delete_by_target", title: "确保 归属于目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 的验收记录不存在", object: "db.objective_acceptance_review", operator: "delete_by_target", params: { targetFrom: "data.target" } },
      { source: { caseStepId: "Setup-11", method: "playwright" }, id: "auth.login.admin", title: "使用 本用例管理员账号 登录 ORF", object: "page.auth", operator: "login", params: { emailFrom: "data.adminEmail", passwordFrom: "data.adminPassword" } },
    ],
  },

  S0: {
    description: "Action 前状态",
    assertions: [
      { source: { caseStepId: "S0-1", method: "api" }, id: "session.authenticated", title: "当前会话 应为 已登录", object: "auth.session", operator: "authenticated" },
      { source: { caseStepId: "S0-2", method: "api" }, id: "session.email", title: "当前会话用户邮箱 应为 `orf-admin-accept-loot-e2e@orf.local`", object: "auth.session.user_email", operator: "equals", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "S0-3", method: "api" }, id: "session.role", title: "当前会话用户角色 应为 `admin`", object: "auth.session.user_role", operator: "equals", params: { roleFrom: "data.adminRole" } },
      { source: { caseStepId: "S0-4", method: "api" }, id: "session.name", title: "当前会话用户名称 应为 `ORF Admin Accept Loot E2E`", object: "auth.session.user_name", operator: "equals", params: { nameFrom: "data.adminName" } },
      { source: { caseStepId: "S0-5", method: "prisma" }, id: "db.submitted_objective.exists", title: "应存在 标题为 `E2E-TARGET-ADMIN-ACCEPT-LOOT`、阶段为 `goalFrozen`、流转状态为 `submitted` 的目标", object: "db.submitted_objective_fixture", operator: "exists", params: { targetFrom: "data.target" } },
      { source: { caseStepId: "S0-6", method: "prisma" }, id: "db.submitted_objective.challenger_contains", title: "目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 的当前挑战者 应包含本用例普通成员", object: "db.submitted_objective_fixture", operator: "challenger_contains", params: { targetFrom: "data.target", memberUserFrom: "runtime.memberUser" } },
      { source: { caseStepId: "S0-7", method: "prisma" }, id: "db.submitted_objective.confirmed_at", title: "目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 的冻结时间 应存在", object: "db.submitted_objective_fixture", operator: "confirmed_at_exists", params: { targetFrom: "data.target" } },
      { source: { caseStepId: "S0-8", method: "prisma" }, id: "db.submitted_objective.loot_submitted_at", title: "目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 的战利品提交时间 应存在", object: "db.submitted_objective_fixture", operator: "loot_submitted_at_exists", params: { targetFrom: "data.target" } },
      { source: { caseStepId: "S0-9", method: "prisma" }, id: "db.submitted_objective.accepted_at_empty", title: "目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 的验收通过时间 应为空", object: "db.submitted_objective_fixture", operator: "accepted_at_empty", params: { targetFrom: "data.target" } },
      { source: { caseStepId: "S0-10", method: "prisma" }, id: "db.submitted_objective.accepted_result_empty", title: "目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 的验收结果 应为空", object: "db.submitted_objective_fixture", operator: "accepted_result_empty", params: { targetFrom: "data.target" } },
      { source: { caseStepId: "S0-11", method: "prisma" }, id: "db.metric.exists", title: "应存在 归属于目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT`、口径为 `E2E-METRIC-ADMIN-ACCEPT-LOOT`、等级积分等级为 `进阶`、等级积分为 `30` 的指标", object: "db.metric", operator: "exists_with_score", params: { targetFrom: "data.target", titleFrom: "data.metric.title", difficultyFrom: "data.metric.difficulty", scoreFrom: "data.metric.score" } },
      { source: { caseStepId: "S0-12", method: "prisma" }, id: "db.metric.accepted_result_empty", title: "指标 `E2E-METRIC-ADMIN-ACCEPT-LOOT` 的验收结果 应为空", object: "db.metric", operator: "accepted_result_empty", params: { titleFrom: "data.metric.title" } },
      { source: { caseStepId: "S0-13", method: "prisma" }, id: "db.objective_loot.exists", title: "应存在 归属于目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT`、提交人为本用例普通成员、完成说明为 `E2E-ADMIN-ACCEPT-LOOT-BODY：普通成员已提交正式验收材料。` 的战利品正式提交记录", object: "db.objective_loot", operator: "exists", params: { targetFrom: "data.target", finalLootFrom: "data.finalLoot", memberUserFrom: "runtime.memberUser" } },
      { source: { caseStepId: "S0-14", method: "prisma" }, id: "db.objective_loot.self_test", title: "目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 的战利品正式提交记录 应包含自测报告 `E2E-ADMIN-ACCEPT-LOOT-SELF-TEST：正式验收前已完成自测。`", object: "db.objective_loot", operator: "self_test", params: { targetFrom: "data.target", selfTestReportBodyFrom: "data.finalLoot.selfTestReportBody" } },
      { source: { caseStepId: "S0-15", method: "prisma" }, id: "db.objective_loot.metric_claim", title: "目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 的战利品正式提交记录 应包含指标 `E2E-METRIC-ADMIN-ACCEPT-LOOT` 的完成主张 `completed` 和证据 `E2E-ADMIN-ACCEPT-LOOT-EVIDENCE：https://example.test/admin-accept-loot`", object: "db.objective_loot", operator: "metric_claim", params: { targetFrom: "data.target", metricFrom: "data.metric" } },
      { source: { caseStepId: "S0-16", method: "prisma" }, id: "db.alignment_request.exists", title: "应存在 归属于目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT`、类型为 `acceptance`、状态为 `requested`、申请人为本用例普通成员的阶段对齐申请", object: "db.objective_alignment_request", operator: "exists", params: { targetFrom: "data.target", kindFrom: "data.alignmentKind", statusFrom: "data.alignmentStatus", memberUserFrom: "runtime.memberUser" } },
      { source: { caseStepId: "S0-17", method: "prisma" }, id: "db.acceptance_review.count_zero", title: "目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 的验收记录数量 应为 `0`", object: "db.objective_acceptance_review", operator: "count", params: { targetFrom: "data.target", count: 0 } },
    ],
  },

  Action: {
    description: "被测业务动作",
    steps: [
      { source: { caseStepId: "Action-1", method: "playwright" }, id: "admin.open_my_challenges", title: "管理员打开 我的挑战", object: "page.challenge", operator: "open_my_challenges" },
      { source: { caseStepId: "Action-2", method: "playwright" }, id: "objective.visible", title: "我的挑战列表 应显示目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT`", object: "page.challenge_objectives", operator: "visible_title", params: { titleFrom: "data.target.title" } },
      { source: { caseStepId: "Action-3", method: "playwright" }, id: "objective.status.submitted", title: "目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 的状态 应显示为 待验收", object: "page.challenge_objective", operator: "status_visible", params: { titleFrom: "data.target.title", statusLabel: "待验收" } },
      { source: { caseStepId: "Action-4", method: "playwright" }, id: "alignment.acceptance.visible", title: "目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 的阶段对齐区域 应显示 `验收对齐`", object: "page.objective_alignment", operator: "acceptance_visible", params: { targetTitleFrom: "data.target.title" } },
      { source: { caseStepId: "Action-5", method: "playwright" }, id: "acceptance.open", title: "点击目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 的 \"去验收\" 操作", object: "page.acceptance_review", operator: "open_from_alignment", params: { targetTitleFrom: "data.target.title" } },
      { source: { caseStepId: "Action-6", method: "playwright" }, id: "acceptance.page.loaded", title: "等待 验收战利品页面加载完成", object: "page.acceptance_review", operator: "loaded", params: { targetTitleFrom: "data.target.title" } },
      { source: { caseStepId: "Action-7", method: "playwright" }, id: "acceptance.material.visible", title: "页面 应显示战利品正式提交材料 `E2E-ADMIN-ACCEPT-LOOT-BODY：普通成员已提交正式验收材料。`", object: "page.acceptance_review", operator: "material_visible", params: { bodyFrom: "data.finalLoot.body" } },
      { source: { caseStepId: "Action-8", method: "playwright" }, id: "acceptance.self_test.visible", title: "页面 应显示自测报告 `E2E-ADMIN-ACCEPT-LOOT-SELF-TEST：正式验收前已完成自测。`", object: "page.acceptance_review", operator: "self_test_visible", params: { selfTestReportBodyFrom: "data.finalLoot.selfTestReportBody" } },
      { source: { caseStepId: "Action-9", method: "playwright" }, id: "acceptance.evidence.visible", title: "页面 应显示指标 `E2E-METRIC-ADMIN-ACCEPT-LOOT` 的证据 `E2E-ADMIN-ACCEPT-LOOT-EVIDENCE：https://example.test/admin-accept-loot`", object: "page.acceptance_review", operator: "evidence_visible", params: { metricTitleFrom: "data.metric.title", evidenceFrom: "data.metric.finalEvidence" } },
      { source: { caseStepId: "Action-10", method: "playwright" }, id: "acceptance.result.select_completed", title: "在指标 `E2E-METRIC-ADMIN-ACCEPT-LOOT` 的 \"验收结论\" 控件中选择 `完成`", object: "page.acceptance_review", operator: "select_metric_result", params: { metricTitleFrom: "data.metric.title", resultLabel: "完成" } },
      { source: { caseStepId: "Action-11", method: "playwright" }, id: "acceptance.summary.visible", title: "页面 应显示 `目标将验收通过`", object: "page.acceptance_review", operator: "summary_visible", params: { summary: "目标将验收通过" } },
      { source: { caseStepId: "Action-12", method: "playwright" }, id: "acceptance.reason.fill", title: "在 \"验收说明\" 输入框输入 `E2E-ADMIN-ACCEPT-LOOT-REASON：证据完整，同意验收通过。`", object: "page.acceptance_review", operator: "fill_reason", params: { reasonFrom: "data.reviewReason" } },
      { source: { caseStepId: "Action-13", method: "playwright" }, id: "acceptance.submit", title: "点击 \"确认验收通过\" 操作", object: "page.acceptance_review", operator: "submit", params: { acceptedTargetFrom: "data.acceptedTarget", metricFrom: "data.metric", acceptanceResultFrom: "data.acceptanceResult", reviewReasonFrom: "data.reviewReason", alignmentFeedbackFrom: "data.alignmentFeedback", adminUserFrom: "runtime.adminUser" } },
    ],
  },

  S1: {
    description: "Action 后状态",
    assertions: [
      { source: { caseStepId: "S1-1", method: "playwright" }, id: "toast.acceptance_review_completed", title: "页面 应提示 战利品验收处理已完成", object: "page.challenge_toast", operator: "acceptance_review_completed" },
      { source: { caseStepId: "S1-2", method: "playwright" }, id: "challenge.page.url", title: "页面 应进入 我的挑战", object: "page.challenge", operator: "url" },
      { source: { caseStepId: "S1-3", method: "playwright" }, id: "scope.all.selected", title: "\"所有挑战\" 视图 应处于选中状态", object: "page.challenge_scope", operator: "selected", params: { label: "所有挑战" } },
      { source: { caseStepId: "S1-4", method: "playwright" }, id: "objective.visible", title: "我的挑战列表 应显示目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT`", object: "page.challenge_objectives", operator: "visible_title", params: { titleFrom: "data.target.title" } },
      { source: { caseStepId: "S1-5", method: "playwright" }, id: "objective.status.accepted", title: "目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 的状态 应显示为 已验收", object: "page.challenge_objective", operator: "status_visible", params: { titleFrom: "data.target.title", statusLabel: "已验收" } },
      { source: { caseStepId: "S1-6", method: "playwright" }, id: "alignment.acceptance.hidden", title: "目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 的阶段对齐区域 应不显示 `验收对齐`", object: "page.objective_alignment", operator: "acceptance_hidden", params: { targetTitleFrom: "data.target.title" } },
      { source: { caseStepId: "S1-7", method: "api" }, id: "api.all_challenges.contains_objective", title: "所有挑战数据 应包含目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT`", object: "api.all_challenges", operator: "contains_objective", params: { titleFrom: "data.target.title" } },
      { source: { caseStepId: "S1-8", method: "api" }, id: "api.all_challenges.objective_stage_flow", title: "所有挑战数据中目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 的阶段 应为 `goalFrozen`，流转状态 应为 `accepted`", object: "api.all_challenges", operator: "objective_stage_flow", params: { targetFrom: "data.acceptedTarget" } },
      { source: { caseStepId: "S1-9", method: "api" }, id: "api.all_challenges.accepted_at", title: "所有挑战数据中目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 的验收通过时间 应存在", object: "api.all_challenges", operator: "accepted_at_exists", params: { titleFrom: "data.target.title" } },
      { source: { caseStepId: "S1-10", method: "api" }, id: "api.all_challenges.accepted_result", title: "所有挑战数据中目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 的验收结果 应为 `completed`", object: "api.all_challenges", operator: "accepted_result", params: { titleFrom: "data.target.title", acceptanceResultFrom: "data.acceptanceResult" } },
      { source: { caseStepId: "S1-11", method: "api" }, id: "api.all_challenges.acceptance_review", title: "所有挑战数据中目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 应包含审核人为本用例管理员、验收结果为 `completed`、验收说明为 `E2E-ADMIN-ACCEPT-LOOT-REASON：证据完整，同意验收通过。` 的验收记录", object: "api.all_challenges", operator: "contains_acceptance_review", params: { targetTitleFrom: "data.target.title", metricFrom: "data.metric", acceptanceResultFrom: "data.acceptanceResult", reasonFrom: "data.reviewReason", adminUserFrom: "runtime.adminUser" } },
      { source: { caseStepId: "S1-12", method: "api" }, id: "api.all_challenges.completed_alignment", title: "所有挑战数据中目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 应包含类型为 `acceptance`、状态为 `completed`、管理员反馈为 `验收对齐完成，目标已验收。` 的阶段对齐申请", object: "api.all_challenges", operator: "contains_completed_alignment_request", params: { targetTitleFrom: "data.target.title", kindFrom: "data.alignmentKind", statusFrom: "data.completedAlignmentStatus", feedbackFrom: "data.alignmentFeedback", adminUserFrom: "runtime.adminUser" } },
      { source: { caseStepId: "S1-13", method: "prisma" }, id: "db.accepted_objective.exists", title: "标题为 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 的目标阶段 应为 `goalFrozen`，流转状态 应为 `accepted`", object: "db.submitted_objective_fixture", operator: "accepted", params: { targetFrom: "data.acceptedTarget" } },
      { source: { caseStepId: "S1-14", method: "prisma" }, id: "db.accepted_objective.accepted_at", title: "目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 的验收通过时间 应存在", object: "db.submitted_objective_fixture", operator: "accepted_at_exists", params: { targetFrom: "data.acceptedTarget" } },
      { source: { caseStepId: "S1-15", method: "prisma" }, id: "db.accepted_objective.accepted_result", title: "目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 的验收结果 应为 `completed`", object: "db.submitted_objective_fixture", operator: "accepted_result", params: { targetFrom: "data.acceptedTarget", acceptanceResultFrom: "data.acceptanceResult" } },
      { source: { caseStepId: "S1-16", method: "prisma" }, id: "db.metric.accepted_result", title: "指标 `E2E-METRIC-ADMIN-ACCEPT-LOOT` 的验收结果 应为 `completed`", object: "db.metric", operator: "accepted_result", params: { titleFrom: "data.metric.title", acceptedResultFrom: "data.metric.acceptedResult" } },
      { source: { caseStepId: "S1-17", method: "prisma" }, id: "db.acceptance_review.exists", title: "应存在 归属于目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT`、审核人为本用例管理员、验收结果为 `completed`、验收说明为 `E2E-ADMIN-ACCEPT-LOOT-REASON：证据完整，同意验收通过。` 的验收记录", object: "db.objective_acceptance_review", operator: "exists", params: { targetFrom: "data.acceptedTarget", metricFrom: "data.metric", acceptanceResultFrom: "data.acceptanceResult", reasonFrom: "data.reviewReason", adminUserFrom: "runtime.adminUser" } },
      { source: { caseStepId: "S1-18", method: "prisma" }, id: "db.acceptance_review.metric_result", title: "目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 的验收记录 应包含指标 `E2E-METRIC-ADMIN-ACCEPT-LOOT` 的验收结果 `completed`", object: "db.objective_acceptance_review", operator: "metric_result", params: { targetFrom: "data.acceptedTarget", metricFrom: "data.metric" } },
      { source: { caseStepId: "S1-19", method: "prisma" }, id: "db.alignment_request.completed", title: "应存在 归属于目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT`、类型为 `acceptance`、状态为 `completed`、管理员反馈为 `验收对齐完成，目标已验收。`、处理人为本用例管理员的阶段对齐申请", object: "db.objective_alignment_request", operator: "completed", params: { targetFrom: "data.acceptedTarget", kindFrom: "data.alignmentKind", statusFrom: "data.completedAlignmentStatus", feedbackFrom: "data.alignmentFeedback", adminUserFrom: "runtime.adminUser" } },
      { source: { caseStepId: "S1-20", method: "prisma" }, id: "db.alignment_request.open_count_zero", title: "目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 的 `acceptance` 类型待处理阶段对齐申请数量 应为 `0`", object: "db.objective_alignment_request", operator: "open_count", params: { targetFrom: "data.acceptedTarget", kindFrom: "data.alignmentKind", count: 0 } },
      { source: { caseStepId: "S1-21", method: "prisma" }, id: "db.objective_loot.exists_after_acceptance", title: "应存在 归属于目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT`、提交人为本用例普通成员、完成说明为 `E2E-ADMIN-ACCEPT-LOOT-BODY：普通成员已提交正式验收材料。` 的战利品正式提交记录", object: "db.objective_loot", operator: "exists", params: { targetFrom: "data.acceptedTarget", finalLootFrom: "data.finalLoot", memberUserFrom: "runtime.memberUser" } },
      { source: { caseStepId: "S1-22", method: "prisma" }, id: "db.accepted_objective.challenger_still_contains", title: "目标 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 的当前挑战者 应仍包含本用例普通成员", object: "db.submitted_objective_fixture", operator: "challenger_contains", params: { targetFrom: "data.acceptedTarget", memberUserFrom: "runtime.memberUser" } },
    ],
  },

  Clean: {
    description: "恢复 B",
    steps: [
      { source: { caseStepId: "Clean-1", method: "prisma" }, id: "db.objectives.delete_created", title: "删除 本用例创建的目标标题前缀 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 对应的目标及其派生数据", object: "db.objectives_by_prefix", operator: "delete", params: { prefixFrom: "data.targetPrefix" } },
      { source: { caseStepId: "Clean-2", method: "api" }, id: "auth.logout", title: "注销当前管理员登录会话", object: "auth", operator: "logout" },
      { source: { caseStepId: "Clean-3", method: "playwright" }, id: "browser.clear", title: "移除当前浏览器中的残留登录态", object: "browser", operator: "clear_state" },
      { source: { caseStepId: "Clean-4", method: "api" }, id: "ory.admin_identity.delete", title: "删除 本用例管理员登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-5", method: "api" }, id: "ory.member_identity.delete", title: "删除 本用例普通成员登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-6", method: "prisma" }, id: "db.admin_user.delete", title: "删除 本用例管理员用户", object: "db.user", operator: "delete", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-7", method: "prisma" }, id: "db.member_user.delete", title: "删除 本用例普通成员用户", object: "db.user", operator: "delete", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-8", method: "prisma" }, id: "db.objectives.absent", title: "应不存在 标题前缀为 `E2E-TARGET-ADMIN-ACCEPT-LOOT` 的目标", object: "db.objectives_by_prefix", operator: "absent", params: { prefixFrom: "data.targetPrefix" } },
      { source: { caseStepId: "Clean-9", method: "prisma" }, id: "db.metric.absent", title: "应不存在 口径为 `E2E-METRIC-ADMIN-ACCEPT-LOOT` 的指标", object: "db.metric", operator: "absent", params: { titleFrom: "data.metric.title" } },
      { source: { caseStepId: "Clean-10", method: "api" }, id: "ory.admin_identity.absent", title: "邮箱为 `orf-admin-accept-loot-e2e@orf.local` 的管理员登录身份 应不存在", object: "ory.identity", operator: "absent", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-11", method: "api" }, id: "ory.member_identity.absent", title: "邮箱为 `orf-member-accept-loot-e2e@orf.local` 的普通成员登录身份 应不存在", object: "ory.identity", operator: "absent", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-12", method: "prisma" }, id: "db.admin_user.absent", title: "邮箱为 `orf-admin-accept-loot-e2e@orf.local` 的管理员用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-13", method: "prisma" }, id: "db.member_user.absent", title: "邮箱为 `orf-member-accept-loot-e2e@orf.local` 的普通成员用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-14", method: "api" }, id: "session.unauthenticated", title: "当前会话 应为 未登录", object: "auth.session", operator: "unauthenticated" },
    ],
  },
} satisfies StateCaseSpec<AdminAcceptLootCaseData>;
