import { STATE_CASE_MODEL, type StateCaseSpec } from "../../_framework/types";
import type { AdminFreezeObjectiveCaseData } from "./_support/admin-freeze-objective.context";

export const adminFreezeObjectiveCase = {
  id: "implementation.admin-freeze-objective",
  title: "管理员可以冻结目标进入实施阶段",
  model: STATE_CASE_MODEL,
  tags: ["implementation", "objective", "freeze", "admin", "happy-path"],

  data: {
    email: "orf-admin-freeze-objective-e2e@orf.local",
    password: "OrfAdminFreezeObjectiveE2E!2026",
    name: "ORF Admin Freeze Objective E2E",
    role: "admin",
    objectiveId: "obj-testd-admin-freeze-objective",
    objectiveTitle: "E2E-ADMIN-FREEZE-OBJECTIVE: 目标前置",
    freezeResultTitle: "E2E-FREEZE-RESULT: 冻结前置指标",
    freezeMetricName: "E2E 冻结目标前置指标完成率",
  },

  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      {
        source: { caseStepId: "B-1", method: "api" },
        id: "frontend.ready",
        title: "前端服务 应可用",
        object: "frontend.service",
        operator: "available",
      },
      {
        source: { caseStepId: "B-2", method: "api" },
        id: "backend.ready",
        title: "后端服务 应可用",
        object: "api.health",
        operator: "ok",
      },
      {
        source: { caseStepId: "B-3", method: "api" },
        id: "frontend.login_entry.accessible",
        title: "前端登录页入口 应可访问",
        object: "frontend.login_entry",
        operator: "accessible",
      },
      {
        source: { caseStepId: "B-4", method: "api" },
        id: "session.endpoint.accessible",
        title: "当前会话查询能力 应可用",
        object: "auth.session",
        operator: "accessible",
      },
      {
        source: { caseStepId: "B-5", method: "prisma" },
        id: "db.ready",
        title: "ORF 数据库 应可连接",
        object: "db",
        operator: "ready",
      },
      {
        source: { caseStepId: "B-6", method: "prisma" },
        id: "db.schema.current",
        title: "ORF 数据库 schema 应为 当前测试版本",
        object: "db.schema",
        operator: "current",
      },
      {
        source: { caseStepId: "B-7", method: "api" },
        id: "ory.admin_public.ready",
        title: "Ory/Kratos 认证服务的管理和公共访问能力 应可用",
        object: "ory.admin_public",
        operator: "ready",
      },
      {
        source: { caseStepId: "B-8", method: "api" },
        id: "session.unauthenticated",
        title: "当前会话 应为 未登录",
        object: "auth.session",
        operator: "unauthenticated",
      },
      {
        source: { caseStepId: "B-9", method: "playwright" },
        id: "cookie.absent",
        title: "当前浏览器 应不存在 Ory 登录会话 cookie",
        object: "browser.cookie",
        operator: "absent",
      },
      {
        source: { caseStepId: "B-10", method: "playwright" },
        id: "storage.empty",
        title: "当前浏览器 应不保留本地登录态",
        object: "browser.auth_storage",
        operator: "empty",
      },
    ],
  },

  Setup: {
    description: "准备管理员账号、本用例独占重估目标和冻结前置指标，登录管理员并进入所有挑战视图",
    steps: [
      {
        source: { caseStepId: "Setup-1", method: "prisma" },
        id: "db.freeze_result.delete_residue",
        title: "删除可能残留的本用例冻结前置指标",
        object: "db.freeze_result",
        operator: "delete",
        params: { titleFrom: "data.freezeResultTitle" },
      },
      {
        source: { caseStepId: "Setup-2", method: "prisma" },
        id: "db.objective.delete_residue",
        title: "删除可能残留的本用例目标及其派生数据",
        object: "db.objective",
        operator: "delete_by_title",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Setup-3", method: "api" },
        id: "ory.admin_identity.upsert",
        title: "准备邮箱为 `orf-admin-freeze-objective-e2e@orf.local`、使用固定测试密码的管理员登录身份",
        object: "ory.identity",
        operator: "upsert_password",
        params: {
          emailFrom: "data.email",
          nameFrom: "data.name",
          passwordFrom: "data.password",
          saveAs: "adminIdentity",
        },
      },
      {
        source: { caseStepId: "Setup-4", method: "prisma" },
        id: "db.admin.upsert",
        title: "准备邮箱为 `orf-admin-freeze-objective-e2e@orf.local`、角色为 `admin`、状态为 `active` 的管理员用户和默认团队成员关系",
        object: "db.user",
        operator: "upsert",
        params: {
          emailFrom: "data.email",
          nameFrom: "data.name",
          roleFrom: "data.role",
          status: "active",
          identityIdFrom: "runtime.adminIdentity.id",
          saveAs: "adminUser",
        },
      },
      {
        source: { caseStepId: "Setup-5", method: "prisma" },
        id: "db.objective.upsert_freeze_target",
        title: "创建标题为 `E2E-ADMIN-FREEZE-OBJECTIVE: 目标前置`、流转状态为 `reestimating`、阶段为 `orfReestimate` 的本用例冻结目标",
        object: "db.objective",
        operator: "upsert",
        params: {
          idFrom: "data.objectiveId",
          titleFrom: "data.objectiveTitle",
          teamIdFrom: "runtime.adminUser.teamId",
          stage: "orfReestimate",
          flowStatus: "reestimating",
          status: "Draft",
          saveAs: "fixtureObjective",
        },
      },
      {
        source: { caseStepId: "Setup-6", method: "prisma" },
        id: "db.freeze_target.from_objective",
        title: "记录 本用例冻结目标",
        object: "db.freeze_target",
        operator: "from_objective",
        params: { objectiveIdFrom: "runtime.fixtureObjective.id", saveAs: "freezeTarget" },
      },
      {
        source: { caseStepId: "Setup-7", method: "prisma" },
        id: "db.freeze_target.prepare",
        title: "清空本用例冻结目标的已确认时间并保持重估状态",
        object: "db.freeze_target",
        operator: "prepare",
        params: { targetFrom: "runtime.freezeTarget" },
      },
      {
        source: { caseStepId: "Setup-8", method: "prisma" },
        id: "db.freeze_result.create",
        title: "为本用例冻结目标创建标题为 `E2E-FREEZE-RESULT: 冻结前置指标` 的冻结前置指标",
        object: "db.freeze_result",
        operator: "create",
        params: {
          targetFrom: "runtime.freezeTarget",
          titleFrom: "data.freezeResultTitle",
          metricNameFrom: "data.freezeMetricName",
          saveAs: "freezeResult",
        },
      },
      {
        source: { caseStepId: "Setup-9", method: "api" },
        id: "ory.admin_sessions.revoke",
        title: "撤销管理员登录身份可能残留的登录会话",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Setup-10", method: "playwright" },
        id: "browser.clear",
        title: "移除当前浏览器中的残留登录态",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "Setup-11", method: "playwright" },
        id: "page.goto.auth",
        title: "打开 ORF 登录页",
        object: "page",
        operator: "goto",
        params: { path: "/auth" },
      },
      {
        source: { caseStepId: "Setup-12", method: "playwright" },
        id: "fill.email",
        title: "在邮箱输入框输入管理员固定测试邮箱",
        object: "page",
        operator: "fill",
        params: { label: "Email", valueFrom: "data.email" },
      },
      {
        source: { caseStepId: "Setup-13", method: "playwright" },
        id: "fill.password",
        title: "在密码输入框输入管理员固定测试密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.password" },
      },
      {
        source: { caseStepId: "Setup-14", method: "playwright" },
        id: "click.sign_in",
        title: "点击 \"Sign In\" 登录操作",
        object: "page",
        operator: "click",
        params: { role: "button", name: "Sign In" },
      },
      {
        source: { caseStepId: "Setup-15", method: "api" },
        id: "session.admin.authenticated",
        title: "当前会话 应为 管理员的已登录会话",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      {
        source: { caseStepId: "Setup-16", method: "playwright" },
        id: "page.goto.tasks",
        title: "打开 挑战工作台",
        object: "page",
        operator: "goto",
        params: { path: "/tasks" },
      },
      {
        source: { caseStepId: "Setup-17", method: "playwright" },
        id: "scope.all",
        title: "切换到 \"所有挑战\" 视图",
        object: "page",
        operator: "click",
        params: { role: "button", name: "所有挑战" },
      },
    ],
  },

  S0: {
    description: "管理员已登录并位于挑战工作台，本用例目标可见且冻结操作可用",
    assertions: [
      {
        source: { caseStepId: "S0-1", method: "api" },
        id: "session.admin.authenticated",
        title: "当前会话 应为 邮箱为 `orf-admin-freeze-objective-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      {
        source: { caseStepId: "S0-2", method: "playwright" },
        id: "url.tasks",
        title: "当前页面 应为 挑战工作台",
        object: "page.url",
        operator: "match",
        params: { pattern: "/tasks$" },
      },
      {
        source: { caseStepId: "S0-3", method: "playwright" },
        id: "freeze_target.visible",
        title: "本用例冻结目标面板 应可见",
        object: "page.freeze_target",
        operator: "visible",
        params: { targetFrom: "runtime.freezeTarget" },
      },
      {
        source: { caseStepId: "S0-4", method: "playwright" },
        id: "freeze_target.freeze.enabled",
        title: "本用例冻结目标的 \"冻结\" 操作 应可点击",
        object: "page.freeze_target",
        operator: "freeze_enabled",
        params: { targetFrom: "runtime.freezeTarget" },
      },
      {
        source: { caseStepId: "S0-5", method: "prisma" },
        id: "db.freeze_target.reestimating",
        title: "本用例冻结目标 应处于 reestimating 状态",
        object: "db.freeze_target",
        operator: "reestimating",
        params: { targetFrom: "runtime.freezeTarget" },
      },
      {
        source: { caseStepId: "S0-6", method: "prisma" },
        id: "db.freeze_result.present",
        title: "本用例冻结目标 应存在 冻结前置指标",
        object: "db.freeze_result",
        operator: "present",
        params: { targetFrom: "runtime.freezeTarget", resultFrom: "runtime.freezeResult" },
      },
    ],
  },

  Action: {
    description: "管理员通过页面冻结目标",
    steps: [
      {
        source: { caseStepId: "Action-1", method: "api" },
        id: "capture.freeze_response",
        title: "监听冻结目标请求响应",
        object: "api.objective_freeze",
        operator: "capture_response",
        params: { targetFrom: "runtime.freezeTarget", saveAs: "freezeResponse" },
      },
      {
        source: { caseStepId: "Action-2", method: "playwright" },
        id: "click.freeze",
        title: "点击 本用例冻结目标的 \"冻结\" 操作",
        object: "page.freeze_target",
        operator: "freeze",
        params: { targetFrom: "runtime.freezeTarget" },
      },
      {
        source: { caseStepId: "Action-3", method: "api" },
        id: "freeze_response.record",
        title: "记录 冻结目标结果中的目标",
        object: "api.objective_freeze_response",
        operator: "record_objective",
        params: { responseFrom: "runtime.freezeResponse", saveAs: "frozenObjective" },
      },
    ],
  },

  S1: {
    description: "目标已经冻结并显示为实施阶段状态，管理员仍保持登录",
    assertions: [
      {
        source: { caseStepId: "S1-1", method: "api" },
        id: "freeze_response.ok",
        title: "冻结目标结果 应成功",
        object: "api.response",
        operator: "ok",
        params: { responseFrom: "runtime.freezeResponse", status: 200 },
      },
      {
        source: { caseStepId: "S1-2", method: "api" },
        id: "frozen_objective.matches",
        title: "冻结目标结果中的目标 应属于本用例目标，流转状态为 `frozen`、阶段为 `goalFrozen` 且冻结确认时间已存在",
        object: "api.objective_freeze_response",
        operator: "matches",
        params: { objectiveFrom: "runtime.frozenObjective", targetFrom: "runtime.freezeTarget" },
      },
      {
        source: { caseStepId: "S1-3", method: "prisma" },
        id: "db.freeze_target.frozen",
        title: "本用例冻结目标 在数据库中 应为 流转状态 `frozen`、阶段 `goalFrozen` 且冻结确认时间已存在",
        object: "db.freeze_target",
        operator: "frozen",
        params: { targetFrom: "runtime.freezeTarget" },
      },
      {
        source: { caseStepId: "S1-4", method: "playwright" },
        id: "page.freeze_target.frozen_status",
        title: "本用例冻结目标面板 应显示 \"已冻结\"",
        object: "page.freeze_target",
        operator: "frozen_status_visible",
        params: { targetFrom: "runtime.freezeTarget" },
      },
      {
        source: { caseStepId: "S1-5", method: "api" },
        id: "session.admin.still_authenticated",
        title: "当前会话 应仍为 管理员的已登录会话",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
    ],
  },

  Clean: {
    description: "删除冻结前置指标、目标、管理员账号和浏览器运行态",
    steps: [
      {
        source: { caseStepId: "Clean-1", method: "prisma" },
        id: "db.freeze_result.delete",
        title: "删除 本用例创建的冻结前置指标",
        object: "db.freeze_result",
        operator: "delete",
        params: { titleFrom: "data.freezeResultTitle", resultFrom: "runtime.freezeResult" },
      },
      {
        source: { caseStepId: "Clean-2", method: "prisma" },
        id: "db.objective.delete",
        title: "删除 本用例冻结目标及其派生数据",
        object: "db.objective",
        operator: "delete_by_title",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Clean-3", method: "api" },
        id: "auth.logout",
        title: "注销当前登录会话",
        object: "auth",
        operator: "logout",
      },
      {
        source: { caseStepId: "Clean-4", method: "playwright" },
        id: "page.runtime.stop",
        title: "离开当前 ORF 前端页面",
        object: "page.runtime",
        operator: "stop",
      },
      {
        source: { caseStepId: "Clean-5", method: "playwright" },
        id: "browser.clear",
        title: "移除当前浏览器中的残留登录态",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "Clean-6", method: "api" },
        id: "ory.admin_sessions.revoke",
        title: "撤销管理员登录身份的残留登录会话",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-7", method: "api" },
        id: "ory.admin_identity.delete",
        title: "删除邮箱为 `orf-admin-freeze-objective-e2e@orf.local` 的管理员登录身份",
        object: "ory.identity",
        operator: "delete_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-8", method: "prisma" },
        id: "db.admin.memberships.delete",
        title: "删除管理员用户的默认团队成员关系",
        object: "db.user",
        operator: "delete_memberships",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-9", method: "prisma" },
        id: "db.admin.delete",
        title: "删除邮箱为 `orf-admin-freeze-objective-e2e@orf.local` 的管理员用户",
        object: "db.user",
        operator: "delete",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-10", method: "prisma" },
        id: "db.freeze_result.absent",
        title: "应不存在 标题为 `E2E-FREEZE-RESULT: 冻结前置指标` 的冻结前置指标",
        object: "db.result",
        operator: "absent",
        params: { titleFrom: "data.freezeResultTitle" },
      },
      {
        source: { caseStepId: "Clean-11", method: "prisma" },
        id: "db.objective.absent",
        title: "应不存在 标题为 `E2E-ADMIN-FREEZE-OBJECTIVE: 目标前置` 的测试目标",
        object: "db.objective",
        operator: "absent",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Clean-12", method: "prisma" },
        id: "db.admin.absent",
        title: "应不存在 邮箱为 `orf-admin-freeze-objective-e2e@orf.local` 的管理员用户",
        object: "db.user",
        operator: "absent",
        params: { emailFrom: "data.email" },
      },
    ],
  },
} satisfies StateCaseSpec<AdminFreezeObjectiveCaseData>;
