import { STATE_CASE_MODEL, type StateCaseSpec, type StepExecutionMethod, type StepSpec } from "../../_framework/types";
import type { PersonalSettingsSavePersistenceCaseData } from "./_support/personal-settings-save-persistence.context";

function step(
  caseStepId: string,
  method: StepExecutionMethod,
  id: string,
  title: string,
  object: string,
  operator: string,
  params?: Record<string, unknown>,
): StepSpec {
  return {
    source: { caseStepId, method },
    id,
    title,
    object,
    operator,
    ...(params ? { params } : {}),
  };
}

export const personalSettingsSavePersistenceCase = {
  id: "defaults.personal-settings.save-persistence",
  title: "20-个人设置保存后刷新和重新登录保留配置",
  model: STATE_CASE_MODEL,
  tags: ["defaults", "personal-settings", "persistence"],
  data: {
    email: "orf-default-page-settings-save-e2e@orf.local",
    password: "OrfDefaultPageSettingsSaveE2E!2026",
    name: "ORF 默认页设置保存用户",
    role: "member",
    status: "active",
    settingsPathPattern: "/settings$",
    defaultLandingLabel: "系统默认",
    savedLandingLabel: "反馈",
    sidebarDefaultLabel: "系统默认",
    savedSidebarLabel: "折叠",
    chatThemeDefaultLabel: "经典浅色",
    savedChatThemeLabel: "舒适暗色",
  },
  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      step("B-1", "api", "frontend.ready", "前端服务 应可用", "frontend.service", "available"),
      step("B-2", "api", "backend.ready", "后端服务 应可用", "api.health", "ok"),
      step("B-3", "api", "frontend.login_entry.accessible", "前端登录页入口 应可访问", "frontend.login_entry", "accessible"),
      step("B-4", "api", "session.endpoint.accessible", "当前会话查询能力 应可用", "auth.session", "accessible"),
      step("B-5", "prisma", "db.ready", "ORF 数据库 应可连接", "db", "ready"),
      step("B-6", "prisma", "db.schema.current", "ORF 数据库 schema 应为 当前测试版本", "db.schema", "current"),
      step("B-7", "api", "ory.admin_public.ready", "Ory/Kratos 认证服务的管理和公共访问能力 应可用", "ory.admin_public", "ready"),
      step("B-8", "api", "session.unauthenticated", "当前会话 应为 未登录", "auth.session", "unauthenticated"),
      step("B-9", "playwright", "cookie.absent", "当前浏览器 应不存在 Ory 登录会话 cookie", "browser.cookie", "absent"),
      step("B-10", "playwright", "storage.empty", "当前浏览器 应不保留本地登录态", "browser.auth_storage", "empty"),
    ],
  },
  Setup: {
    description: "准备设置保存测试用户，并登录进入个人设置页面",
    steps: [
      step("Setup-1", "api", "ory.identity.upsert", "准备邮箱为 `orf-default-page-settings-save-e2e@orf.local`、使用固定测试密码的个人设置保存测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.email", passwordFrom: "data.password", nameFrom: "data.name", saveAs: "identity" }),
      step("Setup-2", "prisma", "db.user.upsert", "准备邮箱为 `orf-default-page-settings-save-e2e@orf.local`、姓名为 `ORF 默认页设置保存用户`、角色为 `member`、状态为 `active` 的个人设置保存测试用户", "db.user", "upsert", { emailFrom: "data.email", passwordFrom: "data.password", nameFrom: "data.name", roleFrom: "data.role", statusFrom: "data.status", identityIdFrom: "runtime.identity.id", saveAs: "user" }),
      step("Setup-3", "api", "preferences.default_landing.default", "设置个人设置保存测试用户默认进入页面为 系统默认", "user.preferences", "set_default_landing_path_by_email", { emailFrom: "data.email", path: null }),
      step("Setup-4", "api", "preferences.sidebar.default", "设置个人设置保存测试用户侧边栏默认状态为 系统默认", "user.preferences", "set_sidebar_state_by_email", { emailFrom: "data.email", state: "system" }),
      step("Setup-5", "api", "preferences.chat_theme.light", "设置个人设置保存测试用户聊天界面主题为 经典浅色", "user.preferences", "set_chat_theme_by_email", { emailFrom: "data.email", theme: "light" }),
      step("Setup-6", "api", "preferences.toast.enabled", "设置个人设置保存测试用户 Toast 通知偏好为 开启", "user.preferences", "set_toast_enabled_by_email", { emailFrom: "data.email", enabled: true }),
      step("Setup-7", "api", "ory.sessions.revoke", "撤销邮箱为 `orf-default-page-settings-save-e2e@orf.local` 的个人设置保存测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.email" }),
      step("Setup-8", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Setup-9", "playwright", "page.goto.auth", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Setup-10", "playwright", "fill.email", "在邮箱输入框输入 `orf-default-page-settings-save-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.email" }),
      step("Setup-11", "playwright", "fill.password", "在密码输入框输入个人设置保存测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.password" }),
      step("Setup-12", "playwright", "click.sign_in", "点击 \"Sign In\" 登录操作", "page.login_form", "submit", { saveAs: "loginResponse" }),
      step("Setup-13", "api", "session.authenticated", "当前会话 应为 邮箱为 `orf-default-page-settings-save-e2e@orf.local`、角色为 `member`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.email", roleFrom: "data.role", statusFrom: "data.status" }),
      step("Setup-14", "playwright", "page.goto.settings", "打开 个人设置页面", "page", "goto", { path: "/settings" }),
    ],
  },
  S0: {
    description: "测试用户位于个人设置页，各设置项处于初始状态",
    assertions: [
      step("S0-1", "api", "session.authenticated", "当前会话 应为 邮箱为 `orf-default-page-settings-save-e2e@orf.local`、角色为 `member`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.email", roleFrom: "data.role", statusFrom: "data.status" }),
      step("S0-2", "playwright", "personal_settings.page.visible", "当前页面 应为 个人设置页面", "personal_settings.page", "visible", { patternFrom: "data.settingsPathPattern" }),
      step("S0-3", "playwright", "personal_settings.default_landing.default", "个人设置页面的默认进入页面设置项 应显示 系统默认", "personal_settings.default_landing", "selected", { labelFrom: "data.defaultLandingLabel" }),
      step("S0-4", "playwright", "personal_settings.sidebar.default", "个人设置页面的侧边栏默认状态设置项 应显示 系统默认", "personal_settings.sidebar_state", "selected", { labelFrom: "data.sidebarDefaultLabel" }),
      step("S0-5", "playwright", "personal_settings.chat_theme.light", "个人设置页面的聊天界面主题设置项 应显示 经典浅色", "personal_settings.chat_theme", "selected", { labelFrom: "data.chatThemeDefaultLabel" }),
      step("S0-6", "playwright", "personal_settings.toast.enabled", "个人设置页面的 Toast 通知开关 应为 开启", "personal_settings.toast", "checked", { enabled: true }),
      step("S0-7", "api", "preferences.default_landing.default", "个人设置保存测试用户的默认进入页面偏好 应为 系统默认", "user.preferences", "default_landing_is", { emailFrom: "data.email", path: null }),
      step("S0-8", "api", "preferences.sidebar.default", "个人设置保存测试用户的侧边栏默认状态偏好 应为 系统默认", "user.preferences", "sidebar_state_is", { emailFrom: "data.email", state: "system" }),
      step("S0-9", "api", "preferences.chat_theme.light", "个人设置保存测试用户的聊天界面主题偏好 应为 经典浅色", "user.preferences", "chat_theme_is", { emailFrom: "data.email", theme: "light" }),
      step("S0-10", "api", "preferences.toast.enabled", "个人设置保存测试用户的 Toast 通知偏好 应为 开启", "user.preferences", "toast_enabled_is", { emailFrom: "data.email", enabled: true }),
    ],
  },
  Action: {
    description: "修改设置、刷新页面，并退出后重新登录回到个人设置页",
    steps: [
      step("Action-1", "playwright", "settings.default_landing.feedback", "在个人设置页面的默认进入页面设置项选择 `反馈`", "personal_settings.default_landing", "select", { emailFrom: "data.email", labelFrom: "data.savedLandingLabel", saveAs: "defaultLandingSnapshot" }),
      step("Action-2", "playwright", "settings.sidebar.collapsed", "在个人设置页面的侧边栏默认状态设置项选择 `折叠`", "personal_settings.sidebar_state", "select", { emailFrom: "data.email", labelFrom: "data.savedSidebarLabel", saveAs: "sidebarSnapshot" }),
      step("Action-3", "playwright", "settings.chat_theme.dark", "在个人设置页面的聊天界面主题设置项选择 `舒适暗色`", "personal_settings.chat_theme", "select", { emailFrom: "data.email", labelFrom: "data.savedChatThemeLabel", saveAs: "chatThemeSnapshot" }),
      step("Action-4", "playwright", "settings.toast.off", "在个人设置页面的 Toast 通知开关选择 关闭", "personal_settings.toast", "set_checked", { emailFrom: "data.email", enabled: false, saveAs: "toastSnapshot" }),
      step("Action-5", "playwright", "settings.page.reload", "刷新 个人设置页面", "personal_settings.page", "reload", { emailFrom: "data.email", defaultLandingLabelFrom: "data.savedLandingLabel", sidebarLabelFrom: "data.savedSidebarLabel", chatThemeLabelFrom: "data.savedChatThemeLabel", toastEnabled: false, saveAs: "refreshSnapshot" }),
      step("Action-6", "api", "auth.logout", "注销当前登录会话", "auth", "logout"),
      step("Action-7", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Action-8", "playwright", "page.goto.auth", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Action-9", "playwright", "fill.email", "在邮箱输入框输入 `orf-default-page-settings-save-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.email" }),
      step("Action-10", "playwright", "fill.password", "在密码输入框输入个人设置保存测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.password" }),
      step("Action-11", "playwright", "click.sign_in", "点击 \"Sign In\" 登录操作", "page.login_form", "submit", { saveAs: "reloginResponse" }),
      step("Action-12", "playwright", "page.goto.settings.after_relogin", "打开 个人设置页面", "page", "goto", { path: "/settings", saveAs: "reloginSettingsSnapshot" }),
    ],
  },
  S1: {
    description: "刷新和重新登录后，已保存配置均保持不变",
    assertions: [
      step("S1-1", "playwright", "refresh.default_landing.feedback", "刷新个人设置页面后，默认进入页面设置项 应显示 `反馈`", "settings_snapshot", "default_landing", { snapshotFrom: "runtime.refreshSnapshot", labelFrom: "data.savedLandingLabel" }),
      step("S1-2", "playwright", "refresh.sidebar.collapsed", "刷新个人设置页面后，侧边栏默认状态设置项 应显示 `折叠`", "settings_snapshot", "sidebar_state", { snapshotFrom: "runtime.refreshSnapshot", labelFrom: "data.savedSidebarLabel" }),
      step("S1-3", "playwright", "refresh.chat_theme.dark", "刷新个人设置页面后，聊天界面主题设置项 应显示 `舒适暗色`", "settings_snapshot", "chat_theme", { snapshotFrom: "runtime.refreshSnapshot", labelFrom: "data.savedChatThemeLabel" }),
      step("S1-4", "playwright", "refresh.toast.off", "刷新个人设置页面后，Toast 通知开关 应为 关闭", "settings_snapshot", "toast_checked", { snapshotFrom: "runtime.refreshSnapshot", enabled: false }),
      step("S1-5", "api", "refresh.preferences.default_landing.feedback", "刷新个人设置页面后，个人设置保存测试用户的默认进入页面偏好 应为 `反馈`", "settings_snapshot", "saved_default_landing", { snapshotFrom: "runtime.refreshSnapshot", path: "/feedback" }),
      step("S1-6", "api", "refresh.preferences.sidebar.collapsed", "刷新个人设置页面后，个人设置保存测试用户的侧边栏默认状态偏好 应为 折叠", "settings_snapshot", "saved_sidebar_state", { snapshotFrom: "runtime.refreshSnapshot", state: "collapsed" }),
      step("S1-7", "api", "refresh.preferences.chat_theme.dark", "刷新个人设置页面后，个人设置保存测试用户的聊天界面主题偏好 应为 `舒适暗色`", "settings_snapshot", "saved_chat_theme", { snapshotFrom: "runtime.refreshSnapshot", theme: "dark" }),
      step("S1-8", "api", "refresh.preferences.toast.off", "刷新个人设置页面后，个人设置保存测试用户的 Toast 通知偏好 应为 关闭", "settings_snapshot", "saved_toast_enabled", { snapshotFrom: "runtime.refreshSnapshot", enabled: false }),
      step("S1-9", "playwright", "relogin.default_landing.feedback", "退出并重新登录后，个人设置页面的默认进入页面设置项 应显示 `反馈`", "personal_settings.default_landing", "selected", { labelFrom: "data.savedLandingLabel" }),
      step("S1-10", "playwright", "relogin.sidebar.collapsed", "退出并重新登录后，个人设置页面的侧边栏默认状态设置项 应显示 `折叠`", "personal_settings.sidebar_state", "selected", { labelFrom: "data.savedSidebarLabel" }),
      step("S1-11", "playwright", "relogin.chat_theme.dark", "退出并重新登录后，个人设置页面的聊天界面主题设置项 应显示 `舒适暗色`", "personal_settings.chat_theme", "selected", { labelFrom: "data.savedChatThemeLabel" }),
      step("S1-12", "playwright", "relogin.toast.off", "退出并重新登录后，个人设置页面的 Toast 通知开关 应为 关闭", "personal_settings.toast", "checked", { enabled: false }),
      step("S1-13", "api", "relogin.preferences.default_landing.feedback", "退出并重新登录后，个人设置保存测试用户的默认进入页面偏好 应为 `反馈`", "user.preferences", "default_landing_is", { emailFrom: "data.email", path: "/feedback" }),
      step("S1-14", "api", "relogin.preferences.sidebar.collapsed", "退出并重新登录后，个人设置保存测试用户的侧边栏默认状态偏好 应为 折叠", "user.preferences", "sidebar_state_is", { emailFrom: "data.email", state: "collapsed" }),
      step("S1-15", "api", "relogin.preferences.chat_theme.dark", "退出并重新登录后，个人设置保存测试用户的聊天界面主题偏好 应为 `舒适暗色`", "user.preferences", "chat_theme_is", { emailFrom: "data.email", theme: "dark" }),
      step("S1-16", "api", "relogin.preferences.toast.off", "退出并重新登录后，个人设置保存测试用户的 Toast 通知偏好 应为 关闭", "user.preferences", "toast_enabled_is", { emailFrom: "data.email", enabled: false }),
      step("S1-17", "api", "session.authenticated", "当前会话 应为 邮箱为 `orf-default-page-settings-save-e2e@orf.local`、角色为 `member`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.email", roleFrom: "data.role", statusFrom: "data.status" }),
    ],
  },
  Clean: {
    description: "删除测试用户偏好、账号和页面会话状态，恢复未登录基准状态",
    steps: [
      step("Clean-1", "api", "auth.logout", "注销当前登录会话", "auth", "logout"),
      step("Clean-2", "playwright", "page.runtime.stop", "离开当前 ORF 前端页面", "page.runtime", "stop"),
      step("Clean-3", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Clean-4", "api", "ory.sessions.revoke", "撤销邮箱为 `orf-default-page-settings-save-e2e@orf.local` 的个人设置保存测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.email" }),
      step("Clean-5", "api", "preferences.default_landing.reset", "恢复邮箱为 `orf-default-page-settings-save-e2e@orf.local` 的默认进入页面为 系统默认", "user.preferences", "set_default_landing_path_by_email", { emailFrom: "data.email", path: null }),
      step("Clean-6", "api", "preferences.sidebar.reset", "恢复邮箱为 `orf-default-page-settings-save-e2e@orf.local` 的侧边栏默认状态为 系统默认", "user.preferences", "set_sidebar_state_by_email", { emailFrom: "data.email", state: "system" }),
      step("Clean-7", "api", "preferences.chat_theme.reset", "恢复邮箱为 `orf-default-page-settings-save-e2e@orf.local` 的聊天界面主题为 经典浅色", "user.preferences", "set_chat_theme_by_email", { emailFrom: "data.email", theme: "light" }),
      step("Clean-8", "api", "preferences.toast.reset", "恢复邮箱为 `orf-default-page-settings-save-e2e@orf.local` 的 Toast 通知偏好为 开启", "user.preferences", "set_toast_enabled_by_email", { emailFrom: "data.email", enabled: true }),
      step("Clean-9", "api", "ory.identity.delete", "删除邮箱为 `orf-default-page-settings-save-e2e@orf.local` 的个人设置保存测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.email" }),
      step("Clean-10", "prisma", "db.user.memberships.delete", "删除邮箱为 `orf-default-page-settings-save-e2e@orf.local` 的个人设置保存测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.email" }),
      step("Clean-11", "prisma", "db.user.delete", "删除邮箱为 `orf-default-page-settings-save-e2e@orf.local` 的个人设置保存测试用户", "db.user", "delete", { emailFrom: "data.email" }),
      step("Clean-12", "api", "ory.identity.absent", "邮箱为 `orf-default-page-settings-save-e2e@orf.local` 的个人设置保存测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.email" }),
      step("Clean-13", "prisma", "db.user.absent", "邮箱为 `orf-default-page-settings-save-e2e@orf.local` 的个人设置保存测试用户 应不存在", "db.user", "absent", { emailFrom: "data.email" }),
    ],
  },
} satisfies StateCaseSpec<PersonalSettingsSavePersistenceCaseData>;
