import { STATE_CASE_MODEL, type StateCaseSpec } from "../../_framework/types";
import type { RegisterInvalidCredentialsCaseData } from "./_support/register-invalid-credentials.context";

export const registerInvalidCredentialsCase = {
  id: "auth.register.invalid-credentials",
  title: "07-用户注册表单输入校验失败",
  model: STATE_CASE_MODEL,
  tags: ["auth", "registration", "validation", "negative"],

  data: {
    name: "ORF Invalid Register E2E",
    role: "member",
    validPassword: "OrfInvalidRegisterE2E!2026",
    blankPassword: "        ",
    shortPassword: "1234567",
    invalidAccountNoAt: "orf-register-invalid-account",
    invalidAccountMissingDomain: "orf-register-invalid@",
    invalidAccountMissingTopLevelDomain: "orf-register-invalid@orf",
    invalidAccountWithSpace: "orf register invalid@orf.local",
    existingEmail: "orf-register-existing-e2e@orf.local",
    existingPassword: "OrfRegisterExistingE2E!2026",
    existingName: "ORF Register Existing E2E",
    invalidPasswordEmptyEmail: "orf-register-invalid-password-empty-e2e@orf.local",
    invalidPasswordBlankEmail: "orf-register-invalid-password-blank-e2e@orf.local",
    invalidPasswordShortEmail: "orf-register-invalid-password-short-e2e@orf.local",
  },

  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      { source: { caseStepId: "B-1", method: "api" }, id: "frontend.ready", title: "前端服务 应可用", object: "frontend.service", operator: "available" },
      { source: { caseStepId: "B-2", method: "api" }, id: "backend.ready", title: "后端服务 应可用", object: "api.health", operator: "ok" },
      { source: { caseStepId: "B-3", method: "api" }, id: "frontend.login_entry.accessible", title: "前端登录页入口 应可访问", object: "frontend.login_entry", operator: "accessible" },
      { source: { caseStepId: "B-4", method: "api" }, id: "session.endpoint.accessible", title: "当前会话查询能力 应可用", object: "auth.session", operator: "accessible" },
      { source: { caseStepId: "B-5", method: "prisma" }, id: "db.ready", title: "ORF 数据库 应可连接", object: "db", operator: "ready" },
      { source: { caseStepId: "B-6", method: "prisma" }, id: "db.schema.current", title: "ORF 数据库 schema 应为 当前测试版本", object: "db.schema", operator: "current" },
      { source: { caseStepId: "B-7", method: "api" }, id: "ory.admin_public.ready", title: "Ory/Kratos 认证服务的管理和公共访问能力 应可用", object: "ory.admin_public", operator: "ready" },
      { source: { caseStepId: "B-8", method: "api" }, id: "session.unauthenticated", title: "当前会话 应为 未登录", object: "auth.session", operator: "unauthenticated" },
      { source: { caseStepId: "B-9", method: "playwright" }, id: "cookie.absent", title: "当前浏览器 应不存在 Ory 登录会话 cookie", object: "browser.cookie", operator: "absent" },
      { source: { caseStepId: "B-10", method: "playwright" }, id: "storage.empty", title: "当前浏览器 应不保留本地登录态", object: "browser.auth_storage", operator: "empty" },
    ],
  },

  Setup: {
    description: "准备已占用邮箱，清理非法密码目标邮箱，并进入注册页",
    steps: [
      { source: { caseStepId: "Setup-1", method: "api" }, id: "ory.existing_sessions.revoke.setup", title: "撤销已占用邮箱测试登录身份可能残留的登录会话", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.existingEmail" } },
      { source: { caseStepId: "Setup-2", method: "api" }, id: "ory.existing_identity.delete.setup", title: "删除邮箱为 `orf-register-existing-e2e@orf.local` 的已占用邮箱测试登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.existingEmail" } },
      { source: { caseStepId: "Setup-3", method: "prisma" }, id: "db.existing_user.memberships.delete.setup", title: "删除邮箱为 `orf-register-existing-e2e@orf.local` 的已占用邮箱测试用户默认团队成员关系", object: "db.user", operator: "delete_memberships", params: { emailFrom: "data.existingEmail" } },
      { source: { caseStepId: "Setup-4", method: "prisma" }, id: "db.existing_user.delete.setup", title: "删除邮箱为 `orf-register-existing-e2e@orf.local` 的已占用邮箱测试用户", object: "db.user", operator: "delete", params: { emailFrom: "data.existingEmail" } },
      { source: { caseStepId: "Setup-5", method: "api" }, id: "ory.invalid_password_empty_identity.delete.setup", title: "删除邮箱为 `orf-register-invalid-password-empty-e2e@orf.local` 的非法密码测试登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.invalidPasswordEmptyEmail" } },
      { source: { caseStepId: "Setup-6", method: "api" }, id: "ory.invalid_password_blank_identity.delete.setup", title: "删除邮箱为 `orf-register-invalid-password-blank-e2e@orf.local` 的非法密码测试登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.invalidPasswordBlankEmail" } },
      { source: { caseStepId: "Setup-7", method: "api" }, id: "ory.invalid_password_short_identity.delete.setup", title: "删除邮箱为 `orf-register-invalid-password-short-e2e@orf.local` 的非法密码测试登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.invalidPasswordShortEmail" } },
      { source: { caseStepId: "Setup-8", method: "prisma" }, id: "db.invalid_password_empty_user.delete.setup", title: "删除邮箱为 `orf-register-invalid-password-empty-e2e@orf.local` 的非法密码测试用户默认团队成员关系和用户", object: "db.user", operator: "delete", params: { emailFrom: "data.invalidPasswordEmptyEmail" } },
      { source: { caseStepId: "Setup-9", method: "prisma" }, id: "db.invalid_password_blank_user.delete.setup", title: "删除邮箱为 `orf-register-invalid-password-blank-e2e@orf.local` 的非法密码测试用户默认团队成员关系和用户", object: "db.user", operator: "delete", params: { emailFrom: "data.invalidPasswordBlankEmail" } },
      { source: { caseStepId: "Setup-10", method: "prisma" }, id: "db.invalid_password_short_user.delete.setup", title: "删除邮箱为 `orf-register-invalid-password-short-e2e@orf.local` 的非法密码测试用户默认团队成员关系和用户", object: "db.user", operator: "delete", params: { emailFrom: "data.invalidPasswordShortEmail" } },
      { source: { caseStepId: "Setup-11", method: "api" }, id: "ory.existing_identity.upsert", title: "准备邮箱为 `orf-register-existing-e2e@orf.local`、使用固定测试密码的已占用邮箱测试登录身份", object: "ory.identity", operator: "upsert_password", params: { emailFrom: "data.existingEmail", passwordFrom: "data.existingPassword", nameFrom: "data.existingName", saveAs: "existingIdentity" } },
      { source: { caseStepId: "Setup-12", method: "prisma" }, id: "db.existing_user.upsert", title: "准备邮箱为 `orf-register-existing-e2e@orf.local`、角色为 `member`、状态为 `active` 的已占用邮箱测试用户", object: "db.user", operator: "upsert", params: { emailFrom: "data.existingEmail", nameFrom: "data.existingName", roleFrom: "data.role", status: "active", identityIdFrom: "runtime.existingIdentity.id", saveAs: "existingUser" } },
      { source: { caseStepId: "Setup-13", method: "api" }, id: "ory.existing_sessions.revoke", title: "撤销已占用邮箱测试登录身份的登录会话", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.existingEmail" } },
      { source: { caseStepId: "Setup-14", method: "playwright" }, id: "browser.clear", title: "移除当前浏览器中的残留登录态", object: "browser", operator: "clear_state" },
      { source: { caseStepId: "Setup-15", method: "playwright" }, id: "page.goto.auth", title: "打开 ORF 登录页", object: "page", operator: "goto", params: { path: "/auth" } },
      { source: { caseStepId: "Setup-16", method: "playwright" }, id: "switch.register", title: "点击登录页的 `Register` 操作", object: "page", operator: "click", params: { role: "button", name: "Register" } },
    ],
  },

  S0: {
    description: "注册表单可用，已占用邮箱存在，非法密码目标邮箱尚未占用",
    assertions: [
      { source: { caseStepId: "S0-1", method: "playwright" }, id: "url.auth", title: "当前页面 应为 注册页", object: "page.url", operator: "match", params: { pattern: "/auth$" } },
      { source: { caseStepId: "S0-2", method: "playwright" }, id: "heading.register.visible", title: "注册页标题 \"Register\" 应可见", object: "page", operator: "visible", params: { role: "heading", name: "Register" } },
      { source: { caseStepId: "S0-3", method: "playwright" }, id: "input.name.visible", title: "姓名输入框 应可见", object: "page", operator: "visible", params: { label: "Name" } },
      { source: { caseStepId: "S0-4", method: "playwright" }, id: "input.name.empty", title: "姓名输入框的值 应为空", object: "input", operator: "value", params: { label: "Name", value: "" } },
      { source: { caseStepId: "S0-5", method: "playwright" }, id: "input.email.visible", title: "邮箱输入框 应可见", object: "page", operator: "visible", params: { label: "Email" } },
      { source: { caseStepId: "S0-6", method: "playwright" }, id: "input.email.empty", title: "邮箱输入框的值 应为空", object: "input", operator: "value", params: { label: "Email", value: "" } },
      { source: { caseStepId: "S0-7", method: "playwright" }, id: "input.password.visible", title: "密码输入框 应可见", object: "page", operator: "visible", params: { label: "Password", exact: true } },
      { source: { caseStepId: "S0-8", method: "playwright" }, id: "input.password.empty", title: "密码输入框的值 应为空", object: "input", operator: "value", params: { label: "Password", exact: true, value: "" } },
      { source: { caseStepId: "S0-9", method: "playwright" }, id: "button.create_account.visible", title: "\"Create Account\" 注册操作 应可见", object: "page", operator: "visible", params: { role: "button", name: "Create Account" } },
      { source: { caseStepId: "S0-10", method: "playwright" }, id: "button.create_account.enabled", title: "\"Create Account\" 注册操作 应可点击", object: "page", operator: "enabled", params: { role: "button", name: "Create Account" } },
      { source: { caseStepId: "S0-11", method: "api" }, id: "session.unauthenticated", title: "当前会话 应为 未登录", object: "auth.session", operator: "unauthenticated" },
      { source: { caseStepId: "S0-12", method: "api" }, id: "ory.existing_identity.exists", title: "认证系统中 应存在 邮箱为 `orf-register-existing-e2e@orf.local` 的已占用邮箱测试登录身份", object: "ory.identity", operator: "exists", params: { emailFrom: "data.existingEmail" } },
      { source: { caseStepId: "S0-13", method: "api" }, id: "ory.existing_identity.password_available", title: "已占用邮箱测试登录身份的密码凭据 应可用", object: "ory.identity", operator: "password_available", params: { emailFrom: "data.existingEmail" } },
      { source: { caseStepId: "S0-14", method: "prisma" }, id: "db.existing_user.active_member", title: "ORF 业务系统中 应存在 邮箱为 `orf-register-existing-e2e@orf.local`、角色为 `member`、状态为 `active` 的已占用邮箱测试用户", object: "db.user", operator: "matches", params: { emailFrom: "data.existingEmail", roleFrom: "data.role", status: "active" } },
      { source: { caseStepId: "S0-15", method: "api" }, id: "ory.invalid_password_empty_identity.absent", title: "认证系统中 应不存在 邮箱为 `orf-register-invalid-password-empty-e2e@orf.local` 的登录身份", object: "ory.identity", operator: "absent", params: { emailFrom: "data.invalidPasswordEmptyEmail" } },
      { source: { caseStepId: "S0-16", method: "api" }, id: "ory.invalid_password_blank_identity.absent", title: "认证系统中 应不存在 邮箱为 `orf-register-invalid-password-blank-e2e@orf.local` 的登录身份", object: "ory.identity", operator: "absent", params: { emailFrom: "data.invalidPasswordBlankEmail" } },
      { source: { caseStepId: "S0-17", method: "api" }, id: "ory.invalid_password_short_identity.absent", title: "认证系统中 应不存在 邮箱为 `orf-register-invalid-password-short-e2e@orf.local` 的登录身份", object: "ory.identity", operator: "absent", params: { emailFrom: "data.invalidPasswordShortEmail" } },
      { source: { caseStepId: "S0-18", method: "prisma" }, id: "db.invalid_password_empty_user.absent", title: "ORF 业务系统中 应不存在 邮箱为 `orf-register-invalid-password-empty-e2e@orf.local` 的用户", object: "db.user", operator: "absent", params: { emailFrom: "data.invalidPasswordEmptyEmail" } },
      { source: { caseStepId: "S0-19", method: "prisma" }, id: "db.invalid_password_blank_user.absent", title: "ORF 业务系统中 应不存在 邮箱为 `orf-register-invalid-password-blank-e2e@orf.local` 的用户", object: "db.user", operator: "absent", params: { emailFrom: "data.invalidPasswordBlankEmail" } },
      { source: { caseStepId: "S0-20", method: "prisma" }, id: "db.invalid_password_short_user.absent", title: "ORF 业务系统中 应不存在 邮箱为 `orf-register-invalid-password-short-e2e@orf.local` 的用户", object: "db.user", operator: "absent", params: { emailFrom: "data.invalidPasswordShortEmail" } },
    ],
  },

  Action: {
    description: "逐一提交非法账号或非法密码的注册表单",
    steps: [
      { source: { caseStepId: "Action-1", method: "playwright" }, id: "fill.name", title: "在姓名输入框输入 `ORF Invalid Register E2E`", object: "page", operator: "fill", params: { label: "Name", valueFrom: "data.name" } },
      { source: { caseStepId: "Action-2", method: "playwright" }, id: "clear.email.empty_account", title: "清空邮箱输入框", object: "page", operator: "fill", params: { label: "Email", value: "" } },
      { source: { caseStepId: "Action-3", method: "playwright" }, id: "fill.password.empty_account", title: "在密码输入框输入合法长度的固定测试密码", object: "page", operator: "fill", params: { label: "Password", exact: true, valueFrom: "data.validPassword" } },
      { source: { caseStepId: "Action-4", method: "playwright" }, id: "click.create_account.empty_account", title: "点击 \"Create Account\" 注册操作", object: "page", operator: "click", params: { role: "button", name: "Create Account" } },
      { source: { caseStepId: "Action-5", method: "playwright" }, id: "error.email_required.visible", title: "注册页错误提示 \"请输入邮箱\" 应可见", object: "page", operator: "visible", params: { text: "请输入邮箱", exact: true } },
      { source: { caseStepId: "Action-6", method: "playwright" }, id: "fill.email.no_at", title: "在邮箱输入框输入 `orf-register-invalid-account`", object: "page", operator: "fill", params: { label: "Email", valueFrom: "data.invalidAccountNoAt" } },
      { source: { caseStepId: "Action-7", method: "playwright" }, id: "fill.password.no_at", title: "在密码输入框输入合法长度的固定测试密码", object: "page", operator: "fill", params: { label: "Password", exact: true, valueFrom: "data.validPassword" } },
      { source: { caseStepId: "Action-8", method: "playwright" }, id: "click.create_account.no_at", title: "点击 \"Create Account\" 注册操作", object: "page", operator: "click", params: { role: "button", name: "Create Account" } },
      { source: { caseStepId: "Action-9", method: "playwright" }, id: "error.invalid_email.no_at.visible", title: "注册页错误提示 \"邮箱格式不正确\" 应可见", object: "page", operator: "visible", params: { text: "邮箱格式不正确", exact: true } },
      { source: { caseStepId: "Action-10", method: "playwright" }, id: "fill.email.missing_domain", title: "在邮箱输入框输入 `orf-register-invalid@`", object: "page", operator: "fill", params: { label: "Email", valueFrom: "data.invalidAccountMissingDomain" } },
      { source: { caseStepId: "Action-11", method: "playwright" }, id: "fill.password.missing_domain", title: "在密码输入框输入合法长度的固定测试密码", object: "page", operator: "fill", params: { label: "Password", exact: true, valueFrom: "data.validPassword" } },
      { source: { caseStepId: "Action-12", method: "playwright" }, id: "click.create_account.missing_domain", title: "点击 \"Create Account\" 注册操作", object: "page", operator: "click", params: { role: "button", name: "Create Account" } },
      { source: { caseStepId: "Action-13", method: "playwright" }, id: "error.invalid_email.missing_domain.visible", title: "注册页错误提示 \"邮箱格式不正确\" 应可见", object: "page", operator: "visible", params: { text: "邮箱格式不正确", exact: true } },
      { source: { caseStepId: "Action-14", method: "playwright" }, id: "fill.email.missing_tld", title: "在邮箱输入框输入 `orf-register-invalid@orf`", object: "page", operator: "fill", params: { label: "Email", valueFrom: "data.invalidAccountMissingTopLevelDomain" } },
      { source: { caseStepId: "Action-15", method: "playwright" }, id: "fill.password.missing_tld", title: "在密码输入框输入合法长度的固定测试密码", object: "page", operator: "fill", params: { label: "Password", exact: true, valueFrom: "data.validPassword" } },
      { source: { caseStepId: "Action-16", method: "playwright" }, id: "click.create_account.missing_tld", title: "点击 \"Create Account\" 注册操作", object: "page", operator: "click", params: { role: "button", name: "Create Account" } },
      { source: { caseStepId: "Action-17", method: "playwright" }, id: "error.invalid_email.missing_tld.visible", title: "注册页错误提示 \"邮箱格式不正确\" 应可见", object: "page", operator: "visible", params: { text: "邮箱格式不正确", exact: true } },
      { source: { caseStepId: "Action-18", method: "playwright" }, id: "fill.email.with_space", title: "在邮箱输入框输入 `orf register invalid@orf.local`", object: "page", operator: "fill", params: { label: "Email", valueFrom: "data.invalidAccountWithSpace" } },
      { source: { caseStepId: "Action-19", method: "playwright" }, id: "fill.password.with_space", title: "在密码输入框输入合法长度的固定测试密码", object: "page", operator: "fill", params: { label: "Password", exact: true, valueFrom: "data.validPassword" } },
      { source: { caseStepId: "Action-20", method: "playwright" }, id: "click.create_account.with_space", title: "点击 \"Create Account\" 注册操作", object: "page", operator: "click", params: { role: "button", name: "Create Account" } },
      { source: { caseStepId: "Action-21", method: "playwright" }, id: "error.invalid_email.with_space.visible", title: "注册页错误提示 \"邮箱格式不正确\" 应可见", object: "page", operator: "visible", params: { text: "邮箱格式不正确", exact: true } },
      { source: { caseStepId: "Action-22", method: "playwright" }, id: "fill.email.existing", title: "在邮箱输入框输入 `orf-register-existing-e2e@orf.local`", object: "page", operator: "fill", params: { label: "Email", valueFrom: "data.existingEmail" } },
      { source: { caseStepId: "Action-23", method: "playwright" }, id: "fill.password.existing", title: "在密码输入框输入合法长度的固定测试密码", object: "page", operator: "fill", params: { label: "Password", exact: true, valueFrom: "data.validPassword" } },
      { source: { caseStepId: "Action-24", method: "playwright" }, id: "click.create_account.existing", title: "点击 \"Create Account\" 注册操作", object: "page", operator: "click", params: { role: "button", name: "Create Account" } },
      { source: { caseStepId: "Action-25", method: "playwright" }, id: "error.existing_email.visible", title: "注册页错误提示 \"邮箱已存在\" 应可见", object: "page", operator: "visible", params: { text: "邮箱已存在", exact: true } },
      { source: { caseStepId: "Action-26", method: "playwright" }, id: "fill.email.empty_password", title: "在邮箱输入框输入 `orf-register-invalid-password-empty-e2e@orf.local`", object: "page", operator: "fill", params: { label: "Email", valueFrom: "data.invalidPasswordEmptyEmail" } },
      { source: { caseStepId: "Action-27", method: "playwright" }, id: "clear.password.empty_password", title: "清空密码输入框", object: "page", operator: "fill", params: { label: "Password", exact: true, value: "" } },
      { source: { caseStepId: "Action-28", method: "playwright" }, id: "click.create_account.empty_password", title: "点击 \"Create Account\" 注册操作", object: "page", operator: "click", params: { role: "button", name: "Create Account" } },
      { source: { caseStepId: "Action-29", method: "playwright" }, id: "error.password_required.empty.visible", title: "注册页错误提示 \"请输入密码\" 应可见", object: "page", operator: "visible", params: { text: "请输入密码", exact: true } },
      { source: { caseStepId: "Action-30", method: "playwright" }, id: "fill.email.blank_password", title: "在邮箱输入框输入 `orf-register-invalid-password-blank-e2e@orf.local`", object: "page", operator: "fill", params: { label: "Email", valueFrom: "data.invalidPasswordBlankEmail" } },
      { source: { caseStepId: "Action-31", method: "playwright" }, id: "fill.password.blank_password", title: "在密码输入框输入纯空白密码", object: "page", operator: "fill", params: { label: "Password", exact: true, valueFrom: "data.blankPassword" } },
      { source: { caseStepId: "Action-32", method: "playwright" }, id: "click.create_account.blank_password", title: "点击 \"Create Account\" 注册操作", object: "page", operator: "click", params: { role: "button", name: "Create Account" } },
      { source: { caseStepId: "Action-33", method: "playwright" }, id: "error.password_required.blank.visible", title: "注册页错误提示 \"请输入密码\" 应可见", object: "page", operator: "visible", params: { text: "请输入密码", exact: true } },
      { source: { caseStepId: "Action-34", method: "playwright" }, id: "fill.email.short_password", title: "在邮箱输入框输入 `orf-register-invalid-password-short-e2e@orf.local`", object: "page", operator: "fill", params: { label: "Email", valueFrom: "data.invalidPasswordShortEmail" } },
      { source: { caseStepId: "Action-35", method: "playwright" }, id: "fill.password.short_password", title: "在密码输入框输入 `1234567`", object: "page", operator: "fill", params: { label: "Password", exact: true, valueFrom: "data.shortPassword" } },
      { source: { caseStepId: "Action-36", method: "playwright" }, id: "click.create_account.short_password", title: "点击 \"Create Account\" 注册操作", object: "page", operator: "click", params: { role: "button", name: "Create Account" } },
      { source: { caseStepId: "Action-37", method: "playwright" }, id: "error.password_short.visible", title: "注册页错误提示 \"密码至少 8 位\" 应可见", object: "page", operator: "visible", params: { text: "密码至少 8 位", exact: true } },
    ],
  },

  S1: {
    description: "非法注册尝试全部被阻拦，不产生新身份、用户或登录态",
    assertions: [
      { source: { caseStepId: "S1-1", method: "playwright" }, id: "url.auth.after_invalid_attempts", title: "当前页面 应仍为 注册页", object: "page.url", operator: "match", params: { pattern: "/auth$" } },
      { source: { caseStepId: "S1-2", method: "api" }, id: "session.unauthenticated.after_invalid_attempts", title: "当前会话 应仍为 未登录", object: "auth.session", operator: "unauthenticated" },
      { source: { caseStepId: "S1-3", method: "playwright" }, id: "cookie.absent.after_invalid_attempts", title: "当前浏览器 应不存在 Ory 登录会话 cookie", object: "browser.cookie", operator: "absent" },
      { source: { caseStepId: "S1-4", method: "playwright" }, id: "storage.empty.after_invalid_attempts", title: "当前浏览器 应不保留本地登录态", object: "browser.auth_storage", operator: "empty" },
      { source: { caseStepId: "S1-5", method: "playwright" }, id: "approval_pending.absent", title: "注册页的 `等待注册审核` 状态 应不可见", object: "page", operator: "count", params: { role: "heading", name: "等待注册审核", count: 0 } },
      { source: { caseStepId: "S1-6", method: "api" }, id: "ory.invalid_password_empty_identity.absent", title: "认证系统中 应不存在 邮箱为 `orf-register-invalid-password-empty-e2e@orf.local` 的登录身份", object: "ory.identity", operator: "absent", params: { emailFrom: "data.invalidPasswordEmptyEmail" } },
      { source: { caseStepId: "S1-7", method: "api" }, id: "ory.invalid_password_blank_identity.absent", title: "认证系统中 应不存在 邮箱为 `orf-register-invalid-password-blank-e2e@orf.local` 的登录身份", object: "ory.identity", operator: "absent", params: { emailFrom: "data.invalidPasswordBlankEmail" } },
      { source: { caseStepId: "S1-8", method: "api" }, id: "ory.invalid_password_short_identity.absent", title: "认证系统中 应不存在 邮箱为 `orf-register-invalid-password-short-e2e@orf.local` 的登录身份", object: "ory.identity", operator: "absent", params: { emailFrom: "data.invalidPasswordShortEmail" } },
      { source: { caseStepId: "S1-9", method: "prisma" }, id: "db.invalid_password_empty_user.absent", title: "ORF 业务系统中 应不存在 邮箱为 `orf-register-invalid-password-empty-e2e@orf.local` 的用户", object: "db.user", operator: "absent", params: { emailFrom: "data.invalidPasswordEmptyEmail" } },
      { source: { caseStepId: "S1-10", method: "prisma" }, id: "db.invalid_password_blank_user.absent", title: "ORF 业务系统中 应不存在 邮箱为 `orf-register-invalid-password-blank-e2e@orf.local` 的用户", object: "db.user", operator: "absent", params: { emailFrom: "data.invalidPasswordBlankEmail" } },
      { source: { caseStepId: "S1-11", method: "prisma" }, id: "db.invalid_password_short_user.absent", title: "ORF 业务系统中 应不存在 邮箱为 `orf-register-invalid-password-short-e2e@orf.local` 的用户", object: "db.user", operator: "absent", params: { emailFrom: "data.invalidPasswordShortEmail" } },
      { source: { caseStepId: "S1-12", method: "api" }, id: "ory.existing_identity.single", title: "认证系统中 邮箱为 `orf-register-existing-e2e@orf.local` 的已占用邮箱测试登录身份 应仍只有一个", object: "ory.identity", operator: "single", params: { emailFrom: "data.existingEmail" } },
      { source: { caseStepId: "S1-13", method: "prisma" }, id: "db.existing_user.single", title: "ORF 业务系统中 邮箱为 `orf-register-existing-e2e@orf.local` 的已占用邮箱测试用户 应仍只有一个", object: "db.user", operator: "single", params: { emailFrom: "data.existingEmail" } },
      { source: { caseStepId: "S1-14", method: "prisma" }, id: "db.existing_user.status_active", title: "已占用邮箱测试用户的状态 应仍为 `active`", object: "db.user", operator: "matches", params: { emailFrom: "data.existingEmail", status: "active" } },
      { source: { caseStepId: "S1-15", method: "prisma" }, id: "db.existing_user.role_member", title: "已占用邮箱测试用户的团队角色 应仍为 `member`", object: "db.user", operator: "matches", params: { emailFrom: "data.existingEmail", roleFrom: "data.role" } },
    ],
  },

  Clean: {
    description: "删除本用例准备和可能残留的账号数据，并恢复未登录基准状态",
    steps: [
      { source: { caseStepId: "Clean-1", method: "api" }, id: "auth.logout", title: "注销当前登录会话", object: "auth", operator: "logout" },
      { source: { caseStepId: "Clean-2", method: "playwright" }, id: "page.runtime.stop", title: "离开当前 ORF 前端页面", object: "page.runtime", operator: "stop" },
      { source: { caseStepId: "Clean-3", method: "playwright" }, id: "browser.clear", title: "移除当前浏览器中的残留登录态", object: "browser", operator: "clear_state" },
      { source: { caseStepId: "Clean-4", method: "api" }, id: "ory.existing_sessions.revoke", title: "撤销已占用邮箱测试登录身份的残留登录会话", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.existingEmail" } },
      { source: { caseStepId: "Clean-5", method: "api" }, id: "ory.existing_identity.delete", title: "删除邮箱为 `orf-register-existing-e2e@orf.local` 的已占用邮箱测试登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.existingEmail" } },
      { source: { caseStepId: "Clean-6", method: "prisma" }, id: "db.existing_user.memberships.delete", title: "删除邮箱为 `orf-register-existing-e2e@orf.local` 的已占用邮箱测试用户默认团队成员关系", object: "db.user", operator: "delete_memberships", params: { emailFrom: "data.existingEmail" } },
      { source: { caseStepId: "Clean-7", method: "prisma" }, id: "db.existing_user.delete", title: "删除邮箱为 `orf-register-existing-e2e@orf.local` 的已占用邮箱测试用户", object: "db.user", operator: "delete", params: { emailFrom: "data.existingEmail" } },
      { source: { caseStepId: "Clean-8", method: "api" }, id: "ory.invalid_password_empty_identity.delete", title: "删除邮箱为 `orf-register-invalid-password-empty-e2e@orf.local` 的非法密码测试登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.invalidPasswordEmptyEmail" } },
      { source: { caseStepId: "Clean-9", method: "api" }, id: "ory.invalid_password_blank_identity.delete", title: "删除邮箱为 `orf-register-invalid-password-blank-e2e@orf.local` 的非法密码测试登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.invalidPasswordBlankEmail" } },
      { source: { caseStepId: "Clean-10", method: "api" }, id: "ory.invalid_password_short_identity.delete", title: "删除邮箱为 `orf-register-invalid-password-short-e2e@orf.local` 的非法密码测试登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.invalidPasswordShortEmail" } },
      { source: { caseStepId: "Clean-11", method: "prisma" }, id: "db.invalid_password_empty_user.delete", title: "删除邮箱为 `orf-register-invalid-password-empty-e2e@orf.local` 的非法密码测试用户默认团队成员关系和用户", object: "db.user", operator: "delete", params: { emailFrom: "data.invalidPasswordEmptyEmail" } },
      { source: { caseStepId: "Clean-12", method: "prisma" }, id: "db.invalid_password_blank_user.delete", title: "删除邮箱为 `orf-register-invalid-password-blank-e2e@orf.local` 的非法密码测试用户默认团队成员关系和用户", object: "db.user", operator: "delete", params: { emailFrom: "data.invalidPasswordBlankEmail" } },
      { source: { caseStepId: "Clean-13", method: "prisma" }, id: "db.invalid_password_short_user.delete", title: "删除邮箱为 `orf-register-invalid-password-short-e2e@orf.local` 的非法密码测试用户默认团队成员关系和用户", object: "db.user", operator: "delete", params: { emailFrom: "data.invalidPasswordShortEmail" } },
      { source: { caseStepId: "Clean-14", method: "api" }, id: "ory.existing_identity.absent", title: "邮箱为 `orf-register-existing-e2e@orf.local` 的已占用邮箱测试登录身份 应不存在", object: "ory.identity", operator: "absent", params: { emailFrom: "data.existingEmail" } },
      { source: { caseStepId: "Clean-15", method: "prisma" }, id: "db.existing_user.absent", title: "邮箱为 `orf-register-existing-e2e@orf.local` 的已占用邮箱测试用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.existingEmail" } },
      { source: { caseStepId: "Clean-16", method: "api" }, id: "ory.invalid_password_empty_identity.absent", title: "邮箱为 `orf-register-invalid-password-empty-e2e@orf.local` 的登录身份 应不存在", object: "ory.identity", operator: "absent", params: { emailFrom: "data.invalidPasswordEmptyEmail" } },
      { source: { caseStepId: "Clean-17", method: "api" }, id: "ory.invalid_password_blank_identity.absent", title: "邮箱为 `orf-register-invalid-password-blank-e2e@orf.local` 的登录身份 应不存在", object: "ory.identity", operator: "absent", params: { emailFrom: "data.invalidPasswordBlankEmail" } },
      { source: { caseStepId: "Clean-18", method: "api" }, id: "ory.invalid_password_short_identity.absent", title: "邮箱为 `orf-register-invalid-password-short-e2e@orf.local` 的登录身份 应不存在", object: "ory.identity", operator: "absent", params: { emailFrom: "data.invalidPasswordShortEmail" } },
      { source: { caseStepId: "Clean-19", method: "prisma" }, id: "db.invalid_password_empty_user.absent", title: "邮箱为 `orf-register-invalid-password-empty-e2e@orf.local` 的用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.invalidPasswordEmptyEmail" } },
      { source: { caseStepId: "Clean-20", method: "prisma" }, id: "db.invalid_password_blank_user.absent", title: "邮箱为 `orf-register-invalid-password-blank-e2e@orf.local` 的用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.invalidPasswordBlankEmail" } },
      { source: { caseStepId: "Clean-21", method: "prisma" }, id: "db.invalid_password_short_user.absent", title: "邮箱为 `orf-register-invalid-password-short-e2e@orf.local` 的用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.invalidPasswordShortEmail" } },
    ],
  },
} satisfies StateCaseSpec<RegisterInvalidCredentialsCaseData>;
