import { STATE_CASE_MODEL, type StateCaseSpec } from "../../../_framework/types";
import type { MemberDeleteTaskActiveForbiddenCaseData } from "./_support/member-delete-task-active-forbidden.context";

export const memberDeleteTaskActiveForbiddenCase = {
  id: "tasks.member-delete-task-active-forbidden",
  title: "非参与的普通成员在执行中不支持删除行动项",
  model: STATE_CASE_MODEL,
  tags: ["tasks", "delete", "member", "active", "permission", "negative-path"],

  data: {
    forbiddenEmail: "orf-member-delete-task-active-forbidden-e2e@orf.local",
    forbiddenPassword: "OrfMemberDeleteTaskActiveForbiddenE2E!2026",
    forbiddenName: "ORF Member Delete Task Active Forbidden E2E",
    forbiddenRole: "member",
    challengerEmail: "orf-member-delete-task-active-challenger-e2e@orf.local",
    challengerPassword: "OrfMemberDeleteTaskActiveChallengerE2E!2026",
    challengerName: "ORF Member Delete Task Active Challenger E2E",
    challengerRole: "member",
    objectiveId: "obj-testd-member-delete-task-active-forbidden",
    objectiveTitle: "E2E-TASK-DELETE-ACTIVE-FORBIDDEN: 目标前置",
    taskId: "task-testd-member-delete-task-active-forbidden",
    taskTitle: "E2E-TASK-DELETE-ACTIVE-FORBIDDEN: 成员删除行动项",
    taskDescription: "执行中非参与普通成员不可删除行动项前置。",
    subtaskId: "ck-testd-member-delete-task-active-forbidden",
    subtaskLabel: "执行中非参与成员不可删除子任务",
    taskStatus: "Todo",
    taskPriority: "Medium",
    objectiveStatus: "Draft",
  },

  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      { source: { caseStepId: "B-1", method: "api" }, id: "frontend.ready", title: "前端服务 应可用", object: "frontend.service", operator: "available" },
      { source: { caseStepId: "B-2", method: "api" }, id: "backend.ready", title: "后端服务 应可用", object: "api.health", operator: "ok" },
      { source: { caseStepId: "B-3", method: "api" }, id: "frontend.login_entry.accessible", title: "前端登录页入口 应可访问", object: "frontend.login_entry", operator: "accessible" },
      { source: { caseStepId: "B-4", method: "api" }, id: "session.endpoint.accessible", title: "当前会话查询能力 应可用", object: "auth.session", operator: "accessible" },
      { source: { caseStepId: "B-5", method: "prisma" }, id: "db.ready", title: "ORF 数据库 应可连接", object: "db", operator: "ready" },
      { source: { caseStepId: "B-6", method: "prisma" }, id: "db.schema.current", title: "ORF 数据库 schema 应为 当前测试版本", object: "db.schema", operator: "current" },
      { source: { caseStepId: "B-7", method: "api" }, id: "ory.admin_public.ready", title: "Ory/Kratos 认证服务的管理和公共访问能力 应可用", object: "ory.admin_public", operator: "ready" },
      { source: { caseStepId: "B-8", method: "api" }, id: "session.unauthenticated", title: "当前会话 应为 未登录", object: "auth.session", operator: "unauthenticated" },
      { source: { caseStepId: "B-9", method: "playwright" }, id: "cookie.absent", title: "当前浏览器 应不存在 Ory 登录会话 cookie", object: "browser.cookie", operator: "absent" },
      { source: { caseStepId: "B-10", method: "playwright" }, id: "storage.empty", title: "当前浏览器 应不保留本地登录态", object: "browser.auth_storage", operator: "empty" },
    ],
  },

  Setup: {
    description: "准备非参与普通成员、目标挑战成员、执行中目标及其行动项，并完成非参与普通成员登录",
    steps: [
      { source: { caseStepId: "Setup-1", method: "prisma" }, id: "db.task.delete_residue", title: "删除 本用例残留的执行中测试行动项及其子行动项", object: "db.task", operator: "delete", params: { titleFrom: "data.taskTitle" } },
      { source: { caseStepId: "Setup-2", method: "prisma" }, id: "db.objective.delete_residue", title: "删除 本用例残留的执行中行动项目标及其派生数据", object: "db.objective", operator: "delete_by_title", params: { titleFrom: "data.objectiveTitle" } },
      { source: { caseStepId: "Setup-3", method: "api" }, id: "ory.forbidden_identity.upsert", title: "准备邮箱为 `orf-member-delete-task-active-forbidden-e2e@orf.local`、使用固定测试密码的非参与普通成员登录身份", object: "ory.identity", operator: "upsert_password", params: { emailFrom: "data.forbiddenEmail", nameFrom: "data.forbiddenName", passwordFrom: "data.forbiddenPassword", saveAs: "forbiddenIdentity" } },
      { source: { caseStepId: "Setup-4", method: "prisma" }, id: "db.forbidden_user.upsert", title: "准备邮箱为 `orf-member-delete-task-active-forbidden-e2e@orf.local`、角色为 `member`、状态为 `active` 的非参与普通成员用户和默认团队成员关系", object: "db.user", operator: "upsert", params: { emailFrom: "data.forbiddenEmail", nameFrom: "data.forbiddenName", roleFrom: "data.forbiddenRole", status: "active", identityIdFrom: "runtime.forbiddenIdentity.id", saveAs: "forbiddenUser" } },
      { source: { caseStepId: "Setup-5", method: "api" }, id: "ory.challenger_identity.upsert", title: "准备邮箱为 `orf-member-delete-task-active-challenger-e2e@orf.local`、使用固定测试密码的目标挑战成员登录身份", object: "ory.identity", operator: "upsert_password", params: { emailFrom: "data.challengerEmail", nameFrom: "data.challengerName", passwordFrom: "data.challengerPassword", saveAs: "challengerIdentity" } },
      { source: { caseStepId: "Setup-6", method: "prisma" }, id: "db.challenger_user.upsert", title: "准备邮箱为 `orf-member-delete-task-active-challenger-e2e@orf.local`、角色为 `member`、状态为 `active` 的目标挑战成员用户和默认团队成员关系", object: "db.user", operator: "upsert", params: { emailFrom: "data.challengerEmail", nameFrom: "data.challengerName", roleFrom: "data.challengerRole", status: "active", identityIdFrom: "runtime.challengerIdentity.id", saveAs: "challengerUser" } },
      { source: { caseStepId: "Setup-7", method: "prisma" }, id: "db.objective.upsert_task_target", title: "创建标题为 `E2E-TASK-DELETE-ACTIVE-FORBIDDEN: 目标前置`、流转状态为 `frozen`、阶段为 `goalFrozen` 的本用例执行中行动项目标", object: "db.objective", operator: "upsert", params: { idFrom: "data.objectiveId", titleFrom: "data.objectiveTitle", teamIdFrom: "runtime.challengerUser.teamId", stage: "goalFrozen", flowStatus: "frozen", statusFrom: "data.objectiveStatus", createdByFrom: "runtime.challengerUser.userId", updatedByFrom: "runtime.challengerUser.userId", saveAs: "fixtureObjective" } },
      { source: { caseStepId: "Setup-8", method: "prisma" }, id: "db.task_target.from_objective", title: "记录 本用例执行中行动项目标", object: "db.task_target", operator: "from_objective", params: { objectiveIdFrom: "runtime.fixtureObjective.id", saveAs: "taskTarget" } },
      { source: { caseStepId: "Setup-9", method: "prisma" }, id: "db.task_target.prepare_forbidden", title: "设置本用例执行中行动项目标的挑战者账号身份包含目标挑战成员且不包含非参与普通成员", object: "db.task_target", operator: "prepare_forbidden", params: { targetFrom: "runtime.taskTarget", challengerNameFrom: "data.challengerName", forbiddenNameFrom: "data.forbiddenName" } },
      { source: { caseStepId: "Setup-10", method: "prisma" }, id: "db.fixture_task.create", title: "创建标题为 `E2E-TASK-DELETE-ACTIVE-FORBIDDEN: 成员删除行动项`、执行人为目标挑战成员的本用例执行中测试行动项", object: "db.task", operator: "create_fixture", params: { idFrom: "data.taskId", targetFrom: "runtime.taskTarget", teamIdFrom: "runtime.challengerUser.teamId", userIdFrom: "runtime.challengerUser.userId", titleFrom: "data.taskTitle", descriptionFrom: "data.taskDescription", assigneeFrom: "data.challengerName", statusFrom: "data.taskStatus", priorityFrom: "data.taskPriority", saveAs: "fixtureTask" } },
      { source: { caseStepId: "Setup-11", method: "prisma" }, id: "db.fixture_subtask.create", title: "创建标签为 `执行中非参与成员不可删除子任务`、归属于本用例执行中测试行动项的本用例执行中测试子行动项", object: "db.task", operator: "create_subtask_fixture", params: { idFrom: "data.subtaskId", taskFrom: "runtime.fixtureTask", labelFrom: "data.subtaskLabel", saveAs: "fixtureSubtask" } },
      { source: { caseStepId: "Setup-12", method: "prisma" }, id: "db.fixture_task.recorded", title: "记录 本用例执行中测试行动项和测试子行动项", object: "db.task", operator: "fixture_recorded", params: { taskFrom: "runtime.fixtureTask", subtaskFrom: "runtime.fixtureSubtask" } },
      { source: { caseStepId: "Setup-13", method: "api" }, id: "ory.forbidden_sessions.revoke", title: "撤销非参与普通成员登录身份可能残留的登录会话", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.forbiddenEmail" } },
      { source: { caseStepId: "Setup-14", method: "api" }, id: "ory.challenger_sessions.revoke", title: "撤销目标挑战成员登录身份可能残留的登录会话", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.challengerEmail" } },
      { source: { caseStepId: "Setup-15", method: "playwright" }, id: "auth.logout", title: "注销当前登录会话", object: "auth", operator: "logout" },
      { source: { caseStepId: "Setup-16", method: "playwright" }, id: "page.runtime.stop", title: "离开当前 ORF 前端页面", object: "page.runtime", operator: "stop" },
      { source: { caseStepId: "Setup-17", method: "playwright" }, id: "browser.clear", title: "移除当前浏览器中的残留登录态", object: "browser", operator: "clear_state" },
      { source: { caseStepId: "Setup-18", method: "playwright" }, id: "page.goto.auth", title: "打开 ORF 登录页", object: "page", operator: "goto", params: { path: "/auth" } },
      { source: { caseStepId: "Setup-19", method: "playwright" }, id: "fill.email", title: "在邮箱输入框输入非参与普通成员固定测试邮箱", object: "page", operator: "fill", params: { label: "Email", valueFrom: "data.forbiddenEmail" } },
      { source: { caseStepId: "Setup-20", method: "playwright" }, id: "fill.password", title: "在密码输入框输入非参与普通成员固定测试密码", object: "page", operator: "fill", params: { label: "Password", exact: true, valueFrom: "data.forbiddenPassword" } },
      { source: { caseStepId: "Setup-21", method: "playwright" }, id: "click.sign_in", title: "点击 \"Sign In\" 登录操作", object: "page.login_form", operator: "submit", params: { saveAs: "forbiddenLoginResponse" } },
    ],
  },

  S0: {
    description: "非参与普通成员已登录，执行中目标存在且挑战者账号身份不包含该成员",
    assertions: [
      { source: { caseStepId: "S0-1", method: "api" }, id: "session.authenticated", title: "当前会话 应为 已登录", object: "auth.session", operator: "authenticated" },
      { source: { caseStepId: "S0-2", method: "api" }, id: "session.email", title: "当前会话用户邮箱 应为 `orf-member-delete-task-active-forbidden-e2e@orf.local`", object: "auth.session.user_email", operator: "equals", params: { emailFrom: "data.forbiddenEmail" } },
      { source: { caseStepId: "S0-3", method: "api" }, id: "session.role", title: "当前会话用户角色 应为 `member`", object: "auth.session.user_role", operator: "equals", params: { roleFrom: "data.forbiddenRole" } },
      { source: { caseStepId: "S0-4", method: "api" }, id: "session.status", title: "当前会话用户状态 应为 `active`", object: "auth.session.user_status", operator: "equals", params: { status: "active" } },
      { source: { caseStepId: "S0-5", method: "prisma" }, id: "db.task_target.flow_status", title: "本用例执行中行动项目标的流转状态 应为 `frozen`", object: "db.task_target", operator: "flow_status", params: { targetFrom: "runtime.taskTarget", status: "frozen" } },
      { source: { caseStepId: "S0-6", method: "prisma" }, id: "db.task_target.stage", title: "本用例执行中行动项目标的阶段 应为 `goalFrozen`", object: "db.task_target", operator: "stage", params: { targetFrom: "runtime.taskTarget", stage: "goalFrozen" } },
      { source: { caseStepId: "S0-7", method: "prisma" }, id: "db.task_target.challenger_present", title: "本用例执行中行动项目标的挑战者账号身份 应包含 目标挑战成员", object: "db.task_target", operator: "challenger_present", params: { targetFrom: "runtime.taskTarget", memberNameFrom: "data.challengerName" } },
      { source: { caseStepId: "S0-8", method: "prisma" }, id: "db.task_target.forbidden_absent", title: "本用例执行中行动项目标的挑战者账号身份 应不包含 非参与普通成员", object: "db.task_target", operator: "challenger_absent", params: { targetFrom: "runtime.taskTarget", memberNameFrom: "data.forbiddenName" } },
      { source: { caseStepId: "S0-9", method: "prisma" }, id: "db.task_target.task_present", title: "本用例执行中行动项目标 应存在 标题为 `E2E-TASK-DELETE-ACTIVE-FORBIDDEN: 成员删除行动项` 的行动项", object: "db.task_target", operator: "task_present", params: { targetFrom: "runtime.taskTarget", taskFrom: "runtime.fixtureTask" } },
      { source: { caseStepId: "S0-10", method: "prisma" }, id: "db.fixture_subtask.present", title: "本用例执行中测试行动项下 应存在 标签为 `执行中非参与成员不可删除子任务` 的子行动项", object: "db.task", operator: "subtask_present", params: { taskFrom: "runtime.fixtureTask", labelFrom: "data.subtaskLabel" } },
      { source: { caseStepId: "S0-11", method: "prisma" }, id: "db.task_target.cannot_delete", title: "本用例执行中行动项目标 应不允许 当前非参与普通成员删除行动项", object: "db.task_target", operator: "cannot_delete_task", params: { targetFrom: "runtime.taskTarget", actorNameFrom: "data.forbiddenName", roleFrom: "data.forbiddenRole" } },
    ],
  },

  Action: {
    description: "非参与普通成员进入挑战工作台并筛选执行中目标",
    steps: [
      { source: { caseStepId: "Action-1", method: "playwright" }, id: "page.goto.tasks", title: "非参与普通成员打开 挑战工作台", object: "page", operator: "goto", params: { path: "/tasks" } },
      { source: { caseStepId: "Action-2", method: "playwright" }, id: "challenge.scope.mine", title: "切换到 \"我的挑战\" 视图", object: "page.challenge_scope", operator: "select", params: { label: "我的挑战" } },
      { source: { caseStepId: "Action-3", method: "playwright" }, id: "challenge.status.active", title: "将状态筛选切换到 \"执行中\"", object: "page.challenge_status_filter", operator: "select", params: { label: "执行中" } },
    ],
  },

  S1: {
    description: "非参与普通成员看不到目标和删除入口，数据库中的行动项及子行动项仍然保留",
    assertions: [
      { source: { caseStepId: "S1-1", method: "playwright" }, id: "url.tasks", title: "当前页面 应为 挑战工作台", object: "page.url", operator: "match", params: { pattern: "/tasks$" } },
      { source: { caseStepId: "S1-2", method: "playwright" }, id: "scope.mine.selected", title: "\"我的挑战\" 视图 应处于选中状态", object: "page.challenge_scope", operator: "selected", params: { label: "我的挑战" } },
      { source: { caseStepId: "S1-3", method: "playwright" }, id: "status.active.selected", title: "\"执行中\" 状态筛选 应处于选中状态", object: "page.challenge_status_filter", operator: "selected", params: { label: "执行中" } },
      { source: { caseStepId: "S1-4", method: "playwright" }, id: "target.panel.absent", title: "本用例执行中行动项目标面板 应不可见", object: "page.task_target", operator: "absent", params: { targetFrom: "runtime.taskTarget" } },
      { source: { caseStepId: "S1-5", method: "playwright" }, id: "fixture_task.delete_absent", title: "本用例执行中测试行动项的 \"删除\" 操作 应不可见", object: "page.task_target", operator: "delete_action_absent", params: { targetFrom: "runtime.taskTarget", taskFrom: "runtime.fixtureTask" } },
      { source: { caseStepId: "S1-6", method: "api" }, id: "api.member_workbench.objective_absent", title: "非参与普通成员的挑战工作台数据 应不包含 本用例执行中行动项目标", object: "api.member_workbench", operator: "objective_absent", params: { targetFrom: "runtime.taskTarget" } },
      { source: { caseStepId: "S1-7", method: "api" }, id: "api.member_workbench.task_absent", title: "非参与普通成员的挑战工作台数据 应不包含 本用例执行中测试行动项", object: "api.member_workbench", operator: "task_absent", params: { taskFrom: "runtime.fixtureTask" } },
      { source: { caseStepId: "S1-8", method: "prisma" }, id: "db.task_target.task_present", title: "本用例执行中行动项目标 应仍存在 标题为 `E2E-TASK-DELETE-ACTIVE-FORBIDDEN: 成员删除行动项` 的行动项", object: "db.task_target", operator: "task_present", params: { targetFrom: "runtime.taskTarget", taskFrom: "runtime.fixtureTask" } },
      { source: { caseStepId: "S1-9", method: "prisma" }, id: "db.fixture_subtask.present", title: "本用例执行中测试行动项下 应仍存在 标签为 `执行中非参与成员不可删除子任务` 的子行动项", object: "db.task", operator: "subtask_present", params: { taskFrom: "runtime.fixtureTask", labelFrom: "data.subtaskLabel" } },
      { source: { caseStepId: "S1-10", method: "prisma" }, id: "db.task_target.forbidden_absent", title: "本用例执行中行动项目标的挑战者账号身份 应仍不包含 非参与普通成员", object: "db.task_target", operator: "challenger_absent", params: { targetFrom: "runtime.taskTarget", memberNameFrom: "data.forbiddenName" } },
      { source: { caseStepId: "S1-11", method: "prisma" }, id: "db.task_target.flow_status", title: "本用例执行中行动项目标的流转状态 应仍为 `frozen`", object: "db.task_target", operator: "flow_status", params: { targetFrom: "runtime.taskTarget", status: "frozen" } },
      { source: { caseStepId: "S1-12", method: "prisma" }, id: "db.task_target.stage", title: "本用例执行中行动项目标的阶段 应仍为 `goalFrozen`", object: "db.task_target", operator: "stage", params: { targetFrom: "runtime.taskTarget", stage: "goalFrozen" } },
      { source: { caseStepId: "S1-13", method: "api" }, id: "session.authenticated.still", title: "当前会话 应仍为 已登录", object: "auth.session", operator: "authenticated" },
      { source: { caseStepId: "S1-14", method: "api" }, id: "session.email.still", title: "当前会话用户邮箱 应仍为 `orf-member-delete-task-active-forbidden-e2e@orf.local`", object: "auth.session.user_email", operator: "equals", params: { emailFrom: "data.forbiddenEmail" } },
      { source: { caseStepId: "S1-15", method: "api" }, id: "session.role.still", title: "当前会话用户角色 应仍为 `member`", object: "auth.session.user_role", operator: "equals", params: { roleFrom: "data.forbiddenRole" } },
      { source: { caseStepId: "S1-16", method: "api" }, id: "session.status.still", title: "当前会话用户状态 应仍为 `active`", object: "auth.session.user_status", operator: "equals", params: { status: "active" } },
    ],
  },

  Clean: {
    description: "删除执行中目标、测试行动项、测试子行动项、两个普通成员身份与浏览器状态",
    steps: [
      { source: { caseStepId: "Clean-1", method: "prisma" }, id: "db.task.delete", title: "删除 本用例残留的执行中测试行动项及其子行动项", object: "db.task", operator: "delete", params: { titleFrom: "data.taskTitle", taskFrom: "runtime.fixtureTask" } },
      { source: { caseStepId: "Clean-2", method: "prisma" }, id: "db.objective.delete", title: "删除 本用例执行中行动项目标及其派生数据", object: "db.objective", operator: "delete_by_title", params: { titleFrom: "data.objectiveTitle" } },
      { source: { caseStepId: "Clean-3", method: "api" }, id: "auth.logout", title: "注销当前登录会话", object: "auth", operator: "logout" },
      { source: { caseStepId: "Clean-4", method: "playwright" }, id: "page.runtime.stop", title: "离开当前 ORF 前端页面", object: "page.runtime", operator: "stop" },
      { source: { caseStepId: "Clean-5", method: "playwright" }, id: "browser.clear", title: "移除当前浏览器中的残留登录态", object: "browser", operator: "clear_state" },
      { source: { caseStepId: "Clean-6", method: "api" }, id: "ory.forbidden_sessions.revoke", title: "撤销非参与普通成员登录身份的残留登录会话", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.forbiddenEmail" } },
      { source: { caseStepId: "Clean-7", method: "api" }, id: "ory.challenger_sessions.revoke", title: "撤销目标挑战成员登录身份的残留登录会话", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.challengerEmail" } },
      { source: { caseStepId: "Clean-8", method: "api" }, id: "ory.forbidden_identity.delete", title: "删除邮箱为 `orf-member-delete-task-active-forbidden-e2e@orf.local` 的非参与普通成员登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.forbiddenEmail" } },
      { source: { caseStepId: "Clean-9", method: "api" }, id: "ory.challenger_identity.delete", title: "删除邮箱为 `orf-member-delete-task-active-challenger-e2e@orf.local` 的目标挑战成员登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.challengerEmail" } },
      { source: { caseStepId: "Clean-10", method: "prisma" }, id: "db.forbidden_membership.delete", title: "删除邮箱为 `orf-member-delete-task-active-forbidden-e2e@orf.local` 的非参与普通成员用户默认团队成员关系", object: "db.user", operator: "delete_memberships", params: { emailFrom: "data.forbiddenEmail" } },
      { source: { caseStepId: "Clean-11", method: "prisma" }, id: "db.challenger_membership.delete", title: "删除邮箱为 `orf-member-delete-task-active-challenger-e2e@orf.local` 的目标挑战成员用户默认团队成员关系", object: "db.user", operator: "delete_memberships", params: { emailFrom: "data.challengerEmail" } },
      { source: { caseStepId: "Clean-12", method: "prisma" }, id: "db.forbidden_user.delete", title: "删除邮箱为 `orf-member-delete-task-active-forbidden-e2e@orf.local` 的非参与普通成员用户", object: "db.user", operator: "delete", params: { emailFrom: "data.forbiddenEmail" } },
      { source: { caseStepId: "Clean-13", method: "prisma" }, id: "db.challenger_user.delete", title: "删除邮箱为 `orf-member-delete-task-active-challenger-e2e@orf.local` 的目标挑战成员用户", object: "db.user", operator: "delete", params: { emailFrom: "data.challengerEmail" } },
      { source: { caseStepId: "Clean-14", method: "prisma" }, id: "db.task.absent", title: "应不存在 标题为 `E2E-TASK-DELETE-ACTIVE-FORBIDDEN: 成员删除行动项` 的测试行动项", object: "db.task", operator: "absent", params: { titleFrom: "data.taskTitle" } },
      { source: { caseStepId: "Clean-15", method: "prisma" }, id: "db.objective.absent", title: "应不存在 标题为 `E2E-TASK-DELETE-ACTIVE-FORBIDDEN: 目标前置` 的测试目标", object: "db.objective", operator: "absent", params: { titleFrom: "data.objectiveTitle" } },
      { source: { caseStepId: "Clean-16", method: "api" }, id: "ory.forbidden_identity.absent", title: "邮箱为 `orf-member-delete-task-active-forbidden-e2e@orf.local` 的非参与普通成员登录身份 应不存在", object: "ory.identity", operator: "absent", params: { emailFrom: "data.forbiddenEmail" } },
      { source: { caseStepId: "Clean-17", method: "api" }, id: "ory.challenger_identity.absent", title: "邮箱为 `orf-member-delete-task-active-challenger-e2e@orf.local` 的目标挑战成员登录身份 应不存在", object: "ory.identity", operator: "absent", params: { emailFrom: "data.challengerEmail" } },
      { source: { caseStepId: "Clean-18", method: "prisma" }, id: "db.forbidden_user.absent", title: "邮箱为 `orf-member-delete-task-active-forbidden-e2e@orf.local` 的非参与普通成员用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.forbiddenEmail" } },
      { source: { caseStepId: "Clean-19", method: "prisma" }, id: "db.challenger_user.absent", title: "邮箱为 `orf-member-delete-task-active-challenger-e2e@orf.local` 的目标挑战成员用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.challengerEmail" } },
    ],
  },
} satisfies StateCaseSpec<MemberDeleteTaskActiveForbiddenCaseData>;
