import { STATE_CASE_MODEL, type StateCaseSpec, type StepExecutionMethod, type StepSpec } from "../../_framework/types";
import type { PersonalSettingsPreferencesCaseData } from "./_support/personal-settings-preferences.context";

function step(
  caseStepId: string,
  method: StepExecutionMethod,
  id: string,
  title: string,
  object: string,
  operator: string,
  params?: Record<string, unknown>,
): StepSpec {
  return {
    source: { caseStepId, method },
    id,
    title,
    object,
    operator,
    ...(params ? { params } : {}),
  };
}

export const personalSettingsPreferencesCase = {
  id: "defaults.personal-settings.preferences",
  title: "15-个人设置默认进入页面和侧边栏状态",
  model: STATE_CASE_MODEL,
  tags: ["defaults", "personal-settings", "preferences", "sidebar"],
  data: {
    email: "orf-default-page-preferences-e2e@orf.local",
    password: "OrfDefaultPagePreferencesE2E!2026",
    name: "ORF 默认页偏好设置用户",
    role: "member",
    status: "active",
    settingsPathPattern: "/settings$",
    feedbackPathPattern: "/feedback$",
    systemDefaultPathPattern: "/tasks$",
    feedbackLandingPath: "/feedback",
  },
  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      step("B-1", "api", "frontend.ready", "前端服务 应可用", "frontend.service", "available"),
      step("B-2", "api", "backend.ready", "后端服务 应可用", "api.health", "ok"),
      step("B-3", "api", "frontend.login_entry.accessible", "前端登录页入口 应可访问", "frontend.login_entry", "accessible"),
      step("B-4", "api", "session.endpoint.accessible", "当前会话查询能力 应可用", "auth.session", "accessible"),
      step("B-5", "prisma", "db.ready", "ORF 数据库 应可连接", "db", "ready"),
      step("B-6", "prisma", "db.schema.current", "ORF 数据库 schema 应为 当前测试版本", "db.schema", "current"),
      step("B-7", "api", "ory.admin_public.ready", "Ory/Kratos 认证服务的管理和公共访问能力 应可用", "ory.admin_public", "ready"),
      step("B-8", "api", "session.unauthenticated", "当前会话 应为 未登录", "auth.session", "unauthenticated"),
      step("B-9", "playwright", "cookie.absent", "当前浏览器 应不存在 Ory 登录会话 cookie", "browser.cookie", "absent"),
      step("B-10", "playwright", "storage.empty", "当前浏览器 应不保留本地登录态", "browser.auth_storage", "empty"),
    ],
  },
  Setup: {
    description: "准备系统默认偏好的测试用户，并登录进入个人设置页面",
    steps: [
      step("Setup-1", "api", "ory.identity.upsert", "准备邮箱为 `orf-default-page-preferences-e2e@orf.local`、使用固定测试密码的个人设置偏好测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.email", passwordFrom: "data.password", nameFrom: "data.name", saveAs: "identity" }),
      step("Setup-2", "prisma", "db.user.upsert", "准备邮箱为 `orf-default-page-preferences-e2e@orf.local`、姓名为 `ORF 默认页偏好设置用户`、角色为 `member`、状态为 `active` 的个人设置偏好测试用户", "db.user", "upsert", { emailFrom: "data.email", passwordFrom: "data.password", nameFrom: "data.name", roleFrom: "data.role", statusFrom: "data.status", identityIdFrom: "runtime.identity.id", saveAs: "user" }),
      step("Setup-3", "api", "preferences.default_landing.system", "设置个人设置偏好测试用户默认进入页面为 系统默认", "user.preferences", "reset_default_landing_path_by_email", { emailFrom: "data.email" }),
      step("Setup-4", "api", "preferences.sidebar.system", "设置个人设置偏好测试用户侧边栏默认状态为 系统默认", "user.preferences", "set_sidebar_state_by_email", { emailFrom: "data.email", state: "system" }),
      step("Setup-5", "api", "ory.sessions.revoke", "撤销邮箱为 `orf-default-page-preferences-e2e@orf.local` 的个人设置偏好测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.email" }),
      step("Setup-6", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Setup-7", "playwright", "page.goto.auth", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Setup-8", "playwright", "fill.email", "在邮箱输入框输入 `orf-default-page-preferences-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.email" }),
      step("Setup-9", "playwright", "fill.password", "在密码输入框输入个人设置偏好测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.password" }),
      step("Setup-10", "playwright", "click.sign_in", "点击 \"Sign In\" 登录操作", "page.login_form", "submit", { saveAs: "loginResponse" }),
      step("Setup-11", "api", "session.authenticated", "当前会话 应为 邮箱为 `orf-default-page-preferences-e2e@orf.local`、角色为 `member`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.email", roleFrom: "data.role", statusFrom: "data.status" }),
      step("Setup-12", "playwright", "page.goto.settings", "打开 个人设置页面", "page", "goto", { path: "/settings" }),
    ],
  },
  S0: {
    description: "测试用户位于个人设置页，默认进入页面和侧边栏默认状态均为系统默认",
    assertions: [
      step("S0-1", "api", "session.authenticated", "当前会话 应为 邮箱为 `orf-default-page-preferences-e2e@orf.local`、角色为 `member`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.email", roleFrom: "data.role", statusFrom: "data.status" }),
      step("S0-2", "playwright", "personal_settings.page.visible", "当前页面 应为 个人设置页面", "personal_settings.page", "visible", { patternFrom: "data.settingsPathPattern" }),
      step("S0-3", "playwright", "personal_settings.default_landing.system", "个人设置页面的默认进入页面设置项 应显示 系统默认", "personal_settings.default_landing", "selected", { label: "系统默认" }),
      step("S0-4", "playwright", "personal_settings.default_landing.enabled", "个人设置页面的默认进入页面设置项 应可选择", "personal_settings.default_landing", "enabled"),
      step("S0-5", "playwright", "personal_settings.sidebar_state.system", "个人设置页面的侧边栏默认状态设置项 应显示 系统默认", "personal_settings.sidebar_state", "selected", { label: "系统默认" }),
      step("S0-6", "playwright", "personal_settings.sidebar_state.enabled", "个人设置页面的侧边栏默认状态设置项 应可选择", "personal_settings.sidebar_state", "enabled"),
      step("S0-7", "api", "preferences.default_landing.system", "个人设置偏好测试用户的默认进入页面偏好 应为 系统默认", "user.preferences", "default_landing_is", { emailFrom: "data.email", path: null }),
      step("S0-8", "api", "preferences.sidebar.system", "个人设置偏好测试用户的侧边栏默认状态偏好 应为 系统默认", "user.preferences", "sidebar_state_is", { emailFrom: "data.email", state: "system" }),
    ],
  },
  Action: {
    description: "选择默认进入页面和侧边栏默认状态，并通过重新登录触发偏好生效",
    steps: [
      step("Action-1", "playwright", "default_landing.select.feedback", "在个人设置页面的默认进入页面设置项选择 `反馈`", "personal_settings.default_landing", "select", { emailFrom: "data.email", label: "反馈", saveAs: "feedbackPreferenceSnapshot" }),
      step("Action-2", "api", "auth.logout.after_feedback_select", "注销当前登录会话", "auth", "logout"),
      step("Action-3", "playwright", "browser.clear.after_feedback_select", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Action-4", "playwright", "page.goto.auth.after_feedback_select", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Action-5", "playwright", "fill.email.after_feedback_select", "在邮箱输入框输入 `orf-default-page-preferences-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.email" }),
      step("Action-6", "playwright", "fill.password.after_feedback_select", "在密码输入框输入个人设置偏好测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.password" }),
      step("Action-7", "playwright", "click.sign_in.after_feedback_select", "点击 \"Sign In\" 登录操作", "page.login_form", "submit", { saveAs: "feedbackLoginResponse" }),
      step("Action-8", "playwright", "page.goto.settings.after_feedback_login", "打开 个人设置页面", "preferences_flow", "open_settings_from_current_page", { expectedPathPatternFrom: "data.feedbackPathPattern", saveAs: "feedbackLandingSnapshot" }),
      step("Action-9", "playwright", "default_landing.select.system", "在个人设置页面的默认进入页面设置项选择 系统默认", "personal_settings.default_landing", "select", { emailFrom: "data.email", label: "系统默认", saveAs: "systemPreferenceSnapshot" }),
      step("Action-10", "api", "auth.logout.after_system_select", "注销当前登录会话", "auth", "logout"),
      step("Action-11", "playwright", "browser.clear.after_system_select", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Action-12", "playwright", "page.goto.auth.after_system_select", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Action-13", "playwright", "fill.email.after_system_select", "在邮箱输入框输入 `orf-default-page-preferences-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.email" }),
      step("Action-14", "playwright", "fill.password.after_system_select", "在密码输入框输入个人设置偏好测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.password" }),
      step("Action-15", "playwright", "click.sign_in.after_system_select", "点击 \"Sign In\" 登录操作", "page.login_form", "submit", { saveAs: "systemLoginResponse" }),
      step("Action-16", "playwright", "page.goto.settings.after_system_login", "打开 个人设置页面", "preferences_flow", "open_settings_from_current_page", { expectedPathPatternFrom: "data.systemDefaultPathPattern", saveAs: "systemLandingSnapshot" }),
      step("Action-17", "playwright", "sidebar_state.select.expanded", "在个人设置页面的侧边栏默认状态设置项选择 `展开`", "personal_settings.sidebar_state", "select", { emailFrom: "data.email", label: "展开", saveAs: "expandedPreferenceSnapshot" }),
      step("Action-18", "api", "auth.logout.after_expanded_select", "注销当前登录会话", "auth", "logout"),
      step("Action-19", "playwright", "browser.clear.after_expanded_select", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Action-20", "playwright", "page.goto.auth.after_expanded_select", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Action-21", "playwright", "fill.email.after_expanded_select", "在邮箱输入框输入 `orf-default-page-preferences-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.email" }),
      step("Action-22", "playwright", "fill.password.after_expanded_select", "在密码输入框输入个人设置偏好测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.password" }),
      step("Action-23", "playwright", "click.sign_in.after_expanded_select", "点击 \"Sign In\" 登录操作", "page.login_form", "submit", { saveAs: "expandedLoginResponse" }),
      step("Action-24", "playwright", "page.goto.settings.after_expanded_login", "打开 个人设置页面", "preferences_flow", "open_settings_from_current_page", { expectedPathPatternFrom: "data.systemDefaultPathPattern", saveAs: "expandedSidebarSnapshot" }),
      step("Action-25", "playwright", "sidebar_state.select.collapsed", "在个人设置页面的侧边栏默认状态设置项选择 `折叠`", "personal_settings.sidebar_state", "select", { emailFrom: "data.email", label: "折叠", saveAs: "collapsedPreferenceSnapshot" }),
      step("Action-26", "api", "auth.logout.after_collapsed_select", "注销当前登录会话", "auth", "logout"),
      step("Action-27", "playwright", "browser.clear.after_collapsed_select", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Action-28", "playwright", "page.goto.auth.after_collapsed_select", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Action-29", "playwright", "fill.email.after_collapsed_select", "在邮箱输入框输入 `orf-default-page-preferences-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.email" }),
      step("Action-30", "playwright", "fill.password.after_collapsed_select", "在密码输入框输入个人设置偏好测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.password" }),
      step("Action-31", "playwright", "click.sign_in.after_collapsed_select", "点击 \"Sign In\" 登录操作", "preferences_login_form", "submit_capture_sidebar", { saveAs: "collapsedSidebarSnapshot" }),
    ],
  },
  S1: {
    description: "默认进入页面和侧边栏默认状态偏好在重新登录后均生效",
    assertions: [
      step("S1-1", "playwright", "snapshot.feedback_landing.page", "默认进入页面选择 `反馈` 后重新登录进入的页面 应为 反馈页面", "preferences_snapshot", "page_matches", { snapshotFrom: "runtime.feedbackLandingSnapshot", patternFrom: "data.feedbackPathPattern" }),
      step("S1-2", "api", "snapshot.feedback_landing.saved", "默认进入页面选择 `反馈` 后，个人设置偏好测试用户的默认进入页面偏好 应为 `反馈`", "preferences_snapshot", "default_landing", { snapshotFrom: "runtime.feedbackPreferenceSnapshot", pathFrom: "data.feedbackLandingPath" }),
      step("S1-3", "playwright", "snapshot.system_landing.page", "默认进入页面选择 系统默认 后重新登录进入的页面 应为 系统默认页面", "preferences_snapshot", "page_matches", { snapshotFrom: "runtime.systemLandingSnapshot", patternFrom: "data.systemDefaultPathPattern" }),
      step("S1-4", "api", "preferences.system_landing.saved", "默认进入页面选择 系统默认 后，个人设置偏好测试用户的默认进入页面偏好 应为 系统默认", "user.preferences", "default_landing_is", { emailFrom: "data.email", path: null }),
      step("S1-5", "playwright", "snapshot.sidebar_expanded", "侧边栏默认状态选择 `展开` 后重新进入系统，侧边栏 应为 展开状态", "preferences_snapshot", "sidebar_state", { snapshotFrom: "runtime.expandedSidebarSnapshot", state: "expanded" }),
      step("S1-6", "api", "snapshot.sidebar_expanded.saved", "侧边栏默认状态选择 `展开` 后，个人设置偏好测试用户的侧边栏默认状态偏好 应为 展开", "preferences_snapshot", "saved_sidebar_state", { snapshotFrom: "runtime.expandedPreferenceSnapshot", state: "expanded" }),
      step("S1-7", "playwright", "snapshot.sidebar_collapsed", "侧边栏默认状态选择 `折叠` 后重新进入系统，侧边栏 应为 折叠状态", "preferences_snapshot", "sidebar_state", { snapshotFrom: "runtime.collapsedSidebarSnapshot", state: "collapsed" }),
      step("S1-8", "api", "preferences.sidebar_collapsed.saved", "侧边栏默认状态选择 `折叠` 后，个人设置偏好测试用户的侧边栏默认状态偏好 应为 折叠", "user.preferences", "sidebar_state_is", { emailFrom: "data.email", state: "collapsed" }),
      step("S1-9", "api", "session.authenticated", "当前会话 应为 邮箱为 `orf-default-page-preferences-e2e@orf.local`、角色为 `member`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.email", roleFrom: "data.role", statusFrom: "data.status" }),
    ],
  },
  Clean: {
    description: "删除测试用户偏好、账号和页面会话状态，恢复未登录基准状态",
    steps: [
      step("Clean-1", "api", "auth.logout", "注销当前登录会话", "auth", "logout"),
      step("Clean-2", "playwright", "page.runtime.stop", "离开当前 ORF 前端页面", "page.runtime", "stop"),
      step("Clean-3", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Clean-4", "api", "ory.sessions.revoke", "撤销邮箱为 `orf-default-page-preferences-e2e@orf.local` 的个人设置偏好测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.email" }),
      step("Clean-5", "api", "preferences.default_landing.reset", "恢复邮箱为 `orf-default-page-preferences-e2e@orf.local` 的默认进入页面为 系统默认", "user.preferences", "reset_default_landing_path_by_email", { emailFrom: "data.email" }),
      step("Clean-6", "api", "preferences.sidebar.reset", "恢复邮箱为 `orf-default-page-preferences-e2e@orf.local` 的侧边栏默认状态为 系统默认", "user.preferences", "set_sidebar_state_by_email", { emailFrom: "data.email", state: "system" }),
      step("Clean-7", "api", "ory.identity.delete", "删除邮箱为 `orf-default-page-preferences-e2e@orf.local` 的个人设置偏好测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.email" }),
      step("Clean-8", "prisma", "db.user.memberships.delete", "删除邮箱为 `orf-default-page-preferences-e2e@orf.local` 的个人设置偏好测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.email" }),
      step("Clean-9", "prisma", "db.user.delete", "删除邮箱为 `orf-default-page-preferences-e2e@orf.local` 的个人设置偏好测试用户", "db.user", "delete", { emailFrom: "data.email" }),
      step("Clean-10", "api", "ory.identity.absent", "邮箱为 `orf-default-page-preferences-e2e@orf.local` 的个人设置偏好测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.email" }),
      step("Clean-11", "prisma", "db.user.absent", "邮箱为 `orf-default-page-preferences-e2e@orf.local` 的个人设置偏好测试用户 应不存在", "db.user", "absent", { emailFrom: "data.email" }),
    ],
  },
} satisfies StateCaseSpec<PersonalSettingsPreferencesCaseData>;
