import type { ObjectiveFlowStatus } from "../../types/orf";
import type { ObjectiveFlowPolicy, ObjectiveLifecycleTarget } from "./types";

const editableStages = ["goalSetting", "resultClaiming", "orfReestimate"] as const;
const reestimateStage = ["orfReestimate"] as const;
const frozenStage = ["goalFrozen"] as const;

export const objectiveFlowStatuses = [
  "candidate",
  "open",
  "applying",
  "recruiting",
  "reestimating",
  "frozen",
  "submitted",
  "accepted",
  "settled",
  "closed",
] as const satisfies readonly ObjectiveFlowStatus[];

export const objectiveFlowPolicy = {
  candidate: {
    label: "候选中",
    phase: "planning",
    tone: "open",
    compatibleStages: editableStages,
    challengeSortRank: 0,
    canPublish: true,
    canApplyForChallenge: false,
    canReviewChallengeApplications: false,
    canRecruitChallengers: false,
    canReinforceChallengers: false,
    canAcceptChallenge: false,
    canMutateResults: true,
    canMutateWorkItems: true,
    canMutateComments: true,
    canMutateCommentsAsChallenger: false,
    canDeleteObjective: true,
    canFreezeAfterReestimate: false,
    canSubmitLoot: false,
    canSubmitContributionReview: false,
    canReviewLoot: false,
    canSettleLoot: false,
    challengeDiscoverable: false,
    bountyHallVisible: false,
    challengeAccepted: false,
    challengeEntryClosed: false,
    resultLocked: false,
    rendersAsFrozen: false,
    submitted: false,
    accepted: false,
    settledOrClosed: false,
  },
  open: {
    label: "可申请",
    phase: "discoverable",
    tone: "open",
    compatibleStages: editableStages,
    challengeSortRank: 1,
    assignedChallengeSortRank: 2,
    canPublish: false,
    canApplyForChallenge: true,
    canReviewChallengeApplications: false,
    canRecruitChallengers: true,
    canReinforceChallengers: false,
    canAcceptChallenge: false,
    canMutateResults: true,
    canMutateWorkItems: false,
    canMutateComments: true,
    canMutateCommentsAsChallenger: false,
    canDeleteObjective: true,
    canFreezeAfterReestimate: false,
    canSubmitLoot: false,
    canSubmitContributionReview: false,
    canReviewLoot: false,
    canSettleLoot: false,
    challengeDiscoverable: true,
    bountyHallVisible: true,
    challengeAccepted: false,
    challengeEntryClosed: false,
    resultLocked: false,
    rendersAsFrozen: false,
    submitted: false,
    accepted: false,
    settledOrClosed: false,
  },
  applying: {
    label: "申请中",
    phase: "forming",
    tone: "active",
    compatibleStages: editableStages,
    challengeSortRank: 1,
    assignedChallengeSortRank: 2,
    canPublish: false,
    canApplyForChallenge: true,
    canReviewChallengeApplications: true,
    canRecruitChallengers: true,
    canReinforceChallengers: false,
    canAcceptChallenge: false,
    canMutateResults: true,
    canMutateWorkItems: false,
    canMutateComments: true,
    canMutateCommentsAsChallenger: false,
    canDeleteObjective: true,
    canFreezeAfterReestimate: false,
    canSubmitLoot: false,
    canSubmitContributionReview: false,
    canReviewLoot: false,
    canSettleLoot: false,
    challengeDiscoverable: true,
    bountyHallVisible: true,
    challengeAccepted: false,
    challengeEntryClosed: false,
    resultLocked: false,
    rendersAsFrozen: false,
    submitted: false,
    accepted: false,
    settledOrClosed: false,
  },
  recruiting: {
    label: "征召中",
    phase: "forming",
    tone: "active",
    compatibleStages: editableStages,
    challengeSortRank: 1,
    assignedChallengeSortRank: 2,
    canPublish: false,
    canApplyForChallenge: true,
    canReviewChallengeApplications: true,
    canRecruitChallengers: true,
    canReinforceChallengers: false,
    canAcceptChallenge: true,
    canMutateResults: true,
    canMutateWorkItems: false,
    canMutateComments: true,
    canMutateCommentsAsChallenger: false,
    canDeleteObjective: true,
    canFreezeAfterReestimate: false,
    canSubmitLoot: false,
    canSubmitContributionReview: false,
    canReviewLoot: false,
    canSettleLoot: false,
    challengeDiscoverable: true,
    bountyHallVisible: true,
    challengeAccepted: false,
    challengeEntryClosed: false,
    resultLocked: false,
    rendersAsFrozen: false,
    submitted: false,
    accepted: false,
    settledOrClosed: false,
  },
  reestimating: {
    label: "重估中",
    phase: "active",
    tone: "active",
    compatibleStages: reestimateStage,
    challengeSortRank: 3,
    canPublish: false,
    canApplyForChallenge: true,
    canReviewChallengeApplications: true,
    canRecruitChallengers: true,
    canReinforceChallengers: false,
    canAcceptChallenge: true,
    canMutateResults: true,
    canMutateWorkItems: true,
    canMutateComments: true,
    canMutateCommentsAsChallenger: true,
    canDeleteObjective: true,
    canFreezeAfterReestimate: true,
    canSubmitLoot: false,
    canSubmitContributionReview: false,
    canReviewLoot: false,
    canSettleLoot: false,
    challengeDiscoverable: true,
    bountyHallVisible: true,
    challengeAccepted: true,
    challengeEntryClosed: false,
    resultLocked: false,
    rendersAsFrozen: false,
    submitted: false,
    accepted: false,
    settledOrClosed: false,
  },
  frozen: {
    label: "已冻结",
    phase: "active",
    tone: "active",
    compatibleStages: frozenStage,
    challengeSortRank: 3,
    canPublish: false,
    canApplyForChallenge: false,
    canReviewChallengeApplications: false,
    canRecruitChallengers: false,
    canReinforceChallengers: true,
    canAcceptChallenge: false,
    canMutateResults: false,
    canMutateWorkItems: true,
    canMutateComments: true,
    canMutateCommentsAsChallenger: true,
    canDeleteObjective: true,
    canFreezeAfterReestimate: false,
    canSubmitLoot: true,
    canSubmitContributionReview: false,
    canReviewLoot: false,
    canSettleLoot: false,
    challengeDiscoverable: false,
    bountyHallVisible: true,
    challengeAccepted: true,
    challengeEntryClosed: false,
    resultLocked: true,
    rendersAsFrozen: true,
    submitted: false,
    accepted: false,
    settledOrClosed: false,
  },
  submitted: {
    label: "待验收",
    phase: "review",
    tone: "review",
    compatibleStages: frozenStage,
    challengeSortRank: 4,
    canPublish: false,
    canApplyForChallenge: false,
    canReviewChallengeApplications: false,
    canRecruitChallengers: false,
    canReinforceChallengers: false,
    canAcceptChallenge: false,
    canMutateResults: false,
    canMutateWorkItems: false,
    canMutateComments: true,
    canMutateCommentsAsChallenger: true,
    canDeleteObjective: false,
    canFreezeAfterReestimate: false,
    canSubmitLoot: false,
    canSubmitContributionReview: false,
    canReviewLoot: true,
    canSettleLoot: false,
    challengeDiscoverable: false,
    bountyHallVisible: true,
    challengeAccepted: false,
    challengeEntryClosed: true,
    resultLocked: true,
    rendersAsFrozen: true,
    submitted: true,
    accepted: false,
    settledOrClosed: false,
  },
  accepted: {
    label: "已验收",
    phase: "accepted",
    tone: "review",
    compatibleStages: frozenStage,
    challengeSortRank: 5,
    canPublish: false,
    canApplyForChallenge: false,
    canReviewChallengeApplications: false,
    canRecruitChallengers: false,
    canReinforceChallengers: false,
    canAcceptChallenge: false,
    canMutateResults: false,
    canMutateWorkItems: false,
    canMutateComments: true,
    canMutateCommentsAsChallenger: true,
    canDeleteObjective: false,
    canFreezeAfterReestimate: false,
    canSubmitLoot: false,
    canSubmitContributionReview: true,
    canReviewLoot: false,
    canSettleLoot: true,
    challengeDiscoverable: false,
    bountyHallVisible: true,
    challengeAccepted: false,
    challengeEntryClosed: true,
    resultLocked: true,
    rendersAsFrozen: true,
    submitted: false,
    accepted: true,
    settledOrClosed: false,
  },
  settled: {
    label: "已结算",
    phase: "settled",
    tone: "done",
    compatibleStages: frozenStage,
    challengeSortRank: 6,
    canPublish: false,
    canApplyForChallenge: false,
    canReviewChallengeApplications: false,
    canRecruitChallengers: false,
    canReinforceChallengers: false,
    canAcceptChallenge: false,
    canMutateResults: false,
    canMutateWorkItems: false,
    canMutateComments: false,
    canMutateCommentsAsChallenger: false,
    canDeleteObjective: false,
    canFreezeAfterReestimate: false,
    canSubmitLoot: false,
    canSubmitContributionReview: false,
    canReviewLoot: false,
    canSettleLoot: false,
    challengeDiscoverable: false,
    bountyHallVisible: true,
    challengeAccepted: false,
    challengeEntryClosed: true,
    resultLocked: true,
    rendersAsFrozen: true,
    submitted: false,
    accepted: false,
    settledOrClosed: true,
  },
  closed: {
    label: "已关闭",
    phase: "closed",
    tone: "open",
    compatibleStages: frozenStage,
    challengeSortRank: 7,
    canPublish: false,
    canApplyForChallenge: false,
    canReviewChallengeApplications: false,
    canRecruitChallengers: false,
    canReinforceChallengers: false,
    canAcceptChallenge: false,
    canMutateResults: false,
    canMutateWorkItems: false,
    canMutateComments: false,
    canMutateCommentsAsChallenger: false,
    canDeleteObjective: true,
    canFreezeAfterReestimate: false,
    canSubmitLoot: false,
    canSubmitContributionReview: false,
    canReviewLoot: false,
    canSettleLoot: false,
    challengeDiscoverable: false,
    bountyHallVisible: false,
    challengeAccepted: false,
    challengeEntryClosed: true,
    resultLocked: true,
    rendersAsFrozen: true,
    submitted: false,
    accepted: false,
    settledOrClosed: true,
  },
} as const satisfies Record<ObjectiveFlowStatus, ObjectiveFlowPolicy>;

export function objectiveFlowStatusOf(target: ObjectiveLifecycleTarget): ObjectiveFlowStatus | null {
  if (!target) return null;
  return typeof target === "string" ? target : target.flowStatus;
}

export function objectiveFlowPolicyFor(target: ObjectiveLifecycleTarget): ObjectiveFlowPolicy | null {
  const flowStatus = objectiveFlowStatusOf(target);
  return flowStatus ? objectiveFlowPolicy[flowStatus] : null;
}

export function objectiveFlowLabel(target: ObjectiveLifecycleTarget): string {
  return objectiveFlowPolicyFor(target)?.label ?? "";
}

export function objectiveFlowTone(target: ObjectiveLifecycleTarget): ObjectiveFlowPolicy["tone"] {
  return objectiveFlowPolicyFor(target)?.tone ?? "open";
}

export function objectiveChallengeSortRank(target: ObjectiveLifecycleTarget, input: { hasChallengers?: boolean } = {}): number {
  const policy = objectiveFlowPolicyFor(target);
  if (!policy) return Number.MAX_SAFE_INTEGER;
  return input.hasChallengers && policy.assignedChallengeSortRank != null
    ? policy.assignedChallengeSortRank
    : policy.challengeSortRank;
}
