import { STATE_CASE_MODEL, type StateCaseSpec, type StepExecutionMethod, type StepSpec } from "../../_framework/types";
import type { CreateObjectiveRoleControlCaseData } from "./_support/create-objective-role-control.context";

function step(
  caseStepId: string,
  method: StepExecutionMethod,
  id: string,
  title: string,
  object: string,
  operator: string,
  params?: Record<string, unknown>,
): StepSpec {
  return {
    source: { caseStepId, method },
    id,
    title,
    object,
    operator,
    ...(params ? { params } : {}),
  };
}

export const createObjectiveRoleControlCase = {
  id: "defaults.create-objective.role-control",
  title: "07-首页新建目标按角色控制",
  model: STATE_CASE_MODEL,
  tags: ["defaults", "topbar", "objective", "role-control"],
  data: {
    admin: {
      email: "orf-default-page-create-objective-admin-e2e@orf.local",
      password: "OrfDefaultPageCreateObjectiveAdminE2E!2026",
      name: "ORF Default Page Create Objective Admin E2E",
      role: "admin",
    },
    member: {
      email: "orf-default-page-create-objective-member-e2e@orf.local",
      password: "OrfDefaultPageCreateObjectiveMemberE2E!2026",
      name: "ORF Default Page Create Objective Member E2E",
      role: "member",
    },
    defaultLandingPath: "/bounties",
    homePath: "/dashboard",
    successTitle: "ORF默认页新建目标E2E-成功创建",
    emptyTitle: "ORF默认页新建目标E2E-空名称",
    cancelledTitle: "ORF默认页新建目标E2E-取消创建",
  },
  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      step("B-1", "api", "frontend.ready", "前端服务 应可用", "frontend.service", "available"),
      step("B-2", "api", "backend.ready", "后端服务 应可用", "api.health", "ok"),
      step("B-3", "api", "frontend.login_entry.accessible", "前端登录页入口 应可访问", "frontend.login_entry", "accessible"),
      step("B-4", "api", "session.endpoint.accessible", "当前会话查询能力 应可用", "auth.session", "accessible"),
      step("B-5", "prisma", "db.ready", "ORF 数据库 应可连接", "db", "ready"),
      step("B-6", "prisma", "db.schema.current", "ORF 数据库 schema 应为 当前测试版本", "db.schema", "current"),
      step("B-7", "api", "ory.admin_public.ready", "Ory/Kratos 认证服务的管理和公共访问能力 应可用", "ory.admin_public", "ready"),
      step("B-8", "api", "session.unauthenticated", "当前会话 应为 未登录", "auth.session", "unauthenticated"),
      step("B-9", "playwright", "cookie.absent", "当前浏览器 应不存在 Ory 登录会话 cookie", "browser.cookie", "absent"),
      step("B-10", "playwright", "storage.empty", "当前浏览器 应不保留本地登录态", "browser.auth_storage", "empty"),
    ],
  },
  Setup: {
    description: "准备管理员和普通成员账号，清理残留目标，并以管理员身份进入首页",
    steps: [
      step("Setup-1", "api", "ory.admin_identity.upsert", "准备邮箱为 `orf-default-page-create-objective-admin-e2e@orf.local`、使用固定测试密码的默认系统页新建目标管理员测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.admin.email", passwordFrom: "data.admin.password", nameFrom: "data.admin.name", saveAs: "adminIdentity" }),
      step("Setup-2", "prisma", "db.admin_user.upsert", "准备邮箱为 `orf-default-page-create-objective-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的默认系统页新建目标管理员测试用户", "db.user", "upsert", { emailFrom: "data.admin.email", passwordFrom: "data.admin.password", nameFrom: "data.admin.name", roleFrom: "data.admin.role", status: "active", identityIdFrom: "runtime.adminIdentity.id", saveAs: "adminUser" }),
      step("Setup-3", "api", "admin.preferences.default_landing_path.set", "设置默认系统页新建目标管理员测试用户默认进入页面为 首页（默认系统页）", "user.preferences", "set_default_landing_path_by_email", { emailFrom: "data.admin.email", pathFrom: "data.defaultLandingPath" }),
      step("Setup-4", "api", "ory.member_identity.upsert", "准备邮箱为 `orf-default-page-create-objective-member-e2e@orf.local`、使用固定测试密码的默认系统页新建目标普通成员测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.member.email", passwordFrom: "data.member.password", nameFrom: "data.member.name", saveAs: "memberIdentity" }),
      step("Setup-5", "prisma", "db.member_user.upsert", "准备邮箱为 `orf-default-page-create-objective-member-e2e@orf.local`、角色为 `member`、状态为 `active` 的默认系统页新建目标普通成员测试用户", "db.user", "upsert", { emailFrom: "data.member.email", passwordFrom: "data.member.password", nameFrom: "data.member.name", roleFrom: "data.member.role", status: "active", identityIdFrom: "runtime.memberIdentity.id", saveAs: "memberUser" }),
      step("Setup-6", "api", "member.preferences.default_landing_path.set", "设置默认系统页新建目标普通成员测试用户默认进入页面为 首页（默认系统页）", "user.preferences", "set_default_landing_path_by_email", { emailFrom: "data.member.email", pathFrom: "data.defaultLandingPath" }),
      step("Setup-7", "prisma", "db.success_objective.delete", "删除标题为 `ORF默认页新建目标E2E-成功创建` 的残留测试目标及其派生数据", "db.objective", "delete", { titleFrom: "data.successTitle" }),
      step("Setup-8", "prisma", "db.empty_objective.delete", "删除标题为 `ORF默认页新建目标E2E-空名称` 的残留测试目标及其派生数据", "db.objective", "delete", { titleFrom: "data.emptyTitle" }),
      step("Setup-9", "prisma", "db.cancelled_objective.delete", "删除标题为 `ORF默认页新建目标E2E-取消创建` 的残留测试目标及其派生数据", "db.objective", "delete", { titleFrom: "data.cancelledTitle" }),
      step("Setup-10", "api", "ory.admin_sessions.revoke", "撤销邮箱为 `orf-default-page-create-objective-admin-e2e@orf.local` 的默认系统页新建目标管理员测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.admin.email" }),
      step("Setup-11", "api", "ory.member_sessions.revoke", "撤销邮箱为 `orf-default-page-create-objective-member-e2e@orf.local` 的默认系统页新建目标普通成员测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.member.email" }),
      step("Setup-12", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Setup-13", "playwright", "page.goto.auth", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Setup-14", "playwright", "fill.admin_email", "在邮箱输入框输入 `orf-default-page-create-objective-admin-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.admin.email" }),
      step("Setup-15", "playwright", "fill.admin_password", "在密码输入框输入默认系统页新建目标管理员测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.admin.password" }),
      step("Setup-16", "playwright", "click.sign_in", "点击 \"Sign In\" 登录操作", "page.login_form", "submit", { saveAs: "adminLoginResponse" }),
      step("Setup-17", "api", "session.admin_authenticated", "当前会话 应为 邮箱为 `orf-default-page-create-objective-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
      step("Setup-18", "playwright", "page.goto.home", "打开 首页（默认系统页）", "page", "goto", { pathFrom: "data.homePath" }),
    ],
  },
  S0: {
    description: "管理员位于首页，新建目标入口可用，测试目标均不存在",
    assertions: [
      step("S0-1", "api", "session.admin_authenticated", "当前会话 应为 邮箱为 `orf-default-page-create-objective-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
      step("S0-2", "playwright", "url.home", "当前页面 应为 首页（默认系统页）", "page.url", "match", { pattern: "/dashboard$" }),
      step("S0-3", "playwright", "topbar.objective.visible", "顶部导航栏的新建目标入口 应可见", "topbar.objective", "visible"),
      step("S0-4", "playwright", "topbar.objective.enabled", "顶部导航栏的新建目标入口 应可点击", "topbar.objective", "enabled"),
      step("S0-5", "prisma", "db.success_objective.absent", "标题为 `ORF默认页新建目标E2E-成功创建` 的测试目标 应不存在", "db.objective", "absent", { titleFrom: "data.successTitle" }),
      step("S0-6", "prisma", "db.empty_objective.absent", "标题为 `ORF默认页新建目标E2E-空名称` 的测试目标 应不存在", "db.objective", "absent", { titleFrom: "data.emptyTitle" }),
      step("S0-7", "prisma", "db.cancelled_objective.absent", "标题为 `ORF默认页新建目标E2E-取消创建` 的测试目标 应不存在", "db.objective", "absent", { titleFrom: "data.cancelledTitle" }),
    ],
  },
  Action: {
    description: "管理员验证新建目标成功、空标题校验、取消不落库，再切换普通成员验证入口隐藏",
    steps: [
      step("Action-1", "playwright", "topbar.objective.click.success", "点击 顶部导航栏的新建目标入口", "topbar.objective", "click"),
      step("Action-2", "playwright", "objective_create.title.fill_success", "在新建目标标题输入框输入 `ORF默认页新建目标E2E-成功创建`", "objective_create.title_input", "fill", { valueFrom: "data.successTitle" }),
      step("Action-3", "playwright", "objective_create.title.submit_success", "提交 新建目标标题输入框", "objective_create.title_input", "submit", { expectedTitleFrom: "data.successTitle", saveAs: "successObjectiveListSnapshot" }),
      step("Action-4", "playwright", "page.goto.home.after_success", "打开 首页（默认系统页）", "page", "goto", { pathFrom: "data.homePath" }),
      step("Action-5", "playwright", "topbar.objective.click.empty", "点击 顶部导航栏的新建目标入口", "topbar.objective", "click"),
      step("Action-6", "playwright", "objective_create.title.submit_empty", "提交 空的新建目标标题输入框", "objective_create.title_input", "submit", { expectedToast: "标题不能为空", saveAs: "emptyTitleToastSnapshot" }),
      step("Action-7", "playwright", "objective_create.draft.cancel_empty", "取消 当前新建目标草稿", "objective_create.draft", "cancel"),
      step("Action-8", "playwright", "page.goto.home.after_empty", "打开 首页（默认系统页）", "page", "goto", { pathFrom: "data.homePath" }),
      step("Action-9", "playwright", "topbar.objective.click.cancelled", "点击 顶部导航栏的新建目标入口", "topbar.objective", "click"),
      step("Action-10", "playwright", "objective_create.title.fill_cancelled", "在新建目标标题输入框输入 `ORF默认页新建目标E2E-取消创建`", "objective_create.title_input", "fill", { valueFrom: "data.cancelledTitle" }),
      step("Action-11", "playwright", "objective_create.draft.cancel_cancelled", "取消 当前新建目标草稿", "objective_create.draft", "cancel"),
      step("Action-12", "api", "auth.logout.admin", "注销当前管理员登录会话", "auth", "logout"),
      step("Action-13", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Action-14", "playwright", "page.goto.auth.member", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Action-15", "playwright", "fill.member_email", "在邮箱输入框输入 `orf-default-page-create-objective-member-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.member.email" }),
      step("Action-16", "playwright", "fill.member_password", "在密码输入框输入默认系统页新建目标普通成员测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.member.password" }),
      step("Action-17", "playwright", "click.sign_in.member", "点击 \"Sign In\" 登录操作", "page.login_form", "submit", { saveAs: "memberLoginResponse" }),
      step("Action-18", "api", "session.member_authenticated", "当前会话 应为 邮箱为 `orf-default-page-create-objective-member-e2e@orf.local`、角色为 `member`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.member.email", roleFrom: "data.member.role", status: "active" }),
      step("Action-19", "playwright", "page.goto.home.member", "打开 首页（默认系统页）", "page", "goto", { pathFrom: "data.homePath" }),
    ],
  },
  S1: {
    description: "管理员创建成功，空标题和取消不落库，普通成员入口不可见",
    assertions: [
      step("S1-1", "prisma", "db.success_objective.exists", "标题为 `ORF默认页新建目标E2E-成功创建` 的测试目标 应存在", "db.objective", "exists", { titleFrom: "data.successTitle" }),
      step("S1-2", "playwright", "challenge.objective_list.success_visible", "管理员提交新建目标标题输入框后，挑战工作台列表 应显示 `ORF默认页新建目标E2E-成功创建` 测试目标", "challenge.objective_list_snapshot", "visible", { snapshotFrom: "runtime.successObjectiveListSnapshot" }),
      step("S1-3", "playwright", "toast.empty_title.visible", "管理员提交空的新建目标标题输入框时，系统 应提示 `标题不能为空`", "toast_snapshot", "visible", { snapshotFrom: "runtime.emptyTitleToastSnapshot", text: "标题不能为空" }),
      step("S1-4", "prisma", "db.empty_objective.absent", "标题为 `ORF默认页新建目标E2E-空名称` 的测试目标 应不存在", "db.objective", "absent", { titleFrom: "data.emptyTitle" }),
      step("S1-5", "prisma", "db.cancelled_objective.absent", "标题为 `ORF默认页新建目标E2E-取消创建` 的测试目标 应不存在", "db.objective", "absent", { titleFrom: "data.cancelledTitle" }),
      step("S1-6", "api", "session.member_authenticated.final", "当前会话 应为 邮箱为 `orf-default-page-create-objective-member-e2e@orf.local`、角色为 `member`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.member.email", roleFrom: "data.member.role", status: "active" }),
      step("S1-7", "playwright", "url.home.member", "当前页面 应为 首页（默认系统页）", "page.url", "match", { pattern: "/dashboard$" }),
      step("S1-8", "playwright", "topbar.objective.hidden.member", "顶部导航栏的新建目标入口 应不可见", "topbar.objective", "hidden"),
    ],
  },
  Clean: {
    description: "删除测试目标、测试账号和认证身份，恢复未登录基准状态",
    steps: [
      step("Clean-1", "prisma", "db.success_objective.delete", "删除标题为 `ORF默认页新建目标E2E-成功创建` 的测试目标及其派生数据", "db.objective", "delete", { titleFrom: "data.successTitle" }),
      step("Clean-2", "prisma", "db.empty_objective.delete", "删除标题为 `ORF默认页新建目标E2E-空名称` 的测试目标及其派生数据", "db.objective", "delete", { titleFrom: "data.emptyTitle" }),
      step("Clean-3", "prisma", "db.cancelled_objective.delete", "删除标题为 `ORF默认页新建目标E2E-取消创建` 的测试目标及其派生数据", "db.objective", "delete", { titleFrom: "data.cancelledTitle" }),
      step("Clean-4", "api", "auth.logout", "注销当前登录会话", "auth", "logout"),
      step("Clean-5", "playwright", "page.runtime.stop", "离开当前 ORF 前端页面", "page.runtime", "stop"),
      step("Clean-6", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Clean-7", "api", "ory.admin_sessions.revoke", "撤销邮箱为 `orf-default-page-create-objective-admin-e2e@orf.local` 的默认系统页新建目标管理员测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-8", "api", "ory.member_sessions.revoke", "撤销邮箱为 `orf-default-page-create-objective-member-e2e@orf.local` 的默认系统页新建目标普通成员测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.member.email" }),
      step("Clean-9", "api", "ory.admin_identity.delete", "删除邮箱为 `orf-default-page-create-objective-admin-e2e@orf.local` 的默认系统页新建目标管理员测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-10", "api", "ory.member_identity.delete", "删除邮箱为 `orf-default-page-create-objective-member-e2e@orf.local` 的默认系统页新建目标普通成员测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.member.email" }),
      step("Clean-11", "api", "admin.preferences.default_landing_path.reset", "恢复邮箱为 `orf-default-page-create-objective-admin-e2e@orf.local` 的默认进入页面为 系统默认", "user.preferences", "reset_default_landing_path_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-12", "api", "member.preferences.default_landing_path.reset", "恢复邮箱为 `orf-default-page-create-objective-member-e2e@orf.local` 的默认进入页面为 系统默认", "user.preferences", "reset_default_landing_path_by_email", { emailFrom: "data.member.email" }),
      step("Clean-13", "prisma", "db.admin_user.memberships.delete", "删除邮箱为 `orf-default-page-create-objective-admin-e2e@orf.local` 的默认系统页新建目标管理员测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.admin.email" }),
      step("Clean-14", "prisma", "db.member_user.memberships.delete", "删除邮箱为 `orf-default-page-create-objective-member-e2e@orf.local` 的默认系统页新建目标普通成员测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.member.email" }),
      step("Clean-15", "prisma", "db.admin_user.delete", "删除邮箱为 `orf-default-page-create-objective-admin-e2e@orf.local` 的默认系统页新建目标管理员测试用户", "db.user", "delete", { emailFrom: "data.admin.email" }),
      step("Clean-16", "prisma", "db.member_user.delete", "删除邮箱为 `orf-default-page-create-objective-member-e2e@orf.local` 的默认系统页新建目标普通成员测试用户", "db.user", "delete", { emailFrom: "data.member.email" }),
      step("Clean-17", "api", "ory.admin_identity.absent", "邮箱为 `orf-default-page-create-objective-admin-e2e@orf.local` 的默认系统页新建目标管理员测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.admin.email" }),
      step("Clean-18", "api", "ory.member_identity.absent", "邮箱为 `orf-default-page-create-objective-member-e2e@orf.local` 的默认系统页新建目标普通成员测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.member.email" }),
      step("Clean-19", "prisma", "db.admin_user.absent", "邮箱为 `orf-default-page-create-objective-admin-e2e@orf.local` 的默认系统页新建目标管理员测试用户 应不存在", "db.user", "absent", { emailFrom: "data.admin.email" }),
      step("Clean-20", "prisma", "db.member_user.absent", "邮箱为 `orf-default-page-create-objective-member-e2e@orf.local` 的默认系统页新建目标普通成员测试用户 应不存在", "db.user", "absent", { emailFrom: "data.member.email" }),
      step("Clean-21", "prisma", "db.success_objective.absent", "标题为 `ORF默认页新建目标E2E-成功创建` 的测试目标 应不存在", "db.objective", "absent", { titleFrom: "data.successTitle" }),
      step("Clean-22", "prisma", "db.empty_objective.absent", "标题为 `ORF默认页新建目标E2E-空名称` 的测试目标 应不存在", "db.objective", "absent", { titleFrom: "data.emptyTitle" }),
      step("Clean-23", "prisma", "db.cancelled_objective.absent", "标题为 `ORF默认页新建目标E2E-取消创建` 的测试目标 应不存在", "db.objective", "absent", { titleFrom: "data.cancelledTitle" }),
    ],
  },
} satisfies StateCaseSpec<CreateObjectiveRoleControlCaseData>;
