import { STATE_CASE_MODEL, type StateCaseSpec, type StepExecutionMethod, type StepSpec } from "../../_framework/types";
import type { SystemPermissionsConfigCaseData } from "./_support/permissions-config.context";

function step(
  caseStepId: string,
  method: StepExecutionMethod,
  id: string,
  title: string,
  object: string,
  operator: string,
  params?: Record<string, unknown>,
): StepSpec {
  return {
    source: { caseStepId, method },
    id,
    title,
    object,
    operator,
    ...(params ? { params } : {}),
  };
}

export const systemPermissionsConfigCase = {
  id: "system.permissions-config.role-rules",
  title: "11-权限管理角色权限配置校验",
  model: STATE_CASE_MODEL,
  tags: ["system", "permissions", "role-config"],
  data: {
    admin: {
      email: "orf-system-permissions-config-admin-e2e@orf.local",
      password: "OrfSystemPermissionsConfigAdminE2E!2026",
      name: "ORF Permissions Config Admin E2E",
      role: "admin",
    },
    memberA: {
      email: "orf-system-permissions-config-member-a-e2e@orf.local",
      password: "OrfSystemPermissionsConfigMemberAE2E!2026",
      name: "ORF Permissions Config Member A E2E",
      role: "member",
    },
    memberB: {
      email: "orf-system-permissions-config-member-b-e2e@orf.local",
      password: "OrfSystemPermissionsConfigMemberBE2E!2026",
      name: "ORF Permissions Config Member B E2E",
      role: "member",
    },
    defaultLandingPath: "/bounties",
    permissionsPath: "/system/permissions",
    targetRole: "member",
    adminRole: "admin",
    permissionKey: "comment.manage",
  },
  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      step("B-1", "api", "frontend.ready", "前端服务 应可用", "frontend.service", "available"),
      step("B-2", "api", "backend.ready", "后端服务 应可用", "api.health", "ok"),
      step("B-3", "api", "frontend.login_entry.accessible", "前端登录页入口 应可访问", "frontend.login_entry", "accessible"),
      step("B-4", "api", "session.endpoint.accessible", "当前会话查询能力 应可用", "auth.session", "accessible"),
      step("B-5", "prisma", "db.ready", "ORF 数据库 应可连接", "db", "ready"),
      step("B-6", "prisma", "db.schema.current", "ORF 数据库 schema 应为 当前测试版本", "db.schema", "current"),
      step("B-7", "api", "ory.admin_public.ready", "Ory/Kratos 认证服务的管理和公共访问能力 应可用", "ory.admin_public", "ready"),
      step("B-8", "api", "session.unauthenticated", "当前会话 应为 未登录", "auth.session", "unauthenticated"),
      step("B-9", "playwright", "cookie.absent", "当前浏览器 应不存在 Ory 登录会话 cookie", "browser.cookie", "absent"),
      step("B-10", "playwright", "storage.empty", "当前浏览器 应不保留本地登录态", "browser.auth_storage", "empty"),
    ],
  },
  Setup: {
    description: "准备管理员与两个成员，记录 member 权限原始配置，并进入权限管理页面",
    steps: [
      step("Setup-1", "api", "ory.admin_identity.upsert", "准备邮箱为 `orf-system-permissions-config-admin-e2e@orf.local`、使用固定测试密码的权限配置管理员测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.admin.email", passwordFrom: "data.admin.password", nameFrom: "data.admin.name", saveAs: "adminIdentity" }),
      step("Setup-2", "prisma", "db.admin_user.upsert", "准备姓名为 \"ORF Permissions Config Admin E2E\"、邮箱为 `orf-system-permissions-config-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的权限配置管理员测试用户", "db.user", "upsert", { emailFrom: "data.admin.email", passwordFrom: "data.admin.password", nameFrom: "data.admin.name", roleFrom: "data.admin.role", status: "active", identityIdFrom: "runtime.adminIdentity.id", saveAs: "adminUser" }),
      step("Setup-3", "api", "admin.preferences.default_landing_path.set", "设置权限配置管理员测试用户默认进入页面为 首页（默认系统页）", "user.preferences", "set_default_landing_path_by_email", { emailFrom: "data.admin.email", pathFrom: "data.defaultLandingPath" }),
      step("Setup-4", "api", "ory.member_a_identity.upsert", "准备邮箱为 `orf-system-permissions-config-member-a-e2e@orf.local`、使用固定测试密码的权限配置普通成员 A 测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.memberA.email", passwordFrom: "data.memberA.password", nameFrom: "data.memberA.name", saveAs: "memberAIdentity" }),
      step("Setup-5", "prisma", "db.member_a_user.upsert", "准备姓名为 \"ORF Permissions Config Member A E2E\"、邮箱为 `orf-system-permissions-config-member-a-e2e@orf.local`、角色为 `member`、状态为 `active` 的权限配置普通成员 A 测试用户", "db.user", "upsert", { emailFrom: "data.memberA.email", passwordFrom: "data.memberA.password", nameFrom: "data.memberA.name", roleFrom: "data.memberA.role", status: "active", identityIdFrom: "runtime.memberAIdentity.id", saveAs: "memberAUser" }),
      step("Setup-6", "api", "ory.member_b_identity.upsert", "准备邮箱为 `orf-system-permissions-config-member-b-e2e@orf.local`、使用固定测试密码的权限配置普通成员 B 测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.memberB.email", passwordFrom: "data.memberB.password", nameFrom: "data.memberB.name", saveAs: "memberBIdentity" }),
      step("Setup-7", "prisma", "db.member_b_user.upsert", "准备姓名为 \"ORF Permissions Config Member B E2E\"、邮箱为 `orf-system-permissions-config-member-b-e2e@orf.local`、角色为 `member`、状态为 `active` 的权限配置普通成员 B 测试用户", "db.user", "upsert", { emailFrom: "data.memberB.email", passwordFrom: "data.memberB.password", nameFrom: "data.memberB.name", roleFrom: "data.memberB.role", status: "active", identityIdFrom: "runtime.memberBIdentity.id", saveAs: "memberBUser" }),
      step("Setup-8", "api", "permissions.member.original_rules.record", "记录修改前的 `member` 角色权限配置", "api.permissions", "read_member_rules", { teamIdFrom: "runtime.adminUser.teamId", saveAs: "originalMemberPermissionRules" }),
      step("Setup-9", "api", "permissions.member.original_count.record", "记录修改前的 `member` 角色已允许权限数量", "api.permissions", "count_member_rules", { rulesFrom: "runtime.originalMemberPermissionRules", saveAs: "originalMemberPermissionCount" }),
      step("Setup-10", "api", "ory.admin_sessions.revoke", "撤销邮箱为 `orf-system-permissions-config-admin-e2e@orf.local` 的权限配置管理员测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.admin.email" }),
      step("Setup-11", "api", "ory.member_a_sessions.revoke", "撤销邮箱为 `orf-system-permissions-config-member-a-e2e@orf.local` 的权限配置普通成员 A 测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.memberA.email" }),
      step("Setup-12", "api", "ory.member_b_sessions.revoke", "撤销邮箱为 `orf-system-permissions-config-member-b-e2e@orf.local` 的权限配置普通成员 B 测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.memberB.email" }),
      step("Setup-13", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Setup-14", "playwright", "page.goto.auth", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Setup-15", "playwright", "fill.admin_email", "在邮箱输入框输入 `orf-system-permissions-config-admin-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.admin.email" }),
      step("Setup-16", "playwright", "fill.admin_password", "在密码输入框输入权限配置管理员测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.admin.password" }),
      step("Setup-17", "playwright", "click.sign_in", "点击 \"Sign In\" 登录操作", "page.login_form", "submit", { saveAs: "adminLoginResponse" }),
      step("Setup-18", "api", "session.admin_authenticated", "当前会话 应为 邮箱为 `orf-system-permissions-config-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
      step("Setup-19", "playwright", "page.goto.permissions", "打开 权限管理页面", "page", "goto", { pathFrom: "data.permissionsPath" }),
    ],
  },
  S0: {
    description: "管理员已登录并位于权限管理页面，成员与管理员角色切换入口和目标权限开关可见",
    assertions: [
      step("S0-1", "api", "session.admin_authenticated", "当前会话 应为 邮箱为 `orf-system-permissions-config-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
      step("S0-2", "playwright", "url.permissions", "当前页面 应为 权限管理页面", "page.url", "match", { pattern: "/system/permissions$" }),
      step("S0-3", "playwright", "role.member.visible", "权限管理页面的 \"成员\" 角色切换操作 应可见", "page.role_tab", "visible", { text: "成员" }),
      step("S0-4", "playwright", "role.admin.visible", "权限管理页面的 \"管理员\" 角色切换操作 应可见", "page.role_tab", "visible", { text: "管理员" }),
      step("S0-5", "playwright", "comment_manage.toggle.visible", "权限管理页面的 `comment.manage` 权限开关 应可见", "page.permission_toggle", "visible", { permissionKeyFrom: "data.permissionKey" }),
      step("S0-6", "api", "permissions.member.original_rules.recorded", "修改前的 `member` 角色权限配置 应已记录", "api.permissions", "recorded", { rulesFrom: "runtime.originalMemberPermissionRules" }),
      step("S0-7", "prisma", "db.member_a.exists", "邮箱为 `orf-system-permissions-config-member-a-e2e@orf.local` 的权限配置普通成员 A 测试用户 应存在", "db.user", "matches", { emailFrom: "data.memberA.email", roleFrom: "data.memberA.role", status: "active" }),
      step("S0-8", "prisma", "db.member_b.exists", "邮箱为 `orf-system-permissions-config-member-b-e2e@orf.local` 的权限配置普通成员 B 测试用户 应存在", "db.user", "matches", { emailFrom: "data.memberB.email", roleFrom: "data.memberB.role", status: "active" }),
    ],
  },
  Action: {
    description: "切换成员和管理员角色，记录权限数量，修改成员角色权限并保存",
    steps: [
      step("Action-1", "playwright", "role.member.click.first", "选择 \"成员\" 角色切换操作", "page.role_tab", "click", { text: "成员" }),
      step("Action-2", "playwright", "member.allowed_count.record", "记录成员角色页面已允许权限数量", "page.permissions_count", "record", { saveAs: "memberAllowedCountBeforeChange" }),
      step("Action-3", "playwright", "role.admin.click", "选择 \"管理员\" 角色切换操作", "page.role_tab", "click", { text: "管理员" }),
      step("Action-4", "playwright", "admin.allowed_count.record", "记录管理员角色页面已允许权限数量", "page.permissions_count", "record", { saveAs: "adminAllowedCount" }),
      step("Action-5", "playwright", "role.member.click.second", "选择 \"成员\" 角色切换操作", "page.role_tab", "click", { text: "成员" }),
      step("Action-6", "playwright", "comment_manage.toggle", "切换 `comment.manage` 权限开关", "page.permission_toggle", "toggle", { originalRulesFrom: "runtime.originalMemberPermissionRules", roleFrom: "data.targetRole", permissionKeyFrom: "data.permissionKey", saveAs: "changedMemberPermissionRules" }),
      step("Action-7", "playwright", "permissions.save", "点击 \"保存角色权限\" 操作", "page.permissions_save", "submit", { saveAs: "permissionUpdateResponse" }),
      step("Action-8", "api", "permissions.member.reread", "重新读取 `member` 角色权限配置", "api.permissions", "read_member_rules", { teamIdFrom: "runtime.adminUser.teamId", saveAs: "rereadMemberPermissionRules" }),
    ],
  },
  S1: {
    description: "角色配置展示、权限数量、保存结果和用户权限范围均符合预期",
    assertions: [
      step("S1-1", "playwright", "member.rules.visible", "选择成员角色后，权限列表 应展示 `member` 角色权限配置", "page.permissions_role_rules", "shows_member_rules", { rulesFrom: "runtime.changedMemberPermissionRules" }),
      step("S1-2", "playwright", "member.count.before.equals_original", "成员角色页面已允许权限数量 应等于 修改前的 `member` 角色已允许权限数量", "page.permissions_count", "equals", { actualFrom: "runtime.memberAllowedCountBeforeChange", expectedFrom: "runtime.originalMemberPermissionCount" }),
      step("S1-3", "playwright", "admin.rules.visible", "选择管理员角色后，权限列表 应展示 `admin` 角色权限配置", "page.permissions_role_rules", "shows_admin_rules"),
      step("S1-4", "playwright", "admin.count.equals_system_total", "管理员角色页面已允许权限数量 应等于 系统权限定义总数", "page.permissions_count", "equals_system_total", { actualFrom: "runtime.adminAllowedCount" }),
      step("S1-5", "playwright", "admin.comment_manage.readonly_allowed", "管理员角色页面的 `comment.manage` 权限开关 应为 只读已允许状态", "page.permission_toggle", "readonly_allowed", { permissionKeyFrom: "data.permissionKey" }),
      step("S1-6", "api", "permission_update.response_ok", "`member` 角色权限保存结果 应成功", "api.permissions", "response_ok", { resultFrom: "runtime.permissionUpdateResponse" }),
      step("S1-7", "api", "member.rules.match_changed", "重新读取的 `member` 角色权限配置 应等于 Action 保存的新权限配置", "api.permissions", "member_rules_equal", { actualRulesFrom: "runtime.rereadMemberPermissionRules", expectedRulesFrom: "runtime.changedMemberPermissionRules", roleFrom: "data.targetRole" }),
      step("S1-8", "api", "member_a.access.match_member_rules", "权限配置普通成员 A 的权限范围 应等于 重新读取的 `member` 角色权限配置", "api.user_access", "matches_rules", { emailFrom: "data.memberA.email", passwordFrom: "data.memberA.password", rulesFrom: "runtime.rereadMemberPermissionRules", roleFrom: "data.targetRole" }),
      step("S1-9", "api", "member_b.access.match_member_rules", "权限配置普通成员 B 的权限范围 应等于 重新读取的 `member` 角色权限配置", "api.user_access", "matches_rules", { emailFrom: "data.memberB.email", passwordFrom: "data.memberB.password", rulesFrom: "runtime.rereadMemberPermissionRules", roleFrom: "data.targetRole" }),
      step("S1-10", "api", "admin.access.includes_all", "权限配置管理员测试用户的权限范围 应包含 系统权限定义中的全部权限", "api.user_access", "includes_all_permissions", { emailFrom: "data.admin.email", passwordFrom: "data.admin.password" }),
      step("S1-11", "playwright", "member.count.after.equals_reread", "保存后成员角色页面已允许权限数量 应等于 重新读取的 `member` 角色已允许权限数量", "page.permissions_count", "equals_rules_count", { rulesFrom: "runtime.rereadMemberPermissionRules", roleFrom: "data.targetRole" }),
      step("S1-12", "api", "session.admin_authenticated.after_save", "当前会话 应仍为 邮箱为 `orf-system-permissions-config-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
    ],
  },
  Clean: {
    description: "恢复成员权限配置，删除权限配置相关测试数据并恢复未登录基准状态",
    steps: [
      step("Clean-1", "api", "permissions.member.restore", "恢复 `member` 角色权限配置为修改前状态", "api.permissions", "restore_member", { rulesFrom: "runtime.originalMemberPermissionRules", teamIdFrom: "runtime.adminUser.teamId", saveAs: "permissionRestoreResponse" }),
      step("Clean-2", "api", "auth.logout", "注销当前登录会话", "auth", "logout"),
      step("Clean-3", "playwright", "page.runtime.stop", "离开当前 ORF 前端页面", "page.runtime", "stop"),
      step("Clean-4", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Clean-5", "api", "ory.admin_sessions.revoke", "撤销邮箱为 `orf-system-permissions-config-admin-e2e@orf.local` 的权限配置管理员测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-6", "api", "ory.member_a_sessions.revoke", "撤销邮箱为 `orf-system-permissions-config-member-a-e2e@orf.local` 的权限配置普通成员 A 测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.memberA.email" }),
      step("Clean-7", "api", "ory.member_b_sessions.revoke", "撤销邮箱为 `orf-system-permissions-config-member-b-e2e@orf.local` 的权限配置普通成员 B 测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.memberB.email" }),
      step("Clean-8", "api", "ory.admin_identity.delete", "删除邮箱为 `orf-system-permissions-config-admin-e2e@orf.local` 的权限配置管理员测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-9", "api", "ory.member_a_identity.delete", "删除邮箱为 `orf-system-permissions-config-member-a-e2e@orf.local` 的权限配置普通成员 A 测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.memberA.email" }),
      step("Clean-10", "api", "ory.member_b_identity.delete", "删除邮箱为 `orf-system-permissions-config-member-b-e2e@orf.local` 的权限配置普通成员 B 测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.memberB.email" }),
      step("Clean-11", "api", "admin.preferences.default_landing_path.reset", "恢复邮箱为 `orf-system-permissions-config-admin-e2e@orf.local` 的默认进入页面为 系统默认", "user.preferences", "reset_default_landing_path_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-12", "prisma", "db.admin_user.memberships.delete", "删除邮箱为 `orf-system-permissions-config-admin-e2e@orf.local` 的权限配置管理员测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.admin.email" }),
      step("Clean-13", "prisma", "db.member_a_user.memberships.delete", "删除邮箱为 `orf-system-permissions-config-member-a-e2e@orf.local` 的权限配置普通成员 A 测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.memberA.email" }),
      step("Clean-14", "prisma", "db.member_b_user.memberships.delete", "删除邮箱为 `orf-system-permissions-config-member-b-e2e@orf.local` 的权限配置普通成员 B 测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.memberB.email" }),
      step("Clean-15", "prisma", "db.admin_user.delete", "删除邮箱为 `orf-system-permissions-config-admin-e2e@orf.local` 的权限配置管理员测试用户", "db.user", "delete", { emailFrom: "data.admin.email" }),
      step("Clean-16", "prisma", "db.member_a_user.delete", "删除邮箱为 `orf-system-permissions-config-member-a-e2e@orf.local` 的权限配置普通成员 A 测试用户", "db.user", "delete", { emailFrom: "data.memberA.email" }),
      step("Clean-17", "prisma", "db.member_b_user.delete", "删除邮箱为 `orf-system-permissions-config-member-b-e2e@orf.local` 的权限配置普通成员 B 测试用户", "db.user", "delete", { emailFrom: "data.memberB.email" }),
      step("Clean-18", "api", "ory.admin_identity.absent", "邮箱为 `orf-system-permissions-config-admin-e2e@orf.local` 的权限配置管理员测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.admin.email" }),
      step("Clean-19", "api", "ory.member_a_identity.absent", "邮箱为 `orf-system-permissions-config-member-a-e2e@orf.local` 的权限配置普通成员 A 测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.memberA.email" }),
      step("Clean-20", "api", "ory.member_b_identity.absent", "邮箱为 `orf-system-permissions-config-member-b-e2e@orf.local` 的权限配置普通成员 B 测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.memberB.email" }),
      step("Clean-21", "prisma", "db.admin_user.absent", "邮箱为 `orf-system-permissions-config-admin-e2e@orf.local` 的权限配置管理员测试用户 应不存在", "db.user", "absent", { emailFrom: "data.admin.email" }),
      step("Clean-22", "prisma", "db.member_a_user.absent", "邮箱为 `orf-system-permissions-config-member-a-e2e@orf.local` 的权限配置普通成员 A 测试用户 应不存在", "db.user", "absent", { emailFrom: "data.memberA.email" }),
      step("Clean-23", "prisma", "db.member_b_user.absent", "邮箱为 `orf-system-permissions-config-member-b-e2e@orf.local` 的权限配置普通成员 B 测试用户 应不存在", "db.user", "absent", { emailFrom: "data.memberB.email" }),
    ],
  },
} satisfies StateCaseSpec<SystemPermissionsConfigCaseData>;
