import { STATE_CASE_MODEL, type StateCaseSpec } from "../../../../_framework/types";
import type { AdminTrialReviewFeedbackCaseData } from "./_support/admin-trial-review-feedback.context";

export const adminTrialReviewFeedbackCase = {
  id: "target.admin-trial-review-feedback",
  title: "管理员可处理试验收并提交反馈",
  model: STATE_CASE_MODEL,
  tags: ["target", "loot", "trial-review", "admin", "feedback"],

  data: {
    adminEmail: "orf-admin-trial-review-feedback-e2e@orf.local",
    adminPassword: "OrfAdminTrialReviewFeedbackE2E!2026",
    adminName: "ORF Admin Trial Review Feedback E2E",
    adminRole: "admin",
    adminStatus: "active",
    memberEmail: "orf-member-trial-review-feedback-e2e@orf.local",
    memberPassword: "OrfMemberTrialReviewFeedbackE2E!2026",
    memberName: "ORF Member Trial Review Feedback E2E",
    memberRole: "member",
    memberStatus: "active",
    targetPrefix: "E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK",
    target: {
      title: "E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK",
      stage: "goalFrozen",
      flowStatus: "frozen",
      finalDueOffsetDays: 8,
    },
    metric: {
      title: "E2E-METRIC-ADMIN-TRIAL-REVIEW-FEEDBACK",
      difficulty: "进阶",
      score: 30,
      claim: "completed",
      evidence: "E2E-TRIAL-REVIEW-FEEDBACK-EVIDENCE：https://example.test/trial-review-feedback",
    },
    trialReview: {
      body: "E2E-TRIAL-REVIEW-FEEDBACK-BODY：普通成员提交待处理试验收材料。",
      selfTestReportBody: "E2E-TRIAL-REVIEW-FEEDBACK-SELF-TEST：已完成试验收前自测。",
      initialStatus: "requested",
      reviewedStatus: "approved",
      commanderFeedback: "E2E-TRIAL-REVIEW-COMMANDER-FEEDBACK：材料完整，同意进入正式提交。",
    },
  },

  B: {
    description: "基准状态",
    assertions: [
      { source: { caseStepId: "B-1", method: "api" }, id: "frontend.ready", title: "前端服务 应可用", object: "frontend.service", operator: "available" },
      { source: { caseStepId: "B-2", method: "api" }, id: "backend.ready", title: "后端服务 应可用", object: "api.health", operator: "ok" },
      { source: { caseStepId: "B-3", method: "prisma" }, id: "db.ready", title: "ORF 数据库 应可连接", object: "db", operator: "ready" },
      { source: { caseStepId: "B-4", method: "api" }, id: "session.unauthenticated", title: "当前会话 应为 未登录", object: "auth.session", operator: "unauthenticated" },
      { source: { caseStepId: "B-5", method: "playwright" }, id: "storage.empty", title: "当前浏览器 应不保留本地登录态", object: "browser.auth_storage", operator: "empty" },
    ],
  },

  Setup: {
    description: "构造 S0",
    steps: [
      { source: { caseStepId: "Setup-1", method: "prisma" }, id: "db.objectives.delete_residue", title: "删除 本用例残留的目标标题前缀 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK` 对应的目标及其派生数据", object: "db.objectives_by_prefix", operator: "delete", params: { prefixFrom: "data.targetPrefix" } },
      { source: { caseStepId: "Setup-2", method: "api" }, id: "ory.admin_identity.upsert", title: "准备邮箱为 `orf-admin-trial-review-feedback-e2e@orf.local`、使用固定测试密码的管理员登录身份", object: "ory.identity", operator: "upsert_password", params: { emailFrom: "data.adminEmail", nameFrom: "data.adminName", passwordFrom: "data.adminPassword", saveAs: "adminIdentity" } },
      { source: { caseStepId: "Setup-3", method: "prisma" }, id: "db.admin_user.upsert", title: "准备 角色为 `admin`、状态为 `active`、名称为 `ORF Admin Trial Review Feedback E2E` 的本用例管理员用户", object: "db.user", operator: "upsert", params: { emailFrom: "data.adminEmail", nameFrom: "data.adminName", roleFrom: "data.adminRole", statusFrom: "data.adminStatus", identityIdFrom: "runtime.adminIdentity.id", saveAs: "adminUser" } },
      { source: { caseStepId: "Setup-4", method: "api" }, id: "ory.member_identity.upsert", title: "准备邮箱为 `orf-member-trial-review-feedback-e2e@orf.local`、使用固定测试密码的普通成员登录身份", object: "ory.identity", operator: "upsert_password", params: { emailFrom: "data.memberEmail", nameFrom: "data.memberName", passwordFrom: "data.memberPassword", saveAs: "memberIdentity" } },
      { source: { caseStepId: "Setup-5", method: "prisma" }, id: "db.member_user.upsert", title: "准备 角色为 `member`、状态为 `active`、名称为 `ORF Member Trial Review Feedback E2E` 的本用例普通成员用户", object: "db.user", operator: "upsert", params: { emailFrom: "data.memberEmail", nameFrom: "data.memberName", roleFrom: "data.memberRole", statusFrom: "data.memberStatus", identityIdFrom: "runtime.memberIdentity.id", saveAs: "memberUser" } },
      { source: { caseStepId: "Setup-6", method: "prisma" }, id: "db.frozen_objective.prepare", title: "准备 标题为 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK`、阶段为 `goalFrozen`、流转状态为 `frozen`、最终验收截止日为运行时当前日期后 `8` 天、冻结时间存在、当前挑战者包含本用例普通成员的目标", object: "db.frozen_objective_fixture", operator: "prepare", params: { adminUserFrom: "runtime.adminUser", memberUserFrom: "runtime.memberUser", targetFrom: "data.target", saveAs: "objective" } },
      { source: { caseStepId: "Setup-7", method: "prisma" }, id: "db.metric.prepare_calibrated", title: "准备 归属于目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK`、口径为 `E2E-METRIC-ADMIN-TRIAL-REVIEW-FEEDBACK`、等级积分等级为 `进阶`、等级积分为 `30` 的指标", object: "db.metric", operator: "prepare_calibrated", params: { targetFrom: "data.target", metricFrom: "data.metric", memberUserFrom: "runtime.memberUser", saveAs: "metric" } },
      { source: { caseStepId: "Setup-8", method: "prisma" }, id: "db.trial_review.prepare_requested", title: "准备 归属于目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK`、状态为 `requested`、申请人为本用例普通成员、完成说明为 `E2E-TRIAL-REVIEW-FEEDBACK-BODY：普通成员提交待处理试验收材料。`、自测报告为 `E2E-TRIAL-REVIEW-FEEDBACK-SELF-TEST：已完成试验收前自测。`、指标 `E2E-METRIC-ADMIN-TRIAL-REVIEW-FEEDBACK` 的完成主张为 `completed`、证据为 `E2E-TRIAL-REVIEW-FEEDBACK-EVIDENCE：https://example.test/trial-review-feedback` 的试验收记录", object: "db.objective_trial_review", operator: "prepare_requested", params: { targetFrom: "data.target", metricFrom: "data.metric", trialReviewFrom: "data.trialReview", memberUserFrom: "runtime.memberUser", saveAs: "trialReview" } },
      { source: { caseStepId: "Setup-9", method: "prisma" }, id: "db.objective_loot.delete_by_target", title: "确保 归属于目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK` 的战利品正式提交记录不存在", object: "db.objective_loot", operator: "delete_by_target", params: { targetFrom: "data.target" } },
      { source: { caseStepId: "Setup-10", method: "playwright" }, id: "auth.login.admin", title: "使用 本用例管理员账号 登录 ORF", object: "page.auth", operator: "login", params: { emailFrom: "data.adminEmail", passwordFrom: "data.adminPassword" } },
    ],
  },

  S0: {
    description: "Action 前状态",
    assertions: [
      { source: { caseStepId: "S0-1", method: "api" }, id: "session.authenticated", title: "当前会话 应为 已登录", object: "auth.session", operator: "authenticated" },
      { source: { caseStepId: "S0-2", method: "api" }, id: "session.email", title: "当前会话用户邮箱 应为 `orf-admin-trial-review-feedback-e2e@orf.local`", object: "auth.session.user_email", operator: "equals", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "S0-3", method: "api" }, id: "session.role", title: "当前会话用户角色 应为 `admin`", object: "auth.session.user_role", operator: "equals", params: { roleFrom: "data.adminRole" } },
      { source: { caseStepId: "S0-4", method: "api" }, id: "session.name", title: "当前会话用户名称 应为 `ORF Admin Trial Review Feedback E2E`", object: "auth.session.user_name", operator: "equals", params: { nameFrom: "data.adminName" } },
      { source: { caseStepId: "S0-5", method: "prisma" }, id: "db.frozen_objective.exists", title: "应存在 标题为 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK`、阶段为 `goalFrozen`、流转状态为 `frozen` 的目标", object: "db.frozen_objective_fixture", operator: "exists", params: { targetFrom: "data.target" } },
      { source: { caseStepId: "S0-6", method: "prisma" }, id: "db.frozen_objective.challenger_contains", title: "目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK` 的当前挑战者 应包含本用例普通成员", object: "db.frozen_objective_fixture", operator: "challenger_contains", params: { targetFrom: "data.target", memberUserFrom: "runtime.memberUser" } },
      { source: { caseStepId: "S0-7", method: "prisma" }, id: "db.frozen_objective.confirmed_at", title: "目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK` 的冻结时间 应存在", object: "db.frozen_objective_fixture", operator: "confirmed_at_exists", params: { targetFrom: "data.target" } },
      { source: { caseStepId: "S0-8", method: "prisma" }, id: "db.metric.exists", title: "应存在 归属于目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK`、口径为 `E2E-METRIC-ADMIN-TRIAL-REVIEW-FEEDBACK`、等级积分等级为 `进阶`、等级积分为 `30` 的指标", object: "db.metric", operator: "exists_with_score", params: { targetFrom: "data.target", titleFrom: "data.metric.title", difficultyFrom: "data.metric.difficulty", scoreFrom: "data.metric.score" } },
      { source: { caseStepId: "S0-9", method: "prisma" }, id: "db.trial_review.requested_exists", title: "应存在 归属于目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK`、状态为 `requested`、申请人为本用例普通成员、完成说明为 `E2E-TRIAL-REVIEW-FEEDBACK-BODY：普通成员提交待处理试验收材料。` 的试验收记录", object: "db.objective_trial_review", operator: "exists", params: { targetFrom: "data.target", trialReviewFrom: "data.trialReview", memberUserFrom: "runtime.memberUser", statusFrom: "data.trialReview.initialStatus" } },
      { source: { caseStepId: "S0-10", method: "prisma" }, id: "db.trial_review.self_test", title: "目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK` 的试验收记录 应包含自测报告 `E2E-TRIAL-REVIEW-FEEDBACK-SELF-TEST：已完成试验收前自测。`", object: "db.objective_trial_review", operator: "self_test", params: { targetFrom: "data.target", selfTestReportBodyFrom: "data.trialReview.selfTestReportBody" } },
      { source: { caseStepId: "S0-11", method: "prisma" }, id: "db.trial_review.metric_claim", title: "目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK` 的试验收记录 应包含指标 `E2E-METRIC-ADMIN-TRIAL-REVIEW-FEEDBACK` 的完成主张 `completed` 和证据 `E2E-TRIAL-REVIEW-FEEDBACK-EVIDENCE：https://example.test/trial-review-feedback`", object: "db.objective_trial_review", operator: "metric_claim", params: { targetFrom: "data.target", metricFrom: "data.metric" } },
      { source: { caseStepId: "S0-12", method: "prisma" }, id: "db.trial_review.feedback_empty", title: "目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK` 的试验收记录反馈说明 应为空", object: "db.objective_trial_review", operator: "feedback_empty", params: { targetFrom: "data.target" } },
      { source: { caseStepId: "S0-13", method: "prisma" }, id: "db.trial_review.reviewed_at_empty", title: "目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK` 的试验收记录处理时间 应为空", object: "db.objective_trial_review", operator: "reviewed_at_empty", params: { targetFrom: "data.target" } },
      { source: { caseStepId: "S0-14", method: "prisma" }, id: "db.objective_loot.count_zero", title: "目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK` 的战利品正式提交记录数量 应为 `0`", object: "db.objective_loot", operator: "count", params: { targetFrom: "data.target", count: 0 } },
    ],
  },

  Action: {
    description: "被测业务动作",
    steps: [
      { source: { caseStepId: "Action-1", method: "playwright" }, id: "admin.open_my_challenges", title: "管理员打开 我的挑战", object: "page.challenge", operator: "open_my_challenges" },
      { source: { caseStepId: "Action-2", method: "playwright" }, id: "trial_review.open", title: "点击目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK` 的 \"处理试验收\" 操作", object: "page.trial_review_feedback", operator: "open_from_all_challenges", params: { targetTitleFrom: "data.target.title" } },
      { source: { caseStepId: "Action-3", method: "playwright" }, id: "trial_review.page.loaded", title: "等待 处理试验收页面加载完成", object: "page.trial_review_feedback", operator: "loaded", params: { targetTitleFrom: "data.target.title" } },
      { source: { caseStepId: "Action-4", method: "playwright" }, id: "trial_review.material.visible", title: "页面 应显示试验收材料 `E2E-TRIAL-REVIEW-FEEDBACK-BODY：普通成员提交待处理试验收材料。`", object: "page.trial_review_feedback", operator: "material_visible", params: { bodyFrom: "data.trialReview.body" } },
      { source: { caseStepId: "Action-5", method: "playwright" }, id: "trial_review.evidence.visible", title: "页面 应显示指标 `E2E-METRIC-ADMIN-TRIAL-REVIEW-FEEDBACK` 的证据 `E2E-TRIAL-REVIEW-FEEDBACK-EVIDENCE：https://example.test/trial-review-feedback`", object: "page.trial_review_feedback", operator: "evidence_visible", params: { metricTitleFrom: "data.metric.title", evidenceFrom: "data.metric.evidence" } },
      { source: { caseStepId: "Action-6", method: "playwright" }, id: "trial_review.decision.select", title: "在 \"试验收结论\" 控件中选择 `可正式提交`", object: "page.trial_review_feedback", operator: "select_decision", params: { decisionLabel: "可正式提交" } },
      { source: { caseStepId: "Action-7", method: "playwright" }, id: "trial_review.feedback.fill", title: "在 \"反馈说明\" 输入框输入 `E2E-TRIAL-REVIEW-COMMANDER-FEEDBACK：材料完整，同意进入正式提交。`", object: "page.trial_review_feedback", operator: "fill_feedback", params: { feedbackFrom: "data.trialReview.commanderFeedback" } },
      { source: { caseStepId: "Action-8", method: "playwright" }, id: "trial_review.feedback.submit", title: "点击 \"提交反馈\" 操作", object: "page.trial_review_feedback", operator: "submit", params: { targetFrom: "data.target", trialReviewFrom: "data.trialReview", adminUserFrom: "runtime.adminUser", memberUserFrom: "runtime.memberUser" } },
    ],
  },

  S1: {
    description: "Action 后状态",
    assertions: [
      { source: { caseStepId: "S1-1", method: "playwright" }, id: "toast.feedback_submitted", title: "页面 应提示 试验收反馈已提交", object: "page.challenge_toast", operator: "trial_review_feedback_submitted" },
      { source: { caseStepId: "S1-2", method: "playwright" }, id: "challenge.page.url", title: "页面 应进入 我的挑战", object: "page.challenge", operator: "url" },
      { source: { caseStepId: "S1-3", method: "playwright" }, id: "scope.all.selected", title: "\"所有挑战\" 视图 应处于选中状态", object: "page.challenge_scope", operator: "selected", params: { label: "所有挑战" } },
      { source: { caseStepId: "S1-4", method: "playwright" }, id: "objective.visible", title: "我的挑战列表 应显示目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK`", object: "page.challenge_objectives", operator: "visible_title", params: { titleFrom: "data.target.title" } },
      { source: { caseStepId: "S1-5", method: "playwright" }, id: "objective.status.frozen", title: "目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK` 的状态 应显示为 已冻结", object: "page.challenge_objective", operator: "status_visible", params: { titleFrom: "data.target.title", statusLabel: "已冻结" } },
      { source: { caseStepId: "S1-6", method: "api" }, id: "api.all_challenges.contains_objective", title: "所有挑战数据 应包含目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK`", object: "api.all_challenges", operator: "contains_objective", params: { titleFrom: "data.target.title" } },
      { source: { caseStepId: "S1-7", method: "api" }, id: "api.all_challenges.objective_stage_flow", title: "所有挑战数据中目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK` 的阶段 应为 `goalFrozen`，流转状态 应为 `frozen`", object: "api.all_challenges", operator: "objective_stage_flow", params: { targetFrom: "data.target" } },
      { source: { caseStepId: "S1-8", method: "api" }, id: "api.all_challenges.contains_trial_review", title: "所有挑战数据中目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK` 应包含状态为 `approved`、申请人为本用例普通成员、反馈说明为 `E2E-TRIAL-REVIEW-COMMANDER-FEEDBACK：材料完整，同意进入正式提交。` 的试验收记录", object: "api.all_challenges", operator: "contains_trial_review", params: { targetTitleFrom: "data.target.title", statusFrom: "data.trialReview.reviewedStatus", commanderFeedbackFrom: "data.trialReview.commanderFeedback", memberUserFrom: "runtime.memberUser", adminUserFrom: "runtime.adminUser" } },
      { source: { caseStepId: "S1-9", method: "api" }, id: "api.all_challenges.reviewed_by", title: "所有挑战数据中目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK` 的试验收记录处理人 应为本用例管理员", object: "api.all_challenges", operator: "trial_review_reviewed_by", params: { targetTitleFrom: "data.target.title", adminUserFrom: "runtime.adminUser" } },
      { source: { caseStepId: "S1-10", method: "api" }, id: "api.all_challenges.reviewed_at_exists", title: "所有挑战数据中目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK` 的试验收记录处理时间 应存在", object: "api.all_challenges", operator: "trial_review_reviewed_at_exists", params: { targetTitleFrom: "data.target.title" } },
      { source: { caseStepId: "S1-11", method: "prisma" }, id: "db.frozen_objective.exists", title: "标题为 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK` 的目标阶段 应为 `goalFrozen`，流转状态 应为 `frozen`", object: "db.frozen_objective_fixture", operator: "exists", params: { targetFrom: "data.target" } },
      { source: { caseStepId: "S1-12", method: "prisma" }, id: "db.trial_review.approved_exists", title: "应存在 归属于目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK`、状态为 `approved`、申请人为本用例普通成员、反馈说明为 `E2E-TRIAL-REVIEW-COMMANDER-FEEDBACK：材料完整，同意进入正式提交。` 的试验收记录", object: "db.objective_trial_review", operator: "exists", params: { targetFrom: "data.target", trialReviewFrom: "data.trialReview", memberUserFrom: "runtime.memberUser", statusFrom: "data.trialReview.reviewedStatus", commanderFeedbackFrom: "data.trialReview.commanderFeedback" } },
      { source: { caseStepId: "S1-13", method: "prisma" }, id: "db.trial_review.reviewed_by", title: "目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK` 的试验收记录处理人 应为本用例管理员", object: "db.objective_trial_review", operator: "reviewed_by", params: { targetFrom: "data.target", adminUserFrom: "runtime.adminUser" } },
      { source: { caseStepId: "S1-14", method: "prisma" }, id: "db.trial_review.reviewed_at_exists", title: "目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK` 的试验收记录处理时间 应存在", object: "db.objective_trial_review", operator: "reviewed_at_exists", params: { targetFrom: "data.target" } },
      { source: { caseStepId: "S1-15", method: "prisma" }, id: "db.trial_review.count_one", title: "目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK` 的试验收记录数量 应为 `1`", object: "db.objective_trial_review", operator: "count", params: { targetFrom: "data.target", count: 1 } },
      { source: { caseStepId: "S1-16", method: "prisma" }, id: "db.objective_loot.count_zero", title: "目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK` 的战利品正式提交记录数量 应为 `0`", object: "db.objective_loot", operator: "count", params: { targetFrom: "data.target", count: 0 } },
      { source: { caseStepId: "S1-17", method: "prisma" }, id: "db.frozen_objective.challenger_still_contains", title: "目标 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK` 的当前挑战者 应仍包含本用例普通成员", object: "db.frozen_objective_fixture", operator: "challenger_contains", params: { targetFrom: "data.target", memberUserFrom: "runtime.memberUser" } },
    ],
  },

  Clean: {
    description: "恢复 B",
    steps: [
      { source: { caseStepId: "Clean-1", method: "prisma" }, id: "db.objectives.delete_created", title: "删除 本用例创建的目标标题前缀 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK` 对应的目标及其派生数据", object: "db.objectives_by_prefix", operator: "delete", params: { prefixFrom: "data.targetPrefix" } },
      { source: { caseStepId: "Clean-2", method: "api" }, id: "auth.logout", title: "注销当前管理员登录会话", object: "auth", operator: "logout" },
      { source: { caseStepId: "Clean-3", method: "playwright" }, id: "browser.clear", title: "移除当前浏览器中的残留登录态", object: "browser", operator: "clear_state" },
      { source: { caseStepId: "Clean-4", method: "api" }, id: "ory.admin_identity.delete", title: "删除 本用例管理员登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-5", method: "api" }, id: "ory.member_identity.delete", title: "删除 本用例普通成员登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-6", method: "prisma" }, id: "db.admin_user.delete", title: "删除 本用例管理员用户", object: "db.user", operator: "delete", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-7", method: "prisma" }, id: "db.member_user.delete", title: "删除 本用例普通成员用户", object: "db.user", operator: "delete", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-8", method: "prisma" }, id: "db.objectives.absent", title: "应不存在 标题前缀为 `E2E-TARGET-ADMIN-TRIAL-REVIEW-FEEDBACK` 的目标", object: "db.objectives_by_prefix", operator: "absent", params: { prefixFrom: "data.targetPrefix" } },
      { source: { caseStepId: "Clean-9", method: "prisma" }, id: "db.metric.absent", title: "应不存在 口径为 `E2E-METRIC-ADMIN-TRIAL-REVIEW-FEEDBACK` 的指标", object: "db.metric", operator: "absent", params: { titleFrom: "data.metric.title" } },
      { source: { caseStepId: "Clean-10", method: "api" }, id: "ory.admin_identity.absent", title: "邮箱为 `orf-admin-trial-review-feedback-e2e@orf.local` 的管理员登录身份 应不存在", object: "ory.identity", operator: "absent", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-11", method: "api" }, id: "ory.member_identity.absent", title: "邮箱为 `orf-member-trial-review-feedback-e2e@orf.local` 的普通成员登录身份 应不存在", object: "ory.identity", operator: "absent", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-12", method: "prisma" }, id: "db.admin_user.absent", title: "邮箱为 `orf-admin-trial-review-feedback-e2e@orf.local` 的管理员用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-13", method: "prisma" }, id: "db.member_user.absent", title: "邮箱为 `orf-member-trial-review-feedback-e2e@orf.local` 的普通成员用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-14", method: "api" }, id: "session.unauthenticated", title: "当前会话 应为 未登录", object: "auth.session", operator: "unauthenticated" },
    ],
  },
} satisfies StateCaseSpec<AdminTrialReviewFeedbackCaseData>;
