import { STATE_CASE_MODEL, type StateCaseSpec, type StepExecutionMethod, type StepSpec } from "../../_framework/types";
import type { SystemPermissionsEffectCaseData } from "./_support/permissions-effect.context";

function step(
  caseStepId: string,
  method: StepExecutionMethod,
  id: string,
  title: string,
  object: string,
  operator: string,
  params?: Record<string, unknown>,
): StepSpec {
  return {
    source: { caseStepId, method },
    id,
    title,
    object,
    operator,
    ...(params ? { params } : {}),
  };
}

export const systemPermissionsEffectCase = {
  id: "system.permissions-effect.save-and-apply",
  title: "12-权限管理保存与生效校验",
  model: STATE_CASE_MODEL,
  tags: ["system", "permissions", "effect"],
  data: {
    admin: {
      email: "orf-system-permissions-effect-admin-e2e@orf.local",
      password: "OrfSystemPermissionsEffectAdminE2E!2026",
      name: "ORF Permissions Effect Admin E2E",
      role: "admin",
    },
    member: {
      email: "orf-system-permissions-effect-member-e2e@orf.local",
      password: "OrfSystemPermissionsEffectMemberE2E!2026",
      name: "ORF Permissions Effect Member E2E",
      role: "member",
    },
    author: {
      email: "orf-system-permissions-effect-author-e2e@orf.local",
      password: "OrfSystemPermissionsEffectAuthorE2E!2026",
      name: "ORF Permissions Effect Author E2E",
      role: "member",
    },
    defaultLandingPath: "/bounties",
    permissionsPath: "/system/permissions",
    tasksPath: "/tasks",
    targetRole: "member",
    permissionKey: "comment.manage",
    objective: {
      id: "obj-system-permissions-effect-comment-target-e2e",
      title: "ORF Permissions Effect Comment Target E2E",
    },
    comment: {
      body: "ORF Permissions Effect Author Comment E2E",
      marker: "permissions-effect-comment",
      targetType: "objective",
    },
  },
  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      step("B-1", "api", "frontend.ready", "前端服务 应可用", "frontend.service", "available"),
      step("B-2", "api", "backend.ready", "后端服务 应可用", "api.health", "ok"),
      step("B-3", "api", "frontend.login_entry.accessible", "前端登录页入口 应可访问", "frontend.login_entry", "accessible"),
      step("B-4", "api", "session.endpoint.accessible", "当前会话查询能力 应可用", "auth.session", "accessible"),
      step("B-5", "prisma", "db.ready", "ORF 数据库 应可连接", "db", "ready"),
      step("B-6", "prisma", "db.schema.current", "ORF 数据库 schema 应为 当前测试版本", "db.schema", "current"),
      step("B-7", "api", "ory.admin_public.ready", "Ory/Kratos 认证服务的管理和公共访问能力 应可用", "ory.admin_public", "ready"),
      step("B-8", "api", "session.unauthenticated", "当前会话 应为 未登录", "auth.session", "unauthenticated"),
      step("B-9", "playwright", "cookie.absent", "当前浏览器 应不存在 Ory 登录会话 cookie", "browser.cookie", "absent"),
      step("B-10", "playwright", "storage.empty", "当前浏览器 应不保留本地登录态", "browser.auth_storage", "empty"),
    ],
  },
  Setup: {
    description: "准备管理员、普通成员、评论作者、评论目标和原始权限配置，并进入 member 权限配置页",
    steps: [
      step("Setup-1", "api", "ory.admin_identity.upsert", "准备邮箱为 `orf-system-permissions-effect-admin-e2e@orf.local`、使用固定测试密码的权限保存生效管理员测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.admin.email", passwordFrom: "data.admin.password", nameFrom: "data.admin.name", saveAs: "adminIdentity" }),
      step("Setup-2", "prisma", "db.admin_user.upsert", "准备姓名为 \"ORF Permissions Effect Admin E2E\"、邮箱为 `orf-system-permissions-effect-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的权限保存生效管理员测试用户", "db.user", "upsert", { emailFrom: "data.admin.email", passwordFrom: "data.admin.password", nameFrom: "data.admin.name", roleFrom: "data.admin.role", status: "active", identityIdFrom: "runtime.adminIdentity.id", saveAs: "adminUser" }),
      step("Setup-3", "api", "admin.preferences.default_landing_path.set", "设置权限保存生效管理员测试用户默认进入页面为 首页（默认系统页）", "user.preferences", "set_default_landing_path_by_email", { emailFrom: "data.admin.email", pathFrom: "data.defaultLandingPath" }),
      step("Setup-4", "api", "ory.member_identity.upsert", "准备邮箱为 `orf-system-permissions-effect-member-e2e@orf.local`、使用固定测试密码的权限保存生效普通成员测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.member.email", passwordFrom: "data.member.password", nameFrom: "data.member.name", saveAs: "memberIdentity" }),
      step("Setup-5", "prisma", "db.member_user.upsert", "准备姓名为 \"ORF Permissions Effect Member E2E\"、邮箱为 `orf-system-permissions-effect-member-e2e@orf.local`、角色为 `member`、状态为 `active` 的权限保存生效普通成员测试用户", "db.user", "upsert", { emailFrom: "data.member.email", passwordFrom: "data.member.password", nameFrom: "data.member.name", roleFrom: "data.member.role", status: "active", identityIdFrom: "runtime.memberIdentity.id", saveAs: "memberUser" }),
      step("Setup-6", "api", "member.preferences.default_landing_path.set", "设置权限保存生效普通成员测试用户默认进入页面为 首页（默认系统页）", "user.preferences", "set_default_landing_path_by_email", { emailFrom: "data.member.email", pathFrom: "data.defaultLandingPath" }),
      step("Setup-7", "api", "ory.author_identity.upsert", "准备邮箱为 `orf-system-permissions-effect-author-e2e@orf.local`、使用固定测试密码的权限保存生效评论作者测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.author.email", passwordFrom: "data.author.password", nameFrom: "data.author.name", saveAs: "authorIdentity" }),
      step("Setup-8", "prisma", "db.author_user.upsert", "准备姓名为 \"ORF Permissions Effect Author E2E\"、邮箱为 `orf-system-permissions-effect-author-e2e@orf.local`、角色为 `member`、状态为 `active` 的权限保存生效评论作者测试用户", "db.user", "upsert", { emailFrom: "data.author.email", passwordFrom: "data.author.password", nameFrom: "data.author.name", roleFrom: "data.author.role", status: "active", identityIdFrom: "runtime.authorIdentity.id", saveAs: "authorUser" }),
      step("Setup-9", "prisma", "db.comment_objective.prepare", "准备标题为 \"ORF Permissions Effect Comment Target E2E\" 的权限保存生效评论目标", "db.comment_objective", "prepare", { idFrom: "data.objective.id", titleFrom: "data.objective.title", teamIdFrom: "runtime.adminUser.teamId", memberNameFrom: "data.member.name", memberUserIdFrom: "runtime.memberUser.userId", authorNameFrom: "data.author.name", authorUserIdFrom: "runtime.authorUser.userId", saveAs: "commentTarget" }),
      step("Setup-10", "prisma", "db.comment.create_root", "准备权限保存生效评论作者测试用户在权限保存生效评论目标下发布的评论", "db.comment", "create_root", { actorEmailFrom: "data.author.email", actorNameFrom: "data.author.name", bodyFrom: "data.comment.body", markerFrom: "data.comment.marker", targetFrom: "runtime.commentTarget", saveAs: "comment" }),
      step("Setup-11", "api", "permissions.member.original_rules.record", "记录修改前的 `member` 角色权限配置", "api.permissions", "read_member_rules", { teamIdFrom: "runtime.adminUser.teamId", saveAs: "originalMemberPermissionRules" }),
      step("Setup-12", "api", "ory.admin_sessions.revoke", "撤销邮箱为 `orf-system-permissions-effect-admin-e2e@orf.local` 的权限保存生效管理员测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.admin.email" }),
      step("Setup-13", "api", "ory.member_sessions.revoke", "撤销邮箱为 `orf-system-permissions-effect-member-e2e@orf.local` 的权限保存生效普通成员测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.member.email" }),
      step("Setup-14", "api", "ory.author_sessions.revoke", "撤销邮箱为 `orf-system-permissions-effect-author-e2e@orf.local` 的权限保存生效评论作者测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.author.email" }),
      step("Setup-15", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Setup-16", "playwright", "page.goto.auth", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Setup-17", "playwright", "fill.admin_email", "在邮箱输入框输入 `orf-system-permissions-effect-admin-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.admin.email" }),
      step("Setup-18", "playwright", "fill.admin_password", "在密码输入框输入权限保存生效管理员测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.admin.password" }),
      step("Setup-19", "playwright", "click.sign_in", "点击 \"Sign In\" 登录操作", "page.login_form", "submit"),
      step("Setup-20", "api", "session.admin_authenticated", "当前会话 应为 邮箱为 `orf-system-permissions-effect-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
      step("Setup-21", "playwright", "page.goto.permissions", "打开 权限管理页面", "page", "goto", { pathFrom: "data.permissionsPath" }),
      step("Setup-22", "playwright", "role.member.click.setup", "选择 \"成员\" 角色切换操作", "page.role_tab", "click", { text: "成员" }),
    ],
  },
  S0: {
    description: "管理员已位于成员权限配置页，目标权限开关和评论数据可用",
    assertions: [
      step("S0-1", "api", "session.admin_authenticated", "当前会话 应为 邮箱为 `orf-system-permissions-effect-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
      step("S0-2", "playwright", "url.permissions", "当前页面 应为 权限管理页面", "page.url", "match", { pattern: "/system/permissions$" }),
      step("S0-3", "playwright", "role.member.selected", "权限管理页面的 \"成员\" 角色切换操作 应为 已选中", "page.role_tab", "selected", { text: "成员" }),
      step("S0-4", "playwright", "comment_manage.toggle.visible", "权限管理页面的 `comment.manage` 权限开关 应可见", "page.permission_toggle", "visible", { permissionKeyFrom: "data.permissionKey" }),
      step("S0-5", "api", "permissions.member.original_rules.recorded", "修改前的 `member` 角色权限配置 应已记录", "api.permissions", "recorded", { rulesFrom: "runtime.originalMemberPermissionRules" }),
      step("S0-6", "prisma", "db.member.exists", "邮箱为 `orf-system-permissions-effect-member-e2e@orf.local` 的权限保存生效普通成员测试用户 应存在", "db.user", "matches", { emailFrom: "data.member.email", roleFrom: "data.member.role", status: "active" }),
      step("S0-7", "prisma", "db.comment.persisted", "权限保存生效评论作者测试用户在权限保存生效评论目标下发布的评论 应存在", "db.comment", "root_persisted", { authorEmailFrom: "data.author.email", bodyFrom: "data.comment.body", targetFrom: "runtime.commentTarget" }),
    ],
  },
  Action: {
    description: "取消 member 评论管理权限并验证保存生效，再授予该权限并验证保存生效",
    steps: [
      step("Action-1", "playwright", "comment_manage.disable", "关闭 `member` 角色的 `comment.manage` 权限开关", "page.permission_toggle", "set", { permissionKeyFrom: "data.permissionKey", checked: false, originalRulesFrom: "runtime.originalMemberPermissionRules", roleFrom: "data.targetRole", saveAs: "disabledMemberPermissionRules" }),
      step("Action-2", "playwright", "permissions.save.disabled", "点击 \"保存角色权限\" 操作", "page.permissions_save", "submit", { saveAs: "disabledPermissionUpdateResponse" }),
      step("Action-3", "playwright", "page.reopen.permissions.disabled", "重新打开 权限管理页面", "page", "goto", { pathFrom: "data.permissionsPath" }),
      step("Action-4", "playwright", "role.member.click.disabled", "选择 \"成员\" 角色切换操作", "page.role_tab", "click", { text: "成员" }),
      step("Action-5", "playwright", "comment_manage.switch_state.record.disabled", "记录重新进入权限管理页面后 `member` 角色的 `comment.manage` 权限开关状态", "page.permission_toggle", "record_state", { permissionKeyFrom: "data.permissionKey", saveAs: "disabledSwitchState" }),
      step("Action-6", "api", "permissions.member.reread.disabled", "重新读取取消权限后的 `member` 角色权限配置", "api.permissions", "read_member_rules", { teamIdFrom: "runtime.adminUser.teamId", saveAs: "disabledMemberPermissionRulesRead" }),
      step("Action-7", "api", "auth.logout.disabled", "注销当前登录会话", "auth", "logout"),
      step("Action-8", "playwright", "browser.clear.disabled", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Action-9", "playwright", "page.goto.auth.member.disabled", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Action-10", "playwright", "fill.member_email.disabled", "在邮箱输入框输入 `orf-system-permissions-effect-member-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.member.email" }),
      step("Action-11", "playwright", "fill.member_password.disabled", "在密码输入框输入权限保存生效普通成员测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.member.password" }),
      step("Action-12", "playwright", "click.sign_in.member.disabled", "点击 \"Sign In\" 登录操作", "page.login_form", "submit"),
      step("Action-13", "api", "member.access.record.disabled", "记录普通成员在取消 `comment.manage` 权限后的权限范围", "api.current_access", "read", { saveAs: "disabledMemberAccess" }),
      step("Action-14", "playwright", "page.goto.tasks.disabled", "打开 权限保存生效评论目标详情页", "page.comment_target", "open", { pathFrom: "data.tasksPath", targetFrom: "runtime.commentTarget" }),
      step("Action-15", "playwright", "comment_manage.actions.record.disabled", "记录普通成员在取消 `comment.manage` 权限后的其他用户评论管理操作状态", "page.comment_manage_actions", "record", { bodyFrom: "data.comment.body", saveAs: "disabledCommentManageActions" }),
      step("Action-16", "api", "auth.logout.before_enable", "注销当前登录会话", "auth", "logout"),
      step("Action-17", "playwright", "browser.clear.before_enable", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Action-18", "playwright", "page.goto.auth.admin.enable", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Action-19", "playwright", "fill.admin_email.enable", "在邮箱输入框输入 `orf-system-permissions-effect-admin-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.admin.email" }),
      step("Action-20", "playwright", "fill.admin_password.enable", "在密码输入框输入权限保存生效管理员测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.admin.password" }),
      step("Action-21", "playwright", "click.sign_in.admin.enable", "点击 \"Sign In\" 登录操作", "page.login_form", "submit"),
      step("Action-22", "playwright", "page.goto.permissions.enable", "打开 权限管理页面", "page", "goto", { pathFrom: "data.permissionsPath" }),
      step("Action-23", "playwright", "role.member.click.enable", "选择 \"成员\" 角色切换操作", "page.role_tab", "click", { text: "成员" }),
      step("Action-24", "playwright", "comment_manage.enable", "开启 `member` 角色的 `comment.manage` 权限开关", "page.permission_toggle", "set", { permissionKeyFrom: "data.permissionKey", checked: true, originalRulesFrom: "runtime.disabledMemberPermissionRulesRead", roleFrom: "data.targetRole", saveAs: "enabledMemberPermissionRules" }),
      step("Action-25", "playwright", "permissions.save.enabled", "点击 \"保存角色权限\" 操作", "page.permissions_save", "submit", { saveAs: "enabledPermissionUpdateResponse" }),
      step("Action-26", "api", "permissions.member.reread.enabled", "重新读取授予权限后的 `member` 角色权限配置", "api.permissions", "read_member_rules", { teamIdFrom: "runtime.adminUser.teamId", saveAs: "enabledMemberPermissionRulesRead" }),
      step("Action-27", "api", "auth.logout.enabled", "注销当前登录会话", "auth", "logout"),
      step("Action-28", "playwright", "browser.clear.enabled", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Action-29", "playwright", "page.goto.auth.member.enabled", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Action-30", "playwright", "fill.member_email.enabled", "在邮箱输入框输入 `orf-system-permissions-effect-member-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.member.email" }),
      step("Action-31", "playwright", "fill.member_password.enabled", "在密码输入框输入权限保存生效普通成员测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.member.password" }),
      step("Action-32", "playwright", "click.sign_in.member.enabled", "点击 \"Sign In\" 登录操作", "page.login_form", "submit"),
      step("Action-33", "api", "member.access.record.enabled", "记录普通成员在授予 `comment.manage` 权限后的权限范围", "api.current_access", "read", { saveAs: "enabledMemberAccess" }),
      step("Action-34", "playwright", "page.goto.tasks.enabled", "打开 权限保存生效评论目标详情页", "page.comment_target", "open", { pathFrom: "data.tasksPath", targetFrom: "runtime.commentTarget" }),
      step("Action-35", "playwright", "comment_manage.actions.record.enabled", "记录普通成员在授予 `comment.manage` 权限后的其他用户评论管理操作状态", "page.comment_manage_actions", "record", { bodyFrom: "data.comment.body", saveAs: "enabledCommentManageActions" }),
    ],
  },
  S1: {
    description: "权限保存后页面配置持久化，普通成员权限范围和评论管理操作随权限变化",
    assertions: [
      step("S1-1", "playwright", "comment_manage.switch.disabled", "重新进入权限管理页面后，`member` 角色的 `comment.manage` 权限开关 应为 未开启状态", "page.permission_switch_state", "unchecked", { stateFrom: "runtime.disabledSwitchState" }),
      step("S1-2", "api", "permissions.disabled.excludes_comment_manage", "取消权限后重新读取的 `member` 角色权限配置 应不包含 `comment.manage` 权限", "api.permissions", "excludes", { rulesFrom: "runtime.disabledMemberPermissionRulesRead", roleFrom: "data.targetRole", permissionKeyFrom: "data.permissionKey" }),
      step("S1-3", "playwright", "comment_manage.actions.disabled", "普通成员在取消 `comment.manage` 权限后的其他用户评论管理操作 应不可用", "page.comment_manage_actions_state", "unavailable", { stateFrom: "runtime.disabledCommentManageActions" }),
      step("S1-4", "api", "member.access.disabled.excludes_comment_manage", "普通成员在取消 `comment.manage` 权限后的权限范围 应不包含 `comment.manage` 权限", "api.current_access", "excludes", { accessFrom: "runtime.disabledMemberAccess", permissionKeyFrom: "data.permissionKey" }),
      step("S1-5", "api", "permissions.enabled.includes_comment_manage", "授予权限后重新读取的 `member` 角色权限配置 应包含 `comment.manage` 权限", "api.permissions", "includes", { rulesFrom: "runtime.enabledMemberPermissionRulesRead", roleFrom: "data.targetRole", permissionKeyFrom: "data.permissionKey" }),
      step("S1-6", "playwright", "comment_manage.actions.enabled", "普通成员在授予 `comment.manage` 权限后的其他用户评论管理操作 应可用", "page.comment_manage_actions_state", "available", { stateFrom: "runtime.enabledCommentManageActions" }),
      step("S1-7", "api", "member.access.enabled.includes_comment_manage", "普通成员在授予 `comment.manage` 权限后的权限范围 应包含 `comment.manage` 权限", "api.current_access", "includes", { accessFrom: "runtime.enabledMemberAccess", permissionKeyFrom: "data.permissionKey" }),
      step("S1-8", "api", "session.member_authenticated.after_enable", "当前会话 应为 邮箱为 `orf-system-permissions-effect-member-e2e@orf.local`、角色为 `member`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.member.email", roleFrom: "data.member.role", status: "active" }),
    ],
  },
  Clean: {
    description: "恢复 member 权限配置，删除评论、目标、用户和认证身份，回到未登录基准状态",
    steps: [
      step("Clean-1", "api", "permissions.member.restore", "恢复 `member` 角色权限配置为修改前状态", "api.permissions", "restore_member", { rulesFrom: "runtime.originalMemberPermissionRules", teamIdFrom: "runtime.adminUser.teamId" }),
      step("Clean-2", "api", "auth.logout", "注销当前登录会话", "auth", "logout"),
      step("Clean-3", "playwright", "page.runtime.stop", "离开当前 ORF 前端页面", "page.runtime", "stop"),
      step("Clean-4", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Clean-5", "api", "ory.admin_sessions.revoke", "撤销邮箱为 `orf-system-permissions-effect-admin-e2e@orf.local` 的权限保存生效管理员测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-6", "api", "ory.member_sessions.revoke", "撤销邮箱为 `orf-system-permissions-effect-member-e2e@orf.local` 的权限保存生效普通成员测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.member.email" }),
      step("Clean-7", "api", "ory.author_sessions.revoke", "撤销邮箱为 `orf-system-permissions-effect-author-e2e@orf.local` 的权限保存生效评论作者测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.author.email" }),
      step("Clean-8", "api", "ory.admin_identity.delete", "删除邮箱为 `orf-system-permissions-effect-admin-e2e@orf.local` 的权限保存生效管理员测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-9", "api", "ory.member_identity.delete", "删除邮箱为 `orf-system-permissions-effect-member-e2e@orf.local` 的权限保存生效普通成员测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.member.email" }),
      step("Clean-10", "api", "ory.author_identity.delete", "删除邮箱为 `orf-system-permissions-effect-author-e2e@orf.local` 的权限保存生效评论作者测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.author.email" }),
      step("Clean-11", "api", "admin.preferences.default_landing_path.reset", "恢复邮箱为 `orf-system-permissions-effect-admin-e2e@orf.local` 的默认进入页面为 系统默认", "user.preferences", "reset_default_landing_path_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-12", "api", "member.preferences.default_landing_path.reset", "恢复邮箱为 `orf-system-permissions-effect-member-e2e@orf.local` 的默认进入页面为 系统默认", "user.preferences", "reset_default_landing_path_by_email", { emailFrom: "data.member.email" }),
      step("Clean-13", "prisma", "db.comments.delete", "删除权限保存生效评论作者测试用户在权限保存生效评论目标下发布的评论", "db.test_comments", "delete", { markerFrom: "data.comment.marker", actorEmailFrom: "data.author.email" }),
      step("Clean-14", "prisma", "db.objective.delete", "删除标题为 \"ORF Permissions Effect Comment Target E2E\" 的权限保存生效评论目标", "db.objective", "delete", { idFrom: "data.objective.id", titleFrom: "data.objective.title" }),
      step("Clean-15", "prisma", "db.admin_user.memberships.delete", "删除邮箱为 `orf-system-permissions-effect-admin-e2e@orf.local` 的权限保存生效管理员测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.admin.email" }),
      step("Clean-16", "prisma", "db.member_user.memberships.delete", "删除邮箱为 `orf-system-permissions-effect-member-e2e@orf.local` 的权限保存生效普通成员测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.member.email" }),
      step("Clean-17", "prisma", "db.author_user.memberships.delete", "删除邮箱为 `orf-system-permissions-effect-author-e2e@orf.local` 的权限保存生效评论作者测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.author.email" }),
      step("Clean-18", "prisma", "db.admin_user.delete", "删除邮箱为 `orf-system-permissions-effect-admin-e2e@orf.local` 的权限保存生效管理员测试用户", "db.user", "delete", { emailFrom: "data.admin.email" }),
      step("Clean-19", "prisma", "db.member_user.delete", "删除邮箱为 `orf-system-permissions-effect-member-e2e@orf.local` 的权限保存生效普通成员测试用户", "db.user", "delete", { emailFrom: "data.member.email" }),
      step("Clean-20", "prisma", "db.author_user.delete", "删除邮箱为 `orf-system-permissions-effect-author-e2e@orf.local` 的权限保存生效评论作者测试用户", "db.user", "delete", { emailFrom: "data.author.email" }),
      step("Clean-21", "api", "ory.admin_identity.absent", "邮箱为 `orf-system-permissions-effect-admin-e2e@orf.local` 的权限保存生效管理员测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.admin.email" }),
      step("Clean-22", "api", "ory.member_identity.absent", "邮箱为 `orf-system-permissions-effect-member-e2e@orf.local` 的权限保存生效普通成员测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.member.email" }),
      step("Clean-23", "api", "ory.author_identity.absent", "邮箱为 `orf-system-permissions-effect-author-e2e@orf.local` 的权限保存生效评论作者测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.author.email" }),
      step("Clean-24", "prisma", "db.admin_user.absent", "邮箱为 `orf-system-permissions-effect-admin-e2e@orf.local` 的权限保存生效管理员测试用户 应不存在", "db.user", "absent", { emailFrom: "data.admin.email" }),
      step("Clean-25", "prisma", "db.member_user.absent", "邮箱为 `orf-system-permissions-effect-member-e2e@orf.local` 的权限保存生效普通成员测试用户 应不存在", "db.user", "absent", { emailFrom: "data.member.email" }),
      step("Clean-26", "prisma", "db.author_user.absent", "邮箱为 `orf-system-permissions-effect-author-e2e@orf.local` 的权限保存生效评论作者测试用户 应不存在", "db.user", "absent", { emailFrom: "data.author.email" }),
      step("Clean-27", "prisma", "db.objective.absent", "标题为 \"ORF Permissions Effect Comment Target E2E\" 的权限保存生效评论目标 应不存在", "db.objective", "absent", { idFrom: "data.objective.id", titleFrom: "data.objective.title" }),
    ],
  },
} satisfies StateCaseSpec<SystemPermissionsEffectCaseData>;
