import { STATE_CASE_MODEL, type StateCaseSpec } from "../../_framework/types";
import type { AdminEditMemberCaseData } from "./_support/admin-edit-member.context";

export const adminEditMemberCase = {
  id: "members.admin-edit",
  title: "管理员可以编辑成员资料",
  model: STATE_CASE_MODEL,
  tags: ["members", "admin", "happy-path"],

  data: {
    adminEmail: "orf-admin-edit-member-e2e@orf.local",
    adminPassword: "OrfAdminEditMemberE2E!2026",
    adminName: "ORF Admin Edit Member E2E",
    adminRole: "admin",
    targetUserId: "user-testd-admin-edit-member",
    originalName: "ORF Member Edit Source E2E",
    originalEmail: "orf-member-edit-source-e2e@orf.local",
    originalRole: "member",
    updatedName: "ORF Member Edit Updated E2E",
    updatedEmail: "orf-member-edit-updated-e2e@orf.local",
    updatedRole: "admin",
    targetEmails: ["orf-member-edit-source-e2e@orf.local", "orf-member-edit-updated-e2e@orf.local"],
  },

  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      {
        source: { caseStepId: "B-1", method: "api" },
        id: "frontend.ready",
        title: "前端服务 应可用",
        object: "frontend.service",
        operator: "available",
      },
      {
        source: { caseStepId: "B-2", method: "api" },
        id: "backend.ready",
        title: "后端服务 应可用",
        object: "api.health",
        operator: "ok",
      },
      {
        source: { caseStepId: "B-3", method: "api" },
        id: "frontend.login_entry.accessible",
        title: "前端登录页入口 应可访问",
        object: "frontend.login_entry",
        operator: "accessible",
      },
      {
        source: { caseStepId: "B-4", method: "api" },
        id: "session.endpoint.accessible",
        title: "当前会话查询能力 应可用",
        object: "auth.session",
        operator: "accessible",
      },
      {
        source: { caseStepId: "B-5", method: "prisma" },
        id: "db.ready",
        title: "ORF 数据库 应可连接",
        object: "db",
        operator: "ready",
      },
      {
        source: { caseStepId: "B-6", method: "prisma" },
        id: "db.schema.current",
        title: "ORF 数据库 schema 应为 当前测试版本",
        object: "db.schema",
        operator: "current",
      },
      {
        source: { caseStepId: "B-7", method: "api" },
        id: "ory.admin_public.ready",
        title: "Ory/Kratos 认证服务的管理和公共访问能力 应可用",
        object: "ory.admin_public",
        operator: "ready",
      },
      {
        source: { caseStepId: "B-8", method: "api" },
        id: "session.unauthenticated",
        title: "当前会话 应为 未登录",
        object: "auth.session",
        operator: "unauthenticated",
      },
      {
        source: { caseStepId: "B-9", method: "playwright" },
        id: "cookie.absent",
        title: "当前浏览器 应不存在 Ory 登录会话 cookie",
        object: "browser.cookie",
        operator: "absent",
      },
      {
        source: { caseStepId: "B-10", method: "playwright" },
        id: "storage.empty",
        title: "当前浏览器 应不保留本地登录态",
        object: "browser.auth_storage",
        operator: "empty",
      },
    ],
  },

  Setup: {
    description: "准备管理员和可编辑成员，登录管理员并打开成员管理页",
    steps: [
      {
        source: { caseStepId: "Setup-1", method: "prisma" },
        id: "db.editable_member.delete_residue",
        title: "删除可能残留的本用例可编辑成员",
        object: "db.user",
        operator: "delete",
        params: {
          userIdFrom: "data.targetUserId",
          emailsFrom: "data.targetEmails",
        },
      },
      {
        source: { caseStepId: "Setup-2", method: "api" },
        id: "ory.admin_identity.upsert",
        title: "准备邮箱为 `orf-admin-edit-member-e2e@orf.local`、使用固定测试密码的管理员登录身份",
        object: "ory.identity",
        operator: "upsert_password",
        params: {
          emailFrom: "data.adminEmail",
          nameFrom: "data.adminName",
          passwordFrom: "data.adminPassword",
          saveAs: "adminIdentity",
        },
      },
      {
        source: { caseStepId: "Setup-3", method: "prisma" },
        id: "db.admin.upsert",
        title: "准备邮箱为 `orf-admin-edit-member-e2e@orf.local`、角色为 `admin`、状态为 `active` 的管理员用户和默认团队成员关系",
        object: "db.user",
        operator: "upsert",
        params: {
          emailFrom: "data.adminEmail",
          nameFrom: "data.adminName",
          roleFrom: "data.adminRole",
          status: "active",
          identityIdFrom: "runtime.adminIdentity.id",
          saveAs: "adminUser",
        },
      },
      {
        source: { caseStepId: "Setup-4", method: "api" },
        id: "ory.sessions.revoke",
        title: "撤销管理员登录身份可能残留的登录会话",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.adminEmail" },
      },
      {
        source: { caseStepId: "Setup-5", method: "playwright" },
        id: "browser.clear",
        title: "移除当前浏览器中的残留登录态",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "Setup-6", method: "prisma" },
        id: "db.editable_member.upsert",
        title: "创建姓名为 \"ORF Member Edit Source E2E\"、邮箱为 `orf-member-edit-source-e2e@orf.local`、角色为 `member`、状态为 `active` 的可编辑成员",
        object: "db.user",
        operator: "upsert",
        params: {
          userIdFrom: "data.targetUserId",
          emailFrom: "data.originalEmail",
          nameFrom: "data.originalName",
          roleFrom: "data.originalRole",
          status: "active",
          saveAs: "editableMember",
        },
      },
      {
        source: { caseStepId: "Setup-7", method: "playwright" },
        id: "page.goto.auth",
        title: "打开 ORF 登录页",
        object: "page",
        operator: "goto",
        params: { path: "/auth" },
      },
      {
        source: { caseStepId: "Setup-8", method: "playwright" },
        id: "fill.email",
        title: "在邮箱输入框输入管理员固定测试邮箱",
        object: "page",
        operator: "fill",
        params: { label: "Email", valueFrom: "data.adminEmail" },
      },
      {
        source: { caseStepId: "Setup-9", method: "playwright" },
        id: "fill.password",
        title: "在密码输入框输入管理员固定测试密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.adminPassword" },
      },
      {
        source: { caseStepId: "Setup-10", method: "playwright" },
        id: "click.sign_in",
        title: "点击 \"Sign In\" 登录操作",
        object: "page",
        operator: "click",
        params: { role: "button", name: "Sign In" },
      },
      {
        source: { caseStepId: "Setup-11", method: "api" },
        id: "session.admin.authenticated",
        title: "当前会话 应为 管理员的已登录会话",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.adminEmail", roleFrom: "data.adminRole", status: "active" },
      },
      {
        source: { caseStepId: "Setup-12", method: "playwright" },
        id: "page.goto.members",
        title: "打开 系统管理的成员管理页面",
        object: "page",
        operator: "goto",
        params: { path: "/system/members" },
      },
    ],
  },

  S0: {
    description: "管理员已登录，成员管理页显示原测试成员且可编辑",
    assertions: [
      {
        source: { caseStepId: "S0-1", method: "api" },
        id: "session.admin.authenticated",
        title: "当前会话 应为 邮箱为 `orf-admin-edit-member-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.adminEmail", roleFrom: "data.adminRole", status: "active" },
      },
      {
        source: { caseStepId: "S0-2", method: "playwright" },
        id: "url.members",
        title: "当前页面 应为 成员管理页面",
        object: "page.url",
        operator: "match",
        params: { pattern: "/system/members$" },
      },
      {
        source: { caseStepId: "S0-3", method: "playwright" },
        id: "page.member_row.original.visible",
        title: "成员管理列表 应显示 原测试成员",
        object: "page.member_row",
        operator: "visible",
        params: { textFrom: "data.originalEmail" },
      },
      {
        source: { caseStepId: "S0-4", method: "playwright" },
        id: "page.member_row.original.edit_visible",
        title: "原测试成员 的 \"编辑\" 操作 应可见",
        object: "page.member_row",
        operator: "edit_visible",
        params: { textFrom: "data.originalEmail" },
      },
      {
        source: { caseStepId: "S0-5", method: "prisma" },
        id: "db.editable_member.original_name",
        title: "原测试成员 的姓名 应为 \"ORF Member Edit Source E2E\"",
        object: "db.user",
        operator: "matches",
        params: { userIdFrom: "data.targetUserId", nameFrom: "data.originalName", status: "active" },
      },
      {
        source: { caseStepId: "S0-6", method: "prisma" },
        id: "db.editable_member.original_email",
        title: "原测试成员 的邮箱 应为 \"orf-member-edit-source-e2e@orf.local\"",
        object: "db.user",
        operator: "matches",
        params: { userIdFrom: "data.targetUserId", emailFrom: "data.originalEmail", status: "active" },
      },
      {
        source: { caseStepId: "S0-7", method: "prisma" },
        id: "db.editable_member.original_role",
        title: "原测试成员 的角色 应为 member",
        object: "db.user",
        operator: "matches",
        params: { userIdFrom: "data.targetUserId", roleFrom: "data.originalRole", status: "active" },
      },
    ],
  },

  Action: {
    description: "管理员编辑测试成员姓名、邮箱和角色",
    steps: [
      {
        source: { caseStepId: "Action-1", method: "api" },
        id: "api.user_update.capture",
        title: "监听编辑成员请求响应",
        object: "api.user_update",
        operator: "capture",
        params: { userIdFrom: "data.targetUserId", saveAs: "updateUserResponse" },
      },
      {
        source: { caseStepId: "Action-2", method: "playwright" },
        id: "page.member_row.original.edit",
        title: "点击 原测试成员 的 \"编辑\" 操作",
        object: "page.member_row",
        operator: "edit",
        params: { textFrom: "data.originalEmail" },
      },
      {
        source: { caseStepId: "Action-3", method: "playwright" },
        id: "page.member_dialog.fill_name",
        title: "填写 姓名 输入框 为 \"ORF Member Edit Updated E2E\"",
        object: "page.member_dialog",
        operator: "fill_name",
        params: { valueFrom: "data.updatedName" },
      },
      {
        source: { caseStepId: "Action-4", method: "playwright" },
        id: "page.member_dialog.fill_email",
        title: "填写 邮箱 输入框 为 \"orf-member-edit-updated-e2e@orf.local\"",
        object: "page.member_dialog",
        operator: "fill_email",
        params: { valueFrom: "data.updatedEmail" },
      },
      {
        source: { caseStepId: "Action-5", method: "playwright" },
        id: "page.member_dialog.select_role",
        title: "选择 角色 为 admin",
        object: "page.member_dialog",
        operator: "select_role",
        params: { roleFrom: "data.updatedRole" },
      },
      {
        source: { caseStepId: "Action-6", method: "playwright" },
        id: "page.member_dialog.submit",
        title: "点击 \"保存\" 操作",
        object: "page.member_dialog",
        operator: "submit",
      },
    ],
  },

  S1: {
    description: "编辑接口成功，数据库和成员管理页显示更新后的成员资料",
    assertions: [
      {
        source: { caseStepId: "S1-1", method: "api" },
        id: "api.user_update.response_ok",
        title: "编辑成员结果 应成功",
        object: "api.response",
        operator: "ok",
        params: { responseFrom: "runtime.updateUserResponse", status: 200 },
      },
      {
        source: { caseStepId: "S1-2", method: "prisma" },
        id: "db.editable_member.updated_name",
        title: "已编辑成员 的姓名 应为 \"ORF Member Edit Updated E2E\"",
        object: "db.user",
        operator: "matches",
        params: { userIdFrom: "data.targetUserId", nameFrom: "data.updatedName", status: "active" },
      },
      {
        source: { caseStepId: "S1-3", method: "prisma" },
        id: "db.editable_member.updated_email",
        title: "已编辑成员 的邮箱 应为 \"orf-member-edit-updated-e2e@orf.local\"",
        object: "db.user",
        operator: "matches",
        params: { userIdFrom: "data.targetUserId", emailFrom: "data.updatedEmail", status: "active" },
      },
      {
        source: { caseStepId: "S1-4", method: "prisma" },
        id: "db.editable_member.updated_role",
        title: "已编辑成员 的角色 应为 admin",
        object: "db.user",
        operator: "matches",
        params: { userIdFrom: "data.targetUserId", roleFrom: "data.updatedRole", status: "active" },
      },
      {
        source: { caseStepId: "S1-5", method: "playwright" },
        id: "page.member_row.updated.visible",
        title: "成员管理列表 应显示 已编辑成员",
        object: "page.member_row",
        operator: "visible",
        params: { textFrom: "data.updatedEmail" },
      },
      {
        source: { caseStepId: "S1-6", method: "playwright" },
        id: "page.member_row.original.absent",
        title: "成员管理列表 应不显示 原测试成员",
        object: "page.member_row",
        operator: "absent",
        params: { textFrom: "data.originalEmail" },
      },
      {
        source: { caseStepId: "S1-7", method: "api" },
        id: "session.admin.still_authenticated",
        title: "当前会话 应仍为 管理员的已登录会话",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.adminEmail", roleFrom: "data.adminRole", status: "active" },
      },
    ],
  },

  Clean: {
    description: "删除可编辑成员并删除管理员编辑成员测试独占 fixture",
    steps: [
      {
        source: { caseStepId: "Clean-1", method: "prisma" },
        id: "db.editable_member.delete",
        title: "删除 本用例可编辑成员",
        object: "db.user",
        operator: "delete",
        params: {
          userIdFrom: "data.targetUserId",
          emailsFrom: "data.targetEmails",
        },
      },
      {
        source: { caseStepId: "Clean-2", method: "prisma" },
        id: "db.editable_member.absent",
        title: "本用例可编辑成员 应不存在",
        object: "db.user",
        operator: "absent",
        params: {
          userIdFrom: "data.targetUserId",
          emailsFrom: "data.targetEmails",
        },
      },
      {
        source: { caseStepId: "Clean-3", method: "api" },
        id: "auth.logout",
        title: "注销当前登录会话",
        object: "auth",
        operator: "logout",
      },
      {
        source: { caseStepId: "Clean-4", method: "playwright" },
        id: "page.runtime.stop",
        title: "离开当前 ORF 前端页面",
        object: "page.runtime",
        operator: "stop",
      },
      {
        source: { caseStepId: "Clean-5", method: "playwright" },
        id: "browser.clear",
        title: "移除当前浏览器中的残留登录态",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "Clean-6", method: "api" },
        id: "ory.sessions.revoke",
        title: "撤销管理员登录身份的残留登录会话",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.adminEmail" },
      },
      {
        source: { caseStepId: "Clean-7", method: "api" },
        id: "ory.admin_identity.delete",
        title: "删除邮箱为 `orf-admin-edit-member-e2e@orf.local` 的管理员登录身份",
        object: "ory.identity",
        operator: "delete_by_email",
        params: { emailFrom: "data.adminEmail" },
      },
      {
        source: { caseStepId: "Clean-8", method: "prisma" },
        id: "db.admin.memberships.delete",
        title: "删除管理员用户的默认团队成员关系",
        object: "db.user",
        operator: "delete_memberships",
        params: { emailFrom: "data.adminEmail" },
      },
      {
        source: { caseStepId: "Clean-9", method: "prisma" },
        id: "db.admin.delete",
        title: "删除邮箱为 `orf-admin-edit-member-e2e@orf.local` 的管理员用户",
        object: "db.user",
        operator: "delete",
        params: { emailFrom: "data.adminEmail" },
      },
    ],
  },
} satisfies StateCaseSpec<AdminEditMemberCaseData>;
