import {
  STATE_CASE_MODEL,
  type StateCaseSpec,
  type StepExecutionMethod,
  type StepSpec,
} from "../../_framework/types";
import type { UserMenuActionsCaseData } from "./_support/user-menu-actions.context";

function step(
  caseStepId: string,
  method: StepExecutionMethod,
  id: string,
  title: string,
  object: string,
  operator: string,
  params?: Record<string, unknown>,
): StepSpec {
  return {
    source: { caseStepId, method },
    id,
    title,
    object,
    operator,
    ...(params ? { params } : {}),
  };
}

export const userMenuActionsCase = {
  id: "defaults.user-menu.actions",
  title: "08-首页用户菜单入口操作正常",
  model: STATE_CASE_MODEL,
  tags: ["defaults", "user-menu", "notifications", "profile"],

  data: {
    avatarUser: {
      email: "orf-default-page-user-menu-avatar-e2e@orf.local",
      password: "OrfDefaultPageUserMenuAvatarE2E!2026",
      name: "ORF 默认页头像用户",
      role: "member",
    },
    noAvatarUser: {
      email: "orf-default-page-user-menu-no-avatar-e2e@orf.local",
      password: "OrfDefaultPageUserMenuNoAvatarE2E!2026",
      name: "ORF 默认页无头像用户",
      role: "member",
    },
    defaultLandingPath: "/bounties",
    homePath: "/dashboard",
  },

  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      step("B-1", "api", "frontend.ready", "前端服务 应可用", "frontend.service", "available"),
      step("B-2", "api", "backend.ready", "后端服务 应可用", "api.health", "ok"),
      step("B-3", "api", "frontend.login_entry.accessible", "前端登录页入口 应可访问", "frontend.login_entry", "accessible"),
      step("B-4", "api", "session.endpoint.accessible", "当前会话查询能力 应可用", "auth.session", "accessible"),
      step("B-5", "prisma", "db.ready", "ORF 数据库 应可连接", "db", "ready"),
      step("B-6", "prisma", "db.schema.current", "ORF 数据库 schema 应为 当前测试版本", "db.schema", "current"),
      step("B-7", "api", "ory.admin_public.ready", "Ory/Kratos 认证服务的管理和公共访问能力 应可用", "ory.admin_public", "ready"),
      step("B-8", "api", "session.unauthenticated", "当前会话 应为 未登录", "auth.session", "unauthenticated"),
      step("B-9", "playwright", "cookie.absent", "当前浏览器 应不存在 Ory 登录会话 cookie", "browser.cookie", "absent"),
      step("B-10", "playwright", "storage.empty", "当前浏览器 应不保留本地登录态", "browser.auth_storage", "empty"),
    ],
  },

  Setup: {
    description: "准备有头像和无头像的默认系统页测试用户，并以有头像用户登录首页",
    steps: [
      step("Setup-1", "api", "ory.avatar_identity.upsert", "准备邮箱为 `orf-default-page-user-menu-avatar-e2e@orf.local`、使用固定测试密码的默认系统页用户菜单自定义头像测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.avatarUser.email", passwordFrom: "data.avatarUser.password", nameFrom: "data.avatarUser.name", saveAs: "avatarIdentity" }),
      step("Setup-2", "prisma", "db.avatar_user.upsert", "准备邮箱为 `orf-default-page-user-menu-avatar-e2e@orf.local`、姓名为 `ORF 默认页头像用户`、角色为 `member`、状态为 `active` 的默认系统页用户菜单自定义头像测试用户", "db.user", "upsert", { emailFrom: "data.avatarUser.email", passwordFrom: "data.avatarUser.password", nameFrom: "data.avatarUser.name", roleFrom: "data.avatarUser.role", status: "active", identityIdFrom: "runtime.avatarIdentity.id", saveAs: "avatarUser" }),
      step("Setup-3", "api", "avatar_user.avatar.upload", "为默认系统页用户菜单自定义头像测试用户上传自定义头像", "user.avatar", "upload_by_email", { emailFrom: "data.avatarUser.email" }),
      step("Setup-4", "api", "avatar_user.preferences.default_landing_path.set", "设置默认系统页用户菜单自定义头像测试用户默认进入页面为 首页（默认系统页）", "user.preferences", "set_default_landing_path_by_email", { emailFrom: "data.avatarUser.email", pathFrom: "data.defaultLandingPath" }),
      step("Setup-5", "api", "ory.no_avatar_identity.upsert", "准备邮箱为 `orf-default-page-user-menu-no-avatar-e2e@orf.local`、使用固定测试密码的默认系统页用户菜单无自定义头像测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.noAvatarUser.email", passwordFrom: "data.noAvatarUser.password", nameFrom: "data.noAvatarUser.name", saveAs: "noAvatarIdentity" }),
      step("Setup-6", "prisma", "db.no_avatar_user.upsert", "准备邮箱为 `orf-default-page-user-menu-no-avatar-e2e@orf.local`、姓名为 `ORF 默认页无头像用户`、角色为 `member`、状态为 `active` 的默认系统页用户菜单无自定义头像测试用户", "db.user", "upsert", { emailFrom: "data.noAvatarUser.email", passwordFrom: "data.noAvatarUser.password", nameFrom: "data.noAvatarUser.name", roleFrom: "data.noAvatarUser.role", status: "active", identityIdFrom: "runtime.noAvatarIdentity.id", saveAs: "noAvatarUser" }),
      step("Setup-7", "api", "no_avatar_user.avatar.absent", "确保默认系统页用户菜单无自定义头像测试用户未上传自定义头像", "user.avatar", "ensure_absent_by_email", { emailFrom: "data.noAvatarUser.email" }),
      step("Setup-8", "api", "no_avatar_user.preferences.default_landing_path.set", "设置默认系统页用户菜单无自定义头像测试用户默认进入页面为 首页（默认系统页）", "user.preferences", "set_default_landing_path_by_email", { emailFrom: "data.noAvatarUser.email", pathFrom: "data.defaultLandingPath" }),
      step("Setup-9", "api", "ory.avatar_sessions.revoke", "撤销邮箱为 `orf-default-page-user-menu-avatar-e2e@orf.local` 的默认系统页用户菜单自定义头像测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.avatarUser.email" }),
      step("Setup-10", "api", "ory.no_avatar_sessions.revoke", "撤销邮箱为 `orf-default-page-user-menu-no-avatar-e2e@orf.local` 的默认系统页用户菜单无自定义头像测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.noAvatarUser.email" }),
      step("Setup-11", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Setup-12", "playwright", "page.goto.auth", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Setup-13", "playwright", "fill.avatar_email", "在邮箱输入框输入 `orf-default-page-user-menu-avatar-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.avatarUser.email" }),
      step("Setup-14", "playwright", "fill.avatar_password", "在密码输入框输入默认系统页用户菜单自定义头像测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.avatarUser.password" }),
      step("Setup-15", "playwright", "click.sign_in.avatar", "点击 \"Sign In\" 登录操作", "page.login_form", "submit", { saveAs: "avatarLoginResponse" }),
      step("Setup-16", "api", "session.avatar_authenticated", "当前会话 应为 邮箱为 `orf-default-page-user-menu-avatar-e2e@orf.local`、角色为 `member`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.avatarUser.email", roleFrom: "data.avatarUser.role", status: "active" }),
      step("Setup-17", "playwright", "page.goto.home", "打开 首页（默认系统页）", "page", "goto", { pathFrom: "data.homePath" }),
    ],
  },

  S0: {
    description: "有头像用户已登录首页，通知入口和侧边栏用户区域可用",
    assertions: [
      step("S0-1", "api", "session.avatar_authenticated", "当前会话 应为 邮箱为 `orf-default-page-user-menu-avatar-e2e@orf.local`、角色为 `member`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.avatarUser.email", roleFrom: "data.avatarUser.role", status: "active" }),
      step("S0-2", "playwright", "url.home", "当前页面 应为 首页（默认系统页）", "page.url", "match", { pattern: "/dashboard$" }),
      step("S0-3", "playwright", "topbar.notifications.visible", "顶部导航栏的通知入口 应可见", "topbar.notifications", "visible"),
      step("S0-4", "playwright", "topbar.notifications.enabled", "顶部导航栏的通知入口 应可点击", "topbar.notifications", "enabled"),
      step("S0-5", "playwright", "sidebar.current_user_avatar.visible", "侧边栏底部的当前用户头像 应可见", "sidebar.current_user_avatar", "visible"),
      step("S0-6", "playwright", "sidebar.current_user_name.text", "侧边栏底部的当前用户名 应显示 `ORF 默认页头像用户`", "sidebar.current_user_name", "text", { nameFrom: "data.avatarUser.name" }),
      step("S0-7", "playwright", "sidebar.user_menu.visible", "侧边栏底部的用户菜单入口 应可见", "sidebar.user_menu", "visible"),
      step("S0-8", "playwright", "sidebar.user_menu.enabled", "侧边栏底部的用户菜单入口 应可点击", "sidebar.user_menu", "enabled"),
    ],
  },

  Action: {
    description: "依次验证通知、头像预览、个人设置、关于更新、退出登录和无头像用户菜单",
    steps: [
      step("Action-1", "playwright", "topbar.notifications.click", "点击 顶部导航栏的通知入口", "topbar.notifications", "click"),
      step("Action-2", "playwright", "notifications.list.visible", "验证 通知消息列表 应可见", "notifications.list", "visible"),
      step("Action-3", "playwright", "notifications.list.close", "关闭 通知消息列表", "notifications.list", "close"),
      step("Action-4", "playwright", "page.goto.home.after_notifications", "打开 首页（默认系统页）", "page", "goto", { pathFrom: "data.homePath" }),
      step("Action-5", "playwright", "sidebar.user_menu.click.avatar", "点击 侧边栏底部的用户菜单入口", "sidebar.user_menu", "click"),
      step("Action-6", "playwright", "avatar_user.user_menu.visible", "验证 自定义头像测试用户的用户菜单 应可见", "user_menu", "visible"),
      step("Action-7", "playwright", "avatar_user.view_avatar.visible", "验证 用户菜单中的 \"查看头像\" 操作 应可见", "user_menu.item", "visible", { name: "查看头像" }),
      step("Action-8", "playwright", "avatar_user.settings.visible", "验证 用户菜单中的 \"个人设置\" 操作 应可见", "user_menu.item", "visible", { name: "个人设置" }),
      step("Action-9", "playwright", "avatar_user.about.visible", "验证 用户菜单中的 \"关于与更新\" 操作 应可见", "user_menu.item", "visible", { name: "关于与更新" }),
      step("Action-10", "playwright", "avatar_user.logout.visible", "验证 用户菜单中的 \"退出登录\" 操作 应可见", "user_menu.item", "visible", { name: "退出登录" }),
      step("Action-11", "playwright", "user_menu.avatar_preview.click", "点击 用户菜单中的 \"查看头像\" 操作", "page.user_menu_item", "click", { name: "查看头像" }),
      step("Action-12", "playwright", "avatar_preview.visible", "验证 查看头像弹窗 应可见", "avatar_preview", "visible"),
      step("Action-13", "playwright", "avatar_preview.close", "关闭 查看头像弹窗", "avatar_preview", "close"),
      step("Action-14", "playwright", "avatar_preview.hidden", "验证 查看头像弹窗 应不可见", "avatar_preview", "hidden"),
      step("Action-15", "playwright", "sidebar.user_menu.click.settings", "点击 侧边栏底部的用户菜单入口", "sidebar.user_menu", "click"),
      step("Action-16", "playwright", "user_menu.settings.click", "点击 用户菜单中的 \"个人设置\" 操作", "page.user_menu_item", "click", { name: "个人设置" }),
      step("Action-17", "playwright", "url.personal_settings", "验证 当前页面 应为 个人设置页面", "page.url", "match", { pattern: "/settings$" }),
      step("Action-18", "playwright", "personal_settings.title.visible", "验证 个人设置页面 应显示 `个人设置` 页面标题", "page", "visible", { role: "heading", name: "个人设置", exact: true }),
      step("Action-19", "playwright", "page.goto.home.after_settings", "打开 首页（默认系统页）", "page", "goto", { pathFrom: "data.homePath" }),
      step("Action-20", "playwright", "sidebar.user_menu.click.about", "点击 侧边栏底部的用户菜单入口", "sidebar.user_menu", "click"),
      step("Action-21", "playwright", "user_menu.about.click", "点击 用户菜单中的 \"关于与更新\" 操作", "page.user_menu_item", "click", { name: "关于与更新" }),
      step("Action-22", "playwright", "about_update_dialog.visible", "验证 关于与更新弹窗 应可见", "about_update_dialog", "visible"),
      step("Action-23", "playwright", "about_update_dialog.close", "关闭 关于与更新弹窗", "about_update_dialog", "close"),
      step("Action-24", "playwright", "about_update_dialog.hidden", "验证 关于与更新弹窗 应不可见", "about_update_dialog", "hidden"),
      step("Action-25", "playwright", "sidebar.user_menu.click.logout", "点击 侧边栏底部的用户菜单入口", "sidebar.user_menu", "click"),
      step("Action-26", "playwright", "user_menu.logout.click", "点击 用户菜单中的 \"退出登录\" 操作", "page.user_menu_item", "click", { name: "退出登录" }),
      step("Action-27", "playwright", "auth_page.visible.after_logout", "验证 前端登录页 应可见", "page", "visible", { role: "button", name: "Sign In" }),
      step("Action-28", "api", "session.unauthenticated.after_logout", "当前会话 应为 未登录", "auth.session", "unauthenticated"),
      step("Action-29", "playwright", "browser.clear.after_logout", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Action-30", "playwright", "page.goto.auth.no_avatar", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Action-31", "playwright", "fill.no_avatar_email", "在邮箱输入框输入 `orf-default-page-user-menu-no-avatar-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.noAvatarUser.email" }),
      step("Action-32", "playwright", "fill.no_avatar_password", "在密码输入框输入默认系统页用户菜单无自定义头像测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.noAvatarUser.password" }),
      step("Action-33", "playwright", "click.sign_in.no_avatar", "点击 \"Sign In\" 登录操作", "page.login_form", "submit", { saveAs: "noAvatarLoginResponse" }),
      step("Action-34", "api", "session.no_avatar_authenticated", "当前会话 应为 邮箱为 `orf-default-page-user-menu-no-avatar-e2e@orf.local`、角色为 `member`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.noAvatarUser.email", roleFrom: "data.noAvatarUser.role", status: "active" }),
      step("Action-35", "playwright", "page.goto.home.no_avatar", "打开 首页（默认系统页）", "page", "goto", { pathFrom: "data.homePath" }),
      step("Action-36", "playwright", "sidebar.user_menu.click.no_avatar", "点击 侧边栏底部的用户菜单入口", "sidebar.user_menu", "click"),
    ],
  },

  S1: {
    description: "无头像用户已登录首页，用户菜单按头像状态正确展示",
    assertions: [
      step("S1-1", "api", "session.no_avatar_authenticated.final", "当前会话 应为 邮箱为 `orf-default-page-user-menu-no-avatar-e2e@orf.local`、角色为 `member`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.noAvatarUser.email", roleFrom: "data.noAvatarUser.role", status: "active" }),
      step("S1-2", "playwright", "url.home.no_avatar", "当前页面 应为 首页（默认系统页）", "page.url", "match", { pattern: "/dashboard$" }),
      step("S1-3", "playwright", "no_avatar_user.avatar.visible", "无自定义头像测试用户进入首页后，侧边栏底部的当前用户头像 应可见", "sidebar.current_user_avatar", "visible"),
      step("S1-4", "playwright", "no_avatar_user.name.text", "无自定义头像测试用户进入首页后，侧边栏底部的当前用户名 应显示 `ORF 默认页无头像用户`", "sidebar.current_user_name", "text", { nameFrom: "data.noAvatarUser.name" }),
      step("S1-5", "playwright", "no_avatar_user.user_menu.visible", "无自定义头像测试用户的用户菜单 应可见", "user_menu", "visible"),
      step("S1-6", "playwright", "no_avatar_user.view_avatar.hidden", "无自定义头像测试用户的用户菜单中的 \"查看头像\" 操作 应不可见", "user_menu.item", "hidden", { name: "查看头像" }),
      step("S1-7", "playwright", "no_avatar_user.settings.visible", "无自定义头像测试用户的用户菜单中的 \"个人设置\" 操作 应可见", "user_menu.item", "visible", { name: "个人设置" }),
      step("S1-8", "playwright", "no_avatar_user.about.visible", "无自定义头像测试用户的用户菜单中的 \"关于与更新\" 操作 应可见", "user_menu.item", "visible", { name: "关于与更新" }),
      step("S1-9", "playwright", "no_avatar_user.logout.visible", "无自定义头像测试用户的用户菜单中的 \"退出登录\" 操作 应可见", "user_menu.item", "visible", { name: "退出登录" }),
    ],
  },

  Clean: {
    description: "删除测试用户头像、账号和页面会话状态，恢复未登录基准状态",
    steps: [
      step("Clean-1", "api", "auth.logout", "注销当前登录会话", "auth", "logout"),
      step("Clean-2", "playwright", "page.runtime.stop", "离开当前 ORF 前端页面", "page.runtime", "stop"),
      step("Clean-3", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Clean-4", "api", "ory.avatar_sessions.revoke", "撤销邮箱为 `orf-default-page-user-menu-avatar-e2e@orf.local` 的默认系统页用户菜单自定义头像测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.avatarUser.email" }),
      step("Clean-5", "api", "ory.no_avatar_sessions.revoke", "撤销邮箱为 `orf-default-page-user-menu-no-avatar-e2e@orf.local` 的默认系统页用户菜单无自定义头像测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.noAvatarUser.email" }),
      step("Clean-6", "api", "avatar_user.avatar.delete", "删除默认系统页用户菜单自定义头像测试用户的自定义头像文件", "user.avatar", "delete_by_email", { emailFrom: "data.avatarUser.email" }),
      step("Clean-7", "api", "no_avatar_user.avatar.delete", "删除默认系统页用户菜单无自定义头像测试用户的自定义头像文件", "user.avatar", "delete_by_email", { emailFrom: "data.noAvatarUser.email" }),
      step("Clean-8", "api", "ory.avatar_identity.delete", "删除邮箱为 `orf-default-page-user-menu-avatar-e2e@orf.local` 的默认系统页用户菜单自定义头像测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.avatarUser.email" }),
      step("Clean-9", "api", "ory.no_avatar_identity.delete", "删除邮箱为 `orf-default-page-user-menu-no-avatar-e2e@orf.local` 的默认系统页用户菜单无自定义头像测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.noAvatarUser.email" }),
      step("Clean-10", "api", "avatar_user.preferences.default_landing_path.reset", "恢复邮箱为 `orf-default-page-user-menu-avatar-e2e@orf.local` 的默认进入页面为 系统默认", "user.preferences", "reset_default_landing_path_by_email", { emailFrom: "data.avatarUser.email" }),
      step("Clean-11", "api", "no_avatar_user.preferences.default_landing_path.reset", "恢复邮箱为 `orf-default-page-user-menu-no-avatar-e2e@orf.local` 的默认进入页面为 系统默认", "user.preferences", "reset_default_landing_path_by_email", { emailFrom: "data.noAvatarUser.email" }),
      step("Clean-12", "prisma", "db.avatar_user.memberships.delete", "删除邮箱为 `orf-default-page-user-menu-avatar-e2e@orf.local` 的默认系统页用户菜单自定义头像测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.avatarUser.email" }),
      step("Clean-13", "prisma", "db.no_avatar_user.memberships.delete", "删除邮箱为 `orf-default-page-user-menu-no-avatar-e2e@orf.local` 的默认系统页用户菜单无自定义头像测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.noAvatarUser.email" }),
      step("Clean-14", "prisma", "db.avatar_user.delete", "删除邮箱为 `orf-default-page-user-menu-avatar-e2e@orf.local` 的默认系统页用户菜单自定义头像测试用户", "db.user", "delete", { emailFrom: "data.avatarUser.email" }),
      step("Clean-15", "prisma", "db.no_avatar_user.delete", "删除邮箱为 `orf-default-page-user-menu-no-avatar-e2e@orf.local` 的默认系统页用户菜单无自定义头像测试用户", "db.user", "delete", { emailFrom: "data.noAvatarUser.email" }),
      step("Clean-16", "api", "ory.avatar_identity.absent", "邮箱为 `orf-default-page-user-menu-avatar-e2e@orf.local` 的默认系统页用户菜单自定义头像测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.avatarUser.email" }),
      step("Clean-17", "api", "ory.no_avatar_identity.absent", "邮箱为 `orf-default-page-user-menu-no-avatar-e2e@orf.local` 的默认系统页用户菜单无自定义头像测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.noAvatarUser.email" }),
      step("Clean-18", "prisma", "db.avatar_user.absent", "邮箱为 `orf-default-page-user-menu-avatar-e2e@orf.local` 的默认系统页用户菜单自定义头像测试用户 应不存在", "db.user", "absent", { emailFrom: "data.avatarUser.email" }),
      step("Clean-19", "prisma", "db.no_avatar_user.absent", "邮箱为 `orf-default-page-user-menu-no-avatar-e2e@orf.local` 的默认系统页用户菜单无自定义头像测试用户 应不存在", "db.user", "absent", { emailFrom: "data.noAvatarUser.email" }),
    ],
  },
} satisfies StateCaseSpec<UserMenuActionsCaseData>;
