import { STATE_CASE_MODEL, type StateCaseSpec } from "../../_framework/types";
import type { ApplyChallengeCaseData } from "./_support/apply-challenge.context";

export const applyChallengeCase = {
  id: "bounties.apply-challenge",
  title: "普通成员可以在悬赏大厅申请挑战",
  model: STATE_CASE_MODEL,
  tags: ["bounties", "challenge-application", "member", "happy-path"],

  data: {
    email: "orf-member-apply-challenge-e2e@orf.local",
    password: "OrfMemberApplyChallengeE2E!2026",
    name: "ORF Member Apply Challenge E2E",
    role: "member",
    objectiveId: "obj-testd-apply-challenge",
    objectiveTitle: "E2E-APPLY-CHALLENGE: 成员申请挑战",
  },

  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      {
        source: { caseStepId: "B-1", method: "api" },
        id: "frontend.ready",
        title: "前端服务 应可用",
        object: "frontend.service",
        operator: "available",
      },
      {
        source: { caseStepId: "B-2", method: "api" },
        id: "backend.ready",
        title: "后端服务 应可用",
        object: "api.health",
        operator: "ok",
      },
      {
        source: { caseStepId: "B-3", method: "api" },
        id: "frontend.login_entry.accessible",
        title: "前端登录页入口 应可访问",
        object: "frontend.login_entry",
        operator: "accessible",
      },
      {
        source: { caseStepId: "B-4", method: "api" },
        id: "session.endpoint.accessible",
        title: "当前会话查询能力 应可用",
        object: "auth.session",
        operator: "accessible",
      },
      {
        source: { caseStepId: "B-5", method: "prisma" },
        id: "db.ready",
        title: "ORF 数据库 应可连接",
        object: "db",
        operator: "ready",
      },
      {
        source: { caseStepId: "B-6", method: "prisma" },
        id: "db.schema.current",
        title: "ORF 数据库 schema 应为 当前测试版本",
        object: "db.schema",
        operator: "current",
      },
      {
        source: { caseStepId: "B-7", method: "api" },
        id: "ory.admin_public.ready",
        title: "Ory/Kratos 认证服务的管理和公共访问能力 应可用",
        object: "ory.admin_public",
        operator: "ready",
      },
      {
        source: { caseStepId: "B-8", method: "api" },
        id: "session.unauthenticated",
        title: "当前会话 应为 未登录",
        object: "auth.session",
        operator: "unauthenticated",
      },
      {
        source: { caseStepId: "B-9", method: "playwright" },
        id: "cookie.absent",
        title: "当前浏览器 应不存在 Ory 登录会话 cookie",
        object: "browser.cookie",
        operator: "absent",
      },
      {
        source: { caseStepId: "B-10", method: "playwright" },
        id: "storage.empty",
        title: "当前浏览器 应不保留本地登录态",
        object: "browser.auth_storage",
        operator: "empty",
      },
    ],
  },

  Setup: {
    description: "准备普通成员账号和本用例独占可申请目标，登录普通成员并进入悬赏大厅",
    steps: [
      {
        source: { caseStepId: "Setup-1", method: "prisma" },
        id: "db.objective.delete_residue",
        title: "删除可能残留的本用例可申请目标及其派生数据",
        object: "db.objective",
        operator: "delete_by_title",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Setup-2", method: "api" },
        id: "ory.member_identity.upsert",
        title: "准备邮箱为 `orf-member-apply-challenge-e2e@orf.local`、使用固定测试密码的普通成员登录身份",
        object: "ory.identity",
        operator: "upsert_password",
        params: {
          emailFrom: "data.email",
          nameFrom: "data.name",
          passwordFrom: "data.password",
          saveAs: "memberIdentity",
        },
      },
      {
        source: { caseStepId: "Setup-3", method: "prisma" },
        id: "db.member.upsert",
        title: "准备邮箱为 `orf-member-apply-challenge-e2e@orf.local`、角色为 `member`、状态为 `active` 的普通成员用户和默认团队成员关系",
        object: "db.user",
        operator: "upsert",
        params: {
          emailFrom: "data.email",
          nameFrom: "data.name",
          roleFrom: "data.role",
          status: "active",
          identityIdFrom: "runtime.memberIdentity.id",
          saveAs: "memberUser",
        },
      },
      {
        source: { caseStepId: "Setup-4", method: "prisma" },
        id: "db.objective.upsert_available",
        title: "创建标题为 `E2E-APPLY-CHALLENGE: 成员申请挑战`、流转状态为 `open`、阶段为 `resultClaiming` 的本用例可申请目标",
        object: "db.objective",
        operator: "upsert",
        params: {
          idFrom: "data.objectiveId",
          titleFrom: "data.objectiveTitle",
          teamIdFrom: "runtime.memberUser.teamId",
          stage: "resultClaiming",
          flowStatus: "open",
          status: "Draft",
          saveAs: "fixtureObjective",
        },
      },
      {
        source: { caseStepId: "Setup-5", method: "api" },
        id: "ory.member_sessions.revoke",
        title: "撤销普通成员登录身份可能残留的登录会话",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Setup-6", method: "playwright" },
        id: "browser.clear",
        title: "移除当前浏览器中的残留登录态",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "Setup-7", method: "playwright" },
        id: "page.goto.auth",
        title: "打开 ORF 登录页",
        object: "page",
        operator: "goto",
        params: { path: "/auth" },
      },
      {
        source: { caseStepId: "Setup-8", method: "playwright" },
        id: "fill.email",
        title: "在邮箱输入框输入普通成员固定测试邮箱",
        object: "page",
        operator: "fill",
        params: { label: "Email", valueFrom: "data.email" },
      },
      {
        source: { caseStepId: "Setup-9", method: "playwright" },
        id: "fill.password",
        title: "在密码输入框输入普通成员固定测试密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.password" },
      },
      {
        source: { caseStepId: "Setup-10", method: "playwright" },
        id: "click.sign_in",
        title: "点击 \"Sign In\" 登录操作",
        object: "page",
        operator: "click",
        params: { role: "button", name: "Sign In" },
      },
      {
        source: { caseStepId: "Setup-11", method: "api" },
        id: "session.member.authenticated",
        title: "当前会话 应为 普通成员已登录会话",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      {
        source: { caseStepId: "Setup-12", method: "playwright" },
        id: "page.goto.bounties",
        title: "打开 悬赏大厅",
        object: "page",
        operator: "goto",
        params: { path: "/bounties" },
      },
      {
        source: { caseStepId: "Setup-13", method: "api" },
        id: "api.bounties.select_target",
        title: "选择悬赏大厅数据中的本用例可申请目标",
        object: "api.bounties",
        operator: "select_available_target",
        params: { titleFrom: "data.objectiveTitle", saveAs: "bountyTarget" },
      },
    ],
  },

  S0: {
    description: "普通成员已登录并位于悬赏大厅，本用例目标可申请且尚无当前成员的待处理申请",
    assertions: [
      {
        source: { caseStepId: "S0-1", method: "api" },
        id: "session.member.authenticated",
        title: "当前会话 应为 普通成员已登录会话",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      {
        source: { caseStepId: "S0-2", method: "playwright" },
        id: "url.bounties",
        title: "当前页面 应为 悬赏大厅",
        object: "page.url",
        operator: "match",
        params: { pattern: "/bounties$" },
      },
      {
        source: { caseStepId: "S0-3", method: "playwright" },
        id: "nav.visible",
        title: "主导航 应可见",
        object: "page",
        operator: "visible",
        params: { label: "主导航" },
      },
      {
        source: { caseStepId: "S0-4", method: "playwright" },
        id: "current_user.visible",
        title: "当前用户显示 应为 \"ORF Member Apply Challenge E2E\"",
        object: "page",
        operator: "visible",
        params: { label: "当前用户" },
      },
      {
        source: { caseStepId: "S0-5", method: "api" },
        id: "api.bounties.target_present",
        title: "悬赏大厅数据中的本用例可申请目标 对当前普通成员 应为 尚未申请",
        object: "api.bounties",
        operator: "target_present",
        params: { targetFrom: "runtime.bountyTarget" },
      },
      {
        source: { caseStepId: "S0-6", method: "playwright" },
        id: "bounty_row.visible",
        title: "悬赏大厅列表中本用例目标对应的行 应可见",
        object: "page.bounty_row",
        operator: "visible",
        params: { targetFrom: "runtime.bountyTarget" },
      },
      {
        source: { caseStepId: "S0-7", method: "playwright" },
        id: "bounty_row.apply_visible",
        title: "本用例目标行中的 \"申请挑战\" 操作 应可见",
        object: "page.bounty_row",
        operator: "apply_visible",
        params: { targetFrom: "runtime.bountyTarget" },
      },
      {
        source: { caseStepId: "S0-8", method: "playwright" },
        id: "bounty_row.apply_enabled",
        title: "本用例目标行中的 \"申请挑战\" 操作 应可点击",
        object: "page.bounty_row",
        operator: "apply_enabled",
        params: { targetFrom: "runtime.bountyTarget" },
      },
      {
        source: { caseStepId: "S0-9", method: "prisma" },
        id: "db.bounty_target.no_pending_application",
        title: "本用例目标 应不存在 申请人为 \"ORF Member Apply Challenge E2E\" 且状态为 `pending` 的挑战申请",
        object: "db.bounty_target",
        operator: "no_pending_application",
        params: { targetFrom: "runtime.bountyTarget", applicantFrom: "data.name" },
      },
    ],
  },

  Action: {
    description: "对本用例目标提交挑战申请",
    steps: [
      {
        source: { caseStepId: "Action-1", method: "playwright" },
        id: "bounty_row.apply",
        title: "点击 本用例目标行的 \"申请挑战\" 操作",
        object: "page.bounty_row",
        operator: "apply",
        params: { targetFrom: "runtime.bountyTarget" },
      },
      {
        source: { caseStepId: "Action-2", method: "playwright" },
        id: "challenge_dialog.visible",
        title: "确认弹窗 应显示 \"提交后等待指挥官确认\"",
        object: "page.challenge_application_dialog",
        operator: "visible",
      },
      {
        source: { caseStepId: "Action-3", method: "api" },
        id: "capture.application_response",
        title: "监听提交挑战申请请求响应",
        object: "api.challenge_application",
        operator: "capture_response",
        params: { targetFrom: "runtime.bountyTarget", saveAs: "applicationResponse" },
      },
      {
        source: { caseStepId: "Action-4", method: "playwright" },
        id: "challenge_dialog.confirm",
        title: "点击 确认弹窗中的 \"申请挑战\" 操作",
        object: "page.challenge_application_dialog",
        operator: "confirm",
      },
    ],
  },

  S1: {
    description: "挑战申请已提交，接口、数据库和页面都显示当前成员已申请",
    assertions: [
      {
        source: { caseStepId: "S1-1", method: "api" },
        id: "application_response.matches",
        title: "提交挑战申请结果 应为 本用例可申请目标的成功结果",
        object: "api.challenge_application",
        operator: "matches",
        params: { responseFrom: "runtime.applicationResponse", targetFrom: "runtime.bountyTarget" },
      },
      {
        source: { caseStepId: "S1-2", method: "prisma" },
        id: "db.bounty_target.pending_application",
        title: "本用例目标 应存在 当前普通成员的已创建 pending 挑战申请",
        object: "db.bounty_target",
        operator: "pending_application",
        params: { targetFrom: "runtime.bountyTarget", applicantFrom: "data.name" },
      },
      {
        source: { caseStepId: "S1-3", method: "prisma" },
        id: "db.bounty_target.flow_matches_application",
        title: "本用例目标提交申请后的流转状态 应为 申请中状态",
        object: "db.bounty_target",
        operator: "flow_matches_application",
        params: { targetFrom: "runtime.bountyTarget" },
      },
      {
        source: { caseStepId: "S1-4", method: "api" },
        id: "api.bounties.has_current_application",
        title: "悬赏大厅数据中的本用例目标 对当前普通成员 应为 已申请",
        object: "api.bounties",
        operator: "has_current_application",
        params: { targetFrom: "runtime.bountyTarget" },
      },
      {
        source: { caseStepId: "S1-5", method: "playwright" },
        id: "bounty_row.applied_disabled",
        title: "本用例目标的可申请操作 应不可再点击",
        object: "page.bounty_row",
        operator: "applied_disabled",
        params: { targetFrom: "runtime.bountyTarget" },
      },
    ],
  },

  Clean: {
    description: "删除本用例目标和普通成员账号并恢复未登录基准状态",
    steps: [
      {
        source: { caseStepId: "Clean-1", method: "prisma" },
        id: "db.objective.delete_by_title",
        title: "删除 本用例可申请目标及其派生数据",
        object: "db.objective",
        operator: "delete_by_title",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Clean-2", method: "api" },
        id: "auth.logout",
        title: "注销当前登录会话",
        object: "auth",
        operator: "logout",
      },
      {
        source: { caseStepId: "Clean-3", method: "playwright" },
        id: "page.runtime.stop",
        title: "离开当前 ORF 前端页面",
        object: "page.runtime",
        operator: "stop",
      },
      {
        source: { caseStepId: "Clean-4", method: "playwright" },
        id: "browser.clear",
        title: "移除当前浏览器中的残留登录态",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "Clean-5", method: "api" },
        id: "ory.member_sessions.revoke",
        title: "撤销普通成员登录身份的残留登录会话",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-6", method: "api" },
        id: "ory.member_identity.delete",
        title: "删除邮箱为 `orf-member-apply-challenge-e2e@orf.local` 的普通成员登录身份",
        object: "ory.identity",
        operator: "delete_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-7", method: "prisma" },
        id: "db.member.memberships.delete",
        title: "删除邮箱为 `orf-member-apply-challenge-e2e@orf.local` 的普通成员用户默认团队成员关系",
        object: "db.user",
        operator: "delete_memberships",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-8", method: "prisma" },
        id: "db.member.delete",
        title: "删除邮箱为 `orf-member-apply-challenge-e2e@orf.local` 的普通成员用户",
        object: "db.user",
        operator: "delete",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-9", method: "prisma" },
        id: "db.objective.absent",
        title: "标题为 `E2E-APPLY-CHALLENGE: 成员申请挑战` 的测试目标 应不存在",
        object: "db.objective",
        operator: "absent",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Clean-10", method: "prisma" },
        id: "db.member.absent",
        title: "邮箱为 `orf-member-apply-challenge-e2e@orf.local` 的普通成员用户 应不存在",
        object: "db.user",
        operator: "absent",
        params: { emailFrom: "data.email" },
      },
    ],
  },
} satisfies StateCaseSpec<ApplyChallengeCaseData>;
