import { STATE_CASE_MODEL, type StateCaseSpec, type StepExecutionMethod, type StepSpec } from "../../_framework/types";
import type { SystemPermissionsOverviewCaseData } from "./_support/permissions-overview.context";

function step(
  caseStepId: string,
  method: StepExecutionMethod,
  id: string,
  title: string,
  object: string,
  operator: string,
  params?: Record<string, unknown>,
): StepSpec {
  return {
    source: { caseStepId, method },
    id,
    title,
    object,
    operator,
    ...(params ? { params } : {}),
  };
}

export const systemPermissionsOverviewCase = {
  id: "system.permissions-overview.elements",
  title: "10-权限管理页面展示与权限列表",
  model: STATE_CASE_MODEL,
  tags: ["system", "permissions", "overview"],
  data: {
    admin: {
      email: "orf-system-permissions-overview-admin-e2e@orf.local",
      password: "OrfSystemPermissionsOverviewAdminE2E!2026",
      name: "ORF Permissions Overview Admin E2E",
      role: "admin",
    },
    defaultLandingPath: "/bounties",
    permissionsPath: "/system/permissions",
    permissions: {
      objectiveCreate: {
        permissionKey: "objective.create",
        category: "目标",
        label: "新建目标",
        location: "悬赏大厅、顶部栏和命令菜单进入挑战页创建入口",
      },
      commentManage: {
        permissionKey: "comment.manage",
        category: "评论",
        label: "管理所有评论",
        location: "评论组件",
      },
      chatRead: {
        permissionKey: "chat.read",
        category: "聊天",
        label: "查看聊天",
        location: "聊天中心",
      },
    },
  },
  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      step("B-1", "api", "frontend.ready", "前端服务 应可用", "frontend.service", "available"),
      step("B-2", "api", "backend.ready", "后端服务 应可用", "api.health", "ok"),
      step("B-3", "api", "frontend.login_entry.accessible", "前端登录页入口 应可访问", "frontend.login_entry", "accessible"),
      step("B-4", "api", "session.endpoint.accessible", "当前会话查询能力 应可用", "auth.session", "accessible"),
      step("B-5", "prisma", "db.ready", "ORF 数据库 应可连接", "db", "ready"),
      step("B-6", "prisma", "db.schema.current", "ORF 数据库 schema 应为 当前测试版本", "db.schema", "current"),
      step("B-7", "api", "ory.admin_public.ready", "Ory/Kratos 认证服务的管理和公共访问能力 应可用", "ory.admin_public", "ready"),
      step("B-8", "api", "session.unauthenticated", "当前会话 应为 未登录", "auth.session", "unauthenticated"),
      step("B-9", "playwright", "cookie.absent", "当前浏览器 应不存在 Ory 登录会话 cookie", "browser.cookie", "absent"),
      step("B-10", "playwright", "storage.empty", "当前浏览器 应不保留本地登录态", "browser.auth_storage", "empty"),
    ],
  },
  Setup: {
    description: "准备管理员测试用户，并以管理员身份进入权限管理页面",
    steps: [
      step("Setup-1", "api", "ory.admin_identity.upsert", "准备邮箱为 `orf-system-permissions-overview-admin-e2e@orf.local`、使用固定测试密码的权限管理页面管理员测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.admin.email", passwordFrom: "data.admin.password", nameFrom: "data.admin.name", saveAs: "adminIdentity" }),
      step("Setup-2", "prisma", "db.admin_user.upsert", "准备姓名为 \"ORF Permissions Overview Admin E2E\"、邮箱为 `orf-system-permissions-overview-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的权限管理页面管理员测试用户", "db.user", "upsert", { emailFrom: "data.admin.email", passwordFrom: "data.admin.password", nameFrom: "data.admin.name", roleFrom: "data.admin.role", status: "active", identityIdFrom: "runtime.adminIdentity.id", saveAs: "adminUser" }),
      step("Setup-3", "api", "admin.preferences.default_landing_path.set", "设置权限管理页面管理员测试用户默认进入页面为 首页（默认系统页）", "user.preferences", "set_default_landing_path_by_email", { emailFrom: "data.admin.email", pathFrom: "data.defaultLandingPath" }),
      step("Setup-4", "api", "ory.admin_sessions.revoke", "撤销邮箱为 `orf-system-permissions-overview-admin-e2e@orf.local` 的权限管理页面管理员测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.admin.email" }),
      step("Setup-5", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Setup-6", "playwright", "page.goto.auth", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Setup-7", "playwright", "fill.admin_email", "在邮箱输入框输入 `orf-system-permissions-overview-admin-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.admin.email" }),
      step("Setup-8", "playwright", "fill.admin_password", "在密码输入框输入权限管理页面管理员测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.admin.password" }),
      step("Setup-9", "playwright", "click.sign_in", "点击 \"Sign In\" 登录操作", "page.login_form", "submit", { saveAs: "adminLoginResponse" }),
      step("Setup-10", "api", "session.admin_authenticated", "当前会话 应为 邮箱为 `orf-system-permissions-overview-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
      step("Setup-11", "api", "permission_definitions.read", "读取系统权限定义列表", "api.permission_definitions", "read", { saveAs: "permissionDefinitions" }),
      step("Setup-12", "playwright", "page.goto.permissions", "打开 权限管理页面", "page", "goto", { pathFrom: "data.permissionsPath" }),
    ],
  },
  S0: {
    description: "管理员已登录并位于权限管理页面，系统权限定义列表包含关键权限",
    assertions: [
      step("S0-1", "api", "session.admin_authenticated", "当前会话 应为 邮箱为 `orf-system-permissions-overview-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
      step("S0-2", "playwright", "url.permissions", "当前页面 应为 权限管理页面", "page.url", "match", { pattern: "/system/permissions$" }),
      step("S0-3", "playwright", "permissions.title.visible", "权限管理页面标题 应可见", "page.permissions_title", "visible"),
      step("S0-4", "api", "permission_definitions.objective_create", "系统权限定义列表 应包含 `objective.create` 权限定义", "api.permission_definitions", "contains", { definitionsFrom: "runtime.permissionDefinitions", permissionFrom: "data.permissions.objectiveCreate" }),
      step("S0-5", "api", "permission_definitions.comment_manage", "系统权限定义列表 应包含 `comment.manage` 权限定义", "api.permission_definitions", "contains", { definitionsFrom: "runtime.permissionDefinitions", permissionFrom: "data.permissions.commentManage" }),
      step("S0-6", "api", "permission_definitions.chat_read", "系统权限定义列表 应包含 `chat.read` 权限定义", "api.permission_definitions", "contains", { definitionsFrom: "runtime.permissionDefinitions", permissionFrom: "data.permissions.chatRead" }),
    ],
  },
  Action: {
    description: "查看权限管理页面",
    steps: [
      step("Action-1", "playwright", "permissions.page.observe", "查看 权限管理页面", "page.permissions_page", "observe"),
    ],
  },
  S1: {
    description: "权限管理页面基础元素和权限列表字段完整展示",
    assertions: [
      step("S1-1", "playwright", "role_switch.visible", "权限管理页面的角色切换区域 应可见", "page.permissions_role_switch", "visible"),
      step("S1-2", "playwright", "role_switch.member", "权限管理页面的角色切换区域 应显示 \"成员\" 角色", "page.permissions_role_switch", "contains_role", { label: "成员" }),
      step("S1-3", "playwright", "role_switch.admin", "权限管理页面的角色切换区域 应显示 \"管理员\" 角色", "page.permissions_role_switch", "contains_role", { label: "管理员" }),
      step("S1-4", "playwright", "permission_list.visible", "权限管理页面的权限列表 应可见", "page.permissions_list", "visible"),
      step("S1-5", "playwright", "permission_list.header.category", "权限管理页面的权限列表表头 应显示 \"分组\"", "page.permissions_list_header", "contains", { text: "分组" }),
      step("S1-6", "playwright", "permission_list.header.key", "权限管理页面的权限列表表头 应显示 \"权限 key\"", "page.permissions_list_header", "contains", { text: "权限 key" }),
      step("S1-7", "playwright", "permission_list.header.label", "权限管理页面的权限列表表头 应显示 \"含义\"", "page.permissions_list_header", "contains", { text: "含义" }),
      step("S1-8", "playwright", "permission_list.header.location", "权限管理页面的权限列表表头 应显示 \"使用位置\"", "page.permissions_list_header", "contains", { text: "使用位置" }),
      step("S1-9", "playwright", "permission_list.header.allowed", "权限管理页面的权限列表表头 应显示 \"允许状态\"", "page.permissions_list_header", "contains_allowed_status"),
      step("S1-10", "playwright", "permission_row.objective_create.visible", "权限管理页面的权限列表 应显示 `objective.create` 权限行", "page.permission_row", "visible", { permissionFrom: "data.permissions.objectiveCreate" }),
      step("S1-11", "playwright", "permission_row.objective_create.category", "`objective.create` 权限行的分组 应显示 \"目标\"", "page.permission_row", "category", { permissionFrom: "data.permissions.objectiveCreate" }),
      step("S1-12", "playwright", "permission_row.objective_create.label", "`objective.create` 权限行的含义 应显示 \"新建目标\"", "page.permission_row", "label", { permissionFrom: "data.permissions.objectiveCreate" }),
      step("S1-13", "playwright", "permission_row.objective_create.location", "`objective.create` 权限行的使用位置 应显示 \"悬赏大厅、顶部栏和命令菜单进入挑战页创建入口\"", "page.permission_row", "location", { permissionFrom: "data.permissions.objectiveCreate" }),
      step("S1-14", "playwright", "permission_row.objective_create.allowed_state", "`objective.create` 权限行的允许状态 应可见", "page.permission_row", "allowed_state_visible", { permissionFrom: "data.permissions.objectiveCreate" }),
      step("S1-15", "playwright", "permission_row.comment_manage.visible", "权限管理页面的权限列表 应显示 `comment.manage` 权限行", "page.permission_row", "visible", { permissionFrom: "data.permissions.commentManage" }),
      step("S1-16", "playwright", "permission_row.comment_manage.category", "`comment.manage` 权限行的分组 应显示 \"评论\"", "page.permission_row", "category", { permissionFrom: "data.permissions.commentManage" }),
      step("S1-17", "playwright", "permission_row.comment_manage.label", "`comment.manage` 权限行的含义 应显示 \"管理所有评论\"", "page.permission_row", "label", { permissionFrom: "data.permissions.commentManage" }),
      step("S1-18", "playwright", "permission_row.comment_manage.location", "`comment.manage` 权限行的使用位置 应显示 \"评论组件\"", "page.permission_row", "location", { permissionFrom: "data.permissions.commentManage" }),
      step("S1-19", "playwright", "permission_row.comment_manage.allowed_state", "`comment.manage` 权限行的允许状态 应可见", "page.permission_row", "allowed_state_visible", { permissionFrom: "data.permissions.commentManage" }),
      step("S1-20", "playwright", "permission_row.chat_read.visible", "权限管理页面的权限列表 应显示 `chat.read` 权限行", "page.permission_row", "visible", { permissionFrom: "data.permissions.chatRead" }),
      step("S1-21", "playwright", "permission_row.chat_read.category", "`chat.read` 权限行的分组 应显示 \"聊天\"", "page.permission_row", "category", { permissionFrom: "data.permissions.chatRead" }),
      step("S1-22", "playwright", "permission_row.chat_read.label", "`chat.read` 权限行的含义 应显示 \"查看聊天\"", "page.permission_row", "label", { permissionFrom: "data.permissions.chatRead" }),
      step("S1-23", "playwright", "permission_row.chat_read.location", "`chat.read` 权限行的使用位置 应显示 \"聊天中心\"", "page.permission_row", "location", { permissionFrom: "data.permissions.chatRead" }),
      step("S1-24", "playwright", "permission_row.chat_read.allowed_state", "`chat.read` 权限行的允许状态 应可见", "page.permission_row", "allowed_state_visible", { permissionFrom: "data.permissions.chatRead" }),
      step("S1-25", "playwright", "permissions.save_button.visible", "权限管理页面的保存角色权限按钮 应可见", "page.permissions_save_button", "visible"),
      step("S1-26", "playwright", "permissions.save_button.disabled_without_change", "权限管理页面的保存角色权限按钮 在未修改权限时 应不可点击", "page.permissions_save_button", "disabled"),
      step("S1-27", "api", "session.admin_authenticated.after_observe", "当前会话 应仍为 邮箱为 `orf-system-permissions-overview-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
    ],
  },
  Clean: {
    description: "删除权限管理页面测试管理员并恢复未登录基准状态",
    steps: [
      step("Clean-1", "api", "auth.logout", "注销当前登录会话", "auth", "logout"),
      step("Clean-2", "playwright", "page.runtime.stop", "离开当前 ORF 前端页面", "page.runtime", "stop"),
      step("Clean-3", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Clean-4", "api", "ory.admin_sessions.revoke", "撤销邮箱为 `orf-system-permissions-overview-admin-e2e@orf.local` 的权限管理页面管理员测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-5", "api", "ory.admin_identity.delete", "删除邮箱为 `orf-system-permissions-overview-admin-e2e@orf.local` 的权限管理页面管理员测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-6", "api", "admin.preferences.default_landing_path.reset", "恢复邮箱为 `orf-system-permissions-overview-admin-e2e@orf.local` 的默认进入页面为 系统默认", "user.preferences", "reset_default_landing_path_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-7", "prisma", "db.admin_user.memberships.delete", "删除邮箱为 `orf-system-permissions-overview-admin-e2e@orf.local` 的权限管理页面管理员测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.admin.email" }),
      step("Clean-8", "prisma", "db.admin_user.delete", "删除邮箱为 `orf-system-permissions-overview-admin-e2e@orf.local` 的权限管理页面管理员测试用户", "db.user", "delete", { emailFrom: "data.admin.email" }),
      step("Clean-9", "api", "ory.admin_identity.absent", "邮箱为 `orf-system-permissions-overview-admin-e2e@orf.local` 的权限管理页面管理员测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.admin.email" }),
      step("Clean-10", "prisma", "db.admin_user.absent", "邮箱为 `orf-system-permissions-overview-admin-e2e@orf.local` 的权限管理页面管理员测试用户 应不存在", "db.user", "absent", { emailFrom: "data.admin.email" }),
    ],
  },
} satisfies StateCaseSpec<SystemPermissionsOverviewCaseData>;
