import { STATE_CASE_MODEL, type StateCaseSpec, type StepExecutionMethod, type StepSpec } from "../../_framework/types";
import type { PersonalSettingsOverviewCaseData } from "./_support/personal-settings-overview.context";

function step(
  caseStepId: string,
  method: StepExecutionMethod,
  id: string,
  title: string,
  object: string,
  operator: string,
  params?: Record<string, unknown>,
): StepSpec {
  return {
    source: { caseStepId, method },
    id,
    title,
    object,
    operator,
    ...(params ? { params } : {}),
  };
}

export const personalSettingsOverviewCase = {
  id: "defaults.personal-settings.overview",
  title: "13-个人设置页面展示与用户信息",
  model: STATE_CASE_MODEL,
  tags: ["defaults", "personal-settings", "profile", "settings"],
  data: {
    email: "orf-default-page-personal-settings-e2e@orf.local",
    password: "OrfDefaultPagePersonalSettingsE2E!2026",
    name: "ORF 默认页个人设置用户",
    role: "member",
    status: "active",
    roleLabel: "成员",
    defaultLandingPath: "/bounties",
    homePath: "/dashboard",
    settingsPathPattern: "/settings$",
  },
  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      step("B-1", "api", "frontend.ready", "前端服务 应可用", "frontend.service", "available"),
      step("B-2", "api", "backend.ready", "后端服务 应可用", "api.health", "ok"),
      step("B-3", "api", "frontend.login_entry.accessible", "前端登录页入口 应可访问", "frontend.login_entry", "accessible"),
      step("B-4", "api", "session.endpoint.accessible", "当前会话查询能力 应可用", "auth.session", "accessible"),
      step("B-5", "prisma", "db.ready", "ORF 数据库 应可连接", "db", "ready"),
      step("B-6", "prisma", "db.schema.current", "ORF 数据库 schema 应为 当前测试版本", "db.schema", "current"),
      step("B-7", "api", "ory.admin_public.ready", "Ory/Kratos 认证服务的管理和公共访问能力 应可用", "ory.admin_public", "ready"),
      step("B-8", "api", "session.unauthenticated", "当前会话 应为 未登录", "auth.session", "unauthenticated"),
      step("B-9", "playwright", "cookie.absent", "当前浏览器 应不存在 Ory 登录会话 cookie", "browser.cookie", "absent"),
      step("B-10", "playwright", "storage.empty", "当前浏览器 应不保留本地登录态", "browser.auth_storage", "empty"),
    ],
  },
  Setup: {
    description: "准备带自定义头像的个人设置页面测试用户，并登录首页",
    steps: [
      step("Setup-1", "api", "ory.identity.upsert", "准备邮箱为 `orf-default-page-personal-settings-e2e@orf.local`、使用固定测试密码的个人设置页面测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.email", passwordFrom: "data.password", nameFrom: "data.name", saveAs: "identity" }),
      step("Setup-2", "prisma", "db.user.upsert", "准备邮箱为 `orf-default-page-personal-settings-e2e@orf.local`、姓名为 `ORF 默认页个人设置用户`、角色为 `member`、状态为 `active` 的个人设置页面测试用户", "db.user", "upsert", { emailFrom: "data.email", passwordFrom: "data.password", nameFrom: "data.name", roleFrom: "data.role", statusFrom: "data.status", identityIdFrom: "runtime.identity.id", saveAs: "user" }),
      step("Setup-3", "api", "user.avatar.upload", "为个人设置页面测试用户上传自定义头像", "user.avatar", "upload_by_email", { emailFrom: "data.email" }),
      step("Setup-4", "api", "preferences.default_landing_path.set", "设置个人设置页面测试用户默认进入页面为 首页（默认系统页）", "user.preferences", "set_default_landing_path_by_email", { emailFrom: "data.email", pathFrom: "data.defaultLandingPath" }),
      step("Setup-5", "api", "ory.sessions.revoke", "撤销邮箱为 `orf-default-page-personal-settings-e2e@orf.local` 的个人设置页面测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.email" }),
      step("Setup-6", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Setup-7", "playwright", "page.goto.auth", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Setup-8", "playwright", "fill.email", "在邮箱输入框输入 `orf-default-page-personal-settings-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.email" }),
      step("Setup-9", "playwright", "fill.password", "在密码输入框输入个人设置页面测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.password" }),
      step("Setup-10", "playwright", "click.sign_in", "点击 \"Sign In\" 登录操作", "page.login_form", "submit", { saveAs: "loginResponse" }),
      step("Setup-11", "api", "session.authenticated", "当前会话 应为 邮箱为 `orf-default-page-personal-settings-e2e@orf.local`、角色为 `member`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.email", roleFrom: "data.role", statusFrom: "data.status" }),
      step("Setup-12", "playwright", "page.goto.home", "打开 首页（默认系统页）", "page", "goto", { pathFrom: "data.homePath" }),
    ],
  },
  S0: {
    description: "个人设置页面测试用户已登录首页，侧边栏用户菜单尚未展开",
    assertions: [
      step("S0-1", "api", "session.authenticated", "当前会话 应为 邮箱为 `orf-default-page-personal-settings-e2e@orf.local`、角色为 `member`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.email", roleFrom: "data.role", statusFrom: "data.status" }),
      step("S0-2", "playwright", "url.home", "当前页面 应为 首页（默认系统页）", "page.url", "match", { pattern: "/dashboard$" }),
      step("S0-3", "playwright", "sidebar.current_user_avatar.visible", "侧边栏底部的当前用户头像 应可见", "sidebar.current_user_avatar", "visible"),
      step("S0-4", "playwright", "sidebar.current_user_name.text", "侧边栏底部的当前用户名 应显示 `ORF 默认页个人设置用户`", "sidebar.current_user_name", "text", { nameFrom: "data.name" }),
      step("S0-5", "playwright", "sidebar.user_menu.visible", "侧边栏底部的用户菜单入口 应可见", "sidebar.user_menu", "visible"),
      step("S0-6", "playwright", "sidebar.user_menu.enabled", "侧边栏底部的用户菜单入口 应可点击", "sidebar.user_menu", "enabled"),
      step("S0-7", "playwright", "user_menu.settings.hidden", "用户菜单中的 \"个人设置\" 操作 应不可见", "user_menu.item", "hidden", { name: "个人设置" }),
    ],
  },
  Action: {
    description: "从首页侧边栏用户菜单进入个人设置页面",
    steps: [
      step("Action-1", "playwright", "sidebar.user_menu.click", "点击 侧边栏底部的用户菜单入口", "sidebar.user_menu", "click"),
      step("Action-2", "playwright", "user_menu.settings.click", "点击 用户菜单中的 \"个人设置\" 操作", "page.user_menu_item", "click", { name: "个人设置" }),
    ],
  },
  S1: {
    description: "个人设置页面展示基础设置项和当前登录用户信息",
    assertions: [
      step("S1-1", "api", "session.authenticated.after_open", "当前会话 应仍为 邮箱为 `orf-default-page-personal-settings-e2e@orf.local`、角色为 `member`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.email", roleFrom: "data.role", statusFrom: "data.status" }),
      step("S1-2", "playwright", "personal_settings.page.visible", "当前页面 应为 个人设置页面", "personal_settings.page", "visible", { patternFrom: "data.settingsPathPattern" }),
      step("S1-3", "playwright", "personal_settings.title.text", "个人设置页面标题 应显示 `个人设置`", "personal_settings.title", "text", { value: "个人设置" }),
      step("S1-4", "playwright", "personal_settings.subtitle.text", "个人设置页面副标题 应显示 `管理当前登录用户的偏好。`", "personal_settings.subtitle", "text", { value: "管理当前登录用户的偏好。" }),
      step("S1-5", "playwright", "personal_settings.avatar.visible", "个人设置页面的当前用户头像 应可见", "personal_settings.current_user_avatar", "visible"),
      step("S1-6", "playwright", "personal_settings.name.text", "个人设置页面的当前用户名 应显示 `ORF 默认页个人设置用户`", "personal_settings.current_user_name", "text", { valueFrom: "data.name" }),
      step("S1-7", "playwright", "personal_settings.email.text", "个人设置页面的当前用户邮箱 应显示 `orf-default-page-personal-settings-e2e@orf.local`", "personal_settings.current_user_email", "text", { valueFrom: "data.email" }),
      step("S1-8", "playwright", "personal_settings.role.text", "个人设置页面的当前用户角色 应显示 `成员`", "personal_settings.current_user_role", "text", { valueFrom: "data.roleLabel" }),
      step("S1-9", "playwright", "personal_settings.status.text", "个人设置页面的当前用户状态 应显示 `active`", "personal_settings.current_user_status", "text", { valueFrom: "data.status" }),
      step("S1-10", "playwright", "personal_settings.upload_avatar.visible", "个人设置页面的上传头像操作 应可见", "personal_settings.upload_avatar", "visible"),
      step("S1-11", "playwright", "personal_settings.upload_avatar.enabled", "个人设置页面的上传头像操作 应可点击", "personal_settings.upload_avatar", "enabled"),
      step("S1-12", "playwright", "personal_settings.delete_avatar.visible", "个人设置页面的删除头像操作 应可见", "personal_settings.delete_avatar", "visible"),
      step("S1-13", "playwright", "personal_settings.delete_avatar.enabled", "个人设置页面的删除头像操作 应可点击", "personal_settings.delete_avatar", "enabled"),
      step("S1-14", "playwright", "personal_settings.default_landing.visible", "个人设置页面的默认进入页面设置项 应可见", "personal_settings.default_landing", "visible"),
      step("S1-15", "playwright", "personal_settings.default_landing.enabled", "个人设置页面的默认进入页面设置项 应可选择", "personal_settings.default_landing", "enabled"),
      step("S1-16", "playwright", "personal_settings.sidebar_state.visible", "个人设置页面的侧边栏默认状态设置项 应可见", "personal_settings.sidebar_state", "visible"),
      step("S1-17", "playwright", "personal_settings.sidebar_state.enabled", "个人设置页面的侧边栏默认状态设置项 应可选择", "personal_settings.sidebar_state", "enabled"),
      step("S1-18", "playwright", "personal_settings.toast.visible", "个人设置页面的 Toast 通知设置项 应可见", "personal_settings.toast", "visible"),
      step("S1-19", "playwright", "personal_settings.toast.enabled", "个人设置页面的 Toast 通知开关 应可点击", "personal_settings.toast", "enabled"),
      step("S1-20", "playwright", "personal_settings.skin_list.visible", "个人设置页面的皮肤列表 应可见", "personal_settings.skin_list", "visible"),
      step("S1-21", "playwright", "personal_settings.skin_list.contains_system", "个人设置页面的皮肤列表 应包含 系统皮肤", "personal_settings.skin_list", "contains_system_skin"),
      step("S1-22", "playwright", "personal_settings.upload_skin.visible", "个人设置页面的上传皮肤按钮 应可见", "personal_settings.upload_skin", "visible"),
      step("S1-23", "playwright", "personal_settings.upload_skin.enabled", "个人设置页面的上传皮肤按钮 应可点击", "personal_settings.upload_skin", "enabled"),
    ],
  },
  Clean: {
    description: "删除测试用户头像、账号和页面会话状态，恢复未登录基准状态",
    steps: [
      step("Clean-1", "api", "auth.logout", "注销当前登录会话", "auth", "logout"),
      step("Clean-2", "playwright", "page.runtime.stop", "离开当前 ORF 前端页面", "page.runtime", "stop"),
      step("Clean-3", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Clean-4", "api", "ory.sessions.revoke", "撤销邮箱为 `orf-default-page-personal-settings-e2e@orf.local` 的个人设置页面测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.email" }),
      step("Clean-5", "api", "user.avatar.delete", "删除个人设置页面测试用户的自定义头像文件", "user.avatar", "delete_by_email", { emailFrom: "data.email" }),
      step("Clean-6", "api", "ory.identity.delete", "删除邮箱为 `orf-default-page-personal-settings-e2e@orf.local` 的个人设置页面测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.email" }),
      step("Clean-7", "api", "preferences.default_landing_path.reset", "恢复邮箱为 `orf-default-page-personal-settings-e2e@orf.local` 的默认进入页面为 系统默认", "user.preferences", "reset_default_landing_path_by_email", { emailFrom: "data.email" }),
      step("Clean-8", "prisma", "db.user.memberships.delete", "删除邮箱为 `orf-default-page-personal-settings-e2e@orf.local` 的个人设置页面测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.email" }),
      step("Clean-9", "prisma", "db.user.delete", "删除邮箱为 `orf-default-page-personal-settings-e2e@orf.local` 的个人设置页面测试用户", "db.user", "delete", { emailFrom: "data.email" }),
      step("Clean-10", "api", "ory.identity.absent", "邮箱为 `orf-default-page-personal-settings-e2e@orf.local` 的个人设置页面测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.email" }),
      step("Clean-11", "prisma", "db.user.absent", "邮箱为 `orf-default-page-personal-settings-e2e@orf.local` 的个人设置页面测试用户 应不存在", "db.user", "absent", { emailFrom: "data.email" }),
    ],
  },
} satisfies StateCaseSpec<PersonalSettingsOverviewCaseData>;
