import { STATE_CASE_MODEL, type StateCaseSpec } from "../../_framework/types";
import type { ReviewApplicationForbiddenCaseData } from "./_support/review-application-forbidden.context";

export const reviewApplicationForbiddenCase = {
  id: "bounties.review-application.member-forbidden",
  title: "成员申请挑战审批-普通成员不可审批申请",
  model: STATE_CASE_MODEL,
  tags: ["bounties", "challenge-application", "review", "member", "permission", "negative-path"],

  data: {
    email: "orf-member-review-forbidden-e2e@orf.local",
    password: "OrfMemberReviewForbiddenE2E!2026",
    name: "ORF Member Review Forbidden E2E",
    role: "member",
    applicantEmail: "orf-member-review-forbidden-applicant-e2e@orf.local",
    applicantPassword: "OrfMemberReviewForbiddenApplicantE2E!2026",
    applicantName: "ORF Member Review Forbidden Applicant E2E",
    applicantRole: "member",
    objectiveId: "obj-testd-review-forbidden",
    objectiveTitle: "E2E-REVIEW-FORBIDDEN: 普通成员不可审批申请",
    applicationId: "challenge-application-testd-review-forbidden",
  },

  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      { source: { caseStepId: "B-1", method: "api" }, id: "frontend.ready", title: "前端服务 应可用", object: "frontend.service", operator: "available" },
      { source: { caseStepId: "B-2", method: "api" }, id: "backend.ready", title: "后端服务 应可用", object: "api.health", operator: "ok" },
      { source: { caseStepId: "B-3", method: "api" }, id: "frontend.login_entry.accessible", title: "前端登录页入口 应可访问", object: "frontend.login_entry", operator: "accessible" },
      { source: { caseStepId: "B-4", method: "api" }, id: "session.endpoint.accessible", title: "当前会话查询能力 应可用", object: "auth.session", operator: "accessible" },
      { source: { caseStepId: "B-5", method: "prisma" }, id: "db.ready", title: "ORF 数据库 应可连接", object: "db", operator: "ready" },
      { source: { caseStepId: "B-6", method: "prisma" }, id: "db.schema.current", title: "ORF 数据库 schema 应为 当前测试版本", object: "db.schema", operator: "current" },
      { source: { caseStepId: "B-7", method: "api" }, id: "ory.admin_public.ready", title: "Ory/Kratos 认证服务的管理和公共访问能力 应可用", object: "ory.admin_public", operator: "ready" },
      { source: { caseStepId: "B-8", method: "api" }, id: "session.unauthenticated", title: "当前会话 应为 未登录", object: "auth.session", operator: "unauthenticated" },
      { source: { caseStepId: "B-9", method: "playwright" }, id: "cookie.absent", title: "当前浏览器 应不存在 Ory 登录会话 cookie", object: "browser.cookie", operator: "absent" },
      { source: { caseStepId: "B-10", method: "playwright" }, id: "storage.empty", title: "当前浏览器 应不保留本地登录态", object: "browser.auth_storage", operator: "empty" },
    ],
  },

  Setup: {
    description: "准备两个普通成员、本用例独占审批目标和 pending 挑战申请，登录普通成员",
    steps: [
      { source: { caseStepId: "Setup-1", method: "prisma" }, id: "db.objective.delete_residue", title: "删除可能残留的本用例审批目标及其派生数据", object: "db.objective", operator: "delete_by_title", params: { titleFrom: "data.objectiveTitle" } },
      { source: { caseStepId: "Setup-2", method: "api" }, id: "ory.member_identity.upsert", title: "准备邮箱为 `orf-member-review-forbidden-e2e@orf.local`、使用固定测试密码的普通成员登录身份", object: "ory.identity", operator: "upsert_password", params: { emailFrom: "data.email", nameFrom: "data.name", passwordFrom: "data.password", saveAs: "memberIdentity" } },
      { source: { caseStepId: "Setup-3", method: "prisma" }, id: "db.member_user_record.upsert", title: "准备邮箱为 `orf-member-review-forbidden-e2e@orf.local`、状态为 `active` 的普通成员用户记录", object: "db.user_record", operator: "upsert", params: { emailFrom: "data.email", nameFrom: "data.name", status: "active", identityIdFrom: "runtime.memberIdentity.id", saveAs: "memberUserRecord" } },
      { source: { caseStepId: "Setup-4", method: "prisma" }, id: "db.member_membership.upsert", title: "准备邮箱为 `orf-member-review-forbidden-e2e@orf.local` 的普通成员用户默认团队成员关系，角色为 `member`", object: "db.default_team_membership", operator: "upsert", params: { emailFrom: "data.email", roleFrom: "data.role", saveAs: "memberUser" } },
      { source: { caseStepId: "Setup-5", method: "api" }, id: "ory.applicant_identity.upsert", title: "准备邮箱为 `orf-member-review-forbidden-applicant-e2e@orf.local`、使用固定测试密码的申请人普通成员登录身份", object: "ory.identity", operator: "upsert_password", params: { emailFrom: "data.applicantEmail", nameFrom: "data.applicantName", passwordFrom: "data.applicantPassword", saveAs: "applicantIdentity" } },
      { source: { caseStepId: "Setup-6", method: "prisma" }, id: "db.applicant_user_record.upsert", title: "准备邮箱为 `orf-member-review-forbidden-applicant-e2e@orf.local`、状态为 `active` 的申请人普通成员用户记录", object: "db.user_record", operator: "upsert", params: { emailFrom: "data.applicantEmail", nameFrom: "data.applicantName", status: "active", identityIdFrom: "runtime.applicantIdentity.id", saveAs: "applicantUserRecord" } },
      { source: { caseStepId: "Setup-7", method: "prisma" }, id: "db.applicant_membership.upsert", title: "准备邮箱为 `orf-member-review-forbidden-applicant-e2e@orf.local` 的申请人普通成员用户默认团队成员关系，角色为 `member`", object: "db.default_team_membership", operator: "upsert", params: { emailFrom: "data.applicantEmail", roleFrom: "data.applicantRole", saveAs: "applicantUser" } },
      { source: { caseStepId: "Setup-8", method: "prisma" }, id: "db.objective.upsert_review_target", title: "创建标题为 `E2E-REVIEW-FORBIDDEN: 普通成员不可审批申请`、流转状态为 `applying`、阶段为 `resultClaiming` 的本用例审批目标", object: "db.objective", operator: "upsert", params: { idFrom: "data.objectiveId", titleFrom: "data.objectiveTitle", teamIdFrom: "runtime.memberUser.teamId", stage: "resultClaiming", flowStatus: "applying", status: "Draft", createdByFrom: "runtime.memberUser.userId", updatedByFrom: "runtime.memberUser.userId", saveAs: "fixtureObjective" } },
      { source: { caseStepId: "Setup-9", method: "prisma" }, id: "db.challenge_application.create_pending", title: "创建 \"ORF Member Review Forbidden Applicant E2E\" 对本用例审批目标的 pending 挑战申请", object: "db.review_forbidden_target", operator: "create_pending_application", params: { objectiveIdFrom: "runtime.fixtureObjective.id", objectiveTitleFrom: "runtime.fixtureObjective.title", applicationIdFrom: "data.applicationId", applicantFrom: "data.applicantName", saveAs: "reviewTarget" } },
      { source: { caseStepId: "Setup-10", method: "prisma" }, id: "db.review_target.challenger_absent", title: "本用例审批目标的挑战者列表 应不包含 \"ORF Member Review Forbidden Applicant E2E\"", object: "db.review_forbidden_target", operator: "challenger_absent", params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.applicantName" } },
      { source: { caseStepId: "Setup-11", method: "api" }, id: "ory.member_sessions.revoke", title: "撤销普通成员登录身份可能残留的登录会话", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.email" } },
      { source: { caseStepId: "Setup-12", method: "api" }, id: "ory.applicant_sessions.revoke", title: "撤销申请人普通成员登录身份可能残留的登录会话", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.applicantEmail" } },
      { source: { caseStepId: "Setup-13", method: "playwright" }, id: "browser.clear", title: "移除当前浏览器中的残留登录态", object: "browser", operator: "clear_state" },
      { source: { caseStepId: "Setup-14", method: "playwright" }, id: "page.goto.auth", title: "打开 ORF 登录页", object: "page", operator: "goto", params: { path: "/auth" } },
      { source: { caseStepId: "Setup-15", method: "playwright" }, id: "fill.email", title: "在邮箱输入框输入普通成员固定测试邮箱", object: "page", operator: "fill", params: { label: "Email", valueFrom: "data.email" } },
      { source: { caseStepId: "Setup-16", method: "playwright" }, id: "fill.password", title: "在密码输入框输入普通成员固定测试密码", object: "page", operator: "fill", params: { label: "Password", exact: true, valueFrom: "data.password" } },
      { source: { caseStepId: "Setup-17", method: "playwright" }, id: "click.sign_in", title: "点击 \"Sign In\" 登录操作", object: "page", operator: "click", params: { role: "button", name: "Sign In" } },
      { source: { caseStepId: "Setup-18", method: "api" }, id: "session.authenticated", title: "当前会话 应为 已登录", object: "auth.session", operator: "authenticated" },
      { source: { caseStepId: "Setup-19", method: "api" }, id: "session.email", title: "当前会话用户邮箱 应为 `orf-member-review-forbidden-e2e@orf.local`", object: "auth.session.user_email", operator: "equals", params: { emailFrom: "data.email" } },
      { source: { caseStepId: "Setup-20", method: "api" }, id: "session.role", title: "当前会话用户角色 应为 `member`", object: "auth.session.user_role", operator: "equals", params: { roleFrom: "data.role" } },
      { source: { caseStepId: "Setup-21", method: "api" }, id: "session.status", title: "当前会话用户状态 应为 `active`", object: "auth.session.user_status", operator: "equals", params: { status: "active" } },
      { source: { caseStepId: "Setup-22", method: "playwright" }, id: "page.goto.tasks", title: "打开 挑战工作台", object: "page", operator: "goto", params: { path: "/tasks" } },
    ],
  },

  S0: {
    description: "普通成员已登录，审批目标保持 pending 申请且页面没有审批操作",
    assertions: [
      { source: { caseStepId: "S0-1", method: "api" }, id: "session.authenticated", title: "当前会话 应为 已登录", object: "auth.session", operator: "authenticated" },
      { source: { caseStepId: "S0-2", method: "api" }, id: "session.email", title: "当前会话用户邮箱 应为 `orf-member-review-forbidden-e2e@orf.local`", object: "auth.session.user_email", operator: "equals", params: { emailFrom: "data.email" } },
      { source: { caseStepId: "S0-3", method: "api" }, id: "session.role", title: "当前会话用户角色 应为 `member`", object: "auth.session.user_role", operator: "equals", params: { roleFrom: "data.role" } },
      { source: { caseStepId: "S0-4", method: "api" }, id: "session.status", title: "当前会话用户状态 应为 `active`", object: "auth.session.user_status", operator: "equals", params: { status: "active" } },
      { source: { caseStepId: "S0-5", method: "playwright" }, id: "url.tasks", title: "当前页面 应为 挑战工作台", object: "page.url", operator: "match", params: { pattern: "/tasks$" } },
      { source: { caseStepId: "S0-6", method: "playwright" }, id: "approve.action.absent", title: "\"通过\" 审批操作 应不可见", object: "page.review_approval_action", operator: "absent", params: { name: "通过" } },
      { source: { caseStepId: "S0-7", method: "playwright" }, id: "reject.action.absent", title: "\"拒绝\" 审批操作 应不可见", object: "page.review_approval_action", operator: "absent", params: { name: "拒绝" } },
      { source: { caseStepId: "S0-8", method: "prisma" }, id: "db.application.pending", title: "\"ORF Member Review Forbidden Applicant E2E\" 对本用例审批目标的挑战申请状态 应为 `pending`", object: "db.review_forbidden_target", operator: "application_status", params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.applicantName", status: "pending" } },
      { source: { caseStepId: "S0-9", method: "prisma" }, id: "db.challenger.absent", title: "本用例审批目标的挑战者列表 应不包含 \"ORF Member Review Forbidden Applicant E2E\"", object: "db.review_forbidden_target", operator: "challenger_absent", params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.applicantName" } },
      { source: { caseStepId: "S0-10", method: "prisma" }, id: "db.flow_status.applying", title: "本用例审批目标的流转状态 应为 `applying`", object: "db.review_forbidden_target", operator: "flow_status", params: { targetFrom: "runtime.reviewTarget", status: "applying" } },
      { source: { caseStepId: "S0-11", method: "prisma" }, id: "db.stage.result_claiming", title: "本用例审批目标的阶段 应为 `resultClaiming`", object: "db.review_forbidden_target", operator: "stage", params: { targetFrom: "runtime.reviewTarget", stage: "resultClaiming" } },
    ],
  },

  Action: {
    description: "普通成员直接调用审批通过接口",
    steps: [
      { source: { caseStepId: "Action-1", method: "api" }, id: "api.review_forbidden_approval.attempt", title: "当前普通成员尝试审批通过 \"ORF Member Review Forbidden Applicant E2E\" 对本用例审批目标的挑战申请", object: "api.review_forbidden_approval", operator: "attempt", params: { targetFrom: "runtime.reviewTarget", saveAs: "approvalAttemptResult" } },
      { source: { caseStepId: "Action-2", method: "prisma" }, id: "db.review_target.read_after", title: "读取 本用例审批目标", object: "db.review_forbidden_target", operator: "read", params: { targetFrom: "runtime.reviewTarget", saveAs: "targetAfterAttempt" } },
    ],
  },

  S1: {
    description: "审批被拒绝，申请和目标状态保持不变",
    assertions: [
      { source: { caseStepId: "S1-1", method: "api" }, id: "api.review_forbidden_approval.status", title: "审批通过结果状态码 应为 403 或等价权限错误", object: "api.review_forbidden_approval", operator: "forbidden", params: { resultFrom: "runtime.approvalAttemptResult" } },
      { source: { caseStepId: "S1-2", method: "prisma" }, id: "db.application.still_pending", title: "\"ORF Member Review Forbidden Applicant E2E\" 对本用例审批目标的挑战申请状态 应仍为 `pending`", object: "db.review_forbidden_target", operator: "application_status", params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.applicantName", status: "pending" } },
      { source: { caseStepId: "S1-3", method: "prisma" }, id: "db.challenger.still_absent", title: "本用例审批目标的挑战者列表 应仍不包含 \"ORF Member Review Forbidden Applicant E2E\"", object: "db.review_forbidden_target", operator: "challenger_absent", params: { targetFrom: "runtime.reviewTarget", applicantFrom: "data.applicantName" } },
      { source: { caseStepId: "S1-4", method: "prisma" }, id: "db.flow_status.still_applying", title: "本用例审批目标的流转状态 应仍为 `applying`", object: "db.review_forbidden_target", operator: "flow_status", params: { targetFrom: "runtime.reviewTarget", status: "applying" } },
      { source: { caseStepId: "S1-5", method: "prisma" }, id: "db.stage.still_result_claiming", title: "本用例审批目标的阶段 应仍为 `resultClaiming`", object: "db.review_forbidden_target", operator: "stage", params: { targetFrom: "runtime.reviewTarget", stage: "resultClaiming" } },
      { source: { caseStepId: "S1-6", method: "playwright" }, id: "url.tasks", title: "当前页面 应为 挑战工作台", object: "page.url", operator: "match", params: { pattern: "/tasks$" } },
      { source: { caseStepId: "S1-7", method: "playwright" }, id: "approve.action.absent", title: "\"通过\" 审批操作 应不可见", object: "page.review_approval_action", operator: "absent", params: { name: "通过" } },
      { source: { caseStepId: "S1-8", method: "playwright" }, id: "reject.action.absent", title: "\"拒绝\" 审批操作 应不可见", object: "page.review_approval_action", operator: "absent", params: { name: "拒绝" } },
      { source: { caseStepId: "S1-9", method: "api" }, id: "session.authenticated", title: "当前会话 应为 已登录", object: "auth.session", operator: "authenticated" },
      { source: { caseStepId: "S1-10", method: "api" }, id: "session.email", title: "当前会话用户邮箱 应为 `orf-member-review-forbidden-e2e@orf.local`", object: "auth.session.user_email", operator: "equals", params: { emailFrom: "data.email" } },
      { source: { caseStepId: "S1-11", method: "api" }, id: "session.role", title: "当前会话用户角色 应为 `member`", object: "auth.session.user_role", operator: "equals", params: { roleFrom: "data.role" } },
      { source: { caseStepId: "S1-12", method: "api" }, id: "session.status", title: "当前会话用户状态 应为 `active`", object: "auth.session.user_status", operator: "equals", params: { status: "active" } },
    ],
  },

  Clean: {
    description: "删除本用例目标、两个普通成员身份和浏览器状态",
    steps: [
      { source: { caseStepId: "Clean-1", method: "prisma" }, id: "db.objective.delete", title: "删除 本用例审批目标及其派生数据", object: "db.objective", operator: "delete", params: { idFrom: "data.objectiveId", titleFrom: "data.objectiveTitle" } },
      { source: { caseStepId: "Clean-2", method: "api" }, id: "auth.logout", title: "注销当前登录会话", object: "auth", operator: "logout" },
      { source: { caseStepId: "Clean-3", method: "playwright" }, id: "page.runtime.stop", title: "离开当前 ORF 前端页面", object: "page.runtime", operator: "stop" },
      { source: { caseStepId: "Clean-4", method: "playwright" }, id: "browser.clear", title: "移除当前浏览器中的残留登录态", object: "browser", operator: "clear_state" },
      { source: { caseStepId: "Clean-5", method: "api" }, id: "ory.member_sessions.revoke", title: "撤销普通成员登录身份的残留登录会话", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.email" } },
      { source: { caseStepId: "Clean-6", method: "api" }, id: "ory.applicant_sessions.revoke", title: "撤销申请人普通成员登录身份的残留登录会话", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.applicantEmail" } },
      { source: { caseStepId: "Clean-7", method: "api" }, id: "ory.member_identity.delete", title: "删除邮箱为 `orf-member-review-forbidden-e2e@orf.local` 的普通成员登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.email" } },
      { source: { caseStepId: "Clean-8", method: "api" }, id: "ory.applicant_identity.delete", title: "删除邮箱为 `orf-member-review-forbidden-applicant-e2e@orf.local` 的申请人普通成员登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.applicantEmail" } },
      { source: { caseStepId: "Clean-9", method: "prisma" }, id: "db.member_membership.delete", title: "删除邮箱为 `orf-member-review-forbidden-e2e@orf.local` 的普通成员用户默认团队成员关系", object: "db.user", operator: "delete_memberships", params: { emailFrom: "data.email" } },
      { source: { caseStepId: "Clean-10", method: "prisma" }, id: "db.applicant_membership.delete", title: "删除邮箱为 `orf-member-review-forbidden-applicant-e2e@orf.local` 的申请人普通成员用户默认团队成员关系", object: "db.user", operator: "delete_memberships", params: { emailFrom: "data.applicantEmail" } },
      { source: { caseStepId: "Clean-11", method: "prisma" }, id: "db.member_user.delete", title: "删除邮箱为 `orf-member-review-forbidden-e2e@orf.local` 的普通成员用户", object: "db.user", operator: "delete", params: { emailFrom: "data.email" } },
      { source: { caseStepId: "Clean-12", method: "prisma" }, id: "db.applicant_user.delete", title: "删除邮箱为 `orf-member-review-forbidden-applicant-e2e@orf.local` 的申请人普通成员用户", object: "db.user", operator: "delete", params: { emailFrom: "data.applicantEmail" } },
      { source: { caseStepId: "Clean-13", method: "prisma" }, id: "db.objective.absent", title: "应不存在 标题为 `E2E-REVIEW-FORBIDDEN: 普通成员不可审批申请` 的测试目标", object: "db.objective", operator: "absent", params: { idFrom: "data.objectiveId", titleFrom: "data.objectiveTitle" } },
      { source: { caseStepId: "Clean-14", method: "api" }, id: "ory.member_identity.absent", title: "邮箱为 `orf-member-review-forbidden-e2e@orf.local` 的普通成员登录身份 应不存在", object: "ory.identity", operator: "absent", params: { emailFrom: "data.email" } },
      { source: { caseStepId: "Clean-15", method: "api" }, id: "ory.applicant_identity.absent", title: "邮箱为 `orf-member-review-forbidden-applicant-e2e@orf.local` 的申请人普通成员登录身份 应不存在", object: "ory.identity", operator: "absent", params: { emailFrom: "data.applicantEmail" } },
      { source: { caseStepId: "Clean-16", method: "prisma" }, id: "db.member_user.absent", title: "邮箱为 `orf-member-review-forbidden-e2e@orf.local` 的普通成员用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.email" } },
      { source: { caseStepId: "Clean-17", method: "prisma" }, id: "db.applicant_user.absent", title: "邮箱为 `orf-member-review-forbidden-applicant-e2e@orf.local` 的申请人普通成员用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.applicantEmail" } },
    ],
  },
} satisfies StateCaseSpec<ReviewApplicationForbiddenCaseData>;
