export const designTokens = {
  color: {
    appBg: "#f3f6fa",
    pageBg: "#f8fafc",
    headerBg: "rgba(248, 250, 252, 0.86)",
    cardBg: "rgba(255, 255, 255, 0.92)",
    cardHoverBg: "#ffffff",
    rowHoverBg: "rgba(59, 130, 246, 0.07)",
    elevatedBg: "#ffffff",
    mutedBg: "#f1f5f9",
    mutedStrongBg: "#e8eef6",
    workflowBg: "#f4f8fb",
    workflowHeaderBg: "rgba(255, 255, 255, 0.76)",
    workflowBodyBg: "rgba(255, 255, 255, 0.84)",
    border: "rgba(15, 23, 42, 0.08)",
    borderStrong: "rgba(15, 23, 42, 0.14)",
    treeLine: "rgba(82, 116, 151, 0.34)",
    textPrimary: "#111827",
    textSecondary: "#526071",
    textMuted: "#7d8998",
    textFaint: "#a4afbd",
    accent: "#3b63f6",
    accentHover: "#2f4fd2",
    accentSoft: "rgba(59, 99, 246, 0.1)",
    accentBorder: "rgba(59, 99, 246, 0.2)",
    accentText: "#3155d4",
    successText: "#079275",
    successBg: "rgba(7, 146, 117, 0.1)",
    successBorder: "rgba(7, 146, 117, 0.2)",
    warningText: "#c96f08",
    warningBg: "rgba(217, 131, 11, 0.12)",
    warningBorder: "rgba(217, 131, 11, 0.22)",
    dangerText: "#dc3b32",
    dangerBg: "rgba(220, 59, 50, 0.1)",
    dangerBorder: "rgba(220, 59, 50, 0.2)",
    infoText: "#147f94",
    infoBg: "rgba(20, 127, 148, 0.1)",
    infoBorder: "rgba(20, 127, 148, 0.2)",
    neutralText: "#667085",
    neutralBg: "rgba(102, 112, 133, 0.1)",
    neutralBorder: "rgba(102, 112, 133, 0.16)",
    sidebarBg: "#020814",
    sidebarHeaderBg: "rgba(2, 10, 24, 0.26)",
    sidebarWorkspaceBg: "rgba(7, 24, 52, 0.22)",
    sidebarSelectedBg: "rgba(14, 165, 233, 0.18)",
    sidebarHoverBg: "rgba(125, 211, 252, 0.18)",
    sidebarControlBg: "rgba(2, 12, 28, 0.56)",
    sidebarControlHoverBg: "rgba(14, 74, 124, 0.66)",
    sidebarDivider: "rgba(125, 211, 252, 0.1)",
    sidebarIcon: "#83e9ff",
    sidebarText: "#f3fbff",
    sidebarTextMuted: "#9dc9df",
    sidebarLinkText: "#d9f2ff",
    sidebarCommandText: "#d4efff",
    sidebarLogoBg: "#15191b",
    sidebarWorkspaceLogoBg: "#eef7f7",
    sidebarWorkspaceLogoText: "#09a36f",
    avatarBorder: "#ff745d",
    avatarBg: "#f2f2f2",
    avatarText: "#255f5d",
  },
  radius: {
    card: "8px",
    control: "6px",
    statusTag: "999px",
  },
  space: {
    cardPadding: "16px",
    pagePaddingX: "28px",
    pagePaddingY: "24px",
  },
  size: {
    rowHeight: "48px",
    treeIndent: "28px",
    topbarHeight: "76px",
    sidebarWidth: "280px",
    sidebarCollapsedWidth: "88px",
    sidebarHeaderHeight: "108px",
  },
  border: {
    width: "1px",
  },
  shadow: {
    card: "0 18px 44px rgba(15, 23, 42, 0.08), 0 1px 1px rgba(15, 23, 42, 0.04)",
  },
  palette: {
    avatar: ["#54b7aa", "#a56be2", "#f4a261", "#45a8bf", "#eb6f92", "#6d7bdd"],
    resultMarker: ["#3f987e", "#f04a3a"],
    dashboardRing: "#3452de",
    ringWarning: "#f7b928",
  },
} as const;

export const designCssVariables = {
  "--orf-bg-app": designTokens.color.appBg,
  "--orf-bg-page": designTokens.color.pageBg,
  "--orf-bg-header": designTokens.color.headerBg,
  "--orf-bg-card": designTokens.color.cardBg,
  "--orf-bg-card-hover": designTokens.color.cardHoverBg,
  "--orf-bg-row-hover": designTokens.color.rowHoverBg,
  "--orf-bg-elevated": designTokens.color.elevatedBg,
  "--orf-bg-muted": designTokens.color.mutedBg,
  "--orf-bg-muted-strong": designTokens.color.mutedStrongBg,
  "--orf-bg-workflow": designTokens.color.workflowBg,
  "--orf-bg-workflow-header": designTokens.color.workflowHeaderBg,
  "--orf-bg-workflow-body": designTokens.color.workflowBodyBg,
  "--orf-border": designTokens.color.border,
  "--orf-border-strong": designTokens.color.borderStrong,
  "--orf-tree-line": designTokens.color.treeLine,
  "--orf-text-primary": designTokens.color.textPrimary,
  "--orf-text-secondary": designTokens.color.textSecondary,
  "--orf-text-muted": designTokens.color.textMuted,
  "--orf-text-faint": designTokens.color.textFaint,
  "--orf-accent": designTokens.color.accent,
  "--orf-accent-hover": designTokens.color.accentHover,
  "--orf-accent-soft": designTokens.color.accentSoft,
  "--orf-accent-border": designTokens.color.accentBorder,
  "--orf-accent-text": designTokens.color.accentText,
  "--orf-success-text": designTokens.color.successText,
  "--orf-success-bg": designTokens.color.successBg,
  "--orf-success-border": designTokens.color.successBorder,
  "--orf-warning-text": designTokens.color.warningText,
  "--orf-warning-bg": designTokens.color.warningBg,
  "--orf-warning-border": designTokens.color.warningBorder,
  "--orf-danger-text": designTokens.color.dangerText,
  "--orf-danger-bg": designTokens.color.dangerBg,
  "--orf-danger-border": designTokens.color.dangerBorder,
  "--orf-info-text": designTokens.color.infoText,
  "--orf-info-bg": designTokens.color.infoBg,
  "--orf-info-border": designTokens.color.infoBorder,
  "--orf-neutral-text": designTokens.color.neutralText,
  "--orf-neutral-bg": designTokens.color.neutralBg,
  "--orf-neutral-border": designTokens.color.neutralBorder,
  "--orf-bg-sidebar": designTokens.color.sidebarBg,
  "--orf-sidebar-header-bg": designTokens.color.sidebarHeaderBg,
  "--orf-sidebar-workspace-bg": designTokens.color.sidebarWorkspaceBg,
  "--orf-sidebar-selected-bg": designTokens.color.sidebarSelectedBg,
  "--orf-sidebar-hover-bg": designTokens.color.sidebarHoverBg,
  "--orf-sidebar-control-bg": designTokens.color.sidebarControlBg,
  "--orf-sidebar-control-hover-bg": designTokens.color.sidebarControlHoverBg,
  "--orf-sidebar-divider": designTokens.color.sidebarDivider,
  "--orf-sidebar-icon": designTokens.color.sidebarIcon,
  "--orf-sidebar-text": designTokens.color.sidebarText,
  "--orf-sidebar-text-muted": designTokens.color.sidebarTextMuted,
  "--orf-sidebar-link-text": designTokens.color.sidebarLinkText,
  "--orf-sidebar-command-text": designTokens.color.sidebarCommandText,
  "--orf-sidebar-logo-bg": designTokens.color.sidebarLogoBg,
  "--orf-sidebar-workspace-logo-bg": designTokens.color.sidebarWorkspaceLogoBg,
  "--orf-sidebar-workspace-logo-text": designTokens.color.sidebarWorkspaceLogoText,
  "--orf-avatar-border": designTokens.color.avatarBorder,
  "--orf-avatar-bg": designTokens.color.avatarBg,
  "--orf-avatar-text": designTokens.color.avatarText,
  "--orf-radius-card": designTokens.radius.card,
  "--orf-radius-control": designTokens.radius.control,
  "--orf-radius-status-tag": designTokens.radius.statusTag,
  "--orf-card-padding": designTokens.space.cardPadding,
  "--orf-page-padding-x": designTokens.space.pagePaddingX,
  "--orf-page-padding-y": designTokens.space.pagePaddingY,
  "--orf-row-height": designTokens.size.rowHeight,
  "--orf-tree-indent": designTokens.size.treeIndent,
  "--orf-topbar-height": designTokens.size.topbarHeight,
  "--orf-sidebar-width": designTokens.size.sidebarWidth,
  "--orf-sidebar-collapsed-width": designTokens.size.sidebarCollapsedWidth,
  "--orf-sidebar-header-height": designTokens.size.sidebarHeaderHeight,
  "--orf-border-width": designTokens.border.width,
  "--orf-shadow-card": designTokens.shadow.card,
  "--orf-page-glow": "linear-gradient(180deg, #f8fafc 0%, #eef4f8 48%, #f5f7fb 100%)",
} as const;

export function applyDesignTokens(root: HTMLElement = document.documentElement) {
  for (const [name, value] of Object.entries(designCssVariables)) {
    root.style.setProperty(name, value);
  }
}
