export const designTokens = {
  color: {
    appBg: "#f7f7f5",
    pageBg: "#fafafa",
    headerBg: "#fbfbfa",
    cardBg: "#fbfbfa",
    cardHoverBg: "#f6f6f4",
    elevatedBg: "#fcfcfb",
    mutedBg: "#f3f3f1",
    mutedStrongBg: "#ececea",
    workflowBg: "#f7f7f5",
    workflowHeaderBg: "#f0f0ee",
    workflowBodyBg: "#fafafa",
    border: "#d6d6d3",
    borderStrong: "#c8c8c4",
    treeLine: "#d0d5dd",
    textPrimary: "#171717",
    textSecondary: "#666666",
    textMuted: "#858585",
    textFaint: "#a7a7a7",
    accent: "#3755d8",
    accentHover: "#2f48bd",
    accentSoft: "rgba(55, 85, 216, 0.11)",
    accentBorder: "rgba(55, 85, 216, 0.26)",
    accentText: "#3652d4",
    successText: "#3f947c",
    successBg: "rgba(63, 148, 124, 0.1)",
    successBorder: "rgba(63, 148, 124, 0.22)",
    warningText: "#a87b10",
    warningBg: "rgba(247, 184, 38, 0.14)",
    warningBorder: "rgba(247, 184, 38, 0.28)",
    dangerText: "#ee493b",
    dangerBg: "rgba(238, 73, 59, 0.1)",
    dangerBorder: "rgba(238, 73, 59, 0.24)",
    infoText: "#397982",
    infoBg: "rgba(123, 205, 218, 0.14)",
    infoBorder: "rgba(123, 205, 218, 0.28)",
    neutralText: "#777777",
    neutralBg: "rgba(120, 120, 120, 0.1)",
    neutralBorder: "rgba(120, 120, 120, 0.18)",
    sidebarBg: "#075856",
    sidebarHeaderBg: "#064f4f",
    sidebarWorkspaceBg: "#2a6f6d",
    sidebarSelectedBg: "#064b4b",
    sidebarHoverBg: "#0a6664",
    sidebarControlBg: "#0a5150",
    sidebarControlHoverBg: "#0d6664",
    sidebarDivider: "rgba(0, 0, 0, 0.18)",
    sidebarIcon: "#74d2d6",
    sidebarText: "#f4fbfb",
    sidebarTextMuted: "#b7d8d8",
    sidebarLinkText: "#e4f3f3",
    sidebarCommandText: "#d7eeee",
    sidebarLogoBg: "#15191b",
    sidebarWorkspaceLogoBg: "#eef7f7",
    sidebarWorkspaceLogoText: "#09a36f",
    avatarBorder: "#ff745d",
    avatarBg: "#f2f2f2",
    avatarText: "#255f5d",
  },
  radius: {
    card: "8px",
    control: "6px",
    statusTag: "999px",
  },
  space: {
    cardPadding: "16px",
    pagePaddingX: "28px",
    pagePaddingY: "24px",
  },
  size: {
    rowHeight: "48px",
    treeIndent: "28px",
    topbarHeight: "76px",
    sidebarWidth: "280px",
    sidebarHeaderHeight: "108px",
  },
  border: {
    width: "1px",
  },
  shadow: {
    card: "none",
  },
  palette: {
    avatar: ["#54b7aa", "#a56be2", "#f4a261", "#45a8bf", "#eb6f92", "#6d7bdd"],
    resultMarker: ["#3f987e", "#f04a3a"],
    dashboardRing: "#3452de",
    ringWarning: "#f7b928",
  },
} as const;

export const designCssVariables = {
  "--orf-bg-app": designTokens.color.appBg,
  "--orf-bg-page": designTokens.color.pageBg,
  "--orf-bg-header": designTokens.color.headerBg,
  "--orf-bg-card": designTokens.color.cardBg,
  "--orf-bg-card-hover": designTokens.color.cardHoverBg,
  "--orf-bg-elevated": designTokens.color.elevatedBg,
  "--orf-bg-muted": designTokens.color.mutedBg,
  "--orf-bg-muted-strong": designTokens.color.mutedStrongBg,
  "--orf-bg-workflow": designTokens.color.workflowBg,
  "--orf-bg-workflow-header": designTokens.color.workflowHeaderBg,
  "--orf-bg-workflow-body": designTokens.color.workflowBodyBg,
  "--orf-border": designTokens.color.border,
  "--orf-border-strong": designTokens.color.borderStrong,
  "--orf-tree-line": designTokens.color.treeLine,
  "--orf-text-primary": designTokens.color.textPrimary,
  "--orf-text-secondary": designTokens.color.textSecondary,
  "--orf-text-muted": designTokens.color.textMuted,
  "--orf-text-faint": designTokens.color.textFaint,
  "--orf-accent": designTokens.color.accent,
  "--orf-accent-hover": designTokens.color.accentHover,
  "--orf-accent-soft": designTokens.color.accentSoft,
  "--orf-accent-border": designTokens.color.accentBorder,
  "--orf-accent-text": designTokens.color.accentText,
  "--orf-success-text": designTokens.color.successText,
  "--orf-success-bg": designTokens.color.successBg,
  "--orf-success-border": designTokens.color.successBorder,
  "--orf-warning-text": designTokens.color.warningText,
  "--orf-warning-bg": designTokens.color.warningBg,
  "--orf-warning-border": designTokens.color.warningBorder,
  "--orf-danger-text": designTokens.color.dangerText,
  "--orf-danger-bg": designTokens.color.dangerBg,
  "--orf-danger-border": designTokens.color.dangerBorder,
  "--orf-info-text": designTokens.color.infoText,
  "--orf-info-bg": designTokens.color.infoBg,
  "--orf-info-border": designTokens.color.infoBorder,
  "--orf-neutral-text": designTokens.color.neutralText,
  "--orf-neutral-bg": designTokens.color.neutralBg,
  "--orf-neutral-border": designTokens.color.neutralBorder,
  "--orf-bg-sidebar": designTokens.color.sidebarBg,
  "--orf-sidebar-header-bg": designTokens.color.sidebarHeaderBg,
  "--orf-sidebar-workspace-bg": designTokens.color.sidebarWorkspaceBg,
  "--orf-sidebar-selected-bg": designTokens.color.sidebarSelectedBg,
  "--orf-sidebar-hover-bg": designTokens.color.sidebarHoverBg,
  "--orf-sidebar-control-bg": designTokens.color.sidebarControlBg,
  "--orf-sidebar-control-hover-bg": designTokens.color.sidebarControlHoverBg,
  "--orf-sidebar-divider": designTokens.color.sidebarDivider,
  "--orf-sidebar-icon": designTokens.color.sidebarIcon,
  "--orf-sidebar-text": designTokens.color.sidebarText,
  "--orf-sidebar-text-muted": designTokens.color.sidebarTextMuted,
  "--orf-sidebar-link-text": designTokens.color.sidebarLinkText,
  "--orf-sidebar-command-text": designTokens.color.sidebarCommandText,
  "--orf-sidebar-logo-bg": designTokens.color.sidebarLogoBg,
  "--orf-sidebar-workspace-logo-bg": designTokens.color.sidebarWorkspaceLogoBg,
  "--orf-sidebar-workspace-logo-text": designTokens.color.sidebarWorkspaceLogoText,
  "--orf-avatar-border": designTokens.color.avatarBorder,
  "--orf-avatar-bg": designTokens.color.avatarBg,
  "--orf-avatar-text": designTokens.color.avatarText,
  "--orf-radius-card": designTokens.radius.card,
  "--orf-radius-control": designTokens.radius.control,
  "--orf-radius-status-tag": designTokens.radius.statusTag,
  "--orf-card-padding": designTokens.space.cardPadding,
  "--orf-page-padding-x": designTokens.space.pagePaddingX,
  "--orf-page-padding-y": designTokens.space.pagePaddingY,
  "--orf-row-height": designTokens.size.rowHeight,
  "--orf-tree-indent": designTokens.size.treeIndent,
  "--orf-topbar-height": designTokens.size.topbarHeight,
  "--orf-sidebar-width": designTokens.size.sidebarWidth,
  "--orf-sidebar-header-height": designTokens.size.sidebarHeaderHeight,
  "--orf-border-width": designTokens.border.width,
  "--orf-shadow-card": designTokens.shadow.card,
  "--orf-page-glow": designTokens.color.appBg,
} as const;

export function applyDesignTokens(root: HTMLElement = document.documentElement) {
  for (const [name, value] of Object.entries(designCssVariables)) {
    root.style.setProperty(name, value);
  }
}
