export const designTokens = {
  color: {
    appBg: "#f4eadb",
    pageBg: "#fff8ea",
    headerBg: "rgba(37, 48, 65, 0.86)",
    cardBg: "rgba(255, 249, 235, 0.9)",
    cardHoverBg: "#ffffff",
    rowHoverBg: "rgba(56, 189, 248, 0.1)",
    elevatedBg: "#ffffff",
    mutedBg: "#fff0d5",
    mutedStrongBg: "#e9d6b7",
    workflowBg: "#fff1d3",
    workflowHeaderBg: "rgba(255, 249, 235, 0.82)",
    workflowBodyBg: "rgba(255, 253, 244, 0.9)",
    border: "rgba(142, 111, 62, 0.14)",
    borderStrong: "rgba(142, 111, 62, 0.26)",
    treeLine: "rgba(56, 137, 168, 0.42)",
    textPrimary: "#172033",
    textSecondary: "#536179",
    textMuted: "#7f8aa3",
    textFaint: "#a7b0c2",
    accent: "#39bde6",
    accentHover: "#1d8fc3",
    accentSoft: "rgba(57, 189, 230, 0.14)",
    accentBorder: "rgba(57, 189, 230, 0.28)",
    accentText: "#1577a6",
    successText: "#139c87",
    successBg: "rgba(19, 156, 135, 0.12)",
    successBorder: "rgba(19, 156, 135, 0.22)",
    warningText: "#b97913",
    warningBg: "rgba(218, 166, 74, 0.18)",
    warningBorder: "rgba(218, 166, 74, 0.32)",
    dangerText: "#dc3b32",
    dangerBg: "rgba(220, 59, 50, 0.1)",
    dangerBorder: "rgba(220, 59, 50, 0.2)",
    infoText: "#2876d8",
    infoBg: "rgba(40, 118, 216, 0.12)",
    infoBorder: "rgba(40, 118, 216, 0.22)",
    neutralText: "#667085",
    neutralBg: "rgba(102, 112, 133, 0.1)",
    neutralBorder: "rgba(102, 112, 133, 0.16)",
    sidebarBg: "#171d28",
    sidebarHeaderBg: "rgba(30, 23, 38, 0.2)",
    sidebarWorkspaceBg: "rgba(30, 23, 38, 0.12)",
    sidebarSelectedBg: "rgba(45, 190, 235, 0.22)",
    sidebarHoverBg: "rgba(45, 190, 235, 0.26)",
    sidebarControlBg: "rgba(45, 190, 235, 0.16)",
    sidebarControlHoverBg: "rgba(45, 190, 235, 0.28)",
    sidebarDivider: "rgba(125, 211, 252, 0.1)",
    sidebarIcon: "#ffffff",
    sidebarText: "#f3fbff",
    sidebarTextMuted: "#9dc9df",
    sidebarLinkText: "#ffffff",
    sidebarCommandText: "#ffffff",
    sidebarLogoBg: "#15191b",
    sidebarWorkspaceLogoBg: "#eef7f7",
    sidebarWorkspaceLogoText: "#09a36f",
    avatarBorder: "#ff745d",
    avatarBg: "#f2f2f2",
    avatarText: "#255f5d",
  },
  radius: {
    card: "8px",
    control: "6px",
    statusTag: "999px",
  },
  space: {
    cardPadding: "16px",
    pagePaddingX: "28px",
    pagePaddingY: "24px",
  },
  size: {
    rowHeight: "48px",
    treeIndent: "28px",
    topbarHeight: "76px",
    sidebarWidth: "280px",
    sidebarCollapsedWidth: "88px",
    sidebarHeaderHeight: "108px",
  },
  border: {
    width: "1px",
  },
  shadow: {
    card: "0 18px 42px rgba(49, 44, 36, 0.1), 0 1px 1px rgba(255, 255, 255, 0.62)",
  },
  palette: {
    avatar: ["#39b8c8", "#a77be8", "#f5a85b", "#60a5fa", "#f06f9a", "#67c78f"],
    resultMarker: ["#28b7a5", "#f59e0b"],
    dashboardRing: "#38a7ff",
    ringWarning: "#f5b642",
  },
} as const;

export const designCssVariables = {
  "--orf-bg-app": designTokens.color.appBg,
  "--orf-bg-page": designTokens.color.pageBg,
  "--orf-bg-header": designTokens.color.headerBg,
  "--orf-bg-card": designTokens.color.cardBg,
  "--orf-bg-card-hover": designTokens.color.cardHoverBg,
  "--orf-bg-row-hover": designTokens.color.rowHoverBg,
  "--orf-bg-elevated": designTokens.color.elevatedBg,
  "--orf-bg-muted": designTokens.color.mutedBg,
  "--orf-bg-muted-strong": designTokens.color.mutedStrongBg,
  "--orf-bg-workflow": designTokens.color.workflowBg,
  "--orf-bg-workflow-header": designTokens.color.workflowHeaderBg,
  "--orf-bg-workflow-body": designTokens.color.workflowBodyBg,
  "--orf-border": designTokens.color.border,
  "--orf-border-strong": designTokens.color.borderStrong,
  "--orf-tree-line": designTokens.color.treeLine,
  "--orf-text-primary": designTokens.color.textPrimary,
  "--orf-text-secondary": designTokens.color.textSecondary,
  "--orf-text-muted": designTokens.color.textMuted,
  "--orf-text-faint": designTokens.color.textFaint,
  "--orf-accent": designTokens.color.accent,
  "--orf-accent-hover": designTokens.color.accentHover,
  "--orf-accent-soft": designTokens.color.accentSoft,
  "--orf-accent-border": designTokens.color.accentBorder,
  "--orf-accent-text": designTokens.color.accentText,
  "--orf-success-text": designTokens.color.successText,
  "--orf-success-bg": designTokens.color.successBg,
  "--orf-success-border": designTokens.color.successBorder,
  "--orf-warning-text": designTokens.color.warningText,
  "--orf-warning-bg": designTokens.color.warningBg,
  "--orf-warning-border": designTokens.color.warningBorder,
  "--orf-danger-text": designTokens.color.dangerText,
  "--orf-danger-bg": designTokens.color.dangerBg,
  "--orf-danger-border": designTokens.color.dangerBorder,
  "--orf-info-text": designTokens.color.infoText,
  "--orf-info-bg": designTokens.color.infoBg,
  "--orf-info-border": designTokens.color.infoBorder,
  "--orf-neutral-text": designTokens.color.neutralText,
  "--orf-neutral-bg": designTokens.color.neutralBg,
  "--orf-neutral-border": designTokens.color.neutralBorder,
  "--orf-bg-sidebar": designTokens.color.sidebarBg,
  "--orf-sidebar-header-bg": designTokens.color.sidebarHeaderBg,
  "--orf-sidebar-workspace-bg": designTokens.color.sidebarWorkspaceBg,
  "--orf-sidebar-selected-bg": designTokens.color.sidebarSelectedBg,
  "--orf-sidebar-hover-bg": designTokens.color.sidebarHoverBg,
  "--orf-sidebar-control-bg": designTokens.color.sidebarControlBg,
  "--orf-sidebar-control-hover-bg": designTokens.color.sidebarControlHoverBg,
  "--orf-sidebar-divider": designTokens.color.sidebarDivider,
  "--orf-sidebar-icon": designTokens.color.sidebarIcon,
  "--orf-sidebar-text": designTokens.color.sidebarText,
  "--orf-sidebar-text-muted": designTokens.color.sidebarTextMuted,
  "--orf-sidebar-link-text": designTokens.color.sidebarLinkText,
  "--orf-sidebar-command-text": designTokens.color.sidebarCommandText,
  "--orf-sidebar-logo-bg": designTokens.color.sidebarLogoBg,
  "--orf-sidebar-workspace-logo-bg": designTokens.color.sidebarWorkspaceLogoBg,
  "--orf-sidebar-workspace-logo-text": designTokens.color.sidebarWorkspaceLogoText,
  "--orf-avatar-border": designTokens.color.avatarBorder,
  "--orf-avatar-bg": designTokens.color.avatarBg,
  "--orf-avatar-text": designTokens.color.avatarText,
  "--orf-radius-card": designTokens.radius.card,
  "--orf-radius-control": designTokens.radius.control,
  "--orf-radius-status-tag": designTokens.radius.statusTag,
  "--orf-card-padding": designTokens.space.cardPadding,
  "--orf-page-padding-x": designTokens.space.pagePaddingX,
  "--orf-page-padding-y": designTokens.space.pagePaddingY,
  "--orf-row-height": designTokens.size.rowHeight,
  "--orf-tree-indent": designTokens.size.treeIndent,
  "--orf-topbar-height": designTokens.size.topbarHeight,
  "--orf-sidebar-width": designTokens.size.sidebarWidth,
  "--orf-sidebar-collapsed-width": designTokens.size.sidebarCollapsedWidth,
  "--orf-sidebar-header-height": designTokens.size.sidebarHeaderHeight,
  "--orf-border-width": designTokens.border.width,
  "--orf-shadow-card": designTokens.shadow.card,
  "--orf-page-glow": "radial-gradient(circle at 76% 0%, rgba(89, 196, 255, 0.18) 0 18%, transparent 38%), radial-gradient(circle at 10% 18%, rgba(255, 210, 126, 0.24) 0 16%, transparent 34%), linear-gradient(180deg, #fff9ec 0%, #eaf8ff 46%, #fff0d4 100%)",
} as const;

export function applyDesignTokens(root: HTMLElement = document.documentElement) {
  for (const [name, value] of Object.entries(designCssVariables)) {
    root.style.setProperty(name, value);
  }
}
