import { STATE_CASE_MODEL, type StateCaseSpec } from "../../_framework/types";
import type { ObjectivePublishCaseData } from "./_support/objective-publish.context";

export const objectivePublishCase = {
  id: "objectives.publish",
  title: "管理员可以新增并发布目标到悬赏大厅",
  model: STATE_CASE_MODEL,
  tags: ["objectives", "publish", "admin", "happy-path"],

  data: {
    email: "orf-admin-objective-publish-e2e@orf.local",
    password: "OrfAdminObjectivePublishE2E!2026",
    name: "ORF Admin Objective Publish E2E",
    role: "admin",
    memberEmail: "orf-member-objective-publish-e2e@orf.local",
    memberPassword: "OrfMemberObjectivePublishE2E!2026",
    memberName: "ORF Member Objective Publish E2E",
    memberRole: "member",
    objectiveTitle: "E2E-OBJECTIVE-PUBLISH: 管理员发布目标",
  },

  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      {
        source: { caseStepId: "B-1", method: "api" },
        id: "frontend.ready",
        title: "前端服务 应可用",
        object: "frontend.service",
        operator: "available",
      },
      {
        source: { caseStepId: "B-2", method: "api" },
        id: "backend.ready",
        title: "后端服务 应可用",
        object: "api.health",
        operator: "ok",
      },
      {
        source: { caseStepId: "B-3", method: "api" },
        id: "frontend.login_entry.accessible",
        title: "前端登录页入口 应可访问",
        object: "frontend.login_entry",
        operator: "accessible",
      },
      {
        source: { caseStepId: "B-4", method: "api" },
        id: "session.endpoint.accessible",
        title: "当前会话查询接口 应可访问",
        object: "auth.session",
        operator: "accessible",
      },
      {
        source: { caseStepId: "B-5", method: "prisma" },
        id: "db.ready",
        title: "ORF 数据库 应可连接",
        object: "db",
        operator: "ready",
      },
      {
        source: { caseStepId: "B-6", method: "prisma" },
        id: "db.schema.current",
        title: "ORF 数据库 schema 应为 当前测试版本",
        object: "db.schema",
        operator: "current",
      },
      {
        source: { caseStepId: "B-7", method: "api" },
        id: "ory.admin_public.ready",
        title: "Ory/Kratos Admin/Public API 应可访问",
        object: "ory.admin_public",
        operator: "ready",
      },
      {
        source: { caseStepId: "B-8", method: "api" },
        id: "session.unauthenticated",
        title: "当前会话 应为 未登录",
        object: "auth.session",
        operator: "unauthenticated",
      },
      {
        source: { caseStepId: "B-9", method: "playwright" },
        id: "cookie.absent",
        title: "当前浏览器 应不存在 Ory session cookie",
        object: "browser.cookie",
        operator: "absent",
      },
      {
        source: { caseStepId: "B-10", method: "playwright" },
        id: "storage.empty",
        title: "当前浏览器 storage 应不包含 登录态",
        object: "browser.auth_storage",
        operator: "empty",
      },
    ],
  },

  Setup: {
    description: "准备管理员和普通成员测试账号，登录管理员并进入挑战工作台所有挑战视图",
    steps: [
      {
        source: { caseStepId: "Setup-1", method: "prisma" },
        id: "db.objective.delete_residue",
        title: "删除可能残留的本用例测试目标及其派生数据",
        object: "db.objective",
        operator: "delete_by_title",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Setup-2", method: "api" },
        id: "ory.admin_identity.upsert",
        title: '准备邮箱为 "orf-admin-objective-publish-e2e@orf.local" 的管理员登录身份，并设置固定测试密码',
        object: "ory.identity",
        operator: "upsert_password",
        params: {
          emailFrom: "data.email",
          nameFrom: "data.name",
          passwordFrom: "data.password",
          saveAs: "adminIdentity",
        },
      },
      {
        source: { caseStepId: "Setup-3", method: "prisma" },
        id: "db.admin.upsert",
        title: '准备邮箱为 "orf-admin-objective-publish-e2e@orf.local"、角色为 admin、状态为 active 的管理员用户和默认团队成员关系',
        object: "db.user",
        operator: "upsert",
        params: {
          emailFrom: "data.email",
          nameFrom: "data.name",
          roleFrom: "data.role",
          status: "active",
          identityIdFrom: "runtime.adminIdentity.id",
          saveAs: "adminUser",
        },
      },
      {
        source: { caseStepId: "Setup-4", method: "api" },
        id: "ory.member_identity.upsert",
        title: '准备邮箱为 "orf-member-objective-publish-e2e@orf.local" 的普通成员登录身份，并设置固定测试密码',
        object: "ory.identity",
        operator: "upsert_password",
        params: {
          emailFrom: "data.memberEmail",
          nameFrom: "data.memberName",
          passwordFrom: "data.memberPassword",
          saveAs: "memberIdentity",
        },
      },
      {
        source: { caseStepId: "Setup-5", method: "prisma" },
        id: "db.member.upsert",
        title: '准备邮箱为 "orf-member-objective-publish-e2e@orf.local"、角色为 member、状态为 active 的普通成员用户和默认团队成员关系',
        object: "db.user",
        operator: "upsert",
        params: {
          emailFrom: "data.memberEmail",
          nameFrom: "data.memberName",
          roleFrom: "data.memberRole",
          status: "active",
          identityIdFrom: "runtime.memberIdentity.id",
          saveAs: "memberUser",
        },
      },
      {
        source: { caseStepId: "Setup-6", method: "api" },
        id: "ory.admin_sessions.revoke",
        title: "撤销管理员登录身份可能残留的 Ory session",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Setup-7", method: "api" },
        id: "ory.member_sessions.revoke",
        title: "撤销普通成员登录身份可能残留的 Ory session",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.memberEmail" },
      },
      {
        source: { caseStepId: "Setup-8", method: "playwright" },
        id: "browser.clear",
        title: "清空当前浏览器上下文的 cookies/localStorage/sessionStorage",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "Setup-9", method: "playwright" },
        id: "page.goto.auth",
        title: "打开 登录页",
        object: "page",
        operator: "goto",
        params: { path: "/auth" },
      },
      {
        source: { caseStepId: "Setup-10", method: "playwright" },
        id: "fill.email",
        title: "在邮箱输入框输入管理员测试邮箱",
        object: "page",
        operator: "fill",
        params: { label: "Email", valueFrom: "data.email" },
      },
      {
        source: { caseStepId: "Setup-11", method: "playwright" },
        id: "fill.password",
        title: "在密码输入框输入管理员测试密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.password" },
      },
      {
        source: { caseStepId: "Setup-12", method: "playwright" },
        id: "click.sign_in",
        title: '点击 "Sign In" 登录操作',
        object: "page",
        operator: "click",
        params: { role: "button", name: "Sign In" },
      },
      {
        source: { caseStepId: "Setup-13", method: "api" },
        id: "session.admin.authenticated",
        title: "当前会话 应为 管理员已登录",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      {
        source: { caseStepId: "Setup-14", method: "playwright" },
        id: "page.goto.tasks",
        title: "打开 挑战工作台",
        object: "page",
        operator: "goto",
        params: { path: "/tasks" },
      },
      {
        source: { caseStepId: "Setup-15", method: "playwright" },
        id: "scope.all",
        title: '切换到 "所有挑战" 视图',
        object: "page",
        operator: "click",
        params: { role: "button", name: "所有挑战" },
      },
      {
        source: { caseStepId: "Setup-16", method: "api" },
        id: "api.workbench.read",
        title: "读取 管理员挑战工作台数据",
        object: "api.my_challenges",
        operator: "read_all",
        params: { saveAs: "workbenchDataBefore" },
      },
    ],
  },

  S0: {
    description: "管理员已登录并位于挑战工作台，所有挑战视图和新建目标操作可用，测试目标仍不存在",
    assertions: [
      {
        source: { caseStepId: "S0-1", method: "api" },
        id: "session.admin.authenticated",
        title: '当前会话 应为 邮箱为 "orf-admin-objective-publish-e2e@orf.local"、角色为 admin、状态为 active 的已登录会话',
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      {
        source: { caseStepId: "S0-2", method: "playwright" },
        id: "url.tasks",
        title: "当前页面 应为 挑战工作台",
        object: "page.url",
        operator: "match",
        params: { pattern: "/tasks$" },
      },
      {
        source: { caseStepId: "S0-3", method: "playwright" },
        id: "scope.all.enabled",
        title: '"所有挑战" 视图 应可用',
        object: "page",
        operator: "enabled",
        params: { role: "button", name: "所有挑战" },
      },
      {
        source: { caseStepId: "S0-4", method: "playwright" },
        id: "new_objective.visible",
        title: '"新建目标" 操作 应可见',
        object: "page",
        operator: "visible",
        params: { role: "button", name: "新建目标" },
      },
      {
        source: { caseStepId: "S0-5", method: "playwright" },
        id: "new_objective.enabled",
        title: '"新建目标" 操作 应可点击',
        object: "page",
        operator: "enabled",
        params: { role: "button", name: "新建目标" },
      },
      {
        source: { caseStepId: "S0-6", method: "api" },
        id: "api.workbench.objective_absent",
        title: '管理员挑战工作台数据 应不包含 标题为 "E2E-OBJECTIVE-PUBLISH: 管理员发布目标" 的测试目标',
        object: "api.my_challenges",
        operator: "objective_absent",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "S0-7", method: "prisma" },
        id: "db.objective.absent",
        title: '应不存在 标题为 "E2E-OBJECTIVE-PUBLISH: 管理员发布目标" 的测试目标',
        object: "db.objective",
        operator: "absent",
        params: { titleFrom: "data.objectiveTitle" },
      },
    ],
  },

  Action: {
    description: "通过页面新建目标并发布该目标",
    steps: [
      {
        source: { caseStepId: "Action-1", method: "api" },
        id: "capture.create_objective_response",
        title: "在提交新建目标前注册创建目标接口响应捕获",
        object: "api",
        operator: "capture_response",
        params: { urlEndsWith: "/api/objectives", method: "POST", saveAs: "createObjectiveResponse" },
      },
      {
        source: { caseStepId: "Action-2", method: "playwright" },
        id: "click.new_objective",
        title: '点击 "新建目标" 操作',
        object: "page",
        operator: "click",
        params: { role: "button", name: "新建目标" },
      },
      {
        source: { caseStepId: "Action-3", method: "playwright" },
        id: "fill.objective_title",
        title: '填写 目标标题 为 "E2E-OBJECTIVE-PUBLISH: 管理员发布目标"',
        object: "page",
        operator: "fill",
        params: { label: "编辑目标标题", valueFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Action-4", method: "playwright" },
        id: "submit.objective_title",
        title: "提交 新建目标表单",
        object: "page.objective_title",
        operator: "submit",
      },
      {
        source: { caseStepId: "Action-5", method: "api" },
        id: "create_objective_response.record",
        title: "创建目标接口响应 应成功，并记录响应中的目标作为 创建的目标",
        object: "api.objective_create_response",
        operator: "record_objective",
        params: { responseFrom: "runtime.createObjectiveResponse", saveAs: "createdObjective" },
      },
      {
        source: { caseStepId: "Action-6", method: "playwright" },
        id: "created_objective.visible",
        title: "挑战工作台列表 应显示 创建的目标",
        object: "page.objective_panel",
        operator: "wait_visible",
        params: { targetFrom: "runtime.createdObjective" },
      },
      {
        source: { caseStepId: "Action-7", method: "playwright" },
        id: "created_objective.candidate",
        title: '创建的目标 的状态显示 应为 "候选中"',
        object: "page.objective_panel",
        operator: "status",
        params: { targetFrom: "runtime.createdObjective", statusText: "候选中" },
      },
      {
        source: { caseStepId: "Action-8", method: "api" },
        id: "capture.publish_objective_response",
        title: "在点击发布前注册发布目标接口响应捕获",
        object: "api.objective_publish",
        operator: "capture_response",
        params: { targetFrom: "runtime.createdObjective", saveAs: "publishObjectiveResponse" },
      },
      {
        source: { caseStepId: "Action-9", method: "playwright" },
        id: "click.publish_objective",
        title: '点击 创建的目标 的 "发布" 操作',
        object: "page.objective_panel",
        operator: "publish",
        params: { targetFrom: "runtime.createdObjective" },
      },
      {
        source: { caseStepId: "Action-10", method: "api" },
        id: "publish_objective_response.record",
        title: "发布目标接口响应 应成功，并记录响应中的目标作为 发布后的目标",
        object: "api.objective_publish_response",
        operator: "record_objective",
        params: { responseFrom: "runtime.publishObjectiveResponse", saveAs: "publishedObjective" },
      },
    ],
  },

  S1: {
    description: "目标已发布，接口、数据库、挑战工作台和悬赏大厅均显示该目标为可申请",
    assertions: [
      {
        source: { caseStepId: "S1-1", method: "api" },
        id: "created_objective.matches",
        title: "创建的目标 应为 标题正确、流转状态为 candidate、业务状态为 Draft、挑战者集合为空的候选草稿目标",
        object: "api.objective_create_response",
        operator: "matches",
        params: { targetFrom: "runtime.createdObjective", titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "S1-2", method: "api" },
        id: "published_objective.matches",
        title: "发布后的目标 应与 创建的目标 ID 相同，且流转状态为 open、阶段为 resultClaiming",
        object: "api.objective_publish_response",
        operator: "matches",
        params: { createdFrom: "runtime.createdObjective", publishedFrom: "runtime.publishedObjective" },
      },
      {
        source: { caseStepId: "S1-3", method: "prisma" },
        id: "db.objective.published",
        title: "数据库中 应存在 本用例创建且已发布的目标",
        object: "db.objective",
        operator: "published",
        params: { targetFrom: "runtime.publishedObjective" },
      },
      {
        source: { caseStepId: "S1-4", method: "api" },
        id: "api.workbench.objective_present",
        title: "管理员挑战工作台数据 应包含 本用例创建的目标",
        object: "api.my_challenges",
        operator: "objective_present",
        params: { targetFrom: "runtime.publishedObjective" },
      },
      {
        source: { caseStepId: "S1-5", method: "playwright" },
        id: "published_objective.visible",
        title: "挑战工作台列表 应显示 本用例创建的目标",
        object: "page.objective_panel",
        operator: "visible",
        params: { targetFrom: "runtime.publishedObjective" },
      },
      {
        source: { caseStepId: "S1-6", method: "playwright" },
        id: "published_objective.open_status",
        title: '本用例创建的目标 的操作状态 应显示为 "可申请"',
        object: "page.objective_panel",
        operator: "status",
        params: { targetFrom: "runtime.publishedObjective", statusText: "可申请" },
      },
      {
        source: { caseStepId: "S1-7", method: "api" },
        id: "api.admin_bounties.objective_present",
        title: "管理员视角的悬赏大厅数据 应包含 本用例创建的目标",
        object: "api.bounties",
        operator: "objective_present",
        params: { targetFrom: "runtime.publishedObjective" },
      },
      {
        source: { caseStepId: "S1-8", method: "playwright" },
        id: "page.goto.admin_bounties",
        title: "打开 管理员视角的悬赏大厅",
        object: "page",
        operator: "goto",
        params: { path: "/bounties" },
      },
      {
        source: { caseStepId: "S1-9", method: "playwright" },
        id: "admin_bounty_row.visible",
        title: "管理员视角的悬赏大厅列表 应显示 本用例创建的目标",
        object: "page.bounty_row",
        operator: "visible",
        params: { targetFrom: "runtime.publishedObjective" },
      },
      {
        source: { caseStepId: "S1-10", method: "api" },
        id: "auth.logout.admin",
        title: "调用退出登录接口撤销管理员登录会话",
        object: "auth",
        operator: "logout",
      },
      {
        source: { caseStepId: "S1-11", method: "playwright" },
        id: "browser.clear.admin",
        title: "清空当前浏览器上下文的 cookies/localStorage/sessionStorage",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "S1-12", method: "playwright" },
        id: "page.goto.auth.member",
        title: "打开 登录页",
        object: "page",
        operator: "goto",
        params: { path: "/auth" },
      },
      {
        source: { caseStepId: "S1-13", method: "playwright" },
        id: "fill.member.email",
        title: "在邮箱输入框输入普通成员测试邮箱",
        object: "page",
        operator: "fill",
        params: { label: "Email", valueFrom: "data.memberEmail" },
      },
      {
        source: { caseStepId: "S1-14", method: "playwright" },
        id: "fill.member.password",
        title: "在密码输入框输入普通成员测试密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.memberPassword" },
      },
      {
        source: { caseStepId: "S1-15", method: "playwright" },
        id: "click.member.sign_in",
        title: '点击 "Sign In" 登录操作',
        object: "page",
        operator: "click",
        params: { role: "button", name: "Sign In" },
      },
      {
        source: { caseStepId: "S1-16", method: "api" },
        id: "session.member.authenticated",
        title: '当前会话 应为 邮箱为 "orf-member-objective-publish-e2e@orf.local"、角色为 member、状态为 active 的已登录会话',
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.memberEmail", roleFrom: "data.memberRole", status: "active" },
      },
      {
        source: { caseStepId: "S1-17", method: "playwright" },
        id: "page.goto.member_bounties",
        title: "打开 普通成员视角的悬赏大厅",
        object: "page",
        operator: "goto",
        params: { path: "/bounties" },
      },
      {
        source: { caseStepId: "S1-18", method: "api" },
        id: "api.member_bounties.objective_present",
        title: "普通成员视角的悬赏大厅数据 应包含 本用例创建的目标",
        object: "api.bounties",
        operator: "objective_present",
        params: { targetFrom: "runtime.publishedObjective" },
      },
      {
        source: { caseStepId: "S1-19", method: "playwright" },
        id: "member_bounty_row.visible",
        title: "普通成员视角的悬赏大厅列表 应显示 本用例创建的目标",
        object: "page.bounty_row",
        operator: "visible",
        params: { targetFrom: "runtime.publishedObjective" },
      },
    ],
  },

  Clean: {
    description: "删除本用例目标、两个独占账号并恢复未登录基准状态",
    steps: [
      {
        source: { caseStepId: "Clean-1", method: "prisma" },
        id: "db.objective.delete_by_title",
        title: "删除本用例创建的目标及其派生数据",
        object: "db.objective",
        operator: "delete_by_title",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Clean-2", method: "api" },
        id: "auth.logout",
        title: "调用退出登录接口撤销当前登录会话",
        object: "auth",
        operator: "logout",
      },
      {
        source: { caseStepId: "Clean-3", method: "playwright" },
        id: "page.runtime.stop",
        title: "当前页面离开 ORF 前端应用",
        object: "page.runtime",
        operator: "stop",
      },
      {
        source: { caseStepId: "Clean-4", method: "playwright" },
        id: "browser.clear",
        title: "清空当前浏览器上下文的 cookies/localStorage/sessionStorage",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "Clean-5", method: "api" },
        id: "ory.admin_sessions.revoke",
        title: "撤销管理员登录身份的残留 Ory session",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-6", method: "api" },
        id: "ory.member_sessions.revoke",
        title: "撤销普通成员登录身份的残留 Ory session",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.memberEmail" },
      },
      {
        source: { caseStepId: "Clean-7", method: "api" },
        id: "ory.admin_identity.delete",
        title: '删除邮箱为 "orf-admin-objective-publish-e2e@orf.local" 的管理员登录身份',
        object: "ory.identity",
        operator: "delete_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-8", method: "api" },
        id: "ory.member_identity.delete",
        title: '删除邮箱为 "orf-member-objective-publish-e2e@orf.local" 的普通成员登录身份',
        object: "ory.identity",
        operator: "delete_by_email",
        params: { emailFrom: "data.memberEmail" },
      },
      {
        source: { caseStepId: "Clean-9", method: "prisma" },
        id: "db.admin.memberships.delete",
        title: "删除管理员用户的默认团队成员关系",
        object: "db.user",
        operator: "delete_memberships",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-10", method: "prisma" },
        id: "db.member.memberships.delete",
        title: "删除普通成员用户的默认团队成员关系",
        object: "db.user",
        operator: "delete_memberships",
        params: { emailFrom: "data.memberEmail" },
      },
      {
        source: { caseStepId: "Clean-11", method: "prisma" },
        id: "db.admin.delete",
        title: '删除邮箱为 "orf-admin-objective-publish-e2e@orf.local" 的管理员用户',
        object: "db.user",
        operator: "delete",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-12", method: "prisma" },
        id: "db.member.delete",
        title: '删除邮箱为 "orf-member-objective-publish-e2e@orf.local" 的普通成员用户',
        object: "db.user",
        operator: "delete",
        params: { emailFrom: "data.memberEmail" },
      },
      {
        source: { caseStepId: "Clean-13", method: "prisma" },
        id: "db.objective.absent",
        title: '应不存在 标题为 "E2E-OBJECTIVE-PUBLISH: 管理员发布目标" 的测试目标',
        object: "db.objective",
        operator: "absent",
        params: { titleFrom: "data.objectiveTitle" },
      },
    ],
  },
} satisfies StateCaseSpec<ObjectivePublishCaseData>;
