import { STATE_CASE_MODEL, type StateCaseSpec } from "../../_framework/types";
import type { ObjectivePublishCaseData } from "./_support/objective-publish.context";

export const objectivePublishCase = {
  id: "objectives.publish.admin",
  title: "管理员可以新增并发布目标到悬赏大厅",
  model: STATE_CASE_MODEL,
  tags: ["objectives", "publish", "admin", "happy-path"],

  data: {
    email: "zrx831@gmail.com",
    password: "123123123",
    name: "zrx",
    role: "admin",
    objectiveTitle: "E2E-OBJECTIVE-PUBLISH: 管理员发布目标",
  },

  B: {
    description: "系统服务、Ory、数据库和预置管理员可用，当前浏览器未登录且测试目标不存在",
    assertions: [
      { id: "backend.ready", title: "后端服务可用", object: "api.health", operator: "ok" },
      { id: "db.ready", title: "数据库可连接", object: "db", operator: "ready" },
      { id: "ory.ready", title: "Ory Admin API 可用", object: "ory.admin", operator: "ready" },
      {
        id: "ory.admin_identity.exists",
        title: "管理员 Ory 身份存在",
        object: "ory.identity",
        operator: "exists",
        params: { emailFrom: "data.email" },
      },
      {
        id: "db.admin.active",
        title: "预置管理员账号可用",
        object: "db.admin",
        operator: "active",
      },
      {
        id: "db.objective.absent",
        title: "测试目标不存在",
        object: "db.objective",
        operator: "absent",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        id: "protected.redirects_to_auth",
        title: "挑战工作台受保护且未登录会回到登录页",
        object: "page.protected",
        operator: "redirects_to_auth",
        params: { path: "/tasks", pattern: "/auth$" },
      },
      { id: "session.unauthenticated", title: "后端 session 未登录", object: "auth.session", operator: "unauthenticated" },
      { id: "cookie.absent", title: "浏览器不存在登录 cookie", object: "browser.cookie", operator: "absent" },
      { id: "storage.empty", title: "浏览器 storage 不含登录态", object: "browser.auth_storage", operator: "empty" },
    ],
  },

  Setup: {
    description: "清理浏览器，登录管理员并进入挑战工作台所有挑战视图",
    steps: [
      { id: "browser.clear", title: "清理浏览器状态", object: "browser", operator: "clear_state" },
      { id: "page.goto.auth", title: "打开登录页", object: "page", operator: "goto", params: { path: "/auth" } },
      { id: "fill.email", title: "输入管理员邮箱", object: "page", operator: "fill", params: { label: "Email", valueFrom: "data.email" } },
      {
        id: "fill.password",
        title: "输入管理员密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.password" },
      },
      {
        id: "click.sign_in",
        title: "点击登录按钮",
        object: "page",
        operator: "click",
        params: { role: "button", name: "Sign In" },
      },
      {
        id: "session.authenticated",
        title: "等待管理员 session 已登录",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      { id: "page.goto.tasks", title: "打开挑战工作台", object: "page", operator: "goto", params: { path: "/tasks" } },
      {
        id: "scope.all",
        title: "切换到所有挑战视图",
        object: "page",
        operator: "click",
        params: { role: "button", name: "所有挑战" },
      },
      {
        id: "api.workbench.read",
        title: "读取管理员挑战工作台数据",
        object: "api.my_challenges",
        operator: "read_all",
        params: { saveAs: "workbenchDataBefore" },
      },
    ],
  },

  S0: {
    description: "管理员已登录并位于挑战工作台，所有挑战视图和新建目标操作可用，测试目标仍不存在",
    assertions: [
      {
        id: "session.authenticated",
        title: "后端 session 已登录",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      { id: "url.tasks", title: "当前页面是挑战工作台", object: "page.url", operator: "match", params: { pattern: "/tasks$" } },
      { id: "scope.all.enabled", title: "所有挑战视图可用", object: "page", operator: "enabled", params: { role: "button", name: "所有挑战" } },
      { id: "new_objective.visible", title: "新建目标操作可见", object: "page", operator: "visible", params: { role: "button", name: "新建目标" } },
      { id: "new_objective.enabled", title: "新建目标操作可点击", object: "page", operator: "enabled", params: { role: "button", name: "新建目标" } },
      {
        id: "api.workbench.objective_absent",
        title: "管理员挑战工作台数据不包含测试目标",
        object: "api.my_challenges",
        operator: "objective_absent",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        id: "db.objective.absent",
        title: "数据库中不存在测试目标",
        object: "db.objective",
        operator: "absent",
        params: { titleFrom: "data.objectiveTitle" },
      },
    ],
  },

  Action: {
    description: "通过页面新建目标并发布该目标",
    steps: [
      {
        id: "capture.create_objective_response",
        title: "监听创建目标请求",
        object: "api",
        operator: "capture_response",
        params: { urlEndsWith: "/api/objectives", method: "POST", saveAs: "createObjectiveResponse" },
      },
      {
        id: "click.new_objective",
        title: "点击新建目标",
        object: "page",
        operator: "click",
        params: { role: "button", name: "新建目标" },
      },
      {
        id: "fill.objective_title",
        title: "填写目标标题",
        object: "page",
        operator: "fill",
        params: { label: "编辑目标标题", valueFrom: "data.objectiveTitle" },
      },
      { id: "submit.objective_title", title: "提交新建目标表单", object: "page.objective_title", operator: "submit" },
      {
        id: "create_objective_response.record",
        title: "记录创建的目标",
        object: "api.objective_create_response",
        operator: "record_objective",
        params: { responseFrom: "runtime.createObjectiveResponse", saveAs: "createdObjective" },
      },
      {
        id: "created_objective.visible",
        title: "创建的目标显示在挑战工作台",
        object: "page.objective_panel",
        operator: "wait_visible",
        params: { targetFrom: "runtime.createdObjective" },
      },
      {
        id: "created_objective.candidate",
        title: "创建的目标显示为候选中",
        object: "page.objective_panel",
        operator: "status",
        params: { targetFrom: "runtime.createdObjective", statusText: "候选中" },
      },
      {
        id: "capture.publish_objective_response",
        title: "监听发布目标请求",
        object: "api.objective_publish",
        operator: "capture_response",
        params: { targetFrom: "runtime.createdObjective", saveAs: "publishObjectiveResponse" },
      },
      {
        id: "click.publish_objective",
        title: "点击发布目标",
        object: "page.objective_panel",
        operator: "publish",
        params: { targetFrom: "runtime.createdObjective" },
      },
      {
        id: "publish_objective_response.record",
        title: "记录发布后的目标",
        object: "api.objective_publish_response",
        operator: "record_objective",
        params: { responseFrom: "runtime.publishObjectiveResponse", saveAs: "publishedObjective" },
      },
    ],
  },

  S1: {
    description: "目标已发布，接口、数据库、挑战工作台和悬赏大厅均显示该目标为可申请",
    assertions: [
      {
        id: "created_objective.matches",
        title: "创建的目标是候选草稿目标",
        object: "api.objective_create_response",
        operator: "matches",
        params: { targetFrom: "runtime.createdObjective", titleFrom: "data.objectiveTitle" },
      },
      {
        id: "published_objective.matches",
        title: "发布后的目标状态正确",
        object: "api.objective_publish_response",
        operator: "matches",
        params: { createdFrom: "runtime.createdObjective", publishedFrom: "runtime.publishedObjective" },
      },
      {
        id: "db.objective.published",
        title: "数据库中目标已发布",
        object: "db.objective",
        operator: "published",
        params: { targetFrom: "runtime.publishedObjective" },
      },
      {
        id: "api.workbench.objective_present",
        title: "管理员挑战工作台数据包含已发布目标",
        object: "api.my_challenges",
        operator: "objective_present",
        params: { targetFrom: "runtime.publishedObjective" },
      },
      {
        id: "published_objective.visible",
        title: "挑战工作台显示已发布目标",
        object: "page.objective_panel",
        operator: "visible",
        params: { targetFrom: "runtime.publishedObjective" },
      },
      {
        id: "published_objective.open_status",
        title: "挑战工作台显示目标可申请",
        object: "page.objective_panel",
        operator: "status",
        params: { targetFrom: "runtime.publishedObjective", statusText: "可申请" },
      },
      {
        id: "api.bounties.objective_present",
        title: "悬赏大厅数据包含已发布目标",
        object: "api.bounties",
        operator: "objective_present",
        params: { targetFrom: "runtime.publishedObjective" },
      },
      { id: "page.goto.bounties", title: "打开悬赏大厅", object: "page", operator: "goto", params: { path: "/bounties" } },
      {
        id: "bounty_row.visible",
        title: "悬赏大厅列表显示已发布目标",
        object: "page.bounty_row",
        operator: "visible",
        params: { targetFrom: "runtime.publishedObjective" },
      },
    ],
  },

  Clean: {
    description: "删除本用例创建的目标，退出登录并恢复未登录基准状态",
    steps: [
      {
        id: "db.objective.delete_by_title",
        title: "删除本用例创建的目标",
        object: "db.objective",
        operator: "delete_by_title",
        params: { titleFrom: "data.objectiveTitle" },
      },
      { id: "auth.logout", title: "退出当前登录态", object: "auth", operator: "logout" },
      { id: "browser.clear", title: "清理浏览器状态", object: "browser", operator: "clear_state" },
      { id: "session.unauthenticated", title: "后端 session 未登录", object: "auth.session", operator: "unauthenticated" },
      {
        id: "ory.admin_identity.exists",
        title: "管理员 Ory 身份仍然存在",
        object: "ory.identity",
        operator: "exists",
        params: { emailFrom: "data.email" },
      },
      {
        id: "db.admin.active",
        title: "预置管理员账号仍然可用",
        object: "db.admin",
        operator: "active",
      },
      {
        id: "db.objective.absent",
        title: "测试目标已清理",
        object: "db.objective",
        operator: "absent",
        params: { titleFrom: "data.objectiveTitle" },
      },
    ],
  },
} satisfies StateCaseSpec<ObjectivePublishCaseData>;
