import { STATE_CASE_MODEL, type StateCaseSpec, type StepExecutionMethod, type StepSpec } from "../../_framework/types";
import type { PersonalSettingsCustomSkinCaseData } from "./_support/personal-settings-custom-skin.context";

function step(
  caseStepId: string,
  method: StepExecutionMethod,
  id: string,
  title: string,
  object: string,
  operator: string,
  params?: Record<string, unknown>,
): StepSpec {
  return {
    source: { caseStepId, method },
    id,
    title,
    object,
    operator,
    ...(params ? { params } : {}),
  };
}

export const personalSettingsCustomSkinCase = {
  id: "defaults.personal-settings.custom-skin",
  title: "19-个人设置自定义皮肤管理校验",
  model: STATE_CASE_MODEL,
  tags: ["defaults", "personal-settings", "custom-skin", "background"],
  data: {
    email: "orf-default-page-custom-skin-e2e@orf.local",
    password: "OrfDefaultPageCustomSkinE2E!2026",
    name: "ORF 默认页自定义皮肤用户",
    role: "member",
    status: "active",
    settingsPathPattern: "/settings$",
    validSkinFileName: "personal-settings-custom-skin-valid.png",
    secondValidSkinFileName: "personal-settings-custom-skin-second.png",
    invalidSkinFileName: "personal-settings-custom-skin-invalid.txt",
    invalidSkinMessage: "仅支持上传图片文件",
  },
  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      step("B-1", "api", "frontend.ready", "前端服务 应可用", "frontend.service", "available"),
      step("B-2", "api", "backend.ready", "后端服务 应可用", "api.health", "ok"),
      step("B-3", "api", "frontend.login_entry.accessible", "前端登录页入口 应可访问", "frontend.login_entry", "accessible"),
      step("B-4", "api", "session.endpoint.accessible", "当前会话查询能力 应可用", "auth.session", "accessible"),
      step("B-5", "prisma", "db.ready", "ORF 数据库 应可连接", "db", "ready"),
      step("B-6", "prisma", "db.schema.current", "ORF 数据库 schema 应为 当前测试版本", "db.schema", "current"),
      step("B-7", "api", "ory.admin_public.ready", "Ory/Kratos 认证服务的管理和公共访问能力 应可用", "ory.admin_public", "ready"),
      step("B-8", "api", "session.unauthenticated", "当前会话 应为 未登录", "auth.session", "unauthenticated"),
      step("B-9", "playwright", "cookie.absent", "当前浏览器 应不存在 Ory 登录会话 cookie", "browser.cookie", "absent"),
      step("B-10", "playwright", "storage.empty", "当前浏览器 应不保留本地登录态", "browser.auth_storage", "empty"),
    ],
  },
  Setup: {
    description: "准备自定义皮肤测试用户、测试文件，并登录进入个人设置页面",
    steps: [
      step("Setup-1", "api", "ory.identity.upsert", "准备邮箱为 `orf-default-page-custom-skin-e2e@orf.local`、使用固定测试密码的个人设置自定义皮肤测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.email", passwordFrom: "data.password", nameFrom: "data.name", saveAs: "identity" }),
      step("Setup-2", "prisma", "db.user.upsert", "准备邮箱为 `orf-default-page-custom-skin-e2e@orf.local`、姓名为 `ORF 默认页自定义皮肤用户`、角色为 `member`、状态为 `active` 的个人设置自定义皮肤测试用户", "db.user", "upsert", { emailFrom: "data.email", passwordFrom: "data.password", nameFrom: "data.name", roleFrom: "data.role", statusFrom: "data.status", identityIdFrom: "runtime.identity.id", saveAs: "user" }),
      step("Setup-3", "api", "preferences.default_landing.default", "设置个人设置自定义皮肤测试用户默认进入页面为 首页（默认系统页）", "user.preferences", "reset_default_landing_path_by_email", { emailFrom: "data.email" }),
      step("Setup-4", "api", "preferences.app_background.default", "设置个人设置自定义皮肤测试用户 AppShell 皮肤偏好为 系统默认", "user.preferences", "reset_app_background_by_email", { emailFrom: "data.email" }),
      step("Setup-5", "api", "personal_backgrounds.delete_residual", "删除个人设置自定义皮肤测试用户的残留自定义皮肤文件", "user.personal_backgrounds", "delete_by_email", { emailFrom: "data.email" }),
      step("Setup-6", "mock", "mock.valid_skin.prepare", "准备本用例有效格式自定义皮肤图片文件", "mock.skin_file", "prepare_image", { fileNameFrom: "data.validSkinFileName", saveAs: "validSkinFile" }),
      step("Setup-7", "mock", "mock.invalid_skin.prepare", "准备本用例无效格式自定义皮肤文件", "mock.skin_file", "prepare_invalid", { fileNameFrom: "data.invalidSkinFileName", saveAs: "invalidSkinFile" }),
      step("Setup-8", "api", "ory.sessions.revoke", "撤销邮箱为 `orf-default-page-custom-skin-e2e@orf.local` 的个人设置自定义皮肤测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.email" }),
      step("Setup-9", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Setup-10", "playwright", "page.goto.auth", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Setup-11", "playwright", "fill.email", "在邮箱输入框输入 `orf-default-page-custom-skin-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.email" }),
      step("Setup-12", "playwright", "fill.password", "在密码输入框输入个人设置自定义皮肤测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.password" }),
      step("Setup-13", "playwright", "click.sign_in", "点击 \"Sign In\" 登录操作", "page.login_form", "submit", { saveAs: "loginResponse" }),
      step("Setup-14", "api", "session.authenticated", "当前会话 应为 邮箱为 `orf-default-page-custom-skin-e2e@orf.local`、角色为 `member`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.email", roleFrom: "data.role", statusFrom: "data.status" }),
      step("Setup-15", "playwright", "page.goto.settings", "打开 个人设置页面", "page", "goto", { path: "/settings" }),
    ],
  },
  S0: {
    description: "测试用户位于个人设置页，皮肤区域可操作且没有自定义皮肤",
    assertions: [
      step("S0-1", "api", "session.authenticated", "当前会话 应为 邮箱为 `orf-default-page-custom-skin-e2e@orf.local`、角色为 `member`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.email", roleFrom: "data.role", statusFrom: "data.status" }),
      step("S0-2", "playwright", "personal_settings.page.visible", "当前页面 应为 个人设置页面", "personal_settings.page", "visible", { patternFrom: "data.settingsPathPattern" }),
      step("S0-3", "playwright", "personal_settings.skin_section.visible", "个人设置页面的“我的 AppShell 皮肤”区域 应可见", "personal_settings.skin_section", "visible"),
      step("S0-4", "playwright", "personal_settings.skin_list.visible", "个人设置页面的皮肤列表 应可见", "personal_settings.skin_list", "visible"),
      step("S0-5", "playwright", "personal_settings.upload_skin.enabled", "个人设置页面的上传皮肤操作 应可点击", "personal_settings.upload_skin", "enabled"),
      step("S0-6", "playwright", "personal_settings.use_selected.visible", "个人设置页面的设为我的背景操作 应可见", "personal_settings.use_selected_background", "visible"),
      step("S0-7", "playwright", "personal_settings.delete_skin.visible", "个人设置页面的删除皮肤操作 应可见", "personal_settings.delete_skin", "visible"),
      step("S0-8", "api", "preferences.app_background.default", "个人设置自定义皮肤测试用户的 AppShell 皮肤偏好 应为 系统默认", "user.preferences", "app_background_is_default", { emailFrom: "data.email" }),
      step("S0-9", "api", "personal_backgrounds.absent", "个人设置自定义皮肤测试用户 应不存在 自定义皮肤文件", "user.personal_backgrounds", "absent", { emailFrom: "data.email" }),
    ],
  },
  Action: {
    description: "上传、校验、应用并删除自定义皮肤",
    steps: [
      step("Action-1", "playwright", "custom_skin.upload_valid", "通过个人设置页面的上传皮肤操作选择本用例有效格式自定义皮肤图片文件", "personal_settings.custom_skin_upload", "choose", { filePathFrom: "runtime.validSkinFile.path", emailFrom: "data.email", saveAs: "validUploadSnapshot" }),
      step("Action-2", "playwright", "custom_skin.upload_invalid", "通过个人设置页面的上传皮肤操作选择本用例无效格式自定义皮肤文件", "personal_settings.custom_skin_upload", "choose_invalid", { filePathFrom: "runtime.invalidSkinFile.path", emailFrom: "data.email", messageFrom: "data.invalidSkinMessage", beforeSnapshotFrom: "runtime.validUploadSnapshot", saveAs: "invalidUploadSnapshot" }),
      step("Action-3", "playwright", "custom_skin.use_default_before_apply", "点击 个人设置页面的使用系统默认操作", "personal_settings.use_system_default_background", "click", { emailFrom: "data.email", saveAs: "defaultBeforeApplySnapshot" }),
      step("Action-4", "playwright", "custom_skin.select_uploaded", "选择 个人设置页面的已上传自定义皮肤卡片", "personal_settings.custom_skin_card", "select", { backgroundFrom: "runtime.validUploadSnapshot.background", saveAs: "selectedCustomSkin" }),
      step("Action-5", "playwright", "custom_skin.use_selected", "点击 个人设置页面的设为我的背景操作", "personal_settings.use_selected_background", "click", { emailFrom: "data.email", backgroundFrom: "runtime.selectedCustomSkin", saveAs: "appliedCustomSkinSnapshot" }),
      step("Action-6", "playwright", "custom_skin.delete_current", "点击 个人设置页面的删除皮肤操作", "personal_settings.delete_custom_skin", "click", { emailFrom: "data.email", backgroundFrom: "runtime.selectedCustomSkin", saveAs: "deleteCurrentSkinSnapshot" }),
      step("Action-7", "playwright", "custom_skin.upload_second_valid", "通过个人设置页面的上传皮肤操作再次选择本用例有效格式自定义皮肤图片文件", "personal_settings.custom_skin_upload", "choose", { filePathFrom: "runtime.validSkinFile.path", emailFrom: "data.email", saveAs: "secondValidUploadSnapshot" }),
      step("Action-8", "playwright", "custom_skin.use_default", "点击 个人设置页面的使用系统默认操作", "personal_settings.use_system_default_background", "click", { emailFrom: "data.email", saveAs: "systemDefaultSkinSnapshot" }),
      step("Action-9", "playwright", "custom_skin.select_second_uploaded", "选择 个人设置页面的新上传自定义皮肤卡片", "personal_settings.custom_skin_card", "select", { backgroundFrom: "runtime.secondValidUploadSnapshot.background", saveAs: "selectedSecondCustomSkin" }),
      step("Action-10", "playwright", "custom_skin.delete_unused", "点击 个人设置页面的删除皮肤操作", "personal_settings.delete_custom_skin", "click", { emailFrom: "data.email", backgroundFrom: "runtime.selectedSecondCustomSkin", saveAs: "deleteUnusedSkinSnapshot" }),
    ],
  },
  S1: {
    description: "自定义皮肤上传、无效格式拦截、应用和删除均符合预期",
    assertions: [
      step("S1-1", "playwright", "snapshot.valid_upload.list_visible", "有效格式自定义皮肤上传后，个人设置页面的皮肤列表 应显示 已上传自定义皮肤", "custom_skin_snapshot", "list_contains_background", { snapshotFrom: "runtime.validUploadSnapshot" }),
      step("S1-2", "api", "snapshot.valid_upload.file_exists", "有效格式自定义皮肤上传后，个人设置自定义皮肤测试用户 应存在 自定义皮肤文件", "custom_skin_snapshot", "file_exists", { snapshotFrom: "runtime.validUploadSnapshot" }),
      step("S1-3", "playwright", "snapshot.invalid_upload.toast", "无效格式自定义皮肤上传后，系统 应提示 `仅支持上传图片文件`", "custom_skin_snapshot", "toast_visible", { snapshotFrom: "runtime.invalidUploadSnapshot", messageFrom: "data.invalidSkinMessage" }),
      step("S1-4", "playwright", "snapshot.invalid_upload.list_still_visible", "无效格式自定义皮肤上传后，个人设置页面的皮肤列表 应仍显示 已上传自定义皮肤", "custom_skin_snapshot", "list_contains_background", { snapshotFrom: "runtime.invalidUploadSnapshot" }),
      step("S1-5", "api", "snapshot.invalid_upload.file_unchanged", "无效格式自定义皮肤上传后，个人设置自定义皮肤测试用户的自定义皮肤文件 应仍为 有效格式自定义皮肤上传后的文件", "custom_skin_snapshot", "file_unchanged", { beforeSnapshotFrom: "runtime.validUploadSnapshot", afterSnapshotFrom: "runtime.invalidUploadSnapshot" }),
      step("S1-6", "playwright", "snapshot.applied.appshell_background", "选择自定义皮肤并设为我的背景后，AppShell 皮肤背景 应应用所选自定义皮肤", "custom_skin_snapshot", "appshell_background_applied", { snapshotFrom: "runtime.appliedCustomSkinSnapshot", backgroundFrom: "runtime.selectedCustomSkin" }),
      step("S1-7", "api", "snapshot.applied.preference", "选择自定义皮肤并设为我的背景后，个人设置自定义皮肤测试用户的 AppShell 皮肤偏好 应为 所选自定义皮肤", "custom_skin_snapshot", "preference_is_background", { snapshotFrom: "runtime.appliedCustomSkinSnapshot", backgroundFrom: "runtime.selectedCustomSkin" }),
      step("S1-8", "playwright", "snapshot.delete_current.list_absent", "删除当前正在使用的自定义皮肤后，个人设置页面的皮肤列表 应不显示 被删除的自定义皮肤", "custom_skin_snapshot", "list_not_contains_background", { snapshotFrom: "runtime.deleteCurrentSkinSnapshot" }),
      step("S1-9", "playwright", "snapshot.delete_current.appshell_default", "删除当前正在使用的自定义皮肤后，AppShell 皮肤背景 应恢复为 系统默认皮肤", "custom_skin_snapshot", "appshell_background_default", { snapshotFrom: "runtime.deleteCurrentSkinSnapshot" }),
      step("S1-10", "api", "snapshot.delete_current.preference_default", "删除当前正在使用的自定义皮肤后，个人设置自定义皮肤测试用户的 AppShell 皮肤偏好 应为 系统默认", "custom_skin_snapshot", "preference_is_default", { snapshotFrom: "runtime.deleteCurrentSkinSnapshot" }),
      step("S1-11", "playwright", "snapshot.second_valid_upload.list_visible", "再次上传有效格式自定义皮肤后，个人设置页面的皮肤列表 应显示 新上传自定义皮肤", "custom_skin_snapshot", "list_contains_background", { snapshotFrom: "runtime.secondValidUploadSnapshot" }),
      step("S1-12", "api", "snapshot.system_default.preference_default", "点击使用系统默认后，个人设置自定义皮肤测试用户的 AppShell 皮肤偏好 应为 系统默认", "custom_skin_snapshot", "preference_is_default", { snapshotFrom: "runtime.systemDefaultSkinSnapshot" }),
      step("S1-13", "playwright", "snapshot.delete_unused.list_absent", "删除未设为当前背景的自定义皮肤后，个人设置页面的皮肤列表 应不显示 被删除的自定义皮肤", "custom_skin_snapshot", "list_not_contains_background", { snapshotFrom: "runtime.deleteUnusedSkinSnapshot" }),
      step("S1-14", "api", "snapshot.delete_unused.files_absent", "删除未设为当前背景的自定义皮肤后，个人设置自定义皮肤测试用户 应不存在 自定义皮肤文件", "user.personal_backgrounds", "absent", { emailFrom: "data.email" }),
      step("S1-15", "api", "session.authenticated", "当前会话 应为 邮箱为 `orf-default-page-custom-skin-e2e@orf.local`、角色为 `member`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.email", roleFrom: "data.role", statusFrom: "data.status" }),
    ],
  },
  Clean: {
    description: "删除测试用户自定义皮肤、偏好、账号和页面会话状态，恢复未登录基准状态",
    steps: [
      step("Clean-1", "api", "auth.logout", "注销当前登录会话", "auth", "logout"),
      step("Clean-2", "playwright", "page.runtime.stop", "离开当前 ORF 前端页面", "page.runtime", "stop"),
      step("Clean-3", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Clean-4", "api", "ory.sessions.revoke", "撤销邮箱为 `orf-default-page-custom-skin-e2e@orf.local` 的个人设置自定义皮肤测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.email" }),
      step("Clean-5", "api", "preferences.default_landing.reset", "恢复邮箱为 `orf-default-page-custom-skin-e2e@orf.local` 的默认进入页面为 系统默认", "user.preferences", "reset_default_landing_path_by_email", { emailFrom: "data.email" }),
      step("Clean-6", "api", "preferences.app_background.reset", "恢复邮箱为 `orf-default-page-custom-skin-e2e@orf.local` 的 AppShell 皮肤偏好为 系统默认", "user.preferences", "reset_app_background_by_email", { emailFrom: "data.email" }),
      step("Clean-7", "api", "personal_backgrounds.delete", "删除个人设置自定义皮肤测试用户的自定义皮肤文件", "user.personal_backgrounds", "delete_by_email", { emailFrom: "data.email" }),
      step("Clean-8", "api", "ory.identity.delete", "删除邮箱为 `orf-default-page-custom-skin-e2e@orf.local` 的个人设置自定义皮肤测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.email" }),
      step("Clean-9", "prisma", "db.user.memberships.delete", "删除邮箱为 `orf-default-page-custom-skin-e2e@orf.local` 的个人设置自定义皮肤测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.email" }),
      step("Clean-10", "prisma", "db.user.delete", "删除邮箱为 `orf-default-page-custom-skin-e2e@orf.local` 的个人设置自定义皮肤测试用户", "db.user", "delete", { emailFrom: "data.email" }),
      step("Clean-11", "api", "ory.identity.absent", "邮箱为 `orf-default-page-custom-skin-e2e@orf.local` 的个人设置自定义皮肤测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.email" }),
      step("Clean-12", "prisma", "db.user.absent", "邮箱为 `orf-default-page-custom-skin-e2e@orf.local` 的个人设置自定义皮肤测试用户 应不存在", "db.user", "absent", { emailFrom: "data.email" }),
    ],
  },
} satisfies StateCaseSpec<PersonalSettingsCustomSkinCaseData>;
