import { STATE_CASE_MODEL, type StateCaseSpec, type StepExecutionMethod, type StepSpec } from "../../_framework/types";
import type { SystemMembersStatusCaseData } from "./_support/members-status.context";

function step(
  caseStepId: string,
  method: StepExecutionMethod,
  id: string,
  title: string,
  object: string,
  operator: string,
  params?: Record<string, unknown>,
): StepSpec {
  return {
    source: { caseStepId, method },
    id,
    title,
    object,
    operator,
    ...(params ? { params } : {}),
  };
}

export const systemMembersStatusCase = {
  id: "system.members-status.disable-enable",
  title: "07-成员管理停用启用用户校验",
  model: STATE_CASE_MODEL,
  tags: ["system", "members", "status", "disable", "enable"],
  data: {
    admin: {
      email: "orf-system-members-status-admin-e2e@orf.local",
      password: "OrfSystemMembersStatusAdminE2E!2026",
      name: "ORF Members Status Admin E2E",
      role: "admin",
    },
    activeUser: {
      email: "orf-system-members-status-active-e2e@orf.local",
      password: "OrfSystemMembersStatusActiveE2E!2026",
      name: "ORF Members Status Active E2E",
      role: "member",
    },
    disabledUser: {
      email: "orf-system-members-status-disabled-e2e@orf.local",
      password: "OrfSystemMembersStatusDisabledE2E!2026",
      name: "ORF Members Status Disabled E2E",
      role: "member",
    },
    cancelUser: {
      email: "orf-system-members-status-cancel-e2e@orf.local",
      password: "OrfSystemMembersStatusCancelE2E!2026",
      name: "ORF Members Status Cancel E2E",
      role: "member",
    },
    defaultLandingPath: "/bounties",
    membersPath: "/system/members",
  },
  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      step("B-1", "api", "frontend.ready", "前端服务 应可用", "frontend.service", "available"),
      step("B-2", "api", "backend.ready", "后端服务 应可用", "api.health", "ok"),
      step("B-3", "api", "frontend.login_entry.accessible", "前端登录页入口 应可访问", "frontend.login_entry", "accessible"),
      step("B-4", "api", "session.endpoint.accessible", "当前会话查询能力 应可用", "auth.session", "accessible"),
      step("B-5", "prisma", "db.ready", "ORF 数据库 应可连接", "db", "ready"),
      step("B-6", "prisma", "db.schema.current", "ORF 数据库 schema 应为 当前测试版本", "db.schema", "current"),
      step("B-7", "api", "ory.admin_public.ready", "Ory/Kratos 认证服务的管理和公共访问能力 应可用", "ory.admin_public", "ready"),
      step("B-8", "api", "session.unauthenticated", "当前会话 应为 未登录", "auth.session", "unauthenticated"),
      step("B-9", "playwright", "cookie.absent", "当前浏览器 应不存在 Ory 登录会话 cookie", "browser.cookie", "absent"),
      step("B-10", "playwright", "storage.empty", "当前浏览器 应不保留本地登录态", "browser.auth_storage", "empty"),
    ],
  },
  Setup: {
    description: "准备管理员、待停用用户、待启用用户和取消停用用户，并以管理员身份进入成员管理页面",
    steps: [
      step("Setup-1", "api", "ory.admin_identity.upsert", "准备邮箱为 `orf-system-members-status-admin-e2e@orf.local`、使用固定测试密码的成员管理停用启用管理员测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.admin.email", passwordFrom: "data.admin.password", nameFrom: "data.admin.name", saveAs: "adminIdentity" }),
      step("Setup-2", "prisma", "db.admin_user.upsert", "准备姓名为 \"ORF Members Status Admin E2E\"、邮箱为 `orf-system-members-status-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的成员管理停用启用管理员测试用户", "db.user", "upsert", { emailFrom: "data.admin.email", passwordFrom: "data.admin.password", nameFrom: "data.admin.name", roleFrom: "data.admin.role", status: "active", identityIdFrom: "runtime.adminIdentity.id", saveAs: "adminUser" }),
      step("Setup-3", "api", "admin.preferences.default_landing_path.set", "设置成员管理停用启用管理员测试用户默认进入页面为 首页（默认系统页）", "user.preferences", "set_default_landing_path_by_email", { emailFrom: "data.admin.email", pathFrom: "data.defaultLandingPath" }),
      step("Setup-4", "api", "ory.active_identity.upsert", "准备邮箱为 `orf-system-members-status-active-e2e@orf.local`、使用固定测试密码的成员管理待停用测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.activeUser.email", passwordFrom: "data.activeUser.password", nameFrom: "data.activeUser.name", saveAs: "activeIdentity" }),
      step("Setup-5", "prisma", "db.active_user.upsert", "准备姓名为 \"ORF Members Status Active E2E\"、邮箱为 `orf-system-members-status-active-e2e@orf.local`、角色为 `member`、状态为 `active` 的成员管理待停用测试用户", "db.user", "upsert", { emailFrom: "data.activeUser.email", passwordFrom: "data.activeUser.password", nameFrom: "data.activeUser.name", roleFrom: "data.activeUser.role", status: "active", identityIdFrom: "runtime.activeIdentity.id", saveAs: "activeUser" }),
      step("Setup-6", "api", "ory.disabled_identity.upsert", "准备邮箱为 `orf-system-members-status-disabled-e2e@orf.local`、使用固定测试密码的成员管理待启用测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.disabledUser.email", passwordFrom: "data.disabledUser.password", nameFrom: "data.disabledUser.name", saveAs: "disabledIdentity" }),
      step("Setup-7", "prisma", "db.disabled_user.upsert", "准备姓名为 \"ORF Members Status Disabled E2E\"、邮箱为 `orf-system-members-status-disabled-e2e@orf.local`、角色为 `member`、状态为 `disabled` 的成员管理待启用测试用户", "db.user", "upsert", { emailFrom: "data.disabledUser.email", passwordFrom: "data.disabledUser.password", nameFrom: "data.disabledUser.name", roleFrom: "data.disabledUser.role", status: "disabled", identityIdFrom: "runtime.disabledIdentity.id", saveAs: "disabledUser" }),
      step("Setup-8", "api", "ory.cancel_identity.upsert", "准备邮箱为 `orf-system-members-status-cancel-e2e@orf.local`、使用固定测试密码的成员管理取消停用测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.cancelUser.email", passwordFrom: "data.cancelUser.password", nameFrom: "data.cancelUser.name", saveAs: "cancelIdentity" }),
      step("Setup-9", "prisma", "db.cancel_user.upsert", "准备姓名为 \"ORF Members Status Cancel E2E\"、邮箱为 `orf-system-members-status-cancel-e2e@orf.local`、角色为 `member`、状态为 `active` 的成员管理取消停用测试用户", "db.user", "upsert", { emailFrom: "data.cancelUser.email", passwordFrom: "data.cancelUser.password", nameFrom: "data.cancelUser.name", roleFrom: "data.cancelUser.role", status: "active", identityIdFrom: "runtime.cancelIdentity.id", saveAs: "cancelUser" }),
      step("Setup-10", "api", "ory.admin_sessions.revoke", "撤销邮箱为 `orf-system-members-status-admin-e2e@orf.local` 的成员管理停用启用管理员测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.admin.email" }),
      step("Setup-11", "api", "ory.active_sessions.revoke", "撤销邮箱为 `orf-system-members-status-active-e2e@orf.local` 的成员管理待停用测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.activeUser.email" }),
      step("Setup-12", "api", "ory.disabled_sessions.revoke", "撤销邮箱为 `orf-system-members-status-disabled-e2e@orf.local` 的成员管理待启用测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.disabledUser.email" }),
      step("Setup-13", "api", "ory.cancel_sessions.revoke", "撤销邮箱为 `orf-system-members-status-cancel-e2e@orf.local` 的成员管理取消停用测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.cancelUser.email" }),
      step("Setup-14", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Setup-15", "playwright", "page.goto.auth", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Setup-16", "playwright", "fill.admin_email", "在邮箱输入框输入 `orf-system-members-status-admin-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.admin.email" }),
      step("Setup-17", "playwright", "fill.admin_password", "在密码输入框输入成员管理停用启用管理员测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.admin.password" }),
      step("Setup-18", "playwright", "click.sign_in", "点击 \"Sign In\" 登录操作", "page.login_form", "submit", { saveAs: "adminLoginResponse" }),
      step("Setup-19", "api", "session.admin_authenticated", "当前会话 应为 邮箱为 `orf-system-members-status-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
      step("Setup-20", "playwright", "page.goto.members", "打开 成员管理页面", "page", "goto", { pathFrom: "data.membersPath" }),
    ],
  },
  S0: {
    description: "管理员已登录并位于成员管理页面，目标用户状态与操作入口满足 Action 前提",
    assertions: [
      step("S0-1", "api", "session.admin_authenticated", "当前会话 应为 邮箱为 `orf-system-members-status-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
      step("S0-2", "playwright", "url.members", "当前页面 应为 成员管理页面", "page.url", "match", { pattern: "/system/members$" }),
      step("S0-3", "playwright", "members.list.active.visible", "成员管理页面的用户列表 应显示 待停用测试用户", "page.members_list", "contains_user", { emailFrom: "data.activeUser.email", nameFrom: "data.activeUser.name" }),
      step("S0-4", "playwright", "members.list.disabled.visible", "成员管理页面的用户列表 应显示 待启用测试用户", "page.members_list", "contains_user", { emailFrom: "data.disabledUser.email", nameFrom: "data.disabledUser.name" }),
      step("S0-5", "playwright", "members.list.cancel.visible", "成员管理页面的用户列表 应显示 取消停用测试用户", "page.members_list", "contains_user", { emailFrom: "data.cancelUser.email", nameFrom: "data.cancelUser.name" }),
      step("S0-6", "playwright", "active.disable.visible", "待停用测试用户列表行的 \"停用\" 操作 应可见", "page.member_row_action", "visible", { emailFrom: "data.activeUser.email", action: "停用" }),
      step("S0-7", "playwright", "active.disable.enabled", "待停用测试用户列表行的 \"停用\" 操作 应可点击", "page.member_row_action", "enabled", { emailFrom: "data.activeUser.email", action: "停用" }),
      step("S0-8", "playwright", "disabled.enable.visible", "待启用测试用户列表行的 \"启用\" 操作 应可见", "page.member_row_action", "visible", { emailFrom: "data.disabledUser.email", action: "启用" }),
      step("S0-9", "playwright", "disabled.enable.enabled", "待启用测试用户列表行的 \"启用\" 操作 应可点击", "page.member_row_action", "enabled", { emailFrom: "data.disabledUser.email", action: "启用" }),
      step("S0-10", "playwright", "cancel.disable.visible", "取消停用测试用户列表行的 \"停用\" 操作 应可见", "page.member_row_action", "visible", { emailFrom: "data.cancelUser.email", action: "停用" }),
      step("S0-11", "playwright", "cancel.disable.enabled", "取消停用测试用户列表行的 \"停用\" 操作 应可点击", "page.member_row_action", "enabled", { emailFrom: "data.cancelUser.email", action: "停用" }),
      step("S0-12", "prisma", "db.active_user.active", "邮箱为 `orf-system-members-status-active-e2e@orf.local` 的成员管理待停用测试用户状态 应为 `active`", "db.user", "matches", { emailFrom: "data.activeUser.email", roleFrom: "data.activeUser.role", status: "active" }),
      step("S0-13", "prisma", "db.disabled_user.disabled", "邮箱为 `orf-system-members-status-disabled-e2e@orf.local` 的成员管理待启用测试用户状态 应为 `disabled`", "db.user", "matches", { emailFrom: "data.disabledUser.email", roleFrom: "data.disabledUser.role", status: "disabled" }),
      step("S0-14", "prisma", "db.cancel_user.active", "邮箱为 `orf-system-members-status-cancel-e2e@orf.local` 的成员管理取消停用测试用户状态 应为 `active`", "db.user", "matches", { emailFrom: "data.cancelUser.email", roleFrom: "data.cancelUser.role", status: "active" }),
    ],
  },
  Action: {
    description: "取消停用用户、确认停用用户、确认启用用户，并验证已停用用户无法登录",
    steps: [
      step("Action-1", "playwright", "cancel.disable.click", "点击 取消停用测试用户列表行的 \"停用\" 操作", "page.member_row_action", "click_confirm", { emailFrom: "data.cancelUser.email", action: "停用", decision: "dismiss", saveAs: "cancelDisableConfirm" }),
      step("Action-2", "playwright", "cancel.disable.confirm.observe", "查看 停用用户确认弹窗", "page.confirm_snapshot", "observe", { snapshotFrom: "runtime.cancelDisableConfirm" }),
      step("Action-3", "playwright", "cancel.disable.confirm.cancel", "点击 停用用户确认弹窗的取消操作", "page.confirm_snapshot", "dismissed", { snapshotFrom: "runtime.cancelDisableConfirm" }),
      step("Action-4", "playwright", "active.disable.click", "点击 待停用测试用户列表行的 \"停用\" 操作", "page.member_row_action", "click_confirm", { emailFrom: "data.activeUser.email", action: "停用", decision: "accept", saveAs: "activeDisableConfirm" }),
      step("Action-5", "playwright", "active.disable.confirm.observe", "查看 停用用户确认弹窗", "page.confirm_snapshot", "observe", { snapshotFrom: "runtime.activeDisableConfirm" }),
      step("Action-6", "playwright", "active.disable.confirm.accept", "点击 停用用户确认弹窗的确认操作", "page.confirm_snapshot", "accepted", { snapshotFrom: "runtime.activeDisableConfirm", waitEmailFrom: "data.activeUser.email", waitStatus: "已停用" }),
      step("Action-7", "playwright", "disabled.enable.click", "点击 待启用测试用户列表行的 \"启用\" 操作", "page.member_row_action", "click_confirm", { emailFrom: "data.disabledUser.email", action: "启用", decision: "accept", saveAs: "disabledEnableConfirm" }),
      step("Action-8", "playwright", "disabled.enable.confirm.observe", "查看 启用用户确认弹窗", "page.confirm_snapshot", "observe", { snapshotFrom: "runtime.disabledEnableConfirm" }),
      step("Action-9", "playwright", "disabled.enable.confirm.accept", "点击 启用用户确认弹窗的确认操作", "page.confirm_snapshot", "accepted", { snapshotFrom: "runtime.disabledEnableConfirm", waitEmailFrom: "data.disabledUser.email", waitStatus: "启用" }),
      step("Action-10", "api", "auth.logout.admin", "注销当前管理员登录会话", "auth", "logout"),
      step("Action-11", "playwright", "browser.clear.before_disabled_login", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Action-12", "playwright", "page.goto.auth.disabled_login", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Action-13", "playwright", "fill.disabled_user_email", "在邮箱输入框输入 `orf-system-members-status-active-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.activeUser.email" }),
      step("Action-14", "playwright", "fill.disabled_user_password", "在密码输入框输入成员管理待停用测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.activeUser.password" }),
      step("Action-15", "playwright", "click.sign_in.disabled_user", "点击 \"Sign In\" 登录操作", "page.login_form", "submit_failure", { saveAs: "disabledLoginResponse" }),
    ],
  },
  S1: {
    description: "取消停用不改变状态，确认停用和确认启用正确更新状态，已停用用户登录失败",
    assertions: [
      step("S1-1", "playwright", "cancel.disable.confirm.title", "停用用户确认弹窗标题 应显示 停用用户确认信息", "page.confirm_snapshot", "message_matches", { snapshotFrom: "runtime.cancelDisableConfirm", pattern: "停用用户" }),
      step("S1-2", "playwright", "cancel.disable.confirm.user", "停用用户确认弹窗 应显示 取消停用测试用户", "page.confirm_snapshot", "contains", { snapshotFrom: "runtime.cancelDisableConfirm", textFrom: "data.cancelUser.name" }),
      step("S1-3", "playwright", "cancel.disable.confirm.hidden", "点击取消后，停用用户确认弹窗 应不可见", "page.confirm_snapshot", "dismissed", { snapshotFrom: "runtime.cancelDisableConfirm" }),
      step("S1-4", "playwright", "members.list.cancel.visible.after_cancel", "点击取消后，成员管理页面的用户列表 应显示 取消停用测试用户", "page.members_list", "contains_user", { emailFrom: "data.cancelUser.email", nameFrom: "data.cancelUser.name" }),
      step("S1-5", "prisma", "db.cancel_user.still_active", "点击取消后，邮箱为 `orf-system-members-status-cancel-e2e@orf.local` 的成员管理取消停用测试用户状态 应仍为 `active`", "db.user", "matches", { emailFrom: "data.cancelUser.email", roleFrom: "data.cancelUser.role", status: "active" }),
      step("S1-6", "playwright", "active.disable.confirm.user", "停用用户确认弹窗 应显示 待停用测试用户", "page.confirm_snapshot", "contains", { snapshotFrom: "runtime.activeDisableConfirm", textFrom: "data.activeUser.name" }),
      step("S1-7", "playwright", "members.list.active.visible.after_disable", "确认停用后，成员管理页面的用户列表 应显示 待停用测试用户", "page.members_list", "contains_user", { emailFrom: "data.activeUser.email", nameFrom: "data.activeUser.name" }),
      step("S1-8", "playwright", "active.status.disabled", "确认停用后，待停用测试用户列表行的状态 应显示为 `已停用`", "page.member_row_status", "text", { emailFrom: "data.activeUser.email", text: "已停用" }),
      step("S1-9", "playwright", "active.enable.visible", "确认停用后，待停用测试用户列表行的 \"启用\" 操作 应可见", "page.member_row_action", "visible", { emailFrom: "data.activeUser.email", action: "启用" }),
      step("S1-10", "prisma", "db.active_user.disabled", "确认停用后，邮箱为 `orf-system-members-status-active-e2e@orf.local` 的成员管理待停用测试用户状态 应为 `disabled`", "db.user", "matches", { emailFrom: "data.activeUser.email", roleFrom: "data.activeUser.role", status: "disabled" }),
      step("S1-11", "playwright", "disabled.enable.confirm.title", "启用用户确认弹窗标题 应显示 启用用户确认信息", "page.confirm_snapshot", "message_matches", { snapshotFrom: "runtime.disabledEnableConfirm", pattern: "启用用户" }),
      step("S1-12", "playwright", "disabled.enable.confirm.user", "启用用户确认弹窗 应显示 待启用测试用户", "page.confirm_snapshot", "contains", { snapshotFrom: "runtime.disabledEnableConfirm", textFrom: "data.disabledUser.name" }),
      step("S1-13", "playwright", "members.list.disabled.visible.after_enable", "确认启用后，成员管理页面的用户列表 应显示 待启用测试用户", "page.members_list", "contains_user", { emailFrom: "data.disabledUser.email", nameFrom: "data.disabledUser.name" }),
      step("S1-14", "playwright", "disabled.status.active", "确认启用后，待启用测试用户列表行的状态 应显示为 `启用`", "page.member_row_status", "text", { emailFrom: "data.disabledUser.email", text: "启用" }),
      step("S1-15", "playwright", "disabled.disable.visible.after_enable", "确认启用后，待启用测试用户列表行的 \"停用\" 操作 应可见", "page.member_row_action", "visible", { emailFrom: "data.disabledUser.email", action: "停用" }),
      step("S1-16", "prisma", "db.disabled_user.active", "确认启用后，邮箱为 `orf-system-members-status-disabled-e2e@orf.local` 的成员管理待启用测试用户状态 应为 `active`", "db.user", "matches", { emailFrom: "data.disabledUser.email", roleFrom: "data.disabledUser.role", status: "active" }),
      step("S1-17", "api", "session.unauthenticated.after_disabled_login", "使用已停用测试用户登录后，当前会话 应为 未登录", "auth.session", "unauthenticated"),
      step("S1-18", "playwright", "disabled.login.error", "使用已停用测试用户登录后，系统 应提示 账号不可用或账号密码错误", "page.login_error", "visible"),
      step("S1-19", "playwright", "disabled.login.stays.auth", "使用已停用测试用户登录后，当前页面 应停留在 ORF 登录页", "page.url", "match", { pattern: "/auth" }),
    ],
  },
  Clean: {
    description: "删除停用启用相关测试数据并恢复未登录基准状态",
    steps: [
      step("Clean-1", "api", "auth.logout", "注销当前登录会话", "auth", "logout"),
      step("Clean-2", "playwright", "page.runtime.stop", "离开当前 ORF 前端页面", "page.runtime", "stop"),
      step("Clean-3", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Clean-4", "api", "ory.admin_sessions.revoke", "撤销邮箱为 `orf-system-members-status-admin-e2e@orf.local` 的成员管理停用启用管理员测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-5", "api", "ory.active_sessions.revoke", "撤销邮箱为 `orf-system-members-status-active-e2e@orf.local` 的成员管理待停用测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.activeUser.email" }),
      step("Clean-6", "api", "ory.disabled_sessions.revoke", "撤销邮箱为 `orf-system-members-status-disabled-e2e@orf.local` 的成员管理待启用测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.disabledUser.email" }),
      step("Clean-7", "api", "ory.cancel_sessions.revoke", "撤销邮箱为 `orf-system-members-status-cancel-e2e@orf.local` 的成员管理取消停用测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.cancelUser.email" }),
      step("Clean-8", "api", "ory.admin_identity.delete", "删除邮箱为 `orf-system-members-status-admin-e2e@orf.local` 的成员管理停用启用管理员测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-9", "api", "ory.active_identity.delete", "删除邮箱为 `orf-system-members-status-active-e2e@orf.local` 的成员管理待停用测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.activeUser.email" }),
      step("Clean-10", "api", "ory.disabled_identity.delete", "删除邮箱为 `orf-system-members-status-disabled-e2e@orf.local` 的成员管理待启用测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.disabledUser.email" }),
      step("Clean-11", "api", "ory.cancel_identity.delete", "删除邮箱为 `orf-system-members-status-cancel-e2e@orf.local` 的成员管理取消停用测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.cancelUser.email" }),
      step("Clean-12", "api", "admin.preferences.default_landing_path.reset", "恢复邮箱为 `orf-system-members-status-admin-e2e@orf.local` 的默认进入页面为 系统默认", "user.preferences", "reset_default_landing_path_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-13", "prisma", "db.admin_user.memberships.delete", "删除邮箱为 `orf-system-members-status-admin-e2e@orf.local` 的成员管理停用启用管理员测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.admin.email" }),
      step("Clean-14", "prisma", "db.active_user.memberships.delete", "删除邮箱为 `orf-system-members-status-active-e2e@orf.local` 的成员管理待停用测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.activeUser.email" }),
      step("Clean-15", "prisma", "db.disabled_user.memberships.delete", "删除邮箱为 `orf-system-members-status-disabled-e2e@orf.local` 的成员管理待启用测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.disabledUser.email" }),
      step("Clean-16", "prisma", "db.cancel_user.memberships.delete", "删除邮箱为 `orf-system-members-status-cancel-e2e@orf.local` 的成员管理取消停用测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.cancelUser.email" }),
      step("Clean-17", "prisma", "db.admin_user.delete", "删除邮箱为 `orf-system-members-status-admin-e2e@orf.local` 的成员管理停用启用管理员测试用户", "db.user", "delete", { emailFrom: "data.admin.email" }),
      step("Clean-18", "prisma", "db.active_user.delete", "删除邮箱为 `orf-system-members-status-active-e2e@orf.local` 的成员管理待停用测试用户", "db.user", "delete", { emailFrom: "data.activeUser.email" }),
      step("Clean-19", "prisma", "db.disabled_user.delete", "删除邮箱为 `orf-system-members-status-disabled-e2e@orf.local` 的成员管理待启用测试用户", "db.user", "delete", { emailFrom: "data.disabledUser.email" }),
      step("Clean-20", "prisma", "db.cancel_user.delete", "删除邮箱为 `orf-system-members-status-cancel-e2e@orf.local` 的成员管理取消停用测试用户", "db.user", "delete", { emailFrom: "data.cancelUser.email" }),
      step("Clean-21", "api", "ory.admin_identity.absent", "邮箱为 `orf-system-members-status-admin-e2e@orf.local` 的成员管理停用启用管理员测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.admin.email" }),
      step("Clean-22", "api", "ory.active_identity.absent", "邮箱为 `orf-system-members-status-active-e2e@orf.local` 的成员管理待停用测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.activeUser.email" }),
      step("Clean-23", "api", "ory.disabled_identity.absent", "邮箱为 `orf-system-members-status-disabled-e2e@orf.local` 的成员管理待启用测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.disabledUser.email" }),
      step("Clean-24", "api", "ory.cancel_identity.absent", "邮箱为 `orf-system-members-status-cancel-e2e@orf.local` 的成员管理取消停用测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.cancelUser.email" }),
      step("Clean-25", "prisma", "db.admin_user.absent", "邮箱为 `orf-system-members-status-admin-e2e@orf.local` 的成员管理停用启用管理员测试用户 应不存在", "db.user", "absent", { emailFrom: "data.admin.email" }),
      step("Clean-26", "prisma", "db.active_user.absent", "邮箱为 `orf-system-members-status-active-e2e@orf.local` 的成员管理待停用测试用户 应不存在", "db.user", "absent", { emailFrom: "data.activeUser.email" }),
      step("Clean-27", "prisma", "db.disabled_user.absent", "邮箱为 `orf-system-members-status-disabled-e2e@orf.local` 的成员管理待启用测试用户 应不存在", "db.user", "absent", { emailFrom: "data.disabledUser.email" }),
      step("Clean-28", "prisma", "db.cancel_user.absent", "邮箱为 `orf-system-members-status-cancel-e2e@orf.local` 的成员管理取消停用测试用户 应不存在", "db.user", "absent", { emailFrom: "data.cancelUser.email" }),
    ],
  },
} satisfies StateCaseSpec<SystemMembersStatusCaseData>;
