import { STATE_CASE_MODEL, type StateCaseSpec, type StepExecutionMethod, type StepSpec } from "../../_framework/types";
import type { GlobalSearchCaseData } from "./_support/global-search.context";

function step(
  caseStepId: string,
  method: StepExecutionMethod,
  id: string,
  title: string,
  object: string,
  operator: string,
  params?: Record<string, unknown>,
): StepSpec {
  return {
    source: { caseStepId, method },
    id,
    title,
    object,
    operator,
    ...(params ? { params } : {}),
  };
}

export const globalSearchCase = {
  id: "defaults.global-search.typed-results",
  title: "04-首页全局搜索展示分类结果",
  model: STATE_CASE_MODEL,
  tags: ["defaults", "global-search", "typed-results"],
  data: {
    email: "orf-default-page-search-e2e@orf.local",
    password: "OrfDefaultPageSearchE2E!2026",
    name: "ORF Default Page Search E2E",
    role: "admin",
    defaultLandingPath: "/bounties",
    homePath: "/dashboard",
    pageKeyword: "反馈",
    fixtureKeyword: "ORF全局搜索E2E",
    objective: {
      id: "testd-default-global-search-objective",
      title: "ORF全局搜索E2E 目标",
    },
    result: {
      id: "testd-default-global-search-result",
      title: "ORF全局搜索E2E 指标",
    },
    task: {
      id: "testd-default-global-search-task",
      title: "ORF全局搜索E2E 行动项",
    },
    feedback: {
      id: "testd-default-global-search-feedback",
      phenomenon: "ORF全局搜索E2E 反馈现象",
    },
  },
  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      step("B-1", "api", "frontend.ready", "前端服务 应可用", "frontend.service", "available"),
      step("B-2", "api", "backend.ready", "后端服务 应可用", "api.health", "ok"),
      step("B-3", "api", "frontend.login_entry.accessible", "前端登录页入口 应可访问", "frontend.login_entry", "accessible"),
      step("B-4", "api", "session.endpoint.accessible", "当前会话查询能力 应可用", "auth.session", "accessible"),
      step("B-5", "prisma", "db.ready", "ORF 数据库 应可连接", "db", "ready"),
      step("B-6", "prisma", "db.schema.current", "ORF 数据库 schema 应为 当前测试版本", "db.schema", "current"),
      step("B-7", "api", "ory.admin_public.ready", "Ory/Kratos 认证服务的管理和公共访问能力 应可用", "ory.admin_public", "ready"),
      step("B-8", "api", "session.unauthenticated", "当前会话 应为 未登录", "auth.session", "unauthenticated"),
      step("B-9", "playwright", "cookie.absent", "当前浏览器 应不存在 Ory 登录会话 cookie", "browser.cookie", "absent"),
      step("B-10", "playwright", "storage.empty", "当前浏览器 应不保留本地登录态", "browser.auth_storage", "empty"),
    ],
  },
  Setup: {
    description: "准备管理员测试用户和可被全局搜索命中的目标、指标、行动项、反馈",
    steps: [
      step("Setup-1", "api", "ory.identity.upsert", "准备邮箱为 `orf-default-page-search-e2e@orf.local`、使用固定测试密码的默认系统页全局搜索测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.email", passwordFrom: "data.password", nameFrom: "data.name", saveAs: "identity" }),
      step("Setup-2", "prisma", "db.user.upsert", "准备邮箱为 `orf-default-page-search-e2e@orf.local`、角色为 `admin`、状态为 `active` 的默认系统页全局搜索测试用户", "db.user", "upsert", { emailFrom: "data.email", passwordFrom: "data.password", nameFrom: "data.name", roleFrom: "data.role", status: "active", identityIdFrom: "runtime.identity.id", saveAs: "user" }),
      step("Setup-3", "api", "preferences.default_landing_path.set", "设置默认系统页全局搜索测试用户默认进入页面为 首页（默认系统页）", "user.preferences", "set_default_landing_path_by_email", { emailFrom: "data.email", pathFrom: "data.defaultLandingPath" }),
      step("Setup-4", "prisma", "db.search_objective.prepare", "准备标题包含 `ORF全局搜索E2E` 的全局搜索测试目标", "db.search_objective", "prepare"),
      step("Setup-5", "prisma", "db.search_result.prepare", "准备标题包含 `ORF全局搜索E2E` 且属于全局搜索测试目标的全局搜索测试指标", "db.search_result", "prepare"),
      step("Setup-6", "prisma", "db.search_task.prepare", "准备标题包含 `ORF全局搜索E2E` 且属于全局搜索测试目标的全局搜索测试任务", "db.search_task", "prepare"),
      step("Setup-7", "prisma", "db.search_feedback.prepare", "准备现象包含 `ORF全局搜索E2E` 的全局搜索测试反馈", "db.search_feedback", "prepare"),
      step("Setup-8", "api", "ory.sessions.revoke", "撤销邮箱为 `orf-default-page-search-e2e@orf.local` 的默认系统页全局搜索测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.email" }),
      step("Setup-9", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Setup-10", "playwright", "page.goto.auth", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Setup-11", "playwright", "fill.email", "在邮箱输入框输入 `orf-default-page-search-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.email" }),
      step("Setup-12", "playwright", "fill.password", "在密码输入框输入默认系统页全局搜索测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.password" }),
      step("Setup-13", "playwright", "click.sign_in", "点击 \"Sign In\" 登录操作", "page.login_form", "submit", { saveAs: "loginResponse" }),
      step("Setup-14", "api", "session.authenticated", "当前会话 应为 邮箱为 `orf-default-page-search-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.email", roleFrom: "data.role", status: "active" }),
      step("Setup-15", "playwright", "page.goto.home", "打开 首页（默认系统页）", "page", "goto", { pathFrom: "data.homePath" }),
    ],
  },
  S0: {
    description: "管理员已登录并位于首页，搜索入口和测试数据均已准备好",
    assertions: [
      step("S0-1", "api", "session.authenticated", "当前会话 应为 邮箱为 `orf-default-page-search-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.email", roleFrom: "data.role", status: "active" }),
      step("S0-2", "playwright", "url.home", "当前页面 应为 首页（默认系统页）", "page.url", "match", { pattern: "/dashboard$" }),
      step("S0-3", "playwright", "topbar.search.visible", "顶部导航栏的全局搜索入口 应可见", "topbar.global_search", "visible"),
      step("S0-4", "playwright", "topbar.search.enabled", "顶部导航栏的全局搜索入口 应可点击", "topbar.global_search", "enabled"),
      step("S0-5", "prisma", "db.search_objective.exists", "标题包含 `ORF全局搜索E2E` 的全局搜索测试目标 应存在", "db.search_objective", "exists", { keywordFrom: "data.fixtureKeyword" }),
      step("S0-6", "prisma", "db.search_result.exists", "标题包含 `ORF全局搜索E2E` 的全局搜索测试指标 应存在", "db.search_result", "exists", { keywordFrom: "data.fixtureKeyword" }),
      step("S0-7", "prisma", "db.search_task.exists", "标题包含 `ORF全局搜索E2E` 的全局搜索测试任务 应存在", "db.search_task", "exists", { keywordFrom: "data.fixtureKeyword" }),
      step("S0-8", "prisma", "db.search_feedback.exists", "现象包含 `ORF全局搜索E2E` 的全局搜索测试反馈 应存在", "db.search_feedback", "exists", { keywordFrom: "data.fixtureKeyword" }),
    ],
  },
  Action: {
    description: "打开全局搜索，先验证固定页面结果，再验证业务数据分类结果",
    steps: [
      step("Action-1", "playwright", "topbar.search.click", "点击 顶部导航栏的全局搜索入口", "topbar.global_search", "click"),
      step("Action-2", "playwright", "global_search.dialog.visible", "全局搜索弹窗 应可见", "global_search.dialog", "visible"),
      step("Action-3", "playwright", "global_search.input.fill_page_keyword", "在全局搜索输入框输入 `反馈`", "global_search.input", "fill", { valueFrom: "data.pageKeyword", snapshotLabelFrom: "data.pageKeyword", snapshotTypeLabel: "页面", saveAs: "pageResultSnapshot" }),
      step("Action-4", "playwright", "global_search.input.clear", "清空 全局搜索输入框", "global_search.input", "clear"),
      step("Action-5", "playwright", "global_search.input.fill_fixture_keyword", "在全局搜索输入框输入 `ORF全局搜索E2E`", "global_search.input", "fill", { valueFrom: "data.fixtureKeyword" }),
    ],
  },
  S1: {
    description: "搜索结果按页面、目标、指标、行动项、反馈类型展示",
    assertions: [
      step("S1-1", "playwright", "global_search.results.visible", "全局搜索结果列表 应可见", "global_search.results", "visible"),
      step("S1-2", "playwright", "global_search.page_result.visible", "全局搜索结果列表 应显示 页面类型的 `反馈` 匹配结果", "global_search.result_snapshot", "visible", { snapshotFrom: "runtime.pageResultSnapshot" }),
      step("S1-3", "playwright", "global_search.objective_result.visible", "全局搜索结果列表 应显示 目标类型的 `ORF全局搜索E2E` 匹配结果", "global_search.result", "visible", { labelFrom: "data.objective.title", typeLabel: "目标" }),
      step("S1-4", "playwright", "global_search.metric_result.visible", "全局搜索结果列表 应显示 指标类型的 `ORF全局搜索E2E` 匹配结果", "global_search.result", "visible", { labelFrom: "data.result.title", typeLabel: "指标" }),
      step("S1-5", "playwright", "global_search.task_result.visible", "全局搜索结果列表 应显示 任务类型的 `ORF全局搜索E2E` 匹配结果", "global_search.result", "visible", { labelFrom: "data.task.title", typeLabel: "行动项" }),
      step("S1-6", "playwright", "global_search.feedback_result.visible", "全局搜索结果列表 应显示 反馈类型的 `ORF全局搜索E2E` 匹配结果", "global_search.result", "visible", { labelFrom: "data.feedback.phenomenon", typeLabel: "反馈" }),
      step("S1-7", "playwright", "global_search.page_type.visible", "全局搜索结果列表中的 `反馈` 页面匹配结果 应显示 页面类型标签", "global_search.result_snapshot", "type_label_visible", { snapshotFrom: "runtime.pageResultSnapshot", typeLabel: "页面" }),
      step("S1-8", "playwright", "global_search.objective_type.visible", "全局搜索结果列表中的目标匹配结果 应显示 目标类型标签", "global_search.result_type", "visible", { labelFrom: "data.objective.title", typeLabel: "目标" }),
      step("S1-9", "playwright", "global_search.metric_type.visible", "全局搜索结果列表中的指标匹配结果 应显示 指标类型标签", "global_search.result_type", "visible", { labelFrom: "data.result.title", typeLabel: "指标" }),
      step("S1-10", "playwright", "global_search.task_type.visible", "全局搜索结果列表中的任务匹配结果 应显示 任务类型标签", "global_search.result_type", "visible", { labelFrom: "data.task.title", typeLabel: "行动项" }),
      step("S1-11", "playwright", "global_search.feedback_type.visible", "全局搜索结果列表中的反馈匹配结果 应显示 反馈类型标签", "global_search.result_type", "visible", { labelFrom: "data.feedback.phenomenon", typeLabel: "反馈" }),
      step("S1-12", "api", "session.authenticated.after_search", "当前会话 应仍为 邮箱为 `orf-default-page-search-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.email", roleFrom: "data.role", status: "active" }),
    ],
  },
  Clean: {
    description: "删除全局搜索夹具、测试用户和认证身份，恢复未登录基准状态",
    steps: [
      step("Clean-1", "api", "auth.logout", "注销当前登录会话", "auth", "logout"),
      step("Clean-2", "playwright", "page.runtime.stop", "离开当前 ORF 前端页面", "page.runtime", "stop"),
      step("Clean-3", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Clean-4", "api", "ory.sessions.revoke", "撤销邮箱为 `orf-default-page-search-e2e@orf.local` 的默认系统页全局搜索测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.email" }),
      step("Clean-5", "api", "ory.identity.delete", "删除邮箱为 `orf-default-page-search-e2e@orf.local` 的默认系统页全局搜索测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.email" }),
      step("Clean-6", "api", "preferences.default_landing_path.reset", "恢复邮箱为 `orf-default-page-search-e2e@orf.local` 的默认进入页面为 系统默认", "user.preferences", "reset_default_landing_path_by_email", { emailFrom: "data.email" }),
      step("Clean-7", "prisma", "db.search_feedback.delete", "删除现象包含 `ORF全局搜索E2E` 的全局搜索测试反馈", "db.search_feedback", "delete", { keywordFrom: "data.fixtureKeyword" }),
      step("Clean-8", "prisma", "db.search_task.delete", "删除标题包含 `ORF全局搜索E2E` 的全局搜索测试任务", "db.search_task", "delete", { keywordFrom: "data.fixtureKeyword" }),
      step("Clean-9", "prisma", "db.search_result.delete", "删除标题包含 `ORF全局搜索E2E` 的全局搜索测试指标", "db.search_result", "delete", { keywordFrom: "data.fixtureKeyword" }),
      step("Clean-10", "prisma", "db.search_objective.delete", "删除标题包含 `ORF全局搜索E2E` 的全局搜索测试目标", "db.search_objective", "delete", { keywordFrom: "data.fixtureKeyword" }),
      step("Clean-11", "prisma", "db.user.memberships.delete", "删除邮箱为 `orf-default-page-search-e2e@orf.local` 的默认系统页全局搜索测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.email" }),
      step("Clean-12", "prisma", "db.user.delete", "删除邮箱为 `orf-default-page-search-e2e@orf.local` 的默认系统页全局搜索测试用户", "db.user", "delete", { emailFrom: "data.email" }),
      step("Clean-13", "api", "ory.identity.absent", "邮箱为 `orf-default-page-search-e2e@orf.local` 的默认系统页全局搜索测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.email" }),
      step("Clean-14", "prisma", "db.user.absent", "邮箱为 `orf-default-page-search-e2e@orf.local` 的默认系统页全局搜索测试用户 应不存在", "db.user", "absent", { emailFrom: "data.email" }),
      step("Clean-15", "prisma", "db.search_objective.absent", "标题包含 `ORF全局搜索E2E` 的全局搜索测试目标 应不存在", "db.search_objective", "absent", { keywordFrom: "data.fixtureKeyword" }),
      step("Clean-16", "prisma", "db.search_result.absent", "标题包含 `ORF全局搜索E2E` 的全局搜索测试指标 应不存在", "db.search_result", "absent", { keywordFrom: "data.fixtureKeyword" }),
      step("Clean-17", "prisma", "db.search_task.absent", "标题包含 `ORF全局搜索E2E` 的全局搜索测试任务 应不存在", "db.search_task", "absent", { keywordFrom: "data.fixtureKeyword" }),
      step("Clean-18", "prisma", "db.search_feedback.absent", "现象包含 `ORF全局搜索E2E` 的全局搜索测试反馈 应不存在", "db.search_feedback", "absent", { keywordFrom: "data.fixtureKeyword" }),
    ],
  },
} satisfies StateCaseSpec<GlobalSearchCaseData>;
