import { STATE_CASE_MODEL, type StateCaseSpec } from "../../_framework/types";
import type { ViewFinalScoreCaseData } from "./_support/view-final-score.context";

export const viewFinalScoreCase = {
  id: "acceptance.view-final-score",
  title: "查看最终分数",
  model: STATE_CASE_MODEL,
  tags: ["acceptance", "final-score", "member", "happy-path"],

  data: {
    email: "orf-member-view-final-score-e2e@orf.local",
    password: "OrfMemberViewFinalScoreE2E!2026",
    name: "ORF Member View Final Score E2E",
    role: "member",
    objectiveId: "obj-testd-view-final-score",
    objectiveTitle: "E2E-VIEW-FINAL-SCORE: 目标前置",
    points: 42,
    reason: "E2E-FINAL-SCORE: 查看最终分数",
  },

  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      {
        source: { caseStepId: "B-1", method: "api" },
        id: "frontend.ready",
        title: "前端服务 应可用",
        object: "frontend.service",
        operator: "available",
      },
      {
        source: { caseStepId: "B-2", method: "api" },
        id: "backend.ready",
        title: "后端服务 应可用",
        object: "api.health",
        operator: "ok",
      },
      {
        source: { caseStepId: "B-3", method: "api" },
        id: "frontend.login_entry.accessible",
        title: "前端登录页入口 应可访问",
        object: "frontend.login_entry",
        operator: "accessible",
      },
      {
        source: { caseStepId: "B-4", method: "api" },
        id: "session.endpoint.accessible",
        title: "当前会话查询接口 应可访问",
        object: "auth.session",
        operator: "accessible",
      },
      {
        source: { caseStepId: "B-5", method: "prisma" },
        id: "db.ready",
        title: "ORF 数据库 应可连接",
        object: "db",
        operator: "ready",
      },
      {
        source: { caseStepId: "B-6", method: "prisma" },
        id: "db.schema.current",
        title: "ORF 数据库 schema 应为 当前测试版本",
        object: "db.schema",
        operator: "current",
      },
      {
        source: { caseStepId: "B-7", method: "api" },
        id: "ory.admin_public.ready",
        title: "Ory/Kratos Admin/Public API 应可访问",
        object: "ory.admin_public",
        operator: "ready",
      },
      {
        source: { caseStepId: "B-8", method: "api" },
        id: "session.unauthenticated",
        title: "当前会话 应为 未登录",
        object: "auth.session",
        operator: "unauthenticated",
      },
      {
        source: { caseStepId: "B-9", method: "playwright" },
        id: "cookie.absent",
        title: "当前浏览器 应不存在 Ory session cookie",
        object: "browser.cookie",
        operator: "absent",
      },
      {
        source: { caseStepId: "B-10", method: "playwright" },
        id: "storage.empty",
        title: "当前浏览器 storage 应不包含 登录态",
        object: "browser.auth_storage",
        operator: "empty",
      },
    ],
  },

  Setup: {
    description: "准备普通成员账号、本用例独占 settled 目标和积分流水，登录普通成员",
    steps: [
      {
        source: { caseStepId: "Setup-1", method: "prisma" },
        id: "db.final_score_ledger.delete_residue",
        title: "删除可能残留的测试积分流水",
        object: "db.final_score_ledger",
        operator: "delete",
        params: { reasonFrom: "data.reason" },
      },
      {
        source: { caseStepId: "Setup-2", method: "prisma" },
        id: "db.objective.delete_residue",
        title: "删除可能残留的本用例目标及其派生数据",
        object: "db.objective",
        operator: "delete_by_title",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Setup-3", method: "api" },
        id: "ory.member_identity.upsert",
        title: '准备邮箱为 "orf-member-view-final-score-e2e@orf.local" 的普通成员登录身份，并设置固定测试密码',
        object: "ory.identity",
        operator: "upsert_password",
        params: {
          emailFrom: "data.email",
          nameFrom: "data.name",
          passwordFrom: "data.password",
          saveAs: "memberIdentity",
        },
      },
      {
        source: { caseStepId: "Setup-4", method: "prisma" },
        id: "db.member.upsert",
        title: '准备邮箱为 "orf-member-view-final-score-e2e@orf.local"、角色为 member、状态为 active 的普通成员用户和默认团队成员关系',
        object: "db.user",
        operator: "upsert",
        params: {
          emailFrom: "data.email",
          nameFrom: "data.name",
          roleFrom: "data.role",
          status: "active",
          identityIdFrom: "runtime.memberIdentity.id",
          saveAs: "memberUser",
        },
      },
      {
        source: { caseStepId: "Setup-5", method: "prisma" },
        id: "db.objective.upsert_final_score_target",
        title: '创建标题为 "E2E-VIEW-FINAL-SCORE: 目标前置" 的本用例独占目标',
        object: "db.objective",
        operator: "upsert",
        params: {
          idFrom: "data.objectiveId",
          titleFrom: "data.objectiveTitle",
          teamIdFrom: "runtime.memberUser.teamId",
          stage: "goalFrozen",
          flowStatus: "settled",
          status: "Draft",
          saveAs: "fixtureObjective",
        },
      },
      {
        source: { caseStepId: "Setup-6", method: "prisma" },
        id: "db.final_score_target.from_objective",
        title: "记录本用例独占目标为 runtime.finalScoreTarget",
        object: "db.final_score_target",
        operator: "from_objective",
        params: { objectiveIdFrom: "runtime.fixtureObjective.id", saveAs: "finalScoreTarget" },
      },
      {
        source: { caseStepId: "Setup-7", method: "prisma" },
        id: "db.final_score_target.prepare",
        title: "设置本用例目标为 settled，挑战者包含普通成员，目标结算积分为 42",
        object: "db.final_score_target",
        operator: "prepare",
        params: { targetFrom: "runtime.finalScoreTarget", memberNameFrom: "data.name", pointsFrom: "data.points" },
      },
      {
        source: { caseStepId: "Setup-8", method: "prisma" },
        id: "db.final_score_ledger.create",
        title: "创建普通成员对本用例目标的测试积分流水，积分为 42",
        object: "db.final_score_ledger",
        operator: "create",
        params: {
          targetFrom: "runtime.finalScoreTarget",
          userIdFrom: "runtime.memberUser.userId",
          memberNameFrom: "data.name",
          pointsFrom: "data.points",
          reasonFrom: "data.reason",
          saveAs: "finalScoreLedger",
        },
      },
      {
        source: { caseStepId: "Setup-9", method: "api" },
        id: "ory.member_sessions.revoke",
        title: "撤销普通成员登录身份可能残留的 Ory session",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Setup-10", method: "playwright" },
        id: "browser.clear",
        title: "清空当前浏览器上下文的 cookies/localStorage/sessionStorage",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "Setup-11", method: "playwright" },
        id: "page.goto.auth",
        title: "打开 登录页",
        object: "page",
        operator: "goto",
        params: { path: "/auth" },
      },
      {
        source: { caseStepId: "Setup-12", method: "playwright" },
        id: "fill.email",
        title: "在邮箱输入框输入普通成员测试邮箱",
        object: "page",
        operator: "fill",
        params: { label: "Email", valueFrom: "data.email" },
      },
      {
        source: { caseStepId: "Setup-13", method: "playwright" },
        id: "fill.password",
        title: "在密码输入框输入普通成员测试密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.password" },
      },
      {
        source: { caseStepId: "Setup-14", method: "playwright" },
        id: "click.sign_in",
        title: '点击 "Sign In" 登录操作',
        object: "page",
        operator: "click",
        params: { role: "button", name: "Sign In" },
      },
      {
        source: { caseStepId: "Setup-15", method: "api" },
        id: "session.member.authenticated",
        title: "当前会话 应为 普通成员已登录",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
    ],
  },

  S0: {
    description: "普通成员已登录，目标已结算且积分流水存在",
    assertions: [
      {
        source: { caseStepId: "S0-1", method: "api" },
        id: "session.member.authenticated",
        title: '当前会话 应为 邮箱为 "orf-member-view-final-score-e2e@orf.local"、角色为 member、状态为 active 的已登录会话',
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      {
        source: { caseStepId: "S0-2", method: "prisma" },
        id: "db.final_score_target.settled_for_member",
        title: "本用例目标 应为 settled 且挑战者包含普通成员",
        object: "db.final_score_target",
        operator: "settled_for_member",
        params: { targetFrom: "runtime.finalScoreTarget", memberNameFrom: "data.name" },
      },
      {
        source: { caseStepId: "S0-3", method: "prisma" },
        id: "db.final_score_ledger.present",
        title: "数据库中 应存在 普通成员对本用例目标的测试积分流水，积分为 42",
        object: "db.final_score_ledger",
        operator: "present",
        params: { targetFrom: "runtime.finalScoreTarget", memberNameFrom: "data.name", pointsFrom: "data.points" },
      },
    ],
  },

  Action: {
    description: "普通成员打开统计页面查看最终分数",
    steps: [
      {
        source: { caseStepId: "Action-1", method: "playwright" },
        id: "page.goto.reports",
        title: "打开 统计页面",
        object: "page",
        operator: "goto",
        params: { path: "/reports" },
      },
      {
        source: { caseStepId: "Action-2", method: "playwright" },
        id: "click.all_time",
        title: '点击 "全部时间" 时间范围操作',
        object: "page",
        operator: "click",
        params: { role: "button", name: "全部时间" },
      },
    ],
  },

  S1: {
    description: "统计页面展示普通成员最终分数，数据库积分流水保持一致",
    assertions: [
      {
        source: { caseStepId: "S1-1", method: "playwright" },
        id: "url.reports",
        title: "当前页面 应为 统计页面",
        object: "page.url",
        operator: "match",
        params: { pattern: "/reports$" },
      },
      {
        source: { caseStepId: "S1-2", method: "playwright" },
        id: "page.final_score.visible",
        title: "成员积分排行榜 应显示普通成员和最终积分 42.0",
        object: "page.final_score",
        operator: "visible",
        params: { memberNameFrom: "data.name", pointsFrom: "data.points" },
      },
      {
        source: { caseStepId: "S1-3", method: "prisma" },
        id: "db.final_score_ledger.present",
        title: "数据库中 普通成员对本用例目标的测试积分流水 应保持为 42",
        object: "db.final_score_ledger",
        operator: "present",
        params: { targetFrom: "runtime.finalScoreTarget", memberNameFrom: "data.name", pointsFrom: "data.points" },
      },
      {
        source: { caseStepId: "S1-4", method: "api" },
        id: "session.member.still_authenticated",
        title: "当前会话 应仍为 普通成员已登录",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
    ],
  },

  Clean: {
    description: "删除本用例创建的积分流水、目标、普通成员账号和页面会话状态",
    steps: [
      {
        source: { caseStepId: "Clean-1", method: "prisma" },
        id: "db.final_score_ledger.delete",
        title: "删除本用例创建的测试积分流水",
        object: "db.final_score_ledger",
        operator: "delete",
        params: { reasonFrom: "data.reason", ledgerFrom: "runtime.finalScoreLedger" },
      },
      {
        source: { caseStepId: "Clean-2", method: "prisma" },
        id: "db.objective.delete",
        title: "删除本用例独占目标及其派生数据",
        object: "db.objective",
        operator: "delete",
        params: { idFrom: "data.objectiveId", titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Clean-3", method: "api" },
        id: "auth.logout",
        title: "退出当前登录态",
        object: "auth",
        operator: "logout",
      },
      {
        source: { caseStepId: "Clean-4", method: "playwright" },
        id: "page.runtime.stop",
        title: "停止当前页面运行态",
        object: "page.runtime",
        operator: "stop",
      },
      {
        source: { caseStepId: "Clean-5", method: "playwright" },
        id: "browser.clear",
        title: "清空当前浏览器上下文的 cookies/localStorage/sessionStorage",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "Clean-6", method: "api" },
        id: "ory.member_sessions.revoke",
        title: "撤销普通成员登录身份的 Ory session",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-7", method: "api" },
        id: "ory.member_identity.delete",
        title: "删除普通成员 Ory 身份",
        object: "ory.identity",
        operator: "delete_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-8", method: "prisma" },
        id: "db.member.delete_memberships",
        title: "删除普通成员默认团队成员关系",
        object: "db.user",
        operator: "delete_memberships",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-9", method: "prisma" },
        id: "db.member.delete",
        title: "删除普通成员用户",
        object: "db.user",
        operator: "delete",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-10", method: "prisma" },
        id: "db.final_score_ledger.absent",
        title: "测试积分流水 应不存在",
        object: "db.final_score_ledger",
        operator: "absent",
        params: { reasonFrom: "data.reason" },
      },
      {
        source: { caseStepId: "Clean-11", method: "prisma" },
        id: "db.objective.absent",
        title: "本用例目标 应不存在",
        object: "db.objective",
        operator: "absent",
        params: { idFrom: "data.objectiveId", titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Clean-12", method: "prisma" },
        id: "db.member.absent",
        title: "普通成员用户 应不存在",
        object: "db.user",
        operator: "absent",
        params: { emailFrom: "data.email" },
      },
    ],
  },
} satisfies StateCaseSpec<ViewFinalScoreCaseData>;
