import { STATE_CASE_MODEL, type StateCaseSpec, type StepExecutionMethod, type StepSpec } from "../../_framework/types";
import type { FeedbackFixture, FeedbackListFilterCaseData } from "./_support/feedback-list-filter.context";

function step(caseStepId: string, method: StepExecutionMethod, id: string, title: string, object: string, operator: string, params?: Record<string, unknown>): StepSpec {
  return { source: { caseStepId, method }, id, title, object, operator, ...(params ? { params } : {}) };
}

const fixtureRows: FeedbackFixture[] = [
  { id: "testd-feedback-filter-technical-open", phenomenon: "ORF反馈筛选E2E-技术问题-Open", category: "技术问题", status: "Open" },
  { id: "testd-feedback-filter-technical-closed", phenomenon: "ORF反馈筛选E2E-技术问题-Closed", category: "技术问题", status: "Closed" },
  { id: "testd-feedback-filter-management-open", phenomenon: "ORF反馈筛选E2E-管理问题-Open", category: "管理问题", status: "Open" },
  { id: "testd-feedback-filter-management-closed", phenomenon: "ORF反馈筛选E2E-管理问题-Closed", category: "管理问题", status: "Closed" },
  { id: "testd-feedback-filter-process-open", phenomenon: "ORF反馈筛选E2E-流程问题-Open", category: "流程问题", status: "Open" },
  { id: "testd-feedback-filter-process-closed", phenomenon: "ORF反馈筛选E2E-流程问题-Closed", category: "流程问题", status: "Closed" },
  { id: "testd-feedback-filter-permission-open", phenomenon: "ORF反馈筛选E2E-权限问题-Open", category: "权限问题", status: "Open" },
  { id: "testd-feedback-filter-permission-closed", phenomenon: "ORF反馈筛选E2E-权限问题-Closed", category: "权限问题", status: "Closed" },
  { id: "testd-feedback-filter-experience-open", phenomenon: "ORF反馈筛选E2E-体验问题-Open", category: "体验问题", status: "Open" },
  { id: "testd-feedback-filter-experience-closed", phenomenon: "ORF反馈筛选E2E-体验问题-Closed", category: "体验问题", status: "Closed" },
];

const phenomenaFor = (category: string) => fixtureRows.filter((item) => item.category === category).map((item) => item.phenomenon);
const excludesFor = (category: string) => fixtureRows.filter((item) => item.category !== category).map((item) => item.phenomenon);

export const feedbackListFilterCase = {
  id: "feedback.list.search-filter-reset",
  title: "01-反馈列表搜索分类与重置",
  model: STATE_CASE_MODEL,
  tags: ["feedback", "list", "search", "filter", "reset"],
  data: {
    email: "orf-feedback-filter-e2e@orf.local",
    password: "OrfFeedbackFilterE2E!2026",
    name: "ORF Feedback Filter E2E",
    role: "admin",
    feedbackPath: "/feedback",
    missingKeyword: "ORF反馈筛选不存在E2E",
    existingKeyword: "ORF反馈筛选E2E-技术问题-Open",
    fixtureRows,
    openPhenomena: fixtureRows.filter((item) => item.status === "Open").map((item) => item.phenomenon),
    closedPhenomena: fixtureRows.filter((item) => item.status === "Closed").map((item) => item.phenomenon),
    allPhenomena: fixtureRows.map((item) => item.phenomenon),
    technicalPhenomena: phenomenaFor("技术问题"), technicalExcludedPhenomena: excludesFor("技术问题"),
    managementPhenomena: phenomenaFor("管理问题"), managementExcludedPhenomena: excludesFor("管理问题"),
    processPhenomena: phenomenaFor("流程问题"), processExcludedPhenomena: excludesFor("流程问题"),
    permissionPhenomena: phenomenaFor("权限问题"), permissionExcludedPhenomena: excludesFor("权限问题"),
    experiencePhenomena: phenomenaFor("体验问题"), experienceExcludedPhenomena: excludesFor("体验问题"),
    technicalOpenPhenomenon: "ORF反馈筛选E2E-技术问题-Open",
    technicalClosedPhenomenon: "ORF反馈筛选E2E-技术问题-Closed",
  },
  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      step("B-1", "api", "frontend.ready", "前端服务 应可用", "frontend.service", "available"),
      step("B-2", "api", "backend.ready", "后端服务 应可用", "api.health", "ok"),
      step("B-3", "api", "frontend.login_entry.accessible", "前端登录页入口 应可访问", "frontend.login_entry", "accessible"),
      step("B-4", "api", "session.endpoint.accessible", "当前会话查询能力 应可用", "auth.session", "accessible"),
      step("B-5", "prisma", "db.ready", "ORF 数据库 应可连接", "db", "ready"),
      step("B-6", "prisma", "db.schema.current", "ORF 数据库 schema 应为 当前测试版本", "db.schema", "current"),
      step("B-7", "api", "ory.admin_public.ready", "Ory/Kratos 认证服务的管理和公共访问能力 应可用", "ory.admin_public", "ready"),
      step("B-8", "api", "session.unauthenticated", "当前会话 应为 未登录", "auth.session", "unauthenticated"),
      step("B-9", "playwright", "cookie.absent", "当前浏览器 应不存在 Ory 登录会话 cookie", "browser.cookie", "absent"),
      step("B-10", "playwright", "storage.empty", "当前浏览器 应不保留本地登录态", "browser.auth_storage", "empty"),
    ],
  },
  Setup: {
    description: "准备管理员测试用户和十条独占反馈 issue，登录后打开反馈页面",
    steps: [
      step("Setup-1", "prisma", "db.feedback_filter_fixtures.delete_residue", "删除现象以 `ORF反馈筛选E2E-` 开头的残留反馈 issue 及其分类记录", "db.feedback_filter_fixtures", "delete", { fixturesFrom: "data.fixtureRows" }),
      step("Setup-2", "api", "ory.identity.upsert", "准备邮箱为 `orf-feedback-filter-e2e@orf.local`、使用固定测试密码的反馈列表筛选测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.email", passwordFrom: "data.password", nameFrom: "data.name", saveAs: "identity" }),
      step("Setup-3", "prisma", "db.user.upsert", "准备邮箱为 `orf-feedback-filter-e2e@orf.local`、姓名为 `ORF Feedback Filter E2E`、角色为 `admin`、状态为 `active` 的反馈列表筛选测试用户和默认团队成员关系", "db.user", "upsert", { emailFrom: "data.email", nameFrom: "data.name", roleFrom: "data.role", status: "active", identityIdFrom: "runtime.identity.id", saveAs: "user" }),
      step("Setup-4", "prisma", "db.feedback_filter_fixtures.prepare", "准备本用例独占的十条反馈 issue：每个分类各有一条状态为 `Open` 和一条状态为 `Closed` 的反馈，现象和分类应与本用例 fixture 表一致", "db.feedback_filter_fixtures", "prepare"),
      step("Setup-5", "api", "ory.sessions.revoke", "撤销邮箱为 `orf-feedback-filter-e2e@orf.local` 的反馈列表筛选测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.email" }),
      step("Setup-6", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Setup-7", "playwright", "page.goto.auth", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Setup-8", "playwright", "fill.email", "在邮箱输入框输入 `orf-feedback-filter-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.email" }),
      step("Setup-9", "playwright", "fill.password", "在密码输入框输入反馈列表筛选测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.password" }),
      step("Setup-10", "playwright", "click.sign_in", "点击 \"Sign In\" 登录操作", "page.login_form", "submit", { saveAs: "loginResponse" }),
      step("Setup-11", "api", "session.authenticated", "当前会话 应为 邮箱为 `orf-feedback-filter-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.email", roleFrom: "data.role", status: "active" }),
      step("Setup-12", "playwright", "page.goto.feedback", "打开 反馈页面", "page", "goto", { pathFrom: "data.feedbackPath" }),
    ],
  },
  S0: {
    description: "管理员已登录并位于反馈页面，默认 Open 与全部分类状态和十条 fixture 均已准备好",
    assertions: [
      step("S0-1", "api", "session.authenticated", "当前会话 应为 邮箱为 `orf-feedback-filter-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.email", roleFrom: "data.role", status: "active" }),
      step("S0-2", "playwright", "feedback.page.visible", "当前页面 应为 反馈页面", "feedback.page", "visible", { pathFrom: "data.feedbackPath" }),
      step("S0-3", "playwright", "feedback.search.visible", "反馈页面的搜索框 应可见", "feedback.search", "visible"),
      step("S0-4", "playwright", "feedback.search.empty", "反馈页面的搜索框的值 应为空", "feedback.search", "value", { value: "" }),
      step("S0-5", "playwright", "feedback.category.all_selected", "反馈页面的分类选择框 应已选择 \"全部分类\"", "feedback.category_filter", "selected_label", { label: "全部分类" }),
      step("S0-6", "playwright", "feedback.state.open_selected", "反馈页面的 `Open` 状态筛选 应为 已选中", "feedback.state_filter", "selected", { state: "Open" }),
      step("S0-7", "playwright", "feedback.reset.disabled", "反馈页面的重置操作 应不可点击", "feedback.reset", "disabled"),
      step("S0-8", "playwright", "feedback.list.open_visible", "反馈页面的列表 应显示 本用例五条 Open 反馈 issue", "feedback.list", "contains_phenomena", { phenomenaFrom: "data.openPhenomena" }),
      step("S0-9", "playwright", "feedback.list.closed_hidden", "反馈页面的列表 应不显示 本用例五条 Closed 反馈 issue", "feedback.list", "lacks_phenomena", { phenomenaFrom: "data.closedPhenomena" }),
      step("S0-10", "prisma", "db.feedback_filter_fixtures.exists", "本用例 fixture 表中的十条反馈 issue 及其分类记录 应存在", "db.feedback_filter_fixtures", "exists", { fixturesFrom: "data.fixtureRows" }),
    ],
  },
  Action: {
    description: "依次记录状态、分类和搜索后的列表快照，再重置筛选条件",
    steps: [
      step("Action-1", "playwright", "feedback.state.open.click", "点击 反馈页面的 `Open` 状态筛选", "feedback.state_filter", "click", { state: "Open" }),
      step("Action-2", "playwright", "feedback.list.open.capture", "记录 `Open` 状态筛选后的反馈列表", "feedback.list", "capture", { saveAs: "openStateSnapshot" }),
      step("Action-3", "playwright", "feedback.state.closed.click", "点击 反馈页面的 `Closed` 状态筛选", "feedback.state_filter", "click", { state: "Closed" }),
      step("Action-4", "playwright", "feedback.list.closed.capture", "记录 `Closed` 状态筛选后的反馈列表", "feedback.list", "capture", { saveAs: "closedStateSnapshot" }),
      step("Action-5", "playwright", "feedback.state.all.click", "点击 反馈页面的 `All` 状态筛选", "feedback.state_filter", "click", { state: "All" }),
      step("Action-6", "playwright", "feedback.list.all.capture", "记录 `All` 状态筛选后的反馈列表", "feedback.list", "capture", { saveAs: "allStateSnapshot" }),
      step("Action-7", "playwright", "feedback.category.technical.select", "在反馈页面的分类选择框选择 \"技术问题\"", "feedback.category_filter", "select", { label: "技术问题" }),
      step("Action-8", "playwright", "feedback.list.technical.capture", "记录选择 \"技术问题\" 后的反馈列表", "feedback.list", "capture", { saveAs: "technicalCategorySnapshot" }),
      step("Action-9", "playwright", "feedback.category.management.select", "在反馈页面的分类选择框选择 \"管理问题\"", "feedback.category_filter", "select", { label: "管理问题" }),
      step("Action-10", "playwright", "feedback.list.management.capture", "记录选择 \"管理问题\" 后的反馈列表", "feedback.list", "capture", { saveAs: "managementCategorySnapshot" }),
      step("Action-11", "playwright", "feedback.category.process.select", "在反馈页面的分类选择框选择 \"流程问题\"", "feedback.category_filter", "select", { label: "流程问题" }),
      step("Action-12", "playwright", "feedback.list.process.capture", "记录选择 \"流程问题\" 后的反馈列表", "feedback.list", "capture", { saveAs: "processCategorySnapshot" }),
      step("Action-13", "playwright", "feedback.category.permission.select", "在反馈页面的分类选择框选择 \"权限问题\"", "feedback.category_filter", "select", { label: "权限问题" }),
      step("Action-14", "playwright", "feedback.list.permission.capture", "记录选择 \"权限问题\" 后的反馈列表", "feedback.list", "capture", { saveAs: "permissionCategorySnapshot" }),
      step("Action-15", "playwright", "feedback.category.experience.select", "在反馈页面的分类选择框选择 \"体验问题\"", "feedback.category_filter", "select", { label: "体验问题" }),
      step("Action-16", "playwright", "feedback.list.experience.capture", "记录选择 \"体验问题\" 后的反馈列表", "feedback.list", "capture", { saveAs: "experienceCategorySnapshot" }),
      step("Action-17", "playwright", "feedback.category.technical.select_again", "在反馈页面的分类选择框选择 \"技术问题\"", "feedback.category_filter", "select", { label: "技术问题" }),
      step("Action-18", "playwright", "feedback.search.existing.fill", "在反馈页面的搜索框输入 `ORF反馈筛选E2E-技术问题-Open`", "feedback.search", "fill", { valueFrom: "data.existingKeyword" }),
      step("Action-19", "playwright", "feedback.list.existing_search.capture", "记录选择 \"技术问题\" 且输入已存在关键字后的反馈列表", "feedback.list", "capture", { saveAs: "existingSearchSnapshot" }),
      step("Action-20", "playwright", "feedback.search.missing.fill", "在反馈页面的搜索框输入 `ORF反馈筛选不存在E2E`", "feedback.search", "fill", { valueFrom: "data.missingKeyword" }),
      step("Action-21", "playwright", "feedback.list.missing_search.capture", "记录选择 \"技术问题\" 且输入不存在关键字后的反馈列表", "feedback.list", "capture", { saveAs: "missingSearchSnapshot" }),
      step("Action-22", "playwright", "feedback.reset.click", "点击 反馈页面的重置操作", "feedback.reset", "click"),
      step("Action-23", "playwright", "feedback.list.reset.capture", "记录重置后的反馈列表和筛选条件", "feedback.list", "capture", { saveAs: "resetSnapshot" }),
    ],
  },
  S1: {
    description: "状态、分类、搜索与重置后的列表快照均符合预期",
    assertions: [
      step("S1-1", "playwright", "feedback.snapshot.open_visible", "`Open` 状态筛选后的反馈列表 应显示 本用例五条 Open 反馈 issue", "feedback.list_snapshot", "contains_phenomena", { snapshotFrom: "runtime.openStateSnapshot", phenomenaFrom: "data.openPhenomena" }),
      step("S1-2", "playwright", "feedback.snapshot.open_closed_hidden", "`Open` 状态筛选后的反馈列表 应不显示 本用例五条 Closed 反馈 issue", "feedback.list_snapshot", "lacks_phenomena", { snapshotFrom: "runtime.openStateSnapshot", phenomenaFrom: "data.closedPhenomena" }),
      step("S1-3", "playwright", "feedback.snapshot.closed_visible", "`Closed` 状态筛选后的反馈列表 应显示 本用例五条 Closed 反馈 issue", "feedback.list_snapshot", "contains_phenomena", { snapshotFrom: "runtime.closedStateSnapshot", phenomenaFrom: "data.closedPhenomena" }),
      step("S1-4", "playwright", "feedback.snapshot.closed_open_hidden", "`Closed` 状态筛选后的反馈列表 应不显示 本用例五条 Open 反馈 issue", "feedback.list_snapshot", "lacks_phenomena", { snapshotFrom: "runtime.closedStateSnapshot", phenomenaFrom: "data.openPhenomena" }),
      step("S1-5", "playwright", "feedback.snapshot.all_visible", "`All` 状态筛选后的反馈列表 应显示 本用例十条反馈 issue", "feedback.list_snapshot", "contains_phenomena", { snapshotFrom: "runtime.allStateSnapshot", phenomenaFrom: "data.allPhenomena" }),
      step("S1-6", "playwright", "feedback.snapshot.technical_visible", "选择 \"技术问题\" 后的反馈列表 应显示 本用例技术问题的 Open 和 Closed 反馈 issue", "feedback.list_snapshot", "contains_phenomena", { snapshotFrom: "runtime.technicalCategorySnapshot", phenomenaFrom: "data.technicalPhenomena" }),
      step("S1-7", "playwright", "feedback.snapshot.technical_hidden", "选择 \"技术问题\" 后的反馈列表 应不显示 本用例其他四个分类的反馈 issue", "feedback.list_snapshot", "lacks_phenomena", { snapshotFrom: "runtime.technicalCategorySnapshot", phenomenaFrom: "data.technicalExcludedPhenomena" }),
      step("S1-8", "playwright", "feedback.snapshot.management_visible", "选择 \"管理问题\" 后的反馈列表 应显示 本用例管理问题的 Open 和 Closed 反馈 issue", "feedback.list_snapshot", "contains_phenomena", { snapshotFrom: "runtime.managementCategorySnapshot", phenomenaFrom: "data.managementPhenomena" }),
      step("S1-9", "playwright", "feedback.snapshot.management_hidden", "选择 \"管理问题\" 后的反馈列表 应不显示 本用例其他四个分类的反馈 issue", "feedback.list_snapshot", "lacks_phenomena", { snapshotFrom: "runtime.managementCategorySnapshot", phenomenaFrom: "data.managementExcludedPhenomena" }),
      step("S1-10", "playwright", "feedback.snapshot.process_visible", "选择 \"流程问题\" 后的反馈列表 应显示 本用例流程问题的 Open 和 Closed 反馈 issue", "feedback.list_snapshot", "contains_phenomena", { snapshotFrom: "runtime.processCategorySnapshot", phenomenaFrom: "data.processPhenomena" }),
      step("S1-11", "playwright", "feedback.snapshot.process_hidden", "选择 \"流程问题\" 后的反馈列表 应不显示 本用例其他四个分类的反馈 issue", "feedback.list_snapshot", "lacks_phenomena", { snapshotFrom: "runtime.processCategorySnapshot", phenomenaFrom: "data.processExcludedPhenomena" }),
      step("S1-12", "playwright", "feedback.snapshot.permission_visible", "选择 \"权限问题\" 后的反馈列表 应显示 本用例权限问题的 Open 和 Closed 反馈 issue", "feedback.list_snapshot", "contains_phenomena", { snapshotFrom: "runtime.permissionCategorySnapshot", phenomenaFrom: "data.permissionPhenomena" }),
      step("S1-13", "playwright", "feedback.snapshot.permission_hidden", "选择 \"权限问题\" 后的反馈列表 应不显示 本用例其他四个分类的反馈 issue", "feedback.list_snapshot", "lacks_phenomena", { snapshotFrom: "runtime.permissionCategorySnapshot", phenomenaFrom: "data.permissionExcludedPhenomena" }),
      step("S1-14", "playwright", "feedback.snapshot.experience_visible", "选择 \"体验问题\" 后的反馈列表 应显示 本用例体验问题的 Open 和 Closed 反馈 issue", "feedback.list_snapshot", "contains_phenomena", { snapshotFrom: "runtime.experienceCategorySnapshot", phenomenaFrom: "data.experiencePhenomena" }),
      step("S1-15", "playwright", "feedback.snapshot.experience_hidden", "选择 \"体验问题\" 后的反馈列表 应不显示 本用例其他四个分类的反馈 issue", "feedback.list_snapshot", "lacks_phenomena", { snapshotFrom: "runtime.experienceCategorySnapshot", phenomenaFrom: "data.experienceExcludedPhenomena" }),
      step("S1-16", "playwright", "feedback.snapshot.existing_visible", "选择 \"技术问题\" 且输入已存在关键字后，反馈列表 应显示 `ORF反馈筛选E2E-技术问题-Open`", "feedback.list_snapshot", "contains_phenomena", { snapshotFrom: "runtime.existingSearchSnapshot", phenomenaFrom: "data.technicalOpenPhenomenon" }),
      step("S1-17", "playwright", "feedback.snapshot.existing_closed_hidden", "选择 \"技术问题\" 且输入已存在关键字后，反馈列表 应不显示 `ORF反馈筛选E2E-技术问题-Closed`", "feedback.list_snapshot", "lacks_phenomena", { snapshotFrom: "runtime.existingSearchSnapshot", phenomenaFrom: "data.technicalClosedPhenomenon" }),
      step("S1-18", "playwright", "feedback.snapshot.missing_hidden", "选择 \"技术问题\" 且输入不存在关键字后，反馈列表 应不显示 本用例技术问题的 Open 和 Closed 反馈 issue", "feedback.list_snapshot", "lacks_phenomena", { snapshotFrom: "runtime.missingSearchSnapshot", phenomenaFrom: "data.technicalPhenomena" }),
      step("S1-19", "playwright", "feedback.snapshot.missing_empty", "选择 \"技术问题\" 且输入不存在关键字后，反馈页面 应显示 \"没有匹配的反馈\" 空结果提示", "feedback.list_snapshot", "empty_message_visible", { snapshotFrom: "runtime.missingSearchSnapshot" }),
      step("S1-20", "playwright", "feedback.snapshot.reset_search_empty", "重置后，反馈页面的搜索框的值 应为空", "feedback.filter_snapshot", "query_empty", { snapshotFrom: "runtime.resetSnapshot" }),
      step("S1-21", "playwright", "feedback.snapshot.reset_category_all", "重置后，反馈页面的分类选择框 应已选择 \"全部分类\"", "feedback.filter_snapshot", "category_selected", { snapshotFrom: "runtime.resetSnapshot", label: "全部分类" }),
      step("S1-22", "playwright", "feedback.snapshot.reset_open", "重置后，反馈页面的 `Open` 状态筛选 应为 已选中", "feedback.filter_snapshot", "state_selected", { snapshotFrom: "runtime.resetSnapshot", state: "Open" }),
      step("S1-23", "playwright", "feedback.snapshot.reset_open_visible", "重置后，反馈页面的列表 应显示 本用例五条 Open 反馈 issue", "feedback.list_snapshot", "contains_phenomena", { snapshotFrom: "runtime.resetSnapshot", phenomenaFrom: "data.openPhenomena" }),
      step("S1-24", "playwright", "feedback.snapshot.reset_closed_hidden", "重置后，反馈页面的列表 应不显示 本用例五条 Closed 反馈 issue", "feedback.list_snapshot", "lacks_phenomena", { snapshotFrom: "runtime.resetSnapshot", phenomenaFrom: "data.closedPhenomena" }),
      step("S1-25", "playwright", "feedback.snapshot.reset_disabled", "重置后，反馈页面的重置操作 应不可点击", "feedback.filter_snapshot", "reset_disabled", { snapshotFrom: "runtime.resetSnapshot" }),
      step("S1-26", "api", "session.authenticated.after_filter", "当前会话 应仍为 邮箱为 `orf-feedback-filter-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.email", roleFrom: "data.role", status: "active" }),
    ],
  },
  Clean: {
    description: "删除独占反馈 fixture、测试用户和认证身份，恢复未登录基准状态",
    steps: [
      step("Clean-1", "api", "auth.logout", "注销当前登录会话", "auth", "logout"),
      step("Clean-2", "playwright", "page.runtime.stop", "离开当前 ORF 前端页面", "page.runtime", "stop"),
      step("Clean-3", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Clean-4", "prisma", "db.feedback_filter_fixtures.delete", "删除现象以 `ORF反馈筛选E2E-` 开头的本用例反馈 issue 及其分类记录", "db.feedback_filter_fixtures", "delete", { fixturesFrom: "data.fixtureRows" }),
      step("Clean-5", "api", "ory.sessions.revoke", "撤销邮箱为 `orf-feedback-filter-e2e@orf.local` 的反馈列表筛选测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.email" }),
      step("Clean-6", "api", "ory.identity.delete", "删除邮箱为 `orf-feedback-filter-e2e@orf.local` 的反馈列表筛选测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.email" }),
      step("Clean-7", "prisma", "db.user.memberships.delete", "删除邮箱为 `orf-feedback-filter-e2e@orf.local` 的反馈列表筛选测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.email" }),
      step("Clean-8", "prisma", "db.user.delete", "删除邮箱为 `orf-feedback-filter-e2e@orf.local` 的反馈列表筛选测试用户", "db.user", "delete", { emailFrom: "data.email" }),
      step("Clean-9", "prisma", "db.feedback_filter_fixtures.absent", "现象以 `ORF反馈筛选E2E-` 开头的本用例反馈 issue 及其分类记录 应不存在", "db.feedback_filter_fixtures", "absent", { fixturesFrom: "data.fixtureRows" }),
      step("Clean-10", "api", "ory.identity.absent", "邮箱为 `orf-feedback-filter-e2e@orf.local` 的反馈列表筛选测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.email" }),
      step("Clean-11", "prisma", "db.user.absent", "邮箱为 `orf-feedback-filter-e2e@orf.local` 的反馈列表筛选测试用户 应不存在", "db.user", "absent", { emailFrom: "data.email" }),
    ],
  },
} satisfies StateCaseSpec<FeedbackListFilterCaseData>;
