import { STATE_CASE_MODEL, type StateCaseSpec } from "../../_framework/types";
import type { AdminReviewLootCaseData } from "./_support/admin-review-loot.context";

export const adminReviewLootCase = {
  id: "acceptance.admin-review-loot",
  title: "管理员验收战利品",
  model: STATE_CASE_MODEL,
  tags: ["acceptance", "loot", "admin", "happy-path"],

  data: {
    adminEmail: "orf-admin-review-loot-e2e@orf.local",
    adminPassword: "OrfAdminReviewLootE2E!2026",
    adminName: "ORF Admin Review Loot E2E",
    adminRole: "admin",
    memberEmail: "orf-member-admin-review-loot-e2e@orf.local",
    memberPassword: "OrfMemberAdminReviewLootE2E!2026",
    memberName: "ORF Member Admin Review Loot E2E",
    memberRole: "member",
    objectiveId: "obj-testd-admin-review-loot",
    objectiveTitle: "E2E-ADMIN-REVIEW-LOOT: 目标前置",
    resultTitle: "E2E-REVIEW-RESULT: 管理员验收战利品指标",
    metricName: "管理员验收战利品指标",
    lootBody: "E2E-REVIEW-LOOT-BODY: 管理员验收战利品完成说明",
    evidenceText: "E2E-REVIEW-EVIDENCE: 验收证据",
    points: 42,
    reason: "E2E-REVIEW-LOOT: 管理员验收战利品",
  },

  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      { source: { caseStepId: "B-1", method: "api" }, id: "frontend.ready", title: "前端服务 应可用", object: "frontend.service", operator: "available" },
      { source: { caseStepId: "B-2", method: "api" }, id: "backend.ready", title: "后端服务 应可用", object: "api.health", operator: "ok" },
      {
        source: { caseStepId: "B-3", method: "api" },
        id: "frontend.login_entry.accessible",
        title: "前端登录页入口 应可访问",
        object: "frontend.login_entry",
        operator: "accessible",
      },
      {
        source: { caseStepId: "B-4", method: "api" },
        id: "session.endpoint.accessible",
        title: "当前会话查询能力 应可用",
        object: "auth.session",
        operator: "accessible",
      },
      { source: { caseStepId: "B-5", method: "prisma" }, id: "db.ready", title: "ORF 数据库 应可连接", object: "db", operator: "ready" },
      {
        source: { caseStepId: "B-6", method: "prisma" },
        id: "db.schema.current",
        title: "ORF 数据库 schema 应为 当前测试版本",
        object: "db.schema",
        operator: "current",
      },
      {
        source: { caseStepId: "B-7", method: "api" },
        id: "ory.admin_public.ready",
        title: "Ory/Kratos 认证服务的管理和公共访问能力 应可用",
        object: "ory.admin_public",
        operator: "ready",
      },
      { source: { caseStepId: "B-8", method: "api" }, id: "session.unauthenticated", title: "当前会话 应为 未登录", object: "auth.session", operator: "unauthenticated" },
      {
        source: { caseStepId: "B-9", method: "playwright" },
        id: "cookie.absent",
        title: "当前浏览器 应不存在 Ory 登录会话 cookie",
        object: "browser.cookie",
        operator: "absent",
      },
      {
        source: { caseStepId: "B-10", method: "playwright" },
        id: "storage.empty",
        title: "当前浏览器 应不保留本地登录态",
        object: "browser.auth_storage",
        operator: "empty",
      },
    ],
  },

  Setup: {
    description: "准备管理员、普通成员、本用例独占 submitted 目标、指标和战利品，登录管理员并进入验收页",
    steps: [
      {
        source: { caseStepId: "Setup-1", method: "prisma" },
        id: "db.review_loot_ledger.delete_residue",
        title: "删除可能残留的 reason 为 `E2E-REVIEW-LOOT: 管理员验收战利品` 的测试积分流水",
        object: "db.review_loot_ledger",
        operator: "delete",
        params: { reasonFrom: "data.reason" },
      },
      {
        source: { caseStepId: "Setup-2", method: "prisma" },
        id: "db.review_loot.delete_residue",
        title: "删除可能残留的内容为 `E2E-REVIEW-LOOT-BODY: 管理员验收战利品完成说明` 的测试战利品",
        object: "db.review_loot",
        operator: "delete",
        params: { bodyFrom: "data.lootBody" },
      },
      {
        source: { caseStepId: "Setup-3", method: "prisma" },
        id: "db.review_loot_result.delete_residue",
        title: "删除可能残留的标题为 `E2E-REVIEW-RESULT: 管理员验收战利品指标` 的测试指标",
        object: "db.review_loot_result",
        operator: "delete",
        params: { titleFrom: "data.resultTitle" },
      },
      {
        source: { caseStepId: "Setup-4", method: "prisma" },
        id: "db.objective.delete_residue",
        title: "删除可能残留的标题为 `E2E-ADMIN-REVIEW-LOOT: 目标前置` 的本用例目标及其派生数据",
        object: "db.objective",
        operator: "delete_by_title",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Setup-5", method: "api" },
        id: "ory.admin_identity.upsert",
        title: "准备邮箱为 `orf-admin-review-loot-e2e@orf.local`、使用固定测试密码的管理员登录身份",
        object: "ory.identity",
        operator: "upsert_password",
        params: { emailFrom: "data.adminEmail", nameFrom: "data.adminName", passwordFrom: "data.adminPassword", saveAs: "adminIdentity" },
      },
      {
        source: { caseStepId: "Setup-6", method: "prisma" },
        id: "db.admin.upsert",
        title: "准备邮箱为 `orf-admin-review-loot-e2e@orf.local`、角色为 `admin`、状态为 `active` 的管理员用户和默认团队成员关系",
        object: "db.user",
        operator: "upsert",
        params: {
          emailFrom: "data.adminEmail",
          nameFrom: "data.adminName",
          roleFrom: "data.adminRole",
          status: "active",
          identityIdFrom: "runtime.adminIdentity.id",
          saveAs: "adminUser",
        },
      },
      {
        source: { caseStepId: "Setup-7", method: "api" },
        id: "ory.member_identity.upsert",
        title: "准备邮箱为 `orf-member-admin-review-loot-e2e@orf.local`、使用固定测试密码的普通成员登录身份",
        object: "ory.identity",
        operator: "upsert_password",
        params: { emailFrom: "data.memberEmail", nameFrom: "data.memberName", passwordFrom: "data.memberPassword", saveAs: "memberIdentity" },
      },
      {
        source: { caseStepId: "Setup-8", method: "prisma" },
        id: "db.member.upsert",
        title: "准备邮箱为 `orf-member-admin-review-loot-e2e@orf.local`、角色为 `member`、状态为 `active` 的普通成员用户和默认团队成员关系",
        object: "db.user",
        operator: "upsert",
        params: {
          emailFrom: "data.memberEmail",
          nameFrom: "data.memberName",
          roleFrom: "data.memberRole",
          status: "active",
          identityIdFrom: "runtime.memberIdentity.id",
          saveAs: "memberUser",
        },
      },
      {
        source: { caseStepId: "Setup-9", method: "prisma" },
        id: "db.objective.upsert_review_loot_target",
        title: "创建标题为 `E2E-ADMIN-REVIEW-LOOT: 目标前置` 的本用例独占目标",
        object: "db.objective",
        operator: "upsert",
        params: {
          idFrom: "data.objectiveId",
          titleFrom: "data.objectiveTitle",
          teamIdFrom: "runtime.adminUser.teamId",
          stage: "goalFrozen",
          flowStatus: "submitted",
          status: "Draft",
          saveAs: "fixtureObjective",
        },
      },
      {
        source: { caseStepId: "Setup-10", method: "prisma" },
        id: "db.review_loot_target.from_objective",
        title: "记录 本用例独占目标",
        object: "db.review_loot_target",
        operator: "from_objective",
        params: { objectiveIdFrom: "runtime.fixtureObjective.id", saveAs: "reviewLootTarget" },
      },
      {
        source: { caseStepId: "Setup-11", method: "prisma" },
        id: "db.review_loot_target.prepare",
        title: "设置本用例目标为 `submitted`，记录 lootSubmittedAt，并设置挑战者列表仅包含普通成员",
        object: "db.review_loot_target",
        operator: "prepare",
        params: { targetFrom: "runtime.reviewLootTarget", memberNameFrom: "data.memberName" },
      },
      {
        source: { caseStepId: "Setup-12", method: "prisma" },
        id: "db.review_loot_result.create",
        title: "创建本用例目标的测试指标，指标积分为 `42`",
        object: "db.review_loot_result",
        operator: "create",
        params: { targetFrom: "runtime.reviewLootTarget", titleFrom: "data.resultTitle", metricNameFrom: "data.metricName", pointsFrom: "data.points", saveAs: "reviewLootResult" },
      },
      {
        source: { caseStepId: "Setup-13", method: "prisma" },
        id: "db.review_loot.create",
        title: "创建本用例目标的测试战利品，并声明测试指标已完成",
        object: "db.review_loot",
        operator: "create",
        params: {
          targetFrom: "runtime.reviewLootTarget",
          resultFrom: "runtime.reviewLootResult",
          bodyFrom: "data.lootBody",
          evidenceTextFrom: "data.evidenceText",
          memberNameFrom: "data.memberName",
          saveAs: "reviewLoot",
        },
      },
      {
        source: { caseStepId: "Setup-14", method: "api" },
        id: "ory.admin_sessions.revoke",
        title: "撤销管理员登录身份可能残留的登录会话",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.adminEmail" },
      },
      {
        source: { caseStepId: "Setup-15", method: "api" },
        id: "ory.member_sessions.revoke",
        title: "撤销普通成员登录身份可能残留的登录会话",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.memberEmail" },
      },
      {
        source: { caseStepId: "Setup-16", method: "playwright" },
        id: "browser.clear",
        title: "移除当前浏览器中的残留登录态",
        object: "browser",
        operator: "clear_state",
      },
      { source: { caseStepId: "Setup-17", method: "playwright" }, id: "page.goto.auth", title: "打开 ORF 登录页", object: "page", operator: "goto", params: { path: "/auth" } },
      { source: { caseStepId: "Setup-18", method: "playwright" }, id: "fill.email", title: "在邮箱输入框输入管理员固定测试邮箱", object: "page", operator: "fill", params: { label: "Email", valueFrom: "data.adminEmail" } },
      {
        source: { caseStepId: "Setup-19", method: "playwright" },
        id: "fill.password",
        title: "在密码输入框输入管理员固定测试密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.adminPassword" },
      },
      { source: { caseStepId: "Setup-20", method: "playwright" }, id: "click.sign_in", title: "点击 `Sign In` 登录操作", object: "page", operator: "click", params: { role: "button", name: "Sign In" } },
      {
        source: { caseStepId: "Setup-21", method: "api" },
        id: "session.admin.authenticated",
        title: "当前会话 应为 管理员的已登录会话",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.adminEmail", roleFrom: "data.adminRole", status: "active" },
      },
      {
        source: { caseStepId: "Setup-22", method: "playwright" },
        id: "page.goto.loot",
        title: "打开 本用例目标战利品页面",
        object: "page.review_loot",
        operator: "goto",
        params: { targetFrom: "runtime.reviewLootTarget" },
      },
    ],
  },

  S0: {
    description: "管理员已登录并位于本用例目标战利品页面，目标可验收结算",
    assertions: [
      {
        source: { caseStepId: "S0-1", method: "api" },
        id: "session.admin.authenticated",
        title: "当前会话 应为 邮箱 `orf-admin-review-loot-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.adminEmail", roleFrom: "data.adminRole", status: "active" },
      },
      { source: { caseStepId: "S0-2", method: "playwright" }, id: "url.loot", title: "当前页面 应为 本用例目标战利品页面", object: "page.url", operator: "match", params: { pattern: "/objectives/.+/loot$" } },
      { source: { caseStepId: "S0-3", method: "playwright" }, id: "review_loot_form.visible", title: "验收战利品表单 应可见", object: "page.review_loot_form", operator: "visible" },
      { source: { caseStepId: "S0-4", method: "prisma" }, id: "db.review_loot_target.submitted", title: "本用例目标流转状态 应为 `submitted` 且战利品提交时间已存在", object: "db.review_loot_target", operator: "submitted", params: { targetFrom: "runtime.reviewLootTarget" } },
      { source: { caseStepId: "S0-5", method: "prisma" }, id: "db.review_loot_result.present", title: "本用例目标 应存在 测试指标", object: "db.review_loot_result", operator: "present", params: { targetFrom: "runtime.reviewLootTarget", resultFrom: "runtime.reviewLootResult" } },
      { source: { caseStepId: "S0-6", method: "prisma" }, id: "db.review_loot.present", title: "本用例目标 应存在 测试战利品", object: "db.review_loot", operator: "present", params: { targetFrom: "runtime.reviewLootTarget", lootFrom: "runtime.reviewLoot" } },
      { source: { caseStepId: "S0-7", method: "prisma" }, id: "db.review_loot_ledger.absent", title: "reason 为 `E2E-REVIEW-LOOT: 管理员验收战利品` 的测试积分流水 应不存在", object: "db.review_loot_ledger", operator: "absent", params: { reasonFrom: "data.reason" } },
    ],
  },

  Action: {
    description: "管理员通过页面验收战利品并结算",
    steps: [
      { source: { caseStepId: "Action-1", method: "playwright" }, id: "fill.review_reason", title: "在 `验收说明` 输入框 输入 测试验收说明", object: "page", operator: "fill", params: { label: "验收说明", valueFrom: "data.reason" } },
      { source: { caseStepId: "Action-2", method: "api" }, id: "capture.review_loot_response", title: "监听 验收战利品请求响应", object: "api.review_loot", operator: "capture_response", params: { targetFrom: "runtime.reviewLootTarget", saveAs: "reviewLootResponse" } },
      { source: { caseStepId: "Action-3", method: "playwright" }, id: "click.review_loot", title: "点击 `验收并结算` 操作", object: "page", operator: "click", params: { role: "button", name: "验收并结算" } },
    ],
  },

  S1: {
    description: "目标已结算，积分流水已经生成，管理员仍保持登录",
    assertions: [
      { source: { caseStepId: "S1-1", method: "api" }, id: "review_loot_response.ok", title: "验收战利品结果 应成功", object: "api.response", operator: "ok", params: { responseFrom: "runtime.reviewLootResponse", status: 200 } },
      { source: { caseStepId: "S1-2", method: "prisma" }, id: "db.review_loot_target.settled", title: "本用例目标流转状态 应为 `settled`，验收结果应为 `completed`，目标结算分数应为 `42`", object: "db.review_loot_target", operator: "settled", params: { targetFrom: "runtime.reviewLootTarget", pointsFrom: "data.points" } },
      {
        source: { caseStepId: "S1-3", method: "prisma" },
        id: "db.review_loot_ledger.present",
        title: "数据库中 应存在 普通成员对本用例目标的测试积分流水，积分为 `42` 且 reason 为测试验收说明",
        object: "db.review_loot_ledger",
        operator: "present",
        params: { targetFrom: "runtime.reviewLootTarget", memberNameFrom: "data.memberName", pointsFrom: "data.points", reasonFrom: "data.reason" },
      },
      { source: { caseStepId: "S1-4", method: "playwright" }, id: "url.reports", title: "当前页面 应为 统计页面", object: "page.url", operator: "match", params: { pattern: "/reports$" } },
      { source: { caseStepId: "S1-5", method: "api" }, id: "session.admin.still_authenticated", title: "当前会话 应仍为 管理员的已登录会话", object: "auth.session", operator: "authenticated", params: { emailFrom: "data.adminEmail", roleFrom: "data.adminRole", status: "active" } },
    ],
  },

  Clean: {
    description: "删除本用例创建的积分流水、战利品、指标、目标、账号和页面会话状态",
    steps: [
      { source: { caseStepId: "Clean-1", method: "prisma" }, id: "db.review_loot_ledger.delete", title: "删除 本用例创建的测试积分流水", object: "db.review_loot_ledger", operator: "delete", params: { reasonFrom: "data.reason" } },
      { source: { caseStepId: "Clean-2", method: "prisma" }, id: "db.review_loot.delete", title: "删除 本用例创建的测试战利品", object: "db.review_loot", operator: "delete", params: { bodyFrom: "data.lootBody", lootFrom: "runtime.reviewLoot" } },
      { source: { caseStepId: "Clean-3", method: "prisma" }, id: "db.review_loot_result.delete", title: "删除 本用例创建的测试指标", object: "db.review_loot_result", operator: "delete", params: { titleFrom: "data.resultTitle", resultFrom: "runtime.reviewLootResult" } },
      { source: { caseStepId: "Clean-4", method: "prisma" }, id: "db.objective.delete", title: "删除 本用例独占目标及其派生数据", object: "db.objective", operator: "delete", params: { idFrom: "data.objectiveId", titleFrom: "data.objectiveTitle" } },
      { source: { caseStepId: "Clean-5", method: "api" }, id: "auth.logout", title: "注销当前登录会话", object: "auth", operator: "logout" },
      { source: { caseStepId: "Clean-6", method: "playwright" }, id: "page.runtime.stop", title: "离开当前 ORF 前端页面", object: "page.runtime", operator: "stop" },
      { source: { caseStepId: "Clean-7", method: "playwright" }, id: "browser.clear", title: "移除当前浏览器中的残留登录态", object: "browser", operator: "clear_state" },
      { source: { caseStepId: "Clean-8", method: "api" }, id: "ory.admin_sessions.revoke", title: "撤销管理员登录身份的残留登录会话", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-9", method: "api" }, id: "ory.member_sessions.revoke", title: "撤销普通成员登录身份的残留登录会话", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-10", method: "api" }, id: "ory.admin_identity.delete", title: "删除管理员登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-11", method: "api" }, id: "ory.member_identity.delete", title: "删除普通成员登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-12", method: "prisma" }, id: "db.admin.delete_memberships", title: "删除 管理员默认团队成员关系", object: "db.user", operator: "delete_memberships", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-13", method: "prisma" }, id: "db.member.delete_memberships", title: "删除 普通成员默认团队成员关系", object: "db.user", operator: "delete_memberships", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-14", method: "prisma" }, id: "db.admin.delete", title: "删除 管理员用户", object: "db.user", operator: "delete", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-15", method: "prisma" }, id: "db.member.delete", title: "删除 普通成员用户", object: "db.user", operator: "delete", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-16", method: "prisma" }, id: "db.review_loot_ledger.absent", title: "reason 为 `E2E-REVIEW-LOOT: 管理员验收战利品` 的测试积分流水 应不存在", object: "db.review_loot_ledger", operator: "absent", params: { reasonFrom: "data.reason" } },
      { source: { caseStepId: "Clean-17", method: "prisma" }, id: "db.review_loot.absent", title: "内容为 `E2E-REVIEW-LOOT-BODY: 管理员验收战利品完成说明` 的测试战利品 应不存在", object: "db.review_loot", operator: "absent", params: { bodyFrom: "data.lootBody" } },
      { source: { caseStepId: "Clean-18", method: "prisma" }, id: "db.review_loot_result.absent", title: "标题为 `E2E-REVIEW-RESULT: 管理员验收战利品指标` 的测试指标 应不存在", object: "db.review_loot_result", operator: "absent", params: { titleFrom: "data.resultTitle" } },
      { source: { caseStepId: "Clean-19", method: "prisma" }, id: "db.objective.absent", title: "标题为 `E2E-ADMIN-REVIEW-LOOT: 目标前置` 的本用例目标 应不存在", object: "db.objective", operator: "absent", params: { idFrom: "data.objectiveId", titleFrom: "data.objectiveTitle" } },
      { source: { caseStepId: "Clean-20", method: "prisma" }, id: "db.admin.absent", title: "邮箱为 `orf-admin-review-loot-e2e@orf.local` 的管理员用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-21", method: "prisma" }, id: "db.member.absent", title: "邮箱为 `orf-member-admin-review-loot-e2e@orf.local` 的普通成员用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.memberEmail" } },
    ],
  },
} satisfies StateCaseSpec<AdminReviewLootCaseData>;
