import { STATE_CASE_MODEL, type StateCaseSpec } from "../../_framework/types";
import type { MemberCreateTaskCaseData } from "./_support/member-create-task.context";

export const memberCreateTaskCase = {
  id: "tasks.member-create-task",
  title: "用户可以增加行动项和子行动项",
  model: STATE_CASE_MODEL,
  tags: ["tasks", "subtasks", "member", "admin", "happy-path"],

  data: {
    adminEmail: "orf-admin-create-task-e2e@orf.local",
    adminPassword: "OrfAdminCreateTaskE2E!2026",
    adminName: "ORF Admin Create Task E2E",
    adminRole: "admin",
    memberEmail: "orf-member-create-task-e2e@orf.local",
    memberPassword: "OrfMemberCreateTaskE2E!2026",
    memberName: "ORF Member Create Task E2E",
    memberRole: "member",
    objectiveId: "obj-testd-user-create-task",
    objectiveTitle: "E2E-USER-CREATE-TASK: 目标前置",
    adminTaskTitle: "E2E-TASK-CREATE: 管理员增加行动项",
    memberTaskTitle: "E2E-TASK-CREATE: 成员增加行动项",
    taskDescription: "执行支撑目标的下一步技术任务。",
    adminSubtaskLabel: "管理员子任务",
    memberSubtaskLabel: "成员子任务",
  },

  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      { source: { caseStepId: "B-1", method: "api" }, id: "frontend.ready", title: "前端服务 应可用", object: "frontend.service", operator: "available" },
      { source: { caseStepId: "B-2", method: "api" }, id: "backend.ready", title: "后端服务 应可用", object: "api.health", operator: "ok" },
      { source: { caseStepId: "B-3", method: "api" }, id: "frontend.login_entry.accessible", title: "前端登录页入口 应可访问", object: "frontend.login_entry", operator: "accessible" },
      { source: { caseStepId: "B-4", method: "api" }, id: "session.endpoint.accessible", title: "当前会话查询能力 应可用", object: "auth.session", operator: "accessible" },
      { source: { caseStepId: "B-5", method: "prisma" }, id: "db.ready", title: "ORF 数据库 应可连接", object: "db", operator: "ready" },
      { source: { caseStepId: "B-6", method: "prisma" }, id: "db.schema.current", title: "ORF 数据库 schema 应为 当前测试版本", object: "db.schema", operator: "current" },
      { source: { caseStepId: "B-7", method: "api" }, id: "ory.admin_public.ready", title: "Ory/Kratos 认证服务的管理和公共访问能力 应可用", object: "ory.admin_public", operator: "ready" },
      { source: { caseStepId: "B-8", method: "api" }, id: "session.unauthenticated", title: "当前会话 应为 未登录", object: "auth.session", operator: "unauthenticated" },
      { source: { caseStepId: "B-9", method: "playwright" }, id: "cookie.absent", title: "当前浏览器 应不存在 Ory 登录会话 cookie", object: "browser.cookie", operator: "absent" },
      { source: { caseStepId: "B-10", method: "playwright" }, id: "storage.empty", title: "当前浏览器 应不保留本地登录态", object: "browser.auth_storage", operator: "empty" },
    ],
  },

  Setup: {
    description: "准备管理员、普通成员和本用例独占重估目标，目标挑战者包含普通成员",
    steps: [
      { source: { caseStepId: "Setup-1", method: "prisma" }, id: "db.admin_task.delete_residue", title: "删除可能残留的本用例管理员测试行动项", object: "db.task", operator: "delete", params: { titleFrom: "data.adminTaskTitle" } },
      { source: { caseStepId: "Setup-2", method: "prisma" }, id: "db.member_task.delete_residue", title: "删除可能残留的本用例成员测试行动项", object: "db.task", operator: "delete", params: { titleFrom: "data.memberTaskTitle" } },
      { source: { caseStepId: "Setup-3", method: "prisma" }, id: "db.objective.delete_residue", title: "删除可能残留的本用例目标及其派生数据", object: "db.objective", operator: "delete_by_title", params: { titleFrom: "data.objectiveTitle" } },
      {
        source: { caseStepId: "Setup-4", method: "api" },
        id: "ory.admin_identity.upsert",
        title: "准备邮箱为 `orf-admin-create-task-e2e@orf.local`、使用固定测试密码的管理员登录身份",
        object: "ory.identity",
        operator: "upsert_password",
        params: { emailFrom: "data.adminEmail", nameFrom: "data.adminName", passwordFrom: "data.adminPassword", saveAs: "adminIdentity" },
      },
      {
        source: { caseStepId: "Setup-5", method: "prisma" },
        id: "db.admin.upsert",
        title: "准备邮箱为 `orf-admin-create-task-e2e@orf.local`、角色为 `admin`、状态为 `active` 的管理员用户和默认团队成员关系",
        object: "db.user",
        operator: "upsert",
        params: { emailFrom: "data.adminEmail", nameFrom: "data.adminName", roleFrom: "data.adminRole", status: "active", identityIdFrom: "runtime.adminIdentity.id", saveAs: "adminUser" },
      },
      {
        source: { caseStepId: "Setup-6", method: "api" },
        id: "ory.member_identity.upsert",
        title: "准备邮箱为 `orf-member-create-task-e2e@orf.local`、使用固定测试密码的普通成员登录身份",
        object: "ory.identity",
        operator: "upsert_password",
        params: { emailFrom: "data.memberEmail", nameFrom: "data.memberName", passwordFrom: "data.memberPassword", saveAs: "memberIdentity" },
      },
      {
        source: { caseStepId: "Setup-7", method: "prisma" },
        id: "db.member.upsert",
        title: "准备邮箱为 `orf-member-create-task-e2e@orf.local`、角色为 `member`、状态为 `active` 的普通成员用户和默认团队成员关系",
        object: "db.user",
        operator: "upsert",
        params: { emailFrom: "data.memberEmail", nameFrom: "data.memberName", roleFrom: "data.memberRole", status: "active", identityIdFrom: "runtime.memberIdentity.id", saveAs: "memberUser" },
      },
      {
        source: { caseStepId: "Setup-8", method: "prisma" },
        id: "db.objective.upsert_task_target",
        title: "创建标题为 `E2E-USER-CREATE-TASK: 目标前置`、流转状态为 `reestimating`、阶段为 `orfReestimate` 的本用例行动项目标",
        object: "db.objective",
        operator: "upsert",
        params: {
          idFrom: "data.objectiveId",
          titleFrom: "data.objectiveTitle",
          teamIdFrom: "runtime.adminUser.teamId",
          stage: "orfReestimate",
          flowStatus: "reestimating",
          status: "Draft",
          saveAs: "fixtureObjective",
        },
      },
      { source: { caseStepId: "Setup-9", method: "prisma" }, id: "db.task_target.from_objective", title: "记录 本用例行动项目标", object: "db.task_target", operator: "from_objective", params: { objectiveIdFrom: "runtime.fixtureObjective.id", saveAs: "taskTarget" } },
      { source: { caseStepId: "Setup-10", method: "prisma" }, id: "db.task_target.prepare", title: "设置本用例行动项目标的挑战者包含普通成员", object: "db.task_target", operator: "prepare", params: { targetFrom: "runtime.taskTarget", memberNameFrom: "data.memberName" } },
      { source: { caseStepId: "Setup-11", method: "api" }, id: "ory.admin_sessions.revoke", title: "撤销管理员登录身份可能残留的登录会话", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Setup-12", method: "api" }, id: "ory.member_sessions.revoke", title: "撤销普通成员登录身份可能残留的登录会话", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Setup-13", method: "playwright" }, id: "auth.logout", title: "注销当前登录会话", object: "auth", operator: "logout" },
      { source: { caseStepId: "Setup-14", method: "playwright" }, id: "page.runtime.stop", title: "离开当前 ORF 前端页面", object: "page.runtime", operator: "stop" },
      { source: { caseStepId: "Setup-15", method: "playwright" }, id: "browser.clear", title: "移除当前浏览器中的残留登录态", object: "browser", operator: "clear_state" },
    ],
  },

  S0: {
    description: "管理员和普通成员账号已准备完成，本用例目标允许两种角色新增行动项",
    assertions: [
      { source: { caseStepId: "S0-1", method: "api" }, id: "session.unauthenticated", title: "当前会话 应为 未登录", object: "auth.session", operator: "unauthenticated" },
      {
        source: { caseStepId: "S0-2", method: "prisma" },
        id: "db.task_target.admin_can_create",
        title: "本用例行动项目标 应允许 管理员新增行动项",
        object: "db.task_target",
        operator: "can_create_task",
        params: { targetFrom: "runtime.taskTarget", actorNameFrom: "data.adminName", roleFrom: "data.adminRole" },
      },
      {
        source: { caseStepId: "S0-3", method: "prisma" },
        id: "db.task_target.member_can_create",
        title: "本用例行动项目标 应允许 普通成员新增行动项",
        object: "db.task_target",
        operator: "can_create_task",
        params: { targetFrom: "runtime.taskTarget", actorNameFrom: "data.memberName", roleFrom: "data.memberRole" },
      },
      {
        source: { caseStepId: "S0-4", method: "prisma" },
        id: "db.admin_task.absent",
        title: "本用例行动项目标 应不存在 标题为 `E2E-TASK-CREATE: 管理员增加行动项` 的行动项",
        object: "db.task_target",
        operator: "task_absent",
        params: { targetFrom: "runtime.taskTarget", titleFrom: "data.adminTaskTitle" },
      },
      {
        source: { caseStepId: "S0-5", method: "prisma" },
        id: "db.member_task.absent",
        title: "本用例行动项目标 应不存在 标题为 `E2E-TASK-CREATE: 成员增加行动项` 的行动项",
        object: "db.task_target",
        operator: "task_absent",
        params: { targetFrom: "runtime.taskTarget", titleFrom: "data.memberTaskTitle" },
      },
    ],
  },

  Action: {
    description: "管理员和普通成员分别新增行动项，并各自在新建行动项下新增子行动项",
    steps: [
      { source: { caseStepId: "Action-1", method: "playwright" }, id: "admin.goto_auth", title: "打开 ORF 登录页", object: "page", operator: "goto", params: { path: "/auth" } },
      { source: { caseStepId: "Action-2", method: "playwright" }, id: "admin.fill_email", title: "在邮箱输入框输入管理员固定测试邮箱", object: "page", operator: "fill", params: { label: "Email", valueFrom: "data.adminEmail" } },
      { source: { caseStepId: "Action-3", method: "playwright" }, id: "admin.fill_password", title: "在密码输入框输入管理员固定测试密码", object: "page", operator: "fill", params: { label: "Password", exact: true, valueFrom: "data.adminPassword" } },
      { source: { caseStepId: "Action-4", method: "playwright" }, id: "admin.sign_in", title: "点击 \"Sign In\" 登录操作", object: "page", operator: "click", params: { role: "button", name: "Sign In" } },
      { source: { caseStepId: "Action-5", method: "api" }, id: "admin.session", title: "当前会话 应为 管理员的已登录会话", object: "auth.session", operator: "authenticated", params: { emailFrom: "data.adminEmail", roleFrom: "data.adminRole", status: "active" } },
      { source: { caseStepId: "Action-6", method: "playwright" }, id: "admin.goto_tasks", title: "打开 挑战工作台", object: "page", operator: "goto", params: { path: "/tasks" } },
      { source: { caseStepId: "Action-7", method: "playwright" }, id: "admin.scope_all", title: "切换到 \"所有挑战\" 视图", object: "page", operator: "click", params: { role: "button", name: "所有挑战" } },
      { source: { caseStepId: "Action-8", method: "playwright" }, id: "admin.target.visible", title: "本用例行动项目标面板 应可见", object: "page.task_target", operator: "visible", params: { targetFrom: "runtime.taskTarget" } },
      { source: { caseStepId: "Action-9", method: "playwright" }, id: "admin.add_task.enabled", title: "本用例行动项目标的 \"新增行动项\" 操作 应可点击", object: "page.task_target", operator: "add_task_enabled", params: { targetFrom: "runtime.taskTarget" } },
      { source: { caseStepId: "Action-10", method: "playwright" }, id: "admin.add_task", title: "点击 本用例行动项目标的 \"新增行动项\" 操作", object: "page.task_target", operator: "add_task", params: { targetFrom: "runtime.taskTarget" } },
      { source: { caseStepId: "Action-11", method: "playwright" }, id: "admin.task_editor.visible", title: "新增行动项内联标题编辑器 应可见", object: "page", operator: "visible", params: { label: "编辑行动项标题" } },
      { source: { caseStepId: "Action-12", method: "playwright" }, id: "admin.fill_task_title", title: "在新增行动项内联标题编辑器输入 管理员测试行动项标题", object: "page", operator: "fill", params: { label: "编辑行动项标题", valueFrom: "data.adminTaskTitle" } },
      { source: { caseStepId: "Action-13", method: "playwright" }, id: "admin.task_editor.submit", title: "提交新增行动项内联标题编辑器", object: "page.task_inline_editor", operator: "submit", params: { saveAs: "adminCreateTaskResponse" } },
      { source: { caseStepId: "Action-14", method: "api" }, id: "admin_task.record", title: "记录 管理员新建行动项结果中的测试行动项", object: "api.task_create_response", operator: "record_task", params: { responseFrom: "runtime.adminCreateTaskResponse", saveAs: "adminCreatedTask" } },
      { source: { caseStepId: "Action-15", method: "playwright" }, id: "admin.add_subtask", title: "点击管理员测试行动项的 \"新增子行动项\" 操作", object: "page.task_target", operator: "add_subtask", params: { targetFrom: "runtime.taskTarget", taskFrom: "runtime.adminCreatedTask" } },
      { source: { caseStepId: "Action-16", method: "playwright" }, id: "admin.subtask_editor.visible", title: "管理员测试行动项下的新增子行动项标题输入框 应可见", object: "page", operator: "visible", params: { label: "编辑子行动项标题" } },
      { source: { caseStepId: "Action-17", method: "playwright" }, id: "admin.fill_subtask_label", title: "在管理员测试行动项下的新增子行动项标题输入框输入 管理员测试子行动项标签", object: "page", operator: "fill", params: { label: "编辑子行动项标题", valueFrom: "data.adminSubtaskLabel" } },
      { source: { caseStepId: "Action-18", method: "playwright" }, id: "admin.subtask_editor.submit", title: "提交新增子行动项内联标题编辑器", object: "page.subtask_inline_editor", operator: "submit", params: { taskFrom: "runtime.adminCreatedTask", saveAs: "adminCreateSubtaskResponse" } },
      { source: { caseStepId: "Action-19", method: "api" }, id: "admin_subtask.record", title: "记录 管理员新建子行动项结果中的测试子行动项", object: "api.subtask_create_response", operator: "record_subtask", params: { responseFrom: "runtime.adminCreateSubtaskResponse", taskFrom: "runtime.adminCreatedTask", saveAs: "adminCreatedSubtask" } },
      { source: { caseStepId: "Action-20", method: "api" }, id: "admin.logout", title: "注销管理员登录会话", object: "auth", operator: "logout" },
      { source: { caseStepId: "Action-21", method: "playwright" }, id: "admin.clear", title: "移除当前浏览器中的残留登录态", object: "browser", operator: "clear_state" },
      { source: { caseStepId: "Action-22", method: "playwright" }, id: "member.goto_auth", title: "打开 ORF 登录页", object: "page", operator: "goto", params: { path: "/auth" } },
      { source: { caseStepId: "Action-23", method: "playwright" }, id: "member.fill_email", title: "在邮箱输入框输入普通成员固定测试邮箱", object: "page", operator: "fill", params: { label: "Email", valueFrom: "data.memberEmail" } },
      { source: { caseStepId: "Action-24", method: "playwright" }, id: "member.fill_password", title: "在密码输入框输入普通成员固定测试密码", object: "page", operator: "fill", params: { label: "Password", exact: true, valueFrom: "data.memberPassword" } },
      { source: { caseStepId: "Action-25", method: "playwright" }, id: "member.sign_in", title: "点击 \"Sign In\" 登录操作", object: "page", operator: "click", params: { role: "button", name: "Sign In" } },
      { source: { caseStepId: "Action-26", method: "api" }, id: "member.session", title: "当前会话 应为 普通成员的已登录会话", object: "auth.session", operator: "authenticated", params: { emailFrom: "data.memberEmail", roleFrom: "data.memberRole", status: "active" } },
      { source: { caseStepId: "Action-27", method: "playwright" }, id: "member.goto_tasks", title: "打开 挑战工作台", object: "page", operator: "goto", params: { path: "/tasks" } },
      { source: { caseStepId: "Action-28", method: "playwright" }, id: "member.target.visible", title: "本用例行动项目标面板 应可见", object: "page.task_target", operator: "visible", params: { targetFrom: "runtime.taskTarget" } },
      { source: { caseStepId: "Action-29", method: "playwright" }, id: "member.add_task.enabled", title: "本用例行动项目标的 \"新增行动项\" 操作 应可点击", object: "page.task_target", operator: "add_task_enabled", params: { targetFrom: "runtime.taskTarget" } },
      { source: { caseStepId: "Action-30", method: "playwright" }, id: "member.add_task", title: "点击 本用例行动项目标的 \"新增行动项\" 操作", object: "page.task_target", operator: "add_task", params: { targetFrom: "runtime.taskTarget" } },
      { source: { caseStepId: "Action-31", method: "playwright" }, id: "member.task_editor.visible", title: "新增行动项内联标题编辑器 应可见", object: "page", operator: "visible", params: { label: "编辑行动项标题" } },
      { source: { caseStepId: "Action-32", method: "playwright" }, id: "member.fill_task_title", title: "在新增行动项内联标题编辑器输入 成员测试行动项标题", object: "page", operator: "fill", params: { label: "编辑行动项标题", valueFrom: "data.memberTaskTitle" } },
      { source: { caseStepId: "Action-33", method: "playwright" }, id: "member.task_editor.submit", title: "提交新增行动项内联标题编辑器", object: "page.task_inline_editor", operator: "submit", params: { saveAs: "memberCreateTaskResponse" } },
      { source: { caseStepId: "Action-34", method: "api" }, id: "member_task.record", title: "记录 普通成员新建行动项结果中的测试行动项", object: "api.task_create_response", operator: "record_task", params: { responseFrom: "runtime.memberCreateTaskResponse", saveAs: "memberCreatedTask" } },
      { source: { caseStepId: "Action-35", method: "playwright" }, id: "member.add_subtask", title: "点击成员测试行动项的 \"新增子行动项\" 操作", object: "page.task_target", operator: "add_subtask", params: { targetFrom: "runtime.taskTarget", taskFrom: "runtime.memberCreatedTask" } },
      { source: { caseStepId: "Action-36", method: "playwright" }, id: "member.subtask_editor.visible", title: "成员测试行动项下的新增子行动项标题输入框 应可见", object: "page", operator: "visible", params: { label: "编辑子行动项标题" } },
      { source: { caseStepId: "Action-37", method: "playwright" }, id: "member.fill_subtask_label", title: "在成员测试行动项下的新增子行动项标题输入框输入 成员测试子行动项标签", object: "page", operator: "fill", params: { label: "编辑子行动项标题", valueFrom: "data.memberSubtaskLabel" } },
      { source: { caseStepId: "Action-38", method: "playwright" }, id: "member.subtask_editor.submit", title: "提交新增子行动项内联标题编辑器", object: "page.subtask_inline_editor", operator: "submit", params: { taskFrom: "runtime.memberCreatedTask", saveAs: "memberCreateSubtaskResponse" } },
      { source: { caseStepId: "Action-39", method: "api" }, id: "member_subtask.record", title: "记录 普通成员新建子行动项结果中的测试子行动项", object: "api.subtask_create_response", operator: "record_subtask", params: { responseFrom: "runtime.memberCreateSubtaskResponse", taskFrom: "runtime.memberCreatedTask", saveAs: "memberCreatedSubtask" } },
    ],
  },

  S1: {
    description: "管理员和普通成员创建的行动项与子行动项均已持久化并显示在目标面板中",
    assertions: [
      { source: { caseStepId: "S1-1", method: "playwright" }, id: "page.admin_created_task.visible", title: "本用例行动项目标面板 应显示 管理员测试行动项标题", object: "page.task_target", operator: "task_visible", params: { targetFrom: "runtime.taskTarget", taskFrom: "runtime.adminCreatedTask" } },
      { source: { caseStepId: "S1-2", method: "playwright" }, id: "page.admin_created_subtask.visible", title: "管理员测试行动项下 应显示 \"管理员子任务\" 子行动项", object: "page.task_target", operator: "subtask_visible", params: { targetFrom: "runtime.taskTarget", subtaskFrom: "runtime.adminCreatedSubtask" } },
      { source: { caseStepId: "S1-3", method: "playwright" }, id: "page.member_created_task.visible", title: "本用例行动项目标面板 应显示 成员测试行动项标题", object: "page.task_target", operator: "task_visible", params: { targetFrom: "runtime.taskTarget", taskFrom: "runtime.memberCreatedTask" } },
      { source: { caseStepId: "S1-4", method: "playwright" }, id: "page.member_created_subtask.visible", title: "成员测试行动项下 应显示 \"成员子任务\" 子行动项", object: "page.task_target", operator: "subtask_visible", params: { targetFrom: "runtime.taskTarget", subtaskFrom: "runtime.memberCreatedSubtask" } },
      {
        source: { caseStepId: "S1-5", method: "prisma" },
        id: "db.admin_created_task.present",
        title: "本用例行动项目标 应存在 标题为 `E2E-TASK-CREATE: 管理员增加行动项`、执行人为管理员的行动项",
        object: "db.task_target",
        operator: "task_present",
        params: { targetFrom: "runtime.taskTarget", titleFrom: "data.adminTaskTitle", descriptionFrom: "data.taskDescription", assigneeFrom: "data.adminName" },
      },
      { source: { caseStepId: "S1-6", method: "prisma" }, id: "db.admin_created_subtask.present", title: "管理员测试行动项 应存在 标签为 \"管理员子任务\" 的子行动项", object: "db.task", operator: "subtask_present", params: { taskFrom: "runtime.adminCreatedTask", labelFrom: "data.adminSubtaskLabel" } },
      {
        source: { caseStepId: "S1-7", method: "prisma" },
        id: "db.member_created_task.present",
        title: "本用例行动项目标 应存在 标题为 `E2E-TASK-CREATE: 成员增加行动项`、执行人为普通成员的行动项",
        object: "db.task_target",
        operator: "task_present",
        params: { targetFrom: "runtime.taskTarget", titleFrom: "data.memberTaskTitle", descriptionFrom: "data.taskDescription", assigneeFrom: "data.memberName" },
      },
      { source: { caseStepId: "S1-8", method: "prisma" }, id: "db.member_created_subtask.present", title: "成员测试行动项 应存在 标签为 \"成员子任务\" 的子行动项", object: "db.task", operator: "subtask_present", params: { taskFrom: "runtime.memberCreatedTask", labelFrom: "data.memberSubtaskLabel" } },
      {
        source: { caseStepId: "S1-9", method: "api" },
        id: "admin_created_task.matches",
        title: "管理员新建行动项结果中的行动项 应属于本用例目标，标题、说明和执行人正确",
        object: "api.task_create_response",
        operator: "matches",
        params: { taskFrom: "runtime.adminCreatedTask", targetFrom: "runtime.taskTarget", titleFrom: "data.adminTaskTitle", descriptionFrom: "data.taskDescription", assigneeFrom: "data.adminName" },
      },
      {
        source: { caseStepId: "S1-10", method: "api" },
        id: "member_created_task.matches",
        title: "普通成员新建行动项结果中的行动项 应属于本用例目标，标题、说明和执行人正确",
        object: "api.task_create_response",
        operator: "matches",
        params: { taskFrom: "runtime.memberCreatedTask", targetFrom: "runtime.taskTarget", titleFrom: "data.memberTaskTitle", descriptionFrom: "data.taskDescription", assigneeFrom: "data.memberName" },
      },
      { source: { caseStepId: "S1-11", method: "api" }, id: "session.member.still_authenticated", title: "当前会话 应仍为 普通成员的已登录会话", object: "auth.session", operator: "authenticated", params: { emailFrom: "data.memberEmail", roleFrom: "data.memberRole", status: "active" } },
    ],
  },

  Clean: {
    description: "删除测试行动项、目标、管理员和普通成员账号并恢复未登录基准状态",
    steps: [
      { source: { caseStepId: "Clean-1", method: "prisma" }, id: "db.admin_task.delete", title: "删除 本用例管理员创建的测试行动项及其子行动项", object: "db.task", operator: "delete", params: { titleFrom: "data.adminTaskTitle", taskFrom: "runtime.adminCreatedTask" } },
      { source: { caseStepId: "Clean-2", method: "prisma" }, id: "db.member_task.delete", title: "删除 本用例成员创建的测试行动项及其子行动项", object: "db.task", operator: "delete", params: { titleFrom: "data.memberTaskTitle", taskFrom: "runtime.memberCreatedTask" } },
      { source: { caseStepId: "Clean-3", method: "prisma" }, id: "db.objective.delete", title: "删除 本用例行动项目标及其派生数据", object: "db.objective", operator: "delete_by_title", params: { titleFrom: "data.objectiveTitle" } },
      { source: { caseStepId: "Clean-4", method: "api" }, id: "auth.logout", title: "注销当前登录会话", object: "auth", operator: "logout" },
      { source: { caseStepId: "Clean-5", method: "playwright" }, id: "page.runtime.stop", title: "离开当前 ORF 前端页面", object: "page.runtime", operator: "stop" },
      { source: { caseStepId: "Clean-6", method: "playwright" }, id: "browser.clear", title: "移除当前浏览器中的残留登录态", object: "browser", operator: "clear_state" },
      { source: { caseStepId: "Clean-7", method: "api" }, id: "ory.admin_sessions.revoke", title: "撤销管理员登录身份的残留登录会话", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-8", method: "api" }, id: "ory.member_sessions.revoke", title: "撤销普通成员登录身份的残留登录会话", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-9", method: "api" }, id: "ory.admin_identity.delete", title: "删除邮箱为 `orf-admin-create-task-e2e@orf.local` 的管理员登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-10", method: "api" }, id: "ory.member_identity.delete", title: "删除邮箱为 `orf-member-create-task-e2e@orf.local` 的普通成员登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-11", method: "prisma" }, id: "db.users.memberships.delete", title: "删除管理员和普通成员用户的默认团队成员关系", object: "db.user", operator: "delete_memberships", params: { emails: ["orf-admin-create-task-e2e@orf.local", "orf-member-create-task-e2e@orf.local"] } },
      { source: { caseStepId: "Clean-12", method: "prisma" }, id: "db.users.delete", title: "删除管理员和普通成员用户", object: "db.user", operator: "delete", params: { emails: ["orf-admin-create-task-e2e@orf.local", "orf-member-create-task-e2e@orf.local"] } },
      { source: { caseStepId: "Clean-13", method: "prisma" }, id: "db.admin_task.absent", title: "应不存在 标题为 `E2E-TASK-CREATE: 管理员增加行动项` 的测试行动项", object: "db.task", operator: "absent", params: { titleFrom: "data.adminTaskTitle" } },
      { source: { caseStepId: "Clean-14", method: "prisma" }, id: "db.member_task.absent", title: "应不存在 标题为 `E2E-TASK-CREATE: 成员增加行动项` 的测试行动项", object: "db.task", operator: "absent", params: { titleFrom: "data.memberTaskTitle" } },
      { source: { caseStepId: "Clean-15", method: "prisma" }, id: "db.objective.absent", title: "应不存在 标题为 `E2E-USER-CREATE-TASK: 目标前置` 的测试目标", object: "db.objective", operator: "absent", params: { titleFrom: "data.objectiveTitle" } },
      { source: { caseStepId: "Clean-16", method: "prisma" }, id: "db.users.absent", title: "应不存在 本用例独占管理员和普通成员用户", object: "db.user", operator: "absent", params: { emails: ["orf-admin-create-task-e2e@orf.local", "orf-member-create-task-e2e@orf.local"] } },
    ],
  },
} satisfies StateCaseSpec<MemberCreateTaskCaseData>;
