import { STATE_CASE_MODEL, type StateCaseSpec } from "../../_framework/types";
import type { MemberCreateTaskCaseData } from "./_support/member-create-task.context";

export const memberCreateTaskCase = {
  id: "tasks.create.member",
  title: "用户可以增加行动项和子行动项",
  model: STATE_CASE_MODEL,
  tags: ["tasks", "subtasks", "member", "happy-path"],

  data: {
    email: "orf-member-e2e@orf.local",
    password: "OrfMemberE2E!2026",
    name: "ORF Member E2E",
    role: "member",
    taskTitle: "E2E-TASK-CREATE: 用户增加行动项",
    taskDescription: "E2E 用户增加行动项说明",
    subtaskLabel: "新子任务",
  },

  B: {
    description: "系统服务、Ory、数据库和预置普通成员可用，当前浏览器未登录且测试行动项不存在",
    assertions: [
      { id: "backend.ready", title: "后端服务可用", object: "api.health", operator: "ok" },
      { id: "db.ready", title: "数据库可连接", object: "db", operator: "ready" },
      { id: "ory.ready", title: "Ory Admin API 可用", object: "ory.admin", operator: "ready" },
      {
        id: "ory.member_identity.exists",
        title: "普通成员 Ory 身份存在",
        object: "ory.identity",
        operator: "exists",
        params: { emailFrom: "data.email" },
      },
      { id: "db.member.active", title: "预置普通成员账号可用", object: "db.member", operator: "active", params: { emailFrom: "data.email" } },
      { id: "db.task_target.available", title: "存在可构造成员新增行动项起点的目标", object: "db.task_target", operator: "available" },
      {
        id: "db.test_task.absent",
        title: "测试行动项不存在",
        object: "db.task",
        operator: "absent",
        params: { titleFrom: "data.taskTitle" },
      },
      { id: "session.unauthenticated", title: "后端 session 未登录", object: "auth.session", operator: "unauthenticated" },
      { id: "cookie.absent", title: "浏览器不存在登录 cookie", object: "browser.cookie", operator: "absent" },
      { id: "storage.empty", title: "浏览器 storage 不含登录态", object: "browser.auth_storage", operator: "empty" },
    ],
  },

  Setup: {
    description: "准备可新增行动项的目标，登录普通成员并进入挑战工作台",
    steps: [
      { id: "browser.clear", title: "清理浏览器状态", object: "browser", operator: "clear_state" },
      {
        id: "db.task_target.select",
        title: "选择可构造成员新增行动项起点的目标",
        object: "db.task_target",
        operator: "select",
        params: { saveAs: "taskTarget" },
      },
      {
        id: "db.task_target.original_state_recorded",
        title: "记录目标原始状态",
        object: "db.task_target",
        operator: "original_state_recorded",
        params: { targetFrom: "runtime.taskTarget" },
      },
      {
        id: "db.task_target.prepare",
        title: "准备目标为普通成员可新增行动项状态",
        object: "db.task_target",
        operator: "prepare",
        params: { targetFrom: "runtime.taskTarget", memberNameFrom: "data.name" },
      },
      { id: "page.goto.auth", title: "打开登录页", object: "page", operator: "goto", params: { path: "/auth" } },
      { id: "fill.email", title: "输入普通成员邮箱", object: "page", operator: "fill", params: { label: "Email", valueFrom: "data.email" } },
      {
        id: "fill.password",
        title: "输入普通成员密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.password" },
      },
      { id: "click.sign_in", title: "点击登录按钮", object: "page", operator: "click", params: { role: "button", name: "Sign In" } },
      {
        id: "session.member.authenticated",
        title: "等待普通成员 session 已登录",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      { id: "page.goto.tasks", title: "打开挑战工作台", object: "page", operator: "goto", params: { path: "/tasks" } },
    ],
  },

  S0: {
    description: "普通成员已登录并位于挑战工作台，目标可见且新增行动项操作可用",
    assertions: [
      {
        id: "session.member.authenticated",
        title: "后端 session 已登录",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      { id: "url.tasks", title: "当前页面是挑战工作台", object: "page.url", operator: "match", params: { pattern: "/tasks$" } },
      {
        id: "task_target.visible",
        title: "目标面板可见",
        object: "page.task_target",
        operator: "visible",
        params: { targetFrom: "runtime.taskTarget" },
      },
      {
        id: "task_target.add_task.enabled",
        title: "目标新增行动项操作可点击",
        object: "page.task_target",
        operator: "add_task_enabled",
        params: { targetFrom: "runtime.taskTarget" },
      },
      {
        id: "db.task_target.can_create",
        title: "目标允许普通成员新增行动项",
        object: "db.task_target",
        operator: "can_create_task",
        params: { targetFrom: "runtime.taskTarget", memberNameFrom: "data.name" },
      },
      {
        id: "db.target_task.absent",
        title: "目标不存在测试行动项",
        object: "db.task_target",
        operator: "task_absent",
        params: { targetFrom: "runtime.taskTarget", titleFrom: "data.taskTitle" },
      },
    ],
  },

  Action: {
    description: "普通成员通过页面新增测试行动项，并在该行动项下新增子行动项",
    steps: [
      {
        id: "click.add_task",
        title: "点击新增行动项",
        object: "page.task_target",
        operator: "add_task",
        params: { targetFrom: "runtime.taskTarget" },
      },
      {
        id: "modal.visible",
        title: "新建行动项弹窗可见",
        object: "page.task_modal",
        operator: "visible",
      },
      {
        id: "fill.task_title",
        title: "输入行动项标题",
        object: "page",
        operator: "fill",
        params: { label: "行动项标题", valueFrom: "data.taskTitle" },
      },
      {
        id: "fill.task_description",
        title: "输入行动项说明",
        object: "page",
        operator: "fill",
        params: { label: "说明", valueFrom: "data.taskDescription" },
      },
      {
        id: "capture.create_task_response",
        title: "监听新建行动项请求",
        object: "api",
        operator: "capture_response",
        params: { urlEndsWith: "/api/tasks", method: "POST", saveAs: "createTaskResponse" },
      },
      {
        id: "click.save_task",
        title: "点击保存行动项",
        object: "page",
        operator: "click",
        params: { role: "button", name: "保存行动项" },
      },
      {
        id: "create_task_response.record",
        title: "记录新建行动项",
        object: "api.task_create_response",
        operator: "record_task",
        params: { responseFrom: "runtime.createTaskResponse", saveAs: "createdTask" },
      },
      {
        id: "capture.create_subtask_response",
        title: "监听新建子行动项请求",
        object: "api.subtask_create",
        operator: "capture_response",
        params: { taskFrom: "runtime.createdTask", saveAs: "createSubtaskResponse" },
      },
      {
        id: "click.add_subtask",
        title: "点击新增子行动项",
        object: "page.task_target",
        operator: "add_subtask",
        params: { targetFrom: "runtime.taskTarget", taskFrom: "runtime.createdTask" },
      },
      {
        id: "create_subtask_response.record",
        title: "记录新建子行动项",
        object: "api.subtask_create_response",
        operator: "record_subtask",
        params: { responseFrom: "runtime.createSubtaskResponse", taskFrom: "runtime.createdTask", labelFrom: "data.subtaskLabel", saveAs: "createdSubtask" },
      },
    ],
  },

  S1: {
    description: "测试行动项和子行动项已经持久化并显示在目标面板中，普通成员仍保持登录",
    assertions: [
      {
        id: "create_task_response.ok",
        title: "新建行动项接口响应成功",
        object: "api.response",
        operator: "ok",
        params: { responseFrom: "runtime.createTaskResponse", status: 200 },
      },
      {
        id: "create_subtask_response.ok",
        title: "新建子行动项接口响应成功",
        object: "api.response",
        operator: "ok",
        params: { responseFrom: "runtime.createSubtaskResponse", status: 200 },
      },
      {
        id: "created_task.matches",
        title: "新建行动项接口返回内容正确",
        object: "api.task_create_response",
        operator: "matches",
        params: {
          taskFrom: "runtime.createdTask",
          targetFrom: "runtime.taskTarget",
          titleFrom: "data.taskTitle",
          descriptionFrom: "data.taskDescription",
          assigneeFrom: "data.name",
        },
      },
      {
        id: "db.created_task.present",
        title: "数据库存在测试行动项",
        object: "db.task_target",
        operator: "task_present",
        params: { targetFrom: "runtime.taskTarget", titleFrom: "data.taskTitle", descriptionFrom: "data.taskDescription", assigneeFrom: "data.name" },
      },
      {
        id: "db.created_subtask.present",
        title: "数据库存在测试子行动项",
        object: "db.task",
        operator: "subtask_present",
        params: { taskFrom: "runtime.createdTask", labelFrom: "data.subtaskLabel" },
      },
      {
        id: "page.created_task.visible",
        title: "目标面板显示测试行动项",
        object: "page.task_target",
        operator: "task_visible",
        params: { targetFrom: "runtime.taskTarget", taskFrom: "runtime.createdTask" },
      },
      {
        id: "page.created_subtask.visible",
        title: "目标面板显示测试子行动项",
        object: "page.task_target",
        operator: "subtask_visible",
        params: { targetFrom: "runtime.taskTarget", taskFrom: "runtime.createdTask", subtaskFrom: "runtime.createdSubtask" },
      },
      {
        id: "session.member.still_authenticated",
        title: "普通成员仍保持登录",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
    ],
  },

  Clean: {
    description: "删除测试行动项，恢复目标原始状态并退出登录",
    steps: [
      {
        id: "db.task.delete",
        title: "删除测试行动项",
        object: "db.task",
        operator: "delete",
        params: { titleFrom: "data.taskTitle", taskFrom: "runtime.createdTask" },
      },
      {
        id: "db.task_target.restore",
        title: "恢复目标原始状态",
        object: "db.task_target",
        operator: "restore",
        params: { targetFrom: "runtime.taskTarget" },
      },
      { id: "auth.logout", title: "退出当前登录态", object: "auth", operator: "logout" },
      { id: "browser.clear", title: "清理浏览器状态", object: "browser", operator: "clear_state" },
      {
        id: "ory.member_identity.exists",
        title: "普通成员 Ory 身份仍然存在",
        object: "ory.identity",
        operator: "exists",
        params: { emailFrom: "data.email" },
      },
      { id: "db.member.active", title: "预置普通成员账号仍然可用", object: "db.member", operator: "active", params: { emailFrom: "data.email" } },
    ],
  },
} satisfies StateCaseSpec<MemberCreateTaskCaseData>;
