import { STATE_CASE_MODEL, type StateCaseSpec } from "../../_framework/types";
import type { MemberCreateTaskCaseData } from "./_support/member-create-task.context";

export const memberCreateTaskCase = {
  id: "tasks.member-create-task",
  title: "用户可以增加行动项和子行动项",
  model: STATE_CASE_MODEL,
  tags: ["tasks", "subtasks", "member", "happy-path"],

  data: {
    email: "orf-member-create-task-e2e@orf.local",
    password: "OrfMemberCreateTaskE2E!2026",
    name: "ORF Member Create Task E2E",
    role: "member",
    objectiveId: "obj-testd-member-create-task",
    objectiveTitle: "E2E-MEMBER-CREATE-TASK: 目标前置",
    taskTitle: "E2E-TASK-CREATE: 用户增加行动项",
    taskDescription: "执行支撑目标的下一步技术任务。",
    subtaskLabel: "新子任务",
  },

  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      {
        source: { caseStepId: "B-1", method: "api" },
        id: "frontend.ready",
        title: "前端服务 应可用",
        object: "frontend.service",
        operator: "available",
      },
      {
        source: { caseStepId: "B-2", method: "api" },
        id: "backend.ready",
        title: "后端服务 应可用",
        object: "api.health",
        operator: "ok",
      },
      {
        source: { caseStepId: "B-3", method: "api" },
        id: "frontend.login_entry.accessible",
        title: "前端登录页入口 应可访问",
        object: "frontend.login_entry",
        operator: "accessible",
      },
      {
        source: { caseStepId: "B-4", method: "api" },
        id: "session.endpoint.accessible",
        title: "当前会话查询接口 应可访问",
        object: "auth.session",
        operator: "accessible",
      },
      {
        source: { caseStepId: "B-5", method: "prisma" },
        id: "db.ready",
        title: "ORF 数据库 应可连接",
        object: "db",
        operator: "ready",
      },
      {
        source: { caseStepId: "B-6", method: "prisma" },
        id: "db.schema.current",
        title: "ORF 数据库 schema 应为 当前测试版本",
        object: "db.schema",
        operator: "current",
      },
      {
        source: { caseStepId: "B-7", method: "api" },
        id: "ory.admin_public.ready",
        title: "Ory/Kratos Admin/Public API 应可访问",
        object: "ory.admin_public",
        operator: "ready",
      },
      {
        source: { caseStepId: "B-8", method: "api" },
        id: "session.unauthenticated",
        title: "当前会话 应为 未登录",
        object: "auth.session",
        operator: "unauthenticated",
      },
      {
        source: { caseStepId: "B-9", method: "playwright" },
        id: "cookie.absent",
        title: "当前浏览器 应不存在 Ory session cookie",
        object: "browser.cookie",
        operator: "absent",
      },
      {
        source: { caseStepId: "B-10", method: "playwright" },
        id: "storage.empty",
        title: "当前浏览器 storage 应不包含 登录态",
        object: "browser.auth_storage",
        operator: "empty",
      },
    ],
  },

  Setup: {
    description: "准备普通成员账号和本用例独占重估目标，登录普通成员并进入挑战工作台",
    steps: [
      {
        source: { caseStepId: "Setup-1", method: "prisma" },
        id: "db.task.delete_residue",
        title: "删除可能残留的本用例测试行动项",
        object: "db.task",
        operator: "delete",
        params: { titleFrom: "data.taskTitle" },
      },
      {
        source: { caseStepId: "Setup-2", method: "prisma" },
        id: "db.objective.delete_residue",
        title: "删除可能残留的本用例目标及其派生数据",
        object: "db.objective",
        operator: "delete_by_title",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Setup-3", method: "api" },
        id: "ory.member_identity.upsert",
        title: '准备邮箱为 "orf-member-create-task-e2e@orf.local" 的普通成员登录身份，并设置固定测试密码',
        object: "ory.identity",
        operator: "upsert_password",
        params: {
          emailFrom: "data.email",
          nameFrom: "data.name",
          passwordFrom: "data.password",
          saveAs: "memberIdentity",
        },
      },
      {
        source: { caseStepId: "Setup-4", method: "prisma" },
        id: "db.member.upsert",
        title: '准备邮箱为 "orf-member-create-task-e2e@orf.local"、角色为 member、状态为 active 的普通成员用户和默认团队成员关系',
        object: "db.user",
        operator: "upsert",
        params: {
          emailFrom: "data.email",
          nameFrom: "data.name",
          roleFrom: "data.role",
          status: "active",
          identityIdFrom: "runtime.memberIdentity.id",
          saveAs: "memberUser",
        },
      },
      {
        source: { caseStepId: "Setup-5", method: "prisma" },
        id: "db.objective.upsert_task_target",
        title: '创建标题为 "E2E-MEMBER-CREATE-TASK: 目标前置"、流转状态为 reestimating、阶段为 orfReestimate 的本用例行动项目标',
        object: "db.objective",
        operator: "upsert",
        params: {
          idFrom: "data.objectiveId",
          titleFrom: "data.objectiveTitle",
          teamIdFrom: "runtime.memberUser.teamId",
          stage: "orfReestimate",
          flowStatus: "reestimating",
          status: "Draft",
          saveAs: "fixtureObjective",
        },
      },
      {
        source: { caseStepId: "Setup-6", method: "prisma" },
        id: "db.task_target.from_objective",
        title: "记录本用例行动项目标为 runtime.taskTarget",
        object: "db.task_target",
        operator: "from_objective",
        params: { objectiveIdFrom: "runtime.fixtureObjective.id", saveAs: "taskTarget" },
      },
      {
        source: { caseStepId: "Setup-7", method: "prisma" },
        id: "db.task_target.prepare",
        title: "设置本用例行动项目标的挑战者包含普通成员",
        object: "db.task_target",
        operator: "prepare",
        params: { targetFrom: "runtime.taskTarget", memberNameFrom: "data.name" },
      },
      {
        source: { caseStepId: "Setup-8", method: "api" },
        id: "ory.member_sessions.revoke",
        title: "撤销普通成员登录身份可能残留的 Ory session",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Setup-9", method: "playwright" },
        id: "browser.clear",
        title: "清空当前浏览器上下文的 cookies/localStorage/sessionStorage",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "Setup-10", method: "playwright" },
        id: "page.goto.auth",
        title: "打开 登录页",
        object: "page",
        operator: "goto",
        params: { path: "/auth" },
      },
      {
        source: { caseStepId: "Setup-11", method: "playwright" },
        id: "fill.email",
        title: "在邮箱输入框输入普通成员测试邮箱",
        object: "page",
        operator: "fill",
        params: { label: "Email", valueFrom: "data.email" },
      },
      {
        source: { caseStepId: "Setup-12", method: "playwright" },
        id: "fill.password",
        title: "在密码输入框输入普通成员测试密码",
        object: "page",
        operator: "fill",
        params: { label: "Password", exact: true, valueFrom: "data.password" },
      },
      {
        source: { caseStepId: "Setup-13", method: "playwright" },
        id: "click.sign_in",
        title: '点击 "Sign In" 登录操作',
        object: "page",
        operator: "click",
        params: { role: "button", name: "Sign In" },
      },
      {
        source: { caseStepId: "Setup-14", method: "api" },
        id: "session.member.authenticated",
        title: "当前会话 应为 普通成员已登录",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      {
        source: { caseStepId: "Setup-15", method: "playwright" },
        id: "page.goto.tasks",
        title: "打开 挑战工作台",
        object: "page",
        operator: "goto",
        params: { path: "/tasks" },
      },
    ],
  },

  S0: {
    description: "普通成员已登录并位于挑战工作台，本用例目标可见且新增行动项操作可用",
    assertions: [
      {
        source: { caseStepId: "S0-1", method: "api" },
        id: "session.member.authenticated",
        title: '当前会话 应为 邮箱为 "orf-member-create-task-e2e@orf.local"、角色为 member、状态为 active 的已登录会话',
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
      {
        source: { caseStepId: "S0-2", method: "playwright" },
        id: "url.tasks",
        title: "当前页面 应为 挑战工作台",
        object: "page.url",
        operator: "match",
        params: { pattern: "/tasks$" },
      },
      {
        source: { caseStepId: "S0-3", method: "playwright" },
        id: "task_target.visible",
        title: "本用例行动项目标面板 应可见",
        object: "page.task_target",
        operator: "visible",
        params: { targetFrom: "runtime.taskTarget" },
      },
      {
        source: { caseStepId: "S0-4", method: "playwright" },
        id: "task_target.add_task.enabled",
        title: '本用例行动项目标的 "新增行动项" 操作 应可点击',
        object: "page.task_target",
        operator: "add_task_enabled",
        params: { targetFrom: "runtime.taskTarget" },
      },
      {
        source: { caseStepId: "S0-5", method: "prisma" },
        id: "db.task_target.can_create",
        title: "本用例行动项目标 应允许 普通成员新增行动项",
        object: "db.task_target",
        operator: "can_create_task",
        params: { targetFrom: "runtime.taskTarget", memberNameFrom: "data.name" },
      },
      {
        source: { caseStepId: "S0-6", method: "prisma" },
        id: "db.target_task.absent",
        title: '本用例行动项目标 应不存在 标题为 "E2E-TASK-CREATE: 用户增加行动项" 的行动项',
        object: "db.task_target",
        operator: "task_absent",
        params: { targetFrom: "runtime.taskTarget", titleFrom: "data.taskTitle" },
      },
    ],
  },

  Action: {
    description: "普通成员通过页面新增测试行动项，并在该行动项下新增子行动项",
    steps: [
      {
        source: { caseStepId: "Action-1", method: "playwright" },
        id: "click.add_task",
        title: '点击本用例行动项目标的 "新增行动项" 操作',
        object: "page.task_target",
        operator: "add_task",
        params: { targetFrom: "runtime.taskTarget" },
      },
      {
        source: { caseStepId: "Action-2", method: "playwright" },
        id: "task_inline_editor.visible",
        title: "新增行动项内联标题编辑器 应可见",
        object: "page",
        operator: "visible",
        params: { label: "编辑行动项标题" },
      },
      {
        source: { caseStepId: "Action-3", method: "playwright" },
        id: "fill.task_title",
        title: "在新增行动项内联标题编辑器输入测试行动项标题",
        object: "page",
        operator: "fill",
        params: { label: "编辑行动项标题", valueFrom: "data.taskTitle" },
      },
      {
        source: { caseStepId: "Action-4", method: "api" },
        id: "capture.create_task_response",
        title: "在提交新增行动项内联标题前注册新建行动项接口响应捕获",
        object: "api",
        operator: "capture_response",
        params: { urlEndsWith: "/api/tasks", method: "POST", saveAs: "createTaskResponse" },
      },
      {
        source: { caseStepId: "Action-5", method: "playwright" },
        id: "task_inline_editor.submit",
        title: "提交新增行动项内联标题编辑器",
        object: "page.task_inline_editor",
        operator: "submit",
      },
      {
        source: { caseStepId: "Action-6", method: "api" },
        id: "create_task_response.record",
        title: "记录新建行动项接口返回的行动项为 runtime.createdTask",
        object: "api.task_create_response",
        operator: "record_task",
        params: { responseFrom: "runtime.createTaskResponse", saveAs: "createdTask" },
      },
      {
        source: { caseStepId: "Action-7", method: "playwright" },
        id: "click.add_subtask",
        title: '点击测试行动项的 "新增子行动项" 操作',
        object: "page.task_target",
        operator: "add_subtask",
        params: { targetFrom: "runtime.taskTarget", taskFrom: "runtime.createdTask" },
      },
      {
        source: { caseStepId: "Action-8", method: "playwright" },
        id: "subtask_inline_editor.visible",
        title: "新增子行动项内联标题编辑器 应可见",
        object: "page",
        operator: "visible",
        params: { label: "编辑子行动项标题" },
      },
      {
        source: { caseStepId: "Action-9", method: "playwright" },
        id: "fill.subtask_label",
        title: "在新增子行动项内联标题编辑器输入测试子行动项标签",
        object: "page",
        operator: "fill",
        params: { label: "编辑子行动项标题", valueFrom: "data.subtaskLabel" },
      },
      {
        source: { caseStepId: "Action-10", method: "api" },
        id: "capture.create_subtask_response",
        title: "在提交新增子行动项内联标题前注册新建子行动项接口响应捕获",
        object: "api.subtask_create",
        operator: "capture_response",
        params: { taskFrom: "runtime.createdTask", saveAs: "createSubtaskResponse" },
      },
      {
        source: { caseStepId: "Action-11", method: "playwright" },
        id: "subtask_inline_editor.submit",
        title: "提交新增子行动项内联标题编辑器",
        object: "page.subtask_inline_editor",
        operator: "submit",
      },
      {
        source: { caseStepId: "Action-12", method: "api" },
        id: "create_subtask_response.record",
        title: "记录新建子行动项为 runtime.createdSubtask",
        object: "api.subtask_create_response",
        operator: "record_subtask",
        params: { responseFrom: "runtime.createSubtaskResponse", taskFrom: "runtime.createdTask", saveAs: "createdSubtask" },
      },
    ],
  },

  S1: {
    description: "测试行动项和子行动项已经持久化并显示在目标面板中，普通成员仍保持登录",
    assertions: [
      {
        source: { caseStepId: "S1-1", method: "api" },
        id: "create_task_response.ok",
        title: "新建行动项接口响应 应成功",
        object: "api.response",
        operator: "ok",
        params: { responseFrom: "runtime.createTaskResponse", status: 200 },
      },
      {
        source: { caseStepId: "S1-2", method: "api" },
        id: "create_subtask_response.ok",
        title: "新建子行动项接口响应 应成功",
        object: "api.response",
        operator: "ok",
        params: { responseFrom: "runtime.createSubtaskResponse", status: 200 },
      },
      {
        source: { caseStepId: "S1-3", method: "api" },
        id: "created_task.matches",
        title: "新建行动项接口返回的行动项 应属于本用例目标，标题、说明和执行人正确",
        object: "api.task_create_response",
        operator: "matches",
        params: {
          taskFrom: "runtime.createdTask",
          targetFrom: "runtime.taskTarget",
          titleFrom: "data.taskTitle",
          descriptionFrom: "data.taskDescription",
          assigneeFrom: "data.name",
        },
      },
      {
        source: { caseStepId: "S1-4", method: "prisma" },
        id: "db.created_task.present",
        title: '本用例行动项目标 应存在 标题为 "E2E-TASK-CREATE: 用户增加行动项"、执行人为普通成员的行动项',
        object: "db.task_target",
        operator: "task_present",
        params: { targetFrom: "runtime.taskTarget", titleFrom: "data.taskTitle", descriptionFrom: "data.taskDescription", assigneeFrom: "data.name" },
      },
      {
        source: { caseStepId: "S1-5", method: "prisma" },
        id: "db.created_subtask.present",
        title: '测试行动项 应存在 标签为 "新子任务" 的子行动项',
        object: "db.task",
        operator: "subtask_present",
        params: { taskFrom: "runtime.createdTask", labelFrom: "data.subtaskLabel" },
      },
      {
        source: { caseStepId: "S1-6", method: "playwright" },
        id: "page.created_task.visible",
        title: "本用例行动项目标面板 应显示 测试行动项标题",
        object: "page.task_target",
        operator: "task_visible",
        params: { targetFrom: "runtime.taskTarget", taskFrom: "runtime.createdTask" },
      },
      {
        source: { caseStepId: "S1-7", method: "playwright" },
        id: "page.created_subtask.visible",
        title: '测试行动项下 应显示 "新子任务" 子行动项',
        object: "page.task_target",
        operator: "subtask_visible",
        params: { targetFrom: "runtime.taskTarget", subtaskFrom: "runtime.createdSubtask" },
      },
      {
        source: { caseStepId: "S1-8", method: "api" },
        id: "session.member.still_authenticated",
        title: "当前会话 应保持 普通成员已登录",
        object: "auth.session",
        operator: "authenticated",
        params: { emailFrom: "data.email", roleFrom: "data.role", status: "active" },
      },
    ],
  },

  Clean: {
    description: "删除测试行动项、目标、普通成员账号和浏览器运行态",
    steps: [
      {
        source: { caseStepId: "Clean-1", method: "prisma" },
        id: "db.task.delete",
        title: "删除本用例创建的测试行动项及其子行动项",
        object: "db.task",
        operator: "delete",
        params: { titleFrom: "data.taskTitle", taskFrom: "runtime.createdTask" },
      },
      {
        source: { caseStepId: "Clean-2", method: "prisma" },
        id: "db.objective.delete",
        title: "删除本用例行动项目标及其派生数据",
        object: "db.objective",
        operator: "delete_by_title",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Clean-3", method: "api" },
        id: "auth.logout",
        title: "调用退出登录接口撤销当前登录会话",
        object: "auth",
        operator: "logout",
      },
      {
        source: { caseStepId: "Clean-4", method: "playwright" },
        id: "page.runtime.stop",
        title: "当前页面离开 ORF 前端应用",
        object: "page.runtime",
        operator: "stop",
      },
      {
        source: { caseStepId: "Clean-5", method: "playwright" },
        id: "browser.clear",
        title: "清空当前浏览器上下文的 cookies/localStorage/sessionStorage",
        object: "browser",
        operator: "clear_state",
      },
      {
        source: { caseStepId: "Clean-6", method: "api" },
        id: "ory.member_sessions.revoke",
        title: "撤销普通成员登录身份的残留 Ory session",
        object: "ory.sessions",
        operator: "revoke_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-7", method: "api" },
        id: "ory.member_identity.delete",
        title: '删除邮箱为 "orf-member-create-task-e2e@orf.local" 的普通成员登录身份',
        object: "ory.identity",
        operator: "delete_by_email",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-8", method: "prisma" },
        id: "db.member.memberships.delete",
        title: "删除普通成员用户的默认团队成员关系",
        object: "db.user",
        operator: "delete_memberships",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-9", method: "prisma" },
        id: "db.member.delete",
        title: '删除邮箱为 "orf-member-create-task-e2e@orf.local" 的普通成员用户',
        object: "db.user",
        operator: "delete",
        params: { emailFrom: "data.email" },
      },
      {
        source: { caseStepId: "Clean-10", method: "prisma" },
        id: "db.task.absent",
        title: '应不存在 标题为 "E2E-TASK-CREATE: 用户增加行动项" 的测试行动项',
        object: "db.task",
        operator: "absent",
        params: { titleFrom: "data.taskTitle" },
      },
      {
        source: { caseStepId: "Clean-11", method: "prisma" },
        id: "db.objective.absent",
        title: '应不存在 标题为 "E2E-MEMBER-CREATE-TASK: 目标前置" 的测试目标',
        object: "db.objective",
        operator: "absent",
        params: { titleFrom: "data.objectiveTitle" },
      },
      {
        source: { caseStepId: "Clean-12", method: "prisma" },
        id: "db.member.absent",
        title: '应不存在 邮箱为 "orf-member-create-task-e2e@orf.local" 的普通成员用户',
        object: "db.user",
        operator: "absent",
        params: { emailFrom: "data.email" },
      },
    ],
  },
} satisfies StateCaseSpec<MemberCreateTaskCaseData>;
