import { STATE_CASE_MODEL, type StateCaseSpec, type StepExecutionMethod, type StepSpec } from "../../_framework/types";
import type { SystemLoginBackgroundCaseData } from "./_support/login-background.context";

function step(
  caseStepId: string,
  method: StepExecutionMethod,
  id: string,
  title: string,
  object: string,
  operator: string,
  params?: Record<string, unknown>,
): StepSpec {
  return {
    source: { caseStepId, method },
    id,
    title,
    object,
    operator,
    ...(params ? { params } : {}),
  };
}

export const systemLoginBackgroundCase = {
  id: "system.login-background.configure",
  title: "14-系统设置登录页背景配置",
  model: STATE_CASE_MODEL,
  tags: ["system", "settings", "login-background"],
  data: {
    admin: {
      email: "orf-system-login-background-admin-e2e@orf.local",
      password: "OrfSystemLoginBackgroundAdminE2E!2026",
      name: "ORF System Login Background Admin E2E",
      role: "admin",
    },
    defaultLandingPath: "/bounties",
    settingsPath: "/system/settings",
    uploadFileBaseName: "zzzz-system-login-background-e2e.png",
    switchIntervalMinutes: 5,
  },
  B: {
    description: "系统服务、对象存储、数据库、认证系统可用，浏览器处于未登录基准状态",
    assertions: [
      step("B-1", "api", "frontend.ready", "前端服务 应可用", "frontend.service", "available"),
      step("B-2", "api", "backend.ready", "后端服务 应可用", "api.health", "ok"),
      step("B-3", "api", "frontend.login_entry.accessible", "前端登录页入口 应可访问", "frontend.login_entry", "accessible"),
      step("B-4", "api", "session.endpoint.accessible", "当前会话查询能力 应可用", "auth.session", "accessible"),
      step("B-5", "prisma", "db.ready", "ORF 数据库 应可连接", "db", "ready"),
      step("B-6", "prisma", "db.schema.current", "ORF 数据库 schema 应为 当前测试版本", "db.schema", "current"),
      step("B-7", "api", "ory.admin_public.ready", "Ory/Kratos 认证服务的管理和公共访问能力 应可用", "ory.admin_public", "ready"),
      step("B-8", "api", "object_storage.system_background.ready", "对象存储服务 应可上传和读取系统背景图片", "object_storage.system_background", "ready"),
      step("B-9", "api", "session.unauthenticated", "当前会话 应为 未登录", "auth.session", "unauthenticated"),
      step("B-10", "playwright", "cookie.absent", "当前浏览器 应不存在 Ory 登录会话 cookie", "browser.cookie", "absent"),
      step("B-11", "playwright", "storage.empty", "当前浏览器 应不保留本地登录态", "browser.auth_storage", "empty"),
    ],
  },
  Setup: {
    description: "准备管理员测试用户，记录系统登录页背景原配置，并进入系统设置页面",
    steps: [
      step("Setup-1", "api", "ory.admin_identity.upsert", "准备邮箱为 `orf-system-login-background-admin-e2e@orf.local`、使用固定测试密码的登录页背景配置管理员测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.admin.email", passwordFrom: "data.admin.password", nameFrom: "data.admin.name", saveAs: "adminIdentity" }),
      step("Setup-2", "prisma", "db.admin_user.upsert", "准备姓名为 \"ORF System Login Background Admin E2E\"、邮箱为 `orf-system-login-background-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的登录页背景配置管理员测试用户", "db.user", "upsert", { emailFrom: "data.admin.email", passwordFrom: "data.admin.password", nameFrom: "data.admin.name", roleFrom: "data.admin.role", status: "active", identityIdFrom: "runtime.adminIdentity.id", saveAs: "adminUser" }),
      step("Setup-3", "api", "login_background.config.capture", "记录系统当前登录页背景配置", "system.login_background_config", "capture", { saveAs: "originalLoginBackgroundConfig" }),
      step("Setup-4", "api", "admin.preferences.default_landing_path.set", "设置登录页背景配置管理员测试用户默认进入页面为 首页（默认系统页）", "user.preferences", "set_default_landing_path_by_email", { emailFrom: "data.admin.email", pathFrom: "data.defaultLandingPath" }),
      step("Setup-5", "api", "ory.admin_sessions.revoke", "撤销邮箱为 `orf-system-login-background-admin-e2e@orf.local` 的登录页背景配置管理员测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.admin.email" }),
      step("Setup-6", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Setup-7", "playwright", "page.goto.auth", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Setup-8", "playwright", "fill.admin_email", "在邮箱输入框输入 `orf-system-login-background-admin-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.admin.email" }),
      step("Setup-9", "playwright", "fill.admin_password", "在密码输入框输入登录页背景配置管理员测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.admin.password" }),
      step("Setup-10", "playwright", "click.sign_in", "点击 \"Sign In\" 登录操作", "page.login_form", "submit", { saveAs: "adminLoginResponse" }),
      step("Setup-11", "api", "session.admin_authenticated", "当前会话 应为 邮箱为 `orf-system-login-background-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
      step("Setup-12", "playwright", "page.goto.settings", "打开 系统设置页面", "page", "goto", { pathFrom: "data.settingsPath" }),
    ],
  },
  S0: {
    description: "管理员已登录并位于系统设置页面的皮肤设置模块",
    assertions: [
      step("S0-1", "api", "session.admin_authenticated", "当前会话 应为 邮箱为 `orf-system-login-background-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
      step("S0-2", "playwright", "url.settings", "当前页面 应为 系统设置页面", "page.url", "match", { pattern: "/system/settings$" }),
      step("S0-3", "playwright", "settings.skin_module.visible", "系统设置页面的皮肤设置模块 应可见", "page.system_settings_skin_module", "visible"),
      step("S0-4", "playwright", "settings.login_background.visible", "系统设置页面的登录页背景设置入口 应可见", "page.system_settings_skin_slot", "visible", { label: "登录页" }),
      step("S0-5", "playwright", "settings.upload.visible", "系统设置页面的上传图片操作 应可见", "page.system_settings_skin_upload", "visible"),
      step("S0-6", "playwright", "settings.save.visible", "系统设置页面的保存皮肤设置操作 应可见", "page.system_settings_skin_save", "visible"),
    ],
  },
  Action: {
    description: "上传并配置系统登录页背景，然后回到未登录登录页验证展示",
    steps: [
      step("Action-1", "playwright", "settings.login_background.click", "点击 系统设置页面的登录页背景设置入口", "page.system_settings_skin_slot", "click", { label: "登录页" }),
      step("Action-2", "playwright", "settings.login_background.upload", "上传登录页背景配置测试图片", "page.system_settings_login_background_upload", "upload", { fileNameFrom: "data.uploadFileBaseName", saveAs: "uploadedLoginBackground" }),
      step("Action-3", "playwright", "settings.login_background.select_uploaded", "在系统设置页面的背景图片列表中选择登录页背景配置测试图片", "page.system_settings_background_card", "select", { backgroundFrom: "runtime.uploadedLoginBackground" }),
      step("Action-4", "playwright", "settings.login_background.mode.switchable", "将登录页背景模式设置为 轮换", "page.system_settings_background_mode", "set", { value: "轮换" }),
      step("Action-5", "playwright", "settings.login_background.trigger.interval", "将登录页背景触发方式设置为 定时", "page.system_settings_background_trigger", "set", { value: "定时" }),
      step("Action-6", "playwright", "settings.login_background.order.random", "将登录页背景切换规则设置为 随机", "page.system_settings_background_order", "set", { value: "随机" }),
      step("Action-7", "playwright", "settings.login_background.interval.five", "将登录页背景切换间隔设置为 5 分钟", "page.system_settings_background_interval", "set", { valueFrom: "data.switchIntervalMinutes" }),
      step("Action-8", "playwright", "settings.login_background.save", "点击 系统设置页面的保存皮肤设置操作", "page.system_settings_skin_save", "click"),
      step("Action-9", "api", "auth.logout", "注销当前登录会话", "auth", "logout"),
      step("Action-10", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Action-11", "playwright", "page.goto.auth.with_background", "打开 ORF 登录页", "page.auth_login", "goto_with_uploaded_background", { backgroundFrom: "runtime.uploadedLoginBackground" }),
    ],
  },
  S1: {
    description: "登录页背景配置已保存并应用到登录页",
    assertions: [
      step("S1-1", "api", "login_background.config.fixed_background", "系统登录页背景配置的固定背景图片 应为 登录页背景配置测试图片", "system.login_background_config", "fixed_background_is", { backgroundFrom: "runtime.uploadedLoginBackground" }),
      step("S1-2", "api", "login_background.config.mode", "系统登录页背景配置的背景模式 应为 轮换", "system.login_background_config", "mode_is", { mode: "switchable" }),
      step("S1-3", "api", "login_background.config.trigger", "系统登录页背景配置的触发方式 应为 定时", "system.login_background_config", "switch_trigger_is", { switchTrigger: "interval" }),
      step("S1-4", "api", "login_background.config.order", "系统登录页背景配置的切换规则 应为 随机", "system.login_background_config", "switch_order_is", { switchOrder: "random" }),
      step("S1-5", "api", "login_background.config.interval", "系统登录页背景配置的切换间隔 应为 5 分钟", "system.login_background_config", "switch_interval_is", { minutesFrom: "data.switchIntervalMinutes" }),
      step("S1-6", "api", "login_background.uploaded.exists", "登录页背景配置测试图片 应存在于系统背景图片列表", "system.login_background_image", "exists", { backgroundFrom: "runtime.uploadedLoginBackground" }),
      step("S1-7", "playwright", "auth.login_background.visible", "ORF 登录页 应展示登录页背景配置测试图片", "page.auth_login_background", "visible", { backgroundFrom: "runtime.uploadedLoginBackground" }),
      step("S1-8", "playwright", "auth.email.visible", "ORF 登录页的邮箱输入框 应可见", "page", "visible", { label: "Email" }),
      step("S1-9", "playwright", "auth.password.visible", "ORF 登录页的密码输入框 应可见", "page", "visible", { label: "Password", exact: true }),
      step("S1-10", "api", "session.unauthenticated", "当前会话 应为 未登录", "auth.session", "unauthenticated"),
    ],
  },
  Clean: {
    description: "恢复原系统登录页背景配置，删除测试图片和测试管理员",
    steps: [
      step("Clean-1", "playwright", "page.runtime.stop", "离开当前 ORF 前端页面", "page.runtime", "stop"),
      step("Clean-2", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Clean-3", "api", "login_background.config.restore", "恢复系统登录页背景配置为 Action 前记录的配置", "system.login_background_config", "restore", { configFrom: "runtime.originalLoginBackgroundConfig.config" }),
      step("Clean-4", "api", "login_background.uploaded.delete", "删除登录页背景配置测试图片", "system.login_background_image", "delete", { backgroundFrom: "runtime.uploadedLoginBackground" }),
      step("Clean-5", "api", "ory.admin_sessions.revoke", "撤销邮箱为 `orf-system-login-background-admin-e2e@orf.local` 的登录页背景配置管理员测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-6", "api", "ory.admin_identity.delete", "删除邮箱为 `orf-system-login-background-admin-e2e@orf.local` 的登录页背景配置管理员测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-7", "api", "admin.preferences.default_landing_path.reset", "恢复邮箱为 `orf-system-login-background-admin-e2e@orf.local` 的默认进入页面为 系统默认", "user.preferences", "reset_default_landing_path_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-8", "prisma", "db.admin_user.memberships.delete", "删除邮箱为 `orf-system-login-background-admin-e2e@orf.local` 的登录页背景配置管理员测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.admin.email" }),
      step("Clean-9", "prisma", "db.admin_user.delete", "删除邮箱为 `orf-system-login-background-admin-e2e@orf.local` 的登录页背景配置管理员测试用户", "db.user", "delete", { emailFrom: "data.admin.email" }),
      step("Clean-10", "api", "ory.admin_identity.absent", "邮箱为 `orf-system-login-background-admin-e2e@orf.local` 的登录页背景配置管理员测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.admin.email" }),
      step("Clean-11", "prisma", "db.admin_user.absent", "邮箱为 `orf-system-login-background-admin-e2e@orf.local` 的登录页背景配置管理员测试用户 应不存在", "db.user", "absent", { emailFrom: "data.admin.email" }),
    ],
  },
} satisfies StateCaseSpec<SystemLoginBackgroundCaseData>;
