import { STATE_CASE_MODEL, type StateCaseSpec, type StepExecutionMethod, type StepSpec } from "../../_framework/types";
import type { PersonalSettingsAvatarCaseData } from "./_support/personal-settings-avatar.context";

function step(
  caseStepId: string,
  method: StepExecutionMethod,
  id: string,
  title: string,
  object: string,
  operator: string,
  params?: Record<string, unknown>,
): StepSpec {
  return {
    source: { caseStepId, method },
    id,
    title,
    object,
    operator,
    ...(params ? { params } : {}),
  };
}

export const personalSettingsAvatarCase = {
  id: "defaults.personal-settings.avatar-management",
  title: "14-个人设置头像管理校验",
  model: STATE_CASE_MODEL,
  tags: ["defaults", "personal-settings", "avatar", "profile"],
  data: {
    manageUser: {
      email: "orf-default-page-avatar-manage-e2e@orf.local",
      password: "OrfDefaultPageAvatarManageE2E!2026",
      name: "ORF 默认页头像管理用户",
      role: "member",
      status: "active",
    },
    noAvatarUser: {
      email: "orf-default-page-avatar-none-e2e@orf.local",
      password: "OrfDefaultPageAvatarNoneE2E!2026",
      name: "ORF 默认页无头像限制用户",
      role: "member",
      status: "active",
    },
    defaultLandingPath: "/bounties",
    settingsPathPattern: "/settings$",
    validAvatarFileName: "personal-settings-avatar-valid.png",
    invalidAvatarFileName: "personal-settings-avatar-invalid.txt",
    invalidAvatarMessage: "仅支持上传图片文件",
  },
  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      step("B-1", "api", "frontend.ready", "前端服务 应可用", "frontend.service", "available"),
      step("B-2", "api", "backend.ready", "后端服务 应可用", "api.health", "ok"),
      step("B-3", "api", "frontend.login_entry.accessible", "前端登录页入口 应可访问", "frontend.login_entry", "accessible"),
      step("B-4", "api", "session.endpoint.accessible", "当前会话查询能力 应可用", "auth.session", "accessible"),
      step("B-5", "prisma", "db.ready", "ORF 数据库 应可连接", "db", "ready"),
      step("B-6", "prisma", "db.schema.current", "ORF 数据库 schema 应为 当前测试版本", "db.schema", "current"),
      step("B-7", "api", "ory.admin_public.ready", "Ory/Kratos 认证服务的管理和公共访问能力 应可用", "ory.admin_public", "ready"),
      step("B-8", "api", "session.unauthenticated", "当前会话 应为 未登录", "auth.session", "unauthenticated"),
      step("B-9", "playwright", "cookie.absent", "当前浏览器 应不存在 Ory 登录会话 cookie", "browser.cookie", "absent"),
      step("B-10", "playwright", "storage.empty", "当前浏览器 应不保留本地登录态", "browser.auth_storage", "empty"),
    ],
  },
  Setup: {
    description: "准备两个无自定义头像的个人设置测试用户，并以头像管理测试用户登录个人设置页",
    steps: [
      step("Setup-1", "api", "ory.manage_identity.upsert", "准备邮箱为 `orf-default-page-avatar-manage-e2e@orf.local`、使用固定测试密码的个人设置头像管理测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.manageUser.email", passwordFrom: "data.manageUser.password", nameFrom: "data.manageUser.name", saveAs: "manageIdentity" }),
      step("Setup-2", "prisma", "db.manage_user.upsert", "准备邮箱为 `orf-default-page-avatar-manage-e2e@orf.local`、姓名为 `ORF 默认页头像管理用户`、角色为 `member`、状态为 `active` 的个人设置头像管理测试用户", "db.user", "upsert", { emailFrom: "data.manageUser.email", passwordFrom: "data.manageUser.password", nameFrom: "data.manageUser.name", roleFrom: "data.manageUser.role", statusFrom: "data.manageUser.status", identityIdFrom: "runtime.manageIdentity.id", saveAs: "manageUser" }),
      step("Setup-3", "api", "user.manage_avatar.delete", "确保个人设置头像管理测试用户未上传自定义头像", "user.avatar", "delete_by_email", { emailFrom: "data.manageUser.email" }),
      step("Setup-4", "api", "preferences.manage_default_landing.set", "设置个人设置头像管理测试用户默认进入页面为 首页（默认系统页）", "user.preferences", "set_default_landing_path_by_email", { emailFrom: "data.manageUser.email", pathFrom: "data.defaultLandingPath" }),
      step("Setup-5", "api", "ory.no_avatar_identity.upsert", "准备邮箱为 `orf-default-page-avatar-none-e2e@orf.local`、使用固定测试密码的个人设置无头像删除限制测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.noAvatarUser.email", passwordFrom: "data.noAvatarUser.password", nameFrom: "data.noAvatarUser.name", saveAs: "noAvatarIdentity" }),
      step("Setup-6", "prisma", "db.no_avatar_user.upsert", "准备邮箱为 `orf-default-page-avatar-none-e2e@orf.local`、姓名为 `ORF 默认页无头像限制用户`、角色为 `member`、状态为 `active` 的个人设置无头像删除限制测试用户", "db.user", "upsert", { emailFrom: "data.noAvatarUser.email", passwordFrom: "data.noAvatarUser.password", nameFrom: "data.noAvatarUser.name", roleFrom: "data.noAvatarUser.role", statusFrom: "data.noAvatarUser.status", identityIdFrom: "runtime.noAvatarIdentity.id", saveAs: "noAvatarUser" }),
      step("Setup-7", "api", "user.no_avatar.delete", "确保个人设置无头像删除限制测试用户未上传自定义头像", "user.avatar", "delete_by_email", { emailFrom: "data.noAvatarUser.email" }),
      step("Setup-8", "api", "preferences.no_avatar_default_landing.set", "设置个人设置无头像删除限制测试用户默认进入页面为 首页（默认系统页）", "user.preferences", "set_default_landing_path_by_email", { emailFrom: "data.noAvatarUser.email", pathFrom: "data.defaultLandingPath" }),
      step("Setup-9", "mock", "mock.valid_avatar.prepare", "准备本用例有效头像图片文件", "mock.avatar_file", "prepare_image", { fileNameFrom: "data.validAvatarFileName", saveAs: "validAvatarFile" }),
      step("Setup-10", "mock", "mock.invalid_avatar.prepare", "准备本用例无效格式头像文件", "mock.avatar_file", "prepare_invalid", { fileNameFrom: "data.invalidAvatarFileName", saveAs: "invalidAvatarFile" }),
      step("Setup-11", "api", "ory.manage_sessions.revoke", "撤销邮箱为 `orf-default-page-avatar-manage-e2e@orf.local` 的个人设置头像管理测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.manageUser.email" }),
      step("Setup-12", "api", "ory.no_avatar_sessions.revoke", "撤销邮箱为 `orf-default-page-avatar-none-e2e@orf.local` 的个人设置无头像删除限制测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.noAvatarUser.email" }),
      step("Setup-13", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Setup-14", "playwright", "page.goto.auth", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Setup-15", "playwright", "fill.manage_email", "在邮箱输入框输入 `orf-default-page-avatar-manage-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.manageUser.email" }),
      step("Setup-16", "playwright", "fill.manage_password", "在密码输入框输入个人设置头像管理测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.manageUser.password" }),
      step("Setup-17", "playwright", "click.sign_in.manage", "点击 \"Sign In\" 登录操作", "page.login_form", "submit", { saveAs: "manageLoginResponse" }),
      step("Setup-18", "api", "session.manage_authenticated", "当前会话 应为 邮箱为 `orf-default-page-avatar-manage-e2e@orf.local`、角色为 `member`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.manageUser.email", roleFrom: "data.manageUser.role", statusFrom: "data.manageUser.status" }),
      step("Setup-19", "playwright", "page.goto.settings", "打开 个人设置页面", "page", "goto", { path: "/settings" }),
    ],
  },
  S0: {
    description: "头像管理测试用户已登录个人设置页，当前没有自定义头像",
    assertions: [
      step("S0-1", "api", "session.manage_authenticated", "当前会话 应为 邮箱为 `orf-default-page-avatar-manage-e2e@orf.local`、角色为 `member`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.manageUser.email", roleFrom: "data.manageUser.role", statusFrom: "data.manageUser.status" }),
      step("S0-2", "playwright", "personal_settings.page.visible", "当前页面 应为 个人设置页面", "personal_settings.page", "visible", { patternFrom: "data.settingsPathPattern" }),
      step("S0-3", "playwright", "personal_settings.avatar.default", "个人设置页面的当前用户头像 应显示 默认头像", "personal_settings.current_user_avatar", "default_visible"),
      step("S0-4", "playwright", "personal_settings.upload_avatar.enabled", "个人设置页面的上传头像操作 应可点击", "personal_settings.upload_avatar", "enabled"),
      step("S0-5", "playwright", "personal_settings.delete_avatar.disabled", "个人设置页面的删除头像操作 应不可点击", "personal_settings.delete_avatar", "disabled"),
      step("S0-6", "prisma", "db.manage_avatar.absent", "邮箱为 `orf-default-page-avatar-manage-e2e@orf.local` 的个人设置头像管理测试用户 应不存在 自定义头像", "db.user_avatar", "absent", { emailFrom: "data.manageUser.email" }),
    ],
  },
  Action: {
    description: "执行头像上传、无效文件上传、删除头像和无头像用户切换",
    steps: [
      step("Action-1", "playwright", "personal_settings.avatar.upload_valid", "通过个人设置页面的上传头像操作选择本用例有效头像图片文件", "personal_settings.avatar_upload", "choose", { filePathFrom: "runtime.validAvatarFile.path", emailFrom: "data.manageUser.email", saveAs: "validUploadSnapshot" }),
      step("Action-2", "playwright", "personal_settings.avatar.upload_invalid", "通过个人设置页面的上传头像操作选择本用例无效格式头像文件", "personal_settings.avatar_upload", "choose_invalid", { filePathFrom: "runtime.invalidAvatarFile.path", emailFrom: "data.manageUser.email", messageFrom: "data.invalidAvatarMessage", saveAs: "invalidUploadSnapshot" }),
      step("Action-3", "playwright", "personal_settings.avatar.delete", "点击 个人设置页面的删除头像操作", "personal_settings.avatar_delete", "click", { emailFrom: "data.manageUser.email", saveAs: "deleteAvatarSnapshot" }),
      step("Action-4", "api", "auth.logout", "注销当前登录会话", "auth", "logout"),
      step("Action-5", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Action-6", "playwright", "page.goto.auth", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Action-7", "playwright", "fill.no_avatar_email", "在邮箱输入框输入 `orf-default-page-avatar-none-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.noAvatarUser.email" }),
      step("Action-8", "playwright", "fill.no_avatar_password", "在密码输入框输入个人设置无头像删除限制测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.noAvatarUser.password" }),
      step("Action-9", "playwright", "click.sign_in.no_avatar", "点击 \"Sign In\" 登录操作", "page.login_form", "submit", { saveAs: "noAvatarLoginResponse" }),
      step("Action-10", "playwright", "page.goto.settings.no_avatar", "打开 个人设置页面", "page", "goto", { path: "/settings" }),
    ],
  },
  S1: {
    description: "头像上传、无效格式拦截、删除头像和无头像删除限制均符合预期",
    assertions: [
      step("S1-1", "playwright", "snapshot.valid_upload.avatar_custom", "有效头像上传后，个人设置头像管理测试用户的当前用户头像 应显示 自定义头像", "avatar_snapshot", "custom_visible", { snapshotFrom: "runtime.validUploadSnapshot" }),
      step("S1-2", "prisma", "snapshot.valid_upload.db_avatar_exists", "有效头像上传后，邮箱为 `orf-default-page-avatar-manage-e2e@orf.local` 的个人设置头像管理测试用户 应存在 自定义头像", "avatar_snapshot", "db_avatar_exists", { snapshotFrom: "runtime.validUploadSnapshot" }),
      step("S1-3", "playwright", "snapshot.invalid_upload.toast", "无效格式头像上传后，系统 应提示 `仅支持上传图片文件`", "avatar_snapshot", "toast_visible", { snapshotFrom: "runtime.invalidUploadSnapshot", messageFrom: "data.invalidAvatarMessage" }),
      step("S1-4", "prisma", "snapshot.invalid_upload.db_avatar_unchanged", "无效格式头像上传后，邮箱为 `orf-default-page-avatar-manage-e2e@orf.local` 的个人设置头像管理测试用户的自定义头像 应仍为 有效头像图片上传后的头像", "avatar_snapshot", "db_avatar_unchanged", { beforeSnapshotFrom: "runtime.validUploadSnapshot", afterSnapshotFrom: "runtime.invalidUploadSnapshot" }),
      step("S1-5", "playwright", "snapshot.delete_avatar.default", "删除头像后，个人设置头像管理测试用户的当前用户头像 应显示 默认头像", "avatar_snapshot", "default_visible", { snapshotFrom: "runtime.deleteAvatarSnapshot" }),
      step("S1-6", "prisma", "snapshot.delete_avatar.db_absent", "删除头像后，邮箱为 `orf-default-page-avatar-manage-e2e@orf.local` 的个人设置头像管理测试用户 应不存在 自定义头像", "avatar_snapshot", "db_avatar_absent", { snapshotFrom: "runtime.deleteAvatarSnapshot" }),
      step("S1-7", "api", "session.no_avatar_authenticated", "当前会话 应为 邮箱为 `orf-default-page-avatar-none-e2e@orf.local`、角色为 `member`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.noAvatarUser.email", roleFrom: "data.noAvatarUser.role", statusFrom: "data.noAvatarUser.status" }),
      step("S1-8", "playwright", "personal_settings.no_avatar_page.visible", "无自定义头像用户的个人设置页面 应为 个人设置页面", "personal_settings.page", "visible", { patternFrom: "data.settingsPathPattern" }),
      step("S1-9", "playwright", "personal_settings.no_avatar.default", "无自定义头像用户的个人设置页面的当前用户头像 应显示 默认头像", "personal_settings.current_user_avatar", "default_visible"),
      step("S1-10", "playwright", "personal_settings.no_avatar.delete_disabled", "无自定义头像用户的个人设置页面的删除头像操作 应不可点击", "personal_settings.delete_avatar", "disabled"),
      step("S1-11", "prisma", "db.no_avatar.absent", "邮箱为 `orf-default-page-avatar-none-e2e@orf.local` 的个人设置无头像删除限制测试用户 应不存在 自定义头像", "db.user_avatar", "absent", { emailFrom: "data.noAvatarUser.email" }),
    ],
  },
  Clean: {
    description: "删除测试用户头像、账号和会话，恢复未登录基准状态",
    steps: [
      step("Clean-1", "api", "auth.logout", "注销当前登录会话", "auth", "logout"),
      step("Clean-2", "playwright", "page.runtime.stop", "离开当前 ORF 前端页面", "page.runtime", "stop"),
      step("Clean-3", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Clean-4", "api", "ory.manage_sessions.revoke", "撤销邮箱为 `orf-default-page-avatar-manage-e2e@orf.local` 的个人设置头像管理测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.manageUser.email" }),
      step("Clean-5", "api", "ory.no_avatar_sessions.revoke", "撤销邮箱为 `orf-default-page-avatar-none-e2e@orf.local` 的个人设置无头像删除限制测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.noAvatarUser.email" }),
      step("Clean-6", "api", "user.manage_avatar.delete", "删除个人设置头像管理测试用户的自定义头像文件", "user.avatar", "delete_by_email", { emailFrom: "data.manageUser.email" }),
      step("Clean-7", "api", "user.no_avatar.delete", "删除个人设置无头像删除限制测试用户的自定义头像文件", "user.avatar", "delete_by_email", { emailFrom: "data.noAvatarUser.email" }),
      step("Clean-8", "api", "ory.manage_identity.delete", "删除邮箱为 `orf-default-page-avatar-manage-e2e@orf.local` 的个人设置头像管理测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.manageUser.email" }),
      step("Clean-9", "api", "ory.no_avatar_identity.delete", "删除邮箱为 `orf-default-page-avatar-none-e2e@orf.local` 的个人设置无头像删除限制测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.noAvatarUser.email" }),
      step("Clean-10", "api", "preferences.manage_default_landing.reset", "恢复邮箱为 `orf-default-page-avatar-manage-e2e@orf.local` 的默认进入页面为 系统默认", "user.preferences", "reset_default_landing_path_by_email", { emailFrom: "data.manageUser.email" }),
      step("Clean-11", "api", "preferences.no_avatar_default_landing.reset", "恢复邮箱为 `orf-default-page-avatar-none-e2e@orf.local` 的默认进入页面为 系统默认", "user.preferences", "reset_default_landing_path_by_email", { emailFrom: "data.noAvatarUser.email" }),
      step("Clean-12", "prisma", "db.manage_user.memberships.delete", "删除邮箱为 `orf-default-page-avatar-manage-e2e@orf.local` 的个人设置头像管理测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.manageUser.email" }),
      step("Clean-13", "prisma", "db.no_avatar_user.memberships.delete", "删除邮箱为 `orf-default-page-avatar-none-e2e@orf.local` 的个人设置无头像删除限制测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.noAvatarUser.email" }),
      step("Clean-14", "prisma", "db.manage_user.delete", "删除邮箱为 `orf-default-page-avatar-manage-e2e@orf.local` 的个人设置头像管理测试用户", "db.user", "delete", { emailFrom: "data.manageUser.email" }),
      step("Clean-15", "prisma", "db.no_avatar_user.delete", "删除邮箱为 `orf-default-page-avatar-none-e2e@orf.local` 的个人设置无头像删除限制测试用户", "db.user", "delete", { emailFrom: "data.noAvatarUser.email" }),
      step("Clean-16", "api", "ory.manage_identity.absent", "邮箱为 `orf-default-page-avatar-manage-e2e@orf.local` 的个人设置头像管理测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.manageUser.email" }),
      step("Clean-17", "api", "ory.no_avatar_identity.absent", "邮箱为 `orf-default-page-avatar-none-e2e@orf.local` 的个人设置无头像删除限制测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.noAvatarUser.email" }),
      step("Clean-18", "prisma", "db.manage_user.absent", "邮箱为 `orf-default-page-avatar-manage-e2e@orf.local` 的个人设置头像管理测试用户 应不存在", "db.user", "absent", { emailFrom: "data.manageUser.email" }),
      step("Clean-19", "prisma", "db.no_avatar_user.absent", "邮箱为 `orf-default-page-avatar-none-e2e@orf.local` 的个人设置无头像删除限制测试用户 应不存在", "db.user", "absent", { emailFrom: "data.noAvatarUser.email" }),
    ],
  },
} satisfies StateCaseSpec<PersonalSettingsAvatarCaseData>;
