import { STATE_CASE_MODEL, type StateCaseSpec } from "../../../../_framework/types";
import type { AdminApproveFrozenReestimateReopenCaseData } from "./_support/admin-approve-frozen-reestimate-reopen.context";

export const adminApproveFrozenReestimateReopenCase = {
  id: "target.admin-approve-frozen-reestimate-reopen",
  title: "管理员批准重新重估后目标回到重估中且参与成员可再次申请完成重估",
  model: STATE_CASE_MODEL,
  tags: ["target", "reestimate", "frozen", "admin", "member", "alignment-request", "metric"],

  data: {
    adminEmail: "orf-admin-approve-frozen-reestimate-e2e@orf.local",
    adminPassword: "OrfAdminApproveFrozenReestimateE2E!2026",
    adminName: "ORF Admin Approve Frozen Reestimate E2E",
    adminRole: "admin",
    adminStatus: "active",
    memberEmail: "orf-member-approve-frozen-reestimate-e2e@orf.local",
    memberPassword: "OrfMemberApproveFrozenReestimateE2E!2026",
    memberName: "ORF Member Approve Frozen Reestimate E2E",
    memberRole: "member",
    memberStatus: "active",
    targetPrefix: "E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE",
    frozenTarget: {
      title: "E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE",
      stage: "goalFrozen",
      flowStatus: "frozen",
      finalDueOffsetDays: 8,
    },
    reestimateTarget: {
      title: "E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE",
      stage: "orfReestimate",
      flowStatus: "reestimating",
    },
    metric: {
      title: "E2E-METRIC-ADMIN-APPROVE-FROZEN-REESTIMATE",
      difficulty: "进阶",
      score: 30,
    },
    frozenReestimateKind: "frozenReestimate",
    reestimateCompletionKind: "reestimateCompletion",
    requestedStatus: "requested",
    completedStatus: "completed",
    reason: "E2E-REASON-ADMIN-APPROVE-FROZEN-REESTIMATE",
    reopenDueOffsetHours: 1,
  },

  B: {
    description: "基准状态",
    assertions: [
      { source: { caseStepId: "B-1", method: "api" }, id: "frontend.ready", title: "前端服务 应可用", object: "frontend.service", operator: "available" },
      { source: { caseStepId: "B-2", method: "api" }, id: "backend.ready", title: "后端服务 应可用", object: "api.health", operator: "ok" },
      { source: { caseStepId: "B-3", method: "prisma" }, id: "db.ready", title: "ORF 数据库 应可连接", object: "db", operator: "ready" },
      { source: { caseStepId: "B-4", method: "api" }, id: "session.unauthenticated", title: "当前会话 应为 未登录", object: "auth.session", operator: "unauthenticated" },
      { source: { caseStepId: "B-5", method: "playwright" }, id: "storage.empty", title: "当前浏览器 应不保留本地登录态", object: "browser.auth_storage", operator: "empty" },
    ],
  },

  Setup: {
    description: "构造 S0",
    steps: [
      { source: { caseStepId: "Setup-1", method: "prisma" }, id: "db.objectives.delete_residue", title: "删除 本用例残留的目标标题前缀 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE` 对应的目标及其派生数据", object: "db.objectives_by_prefix", operator: "delete", params: { prefixFrom: "data.targetPrefix" } },
      { source: { caseStepId: "Setup-2", method: "api" }, id: "ory.admin_identity.upsert", title: "准备邮箱为 `orf-admin-approve-frozen-reestimate-e2e@orf.local`、使用固定测试密码的管理员登录身份", object: "ory.identity", operator: "upsert_password", params: { emailFrom: "data.adminEmail", nameFrom: "data.adminName", passwordFrom: "data.adminPassword", saveAs: "adminIdentity" } },
      { source: { caseStepId: "Setup-3", method: "api" }, id: "ory.member_identity.upsert", title: "准备邮箱为 `orf-member-approve-frozen-reestimate-e2e@orf.local`、使用固定测试密码的普通成员登录身份", object: "ory.identity", operator: "upsert_password", params: { emailFrom: "data.memberEmail", nameFrom: "data.memberName", passwordFrom: "data.memberPassword", saveAs: "memberIdentity" } },
      { source: { caseStepId: "Setup-4", method: "prisma" }, id: "db.admin_user.upsert", title: "准备 角色为 `admin`、状态为 `active`、名称为 `ORF Admin Approve Frozen Reestimate E2E` 的本用例管理员用户", object: "db.user", operator: "upsert", params: { emailFrom: "data.adminEmail", nameFrom: "data.adminName", roleFrom: "data.adminRole", statusFrom: "data.adminStatus", identityIdFrom: "runtime.adminIdentity.id", saveAs: "adminUser" } },
      { source: { caseStepId: "Setup-5", method: "prisma" }, id: "db.member_user.upsert", title: "准备 角色为 `member`、状态为 `active`、名称为 `ORF Member Approve Frozen Reestimate E2E` 的本用例普通成员用户", object: "db.user", operator: "upsert", params: { emailFrom: "data.memberEmail", nameFrom: "data.memberName", roleFrom: "data.memberRole", statusFrom: "data.memberStatus", identityIdFrom: "runtime.memberIdentity.id", saveAs: "memberUser" } },
      { source: { caseStepId: "Setup-6", method: "prisma" }, id: "db.frozen_objective.prepare", title: "准备 标题为 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE`、阶段为 `goalFrozen`、流转状态为 `frozen`、最终验收截止日为运行时当前日期后 `8` 天、冻结时间存在、当前挑战者包含本用例普通成员的目标", object: "db.frozen_objective_fixture", operator: "prepare", params: { adminUserFrom: "runtime.adminUser", memberUserFrom: "runtime.memberUser", targetFrom: "data.frozenTarget", saveAs: "objective" } },
      { source: { caseStepId: "Setup-7", method: "prisma" }, id: "db.metric.prepare_calibrated", title: "准备 归属于目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE`、口径为 `E2E-METRIC-ADMIN-APPROVE-FROZEN-REESTIMATE`、等级积分等级为 `进阶`、等级积分为 `30` 的指标", object: "db.metric", operator: "prepare_calibrated", params: { targetFrom: "data.frozenTarget", metricFrom: "data.metric", memberUserFrom: "runtime.memberUser", saveAs: "metric" } },
      { source: { caseStepId: "Setup-8", method: "prisma" }, id: "db.frozen_reestimate_request.prepare", title: "准备 归属于目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE`、类型为 `frozenReestimate`、状态为 `requested`、申请人为本用例普通成员、申请理由为 `E2E-REASON-ADMIN-APPROVE-FROZEN-REESTIMATE` 的阶段对齐申请", object: "db.objective_alignment_request", operator: "prepare", params: { targetFrom: "data.frozenTarget", kindFrom: "data.frozenReestimateKind", statusFrom: "data.requestedStatus", memberUserFrom: "runtime.memberUser", reasonFrom: "data.reason", saveAs: "frozenReestimateRequest" } },
      { source: { caseStepId: "Setup-9", method: "prisma" }, id: "db.reestimate_completion_request.ensure_open_absent", title: "确保 归属于目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE`、类型为 `reestimateCompletion`、状态为 `requested` 或 `scheduled` 的阶段对齐申请不存在", object: "db.objective_alignment_request", operator: "delete_open", params: { targetFrom: "data.frozenTarget", kindFrom: "data.reestimateCompletionKind" } },
      { source: { caseStepId: "Setup-10", method: "playwright" }, id: "auth.login.admin", title: "使用 本用例管理员账号 登录 ORF", object: "page.auth", operator: "login", params: { emailFrom: "data.adminEmail", passwordFrom: "data.adminPassword" } },
    ],
  },

  S0: {
    description: "Action 前状态",
    assertions: [
      { source: { caseStepId: "S0-1", method: "api" }, id: "session.authenticated", title: "当前会话 应为 已登录", object: "auth.session", operator: "authenticated" },
      { source: { caseStepId: "S0-2", method: "api" }, id: "session.email", title: "当前会话用户邮箱 应为 `orf-admin-approve-frozen-reestimate-e2e@orf.local`", object: "auth.session.user_email", operator: "equals", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "S0-3", method: "api" }, id: "session.role", title: "当前会话用户角色 应为 `admin`", object: "auth.session.user_role", operator: "equals", params: { roleFrom: "data.adminRole" } },
      { source: { caseStepId: "S0-4", method: "api" }, id: "session.name", title: "当前会话用户名称 应为 `ORF Admin Approve Frozen Reestimate E2E`", object: "auth.session.user_name", operator: "equals", params: { nameFrom: "data.adminName" } },
      { source: { caseStepId: "S0-5", method: "prisma" }, id: "db.frozen_objective.exists", title: "应存在 标题为 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE`、阶段为 `goalFrozen`、流转状态为 `frozen` 的目标", object: "db.frozen_objective_fixture", operator: "exists", params: { targetFrom: "data.frozenTarget" } },
      { source: { caseStepId: "S0-6", method: "prisma" }, id: "db.frozen_objective.challenger_contains", title: "目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE` 的当前挑战者 应包含本用例普通成员", object: "db.frozen_objective_fixture", operator: "challenger_contains", params: { targetFrom: "data.frozenTarget", memberUserFrom: "runtime.memberUser" } },
      { source: { caseStepId: "S0-7", method: "prisma" }, id: "db.frozen_objective.confirmed_at", title: "目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE` 的冻结时间 应存在", object: "db.frozen_objective_fixture", operator: "confirmed_at_exists", params: { targetFrom: "data.frozenTarget" } },
      { source: { caseStepId: "S0-8", method: "prisma" }, id: "db.metric.exists", title: "应存在 归属于目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE`、口径为 `E2E-METRIC-ADMIN-APPROVE-FROZEN-REESTIMATE`、等级积分等级为 `进阶`、等级积分为 `30` 的指标", object: "db.metric", operator: "exists_with_score", params: { targetFrom: "data.frozenTarget", titleFrom: "data.metric.title", difficultyFrom: "data.metric.difficulty", scoreFrom: "data.metric.score" } },
      { source: { caseStepId: "S0-9", method: "prisma" }, id: "db.frozen_reestimate_request.exists", title: "应存在 归属于目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE`、类型为 `frozenReestimate`、状态为 `requested`、申请人为本用例普通成员、申请理由为 `E2E-REASON-ADMIN-APPROVE-FROZEN-REESTIMATE` 的阶段对齐申请", object: "db.objective_alignment_request", operator: "exists", params: { targetFrom: "data.frozenTarget", kindFrom: "data.frozenReestimateKind", statusFrom: "data.requestedStatus", memberUserFrom: "runtime.memberUser", reasonFrom: "data.reason" } },
      { source: { caseStepId: "S0-10", method: "prisma" }, id: "db.frozen_reestimate_request.open_count_one", title: "目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE` 的 `frozenReestimate` 类型待处理阶段对齐申请数量 应为 `1`", object: "db.objective_alignment_request", operator: "open_count", params: { targetFrom: "data.frozenTarget", kindFrom: "data.frozenReestimateKind", count: 1 } },
      { source: { caseStepId: "S0-11", method: "prisma" }, id: "db.reestimate_completion_request.open_count_zero", title: "目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE` 的 `reestimateCompletion` 类型待处理阶段对齐申请数量 应为 `0`", object: "db.objective_alignment_request", operator: "open_count", params: { targetFrom: "data.frozenTarget", kindFrom: "data.reestimateCompletionKind", count: 0 } },
    ],
  },

  Action: {
    description: "被测业务动作",
    steps: [
      { source: { caseStepId: "Action-1", method: "playwright" }, id: "admin.open_my_challenges", title: "管理员打开 我的挑战", object: "page.challenge", operator: "open_my_challenges" },
      { source: { caseStepId: "Action-2", method: "playwright" }, id: "scope.select_all", title: "管理员切换到 \"所有挑战\" 视图", object: "page.challenge_scope", operator: "select", params: { label: "所有挑战" } },
      { source: { caseStepId: "Action-3", method: "playwright" }, id: "frozen_reestimate.due.fill", title: "在目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE` 的 \"新的重估截止时间\" 输入框填写运行时当前时间后 `1` 小时", object: "page.frozen_reestimate_approval", operator: "fill_due", params: { targetTitleFrom: "data.frozenTarget.title", offsetHoursFrom: "data.reopenDueOffsetHours" } },
      { source: { caseStepId: "Action-4", method: "playwright" }, id: "frozen_reestimate.approve", title: "点击目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE` 的 \"批准重开\" 操作", object: "page.frozen_reestimate_approval", operator: "approve", params: { targetTitleFrom: "data.frozenTarget.title" } },
      { source: { caseStepId: "Action-5", method: "api" }, id: "auth.logout.admin", title: "注销当前管理员登录会话", object: "auth", operator: "logout" },
      { source: { caseStepId: "Action-6", method: "playwright" }, id: "browser.clear_admin_state", title: "移除当前浏览器中的管理员登录态", object: "browser", operator: "clear_state" },
      { source: { caseStepId: "Action-7", method: "playwright" }, id: "auth.login.member", title: "使用 本用例普通成员账号 登录 ORF", object: "page.auth", operator: "login", params: { emailFrom: "data.memberEmail", passwordFrom: "data.memberPassword" } },
      { source: { caseStepId: "Action-8", method: "playwright" }, id: "member.open_my_challenges", title: "普通成员打开 我的挑战", object: "page.challenge", operator: "open_my_challenges" },
      { source: { caseStepId: "Action-9", method: "playwright" }, id: "reestimate_completion.request", title: "点击目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE` 的 \"申请完成重估\" 操作", object: "page.objective_alignment", operator: "request_reestimate_completion", params: { targetTitleFrom: "data.reestimateTarget.title" } },
    ],
  },

  S1: {
    description: "Action 后状态",
    assertions: [
      { source: { caseStepId: "S1-1", method: "playwright" }, id: "challenge.page.url", title: "页面 应进入 我的挑战", object: "page.challenge", operator: "url" },
      { source: { caseStepId: "S1-2", method: "playwright" }, id: "scope.mine.selected", title: "\"我的挑战\" 视图 应处于选中状态", object: "page.challenge_scope", operator: "selected", params: { label: "我的挑战" } },
      { source: { caseStepId: "S1-3", method: "playwright" }, id: "reestimate_completion.toast.requested", title: "页面 应提示 已申请重估对齐，请约时间并定好会议室", object: "page.challenge_toast", operator: "reestimate_alignment_requested" },
      { source: { caseStepId: "S1-4", method: "playwright" }, id: "objective.visible", title: "我的挑战列表 应显示目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE`", object: "page.challenge_objectives", operator: "visible_title", params: { titleFrom: "data.reestimateTarget.title" } },
      { source: { caseStepId: "S1-5", method: "playwright" }, id: "objective.status.reestimating", title: "目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE` 的状态 应显示为 重估中", object: "page.challenge_objective", operator: "status_visible", params: { titleFrom: "data.reestimateTarget.title", statusLabel: "重估中" } },
      { source: { caseStepId: "S1-6", method: "playwright" }, id: "reestimate_completion.action.hidden", title: "目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE` 的 \"申请完成重估\" 操作 应不可见", object: "page.objective_alignment", operator: "request_reestimate_completion_hidden", params: { targetTitleFrom: "data.reestimateTarget.title" } },
      { source: { caseStepId: "S1-7", method: "playwright" }, id: "metric.visible", title: "目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE` 下 应显示指标口径 `E2E-METRIC-ADMIN-APPROVE-FROZEN-REESTIMATE`", object: "page.challenge_metric", operator: "visible_under_objective", params: { targetTitleFrom: "data.reestimateTarget.title", metricTitleFrom: "data.metric.title" } },
      { source: { caseStepId: "S1-8", method: "playwright" }, id: "metric.difficulty.visible", title: "指标 `E2E-METRIC-ADMIN-APPROVE-FROZEN-REESTIMATE` 的等级积分等级 应显示为 `进阶`", object: "page.metric_difficulty", operator: "visible", params: { metricTitleFrom: "data.metric.title", difficultyFrom: "data.metric.difficulty" } },
      { source: { caseStepId: "S1-9", method: "api" }, id: "api.my_challenges.contains_objective", title: "我的挑战数据 应包含目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE`", object: "api.my_challenges", operator: "contains_objective", params: { titleFrom: "data.reestimateTarget.title" } },
      { source: { caseStepId: "S1-10", method: "api" }, id: "api.my_challenges.objective_stage_flow", title: "我的挑战数据中目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE` 的阶段 应为 `orfReestimate`，流转状态 应为 `reestimating`", object: "api.my_challenges", operator: "objective_stage_flow", params: { targetFrom: "data.reestimateTarget" } },
      { source: { caseStepId: "S1-11", method: "api" }, id: "api.my_challenges.contains_metric", title: "我的挑战数据中目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE` 应包含口径为 `E2E-METRIC-ADMIN-APPROVE-FROZEN-REESTIMATE`、等级积分等级为 `进阶`、等级积分为 `30` 的指标", object: "api.my_challenges", operator: "contains_metric_with_score", params: { targetTitleFrom: "data.reestimateTarget.title", metricTitleFrom: "data.metric.title", difficultyFrom: "data.metric.difficulty", scoreFrom: "data.metric.score" } },
      { source: { caseStepId: "S1-12", method: "api" }, id: "api.all_challenges.contains_completed_frozen_reestimate", title: "我的挑战数据中目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE` 应包含 `frozenReestimate` 类型的已完成阶段对齐申请", object: "api.my_challenges", operator: "contains_alignment_request_status", params: { targetTitleFrom: "data.reestimateTarget.title", kindFrom: "data.frozenReestimateKind", statusFrom: "data.completedStatus" } },
      { source: { caseStepId: "S1-13", method: "api" }, id: "api.my_challenges.contains_requested_reestimate_completion", title: "我的挑战数据中目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE` 应包含 `reestimateCompletion` 类型的待处理阶段对齐申请", object: "api.my_challenges", operator: "contains_alignment_request_status", params: { targetTitleFrom: "data.reestimateTarget.title", kindFrom: "data.reestimateCompletionKind", statusFrom: "data.requestedStatus" } },
      { source: { caseStepId: "S1-14", method: "prisma" }, id: "db.reestimate_objective.exists", title: "标题为 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE` 的目标阶段 应为 `orfReestimate`，流转状态 应为 `reestimating`", object: "db.reestimate_objective", operator: "exists", params: { targetFrom: "data.reestimateTarget" } },
      { source: { caseStepId: "S1-15", method: "prisma" }, id: "db.reestimate_objective.confirmed_at_null", title: "目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE` 的冻结时间 应为空", object: "db.reestimate_objective", operator: "confirmed_at_null", params: { targetFrom: "data.reestimateTarget" } },
      { source: { caseStepId: "S1-16", method: "prisma" }, id: "db.reestimate_objective.due_future", title: "目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE` 的重估截止时间 应晚于当前时间", object: "db.reestimate_objective", operator: "reestimate_due_future", params: { targetFrom: "data.reestimateTarget" } },
      { source: { caseStepId: "S1-17", method: "prisma" }, id: "db.frozen_reestimate_request.completed", title: "应存在 归属于目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE`、类型为 `frozenReestimate`、状态为 `completed`、申请人为本用例普通成员、审核人为本用例管理员的阶段对齐申请", object: "db.objective_alignment_request", operator: "exists", params: { targetFrom: "data.reestimateTarget", kindFrom: "data.frozenReestimateKind", statusFrom: "data.completedStatus", memberUserFrom: "runtime.memberUser", adminUserFrom: "runtime.adminUser" } },
      { source: { caseStepId: "S1-18", method: "prisma" }, id: "db.reestimate_completion_request.requested", title: "应存在 归属于目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE`、类型为 `reestimateCompletion`、状态为 `requested`、申请人为本用例普通成员的阶段对齐申请", object: "db.objective_alignment_request", operator: "exists", params: { targetFrom: "data.reestimateTarget", kindFrom: "data.reestimateCompletionKind", statusFrom: "data.requestedStatus", memberUserFrom: "runtime.memberUser" } },
      { source: { caseStepId: "S1-19", method: "prisma" }, id: "db.frozen_reestimate_request.open_count_zero", title: "目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE` 的 `frozenReestimate` 类型待处理阶段对齐申请数量 应为 `0`", object: "db.objective_alignment_request", operator: "open_count", params: { targetFrom: "data.reestimateTarget", kindFrom: "data.frozenReestimateKind", count: 0 } },
      { source: { caseStepId: "S1-20", method: "prisma" }, id: "db.reestimate_completion_request.open_count_one", title: "目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE` 的 `reestimateCompletion` 类型待处理阶段对齐申请数量 应为 `1`", object: "db.objective_alignment_request", operator: "open_count", params: { targetFrom: "data.reestimateTarget", kindFrom: "data.reestimateCompletionKind", count: 1 } },
      { source: { caseStepId: "S1-21", method: "prisma" }, id: "db.reestimate_objective.challenger_contains", title: "目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE` 的当前挑战者 应仍包含本用例普通成员", object: "db.reestimate_objective", operator: "challenger_contains", params: { targetFrom: "data.reestimateTarget", memberUserFrom: "runtime.memberUser" } },
      { source: { caseStepId: "S1-22", method: "prisma" }, id: "db.metric.still_exists", title: "应存在 归属于目标 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE`、口径为 `E2E-METRIC-ADMIN-APPROVE-FROZEN-REESTIMATE`、等级积分等级为 `进阶`、等级积分为 `30` 的指标", object: "db.metric", operator: "exists_with_score", params: { targetFrom: "data.reestimateTarget", titleFrom: "data.metric.title", difficultyFrom: "data.metric.difficulty", scoreFrom: "data.metric.score" } },
    ],
  },

  Clean: {
    description: "恢复 B",
    steps: [
      { source: { caseStepId: "Clean-1", method: "prisma" }, id: "db.objectives.delete_created", title: "删除 本用例创建的目标标题前缀 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE` 对应的目标及其派生数据", object: "db.objectives_by_prefix", operator: "delete", params: { prefixFrom: "data.targetPrefix" } },
      { source: { caseStepId: "Clean-2", method: "api" }, id: "auth.logout.member", title: "注销当前普通成员登录会话", object: "auth", operator: "logout" },
      { source: { caseStepId: "Clean-3", method: "playwright" }, id: "browser.clear", title: "移除当前浏览器中的残留登录态", object: "browser", operator: "clear_state" },
      { source: { caseStepId: "Clean-4", method: "api" }, id: "ory.admin_identity.delete", title: "删除 本用例管理员登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-5", method: "api" }, id: "ory.member_identity.delete", title: "删除 本用例普通成员登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-6", method: "prisma" }, id: "db.admin_user.delete", title: "删除 本用例管理员用户", object: "db.user", operator: "delete", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-7", method: "prisma" }, id: "db.member_user.delete", title: "删除 本用例普通成员用户", object: "db.user", operator: "delete", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-8", method: "prisma" }, id: "db.objectives.absent", title: "应不存在 标题前缀为 `E2E-TARGET-ADMIN-APPROVE-FROZEN-REESTIMATE` 的目标", object: "db.objectives_by_prefix", operator: "absent", params: { prefixFrom: "data.targetPrefix" } },
      { source: { caseStepId: "Clean-9", method: "prisma" }, id: "db.metric.absent", title: "应不存在 标题为 `E2E-METRIC-ADMIN-APPROVE-FROZEN-REESTIMATE` 的指标", object: "db.metric", operator: "absent", params: { titleFrom: "data.metric.title" } },
      { source: { caseStepId: "Clean-10", method: "api" }, id: "ory.admin_identity.absent", title: "邮箱为 `orf-admin-approve-frozen-reestimate-e2e@orf.local` 的管理员登录身份 应不存在", object: "ory.identity", operator: "absent", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-11", method: "api" }, id: "ory.member_identity.absent", title: "邮箱为 `orf-member-approve-frozen-reestimate-e2e@orf.local` 的普通成员登录身份 应不存在", object: "ory.identity", operator: "absent", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-12", method: "prisma" }, id: "db.admin_user.absent", title: "邮箱为 `orf-admin-approve-frozen-reestimate-e2e@orf.local` 的管理员用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-13", method: "prisma" }, id: "db.member_user.absent", title: "邮箱为 `orf-member-approve-frozen-reestimate-e2e@orf.local` 的普通成员用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-14", method: "api" }, id: "session.unauthenticated", title: "当前会话 应为 未登录", object: "auth.session", operator: "unauthenticated" },
    ],
  },
} satisfies StateCaseSpec<AdminApproveFrozenReestimateReopenCaseData>;
