import { STATE_CASE_MODEL, type StateCaseSpec, type StepExecutionMethod, type StepSpec } from "../../../../_framework/types";
import type { MemberReestimateMetricActionPermissionsCaseData } from "./_support/member-reestimate-metric-action-permissions.context";

const s = (
  caseStepId: string,
  method: StepExecutionMethod,
  id: string,
  title: string,
  object: string,
  operator: string,
  params?: Record<string, unknown>,
): StepSpec => ({
  source: { caseStepId, method },
  id,
  title,
  object,
  operator,
  ...(params ? { params } : {}),
});

export const memberReestimateMetricActionPermissionsCase = {
  id: "target.member-reestimate-metric-action-permissions",
  title: "参与的普通成员在重估中阶段可新增修改指标可新增修改删除行动项但不可删除指标",
  model: STATE_CASE_MODEL,
  tags: ["target", "metric", "action", "member", "permission", "reestimate"],

  data: {
    memberEmail: "orf-member-reestimate-metric-action-e2e@orf.local",
    memberPassword: "OrfMemberReestimateMetricActionE2E!2026",
    memberName: "ORF Member Reestimate Metric Action E2E",
    memberRole: "member",
    memberStatus: "active",
    targetPrefix: "E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION",
    metricPrefix: "E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION",
    createdMetricPrefix: "E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-CREATED",
    actionPrefix: "E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION",
    createdActionPrefix: "E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION-CREATED",
    objective: {
      key: "reestimate",
      title: "E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION",
      stage: "orfReestimate",
      flowStatus: "reestimating",
    },
    metrics: [
      { key: "edit", objectiveKey: "reestimate", title: "E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-EDIT", modifiedTitle: "E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-MODIFIED", uncertaintyLevel: "进阶", uncertaintyScore: 30, acceptedResult: "unreviewed" },
      { key: "deleteForbidden", objectiveKey: "reestimate", title: "E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-DELETE-FORBIDDEN", uncertaintyLevel: "入门", uncertaintyScore: 20, acceptedResult: "unreviewed" },
      { key: "created", objectiveKey: "reestimate", title: "E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-CREATED", uncertaintyLevel: "简易", uncertaintyScore: 10, acceptedResult: "unreviewed" },
    ],
    actions: [
      { key: "edit", objectiveKey: "reestimate", title: "E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION-EDIT", modifiedTitle: "E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION-MODIFIED", status: "Todo", priority: "High" },
      { key: "delete", objectiveKey: "reestimate", title: "E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION-DELETE", status: "Todo", priority: "Medium" },
      { key: "created", objectiveKey: "reestimate", title: "E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION-CREATED", status: "Todo", priority: "High" },
    ],
  },

  B: {
    description: "基准状态",
    assertions: [
      s("B-1", "api", "frontend.ready", "前端服务 应可用", "frontend.service", "available"),
      s("B-2", "api", "backend.ready", "后端服务 应可用", "api.health", "ok"),
      s("B-3", "prisma", "db.ready", "ORF 数据库 应可连接", "db", "ready"),
      s("B-4", "api", "session.unauthenticated", "当前会话 应为 未登录", "auth.session", "unauthenticated"),
      s("B-5", "playwright", "storage.empty", "当前浏览器 应不保留本地登录态", "browser.auth_storage", "empty"),
    ],
  },

  Setup: {
    description: "构造 S0",
    steps: [
      s("Setup-1", "prisma", "db.objectives.delete_residue", "删除 本用例残留的目标标题前缀 `E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION` 对应的目标及其派生数据", "db.objectives_by_prefix", "delete", { prefixFrom: "data.targetPrefix" }),
      s("Setup-2", "api", "ory.member_identity.upsert", "准备邮箱为 `orf-member-reestimate-metric-action-e2e@orf.local`、使用固定测试密码的普通成员登录身份", "ory.identity", "upsert_password", { emailFrom: "data.memberEmail", nameFrom: "data.memberName", passwordFrom: "data.memberPassword", saveAs: "memberIdentity" }),
      s("Setup-3", "prisma", "db.member_user.upsert", "准备 角色为 `member`、状态为 `active`、名称为 `ORF Member Reestimate Metric Action E2E` 的本用例普通成员用户", "db.user", "upsert", { emailFrom: "data.memberEmail", nameFrom: "data.memberName", roleFrom: "data.memberRole", statusFrom: "data.memberStatus", identityIdFrom: "runtime.memberIdentity.id", saveAs: "memberUser" }),
      s("Setup-4", "prisma", "db.reestimate_objective.prepare", "准备 标题为 `E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION`、阶段为 `orfReestimate`、流转状态为 `reestimating`、当前挑战者为本用例普通成员的重估中目标", "db.member_reestimate_objective", "prepare", { memberUserFrom: "runtime.memberUser", targetFrom: "data.objective" }),
      s("Setup-5", "prisma", "db.edit_metric.prepare", "准备 归属于目标 `E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION`、标题为 `E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-EDIT` 的待修改指标", "db.metric", "prepare", { memberUserFrom: "runtime.memberUser", objectiveFrom: "data.objective", metricFrom: "data.metrics.0" }),
      s("Setup-6", "prisma", "db.delete_forbidden_metric.prepare", "准备 归属于目标 `E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION`、标题为 `E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-DELETE-FORBIDDEN` 的不可删除指标", "db.metric", "prepare", { memberUserFrom: "runtime.memberUser", objectiveFrom: "data.objective", metricFrom: "data.metrics.1" }),
      s("Setup-7", "prisma", "db.edit_action.prepare", "准备 归属于目标 `E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION`、标题为 `E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION-EDIT` 的待修改行动项", "db.action", "prepare", { memberUserFrom: "runtime.memberUser", objectiveFrom: "data.objective", actionFrom: "data.actions.0" }),
      s("Setup-8", "prisma", "db.delete_action.prepare", "准备 归属于目标 `E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION`、标题为 `E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION-DELETE` 的待删除行动项", "db.action", "prepare", { memberUserFrom: "runtime.memberUser", objectiveFrom: "data.objective", actionFrom: "data.actions.1" }),
      s("Setup-9", "playwright", "auth.login.member", "使用 本用例普通成员账号 登录 ORF", "page.auth", "login", { emailFrom: "data.memberEmail", passwordFrom: "data.memberPassword" }),
    ],
  },

  S0: {
    description: "Action 前状态",
    assertions: [
      s("S0-1", "api", "session.authenticated", "当前会话 应为 已登录", "auth.session", "authenticated"),
      s("S0-2", "api", "session.email", "当前会话用户邮箱 应为 `orf-member-reestimate-metric-action-e2e@orf.local`", "auth.session.user_email", "equals", { emailFrom: "data.memberEmail" }),
      s("S0-3", "api", "session.role", "当前会话用户角色 应为 `member`", "auth.session.user_role", "equals", { roleFrom: "data.memberRole" }),
      s("S0-4", "api", "session.name", "当前会话用户名称 应为 `ORF Member Reestimate Metric Action E2E`", "auth.session.user_name", "equals", { nameFrom: "data.memberName" }),
      s("S0-5", "api", "permission.metric_mutation.allowed", "当前普通成员对目标 `E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION` 的重估中指标新增、修改权限 应为 已授权", "api.member_metric_mutation_permission", "allowed", { objectiveTitleFrom: "data.objective.title", memberUserFrom: "runtime.memberUser" }),
      s("S0-6", "api", "permission.metric_delete.forbidden", "当前普通成员的指标删除权限 应为 未授权", "api.member_metric_delete_permission", "forbidden"),
      s("S0-7", "api", "permission.action_mutation.allowed", "当前普通成员对目标 `E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION` 的行动项新增、修改、删除权限 应为 已授权", "api.member_work_item_mutation_permission", "allowed", { objectiveTitleFrom: "data.objective.title", memberUserFrom: "runtime.memberUser" }),
      s("S0-8", "prisma", "db.reestimate_objective.exists", "应存在 标题为 `E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION`、阶段为 `orfReestimate`、流转状态为 `reestimating`、当前挑战者为本用例普通成员的目标", "db.member_reestimate_objective", "exists", { targetFrom: "data.objective", memberUserFrom: "runtime.memberUser" }),
      s("S0-9", "prisma", "db.edit_metric.exists", "应存在 归属于目标 `E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION`、标题为 `E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-EDIT` 的指标", "db.metric", "exists", { objectiveTitleFrom: "data.objective.title", titleFrom: "data.metrics.0.title" }),
      s("S0-10", "prisma", "db.delete_forbidden_metric.exists", "应存在 归属于目标 `E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION`、标题为 `E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-DELETE-FORBIDDEN` 的指标", "db.metric", "exists", { objectiveTitleFrom: "data.objective.title", titleFrom: "data.metrics.1.title" }),
      s("S0-11", "prisma", "db.edit_action.exists", "应存在 归属于目标 `E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION`、标题为 `E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION-EDIT` 的行动项", "db.action", "exists", { objectiveTitleFrom: "data.objective.title", titleFrom: "data.actions.0.title" }),
      s("S0-12", "prisma", "db.delete_action.exists", "应存在 归属于目标 `E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION`、标题为 `E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION-DELETE` 的行动项", "db.action", "exists", { objectiveTitleFrom: "data.objective.title", titleFrom: "data.actions.1.title" }),
      s("S0-13", "prisma", "db.created_metrics.absent", "应不存在 标题前缀为 `E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-CREATED` 的指标", "db.metrics_by_prefix", "absent", { prefixFrom: "data.createdMetricPrefix" }),
      s("S0-14", "prisma", "db.created_actions.absent", "应不存在 标题前缀为 `E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION-CREATED` 的行动项", "db.actions_by_prefix", "absent", { prefixFrom: "data.createdActionPrefix" }),
    ],
  },

  Action: {
    description: "被测业务动作",
    steps: [
      s("Action-1", "playwright", "member.open_my_challenges", "普通成员打开 我的挑战", "page.challenge", "open_my_challenges"),
      s("Action-2", "playwright", "objective.visible", "我的挑战列表 应显示目标 `E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION`", "page.challenge_objectives", "visible_title", { titleFrom: "data.objective.title" }),
      s("Action-3", "playwright", "metric.add.click", "点击目标 `E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION` 的 \"提出指标\" 操作", "page.challenge_objective_add", "click_member_metric", { objectiveTitleFrom: "data.objective.title" }),
      s("Action-4", "playwright", "metric.add.submit", "填写新增指标标题为 `E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-CREATED` 并提交", "page.metric_draft", "submit_title", { titleFrom: "data.metrics.2.title", saveAs: "createdMetric" }),
      s("Action-5", "playwright", "metric.edit.click", "点击指标 `E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-EDIT` 的 \"编辑\" 操作", "page.metric_menu", "click_edit", { titleFrom: "data.metrics.0.title" }),
      s("Action-6", "playwright", "metric.edit.submit", "将指标 `E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-EDIT` 的标题修改为 `E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-MODIFIED`", "page.metric_title_editor", "submit_title", { oldTitleFrom: "data.metrics.0.title", newTitleFrom: "data.metrics.0.modifiedTitle" }),
      s("Action-7", "playwright", "metric.delete.click_forbidden", "点击指标 `E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-DELETE-FORBIDDEN` 的 \"删除\" 操作", "page.metric_menu", "click_delete_forbidden", { titleFrom: "data.metrics.1.title" }),
      s("Action-8", "api", "metric.delete.request_forbidden", "删除指标 `E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-DELETE-FORBIDDEN` 的请求结果 应为 权限不足", "api.metric_delete_request", "forbidden", { titleFrom: "data.metrics.1.title" }),
      s("Action-9", "playwright", "action.add.click", "点击目标 `E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION` 的 \"新增行动项\" 操作", "page.challenge_objective_add", "click_action", { objectiveTitleFrom: "data.objective.title" }),
      s("Action-10", "playwright", "action.add.submit", "填写新增行动项标题为 `E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION-CREATED` 并提交", "page.action_draft", "submit_title", { titleFrom: "data.actions.2.title", saveAs: "createdAction" }),
      s("Action-11", "playwright", "action.edit.click", "点击行动项 `E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION-EDIT` 的 \"编辑\" 操作", "page.action_menu", "click_edit", { titleFrom: "data.actions.0.title" }),
      s("Action-12", "playwright", "action.edit.submit", "将行动项 `E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION-EDIT` 的标题修改为 `E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION-MODIFIED`", "page.action_title_editor", "submit_title", { oldTitleFrom: "data.actions.0.title", newTitleFrom: "data.actions.0.modifiedTitle" }),
      s("Action-13", "playwright", "action.delete.click", "点击行动项 `E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION-DELETE` 的 \"删除\" 操作", "page.action_menu", "click_delete", { titleFrom: "data.actions.1.title" }),
      s("Action-14", "playwright", "action.delete.confirm", "在删除行动项确认弹窗中点击 \"确定\" 操作", "page.action_delete_confirm", "confirm"),
    ],
  },

  S1: {
    description: "Action 后状态",
    assertions: [
      s("S1-1", "playwright", "challenge.page.url", "页面 应进入 我的挑战", "page.challenge", "url"),
      s("S1-2", "playwright", "created_metric.visible", "我的挑战列表 应显示指标 `E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-CREATED`", "page.challenge_items", "visible_title", { titleFrom: "data.metrics.2.title" }),
      s("S1-3", "playwright", "modified_metric.visible", "我的挑战列表 应显示指标 `E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-MODIFIED`", "page.challenge_items", "visible_title", { titleFrom: "data.metrics.0.modifiedTitle" }),
      s("S1-4", "playwright", "edit_metric.hidden", "我的挑战列表 应不显示指标 `E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-EDIT`", "page.challenge_items", "hidden_title", { titleFrom: "data.metrics.0.title" }),
      s("S1-5", "playwright", "delete_forbidden_metric.visible", "我的挑战列表 应显示指标 `E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-DELETE-FORBIDDEN`", "page.challenge_items", "visible_title", { titleFrom: "data.metrics.1.title" }),
      s("S1-6", "playwright", "created_action.visible", "我的挑战列表 应显示行动项 `E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION-CREATED`", "page.challenge_items", "visible_title", { titleFrom: "data.actions.2.title" }),
      s("S1-7", "playwright", "modified_action.visible", "我的挑战列表 应显示行动项 `E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION-MODIFIED`", "page.challenge_items", "visible_title", { titleFrom: "data.actions.0.modifiedTitle" }),
      s("S1-8", "playwright", "edit_action.hidden", "我的挑战列表 应不显示行动项 `E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION-EDIT`", "page.challenge_items", "hidden_title", { titleFrom: "data.actions.0.title" }),
      s("S1-9", "playwright", "deleted_action.hidden", "我的挑战列表 应不显示行动项 `E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION-DELETE`", "page.challenge_items", "hidden_title", { titleFrom: "data.actions.1.title" }),
      s("S1-10", "api", "api.created_metric.contains", "我的挑战数据 应包含指标 `E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-CREATED`", "api.my_challenges", "contains_title", { titleFrom: "data.metrics.2.title" }),
      s("S1-11", "api", "api.modified_metric.contains", "我的挑战数据 应包含指标 `E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-MODIFIED`", "api.my_challenges", "contains_title", { titleFrom: "data.metrics.0.modifiedTitle" }),
      s("S1-12", "api", "api.delete_forbidden_metric.contains", "我的挑战数据 应包含指标 `E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-DELETE-FORBIDDEN`", "api.my_challenges", "contains_title", { titleFrom: "data.metrics.1.title" }),
      s("S1-13", "api", "api.created_action.contains", "我的挑战数据 应包含行动项 `E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION-CREATED`", "api.my_challenges", "contains_title", { titleFrom: "data.actions.2.title" }),
      s("S1-14", "api", "api.modified_action.contains", "我的挑战数据 应包含行动项 `E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION-MODIFIED`", "api.my_challenges", "contains_title", { titleFrom: "data.actions.0.modifiedTitle" }),
      s("S1-15", "api", "api.deleted_action.not_contains", "我的挑战数据 应不包含行动项 `E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION-DELETE`", "api.my_challenges", "not_contains_title", { titleFrom: "data.actions.1.title" }),
      s("S1-16", "prisma", "db.created_metric.exists", "应存在 归属于目标 `E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION`、标题为 `E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-CREATED` 的指标", "db.metric", "exists", { objectiveTitleFrom: "data.objective.title", titleFrom: "data.metrics.2.title" }),
      s("S1-17", "prisma", "db.modified_metric.exists", "应存在 归属于目标 `E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION`、标题为 `E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-MODIFIED` 的指标", "db.metric", "exists", { objectiveTitleFrom: "data.objective.title", titleFrom: "data.metrics.0.modifiedTitle" }),
      s("S1-18", "prisma", "db.delete_forbidden_metric.exists", "应存在 归属于目标 `E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION`、标题为 `E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION-DELETE-FORBIDDEN` 的指标", "db.metric", "exists", { objectiveTitleFrom: "data.objective.title", titleFrom: "data.metrics.1.title" }),
      s("S1-19", "prisma", "db.created_action.exists", "应存在 归属于目标 `E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION`、标题为 `E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION-CREATED` 的行动项", "db.action", "exists", { objectiveTitleFrom: "data.objective.title", titleFrom: "data.actions.2.title" }),
      s("S1-20", "prisma", "db.modified_action.exists", "应存在 归属于目标 `E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION`、标题为 `E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION-MODIFIED` 的行动项", "db.action", "exists", { objectiveTitleFrom: "data.objective.title", titleFrom: "data.actions.0.modifiedTitle" }),
      s("S1-21", "prisma", "db.deleted_action.absent", "应不存在 归属于目标 `E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION`、标题为 `E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION-DELETE` 的行动项", "db.action", "absent", { objectiveTitleFrom: "data.objective.title", titleFrom: "data.actions.1.title" }),
      s("S1-22", "prisma", "db.objective.unchanged", "标题为 `E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION` 的目标阶段 应仍为 `orfReestimate`，流转状态 应仍为 `reestimating`", "db.objective_stage", "exists", { targetFrom: "data.objective" }),
    ],
  },

  Clean: {
    description: "恢复 B",
    steps: [
      s("Clean-1", "prisma", "db.objectives.delete_created", "删除 本用例创建的目标标题前缀 `E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION` 对应的目标及其派生数据", "db.objectives_by_prefix", "delete", { prefixFrom: "data.targetPrefix" }),
      s("Clean-2", "api", "auth.logout", "注销当前普通成员登录会话", "auth", "logout"),
      s("Clean-3", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      s("Clean-4", "api", "ory.member_identity.delete", "删除 本用例普通成员登录身份", "ory.identity", "delete_by_email", { emailFrom: "data.memberEmail" }),
      s("Clean-5", "prisma", "db.member_user.delete", "删除 本用例普通成员用户", "db.user", "delete", { emailFrom: "data.memberEmail" }),
      s("Clean-6", "prisma", "db.objectives.absent", "应不存在 标题前缀为 `E2E-TARGET-MEMBER-REESTIMATE-METRIC-ACTION` 的目标", "db.objectives_by_prefix", "absent", { prefixFrom: "data.targetPrefix" }),
      s("Clean-7", "prisma", "db.metrics.absent", "应不存在 标题前缀为 `E2E-METRIC-MEMBER-REESTIMATE-METRIC-ACTION` 的指标", "db.metrics_by_prefix", "absent", { prefixFrom: "data.metricPrefix" }),
      s("Clean-8", "prisma", "db.actions.absent", "应不存在 标题前缀为 `E2E-ACTION-MEMBER-REESTIMATE-METRIC-ACTION` 的行动项", "db.actions_by_prefix", "absent", { prefixFrom: "data.actionPrefix" }),
      s("Clean-9", "api", "ory.member_identity.absent", "邮箱为 `orf-member-reestimate-metric-action-e2e@orf.local` 的普通成员登录身份 应不存在", "ory.identity", "absent", { emailFrom: "data.memberEmail" }),
      s("Clean-10", "prisma", "db.member_user.absent", "邮箱为 `orf-member-reestimate-metric-action-e2e@orf.local` 的普通成员用户 应不存在", "db.user", "absent", { emailFrom: "data.memberEmail" }),
      s("Clean-11", "api", "session.unauthenticated", "当前会话 应为 未登录", "auth.session", "unauthenticated"),
    ],
  },
} satisfies StateCaseSpec<MemberReestimateMetricActionPermissionsCaseData>;
