import { STATE_CASE_MODEL, type StateCaseSpec, type StepExecutionMethod, type StepSpec } from "../../_framework/types";
import type { SystemMembersEditCaseData } from "./_support/members-edit.context";

function step(
  caseStepId: string,
  method: StepExecutionMethod,
  id: string,
  title: string,
  object: string,
  operator: string,
  params?: Record<string, unknown>,
): StepSpec {
  return {
    source: { caseStepId, method },
    id,
    title,
    object,
    operator,
    ...(params ? { params } : {}),
  };
}

export const systemMembersEditCase = {
  id: "system.members-edit.validation",
  title: "06-成员管理编辑用户校验",
  model: STATE_CASE_MODEL,
  tags: ["system", "members", "edit-user", "validation"],
  data: {
    admin: {
      email: "orf-system-members-edit-admin-e2e@orf.local",
      password: "OrfSystemMembersEditAdminE2E!2026",
      name: "ORF Members Edit Admin E2E",
      role: "admin",
    },
    sourceUser: {
      email: "orf-system-members-edit-source-e2e@orf.local",
      name: "ORF Members Edit Source E2E",
      role: "member",
    },
    updatedUser: {
      email: "orf-system-members-edit-updated-e2e@orf.local",
      name: "ORF Members Edit Updated E2E",
      role: "admin",
    },
    existingUser: {
      email: "orf-system-members-edit-existing-e2e@orf.local",
      name: "ORF Members Edit Existing E2E",
      role: "member",
    },
    cancelUser: {
      email: "orf-system-members-edit-cancel-e2e@orf.local",
      name: "ORF Members Edit Cancel E2E",
      role: "member",
    },
    closeUser: {
      email: "orf-system-members-edit-close-e2e@orf.local",
      name: "ORF Members Edit Close E2E",
      role: "member",
    },
    invalidEmailName: "ORF Members Edit Invalid Email E2E",
    defaultLandingPath: "/bounties",
    membersPath: "/system/members",
  },
  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      step("B-1", "api", "frontend.ready", "前端服务 应可用", "frontend.service", "available"),
      step("B-2", "api", "backend.ready", "后端服务 应可用", "api.health", "ok"),
      step("B-3", "api", "frontend.login_entry.accessible", "前端登录页入口 应可访问", "frontend.login_entry", "accessible"),
      step("B-4", "api", "session.endpoint.accessible", "当前会话查询能力 应可用", "auth.session", "accessible"),
      step("B-5", "prisma", "db.ready", "ORF 数据库 应可连接", "db", "ready"),
      step("B-6", "prisma", "db.schema.current", "ORF 数据库 schema 应为 当前测试版本", "db.schema", "current"),
      step("B-7", "api", "ory.admin_public.ready", "Ory/Kratos 认证服务的管理和公共访问能力 应可用", "ory.admin_public", "ready"),
      step("B-8", "api", "session.unauthenticated", "当前会话 应为 未登录", "auth.session", "unauthenticated"),
      step("B-9", "playwright", "cookie.absent", "当前浏览器 应不存在 Ory 登录会话 cookie", "browser.cookie", "absent"),
      step("B-10", "playwright", "storage.empty", "当前浏览器 应不保留本地登录态", "browser.auth_storage", "empty"),
    ],
  },
  Setup: {
    description: "准备管理员、待编辑用户和已存在邮箱用户，并以管理员身份进入成员管理页面",
    steps: [
      step("Setup-1", "api", "ory.admin_identity.upsert", "准备邮箱为 `orf-system-members-edit-admin-e2e@orf.local`、使用固定测试密码的成员管理编辑用户管理员测试认证身份", "ory.identity", "upsert_password", { emailFrom: "data.admin.email", passwordFrom: "data.admin.password", nameFrom: "data.admin.name", saveAs: "adminIdentity" }),
      step("Setup-2", "prisma", "db.admin_user.upsert", "准备姓名为 \"ORF Members Edit Admin E2E\"、邮箱为 `orf-system-members-edit-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的成员管理编辑用户管理员测试用户", "db.user", "upsert", { emailFrom: "data.admin.email", passwordFrom: "data.admin.password", nameFrom: "data.admin.name", roleFrom: "data.admin.role", status: "active", identityIdFrom: "runtime.adminIdentity.id", saveAs: "adminUser" }),
      step("Setup-3", "api", "admin.preferences.default_landing_path.set", "设置成员管理编辑用户管理员测试用户默认进入页面为 首页（默认系统页）", "user.preferences", "set_default_landing_path_by_email", { emailFrom: "data.admin.email", pathFrom: "data.defaultLandingPath" }),
      step("Setup-4", "prisma", "db.source_user.upsert", "准备姓名为 \"ORF Members Edit Source E2E\"、邮箱为 `orf-system-members-edit-source-e2e@orf.local`、角色为 `member`、状态为 `active` 的成员管理待编辑测试用户", "db.user", "upsert", { emailFrom: "data.sourceUser.email", nameFrom: "data.sourceUser.name", roleFrom: "data.sourceUser.role", status: "active", saveAs: "sourceUser" }),
      step("Setup-5", "prisma", "db.existing_user.upsert", "准备姓名为 \"ORF Members Edit Existing E2E\"、邮箱为 `orf-system-members-edit-existing-e2e@orf.local`、角色为 `member`、状态为 `active` 的成员管理编辑用户已存在邮箱测试用户", "db.user", "upsert", { emailFrom: "data.existingUser.email", nameFrom: "data.existingUser.name", roleFrom: "data.existingUser.role", status: "active", saveAs: "existingUser" }),
      step("Setup-6", "prisma", "db.updated_user.delete", "删除邮箱为 `orf-system-members-edit-updated-e2e@orf.local` 的成员管理编辑后目标测试用户", "db.user", "delete", { emailFrom: "data.updatedUser.email" }),
      step("Setup-7", "api", "ory.admin_sessions.revoke", "撤销邮箱为 `orf-system-members-edit-admin-e2e@orf.local` 的成员管理编辑用户管理员测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.admin.email" }),
      step("Setup-8", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Setup-9", "playwright", "page.goto.auth", "打开 ORF 登录页", "page", "goto", { path: "/auth" }),
      step("Setup-10", "playwright", "fill.admin_email", "在邮箱输入框输入 `orf-system-members-edit-admin-e2e@orf.local`", "page", "fill", { label: "Email", valueFrom: "data.admin.email" }),
      step("Setup-11", "playwright", "fill.admin_password", "在密码输入框输入成员管理编辑用户管理员测试固定密码", "page", "fill", { label: "Password", exact: true, valueFrom: "data.admin.password" }),
      step("Setup-12", "playwright", "click.sign_in", "点击 \"Sign In\" 登录操作", "page.login_form", "submit", { saveAs: "adminLoginResponse" }),
      step("Setup-13", "api", "session.admin_authenticated", "当前会话 应为 邮箱为 `orf-system-members-edit-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
      step("Setup-14", "playwright", "page.goto.members", "打开 成员管理页面", "page", "goto", { pathFrom: "data.membersPath" }),
    ],
  },
  S0: {
    description: "管理员已登录并位于成员管理页面，待编辑用户可编辑",
    assertions: [
      step("S0-1", "api", "session.admin_authenticated", "当前会话 应为 邮箱为 `orf-system-members-edit-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
      step("S0-2", "playwright", "url.members", "当前页面 应为 成员管理页面", "page.url", "match", { pattern: "/system/members$" }),
      step("S0-3", "playwright", "members.list.source.visible", "成员管理页面的用户列表 应显示 待编辑测试用户", "page.members_list", "contains_user", { emailFrom: "data.sourceUser.email", nameFrom: "data.sourceUser.name" }),
      step("S0-4", "playwright", "source.edit.visible", "待编辑测试用户列表行的 \"编辑\" 操作 应可见", "page.member_row_edit", "visible", { emailFrom: "data.sourceUser.email" }),
      step("S0-5", "playwright", "source.edit.enabled", "待编辑测试用户列表行的 \"编辑\" 操作 应可点击", "page.member_row_edit", "enabled", { emailFrom: "data.sourceUser.email" }),
      step("S0-6", "prisma", "db.source_user.exists", "邮箱为 `orf-system-members-edit-source-e2e@orf.local` 的成员管理待编辑测试用户 应存在", "db.user", "matches", { emailFrom: "data.sourceUser.email", roleFrom: "data.sourceUser.role", status: "active" }),
      step("S0-7", "prisma", "db.existing_user.exists", "邮箱为 `orf-system-members-edit-existing-e2e@orf.local` 的成员管理编辑用户已存在邮箱测试用户 应存在", "db.user", "matches", { emailFrom: "data.existingUser.email", roleFrom: "data.existingUser.role", status: "active" }),
      step("S0-8", "prisma", "db.updated_user.absent", "邮箱为 `orf-system-members-edit-updated-e2e@orf.local` 的成员管理编辑后目标测试用户 应不存在", "db.user", "absent", { emailFrom: "data.updatedUser.email" }),
    ],
  },
  Action: {
    description: "依次验证编辑用户成功、输入校验、重复邮箱、取消和关闭弹窗",
    steps: [
      step("Action-1", "playwright", "source.edit.click", "点击 待编辑测试用户列表行的 \"编辑\" 操作", "page.member_row_edit", "click", { emailFrom: "data.sourceUser.email" }),
      step("Action-2", "playwright", "edit.dialog.observe", "查看 编辑用户弹窗", "page.edit_user_dialog", "observe", { saveAs: "initialDialogSnapshot" }),
      step("Action-3", "playwright", "edit.updated.name.fill", "将编辑用户弹窗的姓名输入框修改为 \"ORF Members Edit Updated E2E\"", "page.edit_user_dialog.name", "fill", { valueFrom: "data.updatedUser.name" }),
      step("Action-4", "playwright", "edit.updated.email.fill", "将编辑用户弹窗的邮箱输入框修改为 `orf-system-members-edit-updated-e2e@orf.local`", "page.edit_user_dialog.email", "fill", { valueFrom: "data.updatedUser.email" }),
      step("Action-5", "playwright", "edit.updated.role.select", "将编辑用户弹窗的角色选择框修改为 \"管理员\"", "page.edit_user_dialog.role", "select", { label: "管理员" }),
      step("Action-6", "playwright", "edit.updated.save", "点击 编辑用户弹窗的保存操作", "page.edit_user_dialog.save", "click_and_wait_updated", { emailFrom: "data.updatedUser.email" }),
      step("Action-7", "playwright", "updated.edit.click.empty_name", "点击 已编辑测试用户列表行的 \"编辑\" 操作", "page.member_row_edit", "click", { emailFrom: "data.updatedUser.email" }),
      step("Action-8", "playwright", "edit.empty_name.clear", "清空 编辑用户弹窗的姓名输入框", "page.edit_user_dialog.name", "clear"),
      step("Action-9", "playwright", "edit.empty_name.save", "点击 编辑用户弹窗的保存操作", "page.edit_user_dialog.save", "click_invalid_and_snapshot", { field: "name", saveAs: "emptyNameSnapshot" }),
      step("Action-10", "playwright", "edit.empty_name.close", "关闭 编辑用户弹窗", "page.edit_user_dialog", "close"),
      step("Action-11", "playwright", "updated.edit.click.empty_email", "点击 已编辑测试用户列表行的 \"编辑\" 操作", "page.member_row_edit", "click", { emailFrom: "data.updatedUser.email" }),
      step("Action-12", "playwright", "edit.empty_email.clear", "清空 编辑用户弹窗的邮箱输入框", "page.edit_user_dialog.email", "clear"),
      step("Action-13", "playwright", "edit.empty_email.save", "点击 编辑用户弹窗的保存操作", "page.edit_user_dialog.save", "click_invalid_and_snapshot", { field: "email", saveAs: "emptyEmailSnapshot" }),
      step("Action-14", "playwright", "edit.empty_email.close", "关闭 编辑用户弹窗", "page.edit_user_dialog", "close"),
      step("Action-15", "playwright", "updated.edit.click.invalid_email", "点击 已编辑测试用户列表行的 \"编辑\" 操作", "page.member_row_edit", "click", { emailFrom: "data.updatedUser.email" }),
      step("Action-16", "playwright", "edit.invalid_email.fill", "将编辑用户弹窗的邮箱输入框修改为 \"invalid-email\"", "page.edit_user_dialog.email", "fill", { value: "invalid-email" }),
      step("Action-17", "playwright", "edit.invalid_email.save", "点击 编辑用户弹窗的保存操作", "page.edit_user_dialog.save", "click_invalid_and_snapshot", { field: "email", saveAs: "invalidEmailSnapshot" }),
      step("Action-18", "playwright", "edit.invalid_email.close", "关闭 编辑用户弹窗", "page.edit_user_dialog", "close"),
      step("Action-19", "playwright", "updated.edit.click.duplicate", "点击 已编辑测试用户列表行的 \"编辑\" 操作", "page.member_row_edit", "click", { emailFrom: "data.updatedUser.email" }),
      step("Action-20", "playwright", "edit.duplicate.email.fill", "将编辑用户弹窗的邮箱输入框修改为 `orf-system-members-edit-existing-e2e@orf.local`", "page.edit_user_dialog.email", "fill", { valueFrom: "data.existingUser.email" }),
      step("Action-21", "playwright", "edit.duplicate.save", "点击 编辑用户弹窗的保存操作", "page.edit_user_dialog.save", "click_duplicate_and_snapshot", { saveAs: "duplicateEmailSnapshot" }),
      step("Action-22", "playwright", "edit.duplicate.close", "关闭 编辑用户弹窗", "page.edit_user_dialog", "close"),
      step("Action-23", "playwright", "updated.edit.click.cancel", "点击 已编辑测试用户列表行的 \"编辑\" 操作", "page.member_row_edit", "click", { emailFrom: "data.updatedUser.email" }),
      step("Action-24", "playwright", "edit.cancel.name.fill", "将编辑用户弹窗的姓名输入框修改为 \"ORF Members Edit Cancel E2E\"", "page.edit_user_dialog.name", "fill", { valueFrom: "data.cancelUser.name" }),
      step("Action-25", "playwright", "edit.cancel.email.fill", "将编辑用户弹窗的邮箱输入框修改为 `orf-system-members-edit-cancel-e2e@orf.local`", "page.edit_user_dialog.email", "fill", { valueFrom: "data.cancelUser.email" }),
      step("Action-26", "playwright", "edit.cancel.role.select", "将编辑用户弹窗的角色选择框修改为 \"成员\"", "page.edit_user_dialog.role", "select", { label: "成员" }),
      step("Action-27", "playwright", "edit.cancel.click", "点击 编辑用户弹窗的取消操作", "page.edit_user_dialog.cancel", "click"),
      step("Action-28", "playwright", "updated.edit.click.close", "点击 已编辑测试用户列表行的 \"编辑\" 操作", "page.member_row_edit", "click", { emailFrom: "data.updatedUser.email" }),
      step("Action-29", "playwright", "edit.close.name.fill", "将编辑用户弹窗的姓名输入框修改为 \"ORF Members Edit Close E2E\"", "page.edit_user_dialog.name", "fill", { valueFrom: "data.closeUser.name" }),
      step("Action-30", "playwright", "edit.close.email.fill", "将编辑用户弹窗的邮箱输入框修改为 `orf-system-members-edit-close-e2e@orf.local`", "page.edit_user_dialog.email", "fill", { valueFrom: "data.closeUser.email" }),
      step("Action-31", "playwright", "edit.close.role.select", "将编辑用户弹窗的角色选择框修改为 \"成员\"", "page.edit_user_dialog.role", "select", { label: "成员" }),
      step("Action-32", "playwright", "edit.close.click", "点击 编辑用户弹窗的关闭操作", "page.edit_user_dialog.close", "click"),
    ],
  },
  S1: {
    description: "编辑用户成功，校验失败和取消关闭均不修改用户",
    assertions: [
      step("S1-1", "playwright", "dialog.title.visible", "编辑用户弹窗标题 应显示 \"编辑用户\"", "page.edit_user_dialog_snapshot", "title_visible", { snapshotFrom: "runtime.initialDialogSnapshot" }),
      step("S1-2", "playwright", "dialog.name.value", "编辑用户弹窗的姓名输入框 应显示 \"ORF Members Edit Source E2E\"", "page.edit_user_dialog_snapshot", "name_value", { snapshotFrom: "runtime.initialDialogSnapshot", valueFrom: "data.sourceUser.name" }),
      step("S1-3", "playwright", "dialog.email.value", "编辑用户弹窗的邮箱输入框 应显示 `orf-system-members-edit-source-e2e@orf.local`", "page.edit_user_dialog_snapshot", "email_value", { snapshotFrom: "runtime.initialDialogSnapshot", valueFrom: "data.sourceUser.email" }),
      step("S1-4", "playwright", "dialog.role.value", "编辑用户弹窗的角色选择框 应显示 \"成员\"", "page.edit_user_dialog_snapshot", "role_value", { snapshotFrom: "runtime.initialDialogSnapshot", label: "成员" }),
      step("S1-5", "playwright", "members.list.updated.visible", "保存有效编辑用户信息后，成员管理页面的用户列表 应显示 已编辑测试用户", "page.members_list", "contains_user", { emailFrom: "data.updatedUser.email", nameFrom: "data.updatedUser.name" }),
      step("S1-6", "playwright", "members.list.source.hidden", "保存有效编辑用户信息后，成员管理页面的用户列表 应不显示 原待编辑测试用户", "page.members_list", "lacks_user", { emailFrom: "data.sourceUser.email" }),
      step("S1-7", "prisma", "db.updated_user.exists", "邮箱为 `orf-system-members-edit-updated-e2e@orf.local` 的成员管理编辑后目标测试用户 应存在", "db.user", "matches", { emailFrom: "data.updatedUser.email", roleFrom: "data.updatedUser.role", status: "active" }),
      step("S1-8", "prisma", "db.updated_user.role", "邮箱为 `orf-system-members-edit-updated-e2e@orf.local` 的成员管理编辑后目标测试用户角色 应为 `admin`", "db.user", "matches", { emailFrom: "data.updatedUser.email", roleFrom: "data.updatedUser.role" }),
      step("S1-9", "prisma", "db.source_user.absent", "邮箱为 `orf-system-members-edit-source-e2e@orf.local` 的成员管理待编辑测试用户 应不存在", "db.user", "absent", { emailFrom: "data.sourceUser.email" }),
      step("S1-10", "playwright", "empty_name.dialog.visible", "姓名为空保存后，编辑用户弹窗 应保持可见", "page.edit_user_dialog_snapshot", "dialog_visible", { snapshotFrom: "runtime.emptyNameSnapshot" }),
      step("S1-11", "playwright", "empty_name.required", "姓名为空保存后，系统 应提示 姓名必填规则错误", "page.edit_user_dialog_snapshot", "field_invalid", { snapshotFrom: "runtime.emptyNameSnapshot", field: "name" }),
      step("S1-12", "prisma", "db.updated_name.still", "已编辑测试用户的姓名 应仍为 \"ORF Members Edit Updated E2E\"", "db.user", "matches", { emailFrom: "data.updatedUser.email", nameFrom: "data.updatedUser.name" }),
      step("S1-13", "playwright", "empty_email.dialog.visible", "邮箱为空保存后，编辑用户弹窗 应保持可见", "page.edit_user_dialog_snapshot", "dialog_visible", { snapshotFrom: "runtime.emptyEmailSnapshot" }),
      step("S1-14", "playwright", "empty_email.required", "邮箱为空保存后，系统 应提示 邮箱必填规则错误", "page.edit_user_dialog_snapshot", "field_invalid", { snapshotFrom: "runtime.emptyEmailSnapshot", field: "email" }),
      step("S1-15", "prisma", "db.updated_email.still", "已编辑测试用户的邮箱 应仍为 `orf-system-members-edit-updated-e2e@orf.local`", "db.user", "matches", { emailFrom: "data.updatedUser.email", nameFrom: "data.updatedUser.name" }),
      step("S1-16", "playwright", "invalid_email.dialog.visible", "邮箱格式错误保存后，编辑用户弹窗 应保持可见", "page.edit_user_dialog_snapshot", "dialog_visible", { snapshotFrom: "runtime.invalidEmailSnapshot" }),
      step("S1-17", "playwright", "invalid_email.format", "邮箱格式错误保存后，系统 应提示 邮箱格式规则错误", "page.edit_user_dialog_snapshot", "field_invalid", { snapshotFrom: "runtime.invalidEmailSnapshot", field: "email" }),
      step("S1-18", "prisma", "db.invalid_email_name.absent", "姓名为 \"ORF Members Edit Invalid Email E2E\" 的成员管理邮箱格式错误目标测试用户 应不存在", "db.user_name", "absent", { nameFrom: "data.invalidEmailName" }),
      step("S1-19", "playwright", "duplicate.dialog.visible", "邮箱已存在保存后，编辑用户弹窗 应保持可见", "page.edit_user_dialog_snapshot", "dialog_visible", { snapshotFrom: "runtime.duplicateEmailSnapshot" }),
      step("S1-20", "playwright", "duplicate.email.error", "邮箱已存在保存后，系统 应提示 邮箱已存在规则错误", "page.edit_user_dialog_snapshot", "duplicate_email_error", { snapshotFrom: "runtime.duplicateEmailSnapshot" }),
      step("S1-21", "prisma", "db.existing_user.count", "邮箱为 `orf-system-members-edit-existing-e2e@orf.local` 的成员管理编辑用户已存在邮箱测试用户数量 应为 1", "db.user_email", "count", { emailFrom: "data.existingUser.email", expected: 1 }),
      step("S1-22", "playwright", "cancel.dialog.hidden", "点击取消后，编辑用户弹窗 应不可见", "page.edit_user_dialog", "hidden"),
      step("S1-23", "playwright", "members.list.updated.after_cancel", "点击取消后，成员管理页面的用户列表 应显示 已编辑测试用户", "page.members_list", "contains_user", { emailFrom: "data.updatedUser.email", nameFrom: "data.updatedUser.name" }),
      step("S1-24", "prisma", "db.cancel_user.absent", "邮箱为 `orf-system-members-edit-cancel-e2e@orf.local` 的成员管理取消编辑目标测试用户 应不存在", "db.user", "absent", { emailFrom: "data.cancelUser.email" }),
      step("S1-25", "playwright", "close.dialog.hidden", "点击关闭后，编辑用户弹窗 应不可见", "page.edit_user_dialog", "hidden"),
      step("S1-26", "playwright", "members.list.updated.after_close", "点击关闭后，成员管理页面的用户列表 应显示 已编辑测试用户", "page.members_list", "contains_user", { emailFrom: "data.updatedUser.email", nameFrom: "data.updatedUser.name" }),
      step("S1-27", "prisma", "db.close_user.absent", "邮箱为 `orf-system-members-edit-close-e2e@orf.local` 的成员管理关闭编辑目标测试用户 应不存在", "db.user", "absent", { emailFrom: "data.closeUser.email" }),
      step("S1-28", "api", "session.admin_authenticated.after_edit", "当前会话 应仍为 邮箱为 `orf-system-members-edit-admin-e2e@orf.local`、角色为 `admin`、状态为 `active` 的已登录会话", "auth.session", "authenticated", { emailFrom: "data.admin.email", roleFrom: "data.admin.role", status: "active" }),
    ],
  },
  Clean: {
    description: "删除编辑用户相关测试数据并恢复未登录基准状态",
    steps: [
      step("Clean-1", "api", "auth.logout", "注销当前登录会话", "auth", "logout"),
      step("Clean-2", "playwright", "page.runtime.stop", "离开当前 ORF 前端页面", "page.runtime", "stop"),
      step("Clean-3", "playwright", "browser.clear", "移除当前浏览器中的残留登录态", "browser", "clear_state"),
      step("Clean-4", "api", "ory.admin_sessions.revoke", "撤销邮箱为 `orf-system-members-edit-admin-e2e@orf.local` 的成员管理编辑用户管理员测试认证身份的残留登录会话", "ory.sessions", "revoke_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-5", "api", "ory.admin_identity.delete", "删除邮箱为 `orf-system-members-edit-admin-e2e@orf.local` 的成员管理编辑用户管理员测试认证身份", "ory.identity", "delete_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-6", "api", "admin.preferences.default_landing_path.reset", "恢复邮箱为 `orf-system-members-edit-admin-e2e@orf.local` 的默认进入页面为 系统默认", "user.preferences", "reset_default_landing_path_by_email", { emailFrom: "data.admin.email" }),
      step("Clean-7", "prisma", "db.admin_user.memberships.delete", "删除邮箱为 `orf-system-members-edit-admin-e2e@orf.local` 的成员管理编辑用户管理员测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.admin.email" }),
      step("Clean-8", "prisma", "db.source_user.memberships.delete", "删除邮箱为 `orf-system-members-edit-source-e2e@orf.local` 的成员管理待编辑测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.sourceUser.email" }),
      step("Clean-9", "prisma", "db.updated_user.memberships.delete", "删除邮箱为 `orf-system-members-edit-updated-e2e@orf.local` 的成员管理编辑后目标测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.updatedUser.email" }),
      step("Clean-10", "prisma", "db.existing_user.memberships.delete", "删除邮箱为 `orf-system-members-edit-existing-e2e@orf.local` 的成员管理编辑用户已存在邮箱测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.existingUser.email" }),
      step("Clean-11", "prisma", "db.cancel_user.memberships.delete", "删除邮箱为 `orf-system-members-edit-cancel-e2e@orf.local` 的成员管理取消编辑目标测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.cancelUser.email" }),
      step("Clean-12", "prisma", "db.close_user.memberships.delete", "删除邮箱为 `orf-system-members-edit-close-e2e@orf.local` 的成员管理关闭编辑目标测试用户的默认团队成员关系", "db.user", "delete_memberships", { emailFrom: "data.closeUser.email" }),
      step("Clean-13", "prisma", "db.admin_user.delete", "删除邮箱为 `orf-system-members-edit-admin-e2e@orf.local` 的成员管理编辑用户管理员测试用户", "db.user", "delete", { emailFrom: "data.admin.email" }),
      step("Clean-14", "prisma", "db.source_user.delete", "删除邮箱为 `orf-system-members-edit-source-e2e@orf.local` 的成员管理待编辑测试用户", "db.user", "delete", { emailFrom: "data.sourceUser.email" }),
      step("Clean-15", "prisma", "db.updated_user.delete", "删除邮箱为 `orf-system-members-edit-updated-e2e@orf.local` 的成员管理编辑后目标测试用户", "db.user", "delete", { emailFrom: "data.updatedUser.email" }),
      step("Clean-16", "prisma", "db.existing_user.delete", "删除邮箱为 `orf-system-members-edit-existing-e2e@orf.local` 的成员管理编辑用户已存在邮箱测试用户", "db.user", "delete", { emailFrom: "data.existingUser.email" }),
      step("Clean-17", "prisma", "db.cancel_user.delete", "删除邮箱为 `orf-system-members-edit-cancel-e2e@orf.local` 的成员管理取消编辑目标测试用户", "db.user", "delete", { emailFrom: "data.cancelUser.email" }),
      step("Clean-18", "prisma", "db.close_user.delete", "删除邮箱为 `orf-system-members-edit-close-e2e@orf.local` 的成员管理关闭编辑目标测试用户", "db.user", "delete", { emailFrom: "data.closeUser.email" }),
      step("Clean-19", "api", "ory.admin_identity.absent", "邮箱为 `orf-system-members-edit-admin-e2e@orf.local` 的成员管理编辑用户管理员测试认证身份 应不存在", "ory.identity", "absent", { emailFrom: "data.admin.email" }),
      step("Clean-20", "prisma", "db.admin_user.absent", "邮箱为 `orf-system-members-edit-admin-e2e@orf.local` 的成员管理编辑用户管理员测试用户 应不存在", "db.user", "absent", { emailFrom: "data.admin.email" }),
      step("Clean-21", "prisma", "db.source_user.absent", "邮箱为 `orf-system-members-edit-source-e2e@orf.local` 的成员管理待编辑测试用户 应不存在", "db.user", "absent", { emailFrom: "data.sourceUser.email" }),
      step("Clean-22", "prisma", "db.updated_user.absent", "邮箱为 `orf-system-members-edit-updated-e2e@orf.local` 的成员管理编辑后目标测试用户 应不存在", "db.user", "absent", { emailFrom: "data.updatedUser.email" }),
      step("Clean-23", "prisma", "db.existing_user.absent", "邮箱为 `orf-system-members-edit-existing-e2e@orf.local` 的成员管理编辑用户已存在邮箱测试用户 应不存在", "db.user", "absent", { emailFrom: "data.existingUser.email" }),
      step("Clean-24", "prisma", "db.cancel_user.absent", "邮箱为 `orf-system-members-edit-cancel-e2e@orf.local` 的成员管理取消编辑目标测试用户 应不存在", "db.user", "absent", { emailFrom: "data.cancelUser.email" }),
      step("Clean-25", "prisma", "db.close_user.absent", "邮箱为 `orf-system-members-edit-close-e2e@orf.local` 的成员管理关闭编辑目标测试用户 应不存在", "db.user", "absent", { emailFrom: "data.closeUser.email" }),
    ],
  },
} satisfies StateCaseSpec<SystemMembersEditCaseData>;
