import { STATE_CASE_MODEL, type StateCaseSpec } from "../../_framework/types";
import type { AdminDeleteTaskReestimateCaseData } from "./_support/admin-delete-task-reestimate.context";

export const adminDeleteTaskReestimateCase = {
  id: "tasks.admin-delete-task-reestimate",
  title: "管理员在重估中支持删除行动项",
  model: STATE_CASE_MODEL,
  tags: ["tasks", "delete", "admin", "reestimate", "happy-path"],

  data: {
    adminEmail: "orf-admin-delete-task-reestimate-e2e@orf.local",
    adminPassword: "OrfAdminDeleteTaskReestimateE2E!2026",
    adminName: "ORF Admin Delete Task Reestimate E2E",
    adminRole: "admin",
    objectiveId: "obj-testd-admin-delete-task-reestimate",
    objectiveTitle: "E2E-TASK-DELETE-REESTIMATE-ADMIN: 目标前置",
    taskId: "task-testd-admin-delete-task-reestimate",
    taskTitle: "E2E-TASK-DELETE-REESTIMATE-ADMIN: 管理员删除行动项",
    taskDescription: "重估中的管理员待删除行动项测试前置。",
    taskStatus: "Todo",
    taskPriority: "Medium",
    subtaskId: "ck-testd-admin-delete-task-reestimate",
    subtaskLabel: "重估中管理员删除行动项子任务",
    objectiveStatus: "Draft",
  },

  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      { source: { caseStepId: "B-1", method: "api" }, id: "frontend.ready", title: "前端服务 应可用", object: "frontend.service", operator: "available" },
      { source: { caseStepId: "B-2", method: "api" }, id: "backend.ready", title: "后端服务 应可用", object: "api.health", operator: "ok" },
      { source: { caseStepId: "B-3", method: "api" }, id: "frontend.login_entry.accessible", title: "前端登录页入口 应可访问", object: "frontend.login_entry", operator: "accessible" },
      { source: { caseStepId: "B-4", method: "api" }, id: "session.endpoint.accessible", title: "当前会话查询能力 应可用", object: "auth.session", operator: "accessible" },
      { source: { caseStepId: "B-5", method: "prisma" }, id: "db.ready", title: "ORF 数据库 应可连接", object: "db", operator: "ready" },
      { source: { caseStepId: "B-6", method: "prisma" }, id: "db.schema.current", title: "ORF 数据库 schema 应为 当前测试版本", object: "db.schema", operator: "current" },
      { source: { caseStepId: "B-7", method: "api" }, id: "ory.admin_public.ready", title: "Ory/Kratos 认证服务的管理和公共访问能力 应可用", object: "ory.admin_public", operator: "ready" },
      { source: { caseStepId: "B-8", method: "api" }, id: "session.unauthenticated", title: "当前会话 应为 未登录", object: "auth.session", operator: "unauthenticated" },
      { source: { caseStepId: "B-9", method: "playwright" }, id: "cookie.absent", title: "当前浏览器 应不存在 Ory 登录会话 cookie", object: "browser.cookie", operator: "absent" },
      { source: { caseStepId: "B-10", method: "playwright" }, id: "storage.empty", title: "当前浏览器 应不保留本地登录态", object: "browser.auth_storage", operator: "empty" },
    ],
  },

  Setup: {
    description: "准备管理员、重估中的本用例目标、待删除行动项及其子行动项，并完成管理员登录与待重估筛选",
    steps: [
      { source: { caseStepId: "Setup-1", method: "prisma" }, id: "db.task.delete_residue", title: "删除 本用例残留的重估中测试行动项及其子行动项", object: "db.task", operator: "delete", params: { titleFrom: "data.taskTitle" } },
      { source: { caseStepId: "Setup-2", method: "prisma" }, id: "db.objective.delete_residue", title: "删除 本用例残留的重估中行动项目标及其派生数据", object: "db.objective", operator: "delete_by_title", params: { titleFrom: "data.objectiveTitle" } },
      { source: { caseStepId: "Setup-3", method: "api" }, id: "ory.admin_identity.upsert", title: "准备邮箱为 `orf-admin-delete-task-reestimate-e2e@orf.local`、使用固定测试密码的管理员登录身份", object: "ory.identity", operator: "upsert_password", params: { emailFrom: "data.adminEmail", nameFrom: "data.adminName", passwordFrom: "data.adminPassword", saveAs: "adminIdentity" } },
      { source: { caseStepId: "Setup-4", method: "prisma" }, id: "db.admin_user.upsert", title: "准备邮箱为 `orf-admin-delete-task-reestimate-e2e@orf.local`、角色为 `admin`、状态为 `active` 的管理员用户和默认团队成员关系", object: "db.user", operator: "upsert", params: { emailFrom: "data.adminEmail", nameFrom: "data.adminName", roleFrom: "data.adminRole", status: "active", identityIdFrom: "runtime.adminIdentity.id", saveAs: "adminUser" } },
      {
        source: { caseStepId: "Setup-5", method: "prisma" },
        id: "db.objective.upsert_task_target",
        title: "创建标题为 `E2E-TASK-DELETE-REESTIMATE-ADMIN: 目标前置`、流转状态为 `reestimating`、阶段为 `orfReestimate` 的本用例重估中行动项目标",
        object: "db.objective",
        operator: "upsert",
        params: {
          idFrom: "data.objectiveId",
          titleFrom: "data.objectiveTitle",
          teamIdFrom: "runtime.adminUser.teamId",
          stage: "orfReestimate",
          flowStatus: "reestimating",
          statusFrom: "data.objectiveStatus",
          createdByFrom: "runtime.adminUser.userId",
          updatedByFrom: "runtime.adminUser.userId",
          saveAs: "fixtureObjective",
        },
      },
      { source: { caseStepId: "Setup-6", method: "prisma" }, id: "db.task_target.from_objective", title: "记录 本用例重估中行动项目标", object: "db.task_target", operator: "from_objective", params: { objectiveIdFrom: "runtime.fixtureObjective.id", saveAs: "taskTarget" } },
      { source: { caseStepId: "Setup-7", method: "prisma" }, id: "db.task_target.prepare", title: "设置本用例重估中行动项目标的挑战者包含管理员", object: "db.task_target", operator: "prepare", params: { targetFrom: "runtime.taskTarget", memberNameFrom: "data.adminName" } },
      { source: { caseStepId: "Setup-8", method: "prisma" }, id: "db.fixture_task.create", title: "创建标题为 `E2E-TASK-DELETE-REESTIMATE-ADMIN: 管理员删除行动项`、执行人为管理员的本用例重估中测试行动项", object: "db.task", operator: "create_fixture", params: { idFrom: "data.taskId", targetFrom: "runtime.taskTarget", teamIdFrom: "runtime.adminUser.teamId", userIdFrom: "runtime.adminUser.userId", titleFrom: "data.taskTitle", descriptionFrom: "data.taskDescription", assigneeFrom: "data.adminName", statusFrom: "data.taskStatus", priorityFrom: "data.taskPriority", saveAs: "fixtureTask" } },
      { source: { caseStepId: "Setup-9", method: "prisma" }, id: "db.fixture_subtask.create", title: "创建标签为 `重估中管理员删除行动项子任务`、归属于本用例重估中测试行动项的本用例重估中测试子行动项", object: "db.task", operator: "create_subtask_fixture", params: { idFrom: "data.subtaskId", taskFrom: "runtime.fixtureTask", labelFrom: "data.subtaskLabel", saveAs: "fixtureSubtask" } },
      { source: { caseStepId: "Setup-10", method: "prisma" }, id: "db.fixture_task.recorded", title: "记录 本用例重估中测试行动项和测试子行动项", object: "db.task", operator: "fixture_recorded", params: { taskFrom: "runtime.fixtureTask", subtaskFrom: "runtime.fixtureSubtask" } },
      { source: { caseStepId: "Setup-11", method: "api" }, id: "ory.admin_sessions.revoke", title: "撤销管理员登录身份可能残留的登录会话", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Setup-12", method: "playwright" }, id: "auth.logout", title: "注销当前登录会话", object: "auth", operator: "logout" },
      { source: { caseStepId: "Setup-13", method: "playwright" }, id: "page.runtime.stop", title: "离开当前 ORF 前端页面", object: "page.runtime", operator: "stop" },
      { source: { caseStepId: "Setup-14", method: "playwright" }, id: "browser.clear", title: "移除当前浏览器中的残留登录态", object: "browser", operator: "clear_state" },
      { source: { caseStepId: "Setup-15", method: "playwright" }, id: "page.goto.auth", title: "打开 ORF 登录页", object: "page", operator: "goto", params: { path: "/auth" } },
      { source: { caseStepId: "Setup-16", method: "playwright" }, id: "fill.email", title: "在邮箱输入框输入管理员固定测试邮箱", object: "page", operator: "fill", params: { label: "Email", valueFrom: "data.adminEmail" } },
      { source: { caseStepId: "Setup-17", method: "playwright" }, id: "fill.password", title: "在密码输入框输入管理员固定测试密码", object: "page", operator: "fill", params: { label: "Password", exact: true, valueFrom: "data.adminPassword" } },
      { source: { caseStepId: "Setup-18", method: "playwright" }, id: "click.sign_in", title: "点击 \"Sign In\" 登录操作", object: "page.login_form", operator: "submit", params: { saveAs: "adminLoginResponse" } },
      { source: { caseStepId: "Setup-19", method: "playwright" }, id: "page.goto.tasks", title: "打开 挑战工作台", object: "page", operator: "goto", params: { path: "/tasks" } },
      { source: { caseStepId: "Setup-20", method: "playwright" }, id: "challenge.scope.mine", title: "切换到 \"我的挑战\" 视图", object: "page.challenge_scope", operator: "select", params: { label: "我的挑战" } },
      { source: { caseStepId: "Setup-21", method: "playwright" }, id: "challenge.status.pending_reestimate", title: "将状态筛选切换到 \"待重估\"", object: "page.challenge_status_filter", operator: "select", params: { label: "待重估" } },
    ],
  },

  S0: {
    description: "管理员已登录，本用例目标处于待重估对应的重估阶段，且删除入口可见",
    assertions: [
      { source: { caseStepId: "S0-1", method: "api" }, id: "session.authenticated", title: "当前会话 应为 已登录", object: "auth.session", operator: "authenticated" },
      { source: { caseStepId: "S0-2", method: "api" }, id: "session.email", title: "当前会话用户邮箱 应为 `orf-admin-delete-task-reestimate-e2e@orf.local`", object: "auth.session.user_email", operator: "equals", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "S0-3", method: "api" }, id: "session.role", title: "当前会话用户角色 应为 `admin`", object: "auth.session.user_role", operator: "equals", params: { roleFrom: "data.adminRole" } },
      { source: { caseStepId: "S0-4", method: "api" }, id: "session.status", title: "当前会话用户状态 应为 `active`", object: "auth.session.user_status", operator: "equals", params: { status: "active" } },
      { source: { caseStepId: "S0-5", method: "prisma" }, id: "db.task_target.flow_status", title: "本用例重估中行动项目标的流转状态 应为 `reestimating`", object: "db.task_target", operator: "flow_status", params: { targetFrom: "runtime.taskTarget", status: "reestimating" } },
      { source: { caseStepId: "S0-6", method: "prisma" }, id: "db.task_target.stage", title: "本用例重估中行动项目标的阶段 应为 `orfReestimate`", object: "db.task_target", operator: "stage", params: { targetFrom: "runtime.taskTarget", stage: "orfReestimate" } },
      { source: { caseStepId: "S0-7", method: "prisma" }, id: "db.task_target.challenger_present", title: "本用例重估中行动项目标的挑战者列表 应包含 本用例管理员", object: "db.task_target", operator: "challenger_present", params: { targetFrom: "runtime.taskTarget", memberNameFrom: "data.adminName" } },
      { source: { caseStepId: "S0-8", method: "prisma" }, id: "db.task_target.task_present", title: "本用例重估中行动项目标 应存在 标题为 `E2E-TASK-DELETE-REESTIMATE-ADMIN: 管理员删除行动项` 的行动项", object: "db.task_target", operator: "task_present", params: { targetFrom: "runtime.taskTarget", taskFrom: "runtime.fixtureTask" } },
      { source: { caseStepId: "S0-9", method: "prisma" }, id: "db.fixture_subtask.present", title: "本用例重估中测试行动项下 应存在 标签为 `重估中管理员删除行动项子任务` 的子行动项", object: "db.task", operator: "subtask_present", params: { taskFrom: "runtime.fixtureTask", labelFrom: "data.subtaskLabel" } },
      { source: { caseStepId: "S0-10", method: "prisma" }, id: "db.task_target.admin_can_delete", title: "本用例重估中行动项目标 应允许 当前管理员删除行动项", object: "db.task_target", operator: "can_delete_task", params: { targetFrom: "runtime.taskTarget", actorNameFrom: "data.adminName", roleFrom: "data.adminRole" } },
      { source: { caseStepId: "S0-11", method: "playwright" }, id: "url.tasks", title: "当前页面 应为 挑战工作台", object: "page.url", operator: "match", params: { pattern: "/tasks$" } },
      { source: { caseStepId: "S0-12", method: "playwright" }, id: "scope.mine.selected", title: "\"我的挑战\" 视图 应处于选中状态", object: "page.challenge_scope", operator: "selected", params: { label: "我的挑战" } },
      { source: { caseStepId: "S0-13", method: "playwright" }, id: "status.pending_reestimate.selected", title: "\"待重估\" 状态筛选 应处于选中状态", object: "page.challenge_status_filter", operator: "selected", params: { label: "待重估" } },
      { source: { caseStepId: "S0-14", method: "playwright" }, id: "target.panel.visible", title: "本用例重估中行动项目标面板 应可见", object: "page.task_target", operator: "visible", params: { targetFrom: "runtime.taskTarget" } },
      { source: { caseStepId: "S0-15", method: "playwright" }, id: "fixture_task.visible", title: "本用例重估中测试行动项标题 应可见", object: "page.task_target", operator: "task_visible", params: { targetFrom: "runtime.taskTarget", taskFrom: "runtime.fixtureTask" } },
      { source: { caseStepId: "S0-16", method: "playwright" }, id: "fixture_task.delete_visible", title: "本用例重估中测试行动项的 \"删除\" 操作 应可见", object: "page.task_target", operator: "delete_action_visible", params: { targetFrom: "runtime.taskTarget", taskFrom: "runtime.fixtureTask" } },
    ],
  },

  Action: {
    description: "管理员删除重估中目标下的本用例测试行动项并确认删除",
    steps: [
      { source: { caseStepId: "Action-1", method: "playwright" }, id: "fixture_task.delete", title: "点击 本用例重估中测试行动项的 \"删除\" 操作", object: "page.task_target", operator: "delete_task", params: { targetFrom: "runtime.taskTarget", taskFrom: "runtime.fixtureTask", saveAs: "deleteTaskDialog" } },
      { source: { caseStepId: "Action-2", method: "playwright" }, id: "delete_dialog.present", title: "删除行动项确认弹窗 应可见", object: "browser.dialog", operator: "present", params: { dialogFrom: "runtime.deleteTaskDialog" } },
      { source: { caseStepId: "Action-3", method: "playwright" }, id: "delete_dialog.message", title: "删除行动项确认弹窗 应显示 本用例重估中测试行动项标题 和受影响子行动项数量", object: "browser.dialog", operator: "message_contains", params: { dialogFrom: "runtime.deleteTaskDialog", titleFrom: "data.taskTitle", count: 1 } },
      { source: { caseStepId: "Action-4", method: "playwright" }, id: "delete_dialog.accept", title: "在删除行动项确认弹窗中点击 \"确认删除\"", object: "browser.dialog", operator: "accept_delete_task", params: { dialogFrom: "runtime.deleteTaskDialog", taskFrom: "runtime.fixtureTask", saveAs: "deleteTaskResponse" } },
      { source: { caseStepId: "Action-5", method: "api" }, id: "delete_task.response.record", title: "记录 删除本用例重估中测试行动项的结果", object: "api.task_delete_response", operator: "record", params: { responseFrom: "runtime.deleteTaskResponse", saveAs: "deleteTaskResult" } },
    ],
  },

  S1: {
    description: "行动项与子行动项已被删除，目标仍保留在待重估的我的挑战视图中",
    assertions: [
      { source: { caseStepId: "S1-1", method: "playwright" }, id: "url.tasks.still", title: "当前页面 应仍为 挑战工作台", object: "page.url", operator: "match", params: { pattern: "/tasks$" } },
      { source: { caseStepId: "S1-2", method: "playwright" }, id: "target.panel.still_visible", title: "本用例重估中行动项目标面板 应仍可见", object: "page.task_target", operator: "visible", params: { targetFrom: "runtime.taskTarget" } },
      { source: { caseStepId: "S1-3", method: "playwright" }, id: "fixture_task.absent", title: "本用例重估中测试行动项标题 应不可见", object: "page.task_target", operator: "task_absent", params: { targetFrom: "runtime.taskTarget", taskFrom: "runtime.fixtureTask" } },
      { source: { caseStepId: "S1-4", method: "playwright" }, id: "fixture_subtask.absent", title: "标签为 `重估中管理员删除行动项子任务` 的子行动项 应不可见", object: "page.task_target", operator: "subtask_absent", params: { targetFrom: "runtime.taskTarget", subtaskFrom: "runtime.fixtureSubtask" } },
      { source: { caseStepId: "S1-5", method: "api" }, id: "delete_task.response.success", title: "删除本用例重估中测试行动项的结果 应成功", object: "api.task_delete_response", operator: "success", params: { responseFrom: "runtime.deleteTaskResult" } },
      { source: { caseStepId: "S1-6", method: "api" }, id: "member_workbench.task_absent", title: "当前管理员的挑战工作台数据中，本用例重估中行动项目标 应不包含 本用例重估中测试行动项", object: "api.member_workbench", operator: "task_absent", params: { targetFrom: "runtime.taskTarget", taskFrom: "runtime.fixtureTask" } },
      { source: { caseStepId: "S1-7", method: "prisma" }, id: "db.task_target.task_absent", title: "本用例重估中行动项目标 应不存在 标题为 `E2E-TASK-DELETE-REESTIMATE-ADMIN: 管理员删除行动项` 的行动项", object: "db.task_target", operator: "task_absent", params: { targetFrom: "runtime.taskTarget", titleFrom: "data.taskTitle" } },
      { source: { caseStepId: "S1-8", method: "prisma" }, id: "db.fixture_subtask.absent", title: "本用例重估中测试行动项下 应不存在 标签为 `重估中管理员删除行动项子任务` 的子行动项", object: "db.task", operator: "subtask_absent", params: { taskFrom: "runtime.fixtureTask", labelFrom: "data.subtaskLabel" } },
      { source: { caseStepId: "S1-9", method: "prisma" }, id: "db.task_target.flow_status.still", title: "本用例重估中行动项目标的流转状态 应仍为 `reestimating`", object: "db.task_target", operator: "flow_status", params: { targetFrom: "runtime.taskTarget", status: "reestimating" } },
      { source: { caseStepId: "S1-10", method: "prisma" }, id: "db.task_target.challenger_present.still", title: "本用例重估中行动项目标的挑战者列表 应仍包含 本用例管理员", object: "db.task_target", operator: "challenger_present", params: { targetFrom: "runtime.taskTarget", memberNameFrom: "data.adminName" } },
      { source: { caseStepId: "S1-11", method: "api" }, id: "session.authenticated.still", title: "当前会话 应仍为 已登录", object: "auth.session", operator: "authenticated" },
      { source: { caseStepId: "S1-12", method: "api" }, id: "session.email.still", title: "当前会话用户邮箱 应仍为 `orf-admin-delete-task-reestimate-e2e@orf.local`", object: "auth.session.user_email", operator: "equals", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "S1-13", method: "api" }, id: "session.role.still", title: "当前会话用户角色 应仍为 `admin`", object: "auth.session.user_role", operator: "equals", params: { roleFrom: "data.adminRole" } },
    ],
  },

  Clean: {
    description: "删除残留目标、管理员身份和浏览器状态",
    steps: [
      { source: { caseStepId: "Clean-1", method: "prisma" }, id: "db.task.delete", title: "删除 本用例残留的重估中测试行动项及其子行动项", object: "db.task", operator: "delete", params: { titleFrom: "data.taskTitle", taskFrom: "runtime.fixtureTask" } },
      { source: { caseStepId: "Clean-2", method: "prisma" }, id: "db.objective.delete", title: "删除 本用例重估中行动项目标及其派生数据", object: "db.objective", operator: "delete_by_title", params: { titleFrom: "data.objectiveTitle" } },
      { source: { caseStepId: "Clean-3", method: "api" }, id: "auth.logout", title: "注销当前登录会话", object: "auth", operator: "logout" },
      { source: { caseStepId: "Clean-4", method: "playwright" }, id: "page.runtime.stop", title: "离开当前 ORF 前端页面", object: "page.runtime", operator: "stop" },
      { source: { caseStepId: "Clean-5", method: "playwright" }, id: "browser.clear", title: "移除当前浏览器中的残留登录态", object: "browser", operator: "clear_state" },
      { source: { caseStepId: "Clean-6", method: "api" }, id: "ory.admin_sessions.revoke", title: "撤销管理员登录身份的残留登录会话", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-7", method: "api" }, id: "ory.admin_identity.delete", title: "删除邮箱为 `orf-admin-delete-task-reestimate-e2e@orf.local` 的管理员登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-8", method: "prisma" }, id: "db.admin_membership.delete", title: "删除邮箱为 `orf-admin-delete-task-reestimate-e2e@orf.local` 的管理员用户默认团队成员关系", object: "db.user", operator: "delete_memberships", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-9", method: "prisma" }, id: "db.admin_user.delete", title: "删除邮箱为 `orf-admin-delete-task-reestimate-e2e@orf.local` 的管理员用户", object: "db.user", operator: "delete", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-10", method: "prisma" }, id: "db.task.absent", title: "应不存在 标题为 `E2E-TASK-DELETE-REESTIMATE-ADMIN: 管理员删除行动项` 的测试行动项", object: "db.task", operator: "absent", params: { titleFrom: "data.taskTitle" } },
      { source: { caseStepId: "Clean-11", method: "prisma" }, id: "db.objective.absent", title: "应不存在 标题为 `E2E-TASK-DELETE-REESTIMATE-ADMIN: 目标前置` 的测试目标", object: "db.objective", operator: "absent", params: { titleFrom: "data.objectiveTitle" } },
      { source: { caseStepId: "Clean-12", method: "api" }, id: "ory.admin_identity.absent", title: "邮箱为 `orf-admin-delete-task-reestimate-e2e@orf.local` 的管理员登录身份 应不存在", object: "ory.identity", operator: "absent", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-13", method: "prisma" }, id: "db.admin_user.absent", title: "邮箱为 `orf-admin-delete-task-reestimate-e2e@orf.local` 的管理员用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.adminEmail" } },
    ],
  },
} satisfies StateCaseSpec<AdminDeleteTaskReestimateCaseData>;
