import { STATE_CASE_MODEL, type StateCaseSpec } from "../../../../_framework/types";
import type { MemberPeerReviewSubmitCaseData } from "./_support/member-peer-review-submit.context";

export const memberPeerReviewSubmitCase = {
  id: "target.member-peer-review-submit",
  title: "普通成员在已验收阶段可提交匿名互评",
  model: STATE_CASE_MODEL,
  tags: ["target", "loot", "peer-review", "member"],

  data: {
    adminEmail: "orf-admin-peer-review-e2e@orf.local",
    adminPassword: "OrfAdminPeerReviewE2E!2026",
    adminName: "ORF Admin Peer Review E2E",
    adminRole: "admin",
    adminStatus: "active",
    memberEmail: "orf-member-peer-review-e2e@orf.local",
    memberPassword: "OrfMemberPeerReviewE2E!2026",
    memberName: "ORF Member Peer Review E2E",
    memberRole: "member",
    memberStatus: "active",
    teammateEmail: "orf-teammate-peer-review-e2e@orf.local",
    teammatePassword: "OrfTeammatePeerReviewE2E!2026",
    teammateName: "ORF Teammate Peer Review E2E",
    teammateRole: "member",
    teammateStatus: "active",
    targetPrefix: "E2E-TARGET-MEMBER-PEER-REVIEW",
    target: {
      title: "E2E-TARGET-MEMBER-PEER-REVIEW",
      stage: "goalFrozen",
      flowStatus: "accepted",
      finalDueOffsetDays: 8,
    },
    metric: {
      title: "E2E-METRIC-MEMBER-PEER-REVIEW",
      difficulty: "进阶",
      score: 30,
      claim: "completed",
      finalEvidence: "E2E-MEMBER-PEER-REVIEW-EVIDENCE：https://example.test/member-peer-review",
      acceptedResult: "completed",
    },
    finalLoot: {
      body: "E2E-MEMBER-PEER-REVIEW-BODY：正式验收材料已通过。",
      selfTestReportBody: "E2E-MEMBER-PEER-REVIEW-SELF-TEST：互评前已完成验收自测。",
    },
    acceptanceResult: "completed",
    acceptanceReviewReason: "E2E-MEMBER-PEER-REVIEW-ACCEPT：管理员已确认验收通过。",
    peerReview: {
      memberPercent: 60,
      teammatePercent: 40,
      totalPercent: 100,
    },
  },

  B: {
    description: "基准状态",
    assertions: [
      { source: { caseStepId: "B-1", method: "api" }, id: "frontend.ready", title: "前端服务 应可用", object: "frontend.service", operator: "available" },
      { source: { caseStepId: "B-2", method: "api" }, id: "backend.ready", title: "后端服务 应可用", object: "api.health", operator: "ok" },
      { source: { caseStepId: "B-3", method: "prisma" }, id: "db.ready", title: "ORF 数据库 应可连接", object: "db", operator: "ready" },
      { source: { caseStepId: "B-4", method: "api" }, id: "local_settlement.ready", title: "匿名互评共享结算服务 应可用", object: "api.local_settlement", operator: "available" },
      { source: { caseStepId: "B-5", method: "api" }, id: "session.unauthenticated", title: "当前会话 应为 未登录", object: "auth.session", operator: "unauthenticated" },
      { source: { caseStepId: "B-6", method: "playwright" }, id: "storage.empty", title: "当前浏览器 应不保留本地登录态", object: "browser.auth_storage", operator: "empty" },
    ],
  },

  Setup: {
    description: "构造 S0",
    steps: [
      { source: { caseStepId: "Setup-1", method: "prisma" }, id: "db.objectives.delete_residue", title: "删除 本用例残留的目标标题前缀 `E2E-TARGET-MEMBER-PEER-REVIEW` 对应的目标及其派生数据", object: "db.objectives_by_prefix", operator: "delete", params: { prefixFrom: "data.targetPrefix" } },
      { source: { caseStepId: "Setup-2", method: "api" }, id: "ory.admin_identity.upsert", title: "准备邮箱为 `orf-admin-peer-review-e2e@orf.local`、使用固定测试密码的管理员登录身份", object: "ory.identity", operator: "upsert_password", params: { emailFrom: "data.adminEmail", nameFrom: "data.adminName", passwordFrom: "data.adminPassword", saveAs: "adminIdentity" } },
      { source: { caseStepId: "Setup-3", method: "prisma" }, id: "db.admin_user.upsert", title: "准备 角色为 `admin`、状态为 `active`、名称为 `ORF Admin Peer Review E2E` 的本用例管理员用户", object: "db.user", operator: "upsert", params: { emailFrom: "data.adminEmail", nameFrom: "data.adminName", roleFrom: "data.adminRole", statusFrom: "data.adminStatus", identityIdFrom: "runtime.adminIdentity.id", saveAs: "adminUser" } },
      { source: { caseStepId: "Setup-4", method: "api" }, id: "ory.member_identity.upsert", title: "准备邮箱为 `orf-member-peer-review-e2e@orf.local`、使用固定测试密码的普通成员登录身份", object: "ory.identity", operator: "upsert_password", params: { emailFrom: "data.memberEmail", nameFrom: "data.memberName", passwordFrom: "data.memberPassword", saveAs: "memberIdentity" } },
      { source: { caseStepId: "Setup-5", method: "prisma" }, id: "db.member_user.upsert", title: "准备 角色为 `member`、状态为 `active`、名称为 `ORF Member Peer Review E2E` 的本用例普通成员用户", object: "db.user", operator: "upsert", params: { emailFrom: "data.memberEmail", nameFrom: "data.memberName", roleFrom: "data.memberRole", statusFrom: "data.memberStatus", identityIdFrom: "runtime.memberIdentity.id", saveAs: "memberUser" } },
      { source: { caseStepId: "Setup-6", method: "api" }, id: "ory.teammate_identity.upsert", title: "准备邮箱为 `orf-teammate-peer-review-e2e@orf.local`、使用固定测试密码的队友普通成员登录身份", object: "ory.identity", operator: "upsert_password", params: { emailFrom: "data.teammateEmail", nameFrom: "data.teammateName", passwordFrom: "data.teammatePassword", saveAs: "teammateIdentity" } },
      { source: { caseStepId: "Setup-7", method: "prisma" }, id: "db.teammate_user.upsert", title: "准备 角色为 `member`、状态为 `active`、名称为 `ORF Teammate Peer Review E2E` 的本用例队友普通成员用户", object: "db.user", operator: "upsert", params: { emailFrom: "data.teammateEmail", nameFrom: "data.teammateName", roleFrom: "data.teammateRole", statusFrom: "data.teammateStatus", identityIdFrom: "runtime.teammateIdentity.id", saveAs: "teammateUser" } },
      { source: { caseStepId: "Setup-8", method: "prisma" }, id: "db.accepted_objective.prepare", title: "准备 标题为 `E2E-TARGET-MEMBER-PEER-REVIEW`、阶段为 `goalFrozen`、流转状态为 `accepted`、最终验收截止日为运行时当前日期后 `8` 天、冻结时间存在、战利品提交时间存在、验收通过时间存在、验收结果为 `completed`、当前挑战者包含本用例普通成员和本用例队友普通成员的目标", object: "db.accepted_objective_fixture", operator: "prepare", params: { adminUserFrom: "runtime.adminUser", memberUserFrom: "runtime.memberUser", teammateUserFrom: "runtime.teammateUser", targetFrom: "data.target", saveAs: "objective" } },
      { source: { caseStepId: "Setup-9", method: "prisma" }, id: "db.metric.prepare_accepted", title: "准备 归属于目标 `E2E-TARGET-MEMBER-PEER-REVIEW`、口径为 `E2E-METRIC-MEMBER-PEER-REVIEW`、等级积分等级为 `进阶`、等级积分为 `30`、验收结果为 `completed` 的指标", object: "db.metric", operator: "prepare_accepted", params: { targetFrom: "data.target", metricFrom: "data.metric", memberUserFrom: "runtime.memberUser", saveAs: "metric" } },
      { source: { caseStepId: "Setup-10", method: "prisma" }, id: "db.objective_loot.prepare_final", title: "准备 归属于目标 `E2E-TARGET-MEMBER-PEER-REVIEW`、提交人为本用例普通成员、完成说明为 `E2E-MEMBER-PEER-REVIEW-BODY：正式验收材料已通过。`、自测报告为 `E2E-MEMBER-PEER-REVIEW-SELF-TEST：互评前已完成验收自测。`、指标 `E2E-METRIC-MEMBER-PEER-REVIEW` 的完成主张为 `completed`、证据为 `E2E-MEMBER-PEER-REVIEW-EVIDENCE：https://example.test/member-peer-review` 的战利品正式提交记录", object: "db.objective_loot", operator: "prepare_final", params: { targetFrom: "data.target", metricFrom: "data.metric", finalLootFrom: "data.finalLoot", memberUserFrom: "runtime.memberUser", saveAs: "objectiveLoot" } },
      { source: { caseStepId: "Setup-11", method: "prisma" }, id: "db.acceptance_review.prepare_completed", title: "准备 归属于目标 `E2E-TARGET-MEMBER-PEER-REVIEW`、审核人为本用例管理员、验收结果为 `completed`、验收说明为 `E2E-MEMBER-PEER-REVIEW-ACCEPT：管理员已确认验收通过。` 的验收记录", object: "db.objective_acceptance_review", operator: "prepare_completed", params: { targetFrom: "data.target", metricFrom: "data.metric", acceptanceResultFrom: "data.acceptanceResult", reasonFrom: "data.acceptanceReviewReason", adminUserFrom: "runtime.adminUser" } },
      { source: { caseStepId: "Setup-12", method: "prisma" }, id: "db.settlement_events.delete_final", title: "确保 归属于目标 `E2E-TARGET-MEMBER-PEER-REVIEW` 的最终结算事件不存在", object: "db.objective_settlement_events", operator: "delete_final_completion", params: { targetFrom: "data.target" } },
      { source: { caseStepId: "Setup-13", method: "playwright" }, id: "auth.login.member", title: "使用 本用例普通成员账号 登录 ORF", object: "page.auth", operator: "login", params: { emailFrom: "data.memberEmail", passwordFrom: "data.memberPassword" } },
      { source: { caseStepId: "Setup-14", method: "api" }, id: "api.peer_review_draft.ensure_absent", title: "确保 本用例普通成员对目标 `E2E-TARGET-MEMBER-PEER-REVIEW` 的匿名互评草稿不存在", object: "api.local_settlement", operator: "ensure_my_draft_absent", params: { targetFrom: "data.target" } },
    ],
  },

  S0: {
    description: "Action 前状态",
    assertions: [
      { source: { caseStepId: "S0-1", method: "api" }, id: "session.authenticated", title: "当前会话 应为 已登录", object: "auth.session", operator: "authenticated" },
      { source: { caseStepId: "S0-2", method: "api" }, id: "session.email", title: "当前会话用户邮箱 应为 `orf-member-peer-review-e2e@orf.local`", object: "auth.session.user_email", operator: "equals", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "S0-3", method: "api" }, id: "session.role", title: "当前会话用户角色 应为 `member`", object: "auth.session.user_role", operator: "equals", params: { roleFrom: "data.memberRole" } },
      { source: { caseStepId: "S0-4", method: "api" }, id: "session.name", title: "当前会话用户名称 应为 `ORF Member Peer Review E2E`", object: "auth.session.user_name", operator: "equals", params: { nameFrom: "data.memberName" } },
      { source: { caseStepId: "S0-5", method: "prisma" }, id: "db.accepted_objective.exists", title: "应存在 标题为 `E2E-TARGET-MEMBER-PEER-REVIEW`、阶段为 `goalFrozen`、流转状态为 `accepted` 的目标", object: "db.accepted_objective_fixture", operator: "exists", params: { targetFrom: "data.target" } },
      { source: { caseStepId: "S0-6", method: "prisma" }, id: "db.accepted_objective.challenger_member", title: "目标 `E2E-TARGET-MEMBER-PEER-REVIEW` 的当前挑战者 应包含本用例普通成员", object: "db.accepted_objective_fixture", operator: "challenger_contains", params: { targetFrom: "data.target", memberUserFrom: "runtime.memberUser" } },
      { source: { caseStepId: "S0-7", method: "prisma" }, id: "db.accepted_objective.challenger_teammate", title: "目标 `E2E-TARGET-MEMBER-PEER-REVIEW` 的当前挑战者 应包含本用例队友普通成员", object: "db.accepted_objective_fixture", operator: "challenger_contains", params: { targetFrom: "data.target", memberUserFrom: "runtime.teammateUser" } },
      { source: { caseStepId: "S0-8", method: "prisma" }, id: "db.accepted_objective.accepted_at", title: "目标 `E2E-TARGET-MEMBER-PEER-REVIEW` 的验收通过时间 应存在", object: "db.accepted_objective_fixture", operator: "accepted_at_exists", params: { targetFrom: "data.target" } },
      { source: { caseStepId: "S0-9", method: "prisma" }, id: "db.accepted_objective.accepted_result", title: "目标 `E2E-TARGET-MEMBER-PEER-REVIEW` 的验收结果 应为 `completed`", object: "db.accepted_objective_fixture", operator: "accepted_result", params: { targetFrom: "data.target", acceptanceResultFrom: "data.acceptanceResult" } },
      { source: { caseStepId: "S0-10", method: "prisma" }, id: "db.metric.exists_accepted", title: "应存在 归属于目标 `E2E-TARGET-MEMBER-PEER-REVIEW`、口径为 `E2E-METRIC-MEMBER-PEER-REVIEW`、验收结果为 `completed` 的指标", object: "db.metric", operator: "exists_accepted", params: { targetFrom: "data.target", titleFrom: "data.metric.title", difficultyFrom: "data.metric.difficulty", scoreFrom: "data.metric.score", acceptedResultFrom: "data.metric.acceptedResult" } },
      { source: { caseStepId: "S0-11", method: "prisma" }, id: "db.objective_loot.exists", title: "应存在 归属于目标 `E2E-TARGET-MEMBER-PEER-REVIEW`、提交人为本用例普通成员、完成说明为 `E2E-MEMBER-PEER-REVIEW-BODY：正式验收材料已通过。` 的战利品正式提交记录", object: "db.objective_loot", operator: "exists", params: { targetFrom: "data.target", finalLootFrom: "data.finalLoot", memberUserFrom: "runtime.memberUser" } },
      { source: { caseStepId: "S0-12", method: "prisma" }, id: "db.acceptance_review.exists", title: "应存在 归属于目标 `E2E-TARGET-MEMBER-PEER-REVIEW`、审核人为本用例管理员、验收结果为 `completed` 的验收记录", object: "db.objective_acceptance_review", operator: "exists", params: { targetFrom: "data.target", metricFrom: "data.metric", acceptanceResultFrom: "data.acceptanceResult", adminUserFrom: "runtime.adminUser" } },
      { source: { caseStepId: "S0-13", method: "prisma" }, id: "db.settlement_events.final_count_zero", title: "目标 `E2E-TARGET-MEMBER-PEER-REVIEW` 的最终结算事件数量 应为 `0`", object: "db.objective_settlement_events", operator: "final_completion_count", params: { targetFrom: "data.target", count: 0 } },
      { source: { caseStepId: "S0-14", method: "api" }, id: "api.peer_review.empty", title: "当前普通成员对目标 `E2E-TARGET-MEMBER-PEER-REVIEW` 的匿名互评记录 应为空", object: "api.local_settlement", operator: "my_review_empty", params: { targetFrom: "data.target" } },
      { source: { caseStepId: "S0-15", method: "api" }, id: "api.peer_review_draft.empty", title: "当前普通成员对目标 `E2E-TARGET-MEMBER-PEER-REVIEW` 的匿名互评草稿 应为空", object: "api.local_settlement", operator: "my_draft_empty", params: { targetFrom: "data.target" } },
    ],
  },

  Action: {
    description: "被测业务动作",
    steps: [
      { source: { caseStepId: "Action-1", method: "playwright" }, id: "member.open_my_challenges", title: "普通成员打开 我的挑战", object: "page.challenge", operator: "open_my_challenges" },
      { source: { caseStepId: "Action-2", method: "playwright" }, id: "objective.visible", title: "我的挑战列表 应显示目标 `E2E-TARGET-MEMBER-PEER-REVIEW`", object: "page.challenge_objectives", operator: "visible_title", params: { titleFrom: "data.target.title" } },
      { source: { caseStepId: "Action-3", method: "playwright" }, id: "objective.status.accepted", title: "目标 `E2E-TARGET-MEMBER-PEER-REVIEW` 的状态 应显示为 已验收", object: "page.challenge_objective", operator: "status_visible", params: { titleFrom: "data.target.title", statusLabel: "已验收" } },
      { source: { caseStepId: "Action-4", method: "playwright" }, id: "objective.peer_review_action.visible", title: "目标 `E2E-TARGET-MEMBER-PEER-REVIEW` 的 \"提交匿名互评\" 操作 应可见", object: "page.challenge_objective", operator: "action_visible", params: { titleFrom: "data.target.title", actionLabel: "提交匿名互评" } },
      { source: { caseStepId: "Action-5", method: "playwright" }, id: "objective.peer_review_action.enabled", title: "目标 `E2E-TARGET-MEMBER-PEER-REVIEW` 的 \"提交匿名互评\" 操作 应可点击", object: "page.challenge_objective", operator: "action_enabled", params: { titleFrom: "data.target.title", actionLabel: "提交匿名互评" } },
      { source: { caseStepId: "Action-6", method: "playwright" }, id: "peer_review.open", title: "点击目标 `E2E-TARGET-MEMBER-PEER-REVIEW` 的 \"提交匿名互评\" 操作", object: "page.peer_review", operator: "open_from_objective", params: { targetTitleFrom: "data.target.title" } },
      { source: { caseStepId: "Action-7", method: "playwright" }, id: "peer_review.page.loaded", title: "等待 提交匿名互评页面加载完成", object: "page.peer_review", operator: "loaded", params: { targetTitleFrom: "data.target.title" } },
      { source: { caseStepId: "Action-8", method: "playwright" }, id: "peer_review.target.visible", title: "页面 应显示目标 `E2E-TARGET-MEMBER-PEER-REVIEW`", object: "page.peer_review", operator: "target_visible", params: { targetTitleFrom: "data.target.title" } },
      { source: { caseStepId: "Action-9", method: "playwright" }, id: "peer_review.title.visible", title: "页面 应显示 `提交匿名互评`", object: "page.peer_review", operator: "title_visible", params: { title: "提交匿名互评" } },
      { source: { caseStepId: "Action-10", method: "playwright" }, id: "peer_review.notice.empty", title: "页面 应显示 `暂未找到你对这个目标提交过的匿名互评；挑战者页面只显示自己的评价状态。`", object: "page.peer_review", operator: "notice_visible", params: { notice: "暂未找到你对这个目标提交过的匿名互评；挑战者页面只显示自己的评价状态。" } },
      { source: { caseStepId: "Action-11", method: "playwright" }, id: "peer_review.matrix.visible", title: "页面 应显示 `指标贡献分配`", object: "page.peer_review", operator: "matrix_visible", params: { title: "指标贡献分配" } },
      { source: { caseStepId: "Action-12", method: "playwright" }, id: "peer_review.metric.visible", title: "页面 应显示指标 `E2E-METRIC-MEMBER-PEER-REVIEW`", object: "page.peer_review", operator: "metric_visible", params: { metricTitleFrom: "data.metric.title" } },
      { source: { caseStepId: "Action-13", method: "playwright" }, id: "peer_review.member_percent.fill", title: "在指标 `E2E-METRIC-MEMBER-PEER-REVIEW`、成员 `ORF Member Peer Review E2E` 的贡献百分比输入框中填写 `60`", object: "page.peer_review", operator: "fill_metric_percent", params: { metricTitleFrom: "data.metric.title", memberNameFrom: "data.memberName", percentFrom: "data.peerReview.memberPercent" } },
      { source: { caseStepId: "Action-14", method: "playwright" }, id: "peer_review.teammate_percent.fill", title: "在指标 `E2E-METRIC-MEMBER-PEER-REVIEW`、成员 `ORF Teammate Peer Review E2E` 的贡献百分比输入框中填写 `40`", object: "page.peer_review", operator: "fill_metric_percent", params: { metricTitleFrom: "data.metric.title", memberNameFrom: "data.teammateName", percentFrom: "data.peerReview.teammatePercent" } },
      { source: { caseStepId: "Action-15", method: "playwright" }, id: "peer_review.row_total.visible", title: "指标 `E2E-METRIC-MEMBER-PEER-REVIEW` 的行合计 应显示为 `100%`", object: "page.peer_review", operator: "row_total_visible", params: { metricTitleFrom: "data.metric.title", totalPercentFrom: "data.peerReview.totalPercent" } },
      { source: { caseStepId: "Action-16", method: "playwright" }, id: "peer_review.submit.enabled", title: "\"提交匿名互评\" 操作 应可点击", object: "page.peer_review", operator: "submit_enabled", params: { label: "提交匿名互评" } },
      { source: { caseStepId: "Action-17", method: "playwright" }, id: "peer_review.submit", title: "点击 \"提交匿名互评\" 操作", object: "page.peer_review", operator: "submit" },
      { source: { caseStepId: "Action-18", method: "api" }, id: "api.peer_review.submit_result", title: "匿名互评提交结果 应成功，并记录 本用例普通成员匿名互评", object: "api.local_settlement", operator: "submit_result_success", params: { targetFrom: "data.target", saveAs: "peerReview" } },
    ],
  },

  S1: {
    description: "Action 后状态",
    assertions: [
      { source: { caseStepId: "S1-1", method: "playwright" }, id: "toast.peer_review_submitted", title: "页面 应提示 匿名互评已通过 ORF 提交到共享结算服务", object: "page.challenge_toast", operator: "peer_review_submitted" },
      { source: { caseStepId: "S1-2", method: "playwright" }, id: "challenge.page.url", title: "页面 应进入 我的挑战", object: "page.challenge", operator: "url" },
      { source: { caseStepId: "S1-3", method: "playwright" }, id: "scope.mine.selected", title: "\"我的挑战\" 视图 应处于选中状态", object: "page.challenge_scope", operator: "selected", params: { label: "我的挑战" } },
      { source: { caseStepId: "S1-4", method: "playwright" }, id: "objective.visible", title: "我的挑战列表 应显示目标 `E2E-TARGET-MEMBER-PEER-REVIEW`", object: "page.challenge_objectives", operator: "visible_title", params: { titleFrom: "data.target.title" } },
      { source: { caseStepId: "S1-5", method: "playwright" }, id: "objective.status.accepted", title: "目标 `E2E-TARGET-MEMBER-PEER-REVIEW` 的状态 应显示为 已验收", object: "page.challenge_objective", operator: "status_visible", params: { titleFrom: "data.target.title", statusLabel: "已验收" } },
      { source: { caseStepId: "S1-6", method: "playwright" }, id: "objective.peer_review_action.update_visible", title: "目标 `E2E-TARGET-MEMBER-PEER-REVIEW` 的 \"更新匿名互评\" 操作 应可见", object: "page.challenge_objective", operator: "action_visible", params: { titleFrom: "data.target.title", actionLabel: "更新匿名互评" } },
      { source: { caseStepId: "S1-7", method: "api" }, id: "api.peer_review.contains_target", title: "当前普通成员匿名互评数据 应包含目标 `E2E-TARGET-MEMBER-PEER-REVIEW` 的最新互评记录", object: "api.local_settlement", operator: "latest_review_contains_target", params: { targetFrom: "data.target", saveAs: "peerReview" } },
      { source: { caseStepId: "S1-8", method: "api" }, id: "api.peer_review.scored", title: "本用例普通成员匿名互评 的状态 应为 已评分", object: "api.peer_review", operator: "scored", params: { reviewFrom: "runtime.peerReview" } },
      { source: { caseStepId: "S1-9", method: "api" }, id: "api.peer_review.reviewer", title: "本用例普通成员匿名互评 的评价人 应为 `ORF Member Peer Review E2E`", object: "api.peer_review", operator: "reviewer", params: { reviewFrom: "runtime.peerReview", memberUserFrom: "runtime.memberUser" } },
      { source: { caseStepId: "S1-10", method: "api" }, id: "api.peer_review.submitted_at", title: "本用例普通成员匿名互评 的提交时间 应不为空", object: "api.peer_review", operator: "submitted_at_exists", params: { reviewFrom: "runtime.peerReview" } },
      { source: { caseStepId: "S1-11", method: "api" }, id: "api.peer_review.contains_metric", title: "本用例普通成员匿名互评 应包含指标 `E2E-METRIC-MEMBER-PEER-REVIEW`", object: "api.peer_review", operator: "contains_metric", params: { reviewFrom: "runtime.peerReview", metricFrom: "data.metric" } },
      { source: { caseStepId: "S1-12", method: "api" }, id: "api.peer_review.member_percent", title: "本用例普通成员匿名互评中指标 `E2E-METRIC-MEMBER-PEER-REVIEW` 对成员 `ORF Member Peer Review E2E` 的贡献百分比 应为 `60`", object: "api.peer_review", operator: "metric_allocation_percent", params: { reviewFrom: "runtime.peerReview", metricFrom: "data.metric", memberUserFrom: "runtime.memberUser", percentFrom: "data.peerReview.memberPercent" } },
      { source: { caseStepId: "S1-13", method: "api" }, id: "api.peer_review.teammate_percent", title: "本用例普通成员匿名互评中指标 `E2E-METRIC-MEMBER-PEER-REVIEW` 对成员 `ORF Teammate Peer Review E2E` 的贡献百分比 应为 `40`", object: "api.peer_review", operator: "metric_allocation_percent", params: { reviewFrom: "runtime.peerReview", metricFrom: "data.metric", memberUserFrom: "runtime.teammateUser", percentFrom: "data.peerReview.teammatePercent" } },
      { source: { caseStepId: "S1-14", method: "api" }, id: "api.peer_review.total_percent", title: "本用例普通成员匿名互评中指标 `E2E-METRIC-MEMBER-PEER-REVIEW` 的贡献百分比合计 应为 `100`", object: "api.peer_review", operator: "metric_allocation_total", params: { reviewFrom: "runtime.peerReview", metricFrom: "data.metric", totalPercentFrom: "data.peerReview.totalPercent" } },
      { source: { caseStepId: "S1-15", method: "prisma" }, id: "db.accepted_objective.exists_after_submit", title: "标题为 `E2E-TARGET-MEMBER-PEER-REVIEW` 的目标阶段 应为 `goalFrozen`，流转状态 应为 `accepted`", object: "db.accepted_objective_fixture", operator: "exists", params: { targetFrom: "data.target" } },
      { source: { caseStepId: "S1-16", method: "prisma" }, id: "db.accepted_objective.accepted_result_still", title: "目标 `E2E-TARGET-MEMBER-PEER-REVIEW` 的验收结果 应保持 `completed`", object: "db.accepted_objective_fixture", operator: "accepted_result", params: { targetFrom: "data.target", acceptanceResultFrom: "data.acceptanceResult" } },
      { source: { caseStepId: "S1-17", method: "prisma" }, id: "db.accepted_objective.challenger_member_still", title: "目标 `E2E-TARGET-MEMBER-PEER-REVIEW` 的当前挑战者 应仍包含本用例普通成员", object: "db.accepted_objective_fixture", operator: "challenger_contains", params: { targetFrom: "data.target", memberUserFrom: "runtime.memberUser" } },
      { source: { caseStepId: "S1-18", method: "prisma" }, id: "db.accepted_objective.challenger_teammate_still", title: "目标 `E2E-TARGET-MEMBER-PEER-REVIEW` 的当前挑战者 应仍包含本用例队友普通成员", object: "db.accepted_objective_fixture", operator: "challenger_contains", params: { targetFrom: "data.target", memberUserFrom: "runtime.teammateUser" } },
      { source: { caseStepId: "S1-19", method: "prisma" }, id: "db.settlement_events.final_count_zero", title: "目标 `E2E-TARGET-MEMBER-PEER-REVIEW` 的最终结算事件数量 应为 `0`", object: "db.objective_settlement_events", operator: "final_completion_count", params: { targetFrom: "data.target", count: 0 } },
      { source: { caseStepId: "S1-20", method: "prisma" }, id: "db.acceptance_review.exists_after_submit", title: "应存在 归属于目标 `E2E-TARGET-MEMBER-PEER-REVIEW`、审核人为本用例管理员、验收结果为 `completed` 的验收记录", object: "db.objective_acceptance_review", operator: "exists", params: { targetFrom: "data.target", metricFrom: "data.metric", acceptanceResultFrom: "data.acceptanceResult", adminUserFrom: "runtime.adminUser" } },
    ],
  },

  Clean: {
    description: "恢复 B",
    steps: [
      { source: { caseStepId: "Clean-1", method: "prisma" }, id: "db.objectives.delete_created", title: "删除 本用例创建的目标标题前缀 `E2E-TARGET-MEMBER-PEER-REVIEW` 对应的目标及其派生数据", object: "db.objectives_by_prefix", operator: "delete", params: { prefixFrom: "data.targetPrefix" } },
      { source: { caseStepId: "Clean-2", method: "api" }, id: "auth.logout", title: "注销当前普通成员登录会话", object: "auth", operator: "logout" },
      { source: { caseStepId: "Clean-3", method: "playwright" }, id: "browser.clear", title: "移除当前浏览器中的残留登录态", object: "browser", operator: "clear_state" },
      { source: { caseStepId: "Clean-4", method: "api" }, id: "ory.admin_identity.delete", title: "删除 本用例管理员登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-5", method: "api" }, id: "ory.member_identity.delete", title: "删除 本用例普通成员登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-6", method: "api" }, id: "ory.teammate_identity.delete", title: "删除 本用例队友普通成员登录身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.teammateEmail" } },
      { source: { caseStepId: "Clean-7", method: "prisma" }, id: "db.admin_user.delete", title: "删除 本用例管理员用户", object: "db.user", operator: "delete", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-8", method: "prisma" }, id: "db.member_user.delete", title: "删除 本用例普通成员用户", object: "db.user", operator: "delete", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-9", method: "prisma" }, id: "db.teammate_user.delete", title: "删除 本用例队友普通成员用户", object: "db.user", operator: "delete", params: { emailFrom: "data.teammateEmail" } },
      { source: { caseStepId: "Clean-10", method: "prisma" }, id: "db.objectives.absent", title: "应不存在 标题前缀为 `E2E-TARGET-MEMBER-PEER-REVIEW` 的目标", object: "db.objectives_by_prefix", operator: "absent", params: { prefixFrom: "data.targetPrefix" } },
      { source: { caseStepId: "Clean-11", method: "prisma" }, id: "db.metric.absent", title: "应不存在 口径为 `E2E-METRIC-MEMBER-PEER-REVIEW` 的指标", object: "db.metric", operator: "absent", params: { titleFrom: "data.metric.title" } },
      { source: { caseStepId: "Clean-12", method: "api" }, id: "ory.admin_identity.absent", title: "邮箱为 `orf-admin-peer-review-e2e@orf.local` 的管理员登录身份 应不存在", object: "ory.identity", operator: "absent", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-13", method: "api" }, id: "ory.member_identity.absent", title: "邮箱为 `orf-member-peer-review-e2e@orf.local` 的普通成员登录身份 应不存在", object: "ory.identity", operator: "absent", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-14", method: "api" }, id: "ory.teammate_identity.absent", title: "邮箱为 `orf-teammate-peer-review-e2e@orf.local` 的队友普通成员登录身份 应不存在", object: "ory.identity", operator: "absent", params: { emailFrom: "data.teammateEmail" } },
      { source: { caseStepId: "Clean-15", method: "prisma" }, id: "db.admin_user.absent", title: "邮箱为 `orf-admin-peer-review-e2e@orf.local` 的管理员用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-16", method: "prisma" }, id: "db.member_user.absent", title: "邮箱为 `orf-member-peer-review-e2e@orf.local` 的普通成员用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.memberEmail" } },
      { source: { caseStepId: "Clean-17", method: "prisma" }, id: "db.teammate_user.absent", title: "邮箱为 `orf-teammate-peer-review-e2e@orf.local` 的队友普通成员用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.teammateEmail" } },
      { source: { caseStepId: "Clean-18", method: "api" }, id: "session.unauthenticated", title: "当前会话 应为 未登录", object: "auth.session", operator: "unauthenticated" },
    ],
  },
} satisfies StateCaseSpec<MemberPeerReviewSubmitCaseData>;
