import { STATE_CASE_MODEL, type StateCaseSpec } from "../../_framework/types";
import type { MemberScoreStatisticsCaseData } from "./_support/member-score-statistics.context";

export const memberScoreStatisticsCase = {
  id: "statistics.member-score",
  title: "成员分数统计",
  model: STATE_CASE_MODEL,
  tags: ["statistics", "score", "admin", "happy-path"],

  data: {
    adminEmail: "orf-admin-score-stats-e2e@orf.local",
    adminPassword: "OrfAdminScoreStatsE2E!2026",
    adminName: "ORF Admin Score Stats E2E",
    adminRole: "admin",
    firstMemberEmail: "orf-score-stats-member-one-e2e@orf.local",
    firstMemberPassword: "OrfScoreStatsMemberOneE2E!2026",
    firstMemberName: "ORF Score Stats Member One E2E",
    firstMemberRole: "member",
    firstMemberPoints: 70,
    secondMemberEmail: "orf-score-stats-member-two-e2e@orf.local",
    secondMemberPassword: "OrfScoreStatsMemberTwoE2E!2026",
    secondMemberName: "ORF Score Stats Member Two E2E",
    secondMemberRole: "member",
    secondMemberPoints: 30,
    objectiveId: "obj-testd-member-score-statistics",
    objectiveTitle: "E2E-MEMBER-SCORE-STATS: 目标前置",
    reason: "E2E-SCORE-STATS: 成员分数统计",
  },

  B: {
    description: "系统服务可用，浏览器处于未登录基准状态",
    assertions: [
      { source: { caseStepId: "B-1", method: "api" }, id: "frontend.ready", title: "前端服务 应可用", object: "frontend.service", operator: "available" },
      { source: { caseStepId: "B-2", method: "api" }, id: "backend.ready", title: "后端服务 应可用", object: "api.health", operator: "ok" },
      { source: { caseStepId: "B-3", method: "api" }, id: "frontend.login_entry.accessible", title: "前端登录页入口 应可访问", object: "frontend.login_entry", operator: "accessible" },
      { source: { caseStepId: "B-4", method: "api" }, id: "session.endpoint.accessible", title: "当前会话查询接口 应可访问", object: "auth.session", operator: "accessible" },
      { source: { caseStepId: "B-5", method: "prisma" }, id: "db.ready", title: "ORF 数据库 应可连接", object: "db", operator: "ready" },
      { source: { caseStepId: "B-6", method: "prisma" }, id: "db.schema.current", title: "ORF 数据库 schema 应为 当前测试版本", object: "db.schema", operator: "current" },
      { source: { caseStepId: "B-7", method: "api" }, id: "ory.admin_public.ready", title: "Ory/Kratos Admin/Public API 应可访问", object: "ory.admin_public", operator: "ready" },
      { source: { caseStepId: "B-8", method: "api" }, id: "session.unauthenticated", title: "当前会话 应为 未登录", object: "auth.session", operator: "unauthenticated" },
      { source: { caseStepId: "B-9", method: "playwright" }, id: "cookie.absent", title: "当前浏览器 应不存在 Ory session cookie", object: "browser.cookie", operator: "absent" },
      { source: { caseStepId: "B-10", method: "playwright" }, id: "storage.empty", title: "当前浏览器 storage 应不包含 登录态", object: "browser.auth_storage", operator: "empty" },
    ],
  },

  Setup: {
    description: "准备管理员、两个普通成员、本用例独占 settled 目标和积分流水，登录管理员",
    steps: [
      { source: { caseStepId: "Setup-1", method: "prisma" }, id: "db.score_ledger.delete_residue", title: "删除可能残留的测试积分流水", object: "db.score_ledger", operator: "delete", params: { reasonFrom: "data.reason" } },
      { source: { caseStepId: "Setup-2", method: "prisma" }, id: "db.objective.delete_residue", title: "删除可能残留的本用例目标及其派生数据", object: "db.objective", operator: "delete_by_title", params: { titleFrom: "data.objectiveTitle" } },
      { source: { caseStepId: "Setup-3", method: "api" }, id: "ory.admin_identity.upsert", title: "准备管理员登录身份", object: "ory.identity", operator: "upsert_password", params: { emailFrom: "data.adminEmail", nameFrom: "data.adminName", passwordFrom: "data.adminPassword", saveAs: "adminIdentity" } },
      { source: { caseStepId: "Setup-4", method: "prisma" }, id: "db.admin.upsert", title: "准备管理员用户和默认团队成员关系", object: "db.user", operator: "upsert", params: { emailFrom: "data.adminEmail", nameFrom: "data.adminName", roleFrom: "data.adminRole", status: "active", identityIdFrom: "runtime.adminIdentity.id", saveAs: "adminUser" } },
      { source: { caseStepId: "Setup-5", method: "api" }, id: "ory.first_member_identity.upsert", title: "准备第一个普通成员登录身份", object: "ory.identity", operator: "upsert_password", params: { emailFrom: "data.firstMemberEmail", nameFrom: "data.firstMemberName", passwordFrom: "data.firstMemberPassword", saveAs: "firstMemberIdentity" } },
      { source: { caseStepId: "Setup-6", method: "prisma" }, id: "db.first_member.upsert", title: "准备第一个普通成员用户和默认团队成员关系", object: "db.user", operator: "upsert", params: { emailFrom: "data.firstMemberEmail", nameFrom: "data.firstMemberName", roleFrom: "data.firstMemberRole", status: "active", identityIdFrom: "runtime.firstMemberIdentity.id", saveAs: "firstMemberUser" } },
      { source: { caseStepId: "Setup-7", method: "api" }, id: "ory.second_member_identity.upsert", title: "准备第二个普通成员登录身份", object: "ory.identity", operator: "upsert_password", params: { emailFrom: "data.secondMemberEmail", nameFrom: "data.secondMemberName", passwordFrom: "data.secondMemberPassword", saveAs: "secondMemberIdentity" } },
      { source: { caseStepId: "Setup-8", method: "prisma" }, id: "db.second_member.upsert", title: "准备第二个普通成员用户和默认团队成员关系", object: "db.user", operator: "upsert", params: { emailFrom: "data.secondMemberEmail", nameFrom: "data.secondMemberName", roleFrom: "data.secondMemberRole", status: "active", identityIdFrom: "runtime.secondMemberIdentity.id", saveAs: "secondMemberUser" } },
      {
        source: { caseStepId: "Setup-9", method: "prisma" },
        id: "db.objective.upsert_score_statistics_target",
        title: "创建本用例独占目标",
        object: "db.objective",
        operator: "upsert",
        params: { idFrom: "data.objectiveId", titleFrom: "data.objectiveTitle", teamIdFrom: "runtime.adminUser.teamId", stage: "goalFrozen", flowStatus: "settled", status: "Draft", saveAs: "fixtureObjective" },
      },
      { source: { caseStepId: "Setup-10", method: "prisma" }, id: "db.score_statistics_target.from_objective", title: "记录本用例独占目标为 runtime.scoreStatisticsTarget", object: "db.score_statistics_target", operator: "from_objective", params: { objectiveIdFrom: "runtime.fixtureObjective.id", saveAs: "scoreStatisticsTarget" } },
      {
        source: { caseStepId: "Setup-11", method: "prisma" },
        id: "db.score_statistics_target.prepare",
        title: "设置本用例目标为 settled，挑战者包含两个普通成员，目标结算总积分为 100",
        object: "db.score_statistics_target",
        operator: "prepare",
        params: { targetFrom: "runtime.scoreStatisticsTarget", firstMemberNameFrom: "data.firstMemberName", secondMemberNameFrom: "data.secondMemberName", firstPointsFrom: "data.firstMemberPoints", secondPointsFrom: "data.secondMemberPoints" },
      },
      {
        source: { caseStepId: "Setup-12", method: "prisma" },
        id: "db.score_ledger.create",
        title: "创建两个普通成员对本用例目标的测试积分流水",
        object: "db.score_ledger",
        operator: "create",
        params: {
          targetFrom: "runtime.scoreStatisticsTarget",
          firstUserIdFrom: "runtime.firstMemberUser.userId",
          firstMemberNameFrom: "data.firstMemberName",
          firstPointsFrom: "data.firstMemberPoints",
          secondUserIdFrom: "runtime.secondMemberUser.userId",
          secondMemberNameFrom: "data.secondMemberName",
          secondPointsFrom: "data.secondMemberPoints",
          reasonFrom: "data.reason",
        },
      },
      { source: { caseStepId: "Setup-13", method: "api" }, id: "ory.admin_sessions.revoke", title: "撤销管理员登录身份可能残留的 Ory session", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Setup-14", method: "api" }, id: "ory.first_member_sessions.revoke", title: "撤销第一个普通成员登录身份可能残留的 Ory session", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.firstMemberEmail" } },
      { source: { caseStepId: "Setup-15", method: "api" }, id: "ory.second_member_sessions.revoke", title: "撤销第二个普通成员登录身份可能残留的 Ory session", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.secondMemberEmail" } },
      { source: { caseStepId: "Setup-16", method: "playwright" }, id: "browser.clear", title: "清空当前浏览器上下文的 cookies/localStorage/sessionStorage", object: "browser", operator: "clear_state" },
      { source: { caseStepId: "Setup-17", method: "playwright" }, id: "page.goto.auth", title: "打开 登录页", object: "page", operator: "goto", params: { path: "/auth" } },
      { source: { caseStepId: "Setup-18", method: "playwright" }, id: "fill.email", title: "在邮箱输入框输入管理员测试邮箱", object: "page", operator: "fill", params: { label: "Email", valueFrom: "data.adminEmail" } },
      { source: { caseStepId: "Setup-19", method: "playwright" }, id: "fill.password", title: "在密码输入框输入管理员测试密码", object: "page", operator: "fill", params: { label: "Password", exact: true, valueFrom: "data.adminPassword" } },
      { source: { caseStepId: "Setup-20", method: "playwright" }, id: "click.sign_in", title: '点击 "Sign In" 登录操作', object: "page", operator: "click", params: { role: "button", name: "Sign In" } },
      { source: { caseStepId: "Setup-21", method: "api" }, id: "session.admin.authenticated", title: "当前会话 应为 管理员已登录", object: "auth.session", operator: "authenticated", params: { emailFrom: "data.adminEmail", roleFrom: "data.adminRole", status: "active" } },
    ],
  },

  S0: {
    description: "管理员已登录，目标已结算且两个成员积分流水存在",
    assertions: [
      { source: { caseStepId: "S0-1", method: "api" }, id: "session.admin.authenticated", title: "当前会话 应为 管理员已登录", object: "auth.session", operator: "authenticated", params: { emailFrom: "data.adminEmail", roleFrom: "data.adminRole", status: "active" } },
      { source: { caseStepId: "S0-2", method: "prisma" }, id: "db.score_statistics_target.settled", title: "本用例目标 应为 settled", object: "db.score_statistics_target", operator: "settled", params: { targetFrom: "runtime.scoreStatisticsTarget" } },
      { source: { caseStepId: "S0-3", method: "prisma" }, id: "db.score_ledger.first.present", title: "第一个普通成员积分流水存在", object: "db.score_ledger", operator: "present", params: { targetFrom: "runtime.scoreStatisticsTarget", memberNameFrom: "data.firstMemberName", pointsFrom: "data.firstMemberPoints" } },
      { source: { caseStepId: "S0-4", method: "prisma" }, id: "db.score_ledger.second.present", title: "第二个普通成员积分流水存在", object: "db.score_ledger", operator: "present", params: { targetFrom: "runtime.scoreStatisticsTarget", memberNameFrom: "data.secondMemberName", pointsFrom: "data.secondMemberPoints" } },
    ],
  },

  Action: {
    description: "管理员打开统计页面查看成员分数",
    steps: [
      { source: { caseStepId: "Action-1", method: "playwright" }, id: "page.goto.reports", title: "打开 统计页面", object: "page", operator: "goto", params: { path: "/reports" } },
      { source: { caseStepId: "Action-2", method: "playwright" }, id: "click.all_time", title: '点击 "全部时间" 时间范围操作', object: "page", operator: "click", params: { role: "button", name: "全部时间" } },
    ],
  },

  S1: {
    description: "统计页面展示两个成员的积分，数据库积分流水保持一致",
    assertions: [
      { source: { caseStepId: "S1-1", method: "playwright" }, id: "url.reports", title: "当前页面 应为 统计页面", object: "page.url", operator: "match", params: { pattern: "/reports$" } },
      { source: { caseStepId: "S1-2", method: "playwright" }, id: "page.score_statistics.first.visible", title: "成员积分排行榜 应显示第一个普通成员的积分汇总", object: "page.score_statistics", operator: "visible", params: { targetFrom: "runtime.scoreStatisticsTarget", memberNameFrom: "data.firstMemberName" } },
      { source: { caseStepId: "S1-3", method: "playwright" }, id: "page.score_statistics.second.visible", title: "成员积分排行榜 应显示第二个普通成员的积分汇总", object: "page.score_statistics", operator: "visible", params: { targetFrom: "runtime.scoreStatisticsTarget", memberNameFrom: "data.secondMemberName" } },
      { source: { caseStepId: "S1-4", method: "prisma" }, id: "db.score_ledger.first.present", title: "第一个普通成员数据库积分保持一致", object: "db.score_ledger", operator: "present", params: { targetFrom: "runtime.scoreStatisticsTarget", memberNameFrom: "data.firstMemberName", pointsFrom: "data.firstMemberPoints" } },
      { source: { caseStepId: "S1-5", method: "prisma" }, id: "db.score_ledger.second.present", title: "第二个普通成员数据库积分保持一致", object: "db.score_ledger", operator: "present", params: { targetFrom: "runtime.scoreStatisticsTarget", memberNameFrom: "data.secondMemberName", pointsFrom: "data.secondMemberPoints" } },
      { source: { caseStepId: "S1-6", method: "api" }, id: "session.admin.still_authenticated", title: "当前会话 应仍为 管理员已登录", object: "auth.session", operator: "authenticated", params: { emailFrom: "data.adminEmail", roleFrom: "data.adminRole", status: "active" } },
    ],
  },

  Clean: {
    description: "删除本用例创建的积分流水、目标、账号和页面会话状态",
    steps: [
      { source: { caseStepId: "Clean-1", method: "prisma" }, id: "db.score_ledger.delete", title: "删除本用例创建的测试积分流水", object: "db.score_ledger", operator: "delete", params: { reasonFrom: "data.reason" } },
      { source: { caseStepId: "Clean-2", method: "prisma" }, id: "db.objective.delete", title: "删除本用例独占目标及其派生数据", object: "db.objective", operator: "delete", params: { idFrom: "data.objectiveId", titleFrom: "data.objectiveTitle" } },
      { source: { caseStepId: "Clean-3", method: "api" }, id: "auth.logout", title: "退出当前登录态", object: "auth", operator: "logout" },
      { source: { caseStepId: "Clean-4", method: "playwright" }, id: "page.runtime.stop", title: "停止当前页面运行态", object: "page.runtime", operator: "stop" },
      { source: { caseStepId: "Clean-5", method: "playwright" }, id: "browser.clear", title: "清空当前浏览器上下文的 cookies/localStorage/sessionStorage", object: "browser", operator: "clear_state" },
      { source: { caseStepId: "Clean-6", method: "api" }, id: "ory.admin_sessions.revoke", title: "撤销管理员登录身份的 Ory session", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-7", method: "api" }, id: "ory.first_member_sessions.revoke", title: "撤销第一个普通成员登录身份的 Ory session", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.firstMemberEmail" } },
      { source: { caseStepId: "Clean-8", method: "api" }, id: "ory.second_member_sessions.revoke", title: "撤销第二个普通成员登录身份的 Ory session", object: "ory.sessions", operator: "revoke_by_email", params: { emailFrom: "data.secondMemberEmail" } },
      { source: { caseStepId: "Clean-9", method: "api" }, id: "ory.admin_identity.delete", title: "删除管理员 Ory 身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-10", method: "api" }, id: "ory.first_member_identity.delete", title: "删除第一个普通成员 Ory 身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.firstMemberEmail" } },
      { source: { caseStepId: "Clean-11", method: "api" }, id: "ory.second_member_identity.delete", title: "删除第二个普通成员 Ory 身份", object: "ory.identity", operator: "delete_by_email", params: { emailFrom: "data.secondMemberEmail" } },
      { source: { caseStepId: "Clean-12", method: "prisma" }, id: "db.admin.delete_memberships", title: "删除管理员默认团队成员关系", object: "db.user", operator: "delete_memberships", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-13", method: "prisma" }, id: "db.first_member.delete_memberships", title: "删除第一个普通成员默认团队成员关系", object: "db.user", operator: "delete_memberships", params: { emailFrom: "data.firstMemberEmail" } },
      { source: { caseStepId: "Clean-14", method: "prisma" }, id: "db.second_member.delete_memberships", title: "删除第二个普通成员默认团队成员关系", object: "db.user", operator: "delete_memberships", params: { emailFrom: "data.secondMemberEmail" } },
      { source: { caseStepId: "Clean-15", method: "prisma" }, id: "db.admin.delete", title: "删除管理员用户", object: "db.user", operator: "delete", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-16", method: "prisma" }, id: "db.first_member.delete", title: "删除第一个普通成员用户", object: "db.user", operator: "delete", params: { emailFrom: "data.firstMemberEmail" } },
      { source: { caseStepId: "Clean-17", method: "prisma" }, id: "db.second_member.delete", title: "删除第二个普通成员用户", object: "db.user", operator: "delete", params: { emailFrom: "data.secondMemberEmail" } },
      { source: { caseStepId: "Clean-18", method: "prisma" }, id: "db.score_ledger.absent", title: "测试积分流水 应不存在", object: "db.score_ledger", operator: "absent", params: { reasonFrom: "data.reason" } },
      { source: { caseStepId: "Clean-19", method: "prisma" }, id: "db.objective.absent", title: "本用例目标 应不存在", object: "db.objective", operator: "absent", params: { idFrom: "data.objectiveId", titleFrom: "data.objectiveTitle" } },
      { source: { caseStepId: "Clean-20", method: "prisma" }, id: "db.admin.absent", title: "管理员用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.adminEmail" } },
      { source: { caseStepId: "Clean-21", method: "prisma" }, id: "db.first_member.absent", title: "第一个普通成员用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.firstMemberEmail" } },
      { source: { caseStepId: "Clean-22", method: "prisma" }, id: "db.second_member.absent", title: "第二个普通成员用户 应不存在", object: "db.user", operator: "absent", params: { emailFrom: "data.secondMemberEmail" } },
    ],
  },
} satisfies StateCaseSpec<MemberScoreStatisticsCaseData>;
